UPDATE Districts
SET ZOC = 1,
    HitPoints = 100
WHERE DistrictType IN (
    'DISTRICT_HARBOR',
    'DISTRICT_ROYAL_NAVY_DOCKYARD',
    'DISTRICT_COTHON',
    'DISTRICT_NATIONAL_HARBOR'
);

INSERT OR REPLACE INTO Districts_XP2
(DistrictType,			AttackRange)	
SELECT
DistrictType,			1
FROM Districts WHERE DistrictType IN (
    'DISTRICT_HARBOR',
    'DISTRICT_ROYAL_NAVY_DOCKYARD',
    'DISTRICT_COTHON',
    'DISTRICT_NATIONAL_HARBOR'
);