--=====
--TraitModifiers
--=====
DELETE FROM Terrain_YieldChanges WHERE TerrainType LIKE '%DESERT%';
DELETE FROM Terrain_YieldChanges WHERE TerrainType LIKE '%TUNDRA%';
DELETE FROM Terrain_YieldChanges WHERE TerrainType LIKE '%SNOW%';
--=====
--TraitModifiers
--=====
INSERT INTO TraitModifiers			
(TraitType,					ModifierId)
VALUES
('TRAIT_LEADER_MAJOR_CIV',	'GA_AMENDMENT_TERRAIN_DESERT_YIELD'),
('TRAIT_LEADER_MAJOR_CIV',	'GA_AMENDMENT_TERRAIN_DESERT_HILLS_YIELD'),
('TRAIT_LEADER_MAJOR_CIV',	'GA_AMENDMENT_TERRAIN_DESERT_MOUNTAIN_YIELD'),
('TRAIT_LEADER_MAJOR_CIV',	'GA_AMENDMENT_TERRAIN_TUNDRA_YIELD'),
('TRAIT_LEADER_MAJOR_CIV',	'GA_AMENDMENT_TERRAIN_TUNDRA_HILLS_YIELD'),
('TRAIT_LEADER_MAJOR_CIV',	'GA_AMENDMENT_TERRAIN_TUNDRA_MOUNTAIN_YIELD'),
('TRAIT_LEADER_MAJOR_CIV',	'GA_AMENDMENT_TERRAIN_SNOW_YIELD'),
('TRAIT_LEADER_MAJOR_CIV',	'GA_AMENDMENT_TERRAIN_SNOW_HILLS_YIELD'),
('TRAIT_LEADER_MAJOR_CIV',	'GA_AMENDMENT_TERRAIN_SNOW_MOUNTAIN_YIELD'),
('MINOR_CIV_DEFAULT_TRAIT',	'GA_AMENDMENT_TERRAIN_DESERT_YIELD'),
('MINOR_CIV_DEFAULT_TRAIT',	'GA_AMENDMENT_TERRAIN_DESERT_HILLS_YIELD'),
('MINOR_CIV_DEFAULT_TRAIT',	'GA_AMENDMENT_TERRAIN_DESERT_MOUNTAIN_YIELD'),
('MINOR_CIV_DEFAULT_TRAIT',	'GA_AMENDMENT_TERRAIN_TUNDRA_YIELD'),
('MINOR_CIV_DEFAULT_TRAIT',	'GA_AMENDMENT_TERRAIN_TUNDRA_HILLS_YIELD'),
('MINOR_CIV_DEFAULT_TRAIT',	'GA_AMENDMENT_TERRAIN_TUNDRA_MOUNTAIN_YIELD'),
('MINOR_CIV_DEFAULT_TRAIT',	'GA_AMENDMENT_TERRAIN_SNOW_YIELD'),
('MINOR_CIV_DEFAULT_TRAIT',	'GA_AMENDMENT_TERRAIN_SNOW_HILLS_YIELD'),
('MINOR_CIV_DEFAULT_TRAIT',	'GA_AMENDMENT_TERRAIN_SNOW_MOUNTAIN_YIELD');
--=====
--Modifiers
--=====
INSERT INTO Modifiers
(ModifierId,									ModifierType,							SubjectRequirementSetId)
VALUES			
('GA_AMENDMENT_TERRAIN_DESERT_YIELD',			'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'REQSET_GAA_PLOT_IS_DESERT'),
('GA_AMENDMENT_TERRAIN_DESERT_HILLS_YIELD',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'REQSET_GAA_PLOT_IS_DESERT_HILLS'),
('GA_AMENDMENT_TERRAIN_DESERT_MOUNTAIN_YIELD',	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'REQSET_GAA_PLOT_IS_DESERT_MOUNTAIN'),
('GA_AMENDMENT_TERRAIN_TUNDRA_YIELD',			'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'REQSET_GAA_PLOT_IS_TUNDRA'),
('GA_AMENDMENT_TERRAIN_TUNDRA_HILLS_YIELD',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'REQSET_GAA_PLOT_IS_TUNDRA_HILLS'),
('GA_AMENDMENT_TERRAIN_TUNDRA_MOUNTAIN_YIELD',	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'REQSET_GAA_PLOT_IS_TUNDRA_MOUNTAIN'),
('GA_AMENDMENT_TERRAIN_SNOW_YIELD',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'REQSET_GAA_PLOT_IS_SNOW'),
('GA_AMENDMENT_TERRAIN_SNOW_HILLS_YIELD',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'REQSET_GAA_PLOT_IS_SNOW_HILLS'),
('GA_AMENDMENT_TERRAIN_SNOW_MOUNTAIN_YIELD',	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'REQSET_GAA_PLOT_IS_SNOW_MOUNTAIN');
--=====
--ModifierArguments
--=====
INSERT INTO ModifierArguments
(ModifierId,									Name,					Value)
VALUES		
('GA_AMENDMENT_TERRAIN_DESERT_YIELD',			'YieldType',			'YIELD_FAITH,YIELD_GOLD'),		
('GA_AMENDMENT_TERRAIN_DESERT_YIELD',			'Amount',				'1,2'),
('GA_AMENDMENT_TERRAIN_DESERT_HILLS_YIELD',		'YieldType',			'YIELD_GOLD,YIELD_PRODUCTION'),		
('GA_AMENDMENT_TERRAIN_DESERT_HILLS_YIELD',		'Amount',				'2,1'),
('GA_AMENDMENT_TERRAIN_DESERT_MOUNTAIN_YIELD',	'YieldType',			'YIELD_FAITH,YIELD_GOLD,YIELD_PRODUCTION'),		
('GA_AMENDMENT_TERRAIN_DESERT_MOUNTAIN_YIELD',	'Amount',				'1,1,1'),
('GA_AMENDMENT_TERRAIN_TUNDRA_YIELD',			'YieldType',			'YIELD_FAITH,YIELD_FOOD'),		
('GA_AMENDMENT_TERRAIN_TUNDRA_YIELD',			'Amount',				'2,1'),
('GA_AMENDMENT_TERRAIN_TUNDRA_HILLS_YIELD',		'YieldType',			'YIELD_FAITH,YIELD_FOOD,YIELD_PRODUCTION'),		
('GA_AMENDMENT_TERRAIN_TUNDRA_HILLS_YIELD',		'Amount',				'1,1,1'),
('GA_AMENDMENT_TERRAIN_TUNDRA_MOUNTAIN_YIELD',	'YieldType',			'YIELD_FAITH,YIELD_GOLD,YIELD_PRODUCTION'),		
('GA_AMENDMENT_TERRAIN_TUNDRA_MOUNTAIN_YIELD',	'Amount',				'1,1,1'),
('GA_AMENDMENT_TERRAIN_SNOW_YIELD',				'YieldType',			'YIELD_FAITH'),		
('GA_AMENDMENT_TERRAIN_SNOW_YIELD',				'Amount',				3),
('GA_AMENDMENT_TERRAIN_SNOW_HILLS_YIELD',		'YieldType',			'YIELD_FAITH,YIELD_PRODUCTION'),		
('GA_AMENDMENT_TERRAIN_SNOW_HILLS_YIELD',		'Amount',				'2,1'),
('GA_AMENDMENT_TERRAIN_SNOW_MOUNTAIN_YIELD',	'YieldType',			'YIELD_FAITH,YIELD_GOLD,YIELD_PRODUCTION'),		
('GA_AMENDMENT_TERRAIN_SNOW_MOUNTAIN_YIELD',	'Amount',				'1,1,1');
--=====
--RequirementSets
--=====
INSERT INTO RequirementSets	
(RequirementSetId,						RequirementSetType)
VALUES
('REQSET_GAA_PLOT_IS_DESERT',			'REQUIREMENTSET_TEST_ALL'),
('REQSET_GAA_PLOT_IS_DESERT_HILLS',		'REQUIREMENTSET_TEST_ALL'),
('REQSET_GAA_PLOT_IS_DESERT_MOUNTAIN',	'REQUIREMENTSET_TEST_ALL'),
('REQSET_GAA_PLOT_IS_TUNDRA',			'REQUIREMENTSET_TEST_ALL'),
('REQSET_GAA_PLOT_IS_TUNDRA_HILLS',		'REQUIREMENTSET_TEST_ALL'),
('REQSET_GAA_PLOT_IS_TUNDRA_MOUNTAIN',	'REQUIREMENTSET_TEST_ALL'),
('REQSET_GAA_PLOT_IS_SNOW',				'REQUIREMENTSET_TEST_ALL'),
('REQSET_GAA_PLOT_IS_SNOW_HILLS',		'REQUIREMENTSET_TEST_ALL'),
('REQSET_GAA_PLOT_IS_SNOW_MOUNTAIN',	'REQUIREMENTSET_TEST_ALL');
--=====
--RequirementSetRequirements
--=====
INSERT INTO RequirementSetRequirements	
(RequirementSetId,						RequirementId)
VALUES
('REQSET_GAA_PLOT_IS_DESERT',			'REQ_GAA_PLOT_IS_DESERT'),
('REQSET_GAA_PLOT_IS_DESERT_HILLS',		'REQ_GAA_PLOT_IS_DESERT_HILLS'),
('REQSET_GAA_PLOT_IS_DESERT_MOUNTAIN',	'REQ_GAA_PLOT_IS_DESERT_MOUNTAIN'),
('REQSET_GAA_PLOT_IS_TUNDRA',			'REQ_GAA_PLOT_IS_TUNDRA'),
('REQSET_GAA_PLOT_IS_TUNDRA_HILLS',		'REQ_GAA_PLOT_IS_TUNDRA_HILLS'),
('REQSET_GAA_PLOT_IS_TUNDRA_MOUNTAIN',	'REQ_GAA_PLOT_IS_TUNDRA_MOUNTAIN'),
('REQSET_GAA_PLOT_IS_SNOW',				'REQ_GAA_PLOT_IS_SNOW'),
('REQSET_GAA_PLOT_IS_SNOW_HILLS',		'REQ_GAA_PLOT_IS_SNOW_HILLS'),
('REQSET_GAA_PLOT_IS_SNOW_MOUNTAIN',	'REQ_GAA_PLOT_IS_SNOW_MOUNTAIN');
--=====
--Requirements
--=====
INSERT INTO Requirements	
(RequirementId,						RequirementType)
VALUES
('REQ_GAA_PLOT_IS_DESERT',			'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES'),
('REQ_GAA_PLOT_IS_DESERT_HILLS',	'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES'),
('REQ_GAA_PLOT_IS_DESERT_MOUNTAIN',	'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES'),
('REQ_GAA_PLOT_IS_TUNDRA',			'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES'),
('REQ_GAA_PLOT_IS_TUNDRA_HILLS',	'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES'),
('REQ_GAA_PLOT_IS_TUNDRA_MOUNTAIN',	'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES'),
('REQ_GAA_PLOT_IS_SNOW',			'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES'),
('REQ_GAA_PLOT_IS_SNOW_HILLS',		'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES'),
('REQ_GAA_PLOT_IS_SNOW_MOUNTAIN',	'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES');
--=====
--RequirementArguments
--=====
INSERT INTO RequirementArguments			
(RequirementId,						Name,				Value)
VALUES
('REQ_GAA_PLOT_IS_DESERT',			'TerrainType',		'TERRAIN_DESERT'),
('REQ_GAA_PLOT_IS_DESERT_HILLS',	'TerrainType',		'TERRAIN_DESERT_HILLS'),
('REQ_GAA_PLOT_IS_DESERT_MOUNTAIN',	'TerrainType',		'TERRAIN_DESERT_MOUNTAIN'),
('REQ_GAA_PLOT_IS_TUNDRA',			'TerrainType',		'TERRAIN_TUNDRA'),
('REQ_GAA_PLOT_IS_TUNDRA_HILLS',	'TerrainType',		'TERRAIN_TUNDRA_HILLS'),
('REQ_GAA_PLOT_IS_TUNDRA_MOUNTAIN',	'TerrainType',		'TERRAIN_TUNDRA_MOUNTAIN'),
('REQ_GAA_PLOT_IS_SNOW',			'TerrainType',		'TERRAIN_SNOW'),
('REQ_GAA_PLOT_IS_SNOW_HILLS',		'TerrainType',		'TERRAIN_SNOW_HILLS'),
('REQ_GAA_PLOT_IS_SNOW_MOUNTAIN',	'TerrainType',		'TERRAIN_SNOW_MOUNTAIN');

