DELETE FROM MutuallyExclusiveBuildings WHERE Building NOT LIKE 'BUILDING_CITIPOLICY_YIELD_%' AND Building NOT LIKE 'BUILDING_CITYHALL_%';
DELETE FROM MutuallyExclusiveDistricts WHERE District != 'DISTRICT_NOTHING';

CREATE TRIGGER Trig_GA_NoExclusive_Building
AFTER INSERT ON MutuallyExclusiveBuildings
FOR EACH ROW
WHEN NEW.Building NOT LIKE 'BUILDING_CITIPOLICY_YIELD_%' AND NEW.Building NOT LIKE 'BUILDING_CITYHALL_%'
BEGIN
	DELETE FROM MutuallyExclusiveBuildings WHERE Building NOT LIKE 'BUILDING_CITIPOLICY_YIELD_%' AND Building NOT LIKE 'BUILDING_CITYHALL_%';
END;

CREATE TRIGGER Trig_GA_NoExclusive_District
AFTER INSERT ON MutuallyExclusiveDistricts
FOR EACH ROW
WHEN NEW.District != 'DISTRICT_NOTHING'
BEGIN
	DELETE FROM MutuallyExclusiveDistricts WHERE District != 'DISTRICT_NOTHING';
END;

UPDATE Districts SET Description = 'LOC_DISTRICT_NATIONAL_CAMPUS_NO_EXCLUSIVE_DESCRIPTION'
WHERE DistrictType = 'DISTRICT_NATIONAL_CAMPUS';

UPDATE Districts SET Description = 'LOC_DISTRICT_NATIONAL_HOLY_SITE_NO_EXCLUSIVE_DESCRIPTION'
WHERE DistrictType = 'DISTRICT_NATIONAL_HOLY_SITE';

UPDATE Districts SET Description = 'LOC_DISTRICT_NATIONAL_COMMERCIAL_HUB_NO_EXCLUSIVE_DESCRIPTION'
WHERE DistrictType = 'DISTRICT_NATIONAL_COMMERCIAL_HUB';

UPDATE Districts SET Description = 'LOC_DISTRICT_NATIONAL_THEATER_NO_EXCLUSIVE_DESCRIPTION'
WHERE DistrictType = 'DISTRICT_NATIONAL_THEATER';

UPDATE Districts SET Description = 'LOC_DISTRICT_NATIONAL_INDUSTRIAL_ZONE_NO_EXCLUSIVE_DESCRIPTION'
WHERE DistrictType = 'DISTRICT_NATIONAL_INDUSTRIAL_ZONE';

UPDATE Districts SET Description = 'LOC_DISTRICT_NATIONAL_ENCAMPMENT_NO_EXCLUSIVE_DESCRIPTION'
WHERE DistrictType = 'DISTRICT_NATIONAL_ENCAMPMENT';

UPDATE Districts SET Description = 'LOC_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX_NO_EXCLUSIVE_DESCRIPTION'
WHERE DistrictType = 'DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX';

UPDATE Districts SET Description = 'LOC_DISTRICT_NATIONAL_HARBOR_NO_EXCLUSIVE_DESCRIPTION'
WHERE DistrictType = 'DISTRICT_NATIONAL_HARBOR';