---Special Thanks: Sejick

INSERT INTO Types (Type, Kind) VALUES
('GA_MODE_MODIFIER_PLAYER_UNITS_ADJUST_IGNORE_TERRAIN_COST', 'KIND_MODIFIER');

INSERT INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES
('GA_MODE_MODIFIER_PLAYER_UNITS_ADJUST_IGNORE_TERRAIN_COST', 'COLLECTION_PLAYER_UNITS', 'EFFECT_ADJUST_UNIT_IGNORE_TERRAIN_COST');

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'GA_MODE_SETTLER_SPEED_BOOST'),
('TRAIT_LEADER_MAJOR_CIV', 'GA_MODE_SETTLER_IGNORE_TERRAIN'),
('TRAIT_LEADER_MAJOR_CIV', 'GA_MODE_SETTLER_IGNORE_RIVERS'),
('TRAIT_LEADER_MAJOR_CIV', 'GA_MODE_SETTLER_IGNORE_EMBARK');

INSERT INTO Modifiers (ModifierId, ModifierType, Permanent, SubjectRequirementSetId) VALUES
('GA_MODE_SETTLER_SPEED_BOOST', 'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT', 1, 'GA_MODE_SETTLER_SPEED_REQSET'),
('GA_MODE_SETTLER_IGNORE_TERRAIN', 'GA_MODE_MODIFIER_PLAYER_UNITS_ADJUST_IGNORE_TERRAIN_COST', 1, 'GA_MODE_SETTLER_SPEED_REQSET'),
('GA_MODE_SETTLER_IGNORE_RIVERS', 'MODIFIER_PLAYER_UNITS_ADJUST_IGNORE_RIVERS', 1, 'GA_MODE_SETTLER_SPEED_REQSET'),
('GA_MODE_SETTLER_IGNORE_EMBARK', 'MODIFIER_PLAYER_UNITS_ADJUST_IGNORE_SHORES', 1, 'GA_MODE_SETTLER_SPEED_REQSET');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('GA_MODE_SETTLER_SPEED_BOOST', 'Amount', 2),
('GA_MODE_SETTLER_IGNORE_TERRAIN', 'Ignore', 1),
('GA_MODE_SETTLER_IGNORE_TERRAIN', 'Type', 'ALL'),
('GA_MODE_SETTLER_IGNORE_RIVERS', 'Ignore', 1),
('GA_MODE_SETTLER_IGNORE_EMBARK', 'Ignore', 1);

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
('GA_MODE_SETTLER_SPEED_REQSET', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
('GA_MODE_SETTLER_SPEED_REQSET', 'GA_MODE_REQUIRES_UNIT_IS_SETTLER'),
('GA_MODE_SETTLER_SPEED_REQSET', 'GA_MODE_REQUIRES_NO_PALACE');

INSERT INTO Requirements (RequirementId, RequirementType, Inverse) VALUES
('GA_MODE_REQUIRES_UNIT_IS_SETTLER', 'REQUIREMENT_UNIT_TYPE_MATCHES', 0),
('GA_MODE_REQUIRES_NO_PALACE', 'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_BUILDINGS', 1);

INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES
('GA_MODE_REQUIRES_UNIT_IS_SETTLER', 'UnitType', 'UNIT_SETTLER'),
('GA_MODE_REQUIRES_NO_PALACE', 'BuildingType', 'BUILDING_PALACE'),
('GA_MODE_REQUIRES_NO_PALACE', 'Amount', 1);