--CIVILIZATION_NUBIA
--------------------------------------------------------------
-- TraitModifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
VALUES ('TRAIT_CIVILIZATION_TA_SETI' , 'GOLDEN_TRAIT_TA_SETI_MINING' );
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
VALUES ('TRAIT_CIVILIZATION_TA_SETI' , 'GOLDEN_TRAIT_TA_SETI_ARCHERY' );
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
VALUES ('TRAIT_CIVILIZATION_TA_SETI' , 'GOLDEN_TRAIT_TA_SETI_RIVER_MINE_PRODUCTION' );
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
VALUES ('TRAIT_CIVILIZATION_TA_SETI' , 'GOLDEN_TRAIT_TA_SETI_DESERT_MINE_PRODUCTION' );

INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
VALUES ('TRAIT_LEADER_KANDAKE_OF_MEROE' , 'GOLDEN_TRAIT_KANDAKE_OF_MEROE_CAMPUS_SCIENCE' );
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
VALUES ('TRAIT_LEADER_KANDAKE_OF_MEROE' , 'GOLDEN_TRAIT_KANDAKE_OF_MEROE_HOLYSITE_FAITH' );
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
VALUES ('TRAIT_LEADER_KANDAKE_OF_MEROE' , 'GOLDEN_TRAIT_KANDAKE_OF_MEROE_COMMERCIAL_HUB_GOLD' );
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
VALUES ('TRAIT_LEADER_KANDAKE_OF_MEROE' , 'GOLDEN_TRAIT_KANDAKE_OF_MEROE_THERTER_CULTURE' );
-- INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
-- VALUES ('TRAIT_LEADER_KANDAKE_OF_MEROE' , 'GOLDEN_TRAIT_KANDAKE_OF_MEROE_ENCAMPMENT_FOOD' );
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
VALUES ('TRAIT_LEADER_KANDAKE_OF_MEROE' , 'GOLDEN_TRAIT_KANDAKE_OF_MEROE_INDUSTRAIL_ZONE_PRODUCTION' );
--------------------------------------------------------------
-- Modifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES ('GOLDEN_TRAIT_TA_SETI_MINING' , 'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY' , 1 , 1 , NULL );
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES ('GOLDEN_TRAIT_TA_SETI_ARCHERY' , 'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY' , 1 , 1 , NULL );
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES ('GOLDEN_TRAIT_TA_SETI_RIVER_MINE_PRODUCTION' , 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD' , 0 , 0 , 'GOLDEN_PLOT_HAS_RIVER_MINE_REQUIREMENTS' );
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES ('GOLDEN_TRAIT_TA_SETI_DESERT_MINE_PRODUCTION' , 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD' , 0 , 0 , 'GOLDEN_PLOT_HAS_DESERT_MINE_REQUIREMENTS' );
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_CAMPUS_SCIENCE' , 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER' , 0 , 0 , 'GOLDEN_CAMPUS_HAS_FOUR_ADJACENCY_REQUIREMENTS' );
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_HOLYSITE_FAITH' , 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER' , 0 , 0 , 'GOLDEN_HOLY_SITE_HAS_FOUR_ADJACENCY_REQUIREMENTS' );
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_COMMERCIAL_HUB_GOLD' , 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER' , 0 , 0 , 'GOLDEN_COMMERCIAL_HUB_HAS_FOUR_ADJACENCY_REQUIREMENTS' );
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_THERTER_CULTURE' , 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER' , 0 , 0 , 'GOLDEN_THEATER_HAS_FOUR_ADJACENCY_REQUIREMENTS' );
-- INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
-- VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_ENCAMPMENT_FOOD' , 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER' , 0 , 0 , 'GOLDEN_ENCAMPMENT_HAS_FOUR_ADJACENCY_REQUIREMENTS' );
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_INDUSTRAIL_ZONE_PRODUCTION' , 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER' , 0 , 0 , 'GOLDEN_INDUSTRIAL_ZONE_HAS_FOUR_ADJACENCY_REQUIREMENTS' );
--------------------------------------------------------------
-- ModifierArguments
--------------------------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_TA_SETI_MINING' , 'TechType' , 'TECH_MINING'  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_TA_SETI_ARCHERY' , 'TechType' , 'TECH_ARCHERY'  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_TA_SETI_RIVER_MINE_PRODUCTION' , 'YieldType' , 'YIELD_PRODUCTION'  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_TA_SETI_RIVER_MINE_PRODUCTION' , 'Amount' , 1  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_TA_SETI_DESERT_MINE_PRODUCTION' , 'YieldType' , 'YIELD_PRODUCTION'  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_TA_SETI_DESERT_MINE_PRODUCTION' , 'Amount' , 1  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_CAMPUS_SCIENCE' , 'YieldType' , 'YIELD_SCIENCE'  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_CAMPUS_SCIENCE' , 'Amount' , 10  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_HOLYSITE_FAITH' , 'YieldType' , 'YIELD_FAITH'  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_HOLYSITE_FAITH' , 'Amount' , 10  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_COMMERCIAL_HUB_GOLD' , 'YieldType' , 'YIELD_GOLD'  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_COMMERCIAL_HUB_GOLD' , 'Amount' , 10  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_THERTER_CULTURE' , 'YieldType' , 'YIELD_CULTURE'  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_THERTER_CULTURE' , 'Amount' , 10  );
-- INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
-- VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_ENCAMPMENT_FOOD' , 'YieldType' , 'YIELD_FOOD'  );
-- INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
-- VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_ENCAMPMENT_FOOD' , 'Amount' , 10  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_INDUSTRAIL_ZONE_PRODUCTION' , 'YieldType' , 'YIELD_PRODUCTION'  );
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('GOLDEN_TRAIT_KANDAKE_OF_MEROE_INDUSTRAIL_ZONE_PRODUCTION' , 'Amount' , 10  );
UPDATE ModifierArguments SET Value = 30
WHERE ModifierId = 'TRAIT_BASE_DISTRICT_PRODUCTION_MODIFIER' AND Name = 'Amount' AND EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_NUBIAN_PITATI');
UPDATE ModifierArguments SET Value = 60
WHERE ModifierId = 'TRAIT_PYRAMID_DISTRICT_PRODUCTION_MODIFIER' AND Name = 'Amount' AND EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_NUBIAN_PITATI');
---------------------------------------------------------		
--RequirementSets
---------------------------------------------------------	
INSERT OR REPLACE INTO RequirementSets 				(RequirementSetId ,     RequirementSetType) 	VALUES 		
('GOLDEN_PLOT_HAS_RIVER_MINE_REQUIREMENTS' , 			            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLOT_HAS_DESERT_MINE_REQUIREMENTS' , 			            'REQUIREMENTSET_TEST_ALL');
---------------------------------------------------------
--RequirementSetRequirements
---------------------------------------------------------
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,   RequirementId) 			VALUES 	
('GOLDEN_PLOT_HAS_RIVER_MINE_REQUIREMENTS' , 			          'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_MINE'),
('GOLDEN_PLOT_HAS_RIVER_MINE_REQUIREMENTS' , 			          'REQUIRES_PLOT_ADJACENT_TO_RIVER'),
('GOLDEN_PLOT_HAS_DESERT_MINE_REQUIREMENTS' , 			          'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_MINE'),
('GOLDEN_PLOT_HAS_DESERT_MINE_REQUIREMENTS' , 			          'GOLDEN_REQUIRES_PLOT_HAS_DESERT_HILLS');



