--TraitModifiers
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_LEADER_NZINGA_MBANDE',	'GA_TRAIT_NZINGA_MBANDE_FREE_RESOURCE_DIAMONDS'),
('TRAIT_LEADER_NZINGA_MBANDE',	'GA_TRAIT_NZINGA_MBANDE_FREE_RESOURCE_COFFEE'),
('TRAIT_LEADER_NZINGA_MBANDE',	'GA_TRAIT_NZINGA_MBANDE_FREE_RESOURCE_COCOA'),
('TRAIT_LEADER_NZINGA_MBANDE',	'GA_TRAIT_NZINGA_MBANDE_FEATURE_NO_IMPROVEMENT_APPEAL');

----Modifiers
INSERT OR REPLACE INTO Modifiers (ModifierId, 							ModifierType, 												SubjectRequirementSetId) VALUES
('GA_TRAIT_NZINGA_MBANDE_FREE_RESOURCE_DIAMONDS',						'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT',					NULL),
('GA_TRAIT_NZINGA_MBANDE_FREE_RESOURCE_COFFEE',							'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT',					NULL),
('GA_TRAIT_NZINGA_MBANDE_FREE_RESOURCE_COCOA',							'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT',					NULL),
('GA_TRAIT_NZINGA_MBANDE_FEATURE_NO_IMPROVEMENT_APPEAL',				'MODIFIER_GOVERNOR_ADJUST_FEATURE_NO_IMPROVEMENT_APPEAL',		NULL);
--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments (ModifierId,				   				 Name,		    Value) VALUES
('GA_TRAIT_NZINGA_MBANDE_FREE_RESOURCE_DIAMONDS',									'ResourceType',	'RESOURCE_DIAMONDS'),
('GA_TRAIT_NZINGA_MBANDE_FREE_RESOURCE_DIAMONDS',									'Amount',		1),
('GA_TRAIT_NZINGA_MBANDE_FREE_RESOURCE_COFFEE',										'ResourceType',	'RESOURCE_COFFEE'),
('GA_TRAIT_NZINGA_MBANDE_FREE_RESOURCE_COFFEE',										'Amount',		1),
('GA_TRAIT_NZINGA_MBANDE_FREE_RESOURCE_COCOA',										'ResourceType',	'RESOURCE_COCOA'),
('GA_TRAIT_NZINGA_MBANDE_FREE_RESOURCE_COCOA',										'Amount',		1),
('GA_TRAIT_NZINGA_MBANDE_FEATURE_NO_IMPROVEMENT_APPEAL',							'Amount',		1);
