--文化炸弹
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_LEADER_VICTORIA_ALT',	                'GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_CULTURE_BOMB');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
('GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_CULTURE_BOMB',	                'MODIFIER_PLAYER_ADD_CULTURE_BOMB_TRIGGER',		      0, 0,                    	NULL);

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_CULTURE_BOMB',                                 'DistrictType',                 'DISTRICT_INDUSTRIAL_ZONE');


--二级建筑给5瓶子
INSERT INTO TraitModifiers 
(TraitType, 						ModifierID) 
SELECT	
'TRAIT_LEADER_VICTORIA_ALT',		'GOLDEN_TRAIT_VICTORIA_ALT_SCIENCE_FROM_'||BuildingType
FROM Buildings WHERE BuildingType = 'BUILDING_FACTORY' OR BuildingType = 'BUILDING_RAWMATERIAL' OR BuildingType = 'BUILDING_FABRICATION';

INSERT INTO Modifiers 
(ModifierId,												ModifierType) 
SELECT	
'GOLDEN_TRAIT_VICTORIA_ALT_SCIENCE_FROM_'||BuildingType,	'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'
FROM Buildings WHERE BuildingType = 'BUILDING_FACTORY' OR BuildingType = 'BUILDING_RAWMATERIAL' OR BuildingType = 'BUILDING_FABRICATION';

INSERT INTO ModifierArguments 
(ModifierId,												Name,				Value) 
SELECT	
'GOLDEN_TRAIT_VICTORIA_ALT_SCIENCE_FROM_'||BuildingType,	'BuildingType',		BuildingType
FROM Buildings WHERE BuildingType = 'BUILDING_FACTORY' OR BuildingType = 'BUILDING_RAWMATERIAL' OR BuildingType = 'BUILDING_FABRICATION';

INSERT INTO ModifierArguments 
(ModifierId,												Name,				Value) 
SELECT	
'GOLDEN_TRAIT_VICTORIA_ALT_SCIENCE_FROM_'||BuildingType,	'YieldType',		'YIELD_SCIENCE'
FROM Buildings WHERE BuildingType = 'BUILDING_FACTORY' OR BuildingType = 'BUILDING_RAWMATERIAL' OR BuildingType = 'BUILDING_FABRICATION';

INSERT INTO ModifierArguments 
(ModifierId,												Name,				Value) 
SELECT	
'GOLDEN_TRAIT_VICTORIA_ALT_SCIENCE_FROM_'||BuildingType,	'Amount',			5
FROM Buildings WHERE BuildingType = 'BUILDING_FACTORY' OR BuildingType = 'BUILDING_RAWMATERIAL' OR BuildingType = 'BUILDING_FABRICATION';

--工业区建筑给生产力
UPDATE Modifiers
SET SubjectRequirementSetId = 'REQSET_GA_BUILDING_IS_TIER_1_IZ_ENGLAND'
WHERE ModifierId = 'VICTORIA_PRODUCTION_WORKSHOP';

UPDATE Modifiers
SET SubjectRequirementSetId = 'REQSET_GA_BUILDING_IS_TIER_2_IZ_ENGLAND'
WHERE ModifierId = 'VICTORIA_PRODUCTION_FACTORY';

UPDATE Modifiers
SET SubjectRequirementSetId = 'REQSET_GA_BUILDING_IS_TIER_3_IZ_ENGLAND'
WHERE ModifierId = 'VICTORIA_PRODUCTION_POWER_PLANT';

INSERT OR REPLACE INTO RequirementSets 
(RequirementSetId, 								RequirementSetType) 
VALUES	
('REQSET_GA_BUILDING_IS_TIER_1_IZ_ENGLAND',		'REQUIREMENTSET_TEST_ANY'),
('REQSET_GA_BUILDING_IS_TIER_2_IZ_ENGLAND',		'REQUIREMENTSET_TEST_ANY'),
('REQSET_GA_BUILDING_IS_TIER_3_IZ_ENGLAND',		'REQUIREMENTSET_TEST_ANY');

INSERT OR REPLACE INTO RequirementSetRequirements 
(RequirementSetId, 								RequirementId) 
VALUES	
('REQSET_GA_BUILDING_IS_TIER_1_IZ_ENGLAND',		'REQUIRES_CITY_HAS_WORKSHOP_ENGLAND'),
('REQSET_GA_BUILDING_IS_TIER_2_IZ_ENGLAND',		'REQUIRES_CITY_HAS_FACTORY_ENGLAND'),
('REQSET_GA_BUILDING_IS_TIER_3_IZ_ENGLAND',		'REQUIRES_CITY_HAS_POWER_PLANT_ENGLAND'),
('REQSET_GA_BUILDING_IS_TIER_3_IZ_ENGLAND',		'REQUIRES_CITY_HAS_COAL_POWER_PLANT_ENGLAND'),
('REQSET_GA_BUILDING_IS_TIER_3_IZ_ENGLAND',		'REQUIRES_CITY_HAS_FOSSIL_FUEL_POWER_PLANT_ENGLAND');

---建筑拓展支持
INSERT OR REPLACE INTO RequirementSetRequirements 
(RequirementSetId, 								RequirementId) 
SELECT
'REQSET_GA_BUILDING_IS_TIER_1_IZ_ENGLAND',		'REQ_GA_ENGLAND_CITY_HAS'||BuildingType
FROM Buildings WHERE BuildingType = 'BUILDING_STONEMASON' OR BuildingType = 'BUILDING_SMELTERY';

INSERT OR REPLACE INTO RequirementSetRequirements 
(RequirementSetId, 								RequirementId) 
SELECT
'REQSET_GA_BUILDING_IS_TIER_2_IZ_ENGLAND',		'REQ_GA_ENGLAND_CITY_HAS'||BuildingType
FROM Buildings WHERE BuildingType = 'BUILDING_RAWMATERIAL' OR BuildingType = 'BUILDING_FABRICATION';

INSERT OR REPLACE INTO RequirementSetRequirements 
(RequirementSetId, 								RequirementId) 
SELECT
'REQSET_GA_BUILDING_IS_TIER_3_IZ_ENGLAND',		'REQ_GA_ENGLAND_CITY_HAS'||BuildingType
FROM Buildings WHERE BuildingType = 'BUILDING_JNR_RENEWABLE_DISTRIBUTION';

INSERT OR REPLACE INTO Requirements 
(RequirementId, 								RequirementType) 
SELECT
'REQ_GA_ENGLAND_CITY_HAS'||BuildingType,		'REQUIREMENT_CITY_HAS_BUILDING'
FROM Buildings WHERE BuildingType = 'BUILDING_STONEMASON' OR BuildingType = 'BUILDING_SMELTERY' OR BuildingType = 'BUILDING_RAWMATERIAL' OR BuildingType = 'BUILDING_FABRICATION' OR BuildingType = 'BUILDING_JNR_RENEWABLE_DISTRIBUTION';

INSERT OR REPLACE INTO RequirementArguments 
(RequirementId, 								Name,			Value) 
SELECT
'REQ_GA_ENGLAND_CITY_HAS'||BuildingType,		'BuildingType',	BuildingType
FROM Buildings WHERE BuildingType = 'BUILDING_STONEMASON' OR BuildingType = 'BUILDING_SMELTERY' OR BuildingType = 'BUILDING_RAWMATERIAL' OR BuildingType = 'BUILDING_FABRICATION' OR BuildingType = 'BUILDING_JNR_RENEWABLE_DISTRIBUTION';