--------------------------------------------------------------
-- ExcludedAdjacencies
--------------------------------------------------------------
INSERT OR REPLACE INTO ExcludedAdjacencies(YieldChangeId, TraitType) 	   
VALUES ('District_Science' , 'TRAIT_CIVILIZATION_INDONESIA_NUSANTARA' );
INSERT OR REPLACE INTO ExcludedAdjacencies(YieldChangeId, TraitType) 	   
VALUES ('District_Faith' , 'TRAIT_CIVILIZATION_INDONESIA_NUSANTARA' );
INSERT OR REPLACE INTO ExcludedAdjacencies(YieldChangeId, TraitType) 	   
VALUES ('District_Gold' , 'TRAIT_CIVILIZATION_INDONESIA_NUSANTARA' );
INSERT OR REPLACE INTO ExcludedAdjacencies(YieldChangeId, TraitType) 	   
VALUES ('District_Culture' , 'TRAIT_CIVILIZATION_INDONESIA_NUSANTARA' );
INSERT OR REPLACE INTO ExcludedAdjacencies(YieldChangeId, TraitType) 	   
VALUES ('District_Production' , 'TRAIT_CIVILIZATION_INDONESIA_NUSANTARA' );
INSERT OR REPLACE INTO ExcludedAdjacencies(YieldChangeId, TraitType) 	   
VALUES ('DISTRICT_FOOD' , 'TRAIT_CIVILIZATION_INDONESIA_NUSANTARA' );
INSERT OR REPLACE INTO ExcludedAdjacencies(YieldChangeId, TraitType) 	   
VALUES ('CITY_CENTER_CULTURE' , 'TRAIT_CIVILIZATION_INDONESIA_NUSANTARA' );
INSERT OR REPLACE INTO ExcludedAdjacencies(YieldChangeId, TraitType) 	   
VALUES ('CITY_CENTER_FAITH' , 'TRAIT_CIVILIZATION_INDONESIA_NUSANTARA' );
INSERT OR REPLACE INTO ExcludedAdjacencies(YieldChangeId, TraitType) 	   
VALUES ('CITY_CENTER_GOLD' , 'TRAIT_CIVILIZATION_INDONESIA_NUSANTARA' );
INSERT OR REPLACE INTO ExcludedAdjacencies(YieldChangeId, TraitType) 	   
VALUES ('CITY_CENTER_PRODUCTION' , 'TRAIT_CIVILIZATION_INDONESIA_NUSANTARA' );
INSERT OR REPLACE INTO ExcludedAdjacencies(YieldChangeId, TraitType) 	   
VALUES ('CITY_CENTER_SCIENCE' , 'TRAIT_CIVILIZATION_INDONESIA_NUSANTARA' );
INSERT OR REPLACE INTO ExcludedAdjacencies(YieldChangeId, TraitType) 	   
VALUES ('CITY_CENTER_FOOD' , 'TRAIT_CIVILIZATION_INDONESIA_NUSANTARA' );
------
--UA--
------
--TraitModifiers
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_INDONESIA_NUSANTARA';
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_CIVILIZATION_INDONESIA_NUSANTARA',	'TRAIT_NUSANTARA_COAST_HOLY_SITE'),--Base game
('TRAIT_CIVILIZATION_INDONESIA_NUSANTARA',	'TRAIT_NUSANTARA_COAST_CAMPUS'),--Base game
('TRAIT_CIVILIZATION_INDONESIA_NUSANTARA',	'TRAIT_NUSANTARA_COAST_INDUSTRIAL_ZONE'),--Base game
('TRAIT_CIVILIZATION_INDONESIA_NUSANTARA',	'TRAIT_NUSANTARA_COAST_THEATER'),--Base game
('TRAIT_CIVILIZATION_INDONESIA_NUSANTARA',	'TRAIT_NUSANTARA_COAST_ENTERTAINMENT'),--Base game
('TRAIT_CIVILIZATION_INDONESIA_NUSANTARA',	'GA_TRAIT_INDONESIA_ENCAMPMENT_HOUSING'),
('TRAIT_CIVILIZATION_INDONESIA_NUSANTARA' , 'GOLDEN_TRAIT_INDONESIA_NUSANTARA_COMMERCIAL_HUB_ADJACENCYGOLD' ),
('TRAIT_CIVILIZATION_INDONESIA_NUSANTARA' , 'GOLDEN_TRAIT_INDONESIA_NUSANTARA_HARBOR_ADJACENCYGOLD' ),
('TRAIT_CIVILIZATION_INDONESIA_NUSANTARA',	'GA_TRAIT_INDONESIA_FREE_CINNAMON'),
('TRAIT_CIVILIZATION_INDONESIA_NUSANTARA',	'GA_TRAIT_INDONESIA_FREE_CLOVES'),
('TRAIT_CIVILIZATION_INDONESIA_NUSANTARA',	'GA_TRAIT_INDONESIA_FREE_SPICES'),
('TRAIT_CIVILIZATION_INDONESIA_NUSANTARA',	'GA_TRAIT_INDONESIA_FISHERY_PRODUCTION'),
('TRAIT_CIVILIZATION_INDONESIA_NUSANTARA',	'GA_TRAIT_INDONESIA_FISHING_BOATS_PRODUCTION'),
('TRAIT_CIVILIZATION_INDONESIA_NUSANTARA',	'GA_TRAIT_INDONESIA_NON_COASTAL_DEBUFF');
----Modifiers
INSERT OR REPLACE INTO Modifiers (ModifierId, 						ModifierType, 													SubjectRequirementSetId) VALUES
('GOLDEN_TRAIT_INDONESIA_NUSANTARA_COMMERCIAL_HUB_ADJACENCYGOLD' , 	'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY',						NULL ),
('GOLDEN_TRAIT_INDONESIA_NUSANTARA_HARBOR_ADJACENCYGOLD' , 			'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY',						NULL ),
('GA_TRAIT_INDONESIA_ENCAMPMENT_HOUSING',							'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',						'GOLDEN_INDONESIA_ENCAMPMENT_COAST_REQUIREMENTS'),
('GA_TRAIT_INDONESIA_FREE_CINNAMON',								'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT',					NULL),
('GA_TRAIT_INDONESIA_FREE_CLOVES',									'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT',					NULL),
('GA_TRAIT_INDONESIA_FREE_SPICES',									'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT',					NULL),
('GA_TRAIT_INDONESIA_FISHERY_PRODUCTION',							'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',							'GOLDEN_PLOT_HAS_IMPROVEMENT_FISHERY_REQUIREMENTS'),
('GA_TRAIT_INDONESIA_FISHING_BOATS_PRODUCTION',						'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',							'GOLDEN_PLOT_HAS_IMPROVEMENT_FISHING_BOATS_REQUIREMENTS'),
('GA_TRAIT_INDONESIA_NON_COASTAL_DEBUFF',							'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_AMENITY',					'GA_PLOT_NOT_ADJACENT_TO_COAST_REQUIREMENTS');
--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments (ModifierId,				    Name,		    Value) VALUES
('GOLDEN_TRAIT_INDONESIA_NUSANTARA_COMMERCIAL_HUB_ADJACENCYGOLD' , 		'DistrictType' , 'DISTRICT_COMMERCIAL_HUB'  ),
('GOLDEN_TRAIT_INDONESIA_NUSANTARA_COMMERCIAL_HUB_ADJACENCYGOLD' , 		'TerrainType' , 'TERRAIN_COAST'  ),
('GOLDEN_TRAIT_INDONESIA_NUSANTARA_COMMERCIAL_HUB_ADJACENCYGOLD' , 		'YieldType' , 	'YIELD_GOLD'  ),
('GOLDEN_TRAIT_INDONESIA_NUSANTARA_COMMERCIAL_HUB_ADJACENCYGOLD' , 		'Amount' , 		1  ),
('GOLDEN_TRAIT_INDONESIA_NUSANTARA_COMMERCIAL_HUB_ADJACENCYGOLD' , 		'Description' , 'LOC_DISTRICT_NUSANTARA_GOLD'  ),
('GOLDEN_TRAIT_INDONESIA_NUSANTARA_HARBOR_ADJACENCYGOLD' , 				'DistrictType' , 'DISTRICT_HARBOR'  ),
('GOLDEN_TRAIT_INDONESIA_NUSANTARA_HARBOR_ADJACENCYGOLD' , 				'TerrainType' , 'TERRAIN_COAST'  ),
('GOLDEN_TRAIT_INDONESIA_NUSANTARA_HARBOR_ADJACENCYGOLD' , 				'YieldType' , 	'YIELD_GOLD'  ),
('GOLDEN_TRAIT_INDONESIA_NUSANTARA_HARBOR_ADJACENCYGOLD' , 				'Amount' , 1  ),
('GOLDEN_TRAIT_INDONESIA_NUSANTARA_HARBOR_ADJACENCYGOLD' , 				'Description' , 'LOC_DISTRICT_NUSANTARA_GOLD'  ),
('GA_TRAIT_INDONESIA_ENCAMPMENT_HOUSING',								'Amount',		1),
('GA_TRAIT_INDONESIA_FREE_CINNAMON',									'ResourceType',	'RESOURCE_CINNAMON'),
('GA_TRAIT_INDONESIA_FREE_CINNAMON',									'Amount',		1),
('GA_TRAIT_INDONESIA_FREE_CLOVES',										'ResourceType',	'RESOURCE_CLOVES'),
('GA_TRAIT_INDONESIA_FREE_CLOVES',										'Amount',		1),
('GA_TRAIT_INDONESIA_FREE_SPICES',										'ResourceType',	'RESOURCE_SPICES'),
('GA_TRAIT_INDONESIA_FREE_SPICES',										'Amount',		1),
('GA_TRAIT_INDONESIA_FISHERY_PRODUCTION',								'YieldType',	'YIELD_PRODUCTION'),
('GA_TRAIT_INDONESIA_FISHERY_PRODUCTION',								'Amount',		1),
('GA_TRAIT_INDONESIA_FISHING_BOATS_PRODUCTION',							'YieldType',	'YIELD_PRODUCTION'),
('GA_TRAIT_INDONESIA_FISHING_BOATS_PRODUCTION',							'Amount',		1),
('GA_TRAIT_INDONESIA_NON_COASTAL_DEBUFF',								'Amount',		-1);
UPDATE ModifierArguments SET Value = 1
WHERE ModifierId = 'TRAIT_NUSANTARA_COAST_HOLY_SITE' AND Name = 'TilesRequired';
UPDATE ModifierArguments SET Value = 1
WHERE ModifierId = 'TRAIT_NUSANTARA_COAST_CAMPUS' AND Name = 'TilesRequired';
UPDATE ModifierArguments SET Value = 1
WHERE ModifierId = 'TRAIT_NUSANTARA_COAST_INDUSTRIAL_ZONE' AND Name = 'TilesRequired';
UPDATE ModifierArguments SET Value = 1
WHERE ModifierId = 'TRAIT_NUSANTARA_COAST_THEATER' AND Name = 'TilesRequired';
--RequirementSets
INSERT OR REPLACE INTO RequirementSets 				(RequirementSetId , RequirementSetType) 	VALUES 		
('GOLDEN_INDONESIA_ENCAMPMENT_COAST_REQUIREMENTS' , 		'REQUIREMENTSET_TEST_ALL');
--RequirementSetRequirements
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId , RequirementId) 			VALUES 		
('GOLDEN_INDONESIA_ENCAMPMENT_COAST_REQUIREMENTS' , 		'GOLDEN_REQUIRES_DISTRICT_IS_DISTRICT_ENCAMPMENT'),					
('GOLDEN_INDONESIA_ENCAMPMENT_COAST_REQUIREMENTS' , 		'REQUIRES_PLOT_IS_ADJACENT_TO_COAST');
------
--LA--
------
--TraitModifiers
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_EXALTED_GODDESS';

INSERT OR REPLACE INTO TraitModifiers 
(TraitType, 						ModifierId) 
VALUES	
('TRAIT_LEADER_EXALTED_GODDESS',	'TRAIT_FAITH_CITY_CENTER'),--Base game
('TRAIT_LEADER_EXALTED_GODDESS',	'TRAIT_NAVAL_MELEE_FAITH'),--Base game
('TRAIT_LEADER_EXALTED_GODDESS',	'TRAIT_NAVAL_RANGED_FAITH'),--Base game
('TRAIT_LEADER_EXALTED_GODDESS',	'TRAIT_NAVAL_RAIDER_FAITH'),--Base game
('TRAIT_LEADER_EXALTED_GODDESS',	'TRAIT_NAVAL_CARRIER_FAITH'),--Base game
('TRAIT_LEADER_EXALTED_GODDESS',	'GOLDEN_TRAIT_INDONESIA_GOLD_CITY_CENTER'),
('TRAIT_LEADER_EXALTED_GODDESS',	'GOLDEN_TRAIT_INDONESIA_FAITH_CITY_CENTER'),
('TRAIT_LEADER_EXALTED_GODDESS',	'GOLDEN_TRAIT_INDONESIA_PURCHASE_CIVILIAN'),
('TRAIT_LEADER_EXALTED_GODDESS',	'GA_TRAIT_INDONESIA_COAST_FAITH');
----Modifiers
INSERT OR REPLACE INTO Modifiers 
(ModifierId, 									ModifierType, 											SubjectRequirementSetId)
VALUES
('GA_TRAIT_INDONESIA_COAST_FAITH',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',					'GOLDEN_PLOT_HAS_COAST_REQUIREMENTS'),
('GOLDEN_TRAIT_INDONESIA_GOLD_CITY_CENTER', 	'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',		'PLOT_IS_ADJACENT_COAST_CITY_CENTER_REQUIREMENTS'),
('GOLDEN_TRAIT_INDONESIA_FAITH_CITY_CENTER',	'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',		'PLOT_IS_ADJACENT_COAST_CITY_CENTER_REQUIREMENTS'),
('GOLDEN_TRAIT_INDONESIA_PURCHASE_CIVILIAN',	'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',	NULL);
--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,									Name,		    Value) 
VALUES
('GA_TRAIT_INDONESIA_COAST_FAITH',				'YieldType',	'YIELD_FAITH'),
('GA_TRAIT_INDONESIA_COAST_FAITH',				'Amount',		2),
('GOLDEN_TRAIT_INDONESIA_GOLD_CITY_CENTER',		'YieldType',	'YIELD_GOLD'),
('GOLDEN_TRAIT_INDONESIA_GOLD_CITY_CENTER',		'Amount',		5),
('GOLDEN_TRAIT_INDONESIA_FAITH_CITY_CENTER',	'YieldType',	'YIELD_FAITH'),
('GOLDEN_TRAIT_INDONESIA_FAITH_CITY_CENTER',	'Amount',		3),
('GOLDEN_TRAIT_INDONESIA_PURCHASE_CIVILIAN',	'Tag',			'CLASS_LANDCIVILIAN'  );