-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_TRAIT_VIETNAM_FOREST_CAMPUS'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_TRAIT_VIETNAM_FOREST_HOLY_SITE'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_TRAIT_VIETNAM_FOREST_COMMERCIAL_HUB'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_TRAIT_VIETNAM_FOREST_THEATER'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_TRAIT_VIETNAM_FOREST_INDUSTRIAL_ZONE'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_TRAIT_VIETNAM_FOREST_HARBOR'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_TRAIT_VIETNAM_JUNGLE_CAMPUS'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_TRAIT_VIETNAM_JUNGLE_HOLY_SITE'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_TRAIT_VIETNAM_JUNGLE_COMMERCIAL_HUB'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_TRAIT_VIETNAM_JUNGLE_THEATER'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_TRAIT_VIETNAM_JUNGLE_INDUSTRIAL_ZONE'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_TRAIT_VIETNAM_JUNGLE_HARBOR'),
('TRAIT_LEADER_TRIEU',	        'GOLDEN_TRAIT_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS');
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId,						ModifierType,								                                    SubjectRequirementSetId) VALUES	
('GOLDEN_TRAIT_VIETNAM_FOREST_CAMPUS',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_VIETNAM_DISTRICT_IS_CAMPUS_ADJACENT_TO_FOREST_REQUIREMENTS'),
('GOLDEN_TRAIT_VIETNAM_FOREST_HOLY_SITE',			        'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_VIETNAM_DISTRICT_IS_HOLY_SITE_ADJACENT_TO_FOREST_REQUIREMENTS'),
('GOLDEN_TRAIT_VIETNAM_FOREST_COMMERCIAL_HUB',			    'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_VIETNAM_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_TO_FOREST_REQUIREMENTS'),
('GOLDEN_TRAIT_VIETNAM_FOREST_THEATER',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_VIETNAM_DISTRICT_IS_THEATER_ADJACENT_TO_FOREST_REQUIREMENTS'),
('GOLDEN_TRAIT_VIETNAM_FOREST_INDUSTRIAL_ZONE',			    'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_VIETNAM_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_TO_FOREST_REQUIREMENTS'),
('GOLDEN_TRAIT_VIETNAM_FOREST_HARBOR',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_VIETNAM_DISTRICT_IS_HARBOR_ADJACENT_TO_FOREST_REQUIREMENTS'),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_CAMPUS',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_VIETNAM_DISTRICT_IS_CAMPUS_ADJACENT_TO_JUNGLE_REQUIREMENTS'),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_HOLY_SITE',			        'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_VIETNAM_DISTRICT_IS_HOLY_SITE_ADJACENT_TO_JUNGLE_REQUIREMENTS'),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_COMMERCIAL_HUB',			    'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_VIETNAM_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_TO_JUNGLE_REQUIREMENTS'),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_THEATER',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_VIETNAM_DISTRICT_IS_THEATER_ADJACENT_TO_JUNGLE_REQUIREMENTS'),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_INDUSTRIAL_ZONE',			    'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_VIETNAM_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_TO_JUNGLE_REQUIREMENTS'),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_HARBOR',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_VIETNAM_DISTRICT_IS_HARBOR_ADJACENT_TO_JUNGLE_REQUIREMENTS'),
('GOLDEN_TRAIT_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS',		'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',		                        NULL);
-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_TRAIT_VIETNAM_FOREST_CAMPUS',					            'YieldType',	'YIELD_SCIENCE'),
('GOLDEN_TRAIT_VIETNAM_FOREST_CAMPUS',					            'Amount',	    50),
('GOLDEN_TRAIT_VIETNAM_FOREST_HOLY_SITE',					        'YieldType',	'YIELD_FAITH'),
('GOLDEN_TRAIT_VIETNAM_FOREST_HOLY_SITE',					        'Amount',	    50),
('GOLDEN_TRAIT_VIETNAM_FOREST_COMMERCIAL_HUB',					    'YieldType',	'YIELD_GOLD'),
('GOLDEN_TRAIT_VIETNAM_FOREST_COMMERCIAL_HUB',					    'Amount',	    50),
('GOLDEN_TRAIT_VIETNAM_FOREST_THEATER',					            'YieldType',	'YIELD_CULTURE'),
('GOLDEN_TRAIT_VIETNAM_FOREST_THEATER',					            'Amount',	    50),
('GOLDEN_TRAIT_VIETNAM_FOREST_INDUSTRIAL_ZONE',					    'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_VIETNAM_FOREST_INDUSTRIAL_ZONE',					    'Amount',	    50),
('GOLDEN_TRAIT_VIETNAM_FOREST_HARBOR',					            'YieldType',	'YIELD_GOLD'),
('GOLDEN_TRAIT_VIETNAM_FOREST_HARBOR',					            'Amount',	    50),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_CAMPUS',					            'YieldType',	'YIELD_SCIENCE'),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_CAMPUS',					            'Amount',	    50),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_HOLY_SITE',					        'YieldType',	'YIELD_FAITH'),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_HOLY_SITE',					        'Amount',	    50),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_COMMERCIAL_HUB',					    'YieldType',	'YIELD_GOLD'),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_COMMERCIAL_HUB',					    'Amount',	    50),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_THEATER',					            'YieldType',	'YIELD_CULTURE'),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_THEATER',					            'Amount',	    50),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_INDUSTRIAL_ZONE',					    'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_INDUSTRIAL_ZONE',					    'Amount',	    50),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_HARBOR',					            'YieldType',	'YIELD_GOLD'),
('GOLDEN_TRAIT_VIETNAM_JUNGLE_HARBOR',					            'Amount',	    50),
('GOLDEN_TRAIT_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS',		        'AbilityType',	    'ABILITY_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS');

UPDATE ModifierArguments SET  Value = 'CIVIC_DEFENSIVE_TACTICS'
WHERE ModifierId = 'TRAIT_PLANT_MEDIEVAL_WOODS' AND Name = 'CivicType';

-----------------------------------------------
-- RequirementSets
-----------------------------------------------
INSERT OR REPLACE INTO RequirementSets		
(RequirementSetId,							    RequirementSetType) VALUES	
('GOLDEN_VIETNAM_DISTRICT_IS_CAMPUS_ADJACENT_TO_FOREST_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_VIETNAM_DISTRICT_IS_HOLY_SITE_ADJACENT_TO_FOREST_REQUIREMENTS',		    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_VIETNAM_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_TO_FOREST_REQUIREMENTS',		'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_VIETNAM_DISTRICT_IS_THEATER_ADJACENT_TO_FOREST_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_VIETNAM_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_TO_FOREST_REQUIREMENTS',		'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_VIETNAM_DISTRICT_IS_HARBOR_ADJACENT_TO_FOREST_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_VIETNAM_DISTRICT_IS_CAMPUS_ADJACENT_TO_JUNGLE_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_VIETNAM_DISTRICT_IS_HOLY_SITE_ADJACENT_TO_JUNGLE_REQUIREMENTS',		    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_VIETNAM_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_TO_JUNGLE_REQUIREMENTS',		'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_VIETNAM_DISTRICT_IS_THEATER_ADJACENT_TO_JUNGLE_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_VIETNAM_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_TO_JUNGLE_REQUIREMENTS',		'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_VIETNAM_DISTRICT_IS_HARBOR_ADJACENT_TO_JUNGLE_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL');
---------------------------------------------------------------------------------------------------------------
-- RequirementSetRequirements
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSetRequirements		
(RequirementSetId,							RequirementId) VALUES	
('GOLDEN_VIETNAM_DISTRICT_IS_CAMPUS_ADJACENT_TO_FOREST_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_CAMPUS'),
('GOLDEN_VIETNAM_DISTRICT_IS_CAMPUS_ADJACENT_TO_FOREST_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_IS_FOREST_ADJACENT'),
('GOLDEN_VIETNAM_DISTRICT_IS_HOLY_SITE_ADJACENT_TO_FOREST_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HOLY_SITE'),
('GOLDEN_VIETNAM_DISTRICT_IS_HOLY_SITE_ADJACENT_TO_FOREST_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_FOREST_ADJACENT'),
('GOLDEN_VIETNAM_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_TO_FOREST_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_COMMERCIAL_HUB'),
('GOLDEN_VIETNAM_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_TO_FOREST_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_IS_FOREST_ADJACENT'),
('GOLDEN_VIETNAM_DISTRICT_IS_THEATER_ADJACENT_TO_FOREST_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THEATER'),
('GOLDEN_VIETNAM_DISTRICT_IS_THEATER_ADJACENT_TO_FOREST_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_IS_FOREST_ADJACENT'),
('GOLDEN_VIETNAM_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_TO_FOREST_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_INDUSTRIAL_ZONE'),
('GOLDEN_VIETNAM_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_TO_FOREST_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_IS_FOREST_ADJACENT'),
('GOLDEN_VIETNAM_DISTRICT_IS_HARBOR_ADJACENT_TO_FOREST_REQUIREMENTS',	        'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HARBOR'),
('GOLDEN_VIETNAM_DISTRICT_IS_HARBOR_ADJACENT_TO_FOREST_REQUIREMENTS',	        'GOLDEN_REQUIRES_PLOT_IS_FOREST_ADJACENT'),
('GOLDEN_VIETNAM_DISTRICT_IS_CAMPUS_ADJACENT_TO_JUNGLE_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_CAMPUS'),
('GOLDEN_VIETNAM_DISTRICT_IS_CAMPUS_ADJACENT_TO_JUNGLE_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_IS_JUNGLE_ADJACENT'),
('GOLDEN_VIETNAM_DISTRICT_IS_HOLY_SITE_ADJACENT_TO_JUNGLE_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HOLY_SITE'),
('GOLDEN_VIETNAM_DISTRICT_IS_HOLY_SITE_ADJACENT_TO_JUNGLE_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_JUNGLE_ADJACENT'),
('GOLDEN_VIETNAM_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_TO_JUNGLE_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_COMMERCIAL_HUB'),
('GOLDEN_VIETNAM_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_TO_JUNGLE_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_IS_JUNGLE_ADJACENT'),
('GOLDEN_VIETNAM_DISTRICT_IS_THEATER_ADJACENT_TO_JUNGLE_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THEATER'),
('GOLDEN_VIETNAM_DISTRICT_IS_THEATER_ADJACENT_TO_JUNGLE_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_IS_JUNGLE_ADJACENT'),
('GOLDEN_VIETNAM_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_TO_JUNGLE_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_INDUSTRIAL_ZONE'),
('GOLDEN_VIETNAM_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_TO_JUNGLE_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_IS_JUNGLE_ADJACENT'),
('GOLDEN_VIETNAM_DISTRICT_IS_HARBOR_ADJACENT_TO_JUNGLE_REQUIREMENTS',	        'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HARBOR'),
('GOLDEN_VIETNAM_DISTRICT_IS_HARBOR_ADJACENT_TO_JUNGLE_REQUIREMENTS',	        'GOLDEN_REQUIRES_PLOT_IS_JUNGLE_ADJACENT');

-----------------------------------------------
-- Types
-----------------------------------------------
INSERT OR REPLACE INTO Types (Type,						Kind) VALUES
('ABILITY_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS',					'KIND_ABILITY');
-----------------------------------------------
-- TypeTags
-----------------------------------------------		
INSERT OR REPLACE INTO TypeTags (Type,									Tag) VALUES	
('ABILITY_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS',				'CLASS_LIGHT_CAVALRY'),
('ABILITY_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS',			    'CLASS_HEAVY_CAVALRY'),
('ABILITY_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS',			    'CLASS_MELEE'),
('ABILITY_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS',			    'CLASS_TRUE_RANGED'),
('ABILITY_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS',			    'CLASS_SIEGE'),
('ABILITY_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS',			    'CLASS_RECON'),
('ABILITY_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS',			    'CLASS_ANTI_CAVALRY');
INSERT OR REPLACE INTO TypeTags (Type, Tag) SELECT 'ABILITY_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS', 'CLASS_AUTOMATIC_GUN' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_COMPOSITE_BOWMAN');
-----------------------------------------------
-- UnitAbilities
-----------------------------------------------
INSERT OR REPLACE INTO UnitAbilities (UnitAbilityType,						Name,									Description, Inactive) VALUES	
('ABILITY_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS',			'LOC_ABILITY_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS_NAME',	'LOC_ABILITY_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS_DESCRIPTION', 1);
-----------------------------------------------
-- UnitAbilityModifiers
-----------------------------------------------
INSERT OR REPLACE INTO UnitAbilityModifiers (UnitAbilityType,						ModifierId) VALUES	
('ABILITY_TRIEU_GREAT_GENERAL_INFLUENCE_BONUS',			            'WOLIN_GREAT_GENERAL_POINTS');
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId,		ModifierType,								                                    					SubjectRequirementSetId) VALUES	
('WOLIN_GREAT_GENERAL_POINTS',			            'GOLDEN_MODIFIER_PLAYER_ADJUST_UNITS_GREAT_PEOPLE_POINTS_PER_KILL_BY_DEFEATED_STRENGTH',		    NULL);
-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        		Value) VALUES
('WOLIN_GREAT_GENERAL_POINTS',					    'Amount',	    			25),
('WOLIN_GREAT_GENERAL_POINTS',					    'GreatPersonClassType',	    'GREAT_PERSON_CLASS_GENERAL');
--UD
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_THANH_FARM_HOUSING'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_THANH_PASTURE_HOUSING'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_THANH_PLANTATION_HOUSING'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_THANH_CAMP_HOUSING'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_THANH_CANAL_HOUSING'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_THANH_AERODROME_HOUSING'),
('TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_THANH_GOVERNMENT_HOUSING');

INSERT OR REPLACE INTO Modifiers (ModifierId,						ModifierType,								                                    SubjectRequirementSetId) VALUES	
('GOLDEN_THANH_FARM_HOUSING',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_FARM_REQUIREMENTS'),
('GOLDEN_THANH_PASTURE_HOUSING',			        'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_PASTURE_REQUIREMENTS'),
('GOLDEN_THANH_PLANTATION_HOUSING',			        'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_PLANTATION_REQUIREMENTS'),
('GOLDEN_THANH_CAMP_HOUSING',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_CAMP_REQUIREMENTS'),
('GOLDEN_THANH_CANAL_HOUSING',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_CANAL_REQUIREMENTS'),
('GOLDEN_THANH_AERODROME_HOUSING',			        'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_AERODROME_REQUIREMENTS'),
('GOLDEN_THANH_GOVERNMENT_HOUSING',			        'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_GOVERNMENT_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_THANH_FARM_HOUSING',					            'Amount',	    1),
('GOLDEN_THANH_PASTURE_HOUSING',					        'Amount',	    1),
('GOLDEN_THANH_PLANTATION_HOUSING',					        'Amount',	    1),
('GOLDEN_THANH_CAMP_HOUSING',					            'Amount',	    1),
('GOLDEN_THANH_CANAL_HOUSING',					            'Amount',	    1),
('GOLDEN_THANH_AERODROME_HOUSING',					        'Amount',	    1),
('GOLDEN_THANH_GOVERNMENT_HOUSING',					        'Amount',	    1);

INSERT OR REPLACE INTO RequirementSets		(RequirementSetId,							RequirementSetType) VALUES
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_FARM_REQUIREMENTS',		                'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_PASTURE_REQUIREMENTS',		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_PLANTATION_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_CAMP_REQUIREMENTS',		                'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_CANAL_REQUIREMENTS',		                'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_AERODROME_REQUIREMENTS',		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements		(RequirementSetId,							RequirementId) VALUES	
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_FARM_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THANH'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_FARM_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_FARM'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_PASTURE_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THANH'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_PASTURE_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_PASTURE'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_PLANTATION_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THANH'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_PLANTATION_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_PLANTATION'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_CAMP_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THANH'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_CAMP_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_CAMP'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_CANAL_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THANH'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_CANAL_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_CANAL'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_AERODROME_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THANH'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_AERODROME_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_AERODROME'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THANH'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_GOVERNMENT');

INSERT OR REPLACE INTO Requirements (RequirementId,			RequirementType) VALUES	 
('GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THANH',	               'REQUIREMENT_DISTRICT_TYPE_MATCHES');

INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) VALUES
('GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THANH',		        'DistrictType',	    'DISTRICT_THANH');