--------------------------------------------------------------
-- TraitModifiers
--------------------------------------------------------------
DELETE FROM TraitModifiers WHERE ModifierId = 'TRAIT_ANTIQUES_AND_PARKS_CULTURE_FORESTS_OR_WONDERS';
DELETE FROM TraitModifiers WHERE ModifierId = 'TRAIT_ANTIQUES_AND_PARKS_SCIENCE_NATIONAL_WONDERS_OR_MOUNTAINS';
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
VALUES 
('TRAIT_LEADER_ANTIQUES_AND_PARKS' , 'GOLDEN_TRAIT_ANTIQUES_AND_PARKS_CULTURE_FORESTS_OR_WONDERS' ),--与自然奇观或树林相邻的单元格，魅力值为“惊艳”则+1文化值。
('TRAIT_LEADER_ANTIQUES_AND_PARKS' , 'GOLDEN_TRAIT_ANTIQUES_AND_PARKS_GOLD_FORESTS_OR_WONDERS' ),--与世界奇观或树林相邻的单元格，魅力值为“迷人”以上则+1金币
('TRAIT_LEADER_ANTIQUES_AND_PARKS' , 'GOLDEN_TRAIT_ANTIQUES_AND_PARKS_SCIENCE_NATURAL_WONDERS_OR_MOUNTAINS' ),--与自然奇观或山脉相邻的单元格，魅力值为“惊艳”则+1科技值。
('TRAIT_LEADER_ANTIQUES_AND_PARKS' , 'GOLDEN_TRAIT_ANTIQUES_AND_PARKS_GOLD_NATURAL_WONDERS_OR_MOUNTAINS' ),--与自然奇观或山脉相邻的单元格，魅力值为“迷人”以上则+1金币
('TRAIT_LEADER_ANTIQUES_AND_PARKS' , 'GOLDEN_TRAIT_ANTIQUES_AND_PARKS_FREE_UNIT_NATURALIST' ),--解锁“保护地球”后，拥有自然奇观的城市获得2个免费的自然学家。
('TRAIT_LEADER_ANTIQUES_AND_PARKS' , 'GOLDEN_TRAIT_ANTIQUES_AND_PARKS_NATURAL_WONDER_APPEAL' );--。拥有自然奇观的城市的所有单元格分别+1魅力。
--------------------------------------------------------------
-- Modifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES 
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_CULTURE_FORESTS_OR_WONDERS' , 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD' , 0 , 0 , 'GOLDEN_PLOT_ADJACENT_FORESTS_OR_WONDERS_BREATHTAKING_REQUIREMENTS' ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_GOLD_FORESTS_OR_WONDERS' , 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD' , 0 , 0 , 'GOLDEN_PLOT_ADJACENT_FORESTS_OR_WONDERS_CHARMING_REQUIREMENTS' ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_SCIENCE_NATURAL_WONDERS_OR_MOUNTAINS' , 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD' , 0 , 0 , 'GOLDEN_PLOT_ADJACENT_NATURAL_WONDERS_OR_MOUNTAINS_BREATHTAKING_REQUIREMENTS' ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_GOLD_NATURAL_WONDERS_OR_MOUNTAINS' , 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD' , 0 , 0 , 'GOLDEN_PLOT_ADJACENT_NATURAL_WONDERS_OR_MOUNTAINS_CHARMING_REQUIREMENTS' ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_FREE_UNIT_NATURALIST' , 'MODIFIER_PLAYER_BUILT_CITIES_GRANT_FREE_UNIT' , 0 , 0 , 'GOLDEN_PLAYER_HAS_CIVIC_CONSERVATION_CITY_HAS_NATURAL_WONDER_REQUIREMENTS' ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_NATURAL_WONDER_APPEAL' , 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_APPEAL' , 0 , 0 , 'GOLDEN_AMERICA_CITY_HAS_NATURAL_WONDER' );
--------------------------------------------------------------
-- ModifierArguments
--------------------------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES 
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_CULTURE_FORESTS_OR_WONDERS' , 'YieldType' , 'YIELD_CULTURE'  ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_CULTURE_FORESTS_OR_WONDERS' , 'Amount' , 1  ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_GOLD_FORESTS_OR_WONDERS' , 'YieldType' , 'YIELD_GOLD'  ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_GOLD_FORESTS_OR_WONDERS' , 'Amount' , 1  ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_SCIENCE_NATURAL_WONDERS_OR_MOUNTAINS' , 'YieldType' , 'YIELD_SCIENCE'  ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_SCIENCE_NATURAL_WONDERS_OR_MOUNTAINS' , 'Amount' , 1  ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_GOLD_NATURAL_WONDERS_OR_MOUNTAINS' , 'YieldType' , 'YIELD_GOLD'  ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_GOLD_NATURAL_WONDERS_OR_MOUNTAINS' , 'Amount' , 1  ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_FREE_UNIT_NATURALIST' , 'UnitType' , 'UNIT_NATURALIST'  ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_FREE_UNIT_NATURALIST' , 'Amount' , 2  ),
('GOLDEN_TRAIT_ANTIQUES_AND_PARKS_NATURAL_WONDER_APPEAL' , 'Amount' , 1  );
---------------------------------------------------------------------------------------------------------------
-- RequirementSets
---------------------------------------------------------------------------------------------------------------
INSERT INTO RequirementSets
(RequirementSetId,										RequirementSetType) VALUES	
('GOLDEN_AMERICA_CITY_HAS_NATURAL_WONDER',					                            'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_AMERICA_ADJACENT_NATURAL_WONDER_MOUNTAIN',	                            'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_AMERICA_ADJACENT_WONDER_WOODS',				                            'REQUIREMENTSET_TEST_ANY'),

('GOLDEN_PLOT_ADJACENT_NATURAL_WONDERS_OR_MOUNTAINS_BREATHTAKING_REQUIREMENTS',	'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLOT_ADJACENT_FORESTS_OR_WONDERS_BREATHTAKING_REQUIREMENTS',	            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLOT_ADJACENT_NATURAL_WONDERS_OR_MOUNTAINS_CHARMING_REQUIREMENTS',	'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLOT_ADJACENT_FORESTS_OR_WONDERS_CHARMING_REQUIREMENTS',	            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLAYER_HAS_CIVIC_CONSERVATION_CITY_HAS_NATURAL_WONDER_REQUIREMENTS',	        'REQUIREMENTSET_TEST_ALL');
---------------------------------------------------------------------------------------------------------------					
-- RequirementSetRequirements
---------------------------------------------------------------------------------------------------------------
INSERT INTO RequirementSetRequirements
(RequirementSetId,						RequirementId) SELECT	
'GOLDEN_AMERICA_CITY_HAS_NATURAL_WONDER',	'GOLDEN_AMERICA_REQUIRES_CITY_HAS_' ||FeatureType FROM Features WHERE NaturalWonder = 1;

INSERT INTO RequirementSetRequirements
(RequirementSetId,										RequirementId) VALUES	
('GOLDEN_AMERICA_ADJACENT_NATURAL_WONDER_MOUNTAIN',				'REQUIRES_PLOT_ADJACENT_TO_NATURAL_WONDER'),
('GOLDEN_AMERICA_ADJACENT_NATURAL_WONDER_MOUNTAIN',				'REQUIRES_PLOT_ADJACENT_TO_MOUNTAIN'),
('GOLDEN_AMERICA_ADJACENT_WONDER_WOODS',				'REQUIRES_PLOT_ADJACENT_TO_WONDER'),
('GOLDEN_AMERICA_ADJACENT_WONDER_WOODS',				'REQUIRES_PLOT_ADJACENT_FOREST_ROOSEVELT'),
('GOLDEN_PLOT_ADJACENT_NATURAL_WONDERS_OR_MOUNTAINS_BREATHTAKING_REQUIREMENTS',	'GOLDEN_REQUIRES_BREATHTAKING_APPEAL'),
('GOLDEN_PLOT_ADJACENT_NATURAL_WONDERS_OR_MOUNTAINS_BREATHTAKING_REQUIREMENTS',	'GOLDEN_AMERICA_ADJACENT_SCIENCE_FEATURES_MET'),
('GOLDEN_PLOT_ADJACENT_NATURAL_WONDERS_OR_MOUNTAINS_CHARMING_REQUIREMENTS',	'GOLDEN_REQUIRES_CHARMING_APPEAL'),
('GOLDEN_PLOT_ADJACENT_NATURAL_WONDERS_OR_MOUNTAINS_CHARMING_REQUIREMENTS',	'GOLDEN_AMERICA_ADJACENT_SCIENCE_FEATURES_MET'),
('GOLDEN_PLOT_ADJACENT_FORESTS_OR_WONDERS_BREATHTAKING_REQUIREMENTS',	            'GOLDEN_REQUIRES_BREATHTAKING_APPEAL'),
('GOLDEN_PLOT_ADJACENT_FORESTS_OR_WONDERS_BREATHTAKING_REQUIREMENTS',	            'GOLDEN_AMERICA_ADJACENT_CULTURE_FEATURES_MET'),
('GOLDEN_PLOT_ADJACENT_FORESTS_OR_WONDERS_CHARMING_REQUIREMENTS',	            'GOLDEN_REQUIRES_CHARMING_APPEAL'),
('GOLDEN_PLOT_ADJACENT_FORESTS_OR_WONDERS_CHARMING_REQUIREMENTS',	            'GOLDEN_AMERICA_ADJACENT_CULTURE_FEATURES_MET'),
('GOLDEN_PLAYER_HAS_CIVIC_CONSERVATION_CITY_HAS_NATURAL_WONDER_REQUIREMENTS',	        'GOLDEN_REQUIRES_PLAYER_HAS_CIVIC_CONSERVATION'),
('GOLDEN_PLAYER_HAS_CIVIC_CONSERVATION_CITY_HAS_NATURAL_WONDER_REQUIREMENTS',	        'GOLDEN_AMERICA_CITY_HAS_NATURAL_WONDER_MET');
---------------------------------------------------------------------------------------------------------------
-- Requirements
---------------------------------------------------------------------------------------------------------------
INSERT INTO Requirements
(RequirementId,									RequirementType) SELECT	'GOLDEN_AMERICA_REQUIRES_CITY_HAS_' ||FeatureType,	'REQUIREMENT_CITY_HAS_FEATURE' FROM Features WHERE NaturalWonder = 1;

INSERT INTO Requirements
(RequirementId,											RequirementType) VALUES	
('GOLDEN_AMERICA_ADJACENT_SCIENCE_FEATURES_MET',			'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_AMERICA_ADJACENT_CULTURE_FEATURES_MET',			'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_AMERICA_CITY_HAS_NATURAL_WONDER_MET',			    'REQUIREMENT_REQUIREMENTSET_IS_MET');
---------------------------------------------------------------------------------------------------------------
-- RequirementArguments
---------------------------------------------------------------------------------------------------------------
INSERT INTO RequirementArguments
(RequirementId,									Name,			Value) SELECT	'GOLDEN_AMERICA_REQUIRES_CITY_HAS_' ||FeatureType,	'FeatureType',	FeatureType FROM Features WHERE NaturalWonder = 1;

INSERT INTO RequirementArguments
(RequirementId,									Name,				Value) VALUES	
('GOLDEN_AMERICA_ADJACENT_SCIENCE_FEATURES_MET',	'RequirementSetId',	'GOLDEN_AMERICA_ADJACENT_NATURAL_WONDER_MOUNTAIN'),
('GOLDEN_AMERICA_ADJACENT_CULTURE_FEATURES_MET',	'RequirementSetId',	'GOLDEN_AMERICA_ADJACENT_WONDER_WOODS'),
('GOLDEN_AMERICA_CITY_HAS_NATURAL_WONDER_MET',	    'RequirementSetId',	'GOLDEN_AMERICA_CITY_HAS_NATURAL_WONDER');
---------------------------------------------------------------------------------------------------------------
-- 莽骑兵
---------------------------------------------------------------------------------------------------------------
UPDATE RequirementArguments SET Value = 'LEADER_T_ROOSEVELT_ROUGHRIDER'
WHERE RequirementId = 'GOLDEN_AMERICA_REQUIRES_LEADER_IS_T_ROOSEVELT' AND Name = 'LeaderType';