------
--UA--
------
--TraitModifiers
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_SATRAPIES';
INSERT OR REPLACE INTO TraitModifiers 
(TraitType, 						ModifierId) VALUES	
('TRAIT_CIVILIZATION_SATRAPIES',	'TRAIT_SATRAPIES_IMPROVED_ROUTE_LEVEL'),				--Base game
('TRAIT_CIVILIZATION_SATRAPIES',	'TRAIT_SATRAPIES_POLITICAL_PHILOSOPHY_TRADE_ROUTE'),	--Base game
('TRAIT_CIVILIZATION_SATRAPIES',	'GOLDEN_TRAIT_GOLD_PURCHASE_DISTRICTS'),
('TRAIT_CIVILIZATION_SATRAPIES',	'GA_TRAIT_SATRAPIES_POLITICAL_PHILOSOPHY_GOVERNOR_TITLE'),
('TRAIT_CIVILIZATION_SATRAPIES',	'GA_TRAIT_SATRAPIES_DISTRICT_ERA_SCORE'),
('TRAIT_CIVILIZATION_SATRAPIES',	'GA_TRAIT_SATRAPIES_GOLDEN_ERA_TILE_GOLD'),
('TRAIT_CIVILIZATION_SATRAPIES',	'GA_TRAIT_SATRAPIES_DARK_ERA_LOYALTY');

----Modifiers
INSERT OR REPLACE INTO Modifiers (ModifierId, 					ModifierType, 															RunOnce, 	Permanent, 	OwnerRequirementSetId,	SubjectRequirementSetId) VALUES
('GOLDEN_TRAIT_GOLD_PURCHASE_DISTRICTS' , 						'GOLDEN_MODIFIER_PLAYER_CITIES_ADJUST_CAN_PURCHASE_DISTRICTS' , 		0,			0,			NULL,					NULL),
('GA_TRAIT_SATRAPIES_POLITICAL_PHILOSOPHY_GOVERNOR_TITLE',		'MODIFIER_PLAYER_ADJUST_GOVERNOR_POINTS',								1,			1,			NULL,					'PLAYER_HAS_POLITICAL_PHILOSOPHY'),
('GA_TRAIT_SATRAPIES_DISTRICT_ERA_SCORE',						'MODIFIER_PLAYER_ADJUST_PLAYER_ERA_SCORE_PER_DISTRICT_CONSTRUCTED',		0,			0,			NULL,					NULL),
('GA_TRAIT_SATRAPIES_GOLDEN_ERA_TILE_GOLD',						'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									0,			0,			NULL,					'PLAYER_HAS_GOLDEN_AGE'),
('GA_TRAIT_SATRAPIES_DARK_ERA_LOYALTY',							'MODIFIER_PLAYER_CITIES_ADJUST_IDENTITY_PER_TURN',						0,			0,			'PLAYER_HAS_DARK_AGE',	'CITY_NOT_FOUNDED');


--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,	Name,		    Value) VALUES
('GOLDEN_TRAIT_GOLD_PURCHASE_DISTRICTS' , 						'CanPurchase' , 1),
('GA_TRAIT_SATRAPIES_POLITICAL_PHILOSOPHY_GOVERNOR_TITLE',		'Delta',		2),
('GA_TRAIT_SATRAPIES_DISTRICT_ERA_SCORE',						'Amount',		1),
('GA_TRAIT_SATRAPIES_GOLDEN_ERA_TILE_GOLD',						'YieldType',	'YIELD_GOLD'),
('GA_TRAIT_SATRAPIES_GOLDEN_ERA_TILE_GOLD',						'Amount',		1),
('GA_TRAIT_SATRAPIES_DARK_ERA_LOYALTY',							'Amount',		-4);

UPDATE ModifierArguments SET Value = 2
WHERE ModifierId = 'TRAIT_SATRAPIES_POLITICAL_PHILOSOPHY_TRADE_ROUTE' AND Name = 'Amount';

------
--LA--
------
--TraitModifiers
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_LEADER_FALL_BABYLON',	'GOLDEN_TRAIT_FALL_BABYLON_FREE_MELEE_UNITS'),
('TRAIT_LEADER_FALL_BABYLON' , 	'GOLDEN_TRAIT_SURPRISE_WAR_COMBAT' );
----Modifiers
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
('GOLDEN_TRAIT_FALL_BABYLON_FREE_MELEE_UNITS',         	'MODIFIER_PLAYER_CITIES_GRANT_UNIT_BY_CLASS',        	0, 0, 'CITY_NOT_FOUNDED'),
('GOLDEN_TRAIT_SURPRISE_WAR_COMBAT' ,				 	'MODIFIER_PLAYER_ADD_DIPLOMATIC_COMBAT_MODIFIER' , 		0, 0, NULL  );
--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_TRAIT_FALL_BABYLON_FREE_MELEE_UNITS',					'UnitPromotionClassType',	'PROMOTION_CLASS_MELEE'),
('GOLDEN_TRAIT_SURPRISE_WAR_COMBAT' , 							'DiplomaticYieldSource' , 	'SURPRISE_WAR_INITIATED'  ),
('GOLDEN_TRAIT_SURPRISE_WAR_COMBAT' , 							'TurnsActive' , 			10  ),
('GOLDEN_TRAIT_SURPRISE_WAR_COMBAT' , 							'Amount' , 					5  ),
('GOLDEN_TRAIT_SURPRISE_WAR_COMBAT' , 							'ReligiousOnly' , 			0  );

UPDATE ModifierArguments SET Value = 6 WHERE ModifierId = 'TRAIT_ADDITIONAL_MARTIAL_LAW';