--CIVILIZATION_AUSTRALIA
--------------------------------------------------------------
-- ExcludedAdjacencies
--------------------------------------------------------------
INSERT OR REPLACE INTO ExcludedAdjacencies(YieldChangeId, TraitType) 	VALUES   
('District_Science', 'TRAIT_CIVILIZATION_LAND_DOWN_UNDER'),
('District_Faith', 'TRAIT_CIVILIZATION_LAND_DOWN_UNDER'),
('District_Gold', 'TRAIT_CIVILIZATION_LAND_DOWN_UNDER'),
('District_Culture', 'TRAIT_CIVILIZATION_LAND_DOWN_UNDER'),
('District_Production', 'TRAIT_CIVILIZATION_LAND_DOWN_UNDER'),
('DISTRICT_FOOD', 'TRAIT_CIVILIZATION_LAND_DOWN_UNDER'),
('CITY_CENTER_CULTURE', 'TRAIT_CIVILIZATION_LAND_DOWN_UNDER'),
('CITY_CENTER_FAITH', 'TRAIT_CIVILIZATION_LAND_DOWN_UNDER'),
('CITY_CENTER_GOLD', 'TRAIT_CIVILIZATION_LAND_DOWN_UNDER'),
('CITY_CENTER_PRODUCTION', 'TRAIT_CIVILIZATION_LAND_DOWN_UNDER'),
('CITY_CENTER_SCIENCE', 'TRAIT_CIVILIZATION_LAND_DOWN_UNDER'),
('CITY_CENTER_FOOD', 'TRAIT_CIVILIZATION_LAND_DOWN_UNDER');
--------------------------------------------------------------
-- TraitModifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)VALUES
('TRAIT_CIVILIZATION_LAND_DOWN_UNDER', 'GOLDEN_TRAIT_CHARMING_INDUSTRIAL_ZONE'),
('TRAIT_CIVILIZATION_LAND_DOWN_UNDER', 'GOLDEN_TRAIT_BREATHTAKING_INDUSTRIAL_ZONE'),
('TRAIT_CIVILIZATION_LAND_DOWN_UNDER', 'GOLDEN_TRAIT_LAND_DOWN_UNDER_ADJUST_RESOURCE_HARVEST_BONUS'),
('TRAIT_LEADER_CITADEL_CIVILIZATION', 'GOLDEN_TRAIT_CITADELCIVILIZATION_DEFENSIVE_MOVEMENT'),
('TRAIT_LEADER_CITADEL_CIVILIZATION', 'GOLDEN_TRAIT_CITADELCIVILIZATION_DEFENSIVE_COMBAT'),
('TRAIT_LEADER_CITADEL_CIVILIZATION', 'GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_ORIGIN_SCIENCE'),
('TRAIT_LEADER_CITADEL_CIVILIZATION', 'GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_ORIGIN_CULTURE'),
('TRAIT_LEADER_CITADEL_CIVILIZATION', 'GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_DESTINATION_SCIENCE'),
('TRAIT_LEADER_CITADEL_CIVILIZATION', 'GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_DESTINATION_CULTURE'),
('TRAIT_LEADER_CITADEL_CIVILIZATION', 'TRAIT_ADJUST_JOINTWAR_EXPERIENCE'),
('TRAIT_LEADER_CITADEL_CIVILIZATION', 'TRAIT_ADJUST_JOINTWAR_PLUNDER'),
('TRAIT_LEADER_CITADEL_CIVILIZATION', 'TRAIT_ALLIANCE_POINTS_FROM_COMMON_FOE');

DELETE FROM TraitModifiers WHERE ModifierId = 'TRAIT_CITADELCIVILIZATION_LIBERATION_PRODUCTION';
DELETE FROM TraitModifiers WHERE ModifierId = 'TRAIT_COASTAL_HOUSING';
DELETE FROM TraitModifiers WHERE ModifierId = 'TRAIT_CULTURE_BOMB_TRIGGER_PASTURE';
--------------------------------------------------------------
-- Modifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)VALUES
('GOLDEN_TRAIT_CHARMING_INDUSTRIAL_ZONE', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL', 0, 0, NULL),
('GOLDEN_TRAIT_BREATHTAKING_INDUSTRIAL_ZONE', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL', 0, 0, NULL),
('GOLDEN_TRAIT_LAND_DOWN_UNDER_ADJUST_RESOURCE_HARVEST_BONUS', 'GOLDEN_MODIFIER_PLAYER_CITIES_ADJUST_RESOURCE_HARVEST_BONUS', 0, 0, NULL),
('GOLDEN_TRAIT_CITADELCIVILIZATION_DEFENSIVE_MOVEMENT', 'MODIFIER_PLAYER_ADD_DIPLOMATIC_MOVEMENT_MODIFIER', 0, 0, NULL),
('GOLDEN_TRAIT_CITADELCIVILIZATION_DEFENSIVE_COMBAT', 'MODIFIER_PLAYER_ADD_DIPLOMATIC_COMBAT_MODIFIER', 0, 0, NULL),
('GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_ORIGIN_SCIENCE', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_ORIGIN_YIELD_FOR_ALLY_ROUTE', 0, 0, NULL),
('GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_ORIGIN_CULTURE', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_ORIGIN_YIELD_FOR_ALLY_ROUTE', 0, 0, NULL),
('GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_DESTINATION_SCIENCE', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_DESTINATION_YIELD_FOR_ALLY_ROUTE', 0, 0, NULL),
('GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_DESTINATION_CULTURE', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_DESTINATION_YIELD_FOR_ALLY_ROUTE', 0, 0, NULL);
--------------------------------------------------------------
-- ModifierArguments
--------------------------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)VALUES
('GOLDEN_TRAIT_CHARMING_INDUSTRIAL_ZONE', 'YieldType', 'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_CHARMING_INDUSTRIAL_ZONE', 'RequiredAppeal', 2),
('GOLDEN_TRAIT_CHARMING_INDUSTRIAL_ZONE', 'YieldChange', 2),
('GOLDEN_TRAIT_CHARMING_INDUSTRIAL_ZONE', 'DistrictType', 'DISTRICT_INDUSTRIAL_ZONE'),
('GOLDEN_TRAIT_CHARMING_INDUSTRIAL_ZONE', 'Description', 'LOC_DISTRICT_APPEAL_PRODUCTION'),
('GOLDEN_TRAIT_BREATHTAKING_INDUSTRIAL_ZONE', 'YieldType', 'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_BREATHTAKING_INDUSTRIAL_ZONE', 'RequiredAppeal', 4),
('GOLDEN_TRAIT_BREATHTAKING_INDUSTRIAL_ZONE', 'YieldChange', 2),
('GOLDEN_TRAIT_BREATHTAKING_INDUSTRIAL_ZONE', 'DistrictType', 'DISTRICT_INDUSTRIAL_ZONE'),
('GOLDEN_TRAIT_BREATHTAKING_INDUSTRIAL_ZONE', 'Description', 'LOC_DISTRICT_APPEAL_PRODUCTION'),
('GOLDEN_TRAIT_LAND_DOWN_UNDER_ADJUST_RESOURCE_HARVEST_BONUS', 'Amount', 100),
('GOLDEN_TRAIT_CITADELCIVILIZATION_DEFENSIVE_MOVEMENT', 'DiplomaticYieldSource', 'WAR_DECLARATION_RECEIVED'),
('GOLDEN_TRAIT_CITADELCIVILIZATION_DEFENSIVE_MOVEMENT', 'TurnsActive', 10),
('GOLDEN_TRAIT_CITADELCIVILIZATION_DEFENSIVE_MOVEMENT', 'Amount', 2),
('GOLDEN_TRAIT_CITADELCIVILIZATION_DEFENSIVE_COMBAT', 'DiplomaticYieldSource', 'WAR_DECLARATION_RECEIVED'),
('GOLDEN_TRAIT_CITADELCIVILIZATION_DEFENSIVE_COMBAT', 'TurnsActive', 10),
('GOLDEN_TRAIT_CITADELCIVILIZATION_DEFENSIVE_COMBAT', 'Amount', 5),
('GOLDEN_TRAIT_CITADELCIVILIZATION_DEFENSIVE_COMBAT', 'ReligiousOnly', 0),
('GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_ORIGIN_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
('GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_ORIGIN_SCIENCE', 'Amount', 1),
('GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_ORIGIN_CULTURE', 'YieldType', 'YIELD_CULTURE'),
('GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_ORIGIN_CULTURE', 'Amount', 1),
('GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_DESTINATION_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
('GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_DESTINATION_SCIENCE', 'Amount', 1),
('GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_DESTINATION_CULTURE', 'YieldType', 'YIELD_CULTURE'),
('GOLDEN_TRAIT_CITADELCIVILIZATION_TRADEROUTE_DESTINATION_CULTURE', 'Amount', 1);
UPDATE ModifierArguments SET Value = 2
WHERE ModifierId = 'TRAIT_CHARMING_CAMPUS' AND Name = 'YieldChange';
UPDATE ModifierArguments SET Value = 2
WHERE ModifierId = 'TRAIT_CHARMING_COMMERCIAL_HUB' AND Name = 'YieldChange';
UPDATE ModifierArguments SET Value = 2
WHERE ModifierId = 'TRAIT_CHARMING_HOLY_SITE' AND Name = 'YieldChange';
UPDATE ModifierArguments SET Value = 2
WHERE ModifierId = 'TRAIT_CHARMING_THEATER_DISTRICT' AND Name = 'YieldChange';