DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_HARALD_ALT';
-- 港口于“航海术”科技解锁，与港口相邻的海岸单元格+2生产力。
INSERT OR REPLACE INTO TraitModifiers 
(TraitType, 					ModifierID) 
VALUES	
('TRAIT_LEADER_HARALD_ALT',		'GOLDEN_TRAIT_LEADER_HARALD_ALT_UNLOCK_HARBOR'),
('TRAIT_LEADER_HARALD_ALT',		'GOLDEN_TRAIT_LEADER_HARALD_ALT_HARBOR_YIELD');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,										ModifierType,								SubjectRequirementSetId)
VALUES
('GOLDEN_TRAIT_LEADER_HARALD_ALT_UNLOCK_HARBOR',	'MODIFIER_PLAYER_ADJUST_DISTRICT_UNLOCK',	Null),
('GOLDEN_TRAIT_LEADER_HARALD_ALT_HARBOR_YIELD',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		'REQSET_GA_NORWAY_PLOT_ADJACENT');

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,										Name,				Value)
VALUES
('GOLDEN_TRAIT_LEADER_HARALD_ALT_UNLOCK_HARBOR',	'DistrictType',		'DISTRICT_HARBOR'),
('GOLDEN_TRAIT_LEADER_HARALD_ALT_UNLOCK_HARBOR',	'TechType',			'TECH_SHIPBUILDING'),
('GOLDEN_TRAIT_LEADER_HARALD_ALT_HARBOR_YIELD',		'YieldType',		'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_LEADER_HARALD_ALT_HARBOR_YIELD',		'Amount',			2);

INSERT OR REPLACE INTO RequirementSets 
(RequirementSetId, 						RequirementSetType) 
VALUES	
('REQSET_GA_NORWAY_PLOT_ADJACENT',		'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements 
(RequirementSetId, 						RequirementId) 
VALUES	
('REQSET_GA_NORWAY_PLOT_ADJACENT',		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_HARBOR'),
('REQSET_GA_NORWAY_PLOT_ADJACENT',		'REQUIRES_PLOT_IS_COAST');
-- 击杀单位时，获得等同于该单位战斗力25%的海军统帅点数。每次获得海军统帅后，海军近战和陆地近战单位便+2战斗力。
INSERT OR REPLACE INTO TraitModifiers 
(TraitType, 					ModifierID) 
VALUES	
('TRAIT_LEADER_HARALD_ALT',		'GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_POINT_UNIT'),
('TRAIT_LEADER_HARALD_ALT',		'GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT_UNIT'),
('TRAIT_LEADER_HARALD_ALT',		'GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT');

--1.1文明给海军将领 GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT_UNIT 
--1.2海军将领给首都 GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT_CITY 
--1.3首都给近战单位 GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT_EFFECT 
--2.0文明给近战单位 GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT 

INSERT OR REPLACE INTO Modifiers 
(ModifierId,											ModifierType,												SubjectRequirementSetId)
VALUES
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_POINT_UNIT',	'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER',					Null),
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_POINT',		'MODIFIER_PLAYER_UNIT_ADJUST_GREAT_PEOPLE_POINTS_PER_KILL',	Null),
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT_UNIT',	'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER',					'REQSET_GA_NORWAY_UNIT_IS_GREAT_ADMIRAL'),
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT',		'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH',				'REQSET_GA_NORWAY_UNIT_IS_LAND_OR_NAVAL_MELEE_UNIT');
INSERT OR REPLACE INTO Modifiers 
(ModifierId,												ModifierType,										Permanent)
VALUES
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT_CITY',		'GOLDEN_MODIFIER_PLAYER_CAPITAL_ATTACH_MODIFIER',	1);

INSERT OR REPLACE INTO Modifiers 
(ModifierId,												ModifierType,										SubjectRequirementSetId)
VALUES
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT_EFFECT',	'GOLDEN_MODIFIER_PLAYER_ADJUST_PROPERTY',		Null);

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,												Name,						Value)
VALUES
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_POINT_UNIT',		'ModifierId',				'GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_POINT'),
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_POINT',			'GreatPersonClassType',		'GREAT_PERSON_CLASS_ADMIRAL'),
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_POINT',			'Amount',					10),
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT_UNIT',		'ModifierId',				'GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT_CITY'),
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT_CITY',		'ModifierId',				'GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT_EFFECT'),
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT_EFFECT',	'Key',						'PROP_GA_HARALD_GAINED_ADMIRALS_EFFECTS'),
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT_EFFECT',	'Amount',					2),
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT',			'Key',						'PROP_GA_HARALD_GAINED_ADMIRALS_EFFECTS');

INSERT OR REPLACE INTO ModifierStrings 
(ModifierId,										Context,		Text)
VALUES
('GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT',	'Preview',		'LOC_GOLDEN_TRAIT_LEADER_HARALD_ALT_ADMIRAL_COMBAT_TEXT');

INSERT OR REPLACE INTO RequirementSets 
(RequirementSetId, 											RequirementSetType) 
VALUES	
('REQSET_GA_NORWAY_UNIT_IS_GREAT_ADMIRAL',					'REQUIREMENTSET_TEST_ALL'),
('REQSET_GA_NORWAY_UNIT_IS_LAND_OR_NAVAL_MELEE_UNIT',		'REQUIREMENTSET_TEST_ANY');

INSERT OR REPLACE INTO RequirementSetRequirements 
(RequirementSetId, 											RequirementId) 
VALUES	
('REQSET_GA_NORWAY_UNIT_IS_GREAT_ADMIRAL',					'GA_NORWAY_REQUIRES_UNIT_IS_GREAT_ADMIRAL'),
('REQSET_GA_NORWAY_UNIT_IS_LAND_OR_NAVAL_MELEE_UNIT',		'REQUIREMENT_UNIT_IS_MELEE'),
('REQSET_GA_NORWAY_UNIT_IS_LAND_OR_NAVAL_MELEE_UNIT',		'GOLDEN_REQUIRES_UNIT_IS_NAVAL_MELEE');

INSERT OR REPLACE INTO Requirements 
(RequirementId, 								RequirementType) 
VALUES	
('GA_NORWAY_REQUIRES_UNIT_IS_GREAT_ADMIRAL',		'REQUIREMENT_GREAT_PERSON_TYPE_MATCHES'),
('GOLDEN_REQUIRES_UNIT_IS_NAVAL_MELEE',			'REQUIREMENT_UNIT_PROMOTION_CLASS_MATCHES');

INSERT OR REPLACE INTO RequirementArguments 
(RequirementId, 								Name,					Value) 
VALUES	
('GA_NORWAY_REQUIRES_UNIT_IS_GREAT_ADMIRAL',		'GreatPersonClassType',	'GREAT_PERSON_CLASS_ADMIRAL'),
('GOLDEN_REQUIRES_UNIT_IS_NAVAL_MELEE',			'UnitPromotionClass',	'PROMOTION_CLASS_NAVAL_MELEE');