-----------------------------------------------
-- ExcludedDistricts
-----------------------------------------------
INSERT OR REPLACE INTO ExcludedDistricts (DistrictType, 			TraitType) VALUES	
('DISTRICT_WATER_ENTERTAINMENT_COMPLEX',	'TRAIT_CIVILIZATION_BYZANTIUM');
--------------------------------------------------------------
-- TraitModifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)VALUES
('TRAIT_CIVILIZATION_BYZANTIUM', 'GOLDEN_TRAIT_BYZANTIUM_APOSTLE'),
('TRAIT_CIVILIZATION_BYZANTIUM', 'GOLDEN_TRAIT_BYZANTIUM_FREE_WALLS'),
('TRAIT_CIVILIZATION_BYZANTIUM', 'GOLDEN_TRAIT_BYZANTIUM_FREE_CASTLE');
--------------------------------------------------------------
-- UnitAbilityModifiers
--------------------------------------------------------------
DELETE FROM UnitAbilityModifiers WHERE UnitAbilityType = 'ABILITY_BYZANTIUM_COMBAT_UNITS' AND ModifierId = 'BYZANTIUM_PRESSURE_KILLS';
--------------------------------------------------------------
-- Modifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)VALUES
('GOLDEN_TRAIT_BYZANTIUM_APOSTLE', 'MODIFIER_PLAYER_BUILT_CITIES_GRANT_FREE_UNIT', 0, 0, 'GOLDEN_CITY_HAS_WORSHIP_BUILDING_REQUIREMENTS'),
('GOLDEN_TRAIT_BYZANTIUM_FREE_WALLS', 'GOLDEN_MODIFIER_PLAYER_CITIES_GRANT_BUILDING_IN_CITY_IGNORE', 0, 0, 'GOLDEN_PLAYER_HAS_TECH_CASTLES_REQUIREMENTS'),
('GOLDEN_TRAIT_BYZANTIUM_FREE_CASTLE', 'GOLDEN_MODIFIER_PLAYER_CITIES_GRANT_BUILDING_IN_CITY_IGNORE', 0, 0, 'GOLDEN_PLAYER_HAS_TECH_CASTLES_REQUIREMENTS');
--------------------------------------------------------------
-- ModifierArguments
--------------------------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)VALUES
('GOLDEN_TRAIT_BYZANTIUM_APOSTLE', 'UnitType', 'UNIT_APOSTLE'),
('GOLDEN_TRAIT_BYZANTIUM_APOSTLE', 'Amount', 1),
('GOLDEN_TRAIT_BYZANTIUM_FREE_WALLS', 'BuildingType', 'BUILDING_WALLS'),
('GOLDEN_TRAIT_BYZANTIUM_FREE_CASTLE', 'BuildingType', 'BUILDING_CASTLE');
UPDATE ModifierArguments SET Value = 2
WHERE ModifierId = 'BYZANTIUM_GREATPROPHETPOINTS' AND Name = 'Amount';

--------------------------------------------------------------
-- TraitModifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)VALUES
('TRAIT_LEADER_BASIL', 'GOLDEN_TRAIT_BASIL_UNITS_KILL_PRESSURE'),
('TRAIT_LEADER_BASIL', 'GOLDEN_TRAIT_BASIL_ENABLE_WALL_ATTACK_MELEE'),
('TRAIT_LEADER_BASIL', 'GOLDEN_TRAIT_BASIL_ENABLE_WALL_ATTACK_ANTI_CAVALRY');
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES 
('GOLDEN_TRAIT_BASIL_UNITS_KILL_PRESSURE' , 				'MODIFIER_PLAYER_UNITS_GRANT_ABILITY' , 	0 , 0 , NULL),
('GOLDEN_TRAIT_BASIL_ENABLE_WALL_ATTACK_MELEE' , 			'MODIFIER_PLAYER_ADJUST_ENABLE_WALL_ATTACK_WHOLE_GAME_SAME_RELIGION_PROMOTION_CLASS' ,		0 , 0 , NULL ),
('GOLDEN_TRAIT_BASIL_ENABLE_WALL_ATTACK_ANTI_CAVALRY' , 	'MODIFIER_PLAYER_ADJUST_ENABLE_WALL_ATTACK_WHOLE_GAME_SAME_RELIGION_PROMOTION_CLASS' ,		0 , 0 , NULL );
-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('GOLDEN_TRAIT_BASIL_UNITS_KILL_PRESSURE', 					'AbilityType', 					'ABILITY_BASIL_UNITS_KILL_PRESSURE'),
('GOLDEN_TRAIT_BASIL_ENABLE_WALL_ATTACK_MELEE', 			'PromotionClass', 				'PROMOTION_CLASS_MELEE'),
('GOLDEN_TRAIT_BASIL_ENABLE_WALL_ATTACK_ANTI_CAVALRY', 		'PromotionClass', 				'PROMOTION_CLASS_ANTI_CAVALRY');
-----------------------------------------------
-- Types
-----------------------------------------------
INSERT OR REPLACE INTO Types (Type,						Kind) VALUES
('ABILITY_BASIL_UNITS_KILL_PRESSURE',					'KIND_ABILITY');
-----------------------------------------------
-- TypeTags
-----------------------------------------------		
INSERT OR REPLACE INTO TypeTags (Type,									Tag) VALUES	
('ABILITY_BASIL_UNITS_KILL_PRESSURE',				'CLASS_LIGHT_CAVALRY'),
('ABILITY_BASIL_UNITS_KILL_PRESSURE',			    'CLASS_HEAVY_CAVALRY'),
('ABILITY_BASIL_UNITS_KILL_PRESSURE',			    'CLASS_MELEE'),
('ABILITY_BASIL_UNITS_KILL_PRESSURE',			    'CLASS_TRUE_RANGED'),
('ABILITY_BASIL_UNITS_KILL_PRESSURE',			    'CLASS_SIEGE'),
('ABILITY_BASIL_UNITS_KILL_PRESSURE',			    'CLASS_RECON'),
('ABILITY_BASIL_UNITS_KILL_PRESSURE',			    'CLASS_ANTI_CAVALRY'),
('ABILITY_BASIL_UNITS_KILL_PRESSURE',			    'CLASS_NAVAL_MELEE'),
('ABILITY_BASIL_UNITS_KILL_PRESSURE',			    'CLASS_NAVAL_RANGED'),
('ABILITY_BASIL_UNITS_KILL_PRESSURE',			    'CLASS_NAVAL_RAIDER'),
('ABILITY_BASIL_UNITS_KILL_PRESSURE',			    'CLASS_NAVAL_CARRIER'),
('ABILITY_BASIL_UNITS_KILL_PRESSURE',			    'CLASS_AIRCRAFT');
INSERT OR REPLACE INTO TypeTags (Type, Tag) SELECT 'ABILITY_BASIL_UNITS_KILL_PRESSURE', 'CLASS_AUTOMATIC_GUN' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_COMPOSITE_BOWMAN');
-----------------------------------------------
-- UnitAbilities
-----------------------------------------------
INSERT OR REPLACE INTO UnitAbilities (UnitAbilityType,						Name,									Description, Inactive) VALUES	
('ABILITY_BASIL_UNITS_KILL_PRESSURE',			'LOC_ABILITY_BASIL_UNITS_KILL_PRESSURE_NAME',	'LOC_ABILITY_BASIL_UNITS_KILL_PRESSURE_DESCRIPTION', 1);
-----------------------------------------------
-- UnitAbilityModifiers
-----------------------------------------------
INSERT OR REPLACE INTO UnitAbilityModifiers (UnitAbilityType,						ModifierId) VALUES	
('ABILITY_BASIL_UNITS_KILL_PRESSURE',			            'BYZANTIUM_PRESSURE_KILLS');



-----------------------------------------------
--UD
-----------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
SELECT	'TRAIT_CIVILIZATION_BYZANTIUM', 'GOLDEN_HIPPODROME_CITY_CENTER_AMENITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
SELECT	'TRAIT_CIVILIZATION_BYZANTIUM', 'GOLDEN_HIPPODROME_GOVERNMENT_AMENITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
SELECT	'GOLDEN_HIPPODROME_CITY_CENTER_AMENITY', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT', 0, 0, 'GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_CITY_CENTER_REQUIREMENTS' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
SELECT	'GOLDEN_HIPPODROME_GOVERNMENT_AMENITY', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT', 0, 0, 'GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_GOVERNMENT_REQUIREMENTS' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_HIPPODROME_CITY_CENTER_AMENITY', 'Amount', 1 WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_HIPPODROME_GOVERNMENT_AMENITY', 'Amount', 1 WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');

INSERT OR REPLACE INTO RequirementSets		(RequirementSetId,							RequirementSetType) VALUES
('GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_CITY_CENTER_REQUIREMENTS',		                'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		                'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements		(RequirementSetId,							RequirementId) VALUES	
('GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_CITY_CENTER_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HIPPODROME'),
('GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_CITY_CENTER_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_CITY_CENTER'),
('GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HIPPODROME'),
('GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		         'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_GOVERNMENT');

INSERT OR REPLACE INTO Requirements (RequirementId,			RequirementType) VALUES	 
('GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HIPPODROME',	           'REQUIREMENT_DISTRICT_TYPE_MATCHES');

INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) VALUES
('GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HIPPODROME',		        'DistrictType',	    'DISTRICT_HIPPODROME');