DELETE FROM TraitModifiers
WHERE ModifierId = 'ELIZABETH_TRADE_ROUTES_MODIFIER';

DELETE FROM TraitModifiers
WHERE ModifierId = 'ELIZABETH_PLUNDER_ABILITY';


--目的地中每有一个特色区域，[ICON_TradeRoute] 国际贸易路线便+3 [ICON_GOLD] 金币。
UPDATE Modifiers
SET ModifierType = 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_PER_SPECIALTY_DISTRICT_FOR_INTERNATIONAL'
WHERE ModifierId = 'ELIZABETH_TRADE_ROUTES_YIELDS';

--在非首都大陆上的建立沿海城市时获得额外+3 [ICON_Citizen] 人口。
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_LEADER_ELIZABETH',	                'GA_TRAIT_FREE_POPULATION_FOREIGN_COASTAL_CITY');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
('GA_TRAIT_FREE_POPULATION_FOREIGN_COASTAL_CITY',					'MODIFIER_PLAYER_BUILT_CITIES_GRANT_FREE_POPULATION', 0, 0,						'GOLDEN_ENGLAND_COASTAL_CITY_NOT_OWNER_CAPITAL_CONTINENT_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GA_TRAIT_FREE_POPULATION_FOREIGN_COASTAL_CITY',									'Amount',		                3);

--每次获得 [ICON_GreatAdmiral] 海军统帅后，[ICON_TradeRoute] 贸易路线容量+1。
INSERT OR REPLACE INTO TraitModifiers 
(TraitType, 					ModifierID) 
VALUES	
('TRAIT_LEADER_ELIZABETH',		'GA_TRAIT_ENGLAND_TRADE_ROUTES');
INSERT OR REPLACE INTO Modifiers 
(ModifierId,							ModifierType,									Permanent,	SubjectRequirementSetId)
VALUES	
('GA_TRAIT_ENGLAND_TRADE_ROUTES',		'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER',		0,			'REQSET_GA_ENGLAND_UNIT_IS_GREAT_ADMIRAL'),
('GA_TRAIT_ENGLAND_TRADE_ROUTES_MOD',	'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY',	1,			Null);

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,						Name,			Value) 
VALUES
('GA_TRAIT_ENGLAND_TRADE_ROUTES',	'ModifierId',	'GA_TRAIT_ENGLAND_TRADE_ROUTES_MOD'),
('GA_TRAIT_ENGLAND_TRADE_ROUTES',	'Amount',		1);

INSERT OR REPLACE INTO RequirementSets 
(RequirementSetId, 											RequirementSetType) 
VALUES	
('REQSET_GA_ENGLAND_UNIT_IS_GREAT_ADMIRAL',					'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements 
(RequirementSetId, 											RequirementId) 
VALUES	
('REQSET_GA_ENGLAND_UNIT_IS_GREAT_ADMIRAL',					'GA_ENGLAND_REQUIRES_UNIT_IS_GREAT_ADMIRAL');

INSERT OR REPLACE INTO Requirements 
(RequirementId, 								RequirementType) 
VALUES	
('GA_ENGLAND_REQUIRES_UNIT_IS_GREAT_ADMIRAL',		'REQUIREMENT_GREAT_PERSON_TYPE_MATCHES');

INSERT OR REPLACE INTO RequirementArguments 
(RequirementId, 								Name,					Value) 
VALUES	
('GA_ENGLAND_REQUIRES_UNIT_IS_GREAT_ADMIRAL',		'GreatPersonClassType',				'GREAT_PERSON_CLASS_ADMIRAL');