--------------------------------------------------------------
-- Traits
--------------------------------------------------------------
UPDATE Traits SET Description= 'LOC_TRAIT_LEADER_HELLENISTIC_FUSION_EXPANSION1_DESCRIPTION'
WHERE TraitType ='TRAIT_CIVILIZATION_HELLENISTIC_FUSION';
--------------------------------------------------------------
-- TraitModifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_CIVILIZATION_HELLENISTIC_FUSION' , 'TOQUI_DOMESTIC_LOYALTY' ),
('TRAIT_CIVILIZATION_HELLENISTIC_FUSION' , 'TOQUI_FOREIGN_LOYALTY' ),
('TRAIT_CIVILIZATION_HELLENISTIC_FUSION' , 'GOLDEN_TRAIT_HELLENISTIC_FUSION_INDUSTRIAL_ZONE_EUREKA' ),
('TRAIT_CIVILIZATION_HELLENISTIC_FUSION' , 'GOLDEN_TRAIT_HELLENISTIC_FUSION_COMMERCIAL_HUB_INSPIRATION' );
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_TO_WORLDS_END' , 'GOLDEN_TRAIT_TO_WORLDS_END_UNIT_ATTACK_EXPERIENCE' ),
('TRAIT_LEADER_TO_WORLDS_END' , 'GOLDEN_TRAIT_IGNORE_ZOC_MOVEMENT' );
------------------------------------------------------------
-- Modifiers
------------------------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
VALUES ('GOLDEN_TRAIT_HELLENISTIC_FUSION_INDUSTRIAL_ZONE_EUREKA' , 'MODIFIER_PLAYER_CAPTURED_CITY_ATTACH_MODIFIER' , 'GOLDEN_CITY_HAS_DISTRICT_INDUSTRIAL_ZONE_REQUIREMENTS'  );
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES ('GOLDEN_TRAIT_HELLENISTIC_FUSION_INDUSTRIAL_ZONE_EUREKA_MODIFIER' , 'MODIFIER_PLAYER_GRANT_RANDOM_TECHNOLOGY_BOOST_GOODY_HUT' , 1 , 1 , NULL );
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
VALUES ('GOLDEN_TRAIT_HELLENISTIC_FUSION_COMMERCIAL_HUB_INSPIRATION' , 'MODIFIER_PLAYER_CAPTURED_CITY_ATTACH_MODIFIER' , 'GOLDEN_CITY_HAS_DISTRICT_COMMERCIAL_HUB_REQUIREMENTS'  );
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES ('GOLDEN_TRAIT_HELLENISTIC_FUSION_COMMERCIAL_HUB_INSPIRATION_MODIFIER' , 'MODIFIER_PLAYER_GRANT_RANDOM_CIVIC_BOOST_GOODY_HUT' , 1 , 1 , NULL );
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES 
('GOLDEN_TRAIT_TO_WORLDS_END_UNIT_ATTACK_EXPERIENCE' , 	'MODIFIER_PLAYER_UNITS_ADJUST_UNIT_ATTACK_EXPERIENCE_MODIFIER' , NULL  ),
('GOLDEN_TRAIT_IGNORE_ZOC_MOVEMENT' , 					'MODIFIER_PLAYER_UNITS_GRANT_ABILITY' , NULL  );
--------------------------------------------------------------
-- ModifierArguments
--------------------------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES
('GOLDEN_TRAIT_HELLENISTIC_FUSION_INDUSTRIAL_ZONE_EUREKA' , 				'ModifierId' , 'GOLDEN_TRAIT_HELLENISTIC_FUSION_INDUSTRIAL_ZONE_EUREKA_MODIFIER'  ),
('GOLDEN_TRAIT_HELLENISTIC_FUSION_INDUSTRIAL_ZONE_EUREKA_MODIFIER' , 		'Amount' , 1  ),
('GOLDEN_TRAIT_HELLENISTIC_FUSION_INDUSTRIAL_ZONE_EUREKA_MODIFIER' , 		'Source' , 'CAPTURED_CITY'  ),
('GOLDEN_TRAIT_HELLENISTIC_FUSION_COMMERCIAL_HUB_INSPIRATION' , 			'ModifierId' , 'GOLDEN_TRAIT_HELLENISTIC_FUSION_COMMERCIAL_HUB_INSPIRATION_MODIFIER'  ),
('GOLDEN_TRAIT_HELLENISTIC_FUSION_COMMERCIAL_HUB_INSPIRATION_MODIFIER' , 	'Amount' , 1  ),
('GOLDEN_TRAIT_HELLENISTIC_FUSION_COMMERCIAL_HUB_INSPIRATION_MODIFIER' , 	'Source' , 'CAPTURED_CITY'  ),
('GOLDEN_TRAIT_TO_WORLDS_END_UNIT_ATTACK_EXPERIENCE' , 						'Amount' , 100  ),
('GOLDEN_TRAIT_IGNORE_ZOC_MOVEMENT' , 										'AbilityType' , 'ABILITY_IGNORE_ZOC_MOVEMENT'  );
-----------------------------------------------
-- Types
-----------------------------------------------
INSERT OR REPLACE INTO Types (Type,						Kind) VALUES
('ABILITY_IGNORE_ZOC_MOVEMENT',					'KIND_ABILITY');
-----------------------------------------------
-- TypeTags
-----------------------------------------------		
INSERT OR REPLACE INTO TypeTags (Type,									Tag) VALUES	
('ABILITY_IGNORE_ZOC_MOVEMENT',				'CLASS_LIGHT_CAVALRY'),
('ABILITY_IGNORE_ZOC_MOVEMENT',			    'CLASS_HEAVY_CAVALRY'),
('ABILITY_IGNORE_ZOC_MOVEMENT',			    'CLASS_MELEE'),
('ABILITY_IGNORE_ZOC_MOVEMENT',			    'CLASS_TRUE_RANGED'),
('ABILITY_IGNORE_ZOC_MOVEMENT',			    'CLASS_SIEGE'),
('ABILITY_IGNORE_ZOC_MOVEMENT',			    'CLASS_RECON'),
('ABILITY_IGNORE_ZOC_MOVEMENT',			    'CLASS_ANTI_CAVALRY');
INSERT OR REPLACE INTO TypeTags (Type, Tag) SELECT 'ABILITY_IGNORE_ZOC_MOVEMENT', 'CLASS_AUTOMATIC_GUN' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_COMPOSITE_BOWMAN');
-----------------------------------------------
-- UnitAbilities
-----------------------------------------------
INSERT OR REPLACE INTO UnitAbilities (UnitAbilityType,						Name,									Description, Inactive) VALUES	
('ABILITY_IGNORE_ZOC_MOVEMENT',			'LOC_ABILITY_IGNORE_ZOC_MOVEMENT_NAME',	'LOC_ABILITY_IGNORE_ZOC_MOVEMENT_DESCRIPTION', 1);
-----------------------------------------------
-- UnitAbilityModifiers
-----------------------------------------------
INSERT OR REPLACE INTO UnitAbilityModifiers (UnitAbilityType,						ModifierId) VALUES	
('ABILITY_IGNORE_ZOC_MOVEMENT',			            'IGNOREZOC_IGNORE_ZOC'),
('ABILITY_IGNORE_ZOC_MOVEMENT',			            'HEAVYCHARIOT_FASTER_CLEAR_TERRAIN');