--------------------------------------------------------------
-- TraitModifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO TraitModifiers 
(TraitType, 					ModifierId)
VALUES 
('TRAIT_LEADER_LINCOLN' ,		'GOLDEN_TRAIT_LEADER_LINCOLN_IMPROVEMENT_FOOD_YIELD'),
('TRAIT_LEADER_LINCOLN' ,		'GOLDEN_TRAIT_LEADER_LINCOLN_IMPROVEMENT_PRODUCTION_YIELD');
--------------------------------------------------------------
-- BuildingModifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO BuildingModifiers 
(BuildingType, ModifierId)
SELECT 
BuildingType , 'GOLDEN_TRAIT_LEADER_LINCOLN_IMPROVEMENT_YIELD_FROM_BUILDING'
FROM Buildings WHERE PrereqDistrict = 'DISTRICT_INDUSTRIAL_ZONE';
--------------------------------------------------------------
-- Modifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO Modifiers 
(ModifierId, ModifierType, SubjectRequirementSetId)
VALUES 
('GOLDEN_TRAIT_LEADER_LINCOLN_IMPROVEMENT_FOOD_YIELD' ,				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD' ,				'REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_NEAR_IZ_IMPROVEMENT' ),
('GOLDEN_TRAIT_LEADER_LINCOLN_IMPROVEMENT_PRODUCTION_YIELD' ,		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD' ,				'REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_NEAR_IZ_IMPROVEMENT' ),
('GOLDEN_TRAIT_LEADER_LINCOLN_IMPROVEMENT_YIELD_FROM_BUILDING' ,	'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD' ,		'REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_NEAR_IZ_IMPROVEMENT_LINCOLN' );
--------------------------------------------------------------
-- ModifierArguments
--------------------------------------------------------------
INSERT OR REPLACE INTO ModifierArguments 
(ModifierId, Name, Value)
VALUES 
('GOLDEN_TRAIT_LEADER_LINCOLN_IMPROVEMENT_FOOD_YIELD',				'YieldType',	'YIELD_FOOD'),
('GOLDEN_TRAIT_LEADER_LINCOLN_IMPROVEMENT_FOOD_YIELD',				'Amount',		-1),
('GOLDEN_TRAIT_LEADER_LINCOLN_IMPROVEMENT_PRODUCTION_YIELD',		'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_LEADER_LINCOLN_IMPROVEMENT_PRODUCTION_YIELD',		'Amount',		1),
('GOLDEN_TRAIT_LEADER_LINCOLN_IMPROVEMENT_YIELD_FROM_BUILDING',		'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_LEADER_LINCOLN_IMPROVEMENT_YIELD_FROM_BUILDING',		'Amount',		1);
UPDATE ModifierArguments SET  Value = 5
WHERE ModifierId = 'TRAIT_LINCOLN_INDUSTRIAL_ZONE_LOYALTY' AND Name = 'Amount';
--------------------------------------------------------------
-- RequirementSets
--------------------------------------------------------------
INSERT INTO RequirementSets
(RequirementSetId,													RequirementSetType) 
VALUES	
('REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_IMPROVEMENT',					'REQUIREMENTSET_TEST_ANY'),
('REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_NEAR_IZ_IMPROVEMENT',			'REQUIREMENTSET_TEST_ALL'),
('REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_NEAR_IZ_IMPROVEMENT_LINCOLN',	'REQUIREMENTSET_TEST_ALL');
--------------------------------------------------------------
-- RequirementSetRequirements
--------------------------------------------------------------
INSERT INTO RequirementSetRequirements
(RequirementSetId,													RequirementId) 
VALUES	
('REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_IMPROVEMENT',					'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_FARM'),
('REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_IMPROVEMENT',					'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_PASTURE'),
('REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_IMPROVEMENT',					'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_PLANTATION'),
('REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_NEAR_IZ_IMPROVEMENT',			'GOLDEN_REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_IMPROVEMENT_MET'),
('REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_NEAR_IZ_IMPROVEMENT',			'GOLDEN_REQUIRES_PLOT_IS_WITHIN_TWO_TILES_TO_DISTRICT_INDUSTRIAL_ZONE'),
('REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_NEAR_IZ_IMPROVEMENT_LINCOLN',	'GOLDEN_REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_IMPROVEMENT_MET'),
('REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_NEAR_IZ_IMPROVEMENT_LINCOLN',	'GOLDEN_REQUIRES_PLOT_IS_WITHIN_TWO_TILES_TO_DISTRICT_INDUSTRIAL_ZONE'),
('REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_NEAR_IZ_IMPROVEMENT_LINCOLN',	'GOLDEN_REQUIRES_PLAYER_IS_LINCOLN');
--------------------------------------------------------------
-- Requirements & RequirementArguments
--------------------------------------------------------------
INSERT INTO Requirements
(RequirementId,													RequirementType) 
VALUES
('GOLDEN_REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_IMPROVEMENT_MET',	'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_IS_LINCOLN',							'REQUIREMENT_PLAYER_LEADER_TYPE_MATCHES');

INSERT INTO RequirementArguments
(RequirementId,													Name,				Value) 
VALUES	
('GOLDEN_REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_IMPROVEMENT_MET',	'RequirementSetId',	'REQSET_GOLDEN_CITY_PLOT_HAS_SLAVE_IMPROVEMENT'),
('GOLDEN_REQUIRES_PLAYER_IS_LINCOLN',							'LeaderType',		'LEADER_ABRAHAM_LINCOLN');

