--TraitModifiers

DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_NADER_SHAH' AND ModifierId = 'NADER_SHAH_TRADE_GOLD';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_NADER_SHAH' AND ModifierId = 'NADER_SHAH_TRADE_FAITH';

INSERT OR REPLACE INTO TraitModifiers 
(TraitType, 				ModifierId) VALUES	
('TRAIT_LEADER_NADER_SHAH',	'GA_TRAIT_LEADER_NADER_SHAH_CAPTURE_CITY_GOLD'),
('TRAIT_LEADER_NADER_SHAH',	'GA_TRAIT_LEADER_NADER_SHAH_SURPRISE_WAR_PRODUCTION');

--Modifiers
INSERT OR REPLACE INTO Modifiers 
(ModifierId, 											ModifierType, 											SubjectRequirementSetId) VALUES
('GA_TRAIT_LEADER_NADER_SHAH_CAPTURE_CITY_GOLD',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',		'CITY_NOT_FOUNDED'),
('GA_TRAIT_LEADER_NADER_SHAH_SURPRISE_WAR_PRODUCTION',	'MODIFIER_PLAYER_ADD_DIPLOMATIC_YIELD_MODIFIER',		Null);

--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments 
(ModifierId, 											Name, 						Value) VALUES
('GA_TRAIT_LEADER_NADER_SHAH_CAPTURE_CITY_GOLD',		'YieldType',				'YIELD_GOLD'),
('GA_TRAIT_LEADER_NADER_SHAH_CAPTURE_CITY_GOLD',		'Amount',					25),
('GA_TRAIT_LEADER_NADER_SHAH_SURPRISE_WAR_PRODUCTION',	'DiplomaticYieldSource',	'SURPRISE_WAR_INITIATED'),
('GA_TRAIT_LEADER_NADER_SHAH_SURPRISE_WAR_PRODUCTION',	'TurnsActive',				10),
('GA_TRAIT_LEADER_NADER_SHAH_SURPRISE_WAR_PRODUCTION',	'YieldType',				'YIELD_PRODUCTION'),
('GA_TRAIT_LEADER_NADER_SHAH_SURPRISE_WAR_PRODUCTION',	'Amount',					100);

