UPDATE Building_YieldChanges SET YieldChange = 4
WHERE BuildingType = 'BUILDING_PRASAT' AND YieldType = 'YIELD_FAITH' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_PRASAT');
--------------------------------------------------------------
-- TraitModifiers
--------------------------------------------------------------
DELETE FROM TraitModifiers WHERE ModifierId = 'BARAYS_FAITH_POPULATION';
DELETE FROM TraitModifiers WHERE ModifierId = 'TRAIT_FARM_HOLY_SITE_ADJECENCY_FAITH';

INSERT OR REPLACE INTO TraitModifiers		(TraitType, ModifierId) VALUES
-- ('TRAIT_CIVILIZATION_KHMER_BARAYS', 'GOLDEN_TRAIT_LAKE_FAITH_MODIFIER'),
-- ('TRAIT_CIVILIZATION_KHMER_BARAYS', 'GOLDEN_TRAIT_LAKE_GOLD_MODIFIER'),
-- ('TRAIT_CIVILIZATION_KHMER_BARAYS', 'GOLDEN_TRAIT_LAKE_PRODUCTION_MODIFIER'),
('TRAIT_CIVILIZATION_KHMER_BARAYS', 'GOLDEN_TRAIT_KHMER_BARAYS_CANAL_AMENITY'),
('TRAIT_CIVILIZATION_KHMER_BARAYS', 'GOLDEN_TRAIT_KHMER_BARAYS_DAM_AMENITY'),

('TRAIT_CIVILIZATION_KHMER_BARAYS', 'GOLDEN_TRAIT_FARM_AQUEDUCT_ADJECENCY_PRODUCTION'),
('TRAIT_CIVILIZATION_KHMER_BARAYS', 'GOLDEN_TRAIT_FARM_CANAL_ADJECENCY_FOOD'),
('TRAIT_CIVILIZATION_KHMER_BARAYS', 'GOLDEN_TRAIT_FARM_CANAL_ADJECENCY_PRODUCTION'),
('TRAIT_CIVILIZATION_KHMER_BARAYS', 'GOLDEN_TRAIT_FARM_DAM_ADJECENCY_FOOD'),
('TRAIT_CIVILIZATION_KHMER_BARAYS', 'GOLDEN_TRAIT_FARM_DAM_ADJECENCY_PRODUCTION');

DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_MONASTERIES_KING' AND ModifierId = 'TRAIT_MONASTERIES_KING_HOLY_SITE_RIVER_ADJACENCY';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_MONASTERIES_KING' AND ModifierId = 'TRAIT_MONASTERIES_KING_ADJACENCY_FOOD';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_MONASTERIES_KING' AND ModifierId = 'TRAIT_HOLY_SITE_RIVER_2HOUSING';

INSERT OR REPLACE INTO TraitModifiers		(TraitType, ModifierId)VALUES
('TRAIT_LEADER_MONASTERIES_KING', 'GOLDEN_TRAIT_MONASTERIES_KING_DISTRICT_HOLY_SITE_CITIZENS'),
('TRAIT_LEADER_MONASTERIES_KING', 'GOLDEN_TRAIT_MONASTERIES_KING_BUILDING_SHRINE_CITIZENS'),
('TRAIT_LEADER_MONASTERIES_KING', 'GOLDEN_TRAIT_MONASTERIES_KING_BUILDING_PRASAT_CITIZENS'),
('TRAIT_LEADER_MONASTERIES_KING', 'GOLDEN_TRAIT_MONASTERIES_KING_WORSHIP_BUILDING_CITIZENS'),
('TRAIT_LEADER_MONASTERIES_KING', 'GOLDEN_TRAIT_MONASTERIES_KING_DISTRICT_HOLY_SITE_HOUSING'),
('TRAIT_LEADER_MONASTERIES_KING', 'GOLDEN_TRAIT_MONASTERIES_KING_BUILDING_SHRINE_HOUSING'),
('TRAIT_LEADER_MONASTERIES_KING', 'GOLDEN_TRAIT_MONASTERIES_KING_BUILDING_PRASAT_HOUSING'),
('TRAIT_LEADER_MONASTERIES_KING', 'GOLDEN_TRAIT_MONASTERIES_KING_WORSHIP_BUILDING_HOUSING');
INSERT OR REPLACE INTO TraitModifiers		(TraitType, ModifierId)
SELECT 'TRAIT_LEADER_MONASTERIES_KING', 'GOLDEN_TRAIT_MONASTERIES_KING_NO_WORSHIP_BUILDING_DEBUFF' ||YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers		(TraitType, ModifierId)
SELECT	'TRAIT_LEADER_MONASTERIES_KING', 'GOLDEN_TRAIT_MONASTERIES_KING_WORSHIP_BUILDING_BONUS' ||YieldType FROM Yields;
--------------------------------------------------------------
-- Modifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO Modifiers		(ModifierId, ModifierType, SubjectRequirementSetId)VALUES
-- ('GOLDEN_TRAIT_LAKE_FAITH_MODIFIER', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'GOLDEN_PLOT_IS_LAKE_REQUIREMENTS'),
-- ('GOLDEN_TRAIT_LAKE_GOLD_MODIFIER', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'GOLDEN_PLOT_IS_LAKE_REQUIREMENTS'),
-- ('GOLDEN_TRAIT_LAKE_PRODUCTION_MODIFIER', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'GOLDEN_PLOT_IS_LAKE_REQUIREMENTS'),
('GOLDEN_TRAIT_KHMER_BARAYS_CANAL_AMENITY', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT', 'GOLDEN_DISTRICT_IS_DISTRICT_CANAL_REQUIREMENTS'),
('GOLDEN_TRAIT_KHMER_BARAYS_DAM_AMENITY', 	'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT', 'GOLDEN_DISTRICT_IS_DISTRICT_DAM_REQUIREMENTS'),

('GOLDEN_TRAIT_FARM_AQUEDUCT_ADJECENCY_PRODUCTION', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'PLOT_IS_FARM_AQUEDUCT_ADJACENT_REQUIREMENTS'),
('GOLDEN_TRAIT_FARM_CANAL_ADJECENCY_FOOD', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'GOLDEN_PLOT_IS_FARM_CANAL_ADJACENT_REQUIREMENTS'),
('GOLDEN_TRAIT_FARM_CANAL_ADJECENCY_PRODUCTION', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'GOLDEN_PLOT_IS_FARM_CANAL_ADJACENT_REQUIREMENTS'),
('GOLDEN_TRAIT_FARM_DAM_ADJECENCY_FOOD', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'GOLDEN_PLOT_IS_FARM_DAM_ADJACENT_REQUIREMENTS'),
('GOLDEN_TRAIT_FARM_DAM_ADJECENCY_PRODUCTION', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'GOLDEN_PLOT_IS_FARM_DAM_ADJACENT_REQUIREMENTS'),
('GOLDEN_TRAIT_FARM_DAM_ADJECENCY_PRODUCTION', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'GOLDEN_PLOT_IS_FARM_DAM_ADJACENT_REQUIREMENTS'),
('GOLDEN_TRAIT_MONASTERIES_KING_DISTRICT_HOLY_SITE_CITIZENS', 'MODIFIER_PLAYER_CITIES_ADD_POPULATION', 'GOLDEN_CITY_HAS_DISTRICT_HOLY_SITE_REQUIREMENTS'),
('GOLDEN_TRAIT_MONASTERIES_KING_BUILDING_SHRINE_CITIZENS', 'MODIFIER_PLAYER_CITIES_ADD_POPULATION', 'GOLDEN_CITY_HAS_BUILDING_SHRINE_REQUIREMENTS'),
('GOLDEN_TRAIT_MONASTERIES_KING_BUILDING_PRASAT_CITIZENS', 'MODIFIER_PLAYER_CITIES_ADD_POPULATION', 'GOLDEN_CITY_HAS_BUILDING_PRASAT_REQUIREMENTS'),
('GOLDEN_TRAIT_MONASTERIES_KING_WORSHIP_BUILDING_CITIZENS', 'MODIFIER_PLAYER_CITIES_ADD_POPULATION', 'GOLDEN_CITY_HAS_WORSHIP_BUILDING_REQUIREMENTS'),
('GOLDEN_TRAIT_MONASTERIES_KING_DISTRICT_HOLY_SITE_HOUSING', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING', 'DISTRICT_IS_HOLY_SITE'),
('GOLDEN_TRAIT_MONASTERIES_KING_BUILDING_SHRINE_HOUSING', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_HOUSING', 'GOLDEN_CITY_HAS_BUILDING_SHRINE_REQUIREMENTS'),
('GOLDEN_TRAIT_MONASTERIES_KING_BUILDING_PRASAT_HOUSING', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_HOUSING', 'GOLDEN_CITY_HAS_BUILDING_PRASAT_REQUIREMENTS'),
('GOLDEN_TRAIT_MONASTERIES_KING_WORSHIP_BUILDING_HOUSING', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_HOUSING', 'GOLDEN_CITY_HAS_WORSHIP_BUILDING_REQUIREMENTS');

INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,												SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_MONASTERIES_KING_NO_WORSHIP_BUILDING_DEBUFF' ||YieldType,	    'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',		'GOLDEN_CITY_HAS_NO_WORSHIP_BUILDING_REQUIREMENTS' FROM Yields;
INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,												SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_MONASTERIES_KING_WORSHIP_BUILDING_BONUS' ||YieldType,	        'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',		'GOLDEN_CITY_HAS_WORSHIP_BUILDING_REQUIREMENTS' FROM Yields;

--------------------------------------------------------------
-- ModifierArguments
--------------------------------------------------------------
UPDATE ModifierArguments SET Value = 1
WHERE ModifierId = 'TRAIT_FARM_AQUEDUCT_ADJECENCY_FOOD' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 2
WHERE ModifierId = 'TRAIT_AQUEDUCT_AMENITY' AND Name = 'Amount';
INSERT OR REPLACE INTO ModifierArguments		(ModifierId, Name, Value)VALUES
-- ('GOLDEN_TRAIT_LAKE_FAITH_MODIFIER', 'Amount', 2),
-- ('GOLDEN_TRAIT_LAKE_FAITH_MODIFIER', 'YieldType', 'YIELD_FAITH'),
-- ('GOLDEN_TRAIT_LAKE_GOLD_MODIFIER', 'Amount', 1),
-- ('GOLDEN_TRAIT_LAKE_GOLD_MODIFIER', 'YieldType', 'YIELD_GOLD'),
-- ('GOLDEN_TRAIT_LAKE_PRODUCTION_MODIFIER', 'Amount', 2),
-- ('GOLDEN_TRAIT_LAKE_PRODUCTION_MODIFIER', 'YieldType', 'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_KHMER_BARAYS_CANAL_AMENITY', 'Amount', 2),
('GOLDEN_TRAIT_KHMER_BARAYS_DAM_AMENITY', 	'Amount', 2),

('GOLDEN_TRAIT_FARM_AQUEDUCT_ADJECENCY_PRODUCTION', 'Amount', 1),
('GOLDEN_TRAIT_FARM_AQUEDUCT_ADJECENCY_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_FARM_CANAL_ADJECENCY_FOOD', 'Amount', 1),
('GOLDEN_TRAIT_FARM_CANAL_ADJECENCY_FOOD', 'YieldType', 'YIELD_FOOD'),
('GOLDEN_TRAIT_FARM_CANAL_ADJECENCY_PRODUCTION', 'Amount', 1),
('GOLDEN_TRAIT_FARM_CANAL_ADJECENCY_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_FARM_DAM_ADJECENCY_FOOD', 'Amount', 1),
('GOLDEN_TRAIT_FARM_DAM_ADJECENCY_FOOD', 'YieldType', 'YIELD_FOOD'),
('GOLDEN_TRAIT_FARM_DAM_ADJECENCY_PRODUCTION', 'Amount', 1),
('GOLDEN_TRAIT_FARM_DAM_ADJECENCY_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_MONASTERIES_KING_DISTRICT_HOLY_SITE_CITIZENS', 'Amount', 1),
('GOLDEN_TRAIT_MONASTERIES_KING_BUILDING_SHRINE_CITIZENS', 'Amount', 2),
('GOLDEN_TRAIT_MONASTERIES_KING_BUILDING_PRASAT_CITIZENS', 'Amount', 3),
('GOLDEN_TRAIT_MONASTERIES_KING_WORSHIP_BUILDING_CITIZENS', 'Amount', 4),
('GOLDEN_TRAIT_MONASTERIES_KING_DISTRICT_HOLY_SITE_HOUSING', 'Amount', 1),
('GOLDEN_TRAIT_MONASTERIES_KING_BUILDING_SHRINE_HOUSING', 'Amount', 2),
('GOLDEN_TRAIT_MONASTERIES_KING_BUILDING_PRASAT_HOUSING', 'Amount', 3),
('GOLDEN_TRAIT_MONASTERIES_KING_WORSHIP_BUILDING_HOUSING', 'Amount', 4);


INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GOLDEN_TRAIT_MONASTERIES_KING_NO_WORSHIP_BUILDING_DEBUFF' ||YieldType,	        'Amount',	    -10 FROM Yields;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GOLDEN_TRAIT_MONASTERIES_KING_NO_WORSHIP_BUILDING_DEBUFF' ||YieldType,	        'YieldType',	YieldType FROM Yields;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GOLDEN_TRAIT_MONASTERIES_KING_WORSHIP_BUILDING_BONUS' ||YieldType,	        'Amount',	    4 FROM Yields;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GOLDEN_TRAIT_MONASTERIES_KING_WORSHIP_BUILDING_BONUS' ||YieldType,	        'YieldType',	YieldType FROM Yields;
---------------------------------------------------------------------------------------------------------------
-- RequirementSets
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSets (RequirementSetId,							RequirementSetType)VALUES
('GOLDEN_PLOT_IS_FARM_CANAL_ADJACENT_REQUIREMENTS',	'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLOT_IS_FARM_DAM_ADJACENT_REQUIREMENTS',	'REQUIREMENTSET_TEST_ALL');
---------------------------------------------------------------------------------------------------------------
-- RequirementSetRequirements
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,							RequirementId)VALUES
('GOLDEN_PLOT_IS_FARM_CANAL_ADJACENT_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_CANAL'),
('GOLDEN_PLOT_IS_FARM_CANAL_ADJACENT_REQUIREMENTS',	'REQUIRES_PLOT_HAS_FARM'),
('GOLDEN_PLOT_IS_FARM_DAM_ADJACENT_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_DAM'),
('GOLDEN_PLOT_IS_FARM_DAM_ADJACENT_REQUIREMENTS',	'REQUIRES_PLOT_HAS_FARM');

