INSERT OR REPLACE INTO Types (Type, Kind) VALUES 
('MODIFIER_PLAYER_CITIES_ADJUST_YIELD_FOR_FLOOD', 'KIND_MODIFIER');
INSERT OR REPLACE INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES 
('MODIFIER_PLAYER_CITIES_ADJUST_YIELD_FOR_FLOOD', 'COLLECTION_PLAYER_CITIES', 'EFFECT_ADJUST_CITY_YIELD_PER_FLOOD');
-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_CLEOPATRA_ALT';
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_LEADER_CLEOPATRA_ALT',	'CLEOPATRA_FLOODPLAINS_APPEAL'),
('TRAIT_LEADER_CLEOPATRA_ALT',	'GA_CLEOPATRA_FLOODPLAINS_GRASSLAND_APPEAL'),
('TRAIT_LEADER_CLEOPATRA_ALT',	'GA_CLEOPATRA_FLOODPLAINS_PLAINS_APPEAL'),
('TRAIT_LEADER_CLEOPATRA_ALT',	'GA_CLEOPATRA_FLOODPLAINS_CHARMING_CULTURE'),
('TRAIT_LEADER_CLEOPATRA_ALT',	'GA_CLEOPATRA_FLOODPLAINS_CHARMING_FAITH'),
('TRAIT_LEADER_CLEOPATRA_ALT',	'GA_CLEOPATRA_FLOODPLAINS_BREATHTAKING_CULTURE'),
('TRAIT_LEADER_CLEOPATRA_ALT',	'GA_CLEOPATRA_FLOODPLAINS_BREATHTAKING_FAITH'),
('TRAIT_LEADER_CLEOPATRA_ALT',	'GA_CLEOPATRA_FLOOD_PRODUCTION');
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('GA_CLEOPATRA_FLOOD_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_FOR_FLOOD', 0, 0, 0, NULL, NULL);
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES 
('GA_CLEOPATRA_FLOODPLAINS_GRASSLAND_APPEAL' , 'MODIFIER_PLAYER_CITIES_ADJUST_FEATURE_APPEAL_MODIFIER' , 0 , 0 , NULL),
('GA_CLEOPATRA_FLOODPLAINS_PLAINS_APPEAL' , 'MODIFIER_PLAYER_CITIES_ADJUST_FEATURE_APPEAL_MODIFIER' , 0 , 0 , NULL ),
('GA_CLEOPATRA_FLOODPLAINS_CHARMING_CULTURE' , 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD' , 0 , 0 , 'GA_PLOT_HAS_FLOODPLAINS_CHARMING_REQUIREMENTS' ),
('GA_CLEOPATRA_FLOODPLAINS_CHARMING_FAITH' , 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD' , 0 , 0 , 'GA_PLOT_HAS_FLOODPLAINS_CHARMING_REQUIREMENTS' ),
('GA_CLEOPATRA_FLOODPLAINS_BREATHTAKING_CULTURE' , 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD' , 0 , 0 , 'GA_PLOT_HAS_FLOODPLAINS_BREATHTAKING_REQUIREMENTS' ),
('GA_CLEOPATRA_FLOODPLAINS_BREATHTAKING_FAITH' , 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD' , 0 , 0 , 'GA_PLOT_HAS_FLOODPLAINS_BREATHTAKING_REQUIREMENTS' );

-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
UPDATE ModifierArguments SET  Value = 1
WHERE ModifierId = 'CLEOPATRA_FLOODPLAINS_APPEAL' AND Name = 'Amount';

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('GA_CLEOPATRA_FLOODPLAINS_GRASSLAND_APPEAL', 				'FeatureType', 	'FEATURE_FLOODPLAINS_GRASSLAND'),
('GA_CLEOPATRA_FLOODPLAINS_GRASSLAND_APPEAL', 				'Amount', 		1), 
('GA_CLEOPATRA_FLOODPLAINS_PLAINS_APPEAL', 					'FeatureType', 	'FEATURE_FLOODPLAINS_PLAINS'),
('GA_CLEOPATRA_FLOODPLAINS_PLAINS_APPEAL', 					'Amount', 		1), 
('GA_CLEOPATRA_FLOOD_PRODUCTION', 					'YieldType', 	'YIELD_PRODUCTION'),
('GA_CLEOPATRA_FLOOD_PRODUCTION', 					'Amount', 		1), 
('GA_CLEOPATRA_FLOODPLAINS_CHARMING_CULTURE' , 		'YieldType' , 	'YIELD_CULTURE'  ),
('GA_CLEOPATRA_FLOODPLAINS_CHARMING_CULTURE' , 		'Amount' , 		1  ),
('GA_CLEOPATRA_FLOODPLAINS_CHARMING_FAITH' , 		'YieldType' , 	'YIELD_FAITH'  ),
('GA_CLEOPATRA_FLOODPLAINS_CHARMING_FAITH' , 		'Amount' , 		1  ),
('GA_CLEOPATRA_FLOODPLAINS_BREATHTAKING_CULTURE' , 	'YieldType' , 	'YIELD_CULTURE'  ),
('GA_CLEOPATRA_FLOODPLAINS_BREATHTAKING_CULTURE' , 	'Amount' , 		1  ),
('GA_CLEOPATRA_FLOODPLAINS_BREATHTAKING_FAITH' , 	'YieldType' , 	'YIELD_FAITH'  ),
('GA_CLEOPATRA_FLOODPLAINS_BREATHTAKING_FAITH' , 	'Amount' , 		1  );

---------------------------------------------------------------------------------------------------------------
-- RequirementSets
---------------------------------------------------------------------------------------------------------------
INSERT INTO RequirementSets
(RequirementSetId,										RequirementSetType) VALUES	
('GA_PLOT_HAS_FLOODPLAINS_CHARMING_REQUIREMENTS',			'REQUIREMENTSET_TEST_ALL'),
('GA_PLOT_HAS_FLOODPLAINS_BREATHTAKING_REQUIREMENTS',	    'REQUIREMENTSET_TEST_ALL');

---------------------------------------------------------------------------------------------------------------					
-- RequirementSetRequirements
---------------------------------------------------------------------------------------------------------------
INSERT INTO RequirementSetRequirements
(RequirementSetId,										RequirementId) VALUES	
('GA_PLOT_HAS_FLOODPLAINS_CHARMING_REQUIREMENTS',				'GOLDEN_REQUIRES_PLOT_HAS_ANY_FLOODPLAINS'),
('GA_PLOT_HAS_FLOODPLAINS_CHARMING_REQUIREMENTS',				'GOLDEN_REQUIRES_CHARMING_APPEAL'),
('GA_PLOT_HAS_FLOODPLAINS_BREATHTAKING_REQUIREMENTS',			'GOLDEN_REQUIRES_PLOT_HAS_ANY_FLOODPLAINS'),
('GA_PLOT_HAS_FLOODPLAINS_BREATHTAKING_REQUIREMENTS',			'GOLDEN_REQUIRES_BREATHTAKING_APPEAL');