-- RF_Table
-- Author: Flactine
-- DateCreated: 10/11/2023 10:23:55 PM
--------------------------------------------------------------
CREATE TABLE IF NOT EXISTS 'GA_RiseFall'(
    'CivilizationType' TEXT NOT NULL,
    'GloriousEra' TEXT NOT NULL DEFAULT 'NO_ERA',
    'DarkEra' TEXT NOT NULL DEFAULT 'NO_ERA',
    PRIMARY KEY (CivilizationType)
);

INSERT OR REPLACE INTO GA_RiseFall
(CivilizationType, 					GloriousEra, 		DarkEra) 
VALUES
('CIVILIZATION_FLAC_VOCALOID',		'ERA_INFORMATION',	'ERA_FUTURE'),
('CIVILIZATION_FLAC_LEONE',			'ERA_ATOMIC',		'ERA_INFORMATION'),
('CIVILIZATION_FLAC_VERCETTI',		'ERA_ATOMIC',		'ERA_INFORMATION'),
('CIVILIZATION_FLAC_GROVE',			'ERA_ATOMIC',		'ERA_INFORMATION'),
('CIVILIZATION_FLAC_GUP',			'ERA_MODERN',		'ERA_INFORMATION'),
('CIVILIZATION_FLAC_ACADEMY',		'ERA_INFORMATION',	'ERA_FUTURE'),
('CIVILIZATION_FLAC_LUNARMAIDEN',	'ERA_ATOMIC',		'ERA_INFORMATION'),
('CIVILIZATION_FLAC_KANCOLLE',		'ERA_MODERN',		'ERA_ATOMIC'),
('CIVILIZATION_FLAC_POWDERTOY',		'ERA_ATOMIC',		'ERA_ANCIENT'),
('CIVILIZATION_FLAC_AICHANNEL',		'ERA_INFORMATION',	'ERA_FUTURE'),
('CIVILIZATION_FLAC_SMB',			'ERA_MEDIEVAL',		'ERA_RENAISSANCE'),
('CIVILIZATION_FLAC_KCORP',			'ERA_ATOMIC',		'ERA_INFORMATION'),
('CIVILIZATION_FLAC_SPICEWOLF',		'ERA_MEDIEVAL',		'ERA_RENAISSANCE'),
('CIVILIZATION_FLAC_MINECRAFT',		'ERA_MEDIEVAL',		'ERA_INDUSTRIAL'),
('CIVILIZATION_FLAC_LIZPIRATE',		'ERA_RENAISSANCE',	'ERA_MODERN'),
('CIVILIZATION_FLAC_SHIKI',			'ERA_INFORMATION',	'ERA_FUTURE'),
('CIVILIZATION_FLAC_IDOLMASTER',	'ERA_INFORMATION',	'ERA_FUTURE'),
('CIVILIZATION_FLAC_IMCG',			'ERA_INFORMATION',	'ERA_FUTURE'),
('CIVILIZATION_FLAC_LOVELIVE',		'ERA_INFORMATION',	'ERA_FUTURE'),
('CIVILIZATION_FLAC_LLSS',			'ERA_INFORMATION',	'ERA_FUTURE'),
('CIVILIZATION_FLAC_LUSTROUS',		'ERA_CLASSICAL',	'ERA_INFORMATION'),
('CIVILIZATION_FLAC_HTT',			'ERA_INFORMATION',	'ERA_FUTURE');

CREATE TABLE IF NOT EXISTS 'GASCRF_CivilizationTraits'(
    'CivilizationType' TEXT NOT NULL,
    'TraitType' TEXT NOT NULL
);

INSERT OR REPLACE INTO GASCRF_CivilizationTraits 
(CivilizationType,              	TraitType) 
VALUES
('CIVILIZATION_FLAC_VOCALOID',		'TRAIT_GASCRF_INFORMATION_FUTURE'),
('CIVILIZATION_FLAC_LEONE',			'TRAIT_GASCRF_ATOMIC_INFORMATION'),
('CIVILIZATION_FLAC_VERCETTI',		'TRAIT_GASCRF_ATOMIC_INFORMATION'),
('CIVILIZATION_FLAC_GROVE',			'TRAIT_GASCRF_ATOMIC_INFORMATION'),
('CIVILIZATION_FLAC_GUP',			'TRAIT_GASCRF_ATOMIC_INFORMATION'),
('CIVILIZATION_FLAC_ACADEMY',		'TRAIT_GASCRF_INFORMATION_FUTURE'),
('CIVILIZATION_FLAC_LUNARMAIDEN',	'TRAIT_GASCRF_ATOMIC_INFORMATION'),
('CIVILIZATION_FLAC_KANCOLLE',		'TRAIT_GASCRF_MODERN_ATOMIC'),
('CIVILIZATION_FLAC_POWDERTOY',		'TRAIT_GASCRF_ATOMIC_ANCIENT'),
('CIVILIZATION_FLAC_AICHANNEL',		'TRAIT_GASCRF_INFORMATION_FUTURE'),
('CIVILIZATION_FLAC_SMB',			'TRAIT_GASCRF_MEDIEVAL_RENAISSANCE'),
('CIVILIZATION_FLAC_KCORP',			'TRAIT_GASCRF_ATOMIC_INFORMATION'),
('CIVILIZATION_FLAC_SPICEWOLF',		'TRAIT_GASCRF_MEDIEVAL_RENAISSANCE'),
('CIVILIZATION_FLAC_MINECRAFT',		'TRAIT_GASCRF_MEDIEVAL_INDUSTRIAL'),
('CIVILIZATION_FLAC_LIZPIRATE',		'TRAIT_GASCRF_RENAISSANCE_MODERN'),
('CIVILIZATION_FLAC_SHIKI',			'TRAIT_GASCRF_INFORMATION_FUTURE'),
('CIVILIZATION_FLAC_IDOLMASTER',	'TRAIT_GASCRF_INFORMATION_FUTURE'),
('CIVILIZATION_FLAC_IMCG',			'TRAIT_GASCRF_INFORMATION_FUTURE'),
('CIVILIZATION_FLAC_LOVELIVE',		'TRAIT_GASCRF_INFORMATION_FUTURE'),
('CIVILIZATION_FLAC_LLSS',			'TRAIT_GASCRF_INFORMATION_FUTURE'),
('CIVILIZATION_FLAC_LUSTROUS',		'TRAIT_GASCRF_CLASSICAL_INFORMATION'),
('CIVILIZATION_FLAC_HTT',			'TRAIT_GASCRF_INFORMATION_FUTURE');

--Others
INSERT OR REPLACE INTO GA_RiseFall
(CivilizationType, 					GloriousEra, 		DarkEra) 
VALUES
('CIVILIZATION_KHJY',				'ERA_RENAISSANCE',	'ERA_INDUSTRIAL'),
('CIVILIZATION_QSK',				'ERA_MEDIEVAL',		'ERA_RENAISSANCE'),
('CIVILIZATION_JKS',				'ERA_CLASSICAL',	'ERA_RENAISSANCE'),
('CIVILIZATION_OP_IBERIA',			'ERA_RENAISSANCE',	'ERA_ATOMIC'),
('CIVILIZATION_OP_LEITHANIEN',		'ERA_MEDIEVAL',		'ERA_INDUSTRIAL'),
('CIVILIZATION_OP_YAN',				'ERA_CLASSICAL',	'ERA_INDUSTRIAL'),
('CIVILIZATION_OP_LUNGMEN',			'ERA_INFORMATION',	'ERA_INDUSTRIAL');

INSERT OR REPLACE INTO GASCRF_CivilizationTraits 
(CivilizationType,              	TraitType) 
VALUES
('CIVILIZATION_KHJY',				'TRAIT_GASCRF_RENAISSANCE_INDUSTRIAL'),
('CIVILIZATION_QSK',				'TRAIT_GASCRF_MEDIEVAL_RENAISSANCE'),
('CIVILIZATION_JKS',				'TRAIT_GASCRF_CLASSICAL_RENAISSANCE'),
('CIVILIZATION_OP_IBERIA',			'TRAIT_GASCRF_RENAISSANCE_ATOMIC'),
('CIVILIZATION_OP_LEITHANIEN',		'TRAIT_GASCRF_MEDIEVAL_INDUSTRIAL'),
('CIVILIZATION_OP_YAN',				'TRAIT_GASCRF_CLASSICAL_INDUSTRIAL'),
('CIVILIZATION_OP_LUNGMEN',			'TRAIT_GASCRF_INFORMATION_INDUSTRIAL');

INSERT OR REPLACE INTO CivilizationTraits 
(CivilizationType,		TraitType)
SELECT	
a.CivilizationType,		b.TraitType
FROM Civilizations AS a, GASCRF_CivilizationTraits AS b
WHERE a.CivilizationType = b.CivilizationType;

CREATE TRIGGER Trig_GASCRF_Traits
AFTER INSERT ON Civilizations
WHEN NEW.CivilizationType IS NOT NULL
BEGIN
	DELETE FROM CivilizationTraits WHERE TraitType LIKE 'TRAIT_GASCRF_%';
	
	INSERT OR REPLACE INTO CivilizationTraits 
	(CivilizationType,		TraitType)
	SELECT	
	a.CivilizationType,		b.TraitType
	FROM Civilizations AS a, GASCRF_CivilizationTraits AS b
	WHERE a.CivilizationType = b.CivilizationType;
END;