-- RF_Traits
-- Author: Flactine
-- DateCreated: 10/11/2023 10:43:31 PM
--------------------------------------------------------------
INSERT OR REPLACE INTO Types 
(Type,										Kind)  
VALUES
('TRAIT_GASCRF_ANCIENT_CLASSICAL',			'KIND_TRAIT'),
('TRAIT_GASCRF_ANCIENT_MEDIEVAL',			'KIND_TRAIT'),
('TRAIT_GASCRF_ANCIENT_RENAISSANCE',		'KIND_TRAIT'),
('TRAIT_GASCRF_ANCIENT_INDUSTRIAL',			'KIND_TRAIT'),
('TRAIT_GASCRF_ANCIENT_MODERN',				'KIND_TRAIT'),
('TRAIT_GASCRF_ANCIENT_ATOMIC',				'KIND_TRAIT'),
('TRAIT_GASCRF_ANCIENT_INFORMATION',		'KIND_TRAIT'),
('TRAIT_GASCRF_ANCIENT_FUTURE',				'KIND_TRAIT'),
('TRAIT_GASCRF_CLASSICAL_ANCIENT',			'KIND_TRAIT'),
('TRAIT_GASCRF_CLASSICAL_MEDIEVAL',			'KIND_TRAIT'),
('TRAIT_GASCRF_CLASSICAL_RENAISSANCE',		'KIND_TRAIT'),
('TRAIT_GASCRF_CLASSICAL_INDUSTRIAL',		'KIND_TRAIT'),
('TRAIT_GASCRF_CLASSICAL_MODERN',			'KIND_TRAIT'),
('TRAIT_GASCRF_CLASSICAL_ATOMIC',			'KIND_TRAIT'),
('TRAIT_GASCRF_CLASSICAL_INFORMATION',		'KIND_TRAIT'),
('TRAIT_GASCRF_CLASSICAL_FUTURE',			'KIND_TRAIT'),
('TRAIT_GASCRF_MEDIEVAL_ANCIENT',			'KIND_TRAIT'),
('TRAIT_GASCRF_MEDIEVAL_CLASSICAL',			'KIND_TRAIT'),
('TRAIT_GASCRF_MEDIEVAL_RENAISSANCE',		'KIND_TRAIT'),
('TRAIT_GASCRF_MEDIEVAL_INDUSTRIAL',		'KIND_TRAIT'),
('TRAIT_GASCRF_MEDIEVAL_MODERN',			'KIND_TRAIT'),
('TRAIT_GASCRF_MEDIEVAL_ATOMIC',			'KIND_TRAIT'),
('TRAIT_GASCRF_MEDIEVAL_INFORMATION',		'KIND_TRAIT'),
('TRAIT_GASCRF_MEDIEVAL_FUTURE',			'KIND_TRAIT'),
('TRAIT_GASCRF_RENAISSANCE_ANCIENT',		'KIND_TRAIT'),
('TRAIT_GASCRF_RENAISSANCE_CLASSICAL',		'KIND_TRAIT'),
('TRAIT_GASCRF_RENAISSANCE_MEDIEVAL',		'KIND_TRAIT'),
('TRAIT_GASCRF_RENAISSANCE_INDUSTRIAL',		'KIND_TRAIT'),
('TRAIT_GASCRF_RENAISSANCE_MODERN',			'KIND_TRAIT'),
('TRAIT_GASCRF_RENAISSANCE_ATOMIC',			'KIND_TRAIT'),
('TRAIT_GASCRF_RENAISSANCE_INFORMATION',	'KIND_TRAIT'),
('TRAIT_GASCRF_RENAISSANCE_FUTURE',			'KIND_TRAIT'),
('TRAIT_GASCRF_INDUSTRIAL_ANCIENT',			'KIND_TRAIT'),
('TRAIT_GASCRF_INDUSTRIAL_CLASSICAL',		'KIND_TRAIT'),
('TRAIT_GASCRF_INDUSTRIAL_MEDIEVAL',		'KIND_TRAIT'),
('TRAIT_GASCRF_INDUSTRIAL_RENAISSANCE',		'KIND_TRAIT'),
('TRAIT_GASCRF_INDUSTRIAL_MODERN',			'KIND_TRAIT'),
('TRAIT_GASCRF_INDUSTRIAL_ATOMIC',			'KIND_TRAIT'),
('TRAIT_GASCRF_INDUSTRIAL_INFORMATION',		'KIND_TRAIT'),
('TRAIT_GASCRF_INDUSTRIAL_FUTURE',			'KIND_TRAIT'),
('TRAIT_GASCRF_MODERN_ANCIENT',				'KIND_TRAIT'),
('TRAIT_GASCRF_MODERN_CLASSICAL',			'KIND_TRAIT'),
('TRAIT_GASCRF_MODERN_MEDIEVAL',			'KIND_TRAIT'),
('TRAIT_GASCRF_MODERN_RENAISSANCE',			'KIND_TRAIT'),
('TRAIT_GASCRF_MODERN_INDUSTRIAL',			'KIND_TRAIT'),
('TRAIT_GASCRF_MODERN_ATOMIC',				'KIND_TRAIT'),
('TRAIT_GASCRF_MODERN_INFORMATION',			'KIND_TRAIT'),
('TRAIT_GASCRF_MODERN_FUTURE',				'KIND_TRAIT'),
('TRAIT_GASCRF_ATOMIC_ANCIENT',				'KIND_TRAIT'),
('TRAIT_GASCRF_ATOMIC_CLASSICAL',			'KIND_TRAIT'),
('TRAIT_GASCRF_ATOMIC_MEDIEVAL',			'KIND_TRAIT'),
('TRAIT_GASCRF_ATOMIC_RENAISSANCE',			'KIND_TRAIT'),
('TRAIT_GASCRF_ATOMIC_INDUSTRIAL',			'KIND_TRAIT'),
('TRAIT_GASCRF_ATOMIC_MODERN',				'KIND_TRAIT'),
('TRAIT_GASCRF_ATOMIC_INFORMATION',			'KIND_TRAIT'),
('TRAIT_GASCRF_ATOMIC_FUTURE',				'KIND_TRAIT'),
('TRAIT_GASCRF_INFORMATION_ANCIENT',		'KIND_TRAIT'),
('TRAIT_GASCRF_INFORMATION_CLASSICAL',		'KIND_TRAIT'),
('TRAIT_GASCRF_INFORMATION_MEDIEVAL',		'KIND_TRAIT'),
('TRAIT_GASCRF_INFORMATION_RENAISSANCE',	'KIND_TRAIT'),
('TRAIT_GASCRF_INFORMATION_INDUSTRIAL',		'KIND_TRAIT'),
('TRAIT_GASCRF_INFORMATION_MODERN',			'KIND_TRAIT'),
('TRAIT_GASCRF_INFORMATION_ATOMIC',			'KIND_TRAIT'),
('TRAIT_GASCRF_INFORMATION_FUTURE',			'KIND_TRAIT'),
('TRAIT_GASCRF_FUTURE_ANCIENT',				'KIND_TRAIT'),
('TRAIT_GASCRF_FUTURE_CLASSICAL',			'KIND_TRAIT'),
('TRAIT_GASCRF_FUTURE_MEDIEVAL',			'KIND_TRAIT'),
('TRAIT_GASCRF_FUTURE_RENAISSANCE',			'KIND_TRAIT'),
('TRAIT_GASCRF_FUTURE_INDUSTRIAL',			'KIND_TRAIT'),
('TRAIT_GASCRF_FUTURE_MODERN',				'KIND_TRAIT'),
('TRAIT_GASCRF_FUTURE_ATOMIC',				'KIND_TRAIT'),
('TRAIT_GASCRF_FUTURE_INFORMATION',			'KIND_TRAIT');

CREATE TABLE IF NOT EXISTS TEMP_GASCRF_Traits
	(
	"TraitType"	TEXT	NOT NULL,
	"Glorious"	INTEGER NOT NULL DEFAULT 0,
	"Dark"		INTEGER NOT NULL DEFAULT 0
	);
	
INSERT OR REPLACE INTO TEMP_GASCRF_Traits 
(TraitType,									Glorious,		Dark)  
VALUES
('TRAIT_GASCRF_ANCIENT_CLASSICAL',			1,				2),
('TRAIT_GASCRF_ANCIENT_MEDIEVAL',			1,				3),
('TRAIT_GASCRF_ANCIENT_RENAISSANCE',		1,				4),
('TRAIT_GASCRF_ANCIENT_INDUSTRIAL',			1,				5),
('TRAIT_GASCRF_ANCIENT_MODERN',				1,				6),
('TRAIT_GASCRF_ANCIENT_ATOMIC',				1,				7),
('TRAIT_GASCRF_ANCIENT_INFORMATION',		1,				8),
('TRAIT_GASCRF_ANCIENT_FUTURE',				1,				9),
('TRAIT_GASCRF_CLASSICAL_ANCIENT',			2,				1),
('TRAIT_GASCRF_CLASSICAL_MEDIEVAL',			2,				3),
('TRAIT_GASCRF_CLASSICAL_RENAISSANCE',		2,				4),
('TRAIT_GASCRF_CLASSICAL_INDUSTRIAL',		2,				5),
('TRAIT_GASCRF_CLASSICAL_MODERN',			2,				6),
('TRAIT_GASCRF_CLASSICAL_ATOMIC',			2,				7),
('TRAIT_GASCRF_CLASSICAL_INFORMATION',		2,				8),
('TRAIT_GASCRF_CLASSICAL_FUTURE',			2,				9),
('TRAIT_GASCRF_MEDIEVAL_ANCIENT',			3,				1),
('TRAIT_GASCRF_MEDIEVAL_CLASSICAL',			3,				2),
('TRAIT_GASCRF_MEDIEVAL_RENAISSANCE',		3,				4),
('TRAIT_GASCRF_MEDIEVAL_INDUSTRIAL',		3,				5),
('TRAIT_GASCRF_MEDIEVAL_MODERN',			3,				6),
('TRAIT_GASCRF_MEDIEVAL_ATOMIC',			3,				7),
('TRAIT_GASCRF_MEDIEVAL_INFORMATION',		3,				8),
('TRAIT_GASCRF_MEDIEVAL_FUTURE',			3,				9),
('TRAIT_GASCRF_RENAISSANCE_ANCIENT',		4,				1),
('TRAIT_GASCRF_RENAISSANCE_CLASSICAL',		4,				2),
('TRAIT_GASCRF_RENAISSANCE_MEDIEVAL',		4,				3),
('TRAIT_GASCRF_RENAISSANCE_INDUSTRIAL',		4,				5),
('TRAIT_GASCRF_RENAISSANCE_MODERN',			4,				6),
('TRAIT_GASCRF_RENAISSANCE_ATOMIC',			4,				7),
('TRAIT_GASCRF_RENAISSANCE_INFORMATION',	4,				8),
('TRAIT_GASCRF_RENAISSANCE_FUTURE',			4,				9),
('TRAIT_GASCRF_INDUSTRIAL_ANCIENT',			5,				1),
('TRAIT_GASCRF_INDUSTRIAL_CLASSICAL',		5,				2),
('TRAIT_GASCRF_INDUSTRIAL_MEDIEVAL',		5,				3),
('TRAIT_GASCRF_INDUSTRIAL_RENAISSANCE',		5,				4),
('TRAIT_GASCRF_INDUSTRIAL_MODERN',			5,				6),
('TRAIT_GASCRF_INDUSTRIAL_ATOMIC',			5,				7),
('TRAIT_GASCRF_INDUSTRIAL_INFORMATION',		5,				8),
('TRAIT_GASCRF_INDUSTRIAL_FUTURE',			5,				9),
('TRAIT_GASCRF_MODERN_ANCIENT',				6,				1),
('TRAIT_GASCRF_MODERN_CLASSICAL',			6,				2),
('TRAIT_GASCRF_MODERN_MEDIEVAL',			6,				3),
('TRAIT_GASCRF_MODERN_RENAISSANCE',			6,				4),
('TRAIT_GASCRF_MODERN_INDUSTRIAL',			6,				5),
('TRAIT_GASCRF_MODERN_ATOMIC',				6,				7),
('TRAIT_GASCRF_MODERN_INFORMATION',			6,				8),
('TRAIT_GASCRF_MODERN_FUTURE',				6,				9),
('TRAIT_GASCRF_ATOMIC_ANCIENT',				7,				1),
('TRAIT_GASCRF_ATOMIC_CLASSICAL',			7,				2),
('TRAIT_GASCRF_ATOMIC_MEDIEVAL',			7,				3),
('TRAIT_GASCRF_ATOMIC_RENAISSANCE',			7,				4),
('TRAIT_GASCRF_ATOMIC_INDUSTRIAL',			7,				5),
('TRAIT_GASCRF_ATOMIC_MODERN',				7,				6),
('TRAIT_GASCRF_ATOMIC_INFORMATION',			7,				8),
('TRAIT_GASCRF_ATOMIC_FUTURE',				7,				9),
('TRAIT_GASCRF_INFORMATION_ANCIENT',		8,				1),
('TRAIT_GASCRF_INFORMATION_CLASSICAL',		8,				2),
('TRAIT_GASCRF_INFORMATION_MEDIEVAL',		8,				3),
('TRAIT_GASCRF_INFORMATION_RENAISSANCE',	8,				4),
('TRAIT_GASCRF_INFORMATION_INDUSTRIAL',		8,				5),
('TRAIT_GASCRF_INFORMATION_MODERN',			8,				6),
('TRAIT_GASCRF_INFORMATION_ATOMIC',			8,				7),
('TRAIT_GASCRF_INFORMATION_FUTURE',			8,				9),
('TRAIT_GASCRF_FUTURE_ANCIENT',				9,				1),
('TRAIT_GASCRF_FUTURE_CLASSICAL',			1,				2),
('TRAIT_GASCRF_FUTURE_MEDIEVAL',			1,				3),
('TRAIT_GASCRF_FUTURE_RENAISSANCE',			1,				4),
('TRAIT_GASCRF_FUTURE_INDUSTRIAL',			1,				5),
('TRAIT_GASCRF_FUTURE_MODERN',				1,				6),
('TRAIT_GASCRF_FUTURE_ATOMIC',				1,				7),
('TRAIT_GASCRF_FUTURE_INFORMATION',			1,				8);

INSERT OR REPLACE INTO Traits 
(TraitType,									Name,						Description) 
VALUES           
('TRAIT_GASCRF_ANCIENT_CLASSICAL',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ANCIENT_CLASSICAL_DESCRIPTION'),
('TRAIT_GASCRF_ANCIENT_MEDIEVAL',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ANCIENT_MEDIEVAL_DESCRIPTION'),
('TRAIT_GASCRF_ANCIENT_RENAISSANCE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ANCIENT_RENAISSANCE_DESCRIPTION'),
('TRAIT_GASCRF_ANCIENT_INDUSTRIAL',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ANCIENT_INDUSTRIAL_DESCRIPTION'),
('TRAIT_GASCRF_ANCIENT_MODERN',				'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ANCIENT_MODERN_DESCRIPTION'),
('TRAIT_GASCRF_ANCIENT_ATOMIC',				'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ANCIENT_ATOMIC_DESCRIPTION'),
('TRAIT_GASCRF_ANCIENT_INFORMATION',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ANCIENT_INFORMATION_DESCRIPTION'),
('TRAIT_GASCRF_ANCIENT_FUTURE',				'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ANCIENT_FUTURE_DESCRIPTION'),
('TRAIT_GASCRF_CLASSICAL_ANCIENT',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_CLASSICAL_ANCIENT_DESCRIPTION'),
('TRAIT_GASCRF_CLASSICAL_MEDIEVAL',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_CLASSICAL_MEDIEVAL_DESCRIPTION'),
('TRAIT_GASCRF_CLASSICAL_RENAISSANCE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_CLASSICAL_RENAISSANCE_DESCRIPTION'),
('TRAIT_GASCRF_CLASSICAL_INDUSTRIAL',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_CLASSICAL_INDUSTRIAL_DESCRIPTION'),
('TRAIT_GASCRF_CLASSICAL_MODERN',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_CLASSICAL_MODERN_DESCRIPTION'),
('TRAIT_GASCRF_CLASSICAL_ATOMIC',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_CLASSICAL_ATOMIC_DESCRIPTION'),
('TRAIT_GASCRF_CLASSICAL_INFORMATION',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_CLASSICAL_INFORMATION_DESCRIPTION'),
('TRAIT_GASCRF_CLASSICAL_FUTURE',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_CLASSICAL_FUTURE_DESCRIPTION'),
('TRAIT_GASCRF_MEDIEVAL_ANCIENT',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_ANCIENT_DESCRIPTION'),
('TRAIT_GASCRF_MEDIEVAL_CLASSICAL',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_CLASSICAL_DESCRIPTION'),
('TRAIT_GASCRF_MEDIEVAL_RENAISSANCE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_RENAISSANCE_DESCRIPTION'),
('TRAIT_GASCRF_MEDIEVAL_INDUSTRIAL',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_INDUSTRIAL_DESCRIPTION'),
('TRAIT_GASCRF_MEDIEVAL_MODERN',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_MODERN_DESCRIPTION'),
('TRAIT_GASCRF_MEDIEVAL_ATOMIC',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_ATOMIC_DESCRIPTION'),
('TRAIT_GASCRF_MEDIEVAL_INFORMATION',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_INFORMATION_DESCRIPTION'),
('TRAIT_GASCRF_MEDIEVAL_FUTURE',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_FUTURE_DESCRIPTION'),
('TRAIT_GASCRF_RENAISSANCE_ANCIENT',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_RENAISSANCE_ANCIENT_DESCRIPTION'),
('TRAIT_GASCRF_RENAISSANCE_CLASSICAL',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_RENAISSANCE_CLASSICAL_DESCRIPTION'),
('TRAIT_GASCRF_RENAISSANCE_MEDIEVAL',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_RENAISSANCE_MEDIEVAL_DESCRIPTION'),
('TRAIT_GASCRF_RENAISSANCE_INDUSTRIAL',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_RENAISSANCE_INDUSTRIAL_DESCRIPTION'),
('TRAIT_GASCRF_RENAISSANCE_MODERN',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_RENAISSANCE_MODERN_DESCRIPTION'),
('TRAIT_GASCRF_RENAISSANCE_ATOMIC',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_RENAISSANCE_ATOMIC_DESCRIPTION'),
('TRAIT_GASCRF_RENAISSANCE_INFORMATION',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_RENAISSANCE_INFORMATION_DESCRIPTION'),
('TRAIT_GASCRF_RENAISSANCE_FUTURE',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_RENAISSANCE_FUTURE_DESCRIPTION'),
('TRAIT_GASCRF_INDUSTRIAL_ANCIENT',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INDUSTRIAL_ANCIENT_DESCRIPTION'),
('TRAIT_GASCRF_INDUSTRIAL_CLASSICAL',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INDUSTRIAL_CLASSICAL_DESCRIPTION'),
('TRAIT_GASCRF_INDUSTRIAL_MEDIEVAL',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INDUSTRIAL_MEDIEVAL_DESCRIPTION'),
('TRAIT_GASCRF_INDUSTRIAL_RENAISSANCE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INDUSTRIAL_RENAISSANCE_DESCRIPTION'),
('TRAIT_GASCRF_INDUSTRIAL_MODERN',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INDUSTRIAL_MODERN_DESCRIPTION'),
('TRAIT_GASCRF_INDUSTRIAL_ATOMIC',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INDUSTRIAL_ATOMIC_DESCRIPTION'),
('TRAIT_GASCRF_INDUSTRIAL_INFORMATION',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INDUSTRIAL_INFORMATION_DESCRIPTION'),
('TRAIT_GASCRF_INDUSTRIAL_FUTURE',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INDUSTRIAL_FUTURE_DESCRIPTION'),
('TRAIT_GASCRF_MODERN_ANCIENT',				'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MODERN_ANCIENT_DESCRIPTION'),
('TRAIT_GASCRF_MODERN_CLASSICAL',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MODERN_CLASSICAL_DESCRIPTION'),
('TRAIT_GASCRF_MODERN_MEDIEVAL',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MODERN_MEDIEVAL_DESCRIPTION'),
('TRAIT_GASCRF_MODERN_RENAISSANCE',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MODERN_RENAISSANCE_DESCRIPTION'),
('TRAIT_GASCRF_MODERN_INDUSTRIAL',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MODERN_INDUSTRIAL_DESCRIPTION'),
('TRAIT_GASCRF_MODERN_ATOMIC',				'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MODERN_ATOMIC_DESCRIPTION'),
('TRAIT_GASCRF_MODERN_INFORMATION',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MODERN_INFORMATION_DESCRIPTION'),
('TRAIT_GASCRF_MODERN_FUTURE',				'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MODERN_FUTURE_DESCRIPTION'),
('TRAIT_GASCRF_ATOMIC_ANCIENT',				'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ATOMIC_ANCIENT_DESCRIPTION'),
('TRAIT_GASCRF_ATOMIC_CLASSICAL',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ATOMIC_CLASSICAL_DESCRIPTION'),
('TRAIT_GASCRF_ATOMIC_MEDIEVAL',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ATOMIC_MEDIEVAL_DESCRIPTION'),
('TRAIT_GASCRF_ATOMIC_RENAISSANCE',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ATOMIC_RENAISSANCE_DESCRIPTION'),
('TRAIT_GASCRF_ATOMIC_INDUSTRIAL',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ATOMIC_INDUSTRIAL_DESCRIPTION'),
('TRAIT_GASCRF_ATOMIC_MODERN',				'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ATOMIC_MODERN_DESCRIPTION'),
('TRAIT_GASCRF_ATOMIC_INFORMATION',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ATOMIC_INFORMATION_DESCRIPTION'),
('TRAIT_GASCRF_ATOMIC_FUTURE',				'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ATOMIC_FUTURE_DESCRIPTION'),
('TRAIT_GASCRF_INFORMATION_ANCIENT',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_ANCIENT_DESCRIPTION'),
('TRAIT_GASCRF_INFORMATION_CLASSICAL',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_CLASSICAL_DESCRIPTION'),
('TRAIT_GASCRF_INFORMATION_MEDIEVAL',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_MEDIEVAL_DESCRIPTION'),
('TRAIT_GASCRF_INFORMATION_RENAISSANCE',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_RENAISSANCE_DESCRIPTION'),
('TRAIT_GASCRF_INFORMATION_INDUSTRIAL',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_INDUSTRIAL_DESCRIPTION'),
('TRAIT_GASCRF_INFORMATION_MODERN',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_MODERN_DESCRIPTION'),
('TRAIT_GASCRF_INFORMATION_ATOMIC',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_ATOMIC_DESCRIPTION'),
('TRAIT_GASCRF_INFORMATION_FUTURE',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION'),
('TRAIT_GASCRF_FUTURE_ANCIENT',				'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_FUTURE_ANCIENT_DESCRIPTION'),
('TRAIT_GASCRF_FUTURE_CLASSICAL',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_FUTURE_CLASSICAL_DESCRIPTION'),
('TRAIT_GASCRF_FUTURE_MEDIEVAL',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_FUTURE_MEDIEVAL_DESCRIPTION'),
('TRAIT_GASCRF_FUTURE_RENAISSANCE',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_FUTURE_RENAISSANCE_DESCRIPTION'),
('TRAIT_GASCRF_FUTURE_INDUSTRIAL',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_FUTURE_INDUSTRIAL_DESCRIPTION'),
('TRAIT_GASCRF_FUTURE_MODERN',				'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_FUTURE_MODERN_DESCRIPTION'),
('TRAIT_GASCRF_FUTURE_ATOMIC',				'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_FUTURE_ATOMIC_DESCRIPTION'),
('TRAIT_GASCRF_FUTURE_INFORMATION',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_FUTURE_INFORMATION_DESCRIPTION');

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_ANCIENT_BUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Glorious = 1;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_CLASSICAL_BUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Glorious = 2;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_MEDIEVAL_BUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Glorious = 3;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_RENAISSANCE_BUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Glorious = 4;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_INDUSTRIAL_BUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Glorious = 5;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_MODERN_BUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Glorious = 6;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_ATOMIC_BUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Glorious = 7;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_INFORMATION_BUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Glorious = 8;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_FUTURE_BUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Glorious = 9;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_ANCIENT_DEBUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Dark = 1;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_CLASSICAL_DEBUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Dark = 2;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_MEDIEVAL_DEBUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Dark = 3;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_RENAISSANCE_DEBUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Dark = 4;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Dark = 5;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_MODERN_DEBUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Dark = 6;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_ATOMIC_DEBUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Dark = 7;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_INFORMATION_DEBUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Dark = 8;

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,		ModifierId)
SELECT	
a.TraitType,	'GOLDEN_ERA_FUTURE_DEBUFF_' || b.YieldType 
FROM TEMP_GASCRF_Traits AS a, Yields AS b
WHERE a.Dark = 9;