--首发文明
--AMERICA 美国
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_AMERICA', 'LEADER_T_ROOSEVELT', 'GOLDEN_CIVILIZATION_AMERICA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_AMERICA', 'LOC_GOLDEN_CIVILIZATION_AMERICA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_AMERICA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_AMERICA', 'LEADER_T_ROOSEVELT', 'GOLDEN_TRAIT_CIVILIZATION_AMERICA', 'ICON_CIVILIZATION_AMERICA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_AMERICA_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_AMERICA', 'LEADER_T_ROOSEVELT_ROUGHRIDER', 'GOLDEN_CIVILIZATION_AMERICA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_AMERICA', 'LOC_GOLDEN_CIVILIZATION_AMERICA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_AMERICA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_AMERICA', 'LEADER_T_ROOSEVELT_ROUGHRIDER', 'GOLDEN_TRAIT_CIVILIZATION_AMERICA', 'ICON_CIVILIZATION_AMERICA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_AMERICA_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_AMERICA', 'LEADER_ABRAHAM_LINCOLN', 'GOLDEN_CIVILIZATION_AMERICA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_AMERICA', 'LOC_GOLDEN_CIVILIZATION_AMERICA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_AMERICA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_AMERICA', 'LEADER_ABRAHAM_LINCOLN', 'GOLDEN_TRAIT_CIVILIZATION_AMERICA', 'ICON_CIVILIZATION_AMERICA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_AMERICA_DESCRIPTION', 50);

--ARABIA 阿拉伯
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_ARABIA', 'LEADER_SALADIN', 'GOLDEN_CIVILIZATION_ARABIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_ARABIA', 'LOC_GOLDEN_CIVILIZATION_ARABIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_ARABIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_ARABIA', 'LEADER_SALADIN', 'GOLDEN_TRAIT_CIVILIZATION_ARABIA', 'ICON_CIVILIZATION_ARABIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_ARABIA_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_ARABIA', 'LEADER_SALADIN_ALT', 'GOLDEN_CIVILIZATION_ARABIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_ARABIA', 'LOC_GOLDEN_CIVILIZATION_ARABIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_ARABIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_ARABIA', 'LEADER_SALADIN_ALT', 'GOLDEN_TRAIT_CIVILIZATION_ARABIA', 'ICON_CIVILIZATION_ARABIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_ARABIA_DESCRIPTION', 50);

--BRAZIL 巴西
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_BRAZIL', 'LEADER_PEDRO', 'GOLDEN_CIVILIZATION_BRAZIL_CUSTOM_FEATURES', 'ICON_CIVILIZATION_BRAZIL', 'LOC_GOLDEN_CIVILIZATION_BRAZIL_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_BRAZIL_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_BRAZIL', 'LEADER_PEDRO', 'GOLDEN_TRAIT_CIVILIZATION_BRAZIL', 'ICON_CIVILIZATION_BRAZIL', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_BRAZIL_DESCRIPTION', 50);

--CHINA 中国
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_CHINA', 'LEADER_QIN', 'GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_CHINA', 'LOC_GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_CHINA', 'LEADER_QIN', 'GOLDEN_TRAIT_CIVILIZATION_CHINA', 'ICON_CIVILIZATION_CHINA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_CHINA_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_CHINA', 'LEADER_KUBLAI_KHAN_CHINA', 'GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_CHINA', 'LOC_GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_CHINA', 'LEADER_KUBLAI_KHAN_CHINA', 'GOLDEN_TRAIT_CIVILIZATION_CHINA', 'ICON_CIVILIZATION_CHINA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_CHINA_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_CHINA', 'LEADER_YONGLE', 'GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_CHINA', 'LOC_GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_CHINA', 'LEADER_YONGLE', 'GOLDEN_TRAIT_CIVILIZATION_CHINA', 'ICON_CIVILIZATION_CHINA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_CHINA_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_CHINA', 'LEADER_WU_ZETIAN', 'GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_CHINA', 'LOC_GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_CHINA', 'LEADER_WU_ZETIAN', 'GOLDEN_TRAIT_CIVILIZATION_CHINA', 'ICON_CIVILIZATION_CHINA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_CHINA_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_CHINA', 'LEADER_QIN_ALT', 'GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_CHINA', 'LOC_GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_CHINA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_CHINA', 'LEADER_QIN_ALT', 'GOLDEN_TRAIT_CIVILIZATION_CHINA', 'ICON_CIVILIZATION_CHINA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_CHINA_DESCRIPTION', 50);

--EGYPT 埃及
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_EGYPT', 'LEADER_CLEOPATRA', 'GOLDEN_CIVILIZATION_EGYPT_CUSTOM_FEATURES', 'ICON_CIVILIZATION_EGYPT', 'LOC_GOLDEN_CIVILIZATION_EGYPT_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_EGYPT_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_EGYPT', 'LEADER_CLEOPATRA', 'GOLDEN_TRAIT_CIVILIZATION_EGYPT', 'ICON_CIVILIZATION_EGYPT', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_EGYPT_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_EGYPT', 'LEADER_CLEOPATRA_ALT', 'GOLDEN_CIVILIZATION_EGYPT_CUSTOM_FEATURES', 'ICON_CIVILIZATION_EGYPT', 'LOC_GOLDEN_CIVILIZATION_EGYPT_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_EGYPT_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_EGYPT', 'LEADER_CLEOPATRA_ALT', 'GOLDEN_TRAIT_CIVILIZATION_EGYPT', 'ICON_CIVILIZATION_EGYPT', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_EGYPT_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_EGYPT', 'LEADER_RAMSES', 'GOLDEN_CIVILIZATION_EGYPT_CUSTOM_FEATURES', 'ICON_CIVILIZATION_EGYPT', 'LOC_GOLDEN_CIVILIZATION_EGYPT_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_EGYPT_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_EGYPT', 'LEADER_RAMSES', 'GOLDEN_TRAIT_CIVILIZATION_EGYPT', 'ICON_CIVILIZATION_EGYPT', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_EGYPT_DESCRIPTION', 50);

--ENGLAND 英国
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_ENGLAND', 'LEADER_VICTORIA', 'GOLDEN_CIVILIZATION_ENGLAND_CUSTOM_FEATURES', 'ICON_CIVILIZATION_ENGLAND', 'LOC_GOLDEN_CIVILIZATION_ENGLAND_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_ENGLAND_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_ENGLAND', 'LEADER_VICTORIA', 'GOLDEN_TRAIT_CIVILIZATION_ENGLAND', 'ICON_CIVILIZATION_ENGLAND', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_ENGLAND_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_ENGLAND', 'LEADER_ELEANOR_ENGLAND', 'GOLDEN_CIVILIZATION_ENGLAND_CUSTOM_FEATURES', 'ICON_CIVILIZATION_ENGLAND', 'LOC_GOLDEN_CIVILIZATION_ENGLAND_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_ENGLAND_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_ENGLAND', 'LEADER_ELEANOR_ENGLAND', 'GOLDEN_TRAIT_CIVILIZATION_ENGLAND', 'ICON_CIVILIZATION_ENGLAND', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_ENGLAND_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_ENGLAND', 'LEADER_ELIZABETH', 'GOLDEN_CIVILIZATION_ENGLAND_CUSTOM_FEATURES', 'ICON_CIVILIZATION_ENGLAND', 'LOC_GOLDEN_CIVILIZATION_ENGLAND_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_ENGLAND_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_ENGLAND', 'LEADER_ELIZABETH', 'GOLDEN_TRAIT_CIVILIZATION_ENGLAND', 'ICON_CIVILIZATION_ENGLAND', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_ENGLAND_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_ENGLAND', 'LEADER_VICTORIA_ALT', 'GOLDEN_CIVILIZATION_ENGLAND_CUSTOM_FEATURES', 'ICON_CIVILIZATION_ENGLAND', 'LOC_GOLDEN_CIVILIZATION_ENGLAND_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_ENGLAND_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_ENGLAND', 'LEADER_VICTORIA_ALT', 'GOLDEN_TRAIT_CIVILIZATION_ENGLAND', 'ICON_CIVILIZATION_ENGLAND', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_ENGLAND_DESCRIPTION', 50);

--FRANCE 法国
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_FRANCE', 'LEADER_CATHERINE_DE_MEDICI', 'GOLDEN_CIVILIZATION_FRANCE_CUSTOM_FEATURES', 'ICON_CIVILIZATION_FRANCE', 'LOC_GOLDEN_CIVILIZATION_FRANCE_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_FRANCE_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_FRANCE', 'LEADER_CATHERINE_DE_MEDICI', 'GOLDEN_TRAIT_CIVILIZATION_FRANCE', 'ICON_CIVILIZATION_FRANCE', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_FRANCE_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_FRANCE', 'LEADER_CATHERINE_DE_MEDICI_ALT', 'GOLDEN_CIVILIZATION_FRANCE_CUSTOM_FEATURES', 'ICON_CIVILIZATION_FRANCE', 'LOC_GOLDEN_CIVILIZATION_FRANCE_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_FRANCE_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_FRANCE', 'LEADER_CATHERINE_DE_MEDICI_ALT', 'GOLDEN_TRAIT_CIVILIZATION_FRANCE', 'ICON_CIVILIZATION_FRANCE', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_FRANCE_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_FRANCE', 'LEADER_ELEANOR_FRANCE', 'GOLDEN_CIVILIZATION_FRANCE_CUSTOM_FEATURES', 'ICON_CIVILIZATION_FRANCE', 'LOC_GOLDEN_CIVILIZATION_FRANCE_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_FRANCE_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_FRANCE', 'LEADER_ELEANOR_FRANCE', 'GOLDEN_TRAIT_CIVILIZATION_FRANCE', 'ICON_CIVILIZATION_FRANCE', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_FRANCE_DESCRIPTION', 50);

--GERMANY 德国
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_GERMANY', 'LEADER_BARBAROSSA', 'GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES', 'ICON_CIVILIZATION_GERMANY', 'LOC_GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_GERMANY', 'LEADER_BARBAROSSA', 'GOLDEN_TRAIT_CIVILIZATION_GERMANY', 'ICON_CIVILIZATION_GERMANY', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_GERMANY_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_GERMANY', 'LEADER_LUDWIG', 'GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES', 'ICON_CIVILIZATION_GERMANY', 'LOC_GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_GERMANY', 'LEADER_LUDWIG', 'GOLDEN_TRAIT_CIVILIZATION_GERMANY', 'ICON_CIVILIZATION_GERMANY', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_GERMANY_DESCRIPTION', 50);

--GREECE 希腊
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_GREECE', 'LEADER_PERICLES', 'GOLDEN_CIVILIZATION_GREECE_CUSTOM_FEATURES', 'ICON_CIVILIZATION_GREECE', 'LOC_GOLDEN_CIVILIZATION_GREECE_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_GREECE_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_GREECE', 'LEADER_PERICLES', 'GOLDEN_TRAIT_CIVILIZATION_GREECE', 'ICON_CIVILIZATION_GREECE', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_GREECE_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_GREECE', 'LEADER_GORGO', 'GOLDEN_CIVILIZATION_GREECE_CUSTOM_FEATURES', 'ICON_CIVILIZATION_GREECE', 'LOC_GOLDEN_CIVILIZATION_GREECE_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_GREECE_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_GREECE', 'LEADER_GORGO', 'GOLDEN_TRAIT_CIVILIZATION_GREECE', 'ICON_CIVILIZATION_GREECE', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_GREECE_DESCRIPTION', 50);

--INDIA 印度
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_INDIA', 'LEADER_GANDHI', 'GOLDEN_CIVILIZATION_INDIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_INDIA', 'LOC_GOLDEN_CIVILIZATION_INDIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_INDIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_INDIA', 'LEADER_GANDHI', 'GOLDEN_TRAIT_CIVILIZATION_INDIA', 'ICON_CIVILIZATION_INDIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_INDIA_DESCRIPTION', 50);

--JAPAN 日本
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_JAPAN', 'LEADER_HOJO', 'GOLDEN_CIVILIZATION_JAPAN_CUSTOM_FEATURES', 'ICON_CIVILIZATION_JAPAN', 'LOC_GOLDEN_CIVILIZATION_JAPAN_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_JAPAN_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_JAPAN', 'LEADER_HOJO', 'GOLDEN_TRAIT_CIVILIZATION_JAPAN', 'ICON_CIVILIZATION_JAPAN', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_JAPAN_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_JAPAN', 'LEADER_TOKUGAWA', 'GOLDEN_CIVILIZATION_JAPAN_CUSTOM_FEATURES', 'ICON_CIVILIZATION_JAPAN', 'LOC_GOLDEN_CIVILIZATION_JAPAN_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_JAPAN_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_JAPAN', 'LEADER_TOKUGAWA', 'GOLDEN_TRAIT_CIVILIZATION_JAPAN', 'ICON_CIVILIZATION_JAPAN', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_JAPAN_DESCRIPTION', 50);

--KONGO 刚果
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_KONGO', 'LEADER_MVEMBA', 'GOLDEN_CIVILIZATION_KONGO_CUSTOM_FEATURES', 'ICON_CIVILIZATION_KONGO', 'LOC_GOLDEN_CIVILIZATION_KONGO_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_KONGO_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_KONGO', 'LEADER_MVEMBA', 'GOLDEN_TRAIT_CIVILIZATION_KONGO', 'ICON_CIVILIZATION_KONGO', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_KONGO_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_KONGO', 'LEADER_NZINGA_MBANDE', 'GOLDEN_CIVILIZATION_KONGO_CUSTOM_FEATURES', 'ICON_CIVILIZATION_KONGO', 'LOC_GOLDEN_CIVILIZATION_KONGO_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_KONGO_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_KONGO', 'LEADER_NZINGA_MBANDE', 'GOLDEN_TRAIT_CIVILIZATION_KONGO', 'ICON_CIVILIZATION_KONGO', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_KONGO_DESCRIPTION', 50);

--NORWAY 挪威
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_NORWAY', 'LEADER_HARDRADA', 'GOLDEN_CIVILIZATION_NORWAY_CUSTOM_FEATURES', 'ICON_CIVILIZATION_NORWAY', 'LOC_GOLDEN_CIVILIZATION_NORWAY_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_NORWAY_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_NORWAY', 'LEADER_HARDRADA', 'GOLDEN_TRAIT_CIVILIZATION_NORWAY', 'ICON_CIVILIZATION_NORWAY', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_NORWAY_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_NORWAY', 'LEADER_HARALD_ALT', 'GOLDEN_CIVILIZATION_NORWAY_CUSTOM_FEATURES', 'ICON_CIVILIZATION_NORWAY', 'LOC_GOLDEN_CIVILIZATION_NORWAY_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_NORWAY_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_NORWAY', 'LEADER_HARALD_ALT', 'GOLDEN_TRAIT_CIVILIZATION_NORWAY', 'ICON_CIVILIZATION_NORWAY', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_NORWAY_DESCRIPTION', 50);

--ROME 罗马
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_ROME', 'LEADER_TRAJAN', 'GOLDEN_CIVILIZATION_ROME_CUSTOM_FEATURES', 'ICON_CIVILIZATION_ROME', 'LOC_GOLDEN_CIVILIZATION_ROME_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_ROME_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_ROME', 'LEADER_TRAJAN', 'GOLDEN_TRAIT_CIVILIZATION_ROME', 'ICON_CIVILIZATION_ROME', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_ROME_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_ROME', 'LEADER_JULIUS_CAESAR', 'GOLDEN_CIVILIZATION_ROME_CUSTOM_FEATURES', 'ICON_CIVILIZATION_ROME', 'LOC_GOLDEN_CIVILIZATION_ROME_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_ROME_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_ROME', 'LEADER_JULIUS_CAESAR', 'GOLDEN_TRAIT_CIVILIZATION_ROME', 'ICON_CIVILIZATION_ROME', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_ROME_DESCRIPTION', 50);

--RUSSIA 俄罗斯
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_RUSSIA', 'LEADER_PETER_GREAT', 'GOLDEN_CIVILIZATION_RUSSIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_RUSSIA', 'LOC_GOLDEN_CIVILIZATION_RUSSIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_RUSSIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_RUSSIA', 'LEADER_PETER_GREAT', 'GOLDEN_TRAIT_CIVILIZATION_RUSSIA', 'ICON_CIVILIZATION_RUSSIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_RUSSIA_DESCRIPTION', 50);

--SCYTHIA 斯基泰
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_SCYTHIA', 'LEADER_TOMYRIS', 'GOLDEN_CIVILIZATION_SCYTHIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_SCYTHIA', 'LOC_GOLDEN_CIVILIZATION_SCYTHIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_SCYTHIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_SCYTHIA', 'LEADER_TOMYRIS', 'GOLDEN_TRAIT_CIVILIZATION_SCYTHIA', 'ICON_CIVILIZATION_SCYTHIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_SCYTHIA_DESCRIPTION', 50);

--SPAIN 西班牙
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_SPAIN', 'LEADER_PHILIP_II', 'GOLDEN_CIVILIZATION_SPAIN_CUSTOM_FEATURES', 'ICON_CIVILIZATION_SPAIN', 'LOC_GOLDEN_CIVILIZATION_SPAIN_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_SPAIN_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_SPAIN', 'LEADER_PHILIP_II', 'GOLDEN_TRAIT_CIVILIZATION_SPAIN', 'ICON_CIVILIZATION_SPAIN', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_SPAIN_DESCRIPTION', 50);

--SUMERIA 苏美尔
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_SUMERIA', 'LEADER_GILGAMESH', 'GOLDEN_CIVILIZATION_SUMERIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_SUMERIA', 'LOC_GOLDEN_CIVILIZATION_SUMERIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_SUMERIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_SUMERIA', 'LEADER_GILGAMESH', 'GOLDEN_TRAIT_CIVILIZATION_SUMERIA', 'ICON_CIVILIZATION_SUMERIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_SUMERIA_DESCRIPTION', 50);

--迭起兴衰文明
--CREE 克里
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_CREE', 'LEADER_POUNDMAKER', 'GOLDEN_CIVILIZATION_CREE_CUSTOM_FEATURES', 'ICON_CIVILIZATION_CREE', 'LOC_GOLDEN_CIVILIZATION_CREE_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_CREE_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_CREE', 'LEADER_POUNDMAKER', 'GOLDEN_TRAIT_CIVILIZATION_CREE', 'ICON_CIVILIZATION_CREE', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_CREE_DESCRIPTION', 50);

--KOREA 朝鲜
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_KOREA', 'LEADER_SEONDEOK', 'GOLDEN_CIVILIZATION_KOREA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_KOREA', 'LOC_GOLDEN_CIVILIZATION_KOREA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_KOREA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_KOREA', 'LEADER_SEONDEOK', 'GOLDEN_TRAIT_CIVILIZATION_KOREA', 'ICON_CIVILIZATION_KOREA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_KOREA_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_KOREA', 'LEADER_SEJONG', 'GOLDEN_CIVILIZATION_KOREA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_KOREA', 'LOC_GOLDEN_CIVILIZATION_KOREA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_KOREA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_KOREA', 'LEADER_SEJONG', 'GOLDEN_TRAIT_CIVILIZATION_KOREA', 'ICON_CIVILIZATION_KOREA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_KOREA_DESCRIPTION', 50);

--GEORGIA 格鲁吉亚
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_GEORGIA', 'LEADER_TAMAR', 'GOLDEN_CIVILIZATION_GEORGIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_GEORGIA', 'LOC_GOLDEN_CIVILIZATION_GEORGIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_GEORGIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_GEORGIA', 'LEADER_TAMAR', 'GOLDEN_TRAIT_CIVILIZATION_GEORGIA', 'ICON_CIVILIZATION_GEORGIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_GEORGIA_DESCRIPTION', 50);

--MAPUCHE 马普切
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_MAPUCHE', 'LEADER_LAUTARO', 'GOLDEN_CIVILIZATION_MAPUCHE_CUSTOM_FEATURES', 'ICON_CIVILIZATION_MAPUCHE', 'LOC_GOLDEN_CIVILIZATION_MAPUCHE_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_MAPUCHE_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_MAPUCHE', 'LEADER_LAUTARO', 'GOLDEN_TRAIT_CIVILIZATION_MAPUCHE', 'ICON_CIVILIZATION_MAPUCHE', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_MAPUCHE_DESCRIPTION', 50);

--MONGOLIA 蒙古
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_MONGOLIA', 'LEADER_GENGHIS_KHAN', 'GOLDEN_CIVILIZATION_MONGOLIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_MONGOLIA', 'LOC_GOLDEN_CIVILIZATION_MONGOLIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_MONGOLIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_MONGOLIA', 'LEADER_GENGHIS_KHAN', 'GOLDEN_TRAIT_CIVILIZATION_MONGOLIA', 'ICON_CIVILIZATION_MONGOLIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_MONGOLIA_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_MONGOLIA', 'LEADER_KUBLAI_KHAN_MONGOLIA', 'GOLDEN_CIVILIZATION_MONGOLIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_MONGOLIA', 'LOC_GOLDEN_CIVILIZATION_MONGOLIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_MONGOLIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_MONGOLIA', 'LEADER_KUBLAI_KHAN_MONGOLIA', 'GOLDEN_TRAIT_CIVILIZATION_MONGOLIA', 'ICON_CIVILIZATION_MONGOLIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_MONGOLIA_DESCRIPTION', 50);

--NETHERLANDS 荷兰
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_NETHERLANDS', 'LEADER_WILHELMINA', 'GOLDEN_CIVILIZATION_NETHERLANDS_CUSTOM_FEATURES', 'ICON_CIVILIZATION_NETHERLANDS', 'LOC_GOLDEN_CIVILIZATION_NETHERLANDS_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_NETHERLANDS_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_NETHERLANDS', 'LEADER_WILHELMINA', 'GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS', 'ICON_CIVILIZATION_NETHERLANDS', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS_DESCRIPTION', 50);

--SCOTLAND 苏格兰
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_SCOTLAND', 'LEADER_ROBERT_THE_BRUCE', 'GOLDEN_CIVILIZATION_SCOTLAND_CUSTOM_FEATURES', 'ICON_CIVILIZATION_SCOTLAND', 'LOC_GOLDEN_CIVILIZATION_SCOTLAND_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_SCOTLAND_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_SCOTLAND', 'LEADER_ROBERT_THE_BRUCE', 'GOLDEN_TRAIT_CIVILIZATION_SCOTLAND', 'ICON_CIVILIZATION_SCOTLAND', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_SCOTLAND_DESCRIPTION', 50);

--INDIA 印度
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_INDIA', 'LEADER_CHANDRAGUPTA', 'GOLDEN_CIVILIZATION_INDIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_INDIA', 'LOC_GOLDEN_CIVILIZATION_INDIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_INDIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_INDIA', 'LEADER_CHANDRAGUPTA', 'GOLDEN_TRAIT_CIVILIZATION_INDIA', 'ICON_CIVILIZATION_INDIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_INDIA_DESCRIPTION', 50);

--ZULU 祖鲁
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_ZULU', 'LEADER_SHAKA', 'GOLDEN_CIVILIZATION_ZULU_CUSTOM_FEATURES', 'ICON_CIVILIZATION_ZULU', 'LOC_GOLDEN_CIVILIZATION_ZULU_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_ZULU_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_ZULU', 'LEADER_SHAKA', 'GOLDEN_TRAIT_CIVILIZATION_ZULU', 'ICON_CIVILIZATION_ZULU', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_ZULU_DESCRIPTION', 50);

--风云变幻文明
--CANADA 加拿大
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_CANADA', 'LEADER_LAURIER', 'GOLDEN_CIVILIZATION_CANADA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_CANADA', 'LOC_GOLDEN_CIVILIZATION_CANADA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_CANADA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_CANADA', 'LEADER_LAURIER', 'GOLDEN_TRAIT_CIVILIZATION_CANADA', 'ICON_CIVILIZATION_CANADA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_CANADA_DESCRIPTION', 50);

--HUNGARY 匈牙利
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_HUNGARY', 'LEADER_MATTHIAS_CORVINUS', 'GOLDEN_CIVILIZATION_HUNGARY_CUSTOM_FEATURES', 'ICON_CIVILIZATION_HUNGARY', 'LOC_GOLDEN_CIVILIZATION_HUNGARY_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_HUNGARY_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_HUNGARY', 'LEADER_MATTHIAS_CORVINUS', 'GOLDEN_TRAIT_CIVILIZATION_HUNGARY', 'ICON_CIVILIZATION_HUNGARY', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_HUNGARY_DESCRIPTION', 50);

--INCA 印加
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_INCA', 'LEADER_PACHACUTI', 'GOLDEN_CIVILIZATION_INCA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_INCA', 'LOC_GOLDEN_CIVILIZATION_INCA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_INCA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_INCA', 'LEADER_PACHACUTI', 'GOLDEN_TRAIT_CIVILIZATION_INCA', 'ICON_CIVILIZATION_INCA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_INCA_DESCRIPTION', 50);

--MALI 马里
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_MALI', 'LEADER_MANSA_MUSA', 'GOLDEN_CIVILIZATION_MALI_CUSTOM_FEATURES', 'ICON_CIVILIZATION_MALI', 'LOC_GOLDEN_CIVILIZATION_MALI_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_MALI_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_MALI', 'LEADER_MANSA_MUSA', 'GOLDEN_TRAIT_CIVILIZATION_MALI', 'ICON_CIVILIZATION_MALI', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_MALI_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_MALI', 'LEADER_SUNDIATA_KEITA', 'GOLDEN_CIVILIZATION_MALI_CUSTOM_FEATURES', 'ICON_CIVILIZATION_MALI', 'LOC_GOLDEN_CIVILIZATION_MALI_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_MALI_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_MALI', 'LEADER_SUNDIATA_KEITA', 'GOLDEN_TRAIT_CIVILIZATION_MALI', 'ICON_CIVILIZATION_MALI', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_MALI_DESCRIPTION', 50);

--MAORI 毛利
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_MAORI', 'LEADER_KUPE', 'GOLDEN_CIVILIZATION_MAORI_CUSTOM_FEATURES', 'ICON_CIVILIZATION_MAORI', 'LOC_GOLDEN_CIVILIZATION_MAORI_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_MAORI_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_MAORI', 'LEADER_KUPE', 'GOLDEN_TRAIT_CIVILIZATION_MAORI', 'ICON_CIVILIZATION_MAORI', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_MAORI_DESCRIPTION', 50);

--OTTOMAN 奥斯曼
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_OTTOMAN', 'LEADER_SULEIMAN', 'GOLDEN_CIVILIZATION_OTTOMAN_CUSTOM_FEATURES', 'ICON_CIVILIZATION_OTTOMAN', 'LOC_GOLDEN_CIVILIZATION_OTTOMAN_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_OTTOMAN_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_OTTOMAN', 'LEADER_SULEIMAN', 'GOLDEN_TRAIT_CIVILIZATION_OTTOMAN', 'ICON_CIVILIZATION_OTTOMAN', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_OTTOMAN_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_OTTOMAN', 'LEADER_SULEIMAN_ALT', 'GOLDEN_CIVILIZATION_OTTOMAN_CUSTOM_FEATURES', 'ICON_CIVILIZATION_OTTOMAN', 'LOC_GOLDEN_CIVILIZATION_OTTOMAN_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_OTTOMAN_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_OTTOMAN', 'LEADER_SULEIMAN_ALT', 'GOLDEN_TRAIT_CIVILIZATION_OTTOMAN', 'ICON_CIVILIZATION_OTTOMAN', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_OTTOMAN_DESCRIPTION', 50);

--PHOENICIA 腓尼基
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_PHOENICIA', 'LEADER_DIDO', 'GOLDEN_CIVILIZATION_PHOENICIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_PHOENICIA', 'LOC_GOLDEN_CIVILIZATION_PHOENICIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_PHOENICIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_PHOENICIA', 'LEADER_DIDO', 'GOLDEN_TRAIT_CIVILIZATION_PHOENICIA', 'ICON_CIVILIZATION_PHOENICIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_PHOENICIA_DESCRIPTION', 50);

--SWEDEN 瑞典
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_SWEDEN', 'LEADER_KRISTINA', 'GOLDEN_CIVILIZATION_SWEDEN_CUSTOM_FEATURES', 'ICON_CIVILIZATION_SWEDEN', 'LOC_GOLDEN_CIVILIZATION_SWEDEN_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_SWEDEN_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_SWEDEN', 'LEADER_KRISTINA', 'GOLDEN_TRAIT_CIVILIZATION_SWEDEN', 'ICON_CIVILIZATION_SWEDEN', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_SWEDEN_DESCRIPTION', 50);

--DLC文明
--AUSTRALIA 澳大利亚
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_AUSTRALIA', 'LEADER_JOHN_CURTIN', 'GOLDEN_CIVILIZATION_AUSTRALIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_AUSTRALIA', 'LOC_GOLDEN_CIVILIZATION_AUSTRALIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_AUSTRALIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_AUSTRALIA', 'LEADER_JOHN_CURTIN', 'GOLDEN_TRAIT_CIVILIZATION_AUSTRALIA', 'ICON_CIVILIZATION_AUSTRALIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_AUSTRALIA_DESCRIPTION', 50);

--AZTEC 阿兹特克
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_AZTEC', 'LEADER_MONTEZUMA', 'GOLDEN_CIVILIZATION_AZTEC_CUSTOM_FEATURES', 'ICON_CIVILIZATION_AZTEC', 'LOC_GOLDEN_CIVILIZATION_AZTEC_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_AZTEC_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_AZTEC', 'LEADER_MONTEZUMA', 'GOLDEN_TRAIT_CIVILIZATION_AZTEC', 'ICON_CIVILIZATION_AZTEC', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_AZTEC_DESCRIPTION', 50);

--KHMER 高棉
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_KHMER', 'LEADER_JAYAVARMAN', 'GOLDEN_CIVILIZATION_KHMER_CUSTOM_FEATURES', 'ICON_CIVILIZATION_KHMER', 'LOC_GOLDEN_CIVILIZATION_KHMER_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_KHMER_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_KHMER', 'LEADER_JAYAVARMAN', 'GOLDEN_TRAIT_CIVILIZATION_KHMER', 'ICON_CIVILIZATION_KHMER', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_KHMER_DESCRIPTION', 50);

--INDONESIA 印度尼西亚
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_INDONESIA', 'LEADER_GITARJA', 'GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_INDONESIA', 'LOC_GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_INDONESIA', 'LEADER_GITARJA', 'GOLDEN_TRAIT_CIVILIZATION_INDONESIA', 'ICON_CIVILIZATION_INDONESIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_INDONESIA_DESCRIPTION', 50);

--NUBIA 努比亚
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_NUBIA', 'LEADER_AMANITORE', 'GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_NUBIA', 'LOC_GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_NUBIA', 'LEADER_AMANITORE', 'GOLDEN_TRAIT_CIVILIZATION_NUBIA', 'ICON_CIVILIZATION_NUBIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_NUBIA_DESCRIPTION', 50);

--MACEDON 马其顿
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_MACEDON', 'LEADER_ALEXANDER', 'GOLDEN_CIVILIZATION_MACEDON_CUSTOM_FEATURES', 'ICON_CIVILIZATION_MACEDON', 'LOC_GOLDEN_CIVILIZATION_MACEDON_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_MACEDON_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_MACEDON', 'LEADER_ALEXANDER', 'GOLDEN_TRAIT_CIVILIZATION_MACEDON', 'ICON_CIVILIZATION_MACEDON', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_MACEDON_DESCRIPTION', 50);

--PERSIA 波斯
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_PERSIA', 'LEADER_CYRUS', 'GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_PERSIA', 'LOC_GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_PERSIA', 'LEADER_CYRUS', 'GOLDEN_TRAIT_CIVILIZATION_PERSIA', 'ICON_CIVILIZATION_PERSIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_PERSIA_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_PERSIA', 'LEADER_NADER_SHAH', 'GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_PERSIA', 'LOC_GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_PERSIA', 'LEADER_NADER_SHAH', 'GOLDEN_TRAIT_CIVILIZATION_PERSIA', 'ICON_CIVILIZATION_PERSIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_PERSIA_DESCRIPTION', 50);

--POLAND 波兰
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_POLAND', 'LEADER_JADWIGA', 'GOLDEN_CIVILIZATION_POLAND_CUSTOM_FEATURES', 'ICON_CIVILIZATION_POLAND', 'LOC_GOLDEN_CIVILIZATION_POLAND_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_POLAND_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_POLAND', 'LEADER_JADWIGA', 'GOLDEN_TRAIT_CIVILIZATION_POLAND', 'ICON_CIVILIZATION_POLAND', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_POLAND_DESCRIPTION', 50);

--新纪元文明
--MAYA 玛雅
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_MAYA', 'LEADER_LADY_SIX_SKY', 'GOLDEN_CIVILIZATION_MAYA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_MAYA', 'LOC_GOLDEN_CIVILIZATION_MAYA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_MAYA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_MAYA', 'LEADER_LADY_SIX_SKY', 'GOLDEN_TRAIT_CIVILIZATION_MAYA', 'ICON_CIVILIZATION_MAYA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_MAYA_DESCRIPTION', 50);

--GRAN_COLOMBIA 大哥伦比亚
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_GRAN_COLOMBIA', 'LEADER_SIMON_BOLIVAR', 'GOLDEN_CIVILIZATION_GRAN_COLOMBIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_GRAN_COLOMBIA', 'LOC_GOLDEN_CIVILIZATION_GRAN_COLOMBIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_GRAN_COLOMBIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_GRAN_COLOMBIA', 'LEADER_SIMON_BOLIVAR', 'GOLDEN_TRAIT_CIVILIZATION_GRAN_COLOMBIA', 'ICON_CIVILIZATION_GRAN_COLOMBIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_GRAN_COLOMBIA_DESCRIPTION', 50);

--CIVILIZATION_ETHIOPIA 埃塞俄比亚
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_ETHIOPIA', 'LEADER_MENELIK', 'GOLDEN_CIVILIZATION_ETHIOPIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_ETHIOPIA', 'LOC_GOLDEN_CIVILIZATION_ETHIOPIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_ETHIOPIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_ETHIOPIA', 'LEADER_MENELIK', 'GOLDEN_TRAIT_CIVILIZATION_ETHIOPIA', 'ICON_CIVILIZATION_ETHIOPIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_ETHIOPIA_DESCRIPTION', 50);

--CIVILIZATION_BYZANTIUM 拜占庭
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_BYZANTIUM', 'LEADER_BASIL', 'GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES', 'ICON_CIVILIZATION_BYZANTIUM', 'LOC_GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_BYZANTIUM', 'LEADER_BASIL', 'GOLDEN_TRAIT_CIVILIZATION_BYZANTIUM', 'ICON_CIVILIZATION_BYZANTIUM', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_BYZANTIUM_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_BYZANTIUM', 'LEADER_THEODORA', 'GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES', 'ICON_CIVILIZATION_BYZANTIUM', 'LOC_GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_BYZANTIUM', 'LEADER_THEODORA', 'GOLDEN_TRAIT_CIVILIZATION_BYZANTIUM', 'ICON_CIVILIZATION_BYZANTIUM', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_BYZANTIUM_DESCRIPTION', 50);

--CIVILIZATION_GAUL 高卢
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_GAUL', 'LEADER_AMBIORIX', 'GOLDEN_CIVILIZATION_GAUL_CUSTOM_FEATURES', 'ICON_CIVILIZATION_GAUL', 'LOC_GOLDEN_CIVILIZATION_GAUL_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_GAUL_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_GAUL', 'LEADER_AMBIORIX', 'GOLDEN_TRAIT_CIVILIZATION_GAUL', 'ICON_CIVILIZATION_GAUL', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_GAUL_DESCRIPTION', 50);

--CIVILIZATION_BABYLON_STK 巴比伦
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_BABYLON_STK', 'LEADER_HAMMURABI', 'GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES', 'ICON_CIVILIZATION_BABYLON_STK', 'LOC_GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_BABYLON_STK', 'LEADER_HAMMURABI', 'GOLDEN_TRAIT_CIVILIZATION_BABYLON_STK', 'ICON_CIVILIZATION_BABYLON_STK', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_BABYLON_STK_DESCRIPTION', 50);

--CIVILIZATION_VIETNAM 越南
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_VIETNAM', 'LEADER_LADY_TRIEU', 'GOLDEN_CIVILIZATION_VIETNAM_CUSTOM_FEATURES', 'ICON_CIVILIZATION_VIETNAM', 'LOC_GOLDEN_CIVILIZATION_VIETNAM_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_VIETNAM_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_VIETNAM', 'LEADER_LADY_TRIEU', 'GOLDEN_TRAIT_CIVILIZATION_VIETNAM', 'ICON_CIVILIZATION_VIETNAM', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_VIETNAM_DESCRIPTION', 50);

--CIVILIZATION_PORTUGAL 葡萄牙
INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_PORTUGAL', 'LEADER_JOAO_III', 'GOLDEN_CIVILIZATION_PORTUGAL_CUSTOM_FEATURES', 'ICON_CIVILIZATION_PORTUGAL', 'LOC_GOLDEN_CIVILIZATION_PORTUGAL_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_PORTUGAL_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_PORTUGAL', 'LEADER_JOAO_III', 'GOLDEN_TRAIT_CIVILIZATION_PORTUGAL', 'ICON_CIVILIZATION_PORTUGAL', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_PORTUGAL_DESCRIPTION', 50);
