--=====
--Parameters
--=====
INSERT OR REPLACE INTO Parameters
(ParameterId,			Name,							Description,							'Domain',	DefaultValue,	ConfigurationGroup,	ConfigurationId,		NameArrayConfigurationId,	GroupId,		SortIndex)
VALUES
('GOLDEN_EXTRA_TRAITS',	'LOC_GOLDEN_EXTRA_TRAITS_NAME',	'LOC_GOLDEN_EXTRA_TRAITS_DESCRIPTION',	'bool', 	1,				'Game',				'EXTRA_TRAITS_OPTION',	'GAMEMODES_ENABLED_NAMES',	'GameModes',	204),
('GOLDEN_HISTORY',		'LOC_GOLDEN_HISTORY_NAME',		'LOC_GOLDEN_HISTORY_DESCRIPTION',		'bool', 	1,				'Game',				'HISTORY_OPTION',		'GAMEMODES_ENABLED_NAMES',	'GameModes',	205),		
('GOLDEN_APPEAL',		'LOC_GOLDEN_APPEAL_NAME',		'LOC_GOLDEN_APPEAL_DESCRIPTION',		'bool', 	1,				'Game',				'APPEAL_OPTION',		'GAMEMODES_ENABLED_NAMES',	'GameModes',	206),
('GA_CITYPOLICY',		'LOC_GA_CITYPOLICY_NAME',		'LOC_GA_CITYPOLICY_DESCRIPTION',		'bool', 	1,				'Game',				'GA_CITYPOLICY',		'GAMEMODES_ENABLED_NAMES',	'GameModes',	207),       				
('GA_MILITARYSERVICE',	'LOC_GA_MILITARYSERVICE_NAME',	'LOC_GA_MILITARYSERVICE_DESCRIPTION',	'bool', 	1,				'Game',				'GA_MILITARYSERVICE',	'GAMEMODES_ENABLED_NAMES',	'GameModes',	208),       				
('GOLDEN_WORLDWAR',		'LOC_GOLDEN_WORLDWAR_NAME',		'LOC_GOLDEN_WORLDWAR_DESCRIPTION',		'bool', 	1,				'Game',				'WORLDWAR_OPTION',		'GAMEMODES_ENABLED_NAMES',	'GameModes',	209),		
('GOLDEN_FRIEND',		'LOC_GOLDEN_FRIEND_NAME',		'LOC_GOLDEN_FRIEND_DESCRIPTION',		'bool', 	1,				'Game',				'FRIEND_OPTION',		'GAMEMODES_ENABLED_NAMES',	'GameModes',	210),
('GA_TOTALWAR',			'LOC_GA_TOTALWAR_NAME',			'LOC_GA_TOTALWAR_DESCRIPTION',			'bool', 	0,				'Game',				'GA_TOTALWAR',			'GAMEMODES_ENABLED_NAMES',	'GameModes',	211),       
('GA_CULTIVATION',		'LOC_GA_CULTIVATION_NAME',		'LOC_GA_CULTIVATION_DESCRIPTION',		'bool', 	0,				'Game',				'GA_CULTIVATION',		'GAMEMODES_ENABLED_NAMES',	'GameModes',	212),       				
('GA_MILESTONE',		'LOC_GA_MILESTONE_NAME',		'LOC_GA_MILESTONE_DESCRIPTION',			'bool', 	0,				'Game',				'GA_MILESTONE',			'GAMEMODES_ENABLED_NAMES',	'GameModes',	213), 
('GA_MEGALOPOLIS_PRO',	'LOC_GA_MEGALOPOLIS_PRO_NAME',	'LOC_GA_MEGALOPOLIS_PRO_DESCRIPTION',	'bool', 	0,				'Game',				'GA_MEGALOPOLIS_PRO',	'GAMEMODES_ENABLED_NAMES',	'GameModes',	214); 

INSERT OR REPLACE INTO Parameters 
(ParameterId,					ConfigurationGroup, ConfigurationId,	DefaultValue,	Description,								'Domain',				GroupId,			Hash,	Name,	ReadOnly, SortIndex)
VALUES
('GAPreference',				'Game',				'GA_PREFERENCE',			1, 		'LOC_GA_PREFERENCE_DESCRIPTION',			'bool',					'AdvancedOptions',	0,		'LOC_GA_PREFERENCE_NAME',				1, 50),
('GA_COST_CIVIC_TECH',			'Game',				'GA_COST_CIVIC_TECH',		100,	'LOC_GA_COST_CIVIC_TECH_DESCRIPTION',		'GA_CivicTechCost',		'AdvancedOptions',	0,		'LOC_GA_COST_CIVIC_TECH_NAME',			0, 51),
('GA_CITY_DISTANCE',			'Game',				'GA_CITY_DISTANCE',			3,		'LOC_GA_CITY_DISTANCE_DESCRIPTION',			'GA_City_distance',		'AdvancedOptions',	0,		'LOC_GA_CITY_DISTANCE_NAME',			0, 53),
('GA_DEFENSIVEIMPROVEMENTS',	'Game',				'GA_DEFENSIVEIMPROVEMENTS',	0,		'LOC_GA_DEFENSIVEIMPROVEMENTS_DESCRIPTION',	'bool',					'AdvancedOptions',	0,		'LOC_GA_DEFENSIVEIMPROVEMENTS_NAME',	0, 54),
('GA_BARBARIAN',				'Game',				'GA_BARBARIAN',				0,		'LOC_GA_BARBARIAN_DESCRIPTION',				'bool',					'AdvancedOptions',	0,		'LOC_GA_BARBARIAN_NAME',				0, 55),
('GA_HARBOR',					'Game',				'GA_HARBOR',				1,		'LOC_GA_HARBOR_DESCRIPTION',				'bool',					'AdvancedOptions',	0,		'LOC_GA_HARBOR_NAME',					0, 56),
('GA_CAPITAL_LOYAL',			'Game',				'GA_CAPITAL_LOYAL',			0,		'LOC_GA_CAPITAL_LOYAL_DESCRIPTION', 		'bool',					'AdvancedOptions',	0,		'LOC_GA_CAPITAL_LOYAL_NAME',			0, 57),
('GA_AICHEAT',					'Game',				'GA_AICHEAT',				0,		'LOC_GA_AICHEAT_DESCRIPTION',				'bool',					'AdvancedOptions',	0,		'LOC_GA_AICHEAT_NAME',					0, 58),
('GA_STORM',					'Game',				'GA_STORM',					0,		'LOC_GA_STORM_DESCRIPTION',					'bool',					'AdvancedOptions',	0,		'LOC_GA_STORM_NAME',					0, 59),
('GA_WONDER_WATER',				'Game',				'GA_WONDER_WATER',			0,		'LOC_GA_WONDER_WATER_DESCRIPTION',			'bool',					'AdvancedOptions',	0,		'LOC_GA_WONDER_WATER_NAME',				0, 60),
('GA_NO_EXCLUSIVE',				'Game',				'GA_NO_EXCLUSIVE',			0,		'LOC_GA_NO_EXCLUSIVE_DESCRIPTION',			'bool',					'AdvancedOptions',	0,		'LOC_GA_NO_EXCLUSIVE_NAME',				0, 61),
('GA_YIELD_AMENDMENT',			'Game',				'GA_YIELD_AMENDMENT',		1,		'LOC_GA_YIELD_AMENDMENT_DESCRIPTION',		'bool',					'AdvancedOptions',	0,		'LOC_GA_YIELD_AMENDMENT_NAME',			0, 62);

UPDATE Parameters SET SortIndex = 70 WHERE ParameterId = 'NoGoodyHuts';
UPDATE Parameters SET SortIndex = 71 WHERE ParameterId = 'NoBarbarians';

INSERT INTO Parameters 
(ParameterId,			ConfigurationGroup, ConfigurationId,	DefaultValue,	Description,	'Domain', GroupId, Hash, Name, ReadOnly, SortIndex)
VALUES
('GA_CHEATING',			'Game',	'GA_CHEATING',			1,	'LOC_GA_CHEATING_DESCRIPTION',			'bool',	'AdvancedOptions', 0, 'LOC_GA_CHEATING_NAME',			1, 80),
('GA_AIBANWONDER',		'Game',	'GA_AIBANWONDER',		0,	'LOC_GA_AIBANWONDER_DESCRIPTION',		'bool',	'AdvancedOptions', 0, 'LOC_GA_AIBANWONDER_NAME',		0, 81),
('GA_NOMINORWALL',		'Game',	'GA_NOMINORWALL',		0,	'LOC_GA_NOMINORWALL_DESCRIPTION',		'bool',	'AdvancedOptions', 0, 'LOC_GA_NOMINORWALL_NAME',		0, 82),
('GA_CITYMOVER',		'Game',	'GA_CITYMOVER',			0,	'LOC_GA_CITYMOVER_DESCRIPTION',			'bool',	'AdvancedOptions', 0, 'LOC_GA_CITYMOVER_NAME',			0, 83),
('GA_UNITPILEUP',		'Game',	'GA_UNITPILEUP',		0,	'LOC_GA_UNITPILEUP_DESCRIPTION',		'bool',	'AdvancedOptions', 0, 'LOC_GA_UNITPILEUP_NAME',			0, 84),
('GA_MORE_SIGHT',		'Game',	'GA_MORE_SIGHT',		0,	'LOC_GA_MORE_SIGHT_DESCRIPTION',		'bool',	'AdvancedOptions', 0, 'LOC_GA_MORE_SIGHT_NAME',			0, 85),
('GA_MODE_FASTER',		'Game',	'GA_MODE_FASTER',		0,	'LOC_GA_MODE_FASTER_DESCRIPTION',		'bool',	'AdvancedOptions', 0, 'LOC_GA_MODE_FASTER_NAME',		0, 86),
('GA_NOAI_HERO',		'Game',	'GA_NOAI_HERO',			0,	'LOC_GA_NOAI_HERO_DESCRIPTION',			'bool',	'AdvancedOptions', 0, 'LOC_GA_NOAI_HERO_NAME',			0, 87),
('GA_MODE_PANTHEON',	'Game',	'GA_MODE_PANTHEON',		0,	'LOC_GA_MODE_PANTHEON_DESCRIPTION',		'bool',	'AdvancedOptions', 0, 'LOC_GA_MODE_PANTHEON_NAME',		0, 88),
('GA_MODE_PROPHET',		'Game',	'GA_MODE_PROPHET',		0,	'LOC_GA_MODE_PROPHET_DESCRIPTION',		'bool',	'AdvancedOptions', 0, 'LOC_GA_MODE_PROPHET_NAME',		0, 89),
('GA_MODE_NO_POP_LOSE',	'Game',	'GA_MODE_NO_POP_LOSE',	0,	'LOC_GA_MODE_NO_POP_LOSE_DESCRIPTION',	'bool',	'AdvancedOptions', 0, 'LOC_GA_MODE_NO_POP_LOSE_NAME',	0, 90),
('GA_MODE_BARRIERS',	'Game',	'GA_MODE_BARRIERS',		0,	'LOC_GA_MODE_BARRIERS_DESCRIPTION',		'bool',	'AdvancedOptions', 0, 'LOC_GA_MODE_BARRIERS_NAME',		0, 91);

UPDATE Parameters SET SortIndex = 100 WHERE ParameterId = 'GAFooter';
--=====
--GameModeItems
--=====
INSERT INTO GameModeItems 
(GameModeType,			Name,							Description,							Portrait,						Background, Icon, SortIndex)
VALUES
('EXTRA_TRAITS_OPTION',	'LOC_GOLDEN_EXTRA_TRAITS_NAME',	'LOC_GOLDEN_EXTRA_TRAITS_DESCRIPTION',	'IMAGE_GOLDEN_EXTRA_TRAITS',	'GOLDENAGE_MODE_BACKGROUND', 'ICON_CIVIC_HUMANISM',				24),
('HISTORY_OPTION',		'LOC_GOLDEN_HISTORY_NAME',		'LOC_GOLDEN_HISTORY_DESCRIPTION',		'IMAGE_GOLDEN_HISTORY',			'GOLDENAGE_MODE_BACKGROUND', 'ICON_CIVIC_THE_ENLIGHTENMENT',	25),
('APPEAL_OPTION',		'LOC_GOLDEN_APPEAL_NAME',		'LOC_GOLDEN_APPEAL_DESCRIPTION',		'IMAGE_GOLDEN_APPEAL',			'GOLDENAGE_MODE_BACKGROUND', 'ICON_CIVIC_GLOBALIZATION',		26),
('GA_CITYPOLICY',		'LOC_GA_CITYPOLICY_NAME',		'LOC_GA_CITYPOLICY_DESCRIPTION',		'IMAGE_GA_CITYPOLICY',			'GOLDENAGE_MODE_BACKGROUND', 'ICON_CIVIC_CODE_OF_LAWS',			27),
('GA_MILITARYSERVICE',	'LOC_GA_MILITARYSERVICE_NAME',	'LOC_GA_MILITARYSERVICE_DESCRIPTION',	'IMAGE_GA_MILITARYSERVICE',		'GOLDENAGE_MODE_BACKGROUND', 'ICON_CIVIC_NATIONALISM',			28),
('WORLDWAR_OPTION',		'LOC_GOLDEN_WORLDWAR_NAME',		'LOC_GOLDEN_WORLDWAR_DESCRIPTION',		'IMAGE_GOLDEN_WORLDWAR',		'GOLDENAGE_MODE_BACKGROUND', 'ICON_CIVIC_COLD_WAR',				29),
('FRIEND_OPTION',		'LOC_GOLDEN_FRIEND_NAME',		'LOC_GOLDEN_FRIEND_DESCRIPTION',		'IMAGE_GOLDEN_FRIEND',			'GOLDENAGE_MODE_BACKGROUND', 'ICON_CIVIC_CIVIL_SERVICE',		30),
('GA_TOTALWAR',			'LOC_GA_TOTALWAR_NAME',			'LOC_GA_TOTALWAR_DESCRIPTION',			'IMAGE_GA_TOTALWAR',			'GOLDENAGE_MODE_BACKGROUND', 'ICON_CIVIC_MOBILIZATION',			31),
('GA_CULTIVATION',		'LOC_GA_CULTIVATION_NAME',		'LOC_GA_CULTIVATION_DESCRIPTION',		'IMAGE_GA_CULTIVATION',			'GOLDENAGE_MODE_BACKGROUND', 'ICON_TECH_IRRIGATION',			32),
('GA_MILESTONE',		'LOC_GA_MILESTONE_NAME',		'LOC_GA_MILESTONE_DESCRIPTION',			'IMAGE_GA_MILESTONE',			'GOLDENAGE_MODE_BACKGROUND', 'ICON_TECH_FUTURE_TECH',			33),
('GA_MEGALOPOLIS_PRO',	'LOC_GA_MEGALOPOLIS_PRO_NAME',	'LOC_GA_MEGALOPOLIS_PRO_DESCRIPTION',	'IMAGE_GA_MEGALOPOLIS_PRO',		'GOLDENAGE_MODE_BACKGROUND', 'ICON_TECH_NANOTECHNOLOGY',		34);
--=====
--ConfigurationUpdates
--=====
INSERT INTO ConfigurationUpdates 
(SourceGroup, SourceId, SourceValue, TargetGroup, TargetId, TargetValue, Static)
VALUES
('Game',	'GA_MILESTONE', 			1, 'Game',	'GAMEMODE_TREE_RANDOMIZER', 0, 0),
('Game',	'GAMEMODE_TREE_RANDOMIZER', 1, 'Game',	'GA_MILESTONE',				0, 0),
('Game',	'GA_MILESTONE',				1, 'Game',	'GA_TECH_CIVIC',			1, 0);
--=====
--ParameterCriteria
--=====
INSERT INTO ParameterCriteria 
(ParameterId, ConfigurationGroup, ConfigurationId, Operator, ConfigurationValue)
VALUES
('GA_MILESTONE',				'Game',	'GAMEMODE_TREE_RANDOMIZER', 'NotEquals', 1),
('GameMode_Tree_Randomizer',	'Game',	'GA_MILESTONE',				'NotEquals', 1);
--=====
--DomainValues
--=====
INSERT INTO DomainValues
(Description, Domain, Name, SortIndex, Value)
VALUES
('LOC_GA_COST_CIVIC_TECH_100_DESCRIPTION',	'GA_CivicTechCost', 'LOC_GA_COST_CIVIC_TECH_100_NAME',	1,	100),
('LOC_GA_COST_CIVIC_TECH_150_DESCRIPTION',	'GA_CivicTechCost', 'LOC_GA_COST_CIVIC_TECH_150_NAME',	2,	150),
('LOC_GA_COST_CIVIC_TECH_200_DESCRIPTION',	'GA_CivicTechCost', 'LOC_GA_COST_CIVIC_TECH_200_NAME',	3,	200),
('LOC_GA_COST_CIVIC_TECH_300_DESCRIPTION',	'GA_CivicTechCost', 'LOC_GA_COST_CIVIC_TECH_300_NAME',	4,	300),
('LOC_GA_CITY_DISTANCE_2_DESCRIPTION',		'GA_City_distance', 'LOC_GA_CITY_DISTANCE_2_NAME',		1,	2),
('LOC_GA_CITY_DISTANCE_3_DESCRIPTION',		'GA_City_distance', 'LOC_GA_CITY_DISTANCE_3_NAME',		2,	3),
('LOC_GA_CITY_DISTANCE_4_DESCRIPTION',		'GA_City_distance', 'LOC_GA_CITY_DISTANCE_4_NAME',		3,	4),
('LOC_GA_CITY_DISTANCE_5_DESCRIPTION',		'GA_City_distance', 'LOC_GA_CITY_DISTANCE_5_NAME',		4,	5);
--=====
--Victories
--=====
INSERT INTO Victories 
(Domain,					VictoryType,			Name,							Description)
VALUES
('Expansion2_Victories',	'GA_VICTORY_WONDER',	'LOC_GA_WONDERVICTORY_NAME',	'LOC_GA_WONDERVICTORY_DESCRIPTION');