--V224
-- 基础区域
UPDATE Districts
SET OnePerCity = 0
WHERE DistrictType IN (
    'DISTRICT_CAMPUS',
    'DISTRICT_THEATER',
    'DISTRICT_HOLY_SITE',
    'DISTRICT_COMMERCIAL_HUB',
    'DISTRICT_INDUSTRIAL_ZONE',
    'DISTRICT_HARBOR',
	'DISTRICT_ENTERTAINMENT_COMPLEX',
	'DISTRICT_WATER_ENTERTAINMENT_COMPLEX'
);

-- 替换上述基础区域的文明特色区域
UPDATE Districts
SET OnePerCity = 0
WHERE DistrictType IN (
    SELECT CivUniqueDistrictType
    FROM DistrictReplaces
    WHERE ReplacesDistrictType IN (
        'DISTRICT_CAMPUS',
        'DISTRICT_THEATER',
        'DISTRICT_HOLY_SITE',
        'DISTRICT_COMMERCIAL_HUB',
        'DISTRICT_INDUSTRIAL_ZONE',
        'DISTRICT_HARBOR',
		'DISTRICT_ENTERTAINMENT_COMPLEX',
		'DISTRICT_WATER_ENTERTAINMENT_COMPLEX'
    )
);

CREATE TRIGGER IF NOT EXISTS t_GA_Megalopolis_Pro
AFTER INSERT ON DistrictReplaces WHEN NEW.ReplacesDistrictType != 'DISTRICT_CITY_CENTER'
BEGIN
	UPDATE Districts
	SET OnePerCity = 0
	WHERE DistrictType IN (
		SELECT CivUniqueDistrictType
		FROM DistrictReplaces
		WHERE ReplacesDistrictType IN (
			'DISTRICT_CAMPUS',
			'DISTRICT_THEATER',
			'DISTRICT_HOLY_SITE',
			'DISTRICT_COMMERCIAL_HUB',
			'DISTRICT_INDUSTRIAL_ZONE',
			'DISTRICT_HARBOR',
			'DISTRICT_ENTERTAINMENT_COMPLEX',
			'DISTRICT_WATER_ENTERTAINMENT_COMPLEX'
		)
	);
END;