-- RequirementSets
INSERT OR REPLACE INTO RequirementSets 				(RequirementSetId ,     RequirementSetType) 	VALUES 		
('GOLDEN_PLAYER_HAS_ANY_ERA_ANCIENT_WONDERS_REQUIREMENTS' , 		        'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_PLAYER_HAS_ANY_ERA_CLASSICAL_WONDERS_REQUIREMENTS' , 		        'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_PLAYER_HAS_ANY_ERA_MEDIEVAL_WONDERS_REQUIREMENTS' , 		        'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_PLAYER_HAS_ANY_ERA_RENAISSANCE_WONDERS_REQUIREMENTS' , 		    'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_PLAYER_HAS_ANY_ERA_INDUSTRIAL_WONDERS_REQUIREMENTS' , 		        'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_PLAYER_HAS_ANY_ERA_MODERN_WONDERS_REQUIREMENTS' , 		        	'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_PLAYER_HAS_ANY_ERA_ATOMIC_WONDERS_REQUIREMENTS' , 		        	'REQUIREMENTSET_TEST_ANY');
-- RequirementSetRequirements
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,		RequirementId)
SELECT	 'GOLDEN_PLAYER_HAS_ANY_ERA_ANCIENT_WONDERS_REQUIREMENTS',		'GOLDEN_ANCIENT_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_MEDIEVAL';
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,		RequirementId)
SELECT	 'GOLDEN_PLAYER_HAS_ANY_ERA_CLASSICAL_WONDERS_REQUIREMENTS',	'GOLDEN_CLASSICAL_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_RENAISSANCE';
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,		RequirementId)
SELECT	 'GOLDEN_PLAYER_HAS_ANY_ERA_MEDIEVAL_WONDERS_REQUIREMENTS',		'GOLDEN_MEDIEVAL_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_INDUSTRIAL';
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,		RequirementId)
SELECT	 'GOLDEN_PLAYER_HAS_ANY_ERA_RENAISSANCE_WONDERS_REQUIREMENTS',	'GOLDEN_RENAISSANCE_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_MODERN';
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,		RequirementId)
SELECT	 'GOLDEN_PLAYER_HAS_ANY_ERA_INDUSTRIAL_WONDERS_REQUIREMENTS',	'GOLDEN_INDUSTRIAL_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_ATOMIC';
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,		RequirementId)
SELECT	 'GOLDEN_PLAYER_HAS_ANY_ERA_MODERN_WONDERS_REQUIREMENTS',		'GOLDEN_MODERN_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_INFORMATION';
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,		RequirementId)
SELECT	 'GOLDEN_PLAYER_HAS_ANY_ERA_ATOMIC_WONDERS_REQUIREMENTS',		'GOLDEN_ATOMIC_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType 
FROM Buildings WHERE BuildingType IN ('BUILDING_ESTADIO_DO_MARACANA', 'BUILDING_SYDNEY_OPERA_HOUSE', 'BUILDING_AMUNDSEN_SCOTT_RESEARCH_STATION');
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,		RequirementId)
SELECT	 'GOLDEN_PLAYER_HAS_ANY_ERA_ATOMIC_WONDERS_REQUIREMENTS',		'GOLDEN_ATOMIC_WONDER_REQUIRES_PLAYER_HAS_BUILDING_BIOSPHERE'
WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_BIOSPHERE');--'BUILDING_BIOSPHERE' Byzantium_Gaul
-- Requirements
INSERT OR REPLACE INTO Requirements (RequirementId,			RequirementType)
SELECT	 'GOLDEN_ANCIENT_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType,	   		'REQUIREMENT_PLAYER_HAS_BUILDING' 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_MEDIEVAL';
INSERT OR REPLACE INTO Requirements (RequirementId,			RequirementType)
SELECT	 'GOLDEN_CLASSICAL_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType,	   	'REQUIREMENT_PLAYER_HAS_BUILDING' 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_RENAISSANCE';
INSERT OR REPLACE INTO Requirements (RequirementId,			RequirementType)
SELECT	 'GOLDEN_MEDIEVAL_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType,	   		'REQUIREMENT_PLAYER_HAS_BUILDING' 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_INDUSTRIAL';
INSERT OR REPLACE INTO Requirements (RequirementId,			RequirementType)
SELECT	 'GOLDEN_RENAISSANCE_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType,	  	'REQUIREMENT_PLAYER_HAS_BUILDING' 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_MODERN';
INSERT OR REPLACE INTO Requirements (RequirementId,			RequirementType)
SELECT	 'GOLDEN_INDUSTRIAL_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType,	   	'REQUIREMENT_PLAYER_HAS_BUILDING' 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_ATOMIC';
INSERT OR REPLACE INTO Requirements (RequirementId,			RequirementType)
SELECT	 'GOLDEN_MODERN_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType,	   		'REQUIREMENT_PLAYER_HAS_BUILDING' 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_INFORMATION';
INSERT OR REPLACE INTO Requirements (RequirementId,			RequirementType)
SELECT	 'GOLDEN_ATOMIC_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType,	   		'REQUIREMENT_PLAYER_HAS_BUILDING' 
FROM Buildings WHERE BuildingType IN ('BUILDING_ESTADIO_DO_MARACANA', 'BUILDING_SYDNEY_OPERA_HOUSE', 'BUILDING_AMUNDSEN_SCOTT_RESEARCH_STATION');
INSERT OR REPLACE INTO Requirements (RequirementId,			RequirementType)
SELECT	 'GOLDEN_ATOMIC_WONDER_REQUIRES_PLAYER_HAS_BUILDING_BIOSPHERE',	   		'REQUIREMENT_PLAYER_HAS_BUILDING' 
WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_BIOSPHERE');--'BUILDING_BIOSPHERE' Byzantium_Gaul
-- RequirementArguments
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value)
SELECT	 'GOLDEN_ANCIENT_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType,			'BuildingType',	    BuildingType 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_MEDIEVAL';	
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value)
SELECT	 'GOLDEN_CLASSICAL_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType,		'BuildingType',	    BuildingType 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_RENAISSANCE';	
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value)
SELECT	 'GOLDEN_MEDIEVAL_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType,			'BuildingType',	    BuildingType 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_INDUSTRIAL';	
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value)
SELECT	 'GOLDEN_RENAISSANCE_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType,		'BuildingType',	    BuildingType 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_MODERN';	
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value)
SELECT	 'GOLDEN_INDUSTRIAL_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType,		'BuildingType',	    BuildingType 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_ATOMIC';	
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value)
SELECT	 'GOLDEN_MODERN_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType,			'BuildingType',	    BuildingType 
FROM Buildings WHERE IsWonder = 1 AND ObsoleteEra = 'ERA_INFORMATION';	
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value)
SELECT	 'GOLDEN_ATOMIC_WONDER_REQUIRES_PLAYER_HAS_' || BuildingType,			'BuildingType',	    BuildingType 
FROM Buildings WHERE BuildingType IN ('BUILDING_ESTADIO_DO_MARACANA', 'BUILDING_SYDNEY_OPERA_HOUSE', 'BUILDING_AMUNDSEN_SCOTT_RESEARCH_STATION');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value)
SELECT	 'GOLDEN_ATOMIC_WONDER_REQUIRES_PLAYER_HAS_BUILDING_BIOSPHERE',			'BuildingType',	    'BUILDING_BIOSPHERE' 
WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_BIOSPHERE');--'BUILDING_BIOSPHERE' Byzantium_Gaul

--Types
INSERT OR REPLACE INTO Types(Type, Kind) VALUES
('GA_PROJECT_WONDER_VICTORY1', 'KIND_PROJECT'),
('GA_PROJECT_WONDER_VICTORY2', 'KIND_PROJECT'),
('GA_VICTORY_WONDER', 'KIND_VICTORY');
	
-- Enable project
INSERT OR REPLACE INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'GOLDEN_MODIFIER_WONDER_VICTORY_GRANT_PROJECT');
INSERT OR REPLACE INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('GOLDEN_MODIFIER_WONDER_VICTORY_GRANT_PROJECT', 'GOLDEN_WONDER_VICTORY_MODIFIER_GRANT_PROJECT', 'WONDER_VICTORY_ONE_WONDER_FROM_EACH_ERA');
INSERT OR REPLACE INTO ModifierArguments(ModifierId, Name, Value) VALUES
('GOLDEN_MODIFIER_WONDER_VICTORY_GRANT_PROJECT', 'ProjectType', 'GA_PROJECT_WONDER_VICTORY1');

INSERT OR REPLACE INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('WONDER_VICTORY_ONE_WONDER_FROM_EACH_ERA', 'REQUIREMENTSET_TEST_ALL');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,         RequirementId) VALUES 		
('WONDER_VICTORY_ONE_WONDER_FROM_EACH_ERA' , 		    'GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_ANCIENT_WONDERS'),
('WONDER_VICTORY_ONE_WONDER_FROM_EACH_ERA' , 		    'GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_CLASSICAL_WONDERS'),
('WONDER_VICTORY_ONE_WONDER_FROM_EACH_ERA' , 		    'GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_MEDIEVAL_WONDERS'),
('WONDER_VICTORY_ONE_WONDER_FROM_EACH_ERA' , 		    'GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_RENAISSANCE_WONDERS'),
('WONDER_VICTORY_ONE_WONDER_FROM_EACH_ERA' , 		    'GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_INDUSTRIAL_WONDERS'),
('WONDER_VICTORY_ONE_WONDER_FROM_EACH_ERA' , 		    'GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_MODERN_WONDERS'),
('WONDER_VICTORY_ONE_WONDER_FROM_EACH_ERA' , 		    'GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_ATOMIC_WONDERS');
INSERT OR REPLACE INTO 		Requirements (RequirementId,				            RequirementType) VALUES					    
('GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_ANCIENT_WONDERS',		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_CLASSICAL_WONDERS',	'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_MEDIEVAL_WONDERS',		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_RENAISSANCE_WONDERS',	'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_INDUSTRIAL_WONDERS',	'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_MODERN_WONDERS',		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_ATOMIC_WONDERS',		'REQUIREMENT_REQUIREMENTSET_IS_MET');
INSERT OR REPLACE INTO 		RequirementArguments (RequirementId,		                Name,			    Value) VALUES						
('GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_ANCIENT_WONDERS',			    'RequirementSetId',		'GOLDEN_PLAYER_HAS_ANY_ERA_ANCIENT_WONDERS_REQUIREMENTS'),	
('GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_CLASSICAL_WONDERS',			'RequirementSetId',		'GOLDEN_PLAYER_HAS_ANY_ERA_CLASSICAL_WONDERS_REQUIREMENTS'),	
('GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_MEDIEVAL_WONDERS',			    'RequirementSetId',		'GOLDEN_PLAYER_HAS_ANY_ERA_MEDIEVAL_WONDERS_REQUIREMENTS'),	
('GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_RENAISSANCE_WONDERS',			'RequirementSetId',		'GOLDEN_PLAYER_HAS_ANY_ERA_RENAISSANCE_WONDERS_REQUIREMENTS'),	
('GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_INDUSTRIAL_WONDERS',			'RequirementSetId',		'GOLDEN_PLAYER_HAS_ANY_ERA_INDUSTRIAL_WONDERS_REQUIREMENTS'),	
('GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_MODERN_WONDERS',			    'RequirementSetId',		'GOLDEN_PLAYER_HAS_ANY_ERA_MODERN_WONDERS_REQUIREMENTS'),	
('GOLDEN_REQUIRES_PLAYER_HAS_ANY_ERA_ATOMIC_WONDERS',			    'RequirementSetId',		'GOLDEN_PLAYER_HAS_ANY_ERA_ATOMIC_WONDERS_REQUIREMENTS');	

-- Project
INSERT OR REPLACE INTO Projects
(ProjectType,					Name,									ShortName,								Description,							PrereqDistrict,				PrereqCivic,				Cost,	CostProgressionModel,	MaxPlayerInstances)
VALUES
('GA_PROJECT_WONDER_VICTORY1',	'LOC_GA_PROJECT_WONDER_VICTORY1_NAME',	'LOC_GA_PROJECT_WONDER_VICTORY1_NAME',	'LOC_GA_PROJECT_WONDER_VICTORY1_DESC',	'DISTRICT_CITY_CENTER',		'CIVIC_ENVIRONMENTALISM',	10000,	'NO_PROGRESSION_MODEL',	1),
('GA_PROJECT_WONDER_VICTORY2',	'LOC_GA_PROJECT_WONDER_VICTORY2_NAME',	'LOC_GA_PROJECT_WONDER_VICTORY2_NAME',	'LOC_GA_PROJECT_WONDER_VICTORY2_DESC',	'DISTRICT_CITY_CENTER',		'CIVIC_CULTURAL_HEGEMONY',	20000,	'NO_PROGRESSION_MODEL',	1);

INSERT OR REPLACE INTO Projects_XP2(ProjectType, UnlocksFromEffect) VALUES
('GA_PROJECT_WONDER_VICTORY1', 1),
('GA_PROJECT_WONDER_VICTORY2', 1);

INSERT OR REPLACE INTO ProjectCompletionModifiers
(ProjectType,							ModifierId) VALUES	
('GA_PROJECT_WONDER_VICTORY1',			'PROJECT_COMPLETION_UNLOCK_GA_PROJECT_WONDER_VICTORY2');
INSERT OR REPLACE INTO Modifiers
(ModifierId,												 ModifierType,													SubjectRequirementSetId) VALUES	
('PROJECT_COMPLETION_UNLOCK_GA_PROJECT_WONDER_VICTORY2',	 'GOLDEN_WONDER_VICTORY_MODIFIER_GRANT_PROJECT',				NULL);
INSERT OR REPLACE INTO ModifierArguments(ModifierId, Name, Value) VALUES
('PROJECT_COMPLETION_UNLOCK_GA_PROJECT_WONDER_VICTORY2', 'ProjectType', 'GA_PROJECT_WONDER_VICTORY2');

-- Victory
INSERT OR REPLACE INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('GA_WONDER_VICTORY_VICTORY_REQS', 'REQUIREMENTSET_TEST_ALL');
INSERT OR REPLACE INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('GA_WONDER_VICTORY_VICTORY_REQS', 'GA_WONDER_VICTORY_COMPLETED_PROJECT');
INSERT OR REPLACE INTO Requirements(RequirementId, RequirementType) VALUES
('GA_WONDER_VICTORY_COMPLETED_PROJECT', 'REQUIREMENT_PLAYER_HAS_COMPLETED_PROJECT');
INSERT OR REPLACE INTO RequirementArguments(RequirementId, Name, Value) VALUES
('GA_WONDER_VICTORY_COMPLETED_PROJECT', 'ProjectType', 'GA_PROJECT_WONDER_VICTORY2');

INSERT OR REPLACE INTO Victories(VictoryType, 	Name, 							Description,							Blurb, 							RequirementSetId, 					Icon) VALUES
('GA_VICTORY_WONDER', 							'LOC_GA_VICTORY_WONDER_NAME', 	'LOC_GA_VICTORY_WONDER_DESCRIPTION', 	'LOC_GA_VICTORY_WONDER_TEXT', 	'GA_WONDER_VICTORY_VICTORY_REQS', 	'ICON_VICTORY_SCORE');