--------------------------------------------------------------
-- Modifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO Modifiers 
(ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	
'GOLDEN_'|| a.EraType ||'_BUFF_' || b.YieldType,	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'GOLDEN_PLAYER_HAS_'|| a.EraType ||'_ANY_TECH_CIVIC_REQUIREMENTS' 
FROM Eras AS a, Yields AS b;

INSERT OR REPLACE INTO Modifiers 
(ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	
'GOLDEN_'|| a.EraType ||'_DEBUFF_' || b.YieldType,	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'GOLDEN_PLAYER_HAS_'|| a.EraType ||'_ANY_TECH_CIVIC_REQUIREMENTS' 
FROM Eras AS a, Yields AS b;
--------------------------------------------------------------
-- ModifierArguments
--------------------------------------------------------------
INSERT OR REPLACE INTO ModifierArguments 
(ModifierId, Name, Value)
SELECT	
'GOLDEN_'|| a.EraType ||'_BUFF_' || b.YieldType,	'YieldType', b.YieldType 
FROM Eras AS a, Yields AS b;

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId, Name, Value)
SELECT	
'GOLDEN_'|| a.EraType ||'_BUFF_' || b.YieldType,	'Amount', 15
FROM Eras AS a, Yields AS b;

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId, Name, Value)
SELECT	
'GOLDEN_'|| a.EraType ||'_DEBUFF_' || b.YieldType,	'YieldType', b.YieldType 
FROM Eras AS a, Yields AS b;

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId, Name, Value)
SELECT	
'GOLDEN_'|| a.EraType ||'_DEBUFF_' || b.YieldType,	'Amount', -15
FROM Eras AS a, Yields AS b;
--------------------------------------------------------------
-- RequirementSets
--------------------------------------------------------------	
INSERT OR REPLACE INTO RequirementSets	
(RequirementSetId , RequirementSetType)
SELECT 		
'GOLDEN_PLAYER_HAS_'|| EraType ||'_ANY_TECH_CIVIC_REQUIREMENTS' , 			'REQUIREMENTSET_TEST_ALL'
FROM Eras;
--------------------------------------------------------------
-- RequirementSetRequirements
--------------------------------------------------------------			
INSERT OR REPLACE INTO RequirementSetRequirements
(RequirementSetId , RequirementId)
SELECT
'GOLDEN_PLAYER_HAS_'|| EraType ||'_ANY_TECH_CIVIC_REQUIREMENTS' , 			'GOLDEN_REQUIRES_PLAYER_HAS_'|| EraType ||'_ANY_TECH'
FROM Eras;

INSERT OR REPLACE INTO RequirementSetRequirements
(RequirementSetId , RequirementId)
SELECT
'GOLDEN_PLAYER_HAS_'|| EraType ||'_ANY_TECH_CIVIC_REQUIREMENTS' , 			'GOLDEN_REQUIRES_PLAYER_HAS_'|| EraType ||'_ANY_CIVIC'
FROM Eras;
--------------------------------------------------------------
-- Requirements
--------------------------------------------------------------	
INSERT OR REPLACE INTO Requirements
(RequirementId,				   RequirementType) 
SELECT
'GOLDEN_REQUIRES_PLAYER_HAS_'|| EraType ||'_ANY_TECH',		'REQUIREMENT_REQUIREMENTSET_IS_MET'
FROM Eras;

INSERT OR REPLACE INTO Requirements
(RequirementId,				   RequirementType) 
SELECT
'GOLDEN_REQUIRES_PLAYER_HAS_'|| EraType ||'_ANY_CIVIC',		'REQUIREMENT_REQUIREMENTSET_IS_MET'
FROM Eras;
--------------------------------------------------------------
-- RequirementArguments
--------------------------------------------------------------	
INSERT OR REPLACE INTO RequirementArguments 
(RequirementId,		                						Name,			        Value) 
SELECT
'GOLDEN_REQUIRES_PLAYER_HAS_'|| EraType ||'_ANY_TECH',		'RequirementSetId',		'GOLDEN_PLAYER_HAS_'|| EraType ||'_TECH_REQUIREMENTS'
FROM Eras;

INSERT OR REPLACE INTO RequirementArguments 
(RequirementId,		                						Name,			        Value) 
SELECT
'GOLDEN_REQUIRES_PLAYER_HAS_'|| EraType ||'_ANY_CIVIC',		'RequirementSetId',		'GOLDEN_PLAYER_HAS_'|| EraType ||'_CIVIC_REQUIREMENTS'
FROM Eras;
----
--2023.10.14 Modifier
----
INSERT INTO RequirementSetRequirements
(RequirementSetId, RequirementId)
VALUES
('GOLDEN_PLAYER_HAS_ERA_ANCIENT_ANY_TECH_CIVIC_REQUIREMENTS',		'GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_CLASSICAL_ANY_TECH_AND_CIVIC'),
('GOLDEN_PLAYER_HAS_ERA_CLASSICAL_ANY_TECH_CIVIC_REQUIREMENTS',		'GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_MEDIEVAL_ANY_TECH_AND_CIVIC'),
('GOLDEN_PLAYER_HAS_ERA_MEDIEVAL_ANY_TECH_CIVIC_REQUIREMENTS',		'GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_RENAISSANCE_ANY_TECH_AND_CIVIC'),
('GOLDEN_PLAYER_HAS_ERA_RENAISSANCE_ANY_TECH_CIVIC_REQUIREMENTS',	'GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_INDUSTRIAL_ANY_TECH_AND_CIVIC'),
('GOLDEN_PLAYER_HAS_ERA_INDUSTRIAL_ANY_TECH_CIVIC_REQUIREMENTS',	'GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_MODERN_ANY_TECH_AND_CIVIC'),
('GOLDEN_PLAYER_HAS_ERA_MODERN_ANY_TECH_CIVIC_REQUIREMENTS',		'GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_ATOMIC_ANY_TECH_AND_CIVIC'),
('GOLDEN_PLAYER_HAS_ERA_ATOMIC_ANY_TECH_CIVIC_REQUIREMENTS',		'GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_INFORMATION_ANY_TECH_AND_CIVIC'),
('GOLDEN_PLAYER_HAS_ERA_INFORMATION_ANY_TECH_CIVIC_REQUIREMENTS',	'GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_FUTURE_ANY_TECH_AND_CIVIC'),
('GOLDEN_PLAYER_HAS_ERA_FUTURE_ANY_TECH_CIVIC_REQUIREMENTS',		'GOLDEN_REQUIRES_PLAYER_HAS_NO_FUTURE_TECH_AND_FUTURE_CIVIC');

INSERT OR REPLACE INTO Requirements
(RequirementId,				   											RequirementType) 
VALUES
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_CLASSICAL_ANY_TECH_AND_CIVIC',		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_MEDIEVAL_ANY_TECH_AND_CIVIC',		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_RENAISSANCE_ANY_TECH_AND_CIVIC',	'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_INDUSTRIAL_ANY_TECH_AND_CIVIC',		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_MODERN_ANY_TECH_AND_CIVIC',			'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_ATOMIC_ANY_TECH_AND_CIVIC',			'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_INFORMATION_ANY_TECH_AND_CIVIC',	'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_FUTURE_ANY_TECH_AND_CIVIC',			'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_FUTURE_TECH_AND_FUTURE_CIVIC',			'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT OR REPLACE INTO RequirementArguments 
(RequirementId,		                									Name,			        Value) 
VALUES
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_CLASSICAL_ANY_TECH_AND_CIVIC',		'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_CLASSICAL_ANY_TECH_AND_CIVIC'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_MEDIEVAL_ANY_TECH_AND_CIVIC',		'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_MEDIEVAL_ANY_TECH_AND_CIVIC'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_RENAISSANCE_ANY_TECH_AND_CIVIC',	'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_RENAISSANCE_ANY_TECH_AND_CIVIC'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_INDUSTRIAL_ANY_TECH_AND_CIVIC',		'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_INDUSTRIAL_ANY_TECH_AND_CIVIC'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_MODERN_ANY_TECH_AND_CIVIC',			'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_MODERN_ANY_TECH_AND_CIVIC'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_ATOMIC_ANY_TECH_AND_CIVIC',			'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_ATOMIC_ANY_TECH_AND_CIVIC'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_INFORMATION_ANY_TECH_AND_CIVIC',	'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_INFORMATION_ANY_TECH_AND_CIVIC'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_ERA_FUTURE_ANY_TECH_AND_CIVIC',			'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_FUTURE_ANY_TECH_AND_CIVIC'),
('GOLDEN_REQUIRES_PLAYER_HAS_NO_FUTURE_TECH_AND_FUTURE_CIVIC',			'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_FUTURE_TECH_AND_FUTURE_CIVIC');

INSERT OR REPLACE INTO RequirementSets	
(RequirementSetId, 												RequirementSetType)
VALUES
('GOLDEN_PLAYER_HAS_NO_ERA_CLASSICAL_ANY_TECH_AND_CIVIC',		'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_PLAYER_HAS_NO_ERA_MEDIEVAL_ANY_TECH_AND_CIVIC',		'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_PLAYER_HAS_NO_ERA_RENAISSANCE_ANY_TECH_AND_CIVIC',		'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_PLAYER_HAS_NO_ERA_INDUSTRIAL_ANY_TECH_AND_CIVIC',		'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_PLAYER_HAS_NO_ERA_MODERN_ANY_TECH_AND_CIVIC',			'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_PLAYER_HAS_NO_ERA_ATOMIC_ANY_TECH_AND_CIVIC',			'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_PLAYER_HAS_NO_ERA_INFORMATION_ANY_TECH_AND_CIVIC',		'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_PLAYER_HAS_NO_ERA_FUTURE_ANY_TECH_AND_CIVIC',			'REQUIREMENTSET_TEST_ANY'),
('GOLDEN_PLAYER_HAS_NO_FUTURE_TECH_AND_FUTURE_CIVIC',			'REQUIREMENTSET_TEST_ANY');

INSERT OR REPLACE INTO RequirementSetRequirements
(RequirementSetId,												RequirementId)
VALUES
('GOLDEN_PLAYER_HAS_NO_ERA_CLASSICAL_ANY_TECH_AND_CIVIC',		'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_CLASSICAL_ANY_TECH'),
('GOLDEN_PLAYER_HAS_NO_ERA_CLASSICAL_ANY_TECH_AND_CIVIC',		'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_CLASSICAL_ANY_CIVIC'),
('GOLDEN_PLAYER_HAS_NO_ERA_MEDIEVAL_ANY_TECH_AND_CIVIC',		'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_MEDIEVAL_ANY_TECH'),
('GOLDEN_PLAYER_HAS_NO_ERA_MEDIEVAL_ANY_TECH_AND_CIVIC',		'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_MEDIEVAL_ANY_CIVIC'),
('GOLDEN_PLAYER_HAS_NO_ERA_RENAISSANCE_ANY_TECH_AND_CIVIC',		'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_RENAISSANCE_ANY_TECH'),
('GOLDEN_PLAYER_HAS_NO_ERA_RENAISSANCE_ANY_TECH_AND_CIVIC',		'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_RENAISSANCE_ANY_CIVIC'),
('GOLDEN_PLAYER_HAS_NO_ERA_INDUSTRIAL_ANY_TECH_AND_CIVIC',		'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_INDUSTRIAL_ANY_TECH'),
('GOLDEN_PLAYER_HAS_NO_ERA_INDUSTRIAL_ANY_TECH_AND_CIVIC',		'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_INDUSTRIAL_ANY_CIVIC'),
('GOLDEN_PLAYER_HAS_NO_ERA_MODERN_ANY_TECH_AND_CIVIC',			'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_MODERN_ANY_TECH'),
('GOLDEN_PLAYER_HAS_NO_ERA_MODERN_ANY_TECH_AND_CIVIC',			'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_MODERN_ANY_CIVIC'),
('GOLDEN_PLAYER_HAS_NO_ERA_ATOMIC_ANY_TECH_AND_CIVIC',			'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_ATOMIC_ANY_TECH'),
('GOLDEN_PLAYER_HAS_NO_ERA_ATOMIC_ANY_TECH_AND_CIVIC',			'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_ATOMIC_ANY_CIVIC'),
('GOLDEN_PLAYER_HAS_NO_ERA_INFORMATION_ANY_TECH_AND_CIVIC',		'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_INFORMATION_ANY_TECH'),
('GOLDEN_PLAYER_HAS_NO_ERA_INFORMATION_ANY_TECH_AND_CIVIC',		'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_INFORMATION_ANY_CIVIC'),
('GOLDEN_PLAYER_HAS_NO_ERA_FUTURE_ANY_TECH_AND_CIVIC',			'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_FUTURE_ANY_TECH'),
('GOLDEN_PLAYER_HAS_NO_ERA_FUTURE_ANY_TECH_AND_CIVIC',			'GOLDEN_PLAYER_REALLY_HAS_NO_ERA_FUTURE_ANY_CIVIC'),
('GOLDEN_PLAYER_HAS_NO_FUTURE_TECH_AND_FUTURE_CIVIC',			'GOLDEN_REQUIRES_PLAYER_HAS_NO_TECH_FUTURE_TECH'),
('GOLDEN_PLAYER_HAS_NO_FUTURE_TECH_AND_FUTURE_CIVIC',			'GOLDEN_REQUIRES_PLAYER_HAS_NO_CIVIC_FUTURE_CIVIC');

INSERT OR REPLACE INTO Requirements
(RequirementId,				   								RequirementType) 
VALUES
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_CLASSICAL_ANY_TECH',		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_MEDIEVAL_ANY_TECH',		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_RENAISSANCE_ANY_TECH',	'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_INDUSTRIAL_ANY_TECH',		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_MODERN_ANY_TECH',			'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_ATOMIC_ANY_TECH',			'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_INFORMATION_ANY_TECH',	'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_FUTURE_ANY_TECH',			'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_CLASSICAL_ANY_CIVIC',		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_MEDIEVAL_ANY_CIVIC',		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_RENAISSANCE_ANY_CIVIC',	'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_INDUSTRIAL_ANY_CIVIC',	'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_MODERN_ANY_CIVIC',		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_ATOMIC_ANY_CIVIC',		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_INFORMATION_ANY_CIVIC',	'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_FUTURE_ANY_CIVIC',		'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT OR REPLACE INTO RequirementArguments 
(RequirementId,		                						Name,			        Value) 
VALUES
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_CLASSICAL_ANY_TECH',		'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_CLASSICAL_TECH_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_MEDIEVAL_ANY_TECH',		'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_MEDIEVAL_TECH_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_RENAISSANCE_ANY_TECH',	'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_RENAISSANCE_TECH_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_INDUSTRIAL_ANY_TECH',		'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_INDUSTRIAL_TECH_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_MODERN_ANY_TECH',			'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_MODERN_TECH_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_ATOMIC_ANY_TECH',			'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_ATOMIC_TECH_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_INFORMATION_ANY_TECH',	'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_INFORMATION_TECH_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_FUTURE_ANY_TECH',			'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_FUTURE_TECH_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_CLASSICAL_ANY_CIVIC',		'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_CLASSICAL_CIVIC_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_MEDIEVAL_ANY_CIVIC',		'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_MEDIEVAL_CIVIC_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_RENAISSANCE_ANY_CIVIC',	'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_RENAISSANCE_CIVIC_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_INDUSTRIAL_ANY_CIVIC',	'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_INDUSTRIAL_CIVIC_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_MODERN_ANY_CIVIC',		'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_MODERN_CIVIC_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_ATOMIC_ANY_CIVIC',		'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_ATOMIC_CIVIC_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_INFORMATION_ANY_CIVIC',	'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_INFORMATION_CIVIC_REQUIREMENTS'),
('GOLDEN_PLAYER_REALLY_HAS_NO_ERA_FUTURE_ANY_CIVIC',		'RequirementSetId',		'GOLDEN_PLAYER_HAS_NO_ERA_FUTURE_CIVIC_REQUIREMENTS');

--------------------------------------------------------------
-- TraitModifiers
--------------------------------------------------------------
--CIVILIZATION_AMERICA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_AMERICA',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM	Yields;	
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_AMERICA',	'GOLDEN_ERA_MODERN_BUFF_' || YieldType FROM Yields;	
--CIVILIZATION_ARABIA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_ARABIA',	'GOLDEN_ERA_MEDIEVAL_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_ARABIA',	'GOLDEN_ERA_RENAISSANCE_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_BRAZIL
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_BRAZIL',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_BRAZIL',	'GOLDEN_ERA_MODERN_BUFF_' || YieldType FROM Yields;
--CIVILIZATION_CHINA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_CHINA',	'GOLDEN_ERA_MEDIEVAL_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_CHINA',	'GOLDEN_ERA_RENAISSANCE_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_EGYPT
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_EGYPT',	'GOLDEN_ERA_ANCIENT_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_EGYPT',	'GOLDEN_ERA_CLASSICAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_ENGLAND
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_ENGLAND',	'GOLDEN_ERA_MEDIEVAL_DEBUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_ENGLAND',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields;
--CIVILIZATION_FRANCE
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_FRANCE',	'GOLDEN_ERA_MEDIEVAL_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_FRANCE',	'GOLDEN_ERA_RENAISSANCE_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_GERMANY
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_GERMANY',	'GOLDEN_ERA_MEDIEVAL_DEBUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_GERMANY',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields;
--CIVILIZATION_GREECE
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_GREECE',	'GOLDEN_ERA_ANCIENT_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_GREECE',	'GOLDEN_ERA_CLASSICAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_INDIA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_INDIA',	'GOLDEN_ERA_ANCIENT_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_INDIA',	'GOLDEN_ERA_CLASSICAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_JAPAN
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_JAPAN',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_JAPAN',	'GOLDEN_ERA_MODERN_BUFF_' || YieldType FROM Yields;
--CIVILIZATION_KONGO
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_KONGO',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_KONGO',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_NORWAY
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_NORWAY',	'GOLDEN_ERA_MEDIEVAL_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_NORWAY',	'GOLDEN_ERA_RENAISSANCE_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_ROME
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_ROME',	'GOLDEN_ERA_CLASSICAL_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_ROME',	'GOLDEN_ERA_MEDIEVAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_RUSSIA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_RUSSIA',	'GOLDEN_ERA_MODERN_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_RUSSIA',	'GOLDEN_ERA_ATOMIC_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_SCYTHIA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_SCYTHIA',	'GOLDEN_ERA_CLASSICAL_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_SCYTHIA',	'GOLDEN_ERA_MEDIEVAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_SPAIN
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_SPAIN',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_SPAIN',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_SUMERIA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_SUMERIA',	'GOLDEN_ERA_ANCIENT_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_SUMERIA',	'GOLDEN_ERA_CLASSICAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_CREE
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_CREE',	'GOLDEN_ERA_INDUSTRIAL_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_CREE',	'GOLDEN_ERA_MODERN_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_KOREA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_KOREA',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_KOREA',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_GEORGIA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_GEORGIA',	'GOLDEN_ERA_MEDIEVAL_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_GEORGIA',	'GOLDEN_ERA_RENAISSANCE_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_MAPUCHE
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MAPUCHE',	'GOLDEN_ERA_RENAISSANCE_DEBUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MAPUCHE',	'GOLDEN_ERA_INDUSTRIAL_BUFF_' || YieldType FROM Yields;
--CIVILIZATION_MONGOLIA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MONGOLIA',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MONGOLIA',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_NETHERLANDS
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_SCOTLAND
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_SCOTLAND',	'GOLDEN_ERA_RENAISSANCE_DEBUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_SCOTLAND',	'GOLDEN_ERA_INDUSTRIAL_BUFF_' || YieldType FROM Yields;
--CIVILIZATION_ZULU
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_ZULU',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_ZULU',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_CANADA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_CANADA',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_CANADA',	'GOLDEN_ERA_MODERN_BUFF_' || YieldType FROM Yields;
--CIVILIZATION_HUNGARY
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_HUNGARY',	'GOLDEN_ERA_MEDIEVAL_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_HUNGARY',	'GOLDEN_ERA_RENAISSANCE_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_INCA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_INCA',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_INCA',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_MALI
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MALI',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MALI',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_MAORI
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MAORI',	'GOLDEN_ERA_MEDIEVAL_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MAORI',	'GOLDEN_ERA_RENAISSANCE_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_OTTOMAN
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_OTTOMAN',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_OTTOMAN',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_PHOENICIA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_PHOENICIA',	'GOLDEN_ERA_ANCIENT_BUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_PHOENICIA',	'GOLDEN_ERA_CLASSICAL_DEBUFF_' || YieldType FROM Yields;
--CIVILIZATION_SWEDEN
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_SWEDEN',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_SWEDEN',	'GOLDEN_ERA_MODERN_BUFF_' || YieldType FROM Yields;

--------------------------------------------------------------
-- CivilizationTraits
--------------------------------------------------------------
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,              TraitType) VALUES
                                         ('CIVILIZATION_AMERICA',        'GOLDEN_TRAIT_CIVILIZATION_AMERICA'),
										 ('CIVILIZATION_ARABIA',         'GOLDEN_TRAIT_CIVILIZATION_ARABIA'),
										 ('CIVILIZATION_BRAZIL',         'GOLDEN_TRAIT_CIVILIZATION_BRAZIL'),
										 ('CIVILIZATION_CHINA',          'GOLDEN_TRAIT_CIVILIZATION_CHINA'),
										 ('CIVILIZATION_EGYPT',          'GOLDEN_TRAIT_CIVILIZATION_EGYPT'),
										 ('CIVILIZATION_ENGLAND',        'GOLDEN_TRAIT_CIVILIZATION_ENGLAND'),
										 ('CIVILIZATION_FRANCE',         'GOLDEN_TRAIT_CIVILIZATION_FRANCE'),
										 ('CIVILIZATION_GERMANY',        'GOLDEN_TRAIT_CIVILIZATION_GERMANY'),
										 ('CIVILIZATION_GREECE',         'GOLDEN_TRAIT_CIVILIZATION_GREECE'),
										 ('CIVILIZATION_INDIA',          'GOLDEN_TRAIT_CIVILIZATION_INDIA'),
										 ('CIVILIZATION_JAPAN',          'GOLDEN_TRAIT_CIVILIZATION_JAPAN'),
										 ('CIVILIZATION_KONGO',          'GOLDEN_TRAIT_CIVILIZATION_KONGO'),
										 ('CIVILIZATION_NORWAY',         'GOLDEN_TRAIT_CIVILIZATION_NORWAY'),
										 ('CIVILIZATION_ROME',           'GOLDEN_TRAIT_CIVILIZATION_ROME'),
										 ('CIVILIZATION_RUSSIA',         'GOLDEN_TRAIT_CIVILIZATION_RUSSIA'),
										 ('CIVILIZATION_SCYTHIA',        'GOLDEN_TRAIT_CIVILIZATION_SCYTHIA'),
										 ('CIVILIZATION_SPAIN',          'GOLDEN_TRAIT_CIVILIZATION_SPAIN'),
										 ('CIVILIZATION_SUMERIA',        'GOLDEN_TRAIT_CIVILIZATION_SUMERIA');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,              TraitType) VALUES
                                         ('CIVILIZATION_CREE',           'GOLDEN_TRAIT_CIVILIZATION_CREE'),
										 ('CIVILIZATION_KOREA',          'GOLDEN_TRAIT_CIVILIZATION_KOREA'),
										 ('CIVILIZATION_GEORGIA',        'GOLDEN_TRAIT_CIVILIZATION_GEORGIA'),
										 ('CIVILIZATION_MAPUCHE',        'GOLDEN_TRAIT_CIVILIZATION_MAPUCHE'),
										 ('CIVILIZATION_MONGOLIA',       'GOLDEN_TRAIT_CIVILIZATION_MONGOLIA'),
										 ('CIVILIZATION_NETHERLANDS',    'GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS'),
										 ('CIVILIZATION_SCOTLAND',       'GOLDEN_TRAIT_CIVILIZATION_SCOTLAND'),
										 ('CIVILIZATION_ZULU',           'GOLDEN_TRAIT_CIVILIZATION_ZULU');			
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,              TraitType) VALUES
                                         ('CIVILIZATION_CANADA',         'GOLDEN_TRAIT_CIVILIZATION_CANADA'),
										 ('CIVILIZATION_HUNGARY',        'GOLDEN_TRAIT_CIVILIZATION_HUNGARY'),
										 ('CIVILIZATION_INCA',           'GOLDEN_TRAIT_CIVILIZATION_INCA'),
										 ('CIVILIZATION_MALI',           'GOLDEN_TRAIT_CIVILIZATION_MALI'),
										 ('CIVILIZATION_MAORI',          'GOLDEN_TRAIT_CIVILIZATION_MAORI'),
										 ('CIVILIZATION_OTTOMAN',        'GOLDEN_TRAIT_CIVILIZATION_OTTOMAN'),
										 ('CIVILIZATION_PHOENICIA',      'GOLDEN_TRAIT_CIVILIZATION_PHOENICIA'),
										 ('CIVILIZATION_SWEDEN',         'GOLDEN_TRAIT_CIVILIZATION_SWEDEN');												 
--------------------------------------------------------------
-- Types
--------------------------------------------------------------
INSERT OR REPLACE INTO Types (Type,                                       Kind)  VALUES
                            ('GOLDEN_TRAIT_CIVILIZATION_AMERICA',        'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_ARABIA',         'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_BRAZIL',         'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_CHINA',          'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_EGYPT',          'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_ENGLAND',        'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_FRANCE',         'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_GERMANY',        'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_GREECE',         'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_INDIA',          'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_JAPAN',          'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_KONGO',          'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_NORWAY',         'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_ROME',           'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_RUSSIA',         'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_SCYTHIA',        'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_SPAIN',          'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_SUMERIA',        'KIND_TRAIT');
INSERT OR REPLACE INTO Types (Type,                                       Kind)  VALUES
                            ('GOLDEN_TRAIT_CIVILIZATION_CREE',           'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_KOREA',          'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_GEORGIA',        'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_MAPUCHE',        'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_MONGOLIA',       'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS',    'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_SCOTLAND',       'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_ZULU',           'KIND_TRAIT');		
INSERT OR REPLACE INTO Types (Type,                                       Kind)  VALUES
                            ('GOLDEN_TRAIT_CIVILIZATION_CANADA',         'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_HUNGARY',        'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_INCA',           'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_MALI',           'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_MAORI',          'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_OTTOMAN',        'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_PHOENICIA',      'KIND_TRAIT'),
							('GOLDEN_TRAIT_CIVILIZATION_SWEDEN',         'KIND_TRAIT');								
--------------------------------------------------------------
-- Traits
--------------------------------------------------------------
INSERT OR REPLACE INTO Traits (TraitType,                                  Name,                         Description) VALUES                       
                             ('GOLDEN_TRAIT_CIVILIZATION_AMERICA',        'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_AMERICA_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_ARABIA',         'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_ARABIA_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_BRAZIL',         'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_BRAZIL_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_CHINA',          'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_CHINA_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_EGYPT',          'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_EGYPT_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_ENGLAND',        'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_ENGLAND_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_FRANCE',         'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_FRANCE_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_GERMANY',        'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_GERMANY_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_GREECE',         'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_GREECE_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_INDIA',          'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_INDIA_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_JAPAN',          'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_JAPAN_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_KONGO',          'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_KONGO_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_NORWAY',         'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_NORWAY_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_ROME',           'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_ROME_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_RUSSIA',         'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_RUSSIA_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_SCYTHIA',        'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_SCYTHIA_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_SPAIN',          'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_SPAIN_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_SUMERIA',        'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_SUMERIA_DESCRIPTION');
INSERT OR REPLACE INTO Traits (TraitType,                                  Name,                         Description) VALUES                       
                             ('GOLDEN_TRAIT_CIVILIZATION_CREE',           'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_CREE_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_KOREA',          'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_KOREA_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_GEORGIA',        'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_GEORGIA_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_MAPUCHE',        'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_MAPUCHE_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_MONGOLIA',       'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_MONGOLIA_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS',    'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_SCOTLAND',       'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_SCOTLAND_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_ZULU',           'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_ZULU_DESCRIPTION');		
INSERT OR REPLACE INTO Traits (TraitType,                                  Name,                         Description) VALUES                       
                             ('GOLDEN_TRAIT_CIVILIZATION_CANADA',         'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_CANADA_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_HUNGARY',        'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_HUNGARY_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_INCA',           'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_INCA_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_MALI',           'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_MALI_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_MAORI',          'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_MAORI_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_OTTOMAN',        'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_OTTOMAN_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_PHOENICIA',      'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_PHOENICIA_DESCRIPTION'),
							 ('GOLDEN_TRAIT_CIVILIZATION_SWEDEN',         'LOC_GOLDEN_TRAIT_NAME',      'LOC_GOLDEN_TRAIT_CIVILIZATION_SWEDEN_DESCRIPTION');	