--CIVILIZATION_AUSTRALIA
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_AUSTRALIA_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_DIGGER');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_AUSTRALIA_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_AUSTRALIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_AUSTRALIA_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_DIGGER');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_AUSTRALIA',	'GOLDEN_CIVILIZATION_AUSTRALIA_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_DIGGER');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_AUSTRALIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ANIMAL_HUSBANDRY_PASTURE_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_DIGGER');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_AUSTRALIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ANIMAL_HUSBANDRY_NO_WATER_CITY_HOUSING' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_DIGGER');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_AUSTRALIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ASIA_PACIFIC_NON_WAR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_DIGGER');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_AUSTRALIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ASIA_PACIFIC_WAR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_DIGGER');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_AUSTRALIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ASIA_PACIFIC_FAITH_PURCHASE_HARBOR' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_DIGGER');
--CIVILIZATION_AZTEC
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_AZTEC_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_AZTEC_EAGLE_WARRIOR');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_AZTEC_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_AZTEC_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_AZTEC_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_AZTEC_EAGLE_WARRIOR');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_AZTEC',	'GOLDEN_CIVILIZATION_AZTEC_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_AZTEC_EAGLE_WARRIOR');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_AZTEC_CUSTOM_FEATURES',	'GOLDEN_TRAIT_PLANTATION_PLANTATION_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_AZTEC_EAGLE_WARRIOR');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_AZTEC_CUSTOM_FEATURES',	'GOLDEN_TRAIT_PLANTATION_LUXURY_HOUSING' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_AZTEC_EAGLE_WARRIOR');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_AZTEC_CUSTOM_FEATURES',	'GOLDEN_TRAIT_LATIN_AMERICA_TEN_POPULATION_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_AZTEC_EAGLE_WARRIOR');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_AZTEC_CUSTOM_FEATURES',	'GOLDEN_TRAIT_LATIN_AMERICA_NO_TEN_POPULATION_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_AZTEC_EAGLE_WARRIOR');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_AZTEC_CUSTOM_FEATURES',	'GOLDEN_TRAIT_LATIN_AMERICA_FAITH_PURCHASE_ENTERTAINMENT_COMPLEX' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_AZTEC_EAGLE_WARRIOR');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_AZTEC_CUSTOM_FEATURES',	'GOLDEN_TRAIT_LATIN_AMERICA_FAITH_PURCHASE_WATER_ENTERTAINMENT_COMPLEX' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_AZTEC_EAGLE_WARRIOR');

--CIVILIZATION_KHMER
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_KHMER_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_KHMER_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_KHMER_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_KHMER_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_KHMER',	'GOLDEN_CIVILIZATION_KHMER_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_KHMER_CUSTOM_FEATURES',	'GOLDEN_TRAIT_JUNGLE_CAMP_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_KHMER_CUSTOM_FEATURES',	'GOLDEN_TRAIT_JUNGLE_JUNGLE_APPEAL' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_KHMER_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ASIA_PACIFIC_NON_WAR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_KHMER_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ASIA_PACIFIC_WAR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_KHMER_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ASIA_PACIFIC_FAITH_PURCHASE_HARBOR' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
--CIVILIZATION_INDONESIA
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_INDONESIA',	'GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_FISHERY_FISHING_BOATS_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_FISHERY_COASTAL_CITY_HOUSING' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ASIA_PACIFIC_NON_WAR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ASIA_PACIFIC_WAR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ASIA_PACIFIC_FAITH_PURCHASE_HARBOR' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
--CIVILIZATION_NUBIA
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_NUBIAN_PITATI');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_NUBIAN_PITATI');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_NUBIA',	'GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_NUBIAN_PITATI');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_AGRICULTURE_FLOODPLAINS_APPEAL' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_NUBIAN_PITATI');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_AGRICULTURE_FLOODPLAINS_GRASSLAND_APPEAL' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_NUBIAN_PITATI');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_AGRICULTURE_FLOODPLAINS_PLAINS' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_NUBIAN_PITATI');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_AGRICULTURE_FARM_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_NUBIAN_PITATI');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_AFRICA_GOLDENAGE_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_NUBIAN_PITATI');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_AFRICA_DARKAGE_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_NUBIAN_PITATI');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_NUBIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_AFRICA_FAITH_PURCHASE_CITY_CENTER' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_NUBIAN_PITATI');
--CIVILIZATION_MACEDON
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_MACEDON_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_MACEDON_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_MACEDON_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_MACEDON_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_MACEDON',	'GOLDEN_CIVILIZATION_MACEDON_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_MACEDON_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ANIMAL_HUSBANDRY_PASTURE_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_MACEDON_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ANIMAL_HUSBANDRY_NO_WATER_CITY_HOUSING' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_MACEDON_CUSTOM_FEATURES',	'GOLDEN_TRAIT_MEDITERRANEAN_GOVERNOR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_MACEDON_CUSTOM_FEATURES',	'GOLDEN_TRAIT_MEDITERRANEAN_NO_GOVERNOR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_MACEDON_CUSTOM_FEATURES',	'GOLDEN_TRAIT_MEDITERRANEAN_FAITH_PURCHASE_COMMERCIAL_HUB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
--CIVILIZATION_PERSIA
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_PERSIA',	'GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_MANUFACTURE_QUARRY_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_MANUFACTURE_MOUNTAINS_CITY_HOUSING' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_WEST_ASIA_WAR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_WEST_ASIA_NON_WAR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_WEST_ASIA_FAITH_PURCHASE_ENCAMPMENT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
--CIVILIZATION_POLAND
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_POLAND_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_POLISH_HUSSAR');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_POLAND_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_POLAND_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_POLAND_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_POLISH_HUSSAR');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_POLAND',	'GOLDEN_CIVILIZATION_POLAND_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_POLISH_HUSSAR');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_POLAND_CUSTOM_FEATURES',	'GOLDEN_TRAIT_PLANTATION_PLANTATION_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_POLISH_HUSSAR');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_POLAND_CUSTOM_FEATURES',	'GOLDEN_TRAIT_PLANTATION_LUXURY_HOUSING' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_POLISH_HUSSAR');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_POLAND_CUSTOM_FEATURES',	'GOLDEN_TRAIT_CENTRAL_EASTERN_EUROPE_RELIGION_FOUNDER_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_POLISH_HUSSAR');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_POLAND_CUSTOM_FEATURES',	'GOLDEN_TRAIT_CENTRAL_EASTERN_EUROPE_NON_RELIGION_FOUNDER_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_POLISH_HUSSAR');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_POLAND_CUSTOM_FEATURES',	'GOLDEN_TRAIT_CENTRAL_EASTERN_EUROPE_FAITH_PURCHASE_HOLY_SITE' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_POLISH_HUSSAR');
--CIVILIZATION_MAYA
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_MAYA_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_MAYA_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_MAYA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_MAYA_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_MAYA',	'GOLDEN_CIVILIZATION_MAYA_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_MAYA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_PLANTATION_PLANTATION_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_MAYA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_PLANTATION_LUXURY_HOUSING' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_MAYA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_LATIN_AMERICA_TEN_POPULATION_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_MAYA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_LATIN_AMERICA_NO_TEN_POPULATION_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_MAYA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_LATIN_AMERICA_FAITH_PURCHASE_ENTERTAINMENT_COMPLEX' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_MAYA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_LATIN_AMERICA_FAITH_PURCHASE_WATER_ENTERTAINMENT_COMPLEX' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');

--CIVILIZATION_GRAN_COLOMBIA
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_GRAN_COLOMBIA_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_GRAN_COLOMBIA_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_GRAN_COLOMBIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_GRAN_COLOMBIA_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_GRAN_COLOMBIA',	'GOLDEN_CIVILIZATION_GRAN_COLOMBIA_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_GRAN_COLOMBIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_JUNGLE_CAMP_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_GRAN_COLOMBIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_JUNGLE_JUNGLE_APPEAL' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_GRAN_COLOMBIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_LATIN_AMERICA_TEN_POPULATION_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_GRAN_COLOMBIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_LATIN_AMERICA_NO_TEN_POPULATION_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_GRAN_COLOMBIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_LATIN_AMERICA_FAITH_PURCHASE_ENTERTAINMENT_COMPLEX' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_GRAN_COLOMBIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_LATIN_AMERICA_FAITH_PURCHASE_WATER_ENTERTAINMENT_COMPLEX' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');

--CIVILIZATION_ETHIOPIA
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_ETHIOPIA_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_ETHIOPIAN_OROMO_CAVALRY');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_ETHIOPIA_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_ETHIOPIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_ETHIOPIA_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_ETHIOPIAN_OROMO_CAVALRY');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_ETHIOPIA',	'GOLDEN_CIVILIZATION_ETHIOPIA_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_ETHIOPIAN_OROMO_CAVALRY');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_ETHIOPIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_AFRICA_GOLDENAGE_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_ETHIOPIAN_OROMO_CAVALRY');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_ETHIOPIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_AFRICA_DARKAGE_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_ETHIOPIAN_OROMO_CAVALRY');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_ETHIOPIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_AFRICA_FAITH_PURCHASE_CITY_CENTER' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_ETHIOPIAN_OROMO_CAVALRY');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_ETHIOPIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_PLANTATION_PLANTATION_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_ETHIOPIAN_OROMO_CAVALRY');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_ETHIOPIA_CUSTOM_FEATURES',	'GOLDEN_TRAIT_PLANTATION_LUXURY_HOUSING' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_ETHIOPIAN_OROMO_CAVALRY');

--CIVILIZATION_BYZANTIUM
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_BYZANTIUM',	'GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES',	'GOLDEN_TRAIT_MEDITERRANEAN_FAITH_PURCHASE_COMMERCIAL_HUB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES',	'GOLDEN_TRAIT_MEDITERRANEAN_GOVERNOR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES',	'GOLDEN_TRAIT_MEDITERRANEAN_NO_GOVERNOR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES',	'GOLDEN_TRAIT_MANUFACTURE_QUARRY_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_BYZANTIUM_CUSTOM_FEATURES',	'GOLDEN_TRAIT_MANUFACTURE_MOUNTAINS_CITY_HOUSING' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');

--CIVILIZATION_GAUL
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_GAUL_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_GAUL_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_GAUL_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_GAUL_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_GAUL',	'GOLDEN_CIVILIZATION_GAUL_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_GAUL_CUSTOM_FEATURES',	'GOLDEN_TRAIT_MANUFACTURE_QUARRY_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_GAUL_CUSTOM_FEATURES',	'GOLDEN_TRAIT_MANUFACTURE_MOUNTAINS_CITY_HOUSING' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_GAUL_CUSTOM_FEATURES',	'GOLDEN_TRAIT_NORTH_WESTERN_EUROPE_FAITH_PURCHASE_INDUSTRIAL_ZONE' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_GAUL_CUSTOM_FEATURES',	'GOLDEN_TRAIT_NORTH_WESTERN_EUROPE_NON_CAPITAL_CONTINENT_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_GAUL_CUSTOM_FEATURES',	'GOLDEN_TRAIT_NORTH_WESTERN_EUROPE_CAPITAL_CONTINENT_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');

--CIVILIZATION_BABYLON_STK
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BABYLONIAN_SABUM_KIBITTUM');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BABYLONIAN_SABUM_KIBITTUM');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_BABYLON_STK',	'GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BABYLONIAN_SABUM_KIBITTUM');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES',	'GOLDEN_TRAIT_AGRICULTURE_FLOODPLAINS_APPEAL' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BABYLONIAN_SABUM_KIBITTUM');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES',	'GOLDEN_TRAIT_AGRICULTURE_FLOODPLAINS_GRASSLAND_APPEAL' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BABYLONIAN_SABUM_KIBITTUM');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES',	'GOLDEN_TRAIT_AGRICULTURE_FLOODPLAINS_PLAINS' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BABYLONIAN_SABUM_KIBITTUM');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES',	'GOLDEN_TRAIT_AGRICULTURE_FARM_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BABYLONIAN_SABUM_KIBITTUM');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES',	'GOLDEN_TRAIT_WEST_ASIA_WAR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BABYLONIAN_SABUM_KIBITTUM');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES',	'GOLDEN_TRAIT_WEST_ASIA_NON_WAR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BABYLONIAN_SABUM_KIBITTUM');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_BABYLON_STK_CUSTOM_FEATURES',	'GOLDEN_TRAIT_WEST_ASIA_FAITH_PURCHASE_ENCAMPMENT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BABYLONIAN_SABUM_KIBITTUM');

--CIVILIZATION_VIETNAM
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_VIETNAM_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_VIETNAM_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_VIETNAM_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_VIETNAM_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_VIETNAM',	'GOLDEN_CIVILIZATION_VIETNAM_CUSTOM_FEATURES' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_VIETNAM_CUSTOM_FEATURES',	'GOLDEN_TRAIT_JUNGLE_CAMP_CULTURE_BOMB' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_VIETNAM_CUSTOM_FEATURES',	'GOLDEN_TRAIT_JUNGLE_JUNGLE_APPEAL' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_VIETNAM_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ASIA_PACIFIC_FAITH_PURCHASE_HARBOR' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_VIETNAM_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ASIA_PACIFIC_NON_WAR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_VIETNAM_CUSTOM_FEATURES',	'GOLDEN_TRAIT_ASIA_PACIFIC_WAR_IDENTITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');

--CIVILIZATION_PORTUGAL
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_CIVILIZATION_PORTUGAL_CUSTOM_FEATURES',	'KIND_TRAIT' WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PORTUGAL');

INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_CIVILIZATION_PORTUGAL_CUSTOM_FEATURES',	'LOC_GOLDEN_CIVILIZATION_PORTUGAL_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_PORTUGAL_CUSTOM_FEATURES_DESCRIPTION' WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PORTUGAL');

INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,        TraitType)
SELECT	'CIVILIZATION_PORTUGAL',	'GOLDEN_CIVILIZATION_PORTUGAL_CUSTOM_FEATURES' WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PORTUGAL');

INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_PORTUGAL_CUSTOM_FEATURES',	'GOLDEN_TRAIT_FISHERY_FISHING_BOATS_CULTURE_BOMB' WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PORTUGAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_PORTUGAL_CUSTOM_FEATURES',	'GOLDEN_TRAIT_FISHERY_COASTAL_CITY_HOUSING' WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PORTUGAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_PORTUGAL_CUSTOM_FEATURES',	'GOLDEN_TRAIT_NORTH_WESTERN_EUROPE_FAITH_PURCHASE_INDUSTRIAL_ZONE' WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PORTUGAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_PORTUGAL_CUSTOM_FEATURES',	'GOLDEN_TRAIT_NORTH_WESTERN_EUROPE_NON_CAPITAL_CONTINENT_IDENTITY' WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PORTUGAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,        ModifierID)
SELECT	'GOLDEN_CIVILIZATION_PORTUGAL_CUSTOM_FEATURES',	'GOLDEN_TRAIT_NORTH_WESTERN_EUROPE_CAPITAL_CONTINENT_IDENTITY' WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PORTUGAL');