-- =========================================================
-- Types
-- =========================================================

INSERT OR REPLACE INTO Types
    (Type, Kind)
VALUES
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'KIND_IMPROVEMENT'),
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'KIND_IMPROVEMENT'),
    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE',  'KIND_IMPROVEMENT'),
    ('IMPROVEMENT_MODERN_TRAP_DEFENSE',   'KIND_IMPROVEMENT');


-- =========================================================
-- Improvements
-- =========================================================

INSERT OR REPLACE INTO Improvements
    (ImprovementType, Name, Description, Icon, PlunderType, Buildable,
     PrereqTech, BuildInLine, Workable, CanBuildOutsideTerritory, Capturable)
VALUES
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE',
     'LOC_IMPROVEMENT_ANCIENT_TOWER_DEFENSE_NAME',
     'LOC_IMPROVEMENT_ANCIENT_TOWER_DEFENSE_DESC',
     'ICON_IMPROVEMENT_ANCIENT_TOWER_DEFENSE',
     'NO_PLUNDER', 1, 'TECH_MILITARY_ENGINEERING', 1, 0, 1, 0),

    ('IMPROVEMENT_MODERN_TOWER_DEFENSE',
     'LOC_IMPROVEMENT_MODERN_TOWER_DEFENSE_NAME',
     'LOC_IMPROVEMENT_MODERN_TOWER_DEFENSE_DESC',
     'ICON_IMPROVEMENT_MODERN_TOWER_DEFENSE',
     'NO_PLUNDER', 1, 'TECH_RIFLING', 1, 0, 1, 0),

    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE',
     'LOC_IMPROVEMENT_ANCIENT_TRAP_DEFENSE_NAME',
     'LOC_IMPROVEMENT_ANCIENT_TRAP_DEFENSE_DESC',
     'ICON_IMPROVEMENT_ANCIENT_TRAP_DEFENSE',
     'NO_PLUNDER', 1, 'TECH_CONSTRUCTION', 1, 0, 1, 0),

    ('IMPROVEMENT_MODERN_TRAP_DEFENSE',
     'LOC_IMPROVEMENT_MODERN_TRAP_DEFENSE_NAME',
     'LOC_IMPROVEMENT_MODERN_TRAP_DEFENSE_DESC',
     'ICON_IMPROVEMENT_MODERN_TRAP_DEFENSE',
     'NO_PLUNDER', 1, 'TECH_BALLISTICS', 1, 0, 1, 0);


-- =========================================================
-- 修改已有 Improvements 的 Description
-- XML:
-- <Update><Where Description="..."/><Set Description="..."/></Update>
-- =========================================================

UPDATE Improvements
SET Description = 'LOC_IMPROVEMENT_ALCAZAR_DESCRIPTION_ZOMBIE'
WHERE Description = 'LOC_IMPROVEMENT_ALCAZAR_DESCRIPTION';

UPDATE Improvements
SET Description = 'LOC_IMPROVEMENT_MAORI_PA_DESCRIPTION_ZOMBIE'
WHERE Description = 'LOC_IMPROVEMENT_MAORI_PA_DESCRIPTION';

UPDATE Improvements
SET Description = 'LOC_IMPROVEMENT_ROMAN_FORT_DESCRIPTION_ZOMBIE'
WHERE Description = 'LOC_IMPROVEMENT_ROMAN_FORT_DESCRIPTION';

UPDATE Improvements
SET Description = 'LOC_IMPROVEMENT_FORT_DESCRIPTION_ZOMBIE'
WHERE Description = 'LOC_IMPROVEMENT_FORT_DESCRIPTION';

UPDATE Improvements
SET Description = 'LOC_IMPROVEMENT_VAMPIRE_CASTLE_DESCRIPTION_ZOMBIE'
WHERE Description = 'LOC_IMPROVEMENT_VAMPIRE_CASTLE_DESCRIPTION';

UPDATE Improvements
SET Description = 'LOC_IMPROVEMENT_GREAT_WALL_DESCRIPTION_ZOMBIE'
WHERE Description = 'LOC_IMPROVEMENT_GREAT_WALL_DESCRIPTION';


-- =========================================================
-- Improvement_ValidTerrains
-- =========================================================

INSERT OR REPLACE INTO Improvement_ValidTerrains
    (ImprovementType, TerrainType)
VALUES
    -- Ancient Tower Defense
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'TERRAIN_DESERT'),
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'TERRAIN_TUNDRA'),
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'TERRAIN_PLAINS'),
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'TERRAIN_GRASS'),
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'TERRAIN_SNOW'),
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'TERRAIN_DESERT_HILLS'),
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'TERRAIN_TUNDRA_HILLS'),
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'TERRAIN_PLAINS_HILLS'),
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'TERRAIN_GRASS_HILLS'),
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'TERRAIN_SNOW_HILLS'),

    -- Modern Tower Defense
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'TERRAIN_DESERT'),
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'TERRAIN_TUNDRA'),
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'TERRAIN_PLAINS'),
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'TERRAIN_GRASS'),
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'TERRAIN_SNOW'),
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'TERRAIN_DESERT_HILLS'),
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'TERRAIN_TUNDRA_HILLS'),
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'TERRAIN_PLAINS_HILLS'),
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'TERRAIN_GRASS_HILLS'),
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'TERRAIN_SNOW_HILLS'),

    -- Ancient Trap Defense
    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE', 'TERRAIN_DESERT'),
    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE', 'TERRAIN_TUNDRA'),
    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE', 'TERRAIN_PLAINS'),
    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE', 'TERRAIN_GRASS'),
    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE', 'TERRAIN_SNOW'),
    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE', 'TERRAIN_DESERT_HILLS'),
    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE', 'TERRAIN_TUNDRA_HILLS'),
    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE', 'TERRAIN_PLAINS_HILLS'),
    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE', 'TERRAIN_GRASS_HILLS'),
    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE', 'TERRAIN_SNOW_HILLS'),

    -- Modern Trap Defense
    ('IMPROVEMENT_MODERN_TRAP_DEFENSE', 'TERRAIN_DESERT'),
    ('IMPROVEMENT_MODERN_TRAP_DEFENSE', 'TERRAIN_TUNDRA'),
    ('IMPROVEMENT_MODERN_TRAP_DEFENSE', 'TERRAIN_PLAINS'),
    ('IMPROVEMENT_MODERN_TRAP_DEFENSE', 'TERRAIN_GRASS'),
    ('IMPROVEMENT_MODERN_TRAP_DEFENSE', 'TERRAIN_SNOW'),
    ('IMPROVEMENT_MODERN_TRAP_DEFENSE', 'TERRAIN_DESERT_HILLS'),
    ('IMPROVEMENT_MODERN_TRAP_DEFENSE', 'TERRAIN_TUNDRA_HILLS'),
    ('IMPROVEMENT_MODERN_TRAP_DEFENSE', 'TERRAIN_PLAINS_HILLS'),
    ('IMPROVEMENT_MODERN_TRAP_DEFENSE', 'TERRAIN_GRASS_HILLS'),
    ('IMPROVEMENT_MODERN_TRAP_DEFENSE', 'TERRAIN_SNOW_HILLS');


-- =========================================================
-- Improvement_ValidBuildUnits
-- =========================================================

INSERT OR REPLACE INTO Improvement_ValidBuildUnits
    (ImprovementType, UnitType)
VALUES
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'UNIT_BUILDER'),
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'UNIT_MILITARY_ENGINEER'),
    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE', 'UNIT_BUILDER'),
    ('IMPROVEMENT_MODERN_TRAP_DEFENSE', 'UNIT_MILITARY_ENGINEER');


-- =========================================================
-- TypeProperties
-- =========================================================

INSERT OR REPLACE INTO TypeProperties
    (Type, Name, Value)
VALUES
    -- Ancient Tower Defense
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'PLOT_DAMAGE_TO_WALKING_INTO', '10'),
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'PLOT_DAMAGE_TO_WALKING_ADJACENT', '10'),

    -- Modern Tower Defense
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'PLOT_DAMAGE_TO_WALKING_INTO', '15'),
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'PLOT_DAMAGE_TO_WALKING_ADJACENT', '15'),

    -- Ancient Trap Defense
    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE', 'PLOT_DAMAGE_TO_WALKING_INTO', '15'),

    -- Modern Trap Defense
    ('IMPROVEMENT_MODERN_TRAP_DEFENSE', 'PLOT_DAMAGE_TO_WALKING_INTO', '20'),

    -- Visibility Control
    ('IMPROVEMENT_ANCIENT_TOWER_DEFENSE', 'IMPROVEMENT_VIS_CONTROL', '1'),
    ('IMPROVEMENT_MODERN_TOWER_DEFENSE', 'IMPROVEMENT_VIS_CONTROL', '1'),
    ('IMPROVEMENT_ANCIENT_TRAP_DEFENSE', 'IMPROVEMENT_VIS_CONTROL', '1'),
    ('IMPROVEMENT_MODERN_TRAP_DEFENSE', 'IMPROVEMENT_VIS_CONTROL', '1'),

    -- Existing improvements
    ('IMPROVEMENT_GREAT_WALL', 'PLOT_DAMAGE_TO_WALKING_INTO', '10'),
    ('IMPROVEMENT_GREAT_WALL', 'PLOT_DAMAGE_TO_WALKING_ADJACENT', '10'),
    ('IMPROVEMENT_FORT', 'PLOT_DAMAGE_TO_WALKING_INTO', '10'),
    ('IMPROVEMENT_ROMAN_FORT', 'PLOT_DAMAGE_TO_WALKING_INTO', '10'),
    ('IMPROVEMENT_MAORI_PA', 'PLOT_DAMAGE_TO_WALKING_INTO', '10');

