--CIVILIZATION_AUSTRALIA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_AUSTRALIA',	'GOLDEN_ERA_MODERN_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_DIGGER');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_AUSTRALIA',	'GOLDEN_ERA_ATOMIC_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_DIGGER');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_AUSTRALIA',	'GOLDEN_TRAIT_CIVILIZATION_AUSTRALIA' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_DIGGER');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_AUSTRALIA',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_DIGGER');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_AUSTRALIA',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_AUSTRALIA_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_DIGGER');

--CIVILIZATION_AZTEC
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_AZTEC',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_AZTEC_EAGLE_WARRIOR');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_AZTEC',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_AZTEC_EAGLE_WARRIOR');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_AZTEC',	'GOLDEN_TRAIT_CIVILIZATION_AZTEC' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_AZTEC_EAGLE_WARRIOR');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_AZTEC',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_AZTEC_EAGLE_WARRIOR');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_AZTEC',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_AZTEC_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_AZTEC_EAGLE_WARRIOR');

--CIVILIZATION_KHMER
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_KHMER',	'GOLDEN_ERA_MEDIEVAL_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_KHMER',	'GOLDEN_ERA_ATOMIC_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_KHMER',	'GOLDEN_TRAIT_CIVILIZATION_KHMER' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_KHMER',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_KHMER',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_KHMER_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');

--CIVILIZATION_INDONESIA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_INDONESIA',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_INDONESIA',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_INDONESIA',	'GOLDEN_TRAIT_CIVILIZATION_INDONESIA' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_INDONESIA',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_INDONESIA',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_INDONESIA_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');

--CIVILIZATION_NUBIA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_NUBIA',	'GOLDEN_ERA_ANCIENT_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_NUBIAN_PITATI');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_NUBIA',	'GOLDEN_ERA_CLASSICAL_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_NUBIAN_PITATI');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_NUBIA',	'GOLDEN_TRAIT_CIVILIZATION_NUBIA' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_NUBIAN_PITATI');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_NUBIA',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_NUBIAN_PITATI');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_NUBIA',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_NUBIA_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_NUBIAN_PITATI');

--CIVILIZATION_MACEDON
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MACEDON',	'GOLDEN_ERA_CLASSICAL_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MACEDON',	'GOLDEN_ERA_MEDIEVAL_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_MACEDON',	'GOLDEN_TRAIT_CIVILIZATION_MACEDON' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MACEDON',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MACEDON',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_MACEDON_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');

--CIVILIZATION_PERSIA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_PERSIA',	'GOLDEN_ERA_CLASSICAL_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_PERSIA',	'GOLDEN_ERA_MEDIEVAL_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_PERSIA',	'GOLDEN_TRAIT_CIVILIZATION_PERSIA' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_PERSIA',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_PERSIA',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_PERSIA_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL');

--CIVILIZATION_POLAND
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_POLAND',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_POLISH_HUSSAR');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_POLAND',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_POLISH_HUSSAR');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_POLAND',	'GOLDEN_TRAIT_CIVILIZATION_POLAND' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_POLISH_HUSSAR');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_POLAND',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_POLISH_HUSSAR');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_POLAND',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_POLAND_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_POLISH_HUSSAR');

--CIVILIZATION_MAYA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MAYA',	'GOLDEN_ERA_CLASSICAL_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MAYA',	'GOLDEN_ERA_MEDIEVAL_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_MAYA',	'GOLDEN_TRAIT_CIVILIZATION_MAYA' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MAYA',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_MAYA',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_MAYA_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');

--CIVILIZATION_GRAN_COLOMBIA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_GRAN_COLOMBIA',	'GOLDEN_ERA_RENAISSANCE_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_GRAN_COLOMBIA',	'GOLDEN_ERA_INDUSTRIAL_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_GRAN_COLOMBIA',	'GOLDEN_TRAIT_CIVILIZATION_GRAN_COLOMBIA' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_GRAN_COLOMBIA',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_GRAN_COLOMBIA',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_GRAN_COLOMBIA_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');

--CIVILIZATION_ETHIOPIA
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_ETHIOPIA',	'GOLDEN_ERA_INDUSTRIAL_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_ETHIOPIAN_OROMO_CAVALRY');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_ETHIOPIA',	'GOLDEN_ERA_MODERN_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_ETHIOPIAN_OROMO_CAVALRY');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_ETHIOPIA',	'GOLDEN_TRAIT_CIVILIZATION_ETHIOPIA' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_ETHIOPIAN_OROMO_CAVALRY');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_ETHIOPIA',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_ETHIOPIAN_OROMO_CAVALRY');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_ETHIOPIA',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_ETHIOPIA_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_ETHIOPIAN_OROMO_CAVALRY');

--CIVILIZATION_BYZANTIUM
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_BYZANTIUM',	'GOLDEN_ERA_MEDIEVAL_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_BYZANTIUM',	'GOLDEN_ERA_RENAISSANCE_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_BYZANTIUM',	'GOLDEN_TRAIT_CIVILIZATION_BYZANTIUM' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_BYZANTIUM',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_BYZANTIUM',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_BYZANTIUM_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');

--CIVILIZATION_GAUL
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_GAUL',	'GOLDEN_ERA_CLASSICAL_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_GAUL',	'GOLDEN_ERA_MEDIEVAL_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_GAUL',	'GOLDEN_TRAIT_CIVILIZATION_GAUL' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_GAUL',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_GAUL',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_GAUL_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');

--CIVILIZATION_BABYLON_STK
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_BABYLON_STK',	'GOLDEN_ERA_ANCIENT_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_BABYLONIAN_SABUM_KIBITTUM');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_BABYLON_STK',	'GOLDEN_ERA_CLASSICAL_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_BABYLONIAN_SABUM_KIBITTUM');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_BABYLON_STK',	'GOLDEN_TRAIT_CIVILIZATION_BABYLON_STK' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BABYLONIAN_SABUM_KIBITTUM');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_BABYLON_STK',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BABYLONIAN_SABUM_KIBITTUM');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_BABYLON_STK',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_BABYLON_STK_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BABYLONIAN_SABUM_KIBITTUM');

--CIVILIZATION_VIETNAM
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_ERA_MEDIEVAL_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_VIETNAMESE_VOI_CHIEN');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_VIETNAM',	'GOLDEN_ERA_RENAISSANCE_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_VIETNAMESE_VOI_CHIEN');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_VIETNAM',	'GOLDEN_TRAIT_CIVILIZATION_VIETNAM' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_VIETNAM',	'KIND_TRAIT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_VIETNAM',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_VIETNAM_DESCRIPTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');

--CIVILIZATION_PORTUGAL
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_PORTUGAL',	'GOLDEN_ERA_RENAISSANCE_BUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PORTUGAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_PORTUGAL',	'GOLDEN_ERA_INDUSTRIAL_DEBUFF_' || YieldType FROM Yields WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PORTUGAL');
INSERT OR REPLACE INTO CivilizationTraits (CivilizationType,									TraitType)
SELECT	'CIVILIZATION_PORTUGAL',	'GOLDEN_TRAIT_CIVILIZATION_PORTUGAL' WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PORTUGAL');
INSERT OR REPLACE INTO Types (Type,				Kind)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_PORTUGAL',	'KIND_TRAIT' WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PORTUGAL');
INSERT OR REPLACE INTO Traits (TraitType,        Name,                    Description)
SELECT	'GOLDEN_TRAIT_CIVILIZATION_PORTUGAL',	'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_PORTUGAL_DESCRIPTION' WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PORTUGAL');