--------------------------------------------------------------
-- Natural wonders
--------------------------------------------------------------
UPDATE Feature_YieldChanges SET YieldChange = 2
WHERE FeatureType = 'FEATURE_HA_LONG_BAY' AND YieldType = 'YIELD_CULTURE' AND EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_INDONESIAN_JONG');

--------------------------------------------------------------
-- BUILDING_JEBEL_BARKAL
UPDATE Buildings SET RegionalRange = 8
WHERE BuildingType = 'BUILDING_JEBEL_BARKAL' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_JEBEL_BARKAL');

UPDATE Building_YieldChanges SET YieldChange = 2
WHERE BuildingType = 'BUILDING_JEBEL_BARKAL' AND YieldType = 'YIELD_FAITH' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_JEBEL_BARKAL');
INSERT OR REPLACE INTO Building_YieldChanges		(BuildingType, YieldType, YieldChange)
SELECT	'BUILDING_JEBEL_BARKAL', 'YIELD_SCIENCE', 2 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_JEBEL_BARKAL');
INSERT OR REPLACE INTO Building_YieldChanges		(BuildingType, YieldType, YieldChange)
SELECT	'BUILDING_JEBEL_BARKAL', 'YIELD_CULTURE', 2 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_JEBEL_BARKAL');

DELETE FROM BuildingModifiers WHERE ModifierId = 'JEBELBARKAL_GRANT_FOUR_IRON_PER_TURN' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_JEBEL_BARKAL');

--------------------------------------------------------------
-- BUILDING_APADANA
UPDATE Modifiers SET ModifierType = "MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER", SubjectRequirementSetId = NULL
WHERE ModifierId = 'APADANA_AWARD_TWO_INFLUENCE_TOKEN' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_APADANA');

UPDATE ModifierArguments SET Value = 1
WHERE ModifierId = 'APADANA_AWARD_TWO_INFLUENCE_TOKEN_MODIFIER' AND Name = 'Amount' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_APADANA');

--------------------------------------------------------------
-- BUILDING_HALICARNASSUS_MAUSOLEUM
INSERT OR REPLACE INTO Building_GreatPersonPoints		(BuildingType, GreatPersonClassType, PointsPerTurn)
SELECT	'BUILDING_HALICARNASSUS_MAUSOLEUM', 'GREAT_PERSON_CLASS_ENGINEER', 2 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_HALICARNASSUS_MAUSOLEUM');

DELETE FROM BuildingModifiers WHERE ModifierId = 'HALICARNASSUS_MAUSOLEUM_YIELD_MODIFIER' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_APADANA');
INSERT OR REPLACE INTO BuildingModifiers(BuildingType, ModifierId)
SELECT	'BUILDING_HALICARNASSUS_MAUSOLEUM', 'GOLDEN_HALICARNASSUS_MAUSOLEUM_SCIENCE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_HALICARNASSUS_MAUSOLEUM');
INSERT OR REPLACE INTO BuildingModifiers(BuildingType, ModifierId)
SELECT	'BUILDING_HALICARNASSUS_MAUSOLEUM', 'GOLDEN_HALICARNASSUS_MAUSOLEUM_CULTURE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_HALICARNASSUS_MAUSOLEUM');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'GOLDEN_HALICARNASSUS_MAUSOLEUM_SCIENCE', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'GOLDEN_PLOT_HAS_COAST_REQUIREMENTS' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_HALICARNASSUS_MAUSOLEUM');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'GOLDEN_HALICARNASSUS_MAUSOLEUM_CULTURE', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'GOLDEN_PLOT_HAS_COAST_REQUIREMENTS' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_HALICARNASSUS_MAUSOLEUM');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_HALICARNASSUS_MAUSOLEUM_SCIENCE', 'YieldType', 'YIELD_SCIENCE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_HALICARNASSUS_MAUSOLEUM');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_HALICARNASSUS_MAUSOLEUM_SCIENCE', 'Amount', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_HALICARNASSUS_MAUSOLEUM');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_HALICARNASSUS_MAUSOLEUM_CULTURE', 'YieldType', 'YIELD_CULTURE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_HALICARNASSUS_MAUSOLEUM');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_HALICARNASSUS_MAUSOLEUM_CULTURE', 'Amount', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_HALICARNASSUS_MAUSOLEUM');
--------------------------------------------------------------
--BUILDING_BIOSPHERE
UPDATE Buildings SET Cost = 3000
WHERE BuildingType = 'BUILDING_BIOSPHERE' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_BIOSPHERE');