--格鲁吉亚
--Traits
UPDATE Traits SET Description = 'LOC_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_MODE_DESCRIPTION'
WHERE Description = 'LOC_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_DESCRIPTION';
--TraitModifiers
INSERT OR REPLACE INTO TraitModifiers (TraitType,					ModifierId)	
SELECT DISTINCT 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_NEW',	'GOLDEN_TRAIT_FAITH_PURCHASE_' ||PrereqDistrict|| '_BUILDINGS'
FROM Buildings WHERE (PrereqDistrict IS NOT NULL) AND (TraitType IS NULL) AND (InternalOnly = 0);
INSERT OR REPLACE INTO Modifiers (ModifierId,												ModifierType)
SELECT DISTINCT 'GOLDEN_TRAIT_FAITH_PURCHASE_' ||PrereqDistrict|| '_BUILDINGS',	'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE'
FROM Buildings WHERE (PrereqDistrict IS NOT NULL) AND (TraitType IS NULL) AND (InternalOnly = 0);
INSERT OR REPLACE INTO ModifierArguments (ModifierId,													Name,			Value)
SELECT DISTINCT	'GOLDEN_TRAIT_FAITH_PURCHASE_' ||PrereqDistrict|| '_BUILDINGS',	'DistrictType',	PrereqDistrict
FROM Buildings WHERE (PrereqDistrict IS NOT NULL) AND (TraitType IS NULL) AND (InternalOnly = 0);
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_NEW',	'GOLDEN_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_MASONRY_NEW'),
('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_NEW',	'GOLDEN_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_CASTLES_NEW');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
('GOLDEN_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_MASONRY_NEW',             'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',               1, 1, NULL),
('GOLDEN_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_CASTLES_NEW',	            'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',               1, 1, NULL);
---------------------------------------------------------------------------------------------------------------
-- ModifierArguments
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_MASONRY_NEW',		              'TechType',	    'TECH_MASONRY'),
('GOLDEN_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_CASTLES_NEW',			          'TechType',	    'TECH_CASTLES');
--自由城市忠诚度压力
UPDATE TypeProperties SET Value = 1
WHERE Name = 'FREE_CITY_INFLUENCE';

--自由城市比例
UPDATE TypeProperties SET Value = 20
WHERE Name = 'DARK_AGE_CITIES_LOST_PLAYER';
UPDATE TypeProperties SET Value = 20
WHERE Name = 'DARK_AGE_CITIES_LOST_AI';

--更多通配符槽位
UPDATE Government_SlotCounts SET NumSlots = NumSlots + 1
WHERE GovernmentSlotType = 'SLOT_WILDCARD';

--黄金时代政策
UPDATE Policies_XP1 SET MinimumGameEra = 'ERA_MODERN', MaximumGameEra = 'ERA_INFORMATION'
WHERE PolicyType = 'POLICY_MILITARY_INDUSTRIAL_COMPLEX';
UPDATE Policies_XP1 SET MinimumGameEra = 'ERA_ATOMIC'
WHERE PolicyType = 'POLICY_POPULAR_FRONT';
UPDATE Policies_XP1 SET MinimumGameEra = 'ERA_RENAISSANCE', MaximumGameEra = 'ERA_MODERN'
WHERE PolicyType = 'POLICY_FREE_ENQUIRY';
UPDATE Policies_XP1 SET MaximumGameEra = 'ERA_ATOMIC'
WHERE PolicyType = 'POLICY_CULTURE_INDUSTRY';
UPDATE Policies_XP1 SET MaximumGameEra = 'ERA_RENAISSANCE'
WHERE PolicyType = 'POLICY_MANDALA_STATE';

DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_HEARTBEAT_OF_STEAM' AND ModifierId='POLICY_HEARTBEAT_OF_STEAM_GA_INDUSTRIALINFORMATION';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_HEARTBEAT_OF_STEAM' AND ModifierId='POLICY_HEARTBEAT_OF_STEAM_GA_CAMPUS';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_FREE_ENQUIRY' AND ModifierId='POLICY_FREE_ENQUIRY_GA_HARBOR';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_FREE_ENQUIRY' AND ModifierId='POLICY_FREE_ENQUIRY_GA_COMMERCIAL_HUB';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_FREE_ENQUIRY' AND ModifierId='POLICY_FREE_ENQUIRY_GA_CAMPUS';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_CULTURE_INDUSTRY' AND ModifierId='POLICY_CULTURE_INDUSTRY_GA_CULTURE_DISTRICT';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_CULTURE_INDUSTRY' AND ModifierId='POLICY_CULTURE_INDUSTRY_GA_PURCHASE_ENTERTAINMENT_COMPLEX';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_CULTURE_INDUSTRY' AND ModifierId='POLICY_CULTURE_INDUSTRY_GA_PURCHASE_WATER_PARK';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_CULTURE_INDUSTRY' AND ModifierId='POLICY_CULTURE_INDUSTRY_GA_PRODUCTION_DISTRICT';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_MONUMENTALITY' AND ModifierId='POLICY_MONUMENTALITY_GA_MOVEMENT_SETTLER';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_MONUMENTALITY' AND ModifierId='POLICY_MONUMENTALITY_GA_BUILDER_DISCOUNT_MODIFIER';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_SKY_AND_STARS' AND ModifierId='POLICY_PRODUCTION_TO_SPACEPORTS';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_SKY_AND_STARS' AND ModifierId='POLICY_PRODUCTION_TO_AERODROMES';
INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           ModifierId)VALUES	
('POLICY_HEARTBEAT_OF_STEAM',          'GOLDEN_CITIES_PRODUCTION_STACKING'),
('POLICY_MILITARY_INDUSTRIAL_COMPLEX',          'GOLDEN_HEARTBEAT_OF_STEAM_INDUSTRIAL_GOLD'),
('POLICY_MILITARY_INDUSTRIAL_COMPLEX', 'GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_HORSES'),
('POLICY_MILITARY_INDUSTRIAL_COMPLEX', 'GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_IRON'),
('POLICY_MILITARY_INDUSTRIAL_COMPLEX', 'GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_NITER'),
('POLICY_MILITARY_INDUSTRIAL_COMPLEX', 'GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_COAL'),
('POLICY_FREE_ENQUIRY',                'GOLDEN_CITIES_SCIENCE_STACKING'),
('POLICY_CULTURE_INDUSTRY',            'GOLDEN_CITIES_CULTURE_STACKING'),
('POLICY_MANDALA_STATE',            'GOLDEN_CULTURE_INDUSTRY_THEATER_GOLD'),
('POLICY_SKY_AND_STARS',               'GOLDEN_SKY_AND_STARS_SPACE_RACE_PROJECTS_PRODUCTION'),
('POLICY_SKY_AND_STARS',      				'POLICY_FREE_ENQUIRY_GA_CAMPUS');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,                                         ModifierType,                                              SubjectRequirementSetId) VALUES	
('GOLDEN_CITIES_PRODUCTION_STACKING',                'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',                  NULL),
('GOLDEN_CITIES_PRODUCTION_STACKING_MODIFIER',       'MODIFIER_CITY_ADJUST_ALLOWED_INCOMING_REGIONAL_STACKING', NULL),
('GOLDEN_HEARTBEAT_OF_STEAM_INDUSTRIAL_GOLD',        'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS', 'DISTRICT_IS_INDUSTRIAL_ZONE'),
('GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_HORSES', 'MODIFIER_PLAYER_ADJUST_RESOURCE_ACCUMULATION_MODIFIER',   NULL),
('GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_IRON',   'MODIFIER_PLAYER_ADJUST_RESOURCE_ACCUMULATION_MODIFIER',   NULL),
('GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_NITER',  'MODIFIER_PLAYER_ADJUST_RESOURCE_ACCUMULATION_MODIFIER',   NULL),
('GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_COAL',   'MODIFIER_PLAYER_ADJUST_RESOURCE_ACCUMULATION_MODIFIER',   NULL),
('GOLDEN_CITIES_SCIENCE_STACKING',                   'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',                  NULL),
('GOLDEN_CITIES_SCIENCE_STACKING_MODIFIER',          'MODIFIER_CITY_ADJUST_ALLOWED_INCOMING_REGIONAL_STACKING', NULL),
('GOLDEN_CITIES_CULTURE_STACKING',                   'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',                  NULL),
('GOLDEN_CITIES_CULTURE_STACKING_MODIFIER',          'MODIFIER_CITY_ADJUST_ALLOWED_INCOMING_REGIONAL_STACKING', NULL),
('GOLDEN_CULTURE_INDUSTRY_THEATER_GOLD',             'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS', 'DISTRICT_IS_THEATER'),
('GOLDEN_SKY_AND_STARS_SPACE_RACE_PROJECTS_PRODUCTION', 'GOLDEN_MODIFIER_PLAYER_CITIES_ADJUST_SPACE_RACE_PROJECTS_PRODUCTION', NULL);

INSERT OR REPLACE INTO ModifierArguments
(ModifierId,                                                  Name,                   Value) VALUES	
('GOLDEN_CITIES_PRODUCTION_STACKING',                         'ModifierId',           'GOLDEN_CITIES_PRODUCTION_STACKING_MODIFIER'),
('GOLDEN_CITIES_PRODUCTION_STACKING_MODIFIER',                'YieldType',            'YIELD_PRODUCTION'),
('GOLDEN_HEARTBEAT_OF_STEAM_INDUSTRIAL_GOLD',                 'YieldTypeToMirror',    'YIELD_PRODUCTION'),
('GOLDEN_HEARTBEAT_OF_STEAM_INDUSTRIAL_GOLD',                 'YieldTypeToGrant',     'YIELD_GOLD'),
('GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_HORSES',          'Amount',        2),
('GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_HORSES',          'ResourceType',  'RESOURCE_HORSES'),
('GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_IRON',            'Amount',        2),
('GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_IRON',            'ResourceType',  'RESOURCE_IRON'),
('GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_NITER',           'Amount',        2),
('GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_NITER',           'ResourceType',  'RESOURCE_NITER'),
('GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_COAL',            'Amount',        2),
('GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_COAL',            'ResourceType',  'RESOURCE_COAL'),
('GOLDEN_CITIES_SCIENCE_STACKING',                            'ModifierId',    'GOLDEN_CITIES_SCIENCE_STACKING_MODIFIER'),
('GOLDEN_CITIES_SCIENCE_STACKING_MODIFIER',                   'YieldType',     'YIELD_SCIENCE'),
('GOLDEN_CITIES_CULTURE_STACKING',                            'ModifierId',    'GOLDEN_CITIES_CULTURE_STACKING_MODIFIER'),
('GOLDEN_CITIES_CULTURE_STACKING_MODIFIER',                   'YieldType',     'YIELD_CULTURE'),
('GOLDEN_CULTURE_INDUSTRY_THEATER_GOLD',                      'YieldTypeToMirror',    'YIELD_CULTURE'),
('GOLDEN_CULTURE_INDUSTRY_THEATER_GOLD',                      'YieldTypeToGrant',     'YIELD_GOLD'),
('GOLDEN_SKY_AND_STARS_SPACE_RACE_PROJECTS_PRODUCTION',       'Amount',               50);

UPDATE ModifierArguments SET Value = 25
WHERE ModifierId = 'POLICY_TO_ARMS_GA_PRODUCTION' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 200
WHERE ModifierId = 'POLICY_WISH_YOU_WERE_HERE_GA_WONDERS' AND Name = 'ScalingFactor';

--POLICY_PRAETORIAN_GUARD 罗马禁卫军
DELETE FROM PolicyModifiers WHERE ModifierId LIKE 'POLICY_PRAETORIAN_GUARD_GA_PRODUCTION_%';

INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           ModifierId)VALUES	
('POLICY_PRAETORIAN_GUARD',          'GOLDEN_PRAETORIAN_GUARD_COMBAT_STENGTH');
INSERT OR REPLACE INTO Modifiers 
(ModifierId,                                         ModifierType,                                              SubjectRequirementSetId) VALUES	
('GOLDEN_PRAETORIAN_GUARD_COMBAT_STENGTH',            'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',               NULL),
('ABILITY_PRAETORIAN_GUARD_COMBAT_STENGTH_MODIFIER',  'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',              NULL);
INSERT OR REPLACE INTO ModifierArguments
(ModifierId,                                                  Name,                   Value) VALUES	
('GOLDEN_PRAETORIAN_GUARD_COMBAT_STENGTH',            'AbilityType',      'ABILITY_PRAETORIAN_GUARD_COMBAT_STENGTH'),
('ABILITY_PRAETORIAN_GUARD_COMBAT_STENGTH_MODIFIER',  'Amount',           5);
INSERT OR REPLACE INTO ModifierStrings
(ModifierId,                                                  Context,                   Text) VALUES	
('ABILITY_PRAETORIAN_GUARD_COMBAT_STENGTH_MODIFIER',            'Preview',      'LOC_ABILITY_PRAETORIAN_GUARD_COMBAT_STENGTH_DESCRIPTION');
INSERT OR REPLACE INTO Types (Type,						Kind) VALUES
('ABILITY_PRAETORIAN_GUARD_COMBAT_STENGTH',					'KIND_ABILITY');	
INSERT OR REPLACE INTO TypeTags (Type,									Tag) VALUES	
('ABILITY_PRAETORIAN_GUARD_COMBAT_STENGTH',				'CLASS_ALL_COMBAT_UNITS');
INSERT OR REPLACE INTO UnitAbilities (UnitAbilityType,						Name,									Description, Inactive) VALUES	
('ABILITY_PRAETORIAN_GUARD_COMBAT_STENGTH',			'LOC_ABILITY_PRAETORIAN_GUARD_COMBAT_STENGTH_NAME',	'LOC_ABILITY_PRAETORIAN_GUARD_COMBAT_STENGTH_DESCRIPTION', 1);
INSERT OR REPLACE INTO UnitAbilityModifiers (UnitAbilityType,						ModifierId) VALUES	
('ABILITY_PRAETORIAN_GUARD_COMBAT_STENGTH',			            'ABILITY_PRAETORIAN_GUARD_COMBAT_STENGTH_MODIFIER');

--黑暗时代政策（来自动荡模式）
--POLICY_SAMODERZHAVIYE
UPDATE Policies_XP1 SET MinimumGameEra = 'ERA_CLASSICAL', MaximumGameEra = 'ERA_RENAISSANCE'
WHERE PolicyType = 'POLICY_SAMODERZHAVIYE';

DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_SAMODERZHAVIYE' AND ModifierId='SAMODERZHAVIYE_CAPITAL_PRODUCTION';
INSERT OR REPLACE INTO PolicyModifiers (PolicyType,				ModifierId)
SELECT	'POLICY_SAMODERZHAVIYE',		'GOLDEN_SAMODERZHAVIYE_CAPITAL_' ||YieldType FROM Yields;

INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,												SubjectRequirementSetId)
SELECT	'GOLDEN_SAMODERZHAVIYE_CAPITAL_' ||YieldType,	                        'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',			'BUILDING_IS_PALACE' FROM Yields;

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,			            Value)
SELECT	'GOLDEN_SAMODERZHAVIYE_CAPITAL_' ||YieldType,	        'Amount',	    75 FROM Yields;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,			            Value)
SELECT	'GOLDEN_SAMODERZHAVIYE_CAPITAL_' ||YieldType,	        'YieldType',	YieldType FROM Yields;

--POLICY_ISOLATIONISM
UPDATE Policies_XP1 SET MinimumGameEra = 'ERA_MEDIEVAL'
WHERE PolicyType = 'POLICY_ISOLATIONISM';

INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           ModifierId)VALUES	
('POLICY_ISOLATIONISM',          'GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_FAITH'),
('POLICY_ISOLATIONISM',          'GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_SCIENCE'),
('POLICY_ISOLATIONISM',          'GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_CULTURE');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,                                         ModifierType,                                              SubjectRequirementSetId) VALUES	
('GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_FAITH',   'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',              NULL),
('GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_SCIENCE',   'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',              NULL),
('GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_CULTURE',   'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',              NULL);
INSERT OR REPLACE INTO ModifierArguments
(ModifierId,                                                  Name,                   Value) VALUES	
('GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_FAITH',            'Amount',               3),
('GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_FAITH',            'YieldType',            'YIELD_FAITH'),
('GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_FAITH',            'Intercontinental',     0),
('GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_SCIENCE',            'Amount',               3),
('GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_SCIENCE',            'YieldType',            'YIELD_SCIENCE'),
('GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_SCIENCE',            'Intercontinental',     0),
('GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_CULTURE',            'Amount',               3),
('GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_CULTURE',            'YieldType',            'YIELD_CULTURE'),
('GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_CULTURE',            'Intercontinental',     0);

--POLICY_COLLECTIVISM
UPDATE Policies_XP1 SET MaximumGameEra = 'ERA_INFORMATION'
WHERE PolicyType = 'POLICY_COLLECTIVISM';

DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_COLLECTIVISM' AND ModifierId='COLLECTIVISM_ADD_HOUSING';
INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           ModifierId)VALUES	
('POLICY_COLLECTIVISM',          'COLLECTIVISM_INDUSTRIAL_ADJACENCY'),
('POLICY_COLLECTIVISM',          'COLLECTIVISM_FARM_FOOD');

--POLICY_DECENTRALIZATION
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_DECENTRALIZATION' AND ModifierId='DECENTRALIZATION_LOWPOP_LOYALTY';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_DECENTRALIZATION' AND ModifierId='DECENTRALIZATION_HIGHPOP_GOLD';

INSERT OR REPLACE INTO PolicyModifiers (PolicyType,				ModifierId)
SELECT	'POLICY_DECENTRALIZATION',		'GOLDEN_DECENTRALIZATION_LOWPOP_' ||YieldType FROM Yields;
INSERT OR REPLACE INTO PolicyModifiers (PolicyType,				ModifierId)
SELECT	'POLICY_DECENTRALIZATION',		'GOLDEN_DECENTRALIZATION_HIGHPOP_' ||YieldType FROM Yields;

INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,												SubjectRequirementSetId)
SELECT	'GOLDEN_DECENTRALIZATION_LOWPOP_' ||YieldType,	                        'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',			'GOLDEN_CITY_DONT_HAVE_TEN_POPULATION_REQUIREMENTS' FROM Yields;
INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,												SubjectRequirementSetId)
SELECT	'GOLDEN_DECENTRALIZATION_HIGHPOP_' ||YieldType,	                        'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',			'GOLDEN_CITY_HAS_TEN_POPULATION_REQUIREMENTS' FROM Yields;

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,			            Value)
SELECT	'GOLDEN_DECENTRALIZATION_LOWPOP_' ||YieldType,	        'Amount',	    40 FROM Yields;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,			            Value)
SELECT	'GOLDEN_DECENTRALIZATION_LOWPOP_' ||YieldType,	        'YieldType',	YieldType FROM Yields;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,			            Value)
SELECT	'GOLDEN_DECENTRALIZATION_HIGHPOP_' ||YieldType,	        'Amount',	    -10 FROM Yields;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,			            Value)
SELECT	'GOLDEN_DECENTRALIZATION_HIGHPOP_' ||YieldType,	        'YieldType',	YieldType FROM Yields;

--POLICY_DESPOTIC_PATERNALISM
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_DESPOTIC_PATERNALISM' AND ModifierId='DESPOTIC_PATERNALISM_LOYALTY';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_DESPOTIC_PATERNALISM' AND ModifierId='DESPOTIC_PATERNALISM_SCIENCE';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_DESPOTIC_PATERNALISM' AND ModifierId='DESPOTIC_PATERNALISM_CULTURE';

INSERT OR REPLACE INTO PolicyModifiers (PolicyType,				ModifierId)
SELECT	'POLICY_DESPOTIC_PATERNALISM',		'GOLDEN_DESPOTIC_PATERNALISM_GOVERNOR_' ||YieldType FROM Yields;
INSERT OR REPLACE INTO PolicyModifiers (PolicyType,				ModifierId)
SELECT	'POLICY_DESPOTIC_PATERNALISM',		'GOLDEN_DESPOTIC_PATERNALISM_NO_GOVERNOR_' ||YieldType FROM Yields;

INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,												SubjectRequirementSetId)
SELECT	'GOLDEN_DESPOTIC_PATERNALISM_GOVERNOR_' ||YieldType,	                        'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',			'CITY_HAS_GOVERNOR_REQUIREMENTS' FROM Yields;
INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,												SubjectRequirementSetId)
SELECT	'GOLDEN_DESPOTIC_PATERNALISM_NO_GOVERNOR_' ||YieldType,	                        'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',			'CITY_HAS_NO_GOVERNOR_REQUIREMENTS' FROM Yields;

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,			            Value)
SELECT	'GOLDEN_DESPOTIC_PATERNALISM_GOVERNOR_' ||YieldType,	        'Amount',	    10 FROM Yields;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,			            Value)
SELECT	'GOLDEN_DESPOTIC_PATERNALISM_GOVERNOR_' ||YieldType,	        'YieldType',	YieldType FROM Yields;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,			            Value)
SELECT	'GOLDEN_DESPOTIC_PATERNALISM_NO_GOVERNOR_' ||YieldType,	        'Amount',	    -10 FROM Yields;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,			            Value)
SELECT	'GOLDEN_DESPOTIC_PATERNALISM_NO_GOVERNOR_' ||YieldType,	        'YieldType',	YieldType FROM Yields;

--POLICY_SOFT_TARGETS
UPDATE Policies_XP1 SET MaximumGameEra = 'ERA_ATOMIC'
WHERE PolicyType = 'POLICY_SOFT_TARGETS';
UPDATE ModifierArguments SET Value = 20
WHERE ModifierId = 'SOFTTARGETS_COMBAT_STENGTH_DEFENDING_CITIES' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 20
WHERE ModifierId = 'SOFTTARGETS_COMBAT_STENGTH_ATTACKING_DISTRICTS' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = -5
WHERE ModifierId = 'SOFTTARGETS_COMBAT_STENGTH_ATTACKING_UNITS' AND Name = 'Amount';

--POLICY_ROBBER_BARONS
INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                      ModifierId)VALUES	
('POLICY_ROBBER_BARONS',          'GOLDEN_ROBBER_BARONS_GOLD_PLUS'),
('POLICY_ROBBER_BARONS',          'GOLDEN_ROBBER_BARONS_PRODUCTION_PLUS');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,                                         ModifierType,                                              SubjectRequirementSetId) VALUES	
('GOLDEN_ROBBER_BARONS_GOLD_PLUS',            'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',              'GOLDEN_CITY_HAS_SEAPORT_OR_STOCK_EXCHANGE_REQUIREMENTS'),
('GOLDEN_ROBBER_BARONS_PRODUCTION_PLUS',      'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',              'GOLDEN_CITY_HAS_SEAPORT_OR_STOCK_EXCHANGE_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments
(ModifierId,                                                  Name,                   Value) VALUES	
('GOLDEN_ROBBER_BARONS_GOLD_PLUS',            'YieldType',      'YIELD_GOLD'),
('GOLDEN_ROBBER_BARONS_GOLD_PLUS',            'Amount',           15),
('GOLDEN_ROBBER_BARONS_PRODUCTION_PLUS',      'YieldType',      'YIELD_PRODUCTION'),
('GOLDEN_ROBBER_BARONS_PRODUCTION_PLUS',      'Amount',           15);
UPDATE ModifierArguments SET Value = 15
WHERE ModifierId = 'ROBBERBARONS_BANK_OR_SHIPYARD_GOLD' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 15
WHERE ModifierId = 'ROBBERBARONS_BANK_OR_SHIPYARD_PRODUCTION' AND Name = 'Amount';

INSERT OR REPLACE INTO RequirementSets 				(RequirementSetId ,         RequirementSetType) 	VALUES 		
('GOLDEN_CITY_HAS_SEAPORT_OR_STOCK_EXCHANGE_REQUIREMENTS' , 		'REQUIREMENTSET_TEST_ANY');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,         RequirementId) 			VALUES 		
('GOLDEN_CITY_HAS_SEAPORT_OR_STOCK_EXCHANGE_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_CITY_HAS_BUILDING_SEAPORT'),
('GOLDEN_CITY_HAS_SEAPORT_OR_STOCK_EXCHANGE_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_CITY_HAS_BUILDING_STOCK_EXCHANGE');
	
--黑暗时代政策（来自迭起兴衰）
--POLICY_AUTOMATED_WORKFORCE
UPDATE Policies SET Description = 'LOC_POLICY_AUTOMATED_WORKFORCE_GA_DESCRIPTION'
WHERE PolicyType = 'POLICY_AUTOMATED_WORKFORCE';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_AUTOMATED_WORKFORCE' AND ModifierId='AUTOMATED_WORKFORCE_LOYALTY_LOSS';
UPDATE ModifierArguments SET Value = 100
WHERE ModifierId = 'AUTOMATED_WORKFORCE_PROJECT_PRODUCTION' AND Name = 'Amount';

--POLICY_CYBER_WARFARE
UPDATE Policies SET Description = 'LOC_POLICY_CYBER_WARFARE_GA_DESCRIPTION'
WHERE PolicyType = 'POLICY_CYBER_WARFARE';
UPDATE Policies_XP1 SET MinimumGameEra = 'ERA_ATOMIC'
WHERE PolicyType = 'POLICY_CYBER_WARFARE';
INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           ModifierId)VALUES	
('POLICY_CYBER_WARFARE',          'GOLDEN_CYBER_WARFARE_ESPIONAGE_ESTABLISH'),
('POLICY_CYBER_WARFARE',          'GOLDEN_CYBER_WARFARE_ESPIONAGE_REDUCTION');
INSERT OR REPLACE INTO Modifiers 
(ModifierId,                                         ModifierType,                                              SubjectRequirementSetId) VALUES	
('GOLDEN_CYBER_WARFARE_ESPIONAGE_ESTABLISH',   'MODIFIER_PLAYER_UNITS_ADJUST_SPY_ESTABLISH_TIME',              NULL),
('GOLDEN_CYBER_WARFARE_ESPIONAGE_REDUCTION',   'MODIFIER_PLAYER_UNITS_ADJUST_SPY_OFFENSIVE_OPERATION_TIME',    NULL);
INSERT OR REPLACE INTO ModifierArguments
(ModifierId,                                                  Name,                   Value) VALUES	
('GOLDEN_CYBER_WARFARE_ESPIONAGE_ESTABLISH',            'ReductionPercent',            100),
('GOLDEN_CYBER_WARFARE_ESPIONAGE_REDUCTION',            'ReductionPercent',            25);

--POLICY_DISINFORMATION_CAMPAIGN
UPDATE Policies SET Description = 'LOC_POLICY_DISINFORMATION_CAMPAIGN_GA_DESCRIPTION'
WHERE PolicyType = 'POLICY_DISINFORMATION_CAMPAIGN';
UPDATE Policies_XP1 SET MinimumGameEra = 'ERA_ATOMIC'
WHERE PolicyType = 'POLICY_DISINFORMATION_CAMPAIGN';
INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           ModifierId)VALUES	
('POLICY_DISINFORMATION_CAMPAIGN',          'GOLDEN_DISINFORMATION_CAMPAIGN_SPY_DEFENSE');
INSERT OR REPLACE INTO Modifiers 
(ModifierId,                                         ModifierType,                                              SubjectRequirementSetId) VALUES	
('GOLDEN_DISINFORMATION_CAMPAIGN_SPY_DEFENSE',   'MODIFIER_PLAYER_ADJUST_SPY_BONUS',              NULL);
INSERT OR REPLACE INTO ModifierArguments
(ModifierId,                                                  Name,                   Value) VALUES	
('GOLDEN_DISINFORMATION_CAMPAIGN_SPY_DEFENSE',            'Offense',           0),
('GOLDEN_DISINFORMATION_CAMPAIGN_SPY_DEFENSE',            'Amount',            3);
UPDATE ModifierArguments SET Value = 8
WHERE ModifierId = 'DISINFORMATION_CAMPAIGN_BROADCAST_FAVOR' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = -5
WHERE ModifierId = 'DISINFORMATION_CAMPAIGN_SCIENCE_REDUCTION' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = -5
WHERE ModifierId = 'DISINFORMATION_CAMPAIGN_CULTURE_REDUCTION' AND Name = 'Amount';

--POLICY_ROGUE_STATE
UPDATE Policies SET Description = 'LOC_POLICY_ROGUE_STATE_GA_DESCRIPTION'
WHERE PolicyType = 'POLICY_ROGUE_STATE';
UPDATE ModifierArguments SET Value = 100
WHERE ModifierId = 'ROGUESTATE_MANHATTANPROJECT_PRODUCTION' AND Name = 'Amount'; 
UPDATE ModifierArguments SET Value = 100
WHERE ModifierId = 'ROGUESTATE_PROJECTIVY_PRODUCTION' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 100
WHERE ModifierId = 'ROGUESTATE_NUCLEARDEVICE_PRODUCTION' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 100
WHERE ModifierId = 'ROGUESTATE_THERMONUCLEARDEVICE_PRODUCTION' AND Name = 'Amount';
INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           ModifierId)VALUES	
('POLICY_ROGUE_STATE',          'GOLDEN_ROGUE_STATE_NO_WMD_MAINTENANCE');
INSERT OR REPLACE INTO Modifiers 
(ModifierId,                                         ModifierType,                                              SubjectRequirementSetId) VALUES	
('GOLDEN_ROGUE_STATE_NO_WMD_MAINTENANCE',   'MODIFIER_PLAYER_ADJUST_WMD_MAINTENANCE_MODIFIER',              NULL);
INSERT OR REPLACE INTO ModifierArguments
(ModifierId,                                                  Name,                   Value) VALUES	
('GOLDEN_ROGUE_STATE_NO_WMD_MAINTENANCE',            'Amount',            100);

--POLICY_ELITE_FORCES
UPDATE Policies SET Description = 'LOC_POLICY_ELITE_FORCES_DA_GA_DESCRIPTION'
WHERE PolicyType = 'POLICY_ELITE_FORCES';
INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           ModifierId)VALUES	
('POLICY_ELITE_FORCES',          'GOLDEN_ELITE_FORCES_COMBAT_STENGTH');
INSERT OR REPLACE INTO Modifiers 
(ModifierId,                                         ModifierType,                                              SubjectRequirementSetId) VALUES	
('GOLDEN_ELITE_FORCES_COMBAT_STENGTH',            'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',               NULL),
('ABILITY_ELITE_FORCES_COMBAT_STENGTH_MODIFIER',  'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',              NULL);
INSERT OR REPLACE INTO ModifierArguments
(ModifierId,                                                  Name,                   Value) VALUES	
('GOLDEN_ELITE_FORCES_COMBAT_STENGTH',            'AbilityType',      'ABILITY_ELITE_FORCES_COMBAT_STENGTH'),
('ABILITY_ELITE_FORCES_COMBAT_STENGTH_MODIFIER',  'Amount',           10);
INSERT OR REPLACE INTO ModifierStrings
(ModifierId,                                                  Context,                   Text) VALUES	
('ABILITY_ELITE_FORCES_COMBAT_STENGTH_MODIFIER',            'Preview',      'LOC_ABILITY_ELITE_FORCES_COMBAT_STENGTH_DESCRIPTION');
INSERT OR REPLACE INTO Types (Type,						Kind) VALUES
('ABILITY_ELITE_FORCES_COMBAT_STENGTH',					'KIND_ABILITY');	
INSERT OR REPLACE INTO TypeTags (Type,									Tag) VALUES	
('ABILITY_ELITE_FORCES_COMBAT_STENGTH',				'CLASS_ALL_COMBAT_UNITS');
INSERT OR REPLACE INTO UnitAbilities (UnitAbilityType,						Name,									Description, Inactive) VALUES	
('ABILITY_ELITE_FORCES_COMBAT_STENGTH',			'LOC_ABILITY_ELITE_FORCES_COMBAT_STENGTH_NAME',	'LOC_ABILITY_ELITE_FORCES_COMBAT_STENGTH_DESCRIPTION', 1);
INSERT OR REPLACE INTO UnitAbilityModifiers (UnitAbilityType,						ModifierId) VALUES	
('ABILITY_ELITE_FORCES_COMBAT_STENGTH',			            'ABILITY_ELITE_FORCES_COMBAT_STENGTH_MODIFIER');
UPDATE ModifierArguments SET Value = -1
WHERE ModifierId = 'ELITEFORCES_EXTRA_MAINTENANCE' AND Name = 'Amount';

--POLICY_FLOWER_POWER
UPDATE Policies SET Description = 'LOC_POLICY_FLOWER_POWER_GA_DESCRIPTION'
WHERE PolicyType = 'POLICY_FLOWER_POWER';
UPDATE ModifierArguments SET Value = -50
WHERE ModifierId = 'FLOWER_POWER_PURCHASE_INCREASE' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = -50
WHERE ModifierId = 'FLOWER_POWER_PRODUCTION_INCREASE' AND Name = 'Amount';
INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           ModifierId)VALUES	
('POLICY_FLOWER_POWER',          'FUTURE_VICTORY_CULTURE_ROCK_BAND_PROMOTIONS');

--POLICY_INQUISITION
UPDATE Policies SET Description = 'LOC_POLICY_INQUISITION_DA_GA_DESCRIPTION'
WHERE PolicyType = 'POLICY_INQUISITION';
INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           ModifierId)VALUES	
('POLICY_INQUISITION',          'GOLDEN_INQUISITION_FAITH_MODIFIER');
INSERT OR REPLACE INTO Modifiers 
(ModifierId,                                         ModifierType,                                              SubjectRequirementSetId) VALUES	
('GOLDEN_INQUISITION_FAITH_MODIFIER',            'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',           'CITY_FOLLOWS_RELIGION_REQUIREMENTS');
INSERT OR REPLACE INTO ModifierArguments
(ModifierId,                                                  Name,                   Value) VALUES	
('GOLDEN_INQUISITION_FAITH_MODIFIER',            'YieldType',      'YIELD_FAITH'),
('GOLDEN_INQUISITION_FAITH_MODIFIER',            'Amount',           40);
UPDATE ModifierArguments SET Value = -10
WHERE ModifierId = 'INQUISITION_SCIENCE_MODIFIER' AND Name = 'Amount';

--POLICY_MONASTICISM
UPDATE Policies SET Description = 'LOC_POLICY_MONASTICISM_DA_GA_DESCRIPTION'
WHERE PolicyType = 'POLICY_MONASTICISM';
UPDATE Policies_XP1 SET MaximumGameEra = 'ERA_RENAISSANCE'
WHERE PolicyType = 'POLICY_MONASTICISM';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_MONASTICISM';
INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           ModifierId)VALUES	
('POLICY_MONASTICISM',          'GOLDEN_MONASTICISM_HOLYSITE_CULTURE'),
('POLICY_MONASTICISM',          'GOLDEN_MONASTICISM_HOLYSITE_SCIENCE'),
('POLICY_MONASTICISM',          'GOLDEN_MONASTICISM_CULTURE_MODIFIER'),
('POLICY_MONASTICISM',          'GOLDEN_MONASTICISM_SCIENCE_MODIFIER');
INSERT OR REPLACE INTO Modifiers 
(ModifierId,                                         ModifierType,                                              SubjectRequirementSetId) VALUES	
('GOLDEN_MONASTICISM_HOLYSITE_CULTURE',            'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',              'CITY_HAS_HOLY_SITE'),
('GOLDEN_MONASTICISM_HOLYSITE_SCIENCE',            'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',              'CITY_HAS_HOLY_SITE'),
('GOLDEN_MONASTICISM_CULTURE_MODIFIER',            'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',              'GOLDEN_CITY_HAS_NO_DISTRICT_HOLY_SITE_REQUIREMENTS'),
('GOLDEN_MONASTICISM_SCIENCE_MODIFIER',            'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',              'GOLDEN_CITY_HAS_NO_DISTRICT_HOLY_SITE_REQUIREMENTS');
INSERT OR REPLACE INTO ModifierArguments
(ModifierId,                                                  Name,                   Value) VALUES	
('GOLDEN_MONASTICISM_HOLYSITE_CULTURE',            'YieldType',      'YIELD_CULTURE'),
('GOLDEN_MONASTICISM_HOLYSITE_CULTURE',            'Amount',           20),
('GOLDEN_MONASTICISM_HOLYSITE_SCIENCE',            'YieldType',      'YIELD_SCIENCE'),
('GOLDEN_MONASTICISM_HOLYSITE_SCIENCE',            'Amount',           20),
('GOLDEN_MONASTICISM_CULTURE_MODIFIER',            'YieldType',      'YIELD_CULTURE'),
('GOLDEN_MONASTICISM_CULTURE_MODIFIER',            'Amount',           -20),
('GOLDEN_MONASTICISM_SCIENCE_MODIFIER',            'YieldType',      'YIELD_SCIENCE'),
('GOLDEN_MONASTICISM_SCIENCE_MODIFIER',            'Amount',           -20);
