--外交区相关
--DISTRICT_DIPLOMATIC_QUARTER
DELETE FROM District_TradeRouteYields WHERE DistrictType = 'DISTRICT_DIPLOMATIC_QUARTER';
INSERT OR REPLACE INTO District_TradeRouteYields 
(DistrictType, 					YieldType, 			YieldChangeAsOrigin, 	YieldChangeAsDomesticDestination, 	YieldChangeAsInternationalDestination) VALUES
('DISTRICT_DIPLOMATIC_QUARTER', 'YIELD_GOLD', 		0, 						0, 									2),
('DISTRICT_DIPLOMATIC_QUARTER', 'YIELD_PRODUCTION', 0, 						1, 									0),
('DISTRICT_DIPLOMATIC_QUARTER', 'YIELD_FOOD', 		0, 						1, 									0);
UPDATE Districts SET RequiresPopulation = 0
WHERE DistrictType = 'DISTRICT_DIPLOMATIC_QUARTER';

DELETE FROM DistrictModifiers WHERE ModifierId = 'DIPLOMATIC_QUARTER_AWARD_ONE_INFLUENCE_TOKEN';
INSERT OR REPLACE INTO DistrictModifiers (DistrictType, ModifierId) VALUES
('DISTRICT_DIPLOMATIC_QUARTER',  'CIVIC_AWARD_TWO_INFLUENCE_TOKENS');
-- ('DISTRICT_DIPLOMATIC_QUARTER', 'CIVIC_GRANT_PLAYER_GOVERNOR_POINTS');

UPDATE Buildings SET Maintenance = 2, PrereqTech = null, PrereqCivic = 'CIVIC_DIPLOMATIC_SERVICE', Cost = 500
WHERE BuildingType = 'BUILDING_CONSULATE';
UPDATE Buildings SET Maintenance = 3, PrereqCivic = 'CIVIC_IDEOLOGY', Cost = 800
WHERE BuildingType = 'BUILDING_CHANCERY';

INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_CONSULATE', 'CIVIC_GRANT_SPY'),
('BUILDING_CHANCERY',  'CIVIC_GRANT_SPY'),
('BUILDING_CONSULATE', 'CIVIC_AWARD_THREE_INFLUENCE_TOKENS'),
('BUILDING_CHANCERY',  'CIVIC_AWARD_THREE_INFLUENCE_TOKENS'),
-- ('BUILDING_CONSULATE', 'CIVIC_GRANT_PLAYER_GOVERNOR_POINTS'),
-- ('BUILDING_CHANCERY',  'CIVIC_GRANT_PLAYER_GOVERNOR_POINTS'),
('BUILDING_CONSULATE', 'PRINTING_ADD_DIPLO_VISIBILITY'),
('BUILDING_CHANCERY', 'GOLDEN_CHANCERY_COUNTERYSPY_CULTURE');

DELETE FROM BuildingModifiers WHERE ModifierId = 'CONSULATE_SPY_BONUS';

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES
('GOLDEN_CHANCERY_COUNTERYSPY_CULTURE', 'MODIFIER_PLAYER_ADJUST_COUNTER_SPY_AWARD_YIELD_PER_LEVEL', 0, 0, NULL);

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES
('GOLDEN_CHANCERY_COUNTERYSPY_CULTURE', 'YieldType', 'YIELD_CULTURE'),
('GOLDEN_CHANCERY_COUNTERYSPY_CULTURE', 'Amount', 200 ),
('GOLDEN_CHANCERY_COUNTERYSPY_CULTURE', 'PerXLevels', 1 );

UPDATE ModifierArguments SET Value = 200
WHERE ModifierId = 'CHANCERY_COUNTERYSPY_SCIENCE' AND Name = 'Amount';

DELETE FROM TechnologyModifiers WHERE ModifierId = 'PRINTING_ADD_DIPLO_VISIBILITY';
UPDATE Technologies SET Description = 'GA_LOC_TECH_PRINTING_DESCRIPTION'
WHERE TechnologyType = 'TECH_PRINTING';

--独裁统治
INSERT OR REPLACE INTO GovernmentModifiers (GovernmentType, ModifierId) VALUES
('GOVERNMENT_AUTOCRACY', 'GOLDEN_AUTOCRACY_DIPLOMATIC_QUARTER_ALLYIELD');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId) VALUES
('POLICY_GOV_AUTOCRACY', 'GOLDEN_AUTOCRACY_DIPLOMATIC_QUARTER_ALLYIELD');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES
('GOLDEN_AUTOCRACY_DIPLOMATIC_QUARTER_ALLYIELD', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_ALL_YIELDS_CHANGE', 0, 0, 'GOLDEN_CITY_HAS_DISTRICT_DIPLOMATIC_QUARTER_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES
('GOLDEN_AUTOCRACY_DIPLOMATIC_QUARTER_ALLYIELD', 'Amount', 2 );
UPDATE ModifierArguments SET Value = 2
WHERE ModifierId = 'CONSULATE_TIER1' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 2
WHERE ModifierId = 'CHANCERY_TIER2' AND Name = 'Amount';