-- NW_MIK
-- Author: Flactine
-- DateCreated: 4/24/2024 3:48:58 PM
--------------------------------------------------------------
INSERT OR REPLACE INTO District_Adjacencies 
(DistrictType,		YieldChangeId) 
SELECT
DistrictType,		'GOLDEN_NATIONAL_INDUSTRIAL_ZONE_PRODUCTION'
FROM Districts WHERE DistrictType = 'MIK_DISTRICT_GOLDSMITHY';

INSERT OR REPLACE INTO District_Adjacencies 
(DistrictType,		YieldChangeId) 
SELECT
DistrictType,		'GOLDEN_NATIONAL_INDUSTRIAL_ZONE_PRODUCTION_PLUS'
FROM Districts WHERE DistrictType = 'MIK_DISTRICT_GOLDSMITHY';

INSERT OR REPLACE INTO District_Adjacencies 
(DistrictType,		YieldChangeId) 
SELECT
DistrictType,		'GOLDEN_NATIONAL_THEATER_CULTURE'
FROM Districts WHERE DistrictType = 'MIK_DISTRICT_KOOTHAMBALAM';

INSERT OR REPLACE INTO District_Adjacencies 
(DistrictType,		YieldChangeId) 
SELECT
DistrictType,		'GOLDEN_NATIONAL_THEATER_CULTURE_PLUS'
FROM Districts WHERE DistrictType = 'MIK_DISTRICT_KOOTHAMBALAM';

INSERT OR REPLACE INTO District_Adjacencies 
(DistrictType,		YieldChangeId) 
SELECT
DistrictType,		'GOLDEN_NATIONAL_HOLY_SITE_FAITH'
FROM Districts WHERE DistrictType = 'MIK_DISTRICT_DEBRE';

INSERT OR REPLACE INTO District_Adjacencies 
(DistrictType,		YieldChangeId) 
SELECT
DistrictType,		'GOLDEN_NATIONAL_HOLY_SITE_FAITH_PLUS'
FROM Districts WHERE DistrictType = 'MIK_DISTRICT_DEBRE';

INSERT OR REPLACE INTO District_Adjacencies 
(DistrictType,		YieldChangeId) 
SELECT
DistrictType,		'GOLDEN_NATIONAL_COMMERCIAL_HUB_GOLD'
FROM Districts WHERE DistrictType = 'MIK_DISTRICT_KARAVANSARAY';

INSERT OR REPLACE INTO District_Adjacencies 
(DistrictType,		YieldChangeId) 
SELECT
DistrictType,		'GOLDEN_NATIONAL_COMMERCIAL_HUB_GOLD_PLUS'
FROM Districts WHERE DistrictType = 'MIK_DISTRICT_KARAVANSARAY';

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,						ModifierId)
SELECT	
'TRAIT_LEADER_MAJOR_CIV',		'GASC_MIK_DISTRICT_BULLRING_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY' 
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_BULLRING');

INSERT OR REPLACE INTO TraitModifiers 
(TraitType,						ModifierId)
SELECT	
'TRAIT_LEADER_MAJOR_CIV',		'GASC_MIK_DISTRICT_TUNTIAN_NATIONAL_ENCAMPMENT_HOUSING' 
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_TUNTIAN');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,															ModifierType,											SubjectRequirementSetId)
SELECT	
'GASC_MIK_DISTRICT_BULLRING_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY',	'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT', 'REQSET_GASC_MIK_DISTRICT_BULLRING_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX' 
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_BULLRING');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,												ModifierType, SubjectRequirementSetId)
SELECT	
'GASC_MIK_DISTRICT_TUNTIAN_NATIONAL_ENCAMPMENT_HOUSING',	'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING', 'REQSET_GASC_MIK_DISTRICT_TUNTIAN_ADJACENT_TO_NATIONAL_ENCAMPMENT' 
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_TUNTIAN');


INSERT OR REPLACE INTO ModifierArguments 
(ModifierId, Name, Value)
SELECT	
'GASC_MIK_DISTRICT_BULLRING_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY', 'Amount', 2 
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_BULLRING');

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId, Name, Value)
SELECT	
'GASC_MIK_DISTRICT_TUNTIAN_NATIONAL_ENCAMPMENT_HOUSING', 'Amount', 3 
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_TUNTIAN');


INSERT OR REPLACE INTO RequirementSets 
(RequirementSetId, RequirementSetType)
SELECT	
'REQSET_GASC_MIK_DISTRICT_BULLRING_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX', 'REQUIREMENTSET_TEST_ALL' 
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_BULLRING');

INSERT OR REPLACE INTO RequirementSets 
(RequirementSetId, RequirementSetType)
SELECT	
'REQSET_GASC_MIK_DISTRICT_TUNTIAN_ADJACENT_TO_NATIONAL_ENCAMPMENT', 'REQUIREMENTSET_TEST_ALL' 
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_TUNTIAN');

INSERT OR REPLACE INTO RequirementSetRequirements 
(RequirementSetId, RequirementId)
SELECT	
'REQSET_GASC_MIK_DISTRICT_BULLRING_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX', 'REQ_GASC_PLOT_HAS_MIK_DISTRICT_BULLRING'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_BULLRING');

INSERT OR REPLACE INTO RequirementSetRequirements 
(RequirementSetId, RequirementId)
SELECT	
'REQSET_GASC_MIK_DISTRICT_BULLRING_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX', 'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_BULLRING');

INSERT OR REPLACE INTO RequirementSetRequirements
(RequirementSetId, RequirementId)
SELECT	
'REQSET_GASC_MIK_DISTRICT_TUNTIAN_ADJACENT_TO_NATIONAL_ENCAMPMENT', 'REQ_GASC_PLOT_HAS_MIK_DISTRICT_TUNTIAN'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_TUNTIAN');

INSERT OR REPLACE INTO RequirementSetRequirements
(RequirementSetId, RequirementId)
SELECT	
'REQSET_GASC_MIK_DISTRICT_TUNTIAN_ADJACENT_TO_NATIONAL_ENCAMPMENT', 'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_NATIONAL_ENCAMPMENT'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_TUNTIAN');

INSERT OR REPLACE INTO Requirements 
(RequirementId,									RequirementType) 
SELECT	 
'REQ_GASC_PLOT_HAS_MIK_DISTRICT_BULLRING',		'REQUIREMENT_DISTRICT_TYPE_MATCHES'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_BULLRING');

INSERT OR REPLACE INTO RequirementArguments
(RequirementId,									Name,				Value) 
SELECT
'REQ_GASC_PLOT_HAS_MIK_DISTRICT_BULLRING',		'DistrictType',	    'MIK_DISTRICT_BULLRING'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_BULLRING');

INSERT OR REPLACE INTO Requirements
(RequirementId,									RequirementType) 
SELECT	 
'REQ_GASC_PLOT_HAS_MIK_DISTRICT_TUNTIAN',		'REQUIREMENT_DISTRICT_TYPE_MATCHES'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_TUNTIAN');

INSERT OR REPLACE INTO RequirementArguments
(RequirementId,									Name,				Value)
SELECT
'REQ_GASC_PLOT_HAS_MIK_DISTRICT_TUNTIAN',		'DistrictType',		'MIK_DISTRICT_TUNTIAN'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_TUNTIAN');