-- MEGA_MIK
-- Author: Flactine
-- DateCreated: 4/24/2024 10:50:53 PM
--------------------------------------------------------------
INSERT INTO District_Adjacencies	
(DistrictType,				YieldChangeId)	
SELECT 
'MIK_DISTRICT_GOLDSMITHY',	'ADJ_GASC_GOLDSMITHY_1'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_GOLDSMITHY');

INSERT INTO District_Adjacencies	
(DistrictType,				YieldChangeId)	
SELECT 
'MIK_DISTRICT_GOLDSMITHY',	'ADJ_GASC_GOLDSMITHY_2'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_GOLDSMITHY');

INSERT INTO District_Adjacencies	
(DistrictType,				YieldChangeId)	
SELECT 
'MIK_DISTRICT_GOLDSMITHY',	'ADJ_GASC_GOLDSMITHY_3'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_GOLDSMITHY');

INSERT INTO District_Adjacencies	
(DistrictType,					YieldChangeId)	
SELECT 
'MIK_DISTRICT_KOOTHAMBALAM',	'ADJ_GASC_KOOTHAMBALAM_1'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_KOOTHAMBALAM');

INSERT INTO District_Adjacencies	
(DistrictType,					YieldChangeId)	
SELECT 
'MIK_DISTRICT_KOOTHAMBALAM',	'ADJ_GASC_KOOTHAMBALAM_2'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_KOOTHAMBALAM');

INSERT INTO District_Adjacencies	
(DistrictType,					YieldChangeId)	
SELECT 
'MIK_DISTRICT_KOOTHAMBALAM',	'ADJ_GASC_KOOTHAMBALAM_3'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_KOOTHAMBALAM');

INSERT INTO District_Adjacencies	
(DistrictType,					YieldChangeId)	
SELECT 
'MIK_DISTRICT_DEBRE',			'ADJ_GASC_DEBRE_1'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_DEBRE');

INSERT INTO District_Adjacencies	
(DistrictType,					YieldChangeId)	
SELECT 
'MIK_DISTRICT_DEBRE',			'ADJ_GASC_DEBRE_2'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_DEBRE');

INSERT INTO District_Adjacencies	
(DistrictType,					YieldChangeId)	
SELECT 
'MIK_DISTRICT_DEBRE',			'ADJ_GASC_DEBRE_3'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_DEBRE');

INSERT INTO District_Adjacencies	
(DistrictType,					YieldChangeId)	
SELECT 
'MIK_DISTRICT_KARAVANSARAY',	'ADJ_GASC_KARAVANSARAY_1'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_KARAVANSARAY');

INSERT INTO District_Adjacencies	
(DistrictType,					YieldChangeId)	
SELECT 
'MIK_DISTRICT_KARAVANSARAY',	'ADJ_GASC_KARAVANSARAY_2'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_KARAVANSARAY');

INSERT INTO District_Adjacencies	
(DistrictType,					YieldChangeId)	
SELECT 
'MIK_DISTRICT_KARAVANSARAY',	'ADJ_GASC_KARAVANSARAY_3'
WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_KARAVANSARAY');
--=====
--Adjacency_YieldChanges
--=====
INSERT OR REPLACE INTO Adjacency_YieldChanges 
(ID,						Description,				YieldType,				YieldChange,	TilesRequired,	AdjacentDistrict,				PrereqCivic) 
VALUES 
('ADJ_GASC_GOLDSMITHY_1',	'LOC_HARBOR_GOLD_STANDARD',	'YIELD_PRODUCTION',		1,          	1,            	'MIK_DISTRICT_GOLDSMITHY',		Null),
('ADJ_GASC_GOLDSMITHY_2',	'LOC_HARBOR_GOLD_STANDARD',	'YIELD_PRODUCTION',		1,          	1,            	'MIK_DISTRICT_GOLDSMITHY',		'CIVIC_CIVIL_SERVICE'),
('ADJ_GASC_GOLDSMITHY_3',	'LOC_HARBOR_GOLD_STANDARD',	'YIELD_PRODUCTION',		1,          	1,            	'MIK_DISTRICT_GOLDSMITHY',		'CIVIC_URBANIZATION'),
('ADJ_GASC_KOOTHAMBALAM_1',	'LOC_HARBOR_GOLD_STANDARD',	'YIELD_CULTURE',		1,          	1,            	'MIK_DISTRICT_KOOTHAMBALAM',	Null),
('ADJ_GASC_KOOTHAMBALAM_2',	'LOC_HARBOR_GOLD_STANDARD',	'YIELD_CULTURE',		1,          	1,            	'MIK_DISTRICT_KOOTHAMBALAM',	'CIVIC_CIVIL_SERVICE'),
('ADJ_GASC_KOOTHAMBALAM_3',	'LOC_HARBOR_GOLD_STANDARD',	'YIELD_CULTURE',		1,          	1,            	'MIK_DISTRICT_KOOTHAMBALAM',	'CIVIC_URBANIZATION'),
('ADJ_GASC_DEBRE_1',		'LOC_HARBOR_GOLD_STANDARD',	'YIELD_FAITH',			1,          	1,            	'MIK_DISTRICT_DEBRE',			Null),
('ADJ_GASC_DEBRE_2',		'LOC_HARBOR_GOLD_STANDARD',	'YIELD_FAITH',			1,          	1,            	'MIK_DISTRICT_DEBRE',			'CIVIC_CIVIL_SERVICE'),
('ADJ_GASC_DEBRE_3',		'LOC_HARBOR_GOLD_STANDARD',	'YIELD_FAITH',			1,          	1,            	'MIK_DISTRICT_DEBRE',			'CIVIC_URBANIZATION'),
('ADJ_GASC_KARAVANSARAY_1',	'LOC_HARBOR_GOLD_STANDARD',	'YIELD_GOLD',			1,          	1,            	'MIK_DISTRICT_KARAVANSARAY',	Null),
('ADJ_GASC_KARAVANSARAY_2',	'LOC_HARBOR_GOLD_STANDARD',	'YIELD_GOLD',			1,          	1,            	'MIK_DISTRICT_KARAVANSARAY',	'CIVIC_CIVIL_SERVICE'),
('ADJ_GASC_KARAVANSARAY_3',	'LOC_HARBOR_GOLD_STANDARD',	'YIELD_GOLD',			1,          	1,            	'MIK_DISTRICT_KARAVANSARAY',	'CIVIC_URBANIZATION');
--=====
--Check
--=====
DELETE FROM Adjacency_YieldChanges
WHERE AdjacentDistrict = 'MIK_DISTRICT_GOLDSMITHY'
AND NOT EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_GOLDSMITHY');

DELETE FROM Adjacency_YieldChanges
WHERE AdjacentDistrict = 'MIK_DISTRICT_KOOTHAMBALAM'
AND NOT EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_KOOTHAMBALAM');

DELETE FROM Adjacency_YieldChanges
WHERE AdjacentDistrict = 'MIK_DISTRICT_DEBRE'
AND NOT EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_DEBRE');

DELETE FROM Adjacency_YieldChanges
WHERE AdjacentDistrict = 'MIK_DISTRICT_KARAVANSARAY'
AND NOT EXISTS (SELECT * FROM Districts WHERE DistrictType = 'MIK_DISTRICT_KARAVANSARAY');



