-- GASC_Config
-- Author: Flactine
-- DateCreated: 10/14/2023 12:14:05 PM
--------------------------------------------------------------
--=====
--PlayerItems
--=====
INSERT INTO PlayerItems	
(Domain,						CivilizationType,				LeaderType,					Type,			Icon,									Name,						Description,										SortIndex)
VALUES
--VOCALOID
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_VOCALOID',	'LEADER_FLAC_MEIKO',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_VOCALOID',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_VOCALOID',	'LEADER_FLAC_MIKU',			'GASC_RF',	'ICON_CIVILIZATION_FLAC_VOCALOID',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_VOCALOID',	'LEADER_FLAC_YUKARI',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_VOCALOID',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_VOCALOID',	'LEADER_FLAC_NEMU',			'GASC_RF',	'ICON_CIVILIZATION_FLAC_VOCALOID',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
--GTA
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_LEONE',		'LEADER_FLAC_TONI',			'GASC_RF',	'ICON_CIVILIZATION_FLAC_LEONE',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ATOMIC_INFORMATION_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_VERCETTI',	'LEADER_FLAC_TOMMY',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_VERCETTI',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ATOMIC_INFORMATION_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_GROVE',		'LEADER_FLAC_CARL',			'GASC_RF',	'ICON_CIVILIZATION_FLAC_GROVE',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ATOMIC_INFORMATION_DESCRIPTION',		200),
--GUP
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_GUP',		'LEADER_FLAC_MIHO',			'GASC_RF',	'ICON_CIVILIZATION_FLAC_GUP',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MODERN_INFORMATION_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_GUP',		'LEADER_FLAC_KADOTANI',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_GUP',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MODERN_INFORMATION_DESCRIPTION',		200),
--ACADEMY
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_ACADEMY',	'LEADER_FLAC_MIKOTO',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_ACADEMY',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_ACADEMY',	'LEADER_FLAC_MISAKI',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_ACADEMY',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_ACADEMY',	'LEADER_FLAC_FRENDA',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_ACADEMY',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
--LUNARMAIDEN
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_LUNARMAIDEN','LEADER_FLAC_ASAHI',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_LUNARMAIDEN',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ATOMIC_INFORMATION_DESCRIPTION',		200),
--KANCOLLE
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_KANCOLLE',	'LEADER_FLAC_SHIMAKAZE',	'GASC_RF',	'ICON_CIVILIZATION_FLAC_KANCOLLE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MODERN_ATOMIC_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_KANCOLLE',	'LEADER_FLAC_YAMATO',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_KANCOLLE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MODERN_ATOMIC_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_KANCOLLE',	'LEADER_FLAC_TAIHOU',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_KANCOLLE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MODERN_ATOMIC_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_KANCOLLE',	'LEADER_FLAC_NAKA',			'GASC_RF',	'ICON_CIVILIZATION_FLAC_KANCOLLE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MODERN_ATOMIC_DESCRIPTION',	200),
--POWDERTOY
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_POWDERTOY',	'LEADER_FLAC_STICKMAN',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_POWDERTOY',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ATOMIC_ANCIENT_DESCRIPTION',	200),
--AICHANNEL
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_AICHANNEL',	'LEADER_FLAC_KIZUNA_AI',	'GASC_RF',	'ICON_CIVILIZATION_FLAC_AICHANNEL',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
--SMB
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_SMB',		'LEADER_FLAC_MARIO',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_SMB',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_RENAISSANCE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_SMB',		'LEADER_FLAC_LUIGI',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_SMB',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_RENAISSANCE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_SMB',		'LEADER_FLAC_TOAD',			'GASC_RF',	'ICON_CIVILIZATION_FLAC_SMB',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_RENAISSANCE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_SMB',		'LEADER_FLAC_TOADETTE',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_SMB',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_RENAISSANCE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_SMB',		'LEADER_FLAC_PEACH',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_SMB',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_RENAISSANCE_DESCRIPTION',	200),
--KCORP
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_KCORP',		'LEADER_FLAC_MRK',			'GASC_RF',	'ICON_CIVILIZATION_FLAC_KCORP',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_ATOMIC_INFORMATION_DESCRIPTION',		200),
--SPICEWOLF
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_SPICEWOLF',	'LEADER_FLAC_HOLO',			'GASC_RF',	'ICON_CIVILIZATION_FLAC_SPICEWOLF',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_RENAISSANCE_DESCRIPTION',	200),
--MINECRAFT
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_MINECRAFT',	'LEADER_FLAC_STEVE',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_MINECRAFT',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_INDUSTRIAL_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_MINECRAFT',	'LEADER_FLAC_ALEX',			'GASC_RF',	'ICON_CIVILIZATION_FLAC_MINECRAFT',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_INDUSTRIAL_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_MINECRAFT',	'LEADER_FLAC_JESSEM',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_MINECRAFT',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_INDUSTRIAL_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_MINECRAFT',	'LEADER_FLAC_JESSEF',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_MINECRAFT',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_INDUSTRIAL_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_MINECRAFT',	'LEADER_FLAC_PAMA',			'GASC_RF',	'ICON_CIVILIZATION_FLAC_MINECRAFT',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_MEDIEVAL_INDUSTRIAL_DESCRIPTION',		200),
--LIZPIRATE
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_LIZPIRATE',	'LEADER_FLAC_LIZZIE',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_LIZPIRATE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_RENAISSANCE_MODERN_DESCRIPTION',		200),
--SHIKI
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_SHIKI',		'LEADER_FLAC_HINAKO',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_SHIKI',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_SHIKI',		'LEADER_FLAC_KUINA',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_SHIKI',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_SHIKI',		'LEADER_FLAC_MAYUKI',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_SHIKI',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_SHIKI',		'LEADER_FLAC_CHIAKI',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_SHIKI',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
--IDOLMASTER
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_IDOLMASTER',	'LEADER_FLAC_HARUKA',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_IDOLMASTER',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_IDOLMASTER',	'LEADER_FLAC_CHIHAYA',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_IDOLMASTER',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_IDOLMASTER',	'LEADER_FLAC_YAYOI',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_IDOLMASTER',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_IDOLMASTER',	'LEADER_FLAC_RITSUKO',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_IDOLMASTER',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_IDOLMASTER',	'LEADER_FLAC_AZUSA',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_IDOLMASTER',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_IDOLMASTER',	'LEADER_FLAC_IORI',			'GASC_RF',	'ICON_CIVILIZATION_FLAC_IDOLMASTER',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_IDOLMASTER',	'LEADER_FLAC_MAKOTO',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_IDOLMASTER',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_IDOLMASTER',	'LEADER_FLAC_MIKI',			'GASC_RF',	'ICON_CIVILIZATION_FLAC_IDOLMASTER',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_IDOLMASTER',	'LEADER_FLAC_HIBIKI',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_IDOLMASTER',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_IDOLMASTER',	'LEADER_FLAC_YUKIHO',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_IDOLMASTER',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_IDOLMASTER',	'LEADER_FLAC_TAKANE',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_IDOLMASTER',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_IDOLMASTER',	'LEADER_FLAC_MAMI_AMI',		'GASC_RF',	'ICON_CIVILIZATION_FLAC_IDOLMASTER',	'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',	200),
--LOVELIVE
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_LOVELIVE',	'LEADER_FLAC_HONOKA',	'GASC_RF',		'ICON_CIVILIZATION_FLAC_LOVELIVE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_LOVELIVE',	'LEADER_FLAC_ELI',		'GASC_RF',		'ICON_CIVILIZATION_FLAC_LOVELIVE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_LOVELIVE',	'LEADER_FLAC_KOTORI',	'GASC_RF',		'ICON_CIVILIZATION_FLAC_LOVELIVE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_LOVELIVE',	'LEADER_FLAC_UMI',		'GASC_RF',		'ICON_CIVILIZATION_FLAC_LOVELIVE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_LOVELIVE',	'LEADER_FLAC_RIN',		'GASC_RF',		'ICON_CIVILIZATION_FLAC_LOVELIVE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_LOVELIVE',	'LEADER_FLAC_MAKI',		'GASC_RF',		'ICON_CIVILIZATION_FLAC_LOVELIVE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_LOVELIVE',	'LEADER_FLAC_NOZOMI',	'GASC_RF',		'ICON_CIVILIZATION_FLAC_LOVELIVE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_LOVELIVE',	'LEADER_FLAC_HANAYO',	'GASC_RF',		'ICON_CIVILIZATION_FLAC_LOVELIVE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_LOVELIVE',	'LEADER_FLAC_NICO',		'GASC_RF',		'ICON_CIVILIZATION_FLAC_LOVELIVE',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200),
--LUSTROUS
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_LUSTROUS',	'LEADER_FLAC_PHOS',		'GASC_RF',		'ICON_CIVILIZATION_FLAC_LUSTROUS',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_CLASSICAL_INFORMATION_DESCRIPTION',	200),
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_LUSTROUS',	'LEADER_FLAC_BORT',		'GASC_RF',		'ICON_CIVILIZATION_FLAC_LUSTROUS',		'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_CLASSICAL_INFORMATION_DESCRIPTION',	200),
--HTT
('Players:Expansion2_Players',	'CIVILIZATION_FLAC_HTT',		'LEADER_FLAC_YUI',		'GASC_RF',		'ICON_CIVILIZATION_FLAC_HTT',			'LOC_GOLDEN_TRAIT_NAME',	'LOC_TRAIT_GASCRF_INFORMATION_FUTURE_DESCRIPTION',		200);
