----By custom traits
--River
INSERT OR REPLACE INTO StartBiasRivers 
(CivilizationType,           Tier) VALUES	
('CIVILIZATION_CHINA',	     1),
('CIVILIZATION_KOREA',	     2),
('CIVILIZATION_INDIA',	     1),
('CIVILIZATION_SUMERIA',	 1),
('CIVILIZATION_AMERICA',	 2),
('CIVILIZATION_EGYPT',	     1);
INSERT OR REPLACE INTO StartBiasRivers (CivilizationType, Tier)
SELECT	'CIVILIZATION_BABYLON_STK', 1 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_BABYLON_STK');
INSERT OR REPLACE INTO StartBiasRivers (CivilizationType, Tier)
SELECT	'CIVILIZATION_NUBIA',       1 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_NUBIA');

--Jungle
INSERT OR REPLACE INTO StartBiasFeatures 
(CivilizationType,				FeatureType,        Tier) VALUES	
('CIVILIZATION_MAORI',			'FEATURE_JUNGLE',   2),
('CIVILIZATION_KONGO',			'FEATURE_JUNGLE',   1),
('CIVILIZATION_BRAZIL',			'FEATURE_JUNGLE',   1);
INSERT OR REPLACE INTO StartBiasFeatures (CivilizationType, FeatureType, Tier)
SELECT	'CIVILIZATION_KHMER',         'FEATURE_JUNGLE', 2 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_KHMER');
INSERT OR REPLACE INTO StartBiasFeatures (CivilizationType, FeatureType, Tier)
SELECT	'CIVILIZATION_GRAN_COLOMBIA', 'FEATURE_JUNGLE', 2 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_GRAN_COLOMBIA');
INSERT OR REPLACE INTO StartBiasFeatures (CivilizationType, FeatureType, Tier)
SELECT	'CIVILIZATION_VIETNAM',       'FEATURE_JUNGLE', 1 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_VIETNAM');

--Forest
INSERT OR REPLACE INTO StartBiasFeatures 
(CivilizationType,				FeatureType,        Tier) VALUES	
('CIVILIZATION_NORWAY',			'FEATURE_FOREST',   1),
('CIVILIZATION_SWEDEN',			'FEATURE_FOREST',   2),
('CIVILIZATION_RUSSIA',			'FEATURE_FOREST',   2),
('CIVILIZATION_CREE',			'FEATURE_FOREST',   1),
('CIVILIZATION_CANADA',			'FEATURE_FOREST',   1);

--Horses
INSERT OR REPLACE INTO StartBiasResources 
(CivilizationType,				ResourceType,         Tier) VALUES	
('CIVILIZATION_SCYTHIA',	    'RESOURCE_HORSES',    1),
('CIVILIZATION_MONGOLIA',	    'RESOURCE_HORSES',    1),
('CIVILIZATION_ARABIA',	        'RESOURCE_HORSES',    2),
('CIVILIZATION_HUNGARY',	    'RESOURCE_HORSES',    2),
('CIVILIZATION_ZULU',	        'RESOURCE_HORSES',    2);
INSERT OR REPLACE INTO StartBiasResources (CivilizationType, ResourceType, Tier)
SELECT	'CIVILIZATION_AUSTRALIA',       'RESOURCE_HORSES', 2 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_AUSTRALIA');
INSERT OR REPLACE INTO StartBiasResources (CivilizationType, ResourceType, Tier)
SELECT	'CIVILIZATION_MACEDON',         'RESOURCE_HORSES', 2 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_MACEDON');

--Coast
INSERT OR REPLACE INTO StartBiasTerrains 
(CivilizationType,				TerrainType,       Tier) VALUES	
('CIVILIZATION_JAPAN',			'TERRAIN_COAST',   1),
('CIVILIZATION_SCOTLAND',	    'TERRAIN_COAST',   1),
('CIVILIZATION_NETHERLANDS',	'TERRAIN_COAST',   1),
('CIVILIZATION_ENGLAND',		'TERRAIN_COAST',   1),
('CIVILIZATION_SPAIN',		    'TERRAIN_COAST',   1),
('CIVILIZATION_PHOENICIA',		'TERRAIN_COAST',   1);
INSERT OR REPLACE INTO StartBiasTerrains (CivilizationType, TerrainType, Tier)
SELECT	'CIVILIZATION_INDONESIA',     'TERRAIN_COAST', 1 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_INDONESIA');

--Hills
INSERT OR REPLACE INTO StartBiasTerrains 
(CivilizationType,				TerrainType,             Tier) VALUES	
('CIVILIZATION_INCA',			'TERRAIN_GRASS_HILLS',   1),
('CIVILIZATION_INCA',	        'TERRAIN_PLAINS_HILLS',  1),
('CIVILIZATION_MAPUCHE',	    'TERRAIN_GRASS_HILLS',   1),
('CIVILIZATION_MAPUCHE',	    'TERRAIN_PLAINS_HILLS',  1),
('CIVILIZATION_GEORGIA',	    'TERRAIN_GRASS_HILLS',   2),
('CIVILIZATION_GEORGIA',	    'TERRAIN_PLAINS_HILLS',  2),
('CIVILIZATION_OTTOMAN',	    'TERRAIN_GRASS_HILLS',   2),
('CIVILIZATION_OTTOMAN',	    'TERRAIN_PLAINS_HILLS',  2);
INSERT OR REPLACE INTO StartBiasTerrains (CivilizationType, TerrainType, Tier)
SELECT	'CIVILIZATION_GAUL',         'TERRAIN_GRASS_HILLS',  1 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_GAUL');
INSERT OR REPLACE INTO StartBiasTerrains (CivilizationType, TerrainType, Tier)
SELECT	'CIVILIZATION_GAUL',         'TERRAIN_PLAINS_HILLS', 1 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_GAUL');
INSERT OR REPLACE INTO StartBiasTerrains (CivilizationType, TerrainType, Tier)
SELECT	'CIVILIZATION_BYZANTIUM',    'TERRAIN_GRASS_HILLS',  2 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_BYZANTIUM');
INSERT OR REPLACE INTO StartBiasTerrains (CivilizationType, TerrainType, Tier)
SELECT	'CIVILIZATION_BYZANTIUM',    'TERRAIN_PLAINS_HILLS', 2 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_BYZANTIUM');
INSERT OR REPLACE INTO StartBiasTerrains (CivilizationType, TerrainType, Tier)
SELECT	'CIVILIZATION_PERSIA',       'TERRAIN_GRASS_HILLS',  2 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_PERSIA');
INSERT OR REPLACE INTO StartBiasTerrains (CivilizationType, TerrainType, Tier)
SELECT	'CIVILIZATION_PERSIA',       'TERRAIN_PLAINS_HILLS', 2 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_PERSIA');

----By others
--Desert
INSERT OR REPLACE INTO StartBiasTerrains 
(CivilizationType,				TerrainType,               Tier) VALUES	
('CIVILIZATION_ARABIA',			'TERRAIN_DESERT_HILLS',    2),
('CIVILIZATION_ARABIA',			'TERRAIN_DESERT',          2),
('CIVILIZATION_EGYPT',			'TERRAIN_DESERT_HILLS',    2),
('CIVILIZATION_EGYPT',			'TERRAIN_DESERT',          2),
('CIVILIZATION_MALI',			'TERRAIN_DESERT_HILLS',    2),
('CIVILIZATION_MALI',			'TERRAIN_DESERT',          2);
INSERT OR REPLACE INTO StartBiasTerrains (CivilizationType, TerrainType, Tier)
SELECT	'CIVILIZATION_NUBIA',       'TERRAIN_DESERT_HILLS',  2 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_NUBIA');
INSERT OR REPLACE INTO StartBiasTerrains (CivilizationType, TerrainType, Tier)
SELECT	'CIVILIZATION_NUBIA',       'TERRAIN_DESERT',        2 WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType='CIVILIZATION_NUBIA');

--Tundra
INSERT OR REPLACE INTO StartBiasTerrains 
(CivilizationType,				TerrainType,               Tier) VALUES	
('CIVILIZATION_RUSSIA',			'TERRAIN_TUNDRA_HILLS',    1),
('CIVILIZATION_RUSSIA',			'TERRAIN_TUNDRA',          1),
('CIVILIZATION_CANADA',			'TERRAIN_TUNDRA_HILLS',    1),
('CIVILIZATION_CANADA',			'TERRAIN_TUNDRA',          1);

----Individual
--CIVILIZATION_ARABIA
INSERT OR REPLACE INTO StartBiasResources (CivilizationType,						ResourceType, Tier) VALUES	
('CIVILIZATION_ARABIA',			'RESOURCE_OIL', 1);


--CIVILIZATION_MONGOLIA
INSERT OR REPLACE INTO StartBiasTerrains (CivilizationType,						TerrainType, Tier) VALUES	
('CIVILIZATION_MONGOLIA',			'TERRAIN_GRASS', 1),
('CIVILIZATION_MONGOLIA',			'TERRAIN_PLAINS', 1);
