--专业区域项目费用随完成次数上涨
UPDATE Projects SET CostProgressionParam1 = 2500 WHERE CostProgressionModel = 'COST_PROGRESSION_GAME_PROGRESS';

--Space projects
--------------------------------------------------------------
-- Types
--------------------------------------------------------------
INSERT OR REPLACE INTO Types
(Type,									Kind) VALUES	
('PROJECT_SATELLITE_ESPIONAGE',		'KIND_PROJECT'),
('PROJECT_SATELLITE_MILITARY',		'KIND_PROJECT'),
('PROJECT_SATELLITE_NAVIGATION',	'KIND_PROJECT'),
-- ('PROJECT_SATELLITE_WEATHER',		'KIND_PROJECT'),
('PROJECT_SATELLITE_BROADCAST',		'KIND_PROJECT'),
('PROJECT_SATELLITE_COMMUNICATION',	'KIND_PROJECT'),
('PROJECT_SATELLITE_SOLAR_POWER',	'KIND_PROJECT');
--------------------------------------------------------------
-- Projects
--------------------------------------------------------------
INSERT OR REPLACE INTO Projects
(ProjectType,						Cost,	CostProgressionModel,				CostProgressionParam1,	PrereqTech,                PrereqDistrict,			VisualBuildingType,			SpaceRace,	MaxPlayerInstances,	PrereqResource,			AdvisorType,		Name,										ShortName,									Description,										PopupText) VALUES	
('PROJECT_SATELLITE_ESPIONAGE',		3000,	'NO_PROGRESSION_MODEL',				0,						'TECH_TELECOMMUNICATIONS', 'DISTRICT_SPACEPORT',	'BUILDING_MEDIUM_ROCKET',	1,			1,					'RESOURCE_ALUMINUM',	'ADVISOR_GENERIC',	'LOC_PROJECT_SATELLITE_ESPIONAGE_NAME',		'LOC_PROJECT_SATELLITE_ESPIONAGE_NAME',		'LOC_PROJECT_SATELLITE_ESPIONAGE_DESCRIPTION',		'LOC_PROJECT_SATELLITE_ESPIONAGE_POPUP'),
('PROJECT_SATELLITE_MILITARY',		3000,	'NO_PROGRESSION_MODEL',				0,						'TECH_SATELLITES',         'DISTRICT_SPACEPORT',	'BUILDING_MEDIUM_ROCKET',	1,			1,					'RESOURCE_ALUMINUM',	'ADVISOR_CONQUEST',	'LOC_PROJECT_SATELLITE_MILITARY_NAME',		'LOC_PROJECT_SATELLITE_MILITARY_NAME',		'LOC_PROJECT_SATELLITE_MILITARY_DESCRIPTION',		'LOC_PROJECT_SATELLITE_MILITARY_POPUP'),
('PROJECT_SATELLITE_NAVIGATION',	3000,	'NO_PROGRESSION_MODEL',				0,						'TECH_TELECOMMUNICATIONS', 'DISTRICT_SPACEPORT',	'BUILDING_MEDIUM_ROCKET',	1,			1,					'RESOURCE_ALUMINUM',	'ADVISOR_GENERIC',	'LOC_PROJECT_SATELLITE_NAVIGATION_NAME',	'LOC_PROJECT_SATELLITE_NAVIGATION_NAME',	'LOC_PROJECT_SATELLITE_NAVIGATION_DESCRIPTION',		'LOC_PROJECT_SATELLITE_NAVIGATION_POPUP'),
('PROJECT_SATELLITE_BROADCAST',		3000,	'NO_PROGRESSION_MODEL',	            0,					    'TECH_TELECOMMUNICATIONS', 'DISTRICT_SPACEPORT',	'BUILDING_MEDIUM_ROCKET',	1,			1,				    'RESOURCE_ALUMINUM',	'ADVISOR_CULTURE',	'LOC_PROJECT_SATELLITE_BROADCAST_NAME',		'LOC_PROJECT_SATELLITE_BROADCAST_NAME',		'LOC_PROJECT_SATELLITE_BROADCAST_DESCRIPTION',		'LOC_PROJECT_SATELLITE_BROADCAST_POPUP'),
-- ('PROJECT_SATELLITE_WEATHER',		2000,	'NO_PROGRESSION_MODEL',				0,						'TECH_SATELLITES',         'DISTRICT_SPACEPORT',	'BUILDING_MEDIUM_ROCKET',	1,			1,					'RESOURCE_ALUMINUM',	'ADVISOR_GENERIC',	'LOC_PROJECT_SATELLITE_WEATHER_NAME',		'LOC_PROJECT_SATELLITE_WEATHER_NAME',		'LOC_PROJECT_SATELLITE_WEATHER_DESCRIPTION',		'LOC_PROJECT_SATELLITE_WEATHER_POPUP'),
('PROJECT_SATELLITE_COMMUNICATION',	3000,	'NO_PROGRESSION_MODEL',				0,						'TECH_TELECOMMUNICATIONS', 'DISTRICT_SPACEPORT',	'BUILDING_SMALL_ROCKET',	1,			1,				'RESOURCE_ALUMINUM',	'ADVISOR_GENERIC',	'LOC_PROJECT_SATELLITE_COMMUNICATION_NAME',	'LOC_PROJECT_SATELLITE_COMMUNICATION_NAME',	'LOC_PROJECT_SATELLITE_COMMUNICATION_DESCRIPTION',	'LOC_PROJECT_SATELLITE_COMMUNICATION_POPUP'),
('PROJECT_SATELLITE_SOLAR_POWER',	3000,	'NO_PROGRESSION_MODEL',				0,						'TECH_SATELLITES',         'DISTRICT_SPACEPORT',	'BUILDING_SMALL_ROCKET',	1,			1,				'RESOURCE_ALUMINUM',	'ADVISOR_GENERIC',	'LOC_PROJECT_SATELLITE_SOLAR_POWER_NAME',	'LOC_PROJECT_SATELLITE_SOLAR_POWER_NAME',	'LOC_PROJECT_SATELLITE_SOLAR_POWER_DESCRIPTION',	'LOC_PROJECT_SATELLITE_SOLAR_POWER_POPUP');
--------------------------------------------------------------
-- Projects_XP2
--------------------------------------------------------------

--------------------------------------------------------------
-- ProjectPrereqs
--------------------------------------------------------------
INSERT OR REPLACE INTO ProjectPrereqs
(ProjectType,							PrereqProjectType,					MinimumPlayerInstances) VALUES	
('PROJECT_SATELLITE_ESPIONAGE',		'PROJECT_LAUNCH_EARTH_SATELLITE',	1),
('PROJECT_SATELLITE_MILITARY',		'PROJECT_LAUNCH_EARTH_SATELLITE',	1),
('PROJECT_SATELLITE_NAVIGATION',	'PROJECT_LAUNCH_EARTH_SATELLITE',	1),
-- ('PROJECT_SATELLITE_WEATHER',		'PROJECT_LAUNCH_EARTH_SATELLITE',	1),
('PROJECT_SATELLITE_BROADCAST',		'PROJECT_LAUNCH_EARTH_SATELLITE',	1),
('PROJECT_SATELLITE_COMMUNICATION',	'PROJECT_LAUNCH_EARTH_SATELLITE',	1),
('PROJECT_SATELLITE_SOLAR_POWER',	'PROJECT_LAUNCH_EARTH_SATELLITE',	1);
--------------------------------------------------------------
-- Project_ResourceCosts
--------------------------------------------------------------
INSERT OR REPLACE INTO Project_ResourceCosts
(ProjectType,							ResourceType,			StartProductionCost) VALUES	
('PROJECT_SATELLITE_ESPIONAGE',		'RESOURCE_ALUMINUM',	30),
('PROJECT_SATELLITE_MILITARY',		'RESOURCE_ALUMINUM',	30),
('PROJECT_SATELLITE_NAVIGATION',	'RESOURCE_ALUMINUM',	30),
('PROJECT_SATELLITE_BROADCAST',		'RESOURCE_ALUMINUM',	30),
-- ('PROJECT_SATELLITE_WEATHER',		'RESOURCE_ALUMINUM',	30),
('PROJECT_SATELLITE_COMMUNICATION',	'RESOURCE_ALUMINUM',	30),
('PROJECT_SATELLITE_SOLAR_POWER',	'RESOURCE_ALUMINUM',	30);
--------------------------------------------------------------
-- ProjectCompletionModifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO ProjectCompletionModifiers
(ProjectType,							ModifierId) VALUES	
('PROJECT_SATELLITE_ESPIONAGE',		'PROJECT_COMPLETION_SAT_ESPIONAGE_VISIBILITY'),
('PROJECT_SATELLITE_ESPIONAGE',		'PROJECT_COMPLETION_SAT_ESPIONAGE_SPY_BONUS'),
('PROJECT_SATELLITE_MILITARY',		'PROJECT_COMPLETION_SAT_MILITARY_COMBAT_STRENGTH'),
('PROJECT_SATELLITE_NAVIGATION',	'PROJECT_COMPLETION_SAT_NAVIGATION_SEA_MOVEMENT'),
('PROJECT_SATELLITE_NAVIGATION',	'PROJECT_COMPLETION_SAT_NAVIGATION_EMBARKED_MOVEMENT'),
('PROJECT_SATELLITE_NAVIGATION',	'PROJECT_COMPLETION_SAT_NAVIGATION_EMBARKED_TEXT_ONLY'),
('PROJECT_SATELLITE_NAVIGATION',	'PROJECT_COMPLETION_SAT_NAVIGATION_DOMESTIC_TRADE'),
('PROJECT_SATELLITE_NAVIGATION',	'PROJECT_COMPLETION_SAT_NAVIGATION_INTERNATIONAL_TRADE'),
-- ('PROJECT_SATELLITE_WEATHER',		'PROJECT_COMPLETION_SAT_WEATHER_PREVENET_STRUCTURAL_DAMAGE'),
('PROJECT_SATELLITE_BROADCAST',		'PROJECT_COMPLETION_SAT_BROADCAST_TOURISM'),
('PROJECT_SATELLITE_COMMUNICATION',	'PROJECT_COMPLETION_SAT_COMMUNICATION_ENVOYS'),
('PROJECT_SATELLITE_SOLAR_POWER',	'PROJECT_COMPLETION_SAT_SOLAR_POWER');
--------------------------------------------------------------
-- Modifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO Modifiers
(ModifierId,												 ModifierType,													SubjectRequirementSetId) VALUES	
('PROJECT_COMPLETION_SAT_ESPIONAGE_VISIBILITY',				 'MODIFIER_PLAYER_ADD_DIPLO_VISIBILITY',						NULL),
('PROJECT_COMPLETION_SAT_ESPIONAGE_SPY_BONUS',				 'MODIFIER_PLAYER_ADJUST_SPY_BONUS',							NULL),
('PROJECT_COMPLETION_SAT_MILITARY_COMBAT_STRENGTH',			 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',							NULL),
('PROJECT_COMPLETION_SAT_NAVIGATION_SEA_MOVEMENT',			 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',							NULL),
('PROJECT_COMPLETION_SAT_NAVIGATION_EMBARKED_MOVEMENT',		 'MODIFIER_PLAYER_ADJUST_EMBARKED_MOVEMENT',					NULL),
('PROJECT_COMPLETION_SAT_NAVIGATION_EMBARKED_TEXT_ONLY',	 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',							NULL),
('PROJECT_COMPLETION_SAT_NAVIGATION_DOMESTIC_TRADE',		 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',		NULL),
('PROJECT_COMPLETION_SAT_NAVIGATION_INTERNATIONAL_TRADE',	 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	NULL),
-- ('PROJECT_COMPLETION_SAT_WEATHER_PREVENET_STRUCTURAL_DAMAGE','GOLDEN_MODIFIER_PLAYER_CITIES_PREVENET_STRUCTURAL_DAMAGE',	NULL),
('PROJECT_COMPLETION_SAT_BROADCAST_TOURISM',				 'MODIFIER_PLAYER_ADJUST_TOURISM',								NULL),
('PROJECT_COMPLETION_SAT_COMMUNICATION_ENVOYS',				 'MODIFIER_PLAYER_GRANT_INFLUENCE_TOKEN',						NULL),
('PROJECT_COMPLETION_SAT_SOLAR_POWER',						 'MODIFIER_PLAYER_CITIES_ADJUST_FREE_POWER',					NULL);

-- UPDATE Modifiers SET RunOnce=1,	Permanent=1 WHERE ModifierId='PROJECT_COMPLETION_SAT_WEATHER_PREVENET_STRUCTURAL_DAMAGE';
UPDATE Modifiers SET RunOnce=1,	Permanent=1 WHERE ModifierId='PROJECT_COMPLETION_SAT_COMMUNICATION_ENVOYS';
--------------------------------------------------------------
-- ModifierArguments
--------------------------------------------------------------
INSERT OR REPLACE INTO ModifierArguments
(ModifierId,													Name,				Value) VALUES	
('PROJECT_COMPLETION_SAT_ESPIONAGE_VISIBILITY',				'Amount',			1),
('PROJECT_COMPLETION_SAT_ESPIONAGE_VISIBILITY',				'Source',			'SOURCE_PROJECT_SATELLITE'),
('PROJECT_COMPLETION_SAT_ESPIONAGE_VISIBILITY',				'SourceType',		'DIPLO_SOURCE_ALL_NAMES'),
('PROJECT_COMPLETION_SAT_ESPIONAGE_SPY_BONUS',				'Offense',			1),
('PROJECT_COMPLETION_SAT_ESPIONAGE_SPY_BONUS',				'Amount',			1),
('PROJECT_COMPLETION_SAT_MILITARY_COMBAT_STRENGTH',			'AbilityType',		'ABILITY_SAT_MILITARY_COMBAT_STRENGTH_BUFF'),
('PROJECT_COMPLETION_SAT_NAVIGATION_SEA_MOVEMENT',			'AbilityType',		'ABILITY_SAT_NAVIGATION_SEA_MOVEMENT_BUFF'),
('PROJECT_COMPLETION_SAT_NAVIGATION_EMBARKED_MOVEMENT',		'Amount',			1),
('PROJECT_COMPLETION_SAT_NAVIGATION_EMBARKED_TEXT_ONLY',	'AbilityType',		'ABILITY_SAT_NAVIGATION_EMBARKED_BUFF'),
('PROJECT_COMPLETION_SAT_NAVIGATION_DOMESTIC_TRADE',		'YieldType',		'YIELD_PRODUCTION'),
('PROJECT_COMPLETION_SAT_NAVIGATION_DOMESTIC_TRADE',		'Amount',			2),
('PROJECT_COMPLETION_SAT_NAVIGATION_DOMESTIC_TRADE',		'Intercontinental',	1),
('PROJECT_COMPLETION_SAT_NAVIGATION_INTERNATIONAL_TRADE',	'YieldType',		'YIELD_GOLD'),
('PROJECT_COMPLETION_SAT_NAVIGATION_INTERNATIONAL_TRADE',	'Amount',			4),
('PROJECT_COMPLETION_SAT_NAVIGATION_INTERNATIONAL_TRADE',	'Intercontinental',	1),
-- ('PROJECT_COMPLETION_SAT_WEATHER_PREVENET_STRUCTURAL_DAMAGE','Prevent',			1),
('PROJECT_COMPLETION_SAT_BROADCAST_TOURISM',				'Amount',			25),
('PROJECT_COMPLETION_SAT_COMMUNICATION_ENVOYS',				'Amount',			6),
('PROJECT_COMPLETION_SAT_SOLAR_POWER',						'Amount',			8),
('PROJECT_COMPLETION_SAT_SOLAR_POWER',						'SourceType',		'FREE_POWER_SOURCE_SOLAR');

--------------------------------------------------------------
-- Types
--------------------------------------------------------------
INSERT OR REPLACE INTO Types
(Type,												Kind) VALUES	
('ABILITY_SAT_MILITARY_COMBAT_STRENGTH_BUFF',	'KIND_ABILITY'),
('ABILITY_SAT_NAVIGATION_SEA_MOVEMENT_BUFF',	'KIND_ABILITY'),
('ABILITY_SAT_NAVIGATION_EMBARKED_BUFF',		'KIND_ABILITY');
--------------------------------------------------------------
-- UnitAbilities
--------------------------------------------------------------
INSERT OR REPLACE INTO UnitAbilities
(UnitAbilityType,								Name,													Description,													Inactive) VALUES	
('ABILITY_SAT_MILITARY_COMBAT_STRENGTH_BUFF',	'LOC_ABILITY_SAT_MILITARY_COMBAT_STRENGTH_BUFF_NAME',	'LOC_ABILITY_SAT_MILITARY_COMBAT_STRENGTH_BUFF_DESCRIPTION',	1),
('ABILITY_SAT_NAVIGATION_SEA_MOVEMENT_BUFF',	'LOC_ABILITY_SAT_NAVIGATION_SEA_MOVEMENT_BUFF_NAME',	'LOC_ABILITY_SAT_NAVIGATION_SEA_MOVEMENT_BUFF_DESCRIPTION',		1),
('ABILITY_SAT_NAVIGATION_EMBARKED_BUFF',		'LOC_ABILITY_SAT_NAVIGATION_EMBARKED_BUFF_NAME',		'LOC_ABILITY_SAT_NAVIGATION_EMBARKED_BUFF_DESCRIPTION',			1);
--------------------------------------------------------------
-- TypeTags
--------------------------------------------------------------
INSERT OR REPLACE INTO TypeTags
(Type,												Tag) SELECT	
'ABILITY_SAT_MILITARY_COMBAT_STRENGTH_BUFF',	Tag
FROM	TypeTags WHERE	Type='ABILITY_FASCISM_ATTACK_BUFF';

INSERT OR REPLACE INTO TypeTags
(Type,												Tag) SELECT	
'ABILITY_SAT_NAVIGATION_SEA_MOVEMENT_BUFF',		Tag
FROM	TypeTags WHERE	Type='ABILITY_GREAT_LIGHTHOUSE_MOVEMENT';

INSERT OR REPLACE INTO TypeTags
(Type,												Tag) SELECT	
'ABILITY_SAT_NAVIGATION_EMBARKED_BUFF',			Tag
FROM	TypeTags WHERE	Type='ABILITY_GREAT_LIGHTHOUSE_EMBARKED_MOVEMENT';
--------------------------------------------------------------
-- Modifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO Modifiers
(ModifierId,								ModifierType) VALUES	
('SAT_MILITARY_COMBAT_STRENGTH_BUFF',	'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH'),
('SAT_NAVIGATION_SEA_MOVEMENT_BUFF',	'MODIFIER_PLAYER_UNIT_ADJUST_SEA_MOVEMENT');
--------------------------------------------------------------
-- ModifierArguments
--------------------------------------------------------------
INSERT OR REPLACE INTO ModifierArguments
(ModifierId,								Name,		Value) VALUES	
('SAT_MILITARY_COMBAT_STRENGTH_BUFF',	'Amount',	5),
('SAT_NAVIGATION_SEA_MOVEMENT_BUFF',	'Amount',	1);
--------------------------------------------------------------
-- UnitAbilityModifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO UnitAbilityModifiers
(UnitAbilityType,									ModifierId) VALUES	
('ABILITY_SAT_MILITARY_COMBAT_STRENGTH_BUFF',	'SAT_MILITARY_COMBAT_STRENGTH_BUFF'),
('ABILITY_SAT_NAVIGATION_SEA_MOVEMENT_BUFF',	'SAT_NAVIGATION_SEA_MOVEMENT_BUFF');
--------------------------------------------------------------
-- ModifierStrings
--------------------------------------------------------------
INSERT OR REPLACE INTO ModifierStrings
(ModifierId,								Context,	Text) VALUES	
('SAT_MILITARY_COMBAT_STRENGTH_BUFF',	'Preview',	'LOC_ABILITY_SAT_MILITARY_COMBAT_STRENGTH_BUFF_DESCRIPTION');

--新项目兼容建筑拓展内容
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_HORSES_GOLD',					'BUILDING_MINT'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_MINT');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_HORSES_GOLD',					'BUILDING_POST_STATION'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_POST_STATION');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_IRON_GOLD',					'BUILDING_MINT'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_MINT');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_IRON_GOLD',					'BUILDING_POST_STATION'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_POST_STATION');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_NITER_GOLD',					'BUILDING_COMMERCIAL'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_NITER_GOLD',					'BUILDING_TAX_BUREAU'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_COAL_GOLD',					'BUILDING_COMMERCIAL'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_COAL_GOLD',					'BUILDING_TAX_BUREAU'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_OIL_GOLD',						'BUILDING_URBAN_CONSTRUCTION'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_URBAN_CONSTRUCTION');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_OIL_GOLD',						'BUILDING_MILITARY_CORP'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_MILITARY_CORP');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_ALUMINUM_GOLD',				'BUILDING_URBAN_CONSTRUCTION'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_URBAN_CONSTRUCTION');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_ALUMINUM_GOLD',				'BUILDING_MILITARY_CORP'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_MILITARY_CORP');
DELETE FROM Projects_XP2 WHERE ProjectType='PROJECT_URANIUM_GOLD' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_LUXURY_GOODS');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_URANIUM_GOLD',					'BUILDING_LUXURY_GOODS'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_LUXURY_GOODS');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_URANIUM_GOLD',					'BUILDING_DIGITAL_CURRENCY'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_DIGITAL_CURRENCY');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_URANIUM_GOLD',					'BUILDING_FINANCIAL_TOWER'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_FINANCIAL_TOWER');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_URANIUM_GOLD',					'BUILDING_MINING_GROUP'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_MINING_GROUP');