-----------------------------------------------
-- 区分远程单位与可以远程攻击的单位
-----------------------------------------------
INSERT OR REPLACE INTO Tags 
(Tag,						Vocabulary) 
VALUES
('CLASS_TRUE_RANGED',		'ABILITY_CLASS');
INSERT OR REPLACE INTO TypeTags 
(Type,									Tag) 
VALUES
('UNIT_SLINGER',				        'CLASS_TRUE_RANGED'),
('UNIT_ARCHER',				            'CLASS_TRUE_RANGED'),
('UNIT_CROSSBOWMAN',				    'CLASS_TRUE_RANGED'),
('UNIT_FIELD_CANNON',				    'CLASS_TRUE_RANGED'),
('UNIT_MACHINE_GUN',				    'CLASS_TRUE_RANGED'),
('UNIT_CHINESE_CROUCHING_TIGER',		'CLASS_TRUE_RANGED'),
('UNIT_KOREAN_HWACHA',		            'CLASS_TRUE_RANGED');
INSERT OR REPLACE INTO TypeTags	(Type, Tag)
SELECT	'UNIT_NUBIAN_PITATI', 'CLASS_TRUE_RANGED' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_NUBIAN_PITATI');--DLC
INSERT OR REPLACE INTO TypeTags	(Type, Tag)
SELECT	'UNIT_MAYAN_HULCHE', 'CLASS_TRUE_RANGED' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');--DLC
INSERT OR REPLACE INTO TypeTags	(Type, Tag)
SELECT	'UNIT_VIETNAMESE_VOI_CHIEN', 'CLASS_TRUE_RANGED' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');--DLC

--range damage
INSERT OR REPLACE INTO TypeTags 
(Type,									Tag) 
VALUES
('UNIT_BARBARIAN_HORSE_ARCHER',			'CLASS_RANGED'),
('UNIT_EGYPTIAN_CHARIOT_ARCHER',		'CLASS_RANGED');

INSERT OR REPLACE INTO UnitUpgrades
(Unit,							UpgradeUnit) 
VALUES
('UNIT_BARBARIAN_HORSEMAN',		'UNIT_HORSEMAN');
