--------------------------------------------------------------
-- 贸易食物
--------------------------------------------------------------
INSERT OR REPLACE INTO Types			
(Type,															Kind) VALUES
('POLICY_DOMESTIC_FOOD_LV1',									'KIND_POLICY'),
('POLICY_DOMESTIC_FOOD_LV2',									'KIND_POLICY'),
('POLICY_DOMESTIC_FOOD_LV3',									'KIND_POLICY'),
('POLICY_INTERNATIONAL_FOOD_LV1',								'KIND_POLICY'),
('POLICY_INTERNATIONAL_FOOD_LV2',								'KIND_POLICY'),
('POLICY_INTERNATIONAL_FOOD_LV3',								'KIND_POLICY');

INSERT OR REPLACE INTO Policies			
(PolicyType,						Name,										Description,										PrereqCivic,				GovernmentSlotType) VALUES
('POLICY_DOMESTIC_FOOD_LV1',		'LOC_POLICY_DOMESTIC_FOOD_LV1_NAME',		'LOC_POLICY_DOMESTIC_FOOD_LV1_DESCRIPTION',			'CIVIC_CIVIL_SERVICE',		'SLOT_DIPLOMATIC'),
('POLICY_DOMESTIC_FOOD_LV2',		'LOC_POLICY_DOMESTIC_FOOD_LV2_NAME',		'LOC_POLICY_DOMESTIC_FOOD_LV2_DESCRIPTION',			'CIVIC_NATIONALISM',		'SLOT_DIPLOMATIC'),
('POLICY_DOMESTIC_FOOD_LV3',		'LOC_POLICY_DOMESTIC_FOOD_LV3_NAME',		'LOC_POLICY_DOMESTIC_FOOD_LV3_DESCRIPTION',			'CIVIC_CAPITALISM',			'SLOT_DIPLOMATIC'),
('POLICY_INTERNATIONAL_FOOD_LV1',	'LOC_POLICY_INTERNATIONAL_FOOD_LV1_NAME',	'LOC_POLICY_INTERNATIONAL_FOOD_LV1_DESCRIPTION',	'CIVIC_MEDIEVAL_FAIRES',	'SLOT_DIPLOMATIC'),
('POLICY_INTERNATIONAL_FOOD_LV2',	'LOC_POLICY_INTERNATIONAL_FOOD_LV2_NAME',	'LOC_POLICY_INTERNATIONAL_FOOD_LV2_DESCRIPTION',	'CIVIC_URBANIZATION',		'SLOT_DIPLOMATIC'),
('POLICY_INTERNATIONAL_FOOD_LV3',	'LOC_POLICY_INTERNATIONAL_FOOD_LV3_NAME',	'LOC_POLICY_INTERNATIONAL_FOOD_LV3_DESCRIPTION',	'CIVIC_RAPID_DEPLOYMENT',	'SLOT_DIPLOMATIC');

INSERT OR REPLACE INTO ObsoletePolicies (PolicyType, ObsoletePolicy) VALUES	
('POLICY_DOMESTIC_FOOD_LV1', 		'POLICY_DOMESTIC_FOOD_LV2'), 
('POLICY_DOMESTIC_FOOD_LV2',  		'POLICY_DOMESTIC_FOOD_LV3'),
('POLICY_INTERNATIONAL_FOOD_LV1', 	'POLICY_INTERNATIONAL_FOOD_LV2'), 
('POLICY_INTERNATIONAL_FOOD_LV2',  	'POLICY_INTERNATIONAL_FOOD_LV3');
		
INSERT OR REPLACE INTO PolicyModifiers			
(PolicyType,						ModifierId) VALUES
('POLICY_DOMESTIC_FOOD_LV1',		'GOLDEN_POLICY_DOMESTIC_FOOD_LV1_FOOD'),
('POLICY_DOMESTIC_FOOD_LV1',		'GOLDEN_POLICY_DOMESTIC_FOOD_LV1_GOLD'),
('POLICY_DOMESTIC_FOOD_LV2',		'GOLDEN_POLICY_DOMESTIC_FOOD_LV2_FOOD'),
('POLICY_DOMESTIC_FOOD_LV2',		'GOLDEN_POLICY_DOMESTIC_FOOD_LV2_GOLD'),
('POLICY_DOMESTIC_FOOD_LV3',		'GOLDEN_POLICY_DOMESTIC_FOOD_LV3_FOOD'),
('POLICY_DOMESTIC_FOOD_LV3',		'GOLDEN_POLICY_DOMESTIC_FOOD_LV3_GOLD'),
('POLICY_INTERNATIONAL_FOOD_LV1',	'GOLDEN_POLICY_INTERNATIONAL_FOOD_LV1_FOOD'),
('POLICY_INTERNATIONAL_FOOD_LV1',	'GOLDEN_POLICY_INTERNATIONAL_FOOD_LV1_GOLD'),
('POLICY_INTERNATIONAL_FOOD_LV2',	'GOLDEN_POLICY_INTERNATIONAL_FOOD_LV2_FOOD'),
('POLICY_INTERNATIONAL_FOOD_LV2',	'GOLDEN_POLICY_INTERNATIONAL_FOOD_LV2_GOLD'),
('POLICY_INTERNATIONAL_FOOD_LV3',	'GOLDEN_POLICY_INTERNATIONAL_FOOD_LV3_FOOD'),
('POLICY_INTERNATIONAL_FOOD_LV3',	'GOLDEN_POLICY_INTERNATIONAL_FOOD_LV3_GOLD');


INSERT OR REPLACE INTO Modifiers
(ModifierId,										    ModifierType,													SubjectRequirementSetId) VALUES
('GOLDEN_POLICY_DOMESTIC_FOOD_LV1_FOOD',				'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',		null),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV1_GOLD',				'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',		null),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV2_FOOD',				'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',		null),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV2_GOLD',				'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',		null),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV3_FOOD',				'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',		null),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV3_GOLD',				'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',		null),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV1_FOOD',			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	null),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV1_GOLD',			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	null),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV2_FOOD',			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	null),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV2_GOLD',			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	null),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV3_FOOD',			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	null),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV3_GOLD',			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	null);


INSERT OR REPLACE INTO ModifierArguments
(ModifierId,										Name,					Value) VALUES			
('GOLDEN_POLICY_DOMESTIC_FOOD_LV1_FOOD',			'YieldType',			'YIELD_FOOD'),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV1_FOOD',			'Amount',			    3),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV1_GOLD',			'YieldType',			'YIELD_GOLD'),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV1_GOLD',			'Amount',			    -3),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV2_FOOD',			'YieldType',			'YIELD_FOOD'),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV2_FOOD',			'Amount',			    6),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV2_GOLD',			'YieldType',			'YIELD_GOLD'),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV2_GOLD',			'Amount',			    -6),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV3_FOOD',			'YieldType',			'YIELD_FOOD'),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV3_FOOD',			'Amount',			    9),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV3_GOLD',			'YieldType',			'YIELD_GOLD'),
('GOLDEN_POLICY_DOMESTIC_FOOD_LV3_GOLD',			'Amount',			    -9),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV1_FOOD',		'YieldType',			'YIELD_FOOD'),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV1_FOOD',		'Amount',			    3),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV1_GOLD',		'YieldType',			'YIELD_GOLD'),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV1_GOLD',		'Amount',			    -3),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV2_FOOD',		'YieldType',			'YIELD_FOOD'),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV2_FOOD',		'Amount',			    6),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV2_GOLD',		'YieldType',			'YIELD_GOLD'),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV2_GOLD',		'Amount',			    -6),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV3_FOOD',		'YieldType',			'YIELD_FOOD'),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV3_FOOD',		'Amount',			    9),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV3_GOLD',		'YieldType',			'YIELD_GOLD'),
('GOLDEN_POLICY_INTERNATIONAL_FOOD_LV3_GOLD',		'Amount',			    -9);