-- GoldenAge_BE_Entertainment_Complex
-- Author: Flactine
-- DateCreated: 9/6/2022 10:51:51 AM
--------------------------------------------------------------
INSERT OR REPLACE INTO Types
(Type,						Kind)	
VALUES
('BUILDING_CHESS_ROOM',		'KIND_BUILDING'),
('BUILDING_TEAHOUSE',		'KIND_BUILDING'),
('BUILDING_ARBORETUM',		'KIND_BUILDING');

INSERT OR REPLACE INTO Buildings
(BuildingType,				Name,								Description,								PrereqTech,					PrereqCivic,				Cost,	PrereqDistrict,						PurChaseYield,		Maintenance,	CitizenSlots,	Entertainment,	RegionalRange,	AdvisorType)
VALUES                                                                          
('BUILDING_CHESS_ROOM',		'LOC_BUILDING_CHESS_ROOM_NAME',		'LOC_BUILDING_CHESS_ROOM_DESCRIPTION',		Null,						'CIVIC_GAMES_RECREATION',	80,		'DISTRICT_ENTERTAINMENT_COMPLEX',	'YIELD_GOLD',		2,				1,				1,				3,				'ADVISOR_GENERIC'),
('BUILDING_TEAHOUSE',		'LOC_BUILDING_TEAHOUSE_NAME',		'LOC_BUILDING_TEAHOUSE_DESCRIPTION',		Null,						'CIVIC_GAMES_RECREATION',	80,		'DISTRICT_ENTERTAINMENT_COMPLEX',	'YIELD_GOLD',		2,				1,				1,				3,				'ADVISOR_GENERIC'),
('BUILDING_ARBORETUM',		'LOC_BUILDING_ARBORETUM_NAME',		'LOC_BUILDING_ARBORETUM_DESCRIPTION',		'TECH_SANITATION',			Null,						250,	'DISTRICT_ENTERTAINMENT_COMPLEX',	'YIELD_GOLD',		3,				1,				2,				4,				'ADVISOR_GENERIC');

UPDATE Buildings 
SET Cost = 80
WHERE BuildingType = 'BUILDING_ARENA';

UPDATE Buildings 
SET Cost = 250
WHERE BuildingType = 'BUILDING_ZOO';

UPDATE Buildings 
SET Cost = 600
WHERE BuildingType = 'BUILDING_STADIUM';

DELETE FROM BuildingReplaces WHERE CivUniqueBuildingType = 'BUILDING_THERMAL_BATH';

INSERT OR REPLACE INTO BuildingPrereqs
(Building,					PrereqBuilding)	
VALUES
('BUILDING_ZOO',			'BUILDING_CHESS_ROOM'),
('BUILDING_ZOO',			'BUILDING_TEAHOUSE'),
('BUILDING_ARBORETUM',		'BUILDING_ARENA'),
('BUILDING_ARBORETUM',		'BUILDING_CHESS_ROOM'),
('BUILDING_ARBORETUM',		'BUILDING_TEAHOUSE'),
('BUILDING_THERMAL_BATH',	'BUILDING_CHESS_ROOM'),
('BUILDING_THERMAL_BATH',	'BUILDING_TEAHOUSE'),
('BUILDING_STADIUM',		'BUILDING_ARBORETUM'),
('BUILDING_STADIUM',		'BUILDING_THERMAL_BATH');

INSERT OR REPLACE INTO MutuallyExclusiveBuildings
(Building,					MutuallyExclusiveBuilding)	
VALUES
('BUILDING_ARENA',			'BUILDING_CHESS_ROOM'),
('BUILDING_ARENA',			'BUILDING_TEAHOUSE'),
('BUILDING_CHESS_ROOM',		'BUILDING_ARENA'),
('BUILDING_CHESS_ROOM',		'BUILDING_TEAHOUSE'),
('BUILDING_TEAHOUSE',		'BUILDING_ARENA'),
('BUILDING_TEAHOUSE',		'BUILDING_CHESS_ROOM'),
('BUILDING_ZOO',			'BUILDING_ARBORETUM'),
('BUILDING_ZOO',			'BUILDING_THERMAL_BATH'),
('BUILDING_ARBORETUM',		'BUILDING_ZOO'),
('BUILDING_ARBORETUM',		'BUILDING_THERMAL_BATH'),
('BUILDING_THERMAL_BATH',	'BUILDING_ZOO'),
('BUILDING_THERMAL_BATH',	'BUILDING_ARBORETUM');

INSERT OR REPLACE INTO Buildings_XP2
(BuildingType,			RequiredPower,	EntertainmentBonusWithPower)	
SELECT
'BUILDING_CHESS_ROOM',	RequiredPower,	EntertainmentBonusWithPower
FROM Buildings_XP2 WHERE BuildingType = 'BUILDING_ARENA'
UNION ALL
SELECT
'BUILDING_TEAHOUSE',	RequiredPower,	EntertainmentBonusWithPower
FROM Buildings_XP2 WHERE BuildingType = 'BUILDING_ARENA'
UNION ALL
SELECT
'BUILDING_ARBORETUM',	RequiredPower,	EntertainmentBonusWithPower
FROM Buildings_XP2 WHERE BuildingType = 'BUILDING_ZOO';

INSERT OR REPLACE INTO Building_TourismBombs_XP2
(BuildingType,				TourismBombValue)
SELECT
'BUILDING_CHESS_ROOM',		TourismBombValue
FROM Building_TourismBombs_XP2 WHERE BuildingType = 'BUILDING_ARENA'
UNION ALL
SELECT
'BUILDING_TEAHOUSE',		TourismBombValue
FROM Building_TourismBombs_XP2 WHERE BuildingType = 'BUILDING_ARENA'
UNION ALL
SELECT
'BUILDING_ARBORETUM',		TourismBombValue
FROM Building_TourismBombs_XP2 WHERE BuildingType = 'BUILDING_ZOO';

INSERT OR REPLACE INTO Building_CitizenYieldChanges
(BuildingType,			YieldType,	YieldChange)	
SELECT
'BUILDING_CHESS_ROOM',	YieldType,	YieldChange
FROM Building_CitizenYieldChanges WHERE BuildingType = 'BUILDING_ARENA'
UNION ALL
SELECT
'BUILDING_TEAHOUSE',	YieldType,	YieldChange
FROM Building_CitizenYieldChanges WHERE BuildingType = 'BUILDING_ARENA'
UNION ALL
SELECT
'BUILDING_ARBORETUM',	YieldType,	YieldChange
FROM Building_CitizenYieldChanges WHERE BuildingType = 'BUILDING_ZOO';

INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,				ModifierId)
SELECT
'BUILDING_CHESS_ROOM',		ModifierId
FROM BuildingModifiers WHERE ModifierId = 'GOLDEN_ARENA_TOURISM'
UNION ALL
SELECT
'BUILDING_TEAHOUSE',		ModifierId
FROM BuildingModifiers WHERE ModifierId = 'GOLDEN_ARENA_TOURISM'
UNION ALL
SELECT
'BUILDING_ARBORETUM',		ModifierId
FROM BuildingModifiers WHERE ModifierId = 'GOLDEN_ZOO_TOURISM';

INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,					ModifierId)	
VALUES
('BUILDING_ARENA',				'GOLDEN_ARENA_EXTRA_AMENITY'),
('BUILDING_CHESS_ROOM',			'GOLDEN_CHESS_ROOM_EXTRA_AMENITY'),
('BUILDING_TEAHOUSE',			'GOLDEN_TEAHOUSE_EXTRA_AMENITY'),
('BUILDING_ZOO',				'GOLDEN_ZOO_BUILDING_SCIENCE'),
('BUILDING_ZOO',				'GOLDEN_ZOO_PLOT_SCIENCE'),
('BUILDING_ARBORETUM',			'GOLDEN_ARBORETUM_BUILDING_SCIENCE'),
('BUILDING_ARBORETUM',			'GOLDEN_ARBORETUM_PLOT_SCIENCE');

INSERT OR REPLACE INTO Modifiers 
(ModifierId, 							ModifierType,									SubjectRequirementSetId) 
VALUES 
('GOLDEN_ARENA_EXTRA_AMENITY',			'MODIFIER_SINGLE_CITY_ADJUST_ENTERTAINMENT',	'REQSET_GABE_CITY_IMPROVED_HORSE_OR_HAS_ENCAMPMENT'),
('GOLDEN_CHESS_ROOM_EXTRA_AMENITY',		'MODIFIER_SINGLE_CITY_ADJUST_ENTERTAINMENT',	'GOLDEN_CITY_HAS_TWENTY_POPULATION_REQUIREMENTS'),
('GOLDEN_TEAHOUSE_EXTRA_AMENITY',		'MODIFIER_SINGLE_CITY_ADJUST_ENTERTAINMENT',	'REQSET_GABE_CITY_IMPROVED_DRINKS'),

('GOLDEN_ZOO_BUILDING_SCIENCE',			'MODIFIER_BUILDING_YIELD_CHANGE',				'REQSET_GABE_CITY_HAS_BUILDING_ANIMAL_LAB'),
('GOLDEN_ZOO_PLOT_SCIENCE',				'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',	'REQSET_GABE_PLOT_IS_ANIMAL'),
('GOLDEN_ARBORETUM_BUILDING_SCIENCE',	'MODIFIER_BUILDING_YIELD_CHANGE',				'REQSET_GABE_CITY_HAS_BUILDING_BIOLOGY_LAB'),
('GOLDEN_ARBORETUM_PLOT_SCIENCE',		'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',	'REQSET_GABE_PLOT_IS_PLANT');

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId, 							Name, 			Value) 
VALUES 
('GOLDEN_ARENA_EXTRA_AMENITY',			'Amount',		1), 
('GOLDEN_CHESS_ROOM_EXTRA_AMENITY',		'Amount',		1), 
('GOLDEN_TEAHOUSE_EXTRA_AMENITY',		'Amount',		1), 

('GOLDEN_ZOO_BUILDING_SCIENCE',				'BuildingType',		'BUILDING_ZOO'),
('GOLDEN_ZOO_BUILDING_SCIENCE',				'YieldType',		'YIELD_SCIENCE'),
('GOLDEN_ZOO_BUILDING_SCIENCE',				'Amount',			1),
('GOLDEN_ZOO_PLOT_SCIENCE',					'YieldType',		'YIELD_SCIENCE'),
('GOLDEN_ZOO_PLOT_SCIENCE',					'Amount',			1),

('GOLDEN_ARBORETUM_BUILDING_SCIENCE',		'BuildingType',		'BUILDING_ARBORETUM'),
('GOLDEN_ARBORETUM_BUILDING_SCIENCE',		'YieldType',		'YIELD_SCIENCE'),
('GOLDEN_ARBORETUM_BUILDING_SCIENCE',		'Amount',			1),
('GOLDEN_ARBORETUM_PLOT_SCIENCE',			'YieldType',		'YIELD_SCIENCE'),
('GOLDEN_ARBORETUM_PLOT_SCIENCE',			'Amount',			1);

INSERT OR REPLACE INTO RequirementSets
(RequirementSetId,										RequirementSetType)	
VALUES
('REQSET_GABE_CITY_IMPROVED_HORSE_OR_HAS_ENCAMPMENT',	'REQUIREMENTSET_TEST_ANY'),
('REQSET_GABE_CITY_IMPROVED_DRINKS',					'REQUIREMENTSET_TEST_ANY'),
('REQSET_GABE_CITY_HAS_BUILDING_ANIMAL_LAB',			'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_CITY_HAS_BUILDING_BIOLOGY_LAB',			'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_CITY_HAS_BUILDING_RESEARCH_LAB',			'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_CITY_HAS_BUILDING_CHEMISTRY_LAB',			'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_PLOT_IS_ANIMAL',							'REQUIREMENTSET_TEST_ANY'),
('REQSET_GABE_PLOT_IS_PLANT',							'REQUIREMENTSET_TEST_ANY'),
('REQSET_GABE_PLOT_IS_FISH',							'REQUIREMENTSET_TEST_ANY');

INSERT OR REPLACE INTO RequirementSetRequirements 
(RequirementSetId,										RequirementId) 
VALUES 
('REQSET_GABE_CITY_IMPROVED_HORSE_OR_HAS_ENCAMPMENT',	'GOLDEN_REQUIRES_IMPROVED_HORSE'),  --from GoldenAge_Buildings_Expansion_Commercial.sql
('REQSET_GABE_CITY_IMPROVED_HORSE_OR_HAS_ENCAMPMENT',	'GOLDEN_REQUIRES_CITY_HAS_DISTRICT_ENCAMPMENT'),
('REQSET_GABE_CITY_IMPROVED_DRINKS',					'GOLDEN_REQUIRES_IMPROVED_TEA'),
('REQSET_GABE_CITY_IMPROVED_DRINKS',					'GOLDEN_REQUIRES_IMPROVED_COFFEE'),
('REQSET_GABE_CITY_IMPROVED_DRINKS',					'GOLDEN_REQUIRES_IMPROVED_WINE'),

('REQSET_GABE_PLOT_IS_ANIMAL',							'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_CAMP'),
('REQSET_GABE_PLOT_IS_PLANT',							'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_PLANTATION'),
('REQSET_GABE_PLOT_IS_FISH',							'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_FISHING_BOATS');

INSERT OR REPLACE INTO Requirements
(RequirementId,						RequirementType)
VALUES 
('GOLDEN_REQUIRES_IMPROVED_TEA',	'REQUIREMENT_CITY_HAS_RESOURCE_TYPE_IMPROVED'),
('GOLDEN_REQUIRES_IMPROVED_COFFEE',	'REQUIREMENT_CITY_HAS_RESOURCE_TYPE_IMPROVED'),
('GOLDEN_REQUIRES_IMPROVED_WINE',	'REQUIREMENT_CITY_HAS_RESOURCE_TYPE_IMPROVED');

INSERT OR REPLACE INTO RequirementArguments
(RequirementId, 						Name, 			Value)
VALUES 
('GOLDEN_REQUIRES_IMPROVED_TEA',		'ResourceType', 'RESOURCE_TEA'),
('GOLDEN_REQUIRES_IMPROVED_COFFEE',		'ResourceType', 'RESOURCE_COFFEE'),
('GOLDEN_REQUIRES_IMPROVED_WINE',		'ResourceType', 'RESOURCE_WINE');