--所有专家额外消耗1食物
-- INSERT OR REPLACE INTO District_CitizenYieldChanges (DistrictType, YieldType, YieldChange) SELECT DISTINCT 
-- DistrictType,  'YIELD_FOOD', -1 FROM District_CitizenYieldChanges WHERE YieldType <> 'YIELD_FOOD';

--根据人口数量额外宜居度需求
INSERT OR REPLACE INTO DistrictModifiers
(DistrictType,				ModifierId)
VALUES
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_AMENITIES_DEBUFF_TWENTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_AMENITIES_DEBUFF_THIRTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_AMENITIES_DEBUFF_FOURTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_AMENITIES_DEBUFF_FIFTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_AMENITIES_DEBUFF_SIXTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_AMENITIES_DEBUFF_SEVENTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_AMENITIES_DEBUFF_EIGHTY');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,								        ModifierType,														SubjectRequirementSetId)
VALUES
('GOLDEN_CITY_AMENITIES_DEBUFF_TWENTY',	            'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',	                			'GOLDEN_CITY_HAS_TWENTY_POPULATION_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_TWENTY_MODIFIER',	'GOLDEN_MODIFIER_PLAYER_DISTRICT_ADJUST_EXTRA_ENTERTAINMENT',		'GOLDEN_DISTRICT_IS_DISTRICT_CITY_CENTER_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_THIRTY',	            'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',	                			'GOLDEN_CITY_HAS_THIRTY_POPULATION_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_THIRTY_MODIFIER',	'GOLDEN_MODIFIER_PLAYER_DISTRICT_ADJUST_EXTRA_ENTERTAINMENT',		'GOLDEN_DISTRICT_IS_DISTRICT_CITY_CENTER_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_FOURTY',	            'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',	                			'GOLDEN_CITY_HAS_FOURTY_POPULATION_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_FOURTY_MODIFIER',	'GOLDEN_MODIFIER_PLAYER_DISTRICT_ADJUST_EXTRA_ENTERTAINMENT',		'GOLDEN_DISTRICT_IS_DISTRICT_CITY_CENTER_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_FIFTY',	            'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',	                			'GOLDEN_CITY_HAS_FIFTY_POPULATION_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_FIFTY_MODIFIER',	    'GOLDEN_MODIFIER_PLAYER_DISTRICT_ADJUST_EXTRA_ENTERTAINMENT',		'GOLDEN_DISTRICT_IS_DISTRICT_CITY_CENTER_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_SIXTY',	            'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',	                			'GOLDEN_CITY_HAS_SIXTY_POPULATION_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_SIXTY_MODIFIER',		'GOLDEN_MODIFIER_PLAYER_DISTRICT_ADJUST_EXTRA_ENTERTAINMENT',		'GOLDEN_DISTRICT_IS_DISTRICT_CITY_CENTER_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_SEVENTY',	        'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',	                			'GOLDEN_CITY_HAS_SEVENTY_POPULATION_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_SEVENTY_MODIFIER',	'GOLDEN_MODIFIER_PLAYER_DISTRICT_ADJUST_EXTRA_ENTERTAINMENT',		'GOLDEN_DISTRICT_IS_DISTRICT_CITY_CENTER_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_EIGHTY',	            'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',	                			'GOLDEN_CITY_HAS_EIGHTY_POPULATION_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_EIGHTY_MODIFIER',	'GOLDEN_MODIFIER_PLAYER_DISTRICT_ADJUST_EXTRA_ENTERTAINMENT',		'GOLDEN_DISTRICT_IS_DISTRICT_CITY_CENTER_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,							            Name,		    Value)
VALUES
('GOLDEN_CITY_AMENITIES_DEBUFF_TWENTY',	            'ModifierId',   'GOLDEN_CITY_AMENITIES_DEBUFF_TWENTY_MODIFIER'),
('GOLDEN_CITY_AMENITIES_DEBUFF_TWENTY_MODIFIER',	'Amount',	    -1),
('GOLDEN_CITY_AMENITIES_DEBUFF_THIRTY',	            'ModifierId',   'GOLDEN_CITY_AMENITIES_DEBUFF_THIRTY_MODIFIER'),
('GOLDEN_CITY_AMENITIES_DEBUFF_THIRTY_MODIFIER',	'Amount',	    -1),
('GOLDEN_CITY_AMENITIES_DEBUFF_FOURTY',	            'ModifierId',   'GOLDEN_CITY_AMENITIES_DEBUFF_FOURTY_MODIFIER'),
('GOLDEN_CITY_AMENITIES_DEBUFF_FOURTY_MODIFIER',	'Amount',	    -1),
('GOLDEN_CITY_AMENITIES_DEBUFF_FIFTY',	            'ModifierId',   'GOLDEN_CITY_AMENITIES_DEBUFF_FIFTY_MODIFIER'),
('GOLDEN_CITY_AMENITIES_DEBUFF_FIFTY_MODIFIER',	    'Amount',	    -1),
('GOLDEN_CITY_AMENITIES_DEBUFF_SIXTY',	            'ModifierId',   'GOLDEN_CITY_AMENITIES_DEBUFF_SIXTY_MODIFIER'),
('GOLDEN_CITY_AMENITIES_DEBUFF_SIXTY_MODIFIER',		'Amount',	    -1),
('GOLDEN_CITY_AMENITIES_DEBUFF_SEVENTY',	        'ModifierId',   'GOLDEN_CITY_AMENITIES_DEBUFF_SEVENTY_MODIFIER'),
('GOLDEN_CITY_AMENITIES_DEBUFF_SEVENTY_MODIFIER',	'Amount',	    -1),
('GOLDEN_CITY_AMENITIES_DEBUFF_EIGHTY',	            'ModifierId',   'GOLDEN_CITY_AMENITIES_DEBUFF_EIGHTY_MODIFIER'),
('GOLDEN_CITY_AMENITIES_DEBUFF_EIGHTY_MODIFIER',	'Amount',	    -1);

--根据人口数量消耗额外的电力
INSERT OR REPLACE INTO DistrictModifiers
(DistrictType,				ModifierId)
VALUES	
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_POWER_TWENTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_POWER_THIRTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_POWER_FOURTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_POWER_FIFTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_POWER_SIXTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_POWER_SEVENTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_POWER_EIGHTY');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,								ModifierType,										SubjectRequirementSetId,								OwnerRequirementSetId)
VALUES
('GOLDEN_CITY_POWER_TWENTY',	            'MODIFIER_SINGLE_CITY_ADJUST_REQUIRED_POWER',	    'GOLDEN_CITY_HAS_TWENTY_POPULATION_REQUIREMENTS',		'GOLDEN_GAME_ERA_ATLEAST_ERA_INDUSTRIAL_REQUIREMENTS'),
('GOLDEN_CITY_POWER_THIRTY',	            'MODIFIER_SINGLE_CITY_ADJUST_REQUIRED_POWER',	    'GOLDEN_CITY_HAS_THIRTY_POPULATION_REQUIREMENTS',		'GOLDEN_GAME_ERA_ATLEAST_ERA_INDUSTRIAL_REQUIREMENTS'),
('GOLDEN_CITY_POWER_FOURTY',	            'MODIFIER_SINGLE_CITY_ADJUST_REQUIRED_POWER',	    'GOLDEN_CITY_HAS_FOURTY_POPULATION_REQUIREMENTS',		'GOLDEN_GAME_ERA_ATLEAST_ERA_INDUSTRIAL_REQUIREMENTS'),
('GOLDEN_CITY_POWER_FIFTY',	                'MODIFIER_SINGLE_CITY_ADJUST_REQUIRED_POWER',	    'GOLDEN_CITY_HAS_FIFTY_POPULATION_REQUIREMENTS',		'GOLDEN_GAME_ERA_ATLEAST_ERA_INDUSTRIAL_REQUIREMENTS'),
('GOLDEN_CITY_POWER_SIXTY',	            	'MODIFIER_SINGLE_CITY_ADJUST_REQUIRED_POWER',	    'GOLDEN_CITY_HAS_SIXTY_POPULATION_REQUIREMENTS',		'GOLDEN_GAME_ERA_ATLEAST_ERA_INDUSTRIAL_REQUIREMENTS'),
('GOLDEN_CITY_POWER_SEVENTY',	            'MODIFIER_SINGLE_CITY_ADJUST_REQUIRED_POWER',	    'GOLDEN_CITY_HAS_SEVENTY_POPULATION_REQUIREMENTS',		'GOLDEN_GAME_ERA_ATLEAST_ERA_INDUSTRIAL_REQUIREMENTS'),
('GOLDEN_CITY_POWER_EIGHTY',	            'MODIFIER_SINGLE_CITY_ADJUST_REQUIRED_POWER',	    'GOLDEN_CITY_HAS_EIGHTY_POPULATION_REQUIREMENTS',		'GOLDEN_GAME_ERA_ATLEAST_ERA_INDUSTRIAL_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,						Name,		    Value)
VALUES
('GOLDEN_CITY_POWER_TWENTY',	    'Amount',	    1),
('GOLDEN_CITY_POWER_THIRTY',	    'Amount',	    1),
('GOLDEN_CITY_POWER_FOURTY',	    'Amount',	    1),
('GOLDEN_CITY_POWER_FIFTY',	        'Amount',	    1),
('GOLDEN_CITY_POWER_SIXTY',	    	'Amount',	    1),
('GOLDEN_CITY_POWER_SEVENTY',	    'Amount',	    1),
('GOLDEN_CITY_POWER_EIGHTY',	    'Amount',	    1);

--后期电力不足减宜居度
INSERT OR REPLACE INTO DistrictModifiers
(DistrictType,				ModifierId)
VALUES	
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_MODERN'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_ATOMIC'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_INFORMATION'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_FUTURE');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,								                    ModifierType,											        SubjectRequirementSetId)
VALUES
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_MODERN',	            'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',	                        'GOLDEN_CITY_IS_NOT_POWERED_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_MODERN_MODIFIER',	    'GOLDEN_MODIFIER_PLAYER_DISTRICT_ADJUST_EXTRA_ENTERTAINMENT',	'GOLDEN_GAME_ERA_IS_MODERN_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_ATOMIC',	            'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',	                        'GOLDEN_CITY_IS_NOT_POWERED_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_ATOMIC_MODIFIER',	    'GOLDEN_MODIFIER_PLAYER_DISTRICT_ADJUST_EXTRA_ENTERTAINMENT',	'GOLDEN_GAME_ERA_IS_ATOMIC_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_INFORMATION',	        'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',	                        'GOLDEN_CITY_IS_NOT_POWERED_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_INFORMATION_MODIFIER',	'GOLDEN_MODIFIER_PLAYER_DISTRICT_ADJUST_EXTRA_ENTERTAINMENT',	'GOLDEN_GAME_ERA_IS_INFORMATION_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_FUTURE',	            'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',	                        'GOLDEN_CITY_IS_NOT_POWERED_REQUIREMENTS'),
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_FUTURE_MODIFIER',	    'GOLDEN_MODIFIER_PLAYER_DISTRICT_ADJUST_EXTRA_ENTERTAINMENT',	'GOLDEN_GAME_ERA_IS_FUTURE_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,							                        Name,		    Value)
VALUES
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_MODERN',	            'ModifierId',   'GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_MODERN_MODIFIER'),
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_MODERN_MODIFIER',	    'Amount',	    -1),
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_ATOMIC',	            'ModifierId',   'GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_ATOMIC_MODIFIER'),
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_ATOMIC_MODIFIER',	    'Amount',	    -2),
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_INFORMATION',	        'ModifierId',   'GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_INFORMATION_MODIFIER'),
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_INFORMATION_MODIFIER',	'Amount',	    -3),
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_FUTURE',	            'ModifierId',   'GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_FUTURE_MODIFIER'),
('GOLDEN_CITY_AMENITIES_DEBUFF_NO_POWER_FUTURE_MODIFIER',	    'Amount',	    -4);

INSERT OR REPLACE INTO RequirementSets 				
(RequirementSetId,																RequirementSetType)
VALUES 		
('GOLDEN_GAME_ERA_IS_MODERN_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS' , 		'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_GAME_ERA_IS_ATOMIC_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS' , 		'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_GAME_ERA_IS_INFORMATION_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS' , 	'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_GAME_ERA_IS_FUTURE_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS' , 	    'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements 	
(RequirementSetId,																RequirementId)
VALUES 		
('GOLDEN_GAME_ERA_IS_MODERN_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS' , 		'GOLDEN_REQUIRES_GAME_ERA_IS_ERA_MODERN'),
('GOLDEN_GAME_ERA_IS_MODERN_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS' , 		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_CITY_CENTER'),
('GOLDEN_GAME_ERA_IS_ATOMIC_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS' , 		'GOLDEN_REQUIRES_GAME_ERA_IS_ERA_ATOMIC'),
('GOLDEN_GAME_ERA_IS_ATOMIC_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS' , 		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_CITY_CENTER'),
('GOLDEN_GAME_ERA_IS_INFORMATION_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS' , 	'GOLDEN_REQUIRES_GAME_ERA_IS_ERA_INFORMATION'),
('GOLDEN_GAME_ERA_IS_INFORMATION_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS' , 	'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_CITY_CENTER'),
('GOLDEN_GAME_ERA_IS_FUTURE_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS' , 	    'GOLDEN_REQUIRES_GAME_ERA_IS_ERA_FUTURE'),
('GOLDEN_GAME_ERA_IS_FUTURE_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS' , 	    'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_CITY_CENTER');

--+1 Citizen slot for base district
UPDATE Districts SET CitizenSlots = 1 WHERE DistrictType IN (SELECT DISTINCT DistrictType FROM District_GreatPersonPoints);--No entertainment districts here

UPDATE Districts SET CitizenSlots = 1 WHERE DistrictType = 'DISTRICT_ENTERTAINMENT_COMPLEX';
UPDATE Districts SET CitizenSlots = 1 WHERE DistrictType = 'DISTRICT_WATER_ENTERTAINMENT_COMPLEX';
UPDATE Districts SET CitizenSlots = 1 WHERE DistrictType = 'DISTRICT_STREET_CARNIVAL';
UPDATE Districts SET CitizenSlots = 1 WHERE DistrictType = 'DISTRICT_WATER_STREET_CARNIVAL';
UPDATE Districts SET CitizenSlots = 1 WHERE DistrictType = 'DISTRICT_HIPPODROME' AND EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_BYZANTINE_DROMON');

--City center plot yields increase with game era
UPDATE GlobalParameters SET Value = 2 WHERE Name = 'YIELD_FOOD_CITY_TERRAIN_REPLACE';
UPDATE GlobalParameters SET Value = 2 WHERE Name = 'YIELD_PRODUCTION_CITY_TERRAIN_REPLACE';

INSERT OR REPLACE INTO DistrictModifiers
       (DistrictType ,           ModifierId)
SELECT 'DISTRICT_CITY_CENTER' ,  'GOLDEN_CITY_CENTER_PLOT_FOOD_' ||EraType FROM Eras WHERE EraType <> 'ERA_ANCIENT';
INSERT OR REPLACE INTO DistrictModifiers
       (DistrictType ,           ModifierId)
SELECT 'DISTRICT_CITY_CENTER' ,  'GOLDEN_CITY_CENTER_PLOT_PRODUCTION_' ||EraType FROM Eras WHERE EraType <> 'ERA_ANCIENT';

INSERT OR REPLACE INTO Modifiers
       (ModifierId ,                                     ModifierType,                                    SubjectRequirementSetId,                               OwnerRequirementSetId)
SELECT 'GOLDEN_CITY_CENTER_PLOT_FOOD_' ||EraType,        'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',   'GOLDEN_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS',   'GOLDEN_GAME_ERA_ATLEAST_' ||EraType|| '_REQUIREMENTS' FROM Eras WHERE EraType <> 'ERA_ANCIENT';
INSERT OR REPLACE INTO Modifiers
       (ModifierId ,                                     ModifierType,                                    SubjectRequirementSetId,                               OwnerRequirementSetId)
SELECT 'GOLDEN_CITY_CENTER_PLOT_PRODUCTION_' ||EraType,  'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',   'GOLDEN_PLOT_HAS_DISTRICT_CITY_CENTER_REQUIREMENTS',   'GOLDEN_GAME_ERA_ATLEAST_' ||EraType|| '_REQUIREMENTS' FROM Eras WHERE EraType <> 'ERA_ANCIENT';

INSERT OR REPLACE INTO ModifierArguments
       (ModifierId , Name , Value)
SELECT ModifierId , 'Amount' , 1 FROM DistrictModifiers WHERE ModifierId LIKE 'GOLDEN_CITY_CENTER_PLOT_%';
INSERT OR REPLACE INTO ModifierArguments
       (ModifierId , Name , Value)
SELECT ModifierId , 'YieldType' , 'YIELD_FOOD' FROM DistrictModifiers WHERE ModifierId LIKE 'GOLDEN_CITY_CENTER_PLOT_FOOD_%';
INSERT OR REPLACE INTO ModifierArguments
       (ModifierId , Name , Value)
SELECT ModifierId , 'YieldType' , 'YIELD_PRODUCTION' FROM DistrictModifiers WHERE ModifierId LIKE 'GOLDEN_CITY_CENTER_PLOT_PRODUCTION_%';

--allow placing districts on forest and jungle upon CIVIC_NATURAL_HISTORY
INSERT OR REPLACE INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId)
SELECT 'MODIFIER_DISTRICT_JUNGLE_ALLOW_' || DistrictType, 'MODIFIER_PLAYER_CITIES_ADJUST_VALID_FEATURES_DISTRICTS', 'GOLDEN_PLAYER_HAS_CIVIC_NATURAL_HISTORY_REQUIREMENTS' FROM Districts;
INSERT OR REPLACE INTO ModifierArguments(ModifierId, Name, Value)
SELECT 'MODIFIER_DISTRICT_JUNGLE_ALLOW_' || DistrictType, 'DistrictType', DistrictType FROM Districts;
INSERT OR REPLACE INTO ModifierArguments(ModifierId, Name, Value)
SELECT 'MODIFIER_DISTRICT_JUNGLE_ALLOW_' || DistrictType, 'FeatureType', 'FEATURE_JUNGLE' FROM Districts;
INSERT OR REPLACE INTO Traits(TraitType) 
VALUES('TRAIT_GA_DISTRICT_JUNGLE');
INSERT OR REPLACE INTO Types(Type, Kind) 
VALUES('TRAIT_GA_DISTRICT_JUNGLE', 'KIND_TRAIT');
INSERT OR REPLACE INTO TraitModifiers(TraitType, ModifierId)
SELECT 'TRAIT_GA_DISTRICT_JUNGLE', 'MODIFIER_DISTRICT_JUNGLE_ALLOW_' || DistrictType FROM Districts;
INSERT OR REPLACE INTO CivilizationTraits(CivilizationType, TraitType)
SELECT CivilizationType, 'TRAIT_GA_DISTRICT_JUNGLE' FROM Civilizations;
INSERT OR REPLACE INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId)
SELECT 'MODIFIER_DISTRICT_FOREST_ALLOW_' || DistrictType, 'MODIFIER_PLAYER_CITIES_ADJUST_VALID_FEATURES_DISTRICTS', 'GOLDEN_PLAYER_HAS_CIVIC_NATURAL_HISTORY_REQUIREMENTS' FROM Districts;
INSERT OR REPLACE INTO ModifierArguments(ModifierId, Name, Value)
SELECT 'MODIFIER_DISTRICT_FOREST_ALLOW_' || DistrictType, 'DistrictType', DistrictType FROM Districts;
INSERT OR REPLACE INTO ModifierArguments(ModifierId, Name, Value)
SELECT 'MODIFIER_DISTRICT_FOREST_ALLOW_' || DistrictType, 'FeatureType', 'FEATURE_FOREST' FROM Districts;
INSERT OR REPLACE INTO Traits(TraitType) 
VALUES('TRAIT_GA_DISTRICT_FOREST');
INSERT OR REPLACE INTO Types(Type, Kind) 
VALUES('TRAIT_GA_DISTRICT_FOREST', 'KIND_TRAIT');
INSERT OR REPLACE INTO TraitModifiers(TraitType, ModifierId)
SELECT 'TRAIT_GA_DISTRICT_FOREST', 'MODIFIER_DISTRICT_FOREST_ALLOW_' || DistrictType FROM Districts;
INSERT OR REPLACE INTO CivilizationTraits(CivilizationType, TraitType)
SELECT CivilizationType, 'TRAIT_GA_DISTRICT_FOREST' FROM Civilizations;
DELETE FROM TraitModifiers WHERE ModifierId='MODIFIER_DISTRICT_FOREST_ALLOW_DISTRICT_INDUSTRIAL_ZONE';
DELETE FROM TraitModifiers WHERE ModifierId='MODIFIER_DISTRICT_JUNGLE_ALLOW_DISTRICT_INDUSTRIAL_ZONE';
DELETE FROM TraitModifiers WHERE ModifierId='MODIFIER_DISTRICT_FOREST_ALLOW_DISTRICT_HANSA';
DELETE FROM TraitModifiers WHERE ModifierId='MODIFIER_DISTRICT_JUNGLE_ALLOW_DISTRICT_HANSA';
DELETE FROM TraitModifiers WHERE ModifierId='MODIFIER_DISTRICT_FOREST_ALLOW_DISTRICT_ENCAMPMENT';
DELETE FROM TraitModifiers WHERE ModifierId='MODIFIER_DISTRICT_JUNGLE_ALLOW_DISTRICT_ENCAMPMENT';
DELETE FROM TraitModifiers WHERE ModifierId='MODIFIER_DISTRICT_FOREST_ALLOW_DISTRICT_IKANDA';
DELETE FROM TraitModifiers WHERE ModifierId='MODIFIER_DISTRICT_JUNGLE_ALLOW_DISTRICT_IKANDA';
DELETE FROM TraitModifiers WHERE ModifierId='MODIFIER_DISTRICT_FOREST_ALLOW_DISTRICT_SPACEPORT';
DELETE FROM TraitModifiers WHERE ModifierId='MODIFIER_DISTRICT_JUNGLE_ALLOW_DISTRICT_SPACEPORT';
DELETE FROM TraitModifiers WHERE ModifierId='MODIFIER_DISTRICT_FOREST_ALLOW_DISTRICT_AERODROME';
DELETE FROM TraitModifiers WHERE ModifierId='MODIFIER_DISTRICT_JUNGLE_ALLOW_DISTRICT_AERODROME';

--非专业化区域加2专家槽位 产出2粮2锤2金
UPDATE Districts SET CitizenSlots = 2 WHERE DistrictType = 'DISTRICT_GOVERNMENT';
UPDATE Districts SET CitizenSlots = 2 WHERE DistrictType = 'DISTRICT_AERODROME';
UPDATE Districts SET CitizenSlots = 2 WHERE DistrictType = 'DISTRICT_AQUEDUCT';
UPDATE Districts SET CitizenSlots = 2 WHERE DistrictType = 'DISTRICT_CANAL';
UPDATE Districts SET CitizenSlots = 2 WHERE DistrictType = 'DISTRICT_DAM';
UPDATE Districts SET CitizenSlots = 2 WHERE DistrictType = 'DISTRICT_NEIGHBORHOOD';
UPDATE Districts SET CitizenSlots = 2 WHERE DistrictType = 'DISTRICT_BATH';
UPDATE Districts SET CitizenSlots = 2 WHERE DistrictType = 'DISTRICT_MBANZA';
UPDATE Districts SET CitizenSlots = 2 WHERE DistrictType = 'DISTRICT_DIPLOMATIC_QUARTER' AND EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_DIPLOMATIC_QUARTER');
UPDATE Districts SET CitizenSlots = 2 WHERE DistrictType = 'DISTRICT_PRESERVE' AND EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_PRESERVE');

INSERT OR REPLACE INTO District_CitizenYieldChanges (DistrictType, YieldType, YieldChange) VALUES 
('DISTRICT_GOVERNMENT',  'YIELD_FOOD',       	2), 		
('DISTRICT_GOVERNMENT',  'YIELD_GOLD',       	2), 		 
('DISTRICT_GOVERNMENT',  'YIELD_PRODUCTION',    2),
('DISTRICT_AERODROME',   'YIELD_FOOD',       	2), 		
('DISTRICT_AERODROME',   'YIELD_GOLD',       	2), 		 
('DISTRICT_AERODROME',   'YIELD_PRODUCTION',    2),
('DISTRICT_AQUEDUCT',    'YIELD_FOOD',       	2), 		
('DISTRICT_AQUEDUCT',    'YIELD_GOLD',       	2), 		 
('DISTRICT_AQUEDUCT',    'YIELD_PRODUCTION',    2),
('DISTRICT_CANAL',  	'YIELD_FOOD',       	2), 		
('DISTRICT_CANAL',  	'YIELD_GOLD',       	2), 		 
('DISTRICT_CANAL',  	'YIELD_PRODUCTION',     2),
('DISTRICT_DAM',  		'YIELD_FOOD',       	2), 		
('DISTRICT_DAM',  		'YIELD_GOLD',       	2), 		 
('DISTRICT_DAM',  		'YIELD_PRODUCTION',     2),
('DISTRICT_NEIGHBORHOOD',  'YIELD_FOOD',       	2), 		
('DISTRICT_NEIGHBORHOOD',  'YIELD_GOLD',       	2), 		 
('DISTRICT_NEIGHBORHOOD',  'YIELD_PRODUCTION',  2),
('DISTRICT_BATH',  		'YIELD_FOOD',       	2), 		
('DISTRICT_BATH',  		'YIELD_GOLD',       	2), 		 
('DISTRICT_BATH',  		'YIELD_PRODUCTION',     2),
('DISTRICT_MBANZA',  	'YIELD_FOOD',       	2), 		
('DISTRICT_MBANZA',  	'YIELD_GOLD',       	2), 		 
('DISTRICT_MBANZA',  	'YIELD_PRODUCTION',     2); 		
INSERT OR REPLACE INTO District_CitizenYieldChanges (DistrictType, YieldType, YieldChange) SELECT 
'DISTRICT_DIPLOMATIC_QUARTER',  'YIELD_FOOD',       	2 		 WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_DIPLOMATIC_QUARTER');
INSERT OR REPLACE INTO District_CitizenYieldChanges (DistrictType, YieldType, YieldChange) SELECT 
'DISTRICT_DIPLOMATIC_QUARTER',  'YIELD_GOLD',       	2 		 WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_DIPLOMATIC_QUARTER');
INSERT OR REPLACE INTO District_CitizenYieldChanges (DistrictType, YieldType, YieldChange) SELECT 
'DISTRICT_DIPLOMATIC_QUARTER',  'YIELD_PRODUCTION',     2 		 WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_DIPLOMATIC_QUARTER');
INSERT OR REPLACE INTO District_CitizenYieldChanges (DistrictType, YieldType, YieldChange) SELECT 
'DISTRICT_PRESERVE',  'YIELD_FOOD',       	2 		 WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_PRESERVE');
INSERT OR REPLACE INTO District_CitizenYieldChanges (DistrictType, YieldType, YieldChange) SELECT 
'DISTRICT_PRESERVE',  'YIELD_GOLD',       	2 		 WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_PRESERVE');
INSERT OR REPLACE INTO District_CitizenYieldChanges (DistrictType, YieldType, YieldChange) SELECT 
'DISTRICT_PRESERVE',  'YIELD_PRODUCTION',   2 		 WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_PRESERVE');

--新城市更多人口和单元格
INSERT OR REPLACE INTO TraitModifiers
       (TraitType ,           ModifierId)
SELECT 'TRAIT_LEADER_MAJOR_CIV' ,  'GOLDEN_NEW_CITY_CITIZEN_' ||EraType FROM Eras WHERE EraType <> 'ERA_ANCIENT';
INSERT OR REPLACE INTO TraitModifiers
       (TraitType ,           ModifierId)
SELECT 'TRAIT_LEADER_MAJOR_CIV' ,  'GOLDEN_NEW_CITY_PLOT_' ||EraType FROM Eras WHERE EraType <> 'ERA_ANCIENT';

INSERT OR REPLACE INTO Modifiers
       (ModifierId ,                                ModifierType,                                    		SubjectRequirementSetId)
SELECT 'GOLDEN_NEW_CITY_CITIZEN_' ||EraType,        'MODIFIER_PLAYER_BUILT_CITIES_GRANT_FREE_POPULATION',   'GOLDEN_GAME_ERA_ATLEAST_' ||EraType|| '_REQUIREMENTS' FROM Eras WHERE EraType <> 'ERA_ANCIENT';
INSERT OR REPLACE INTO Modifiers
       (ModifierId ,                                ModifierType,                                    		SubjectRequirementSetId)
SELECT 'GOLDEN_NEW_CITY_PLOT_' ||EraType,  			'MODIFIER_PLAYER_ADJUST_CITY_TILES',   					'GOLDEN_GAME_ERA_ATLEAST_' ||EraType|| '_REQUIREMENTS' FROM Eras WHERE EraType <> 'ERA_ANCIENT';

INSERT OR REPLACE INTO ModifierArguments
       (ModifierId , Name , Value)
SELECT ModifierId , 'Amount' , 1 FROM TraitModifiers WHERE ModifierId LIKE 'GOLDEN_NEW_CITY_CITIZEN_ERA_%';
INSERT OR REPLACE INTO ModifierArguments
       (ModifierId , Name , Value)
SELECT ModifierId , 'Amount' , 1 FROM TraitModifiers WHERE ModifierId LIKE 'GOLDEN_NEW_CITY_PLOT_ERA_%';

--不同时代开局
UPDATE StartEras SET Gold=80
WHERE EraType = 'ERA_ANCIENT';
UPDATE StartEras SET Gold=300, Faith=300, StartingPopulationCapital=4, StartingAmenitiesCapital=1, StartingHousingCapital=1
WHERE EraType = 'ERA_CLASSICAL';
UPDATE StartEras SET Gold=600, Faith=600, StartingPopulationCapital=7, StartingAmenitiesCapital=2, StartingHousingCapital=5, StartingPopulationOtherCities=3, StartingAmenitiesOtherCities=2, StartingHousingOtherCities=1
WHERE EraType = 'ERA_MEDIEVAL';
UPDATE StartEras SET Gold=900, Faith=900, StartingPopulationCapital=10, StartingAmenitiesCapital=4, StartingHousingCapital=9, StartingPopulationOtherCities=4, StartingAmenitiesOtherCities=3, StartingHousingOtherCities=3
WHERE EraType = 'ERA_RENAISSANCE';
UPDATE StartEras SET Gold=1200, Faith=1200, StartingPopulationCapital=13, StartingAmenitiesCapital=5, StartingHousingCapital=13, StartingPopulationOtherCities=5, StartingAmenitiesOtherCities=3, StartingHousingOtherCities=5
WHERE EraType = 'ERA_INDUSTRIAL';
UPDATE StartEras SET Gold=1500, Faith=1500, StartingPopulationCapital=16, StartingAmenitiesCapital=6, StartingHousingCapital=17, StartingPopulationOtherCities=6, StartingAmenitiesOtherCities=4, StartingHousingOtherCities=7
WHERE EraType = 'ERA_MODERN';
UPDATE StartEras SET Gold=1800, Faith=1800, StartingPopulationCapital=19, StartingAmenitiesCapital=8, StartingHousingCapital=21, StartingPopulationOtherCities=7, StartingAmenitiesOtherCities=5, StartingHousingOtherCities=9
WHERE EraType = 'ERA_ATOMIC';
UPDATE StartEras SET Gold=2100, Faith=2100, StartingPopulationCapital=22, StartingAmenitiesCapital=9, StartingHousingCapital=24, StartingPopulationOtherCities=8, StartingAmenitiesOtherCities=5, StartingHousingOtherCities=11
WHERE EraType = 'ERA_INFORMATION';

--XML to SQL
--水渠 6 - 8
REPLACE INTO GlobalParameters (Name, Value)
VALUES ('CITY_POPULATION_AQUEDUCT_MIN', 8);

-- 区域涨价
UPDATE Districts SET Cost = 30 WHERE Cost = 27;
UPDATE Districts SET Cost = 60 WHERE Cost = 54;

-- 政府广场不再需要人口
UPDATE Districts SET RequiresPopulation = 0 WHERE DistrictType = 'DISTRICT_GOVERNMENT';

-- 水渠成本
UPDATE Districts SET Cost = 48 WHERE DistrictType = 'DISTRICT_AQUEDUCT';

-- 运河成本与科技前置
UPDATE Districts
SET Cost = 48, PrereqTech = 'TECH_BUTTRESS'
WHERE DistrictType = 'DISTRICT_CANAL';

-- 水坝属性调整
UPDATE Districts
SET Cost = 48, OnePerCity = 1, Entertainment = 0, Housing = 0
WHERE DistrictType = 'DISTRICT_DAM';

-- 住宅区调整
UPDATE Districts
SET Cost = 48, Housing = 4
WHERE DistrictType = 'DISTRICT_NEIGHBORHOOD';

-- 水上娱乐区调整
UPDATE Districts
SET Entertainment = 0, PrereqCivic = 'CIVIC_COLONIALISM'
WHERE DistrictType = 'DISTRICT_WATER_ENTERTAINMENT_COMPLEX';

-- 娱乐区不再直接提供娱乐
UPDATE Districts
SET Entertainment = 0
WHERE DistrictType = 'DISTRICT_ENTERTAINMENT_COMPLEX';

-- 工业区不能邻近城市中心
UPDATE Districts
SET NoAdjacentCity = 1
WHERE DistrictType = 'DISTRICT_INDUSTRIAL_ZONE';

-- 区域攻击范围
REPLACE INTO Districts_XP2 (DistrictType, AttackRange)
VALUES ('DISTRICT_HARBOR', 1);

REPLACE INTO Districts_XP2 (DistrictType, AttackRange)
VALUES ('DISTRICT_ENCAMPMENT', 1);

-- 魅力对社区加成
UPDATE AppealHousingChanges
SET AppealChange = 4
WHERE DistrictType = 'DISTRICT_NEIGHBORHOOD' AND MinimumValue = 4;

UPDATE AppealHousingChanges
SET AppealChange = 2
WHERE DistrictType = 'DISTRICT_NEIGHBORHOOD' AND MinimumValue = 2;

UPDATE AppealHousingChanges
SET AppealChange = 0
WHERE DistrictType = 'DISTRICT_NEIGHBORHOOD' AND MinimumValue = -1;

UPDATE AppealHousingChanges
SET AppealChange = -2
WHERE DistrictType = 'DISTRICT_NEIGHBORHOOD' AND MinimumValue = -3;

UPDATE AppealHousingChanges
SET AppealChange = -4
WHERE DistrictType = 'DISTRICT_NEIGHBORHOOD' AND MinimumValue = -100;


