--V228 未来时代政策改为非紫卡
UPDATE Policies SET GovernmentSlotType="SLOT_MILITARY" WHERE PolicyType="POLICY_FUTURE_VICTORY_SCIENCE";
UPDATE Policies SET GovernmentSlotType="SLOT_DIPLOMATIC" WHERE PolicyType="POLICY_FUTURE_COUNTER_CULTURE";
UPDATE Policies SET GovernmentSlotType="SLOT_DIPLOMATIC" WHERE PolicyType="POLICY_FUTURE_VICTORY_CULTURE";
UPDATE Policies SET GovernmentSlotType="SLOT_DIPLOMATIC" WHERE PolicyType="POLICY_FUTURE_COUNTER_SCIENCE";
UPDATE Policies SET GovernmentSlotType="SLOT_MILITARY" WHERE PolicyType="POLICY_FUTURE_VICTORY_DOMINATION";
UPDATE Policies SET GovernmentSlotType="SLOT_DIPLOMATIC" WHERE PolicyType="POLICY_FUTURE_COUNTER_DIPLOMATIC";
UPDATE Policies SET GovernmentSlotType="SLOT_DIPLOMATIC" WHERE PolicyType="POLICY_FUTURE_VICTORY_DIPLOMATIC";
UPDATE Policies SET GovernmentSlotType="SLOT_MILITARY" WHERE PolicyType="POLICY_FUTURE_COUNTER_DOMINATION";
--屏蔽政策卡
UPDATE Policies SET ExplicitUnlock = 1 WHERE PolicyType="POLICY_MILITARY_RESEARCH";
UPDATE Policies SET ExplicitUnlock = 1 WHERE PolicyType="POLICY_INTEGRATED_SPACE_CELL";
UPDATE Policies SET ExplicitUnlock = 1 WHERE PolicyType="POLICY_LIBERALISM";
UPDATE Policies SET ExplicitUnlock = 1 WHERE PolicyType="POLICY_LAISSEZ_FAIRE";
UPDATE Policies SET ExplicitUnlock = 1 WHERE PolicyType="POLICY_SPORTS_MEDIA";
UPDATE Policies SET ExplicitUnlock = 1 WHERE PolicyType="POLICY_MILITARY_ORGANIZATION";
UPDATE Policies SET ExplicitUnlock = 1 WHERE PolicyType="POLICY_NOBEL_PRIZE";
UPDATE Policies SET ExplicitUnlock = 1 WHERE PolicyType="POLICY_FIVE_YEAR_PLAN";
UPDATE Policies SET ExplicitUnlock = 1 WHERE PolicyType="POLICY_ECONOMIC_UNION";