--市政厅建筑
INSERT OR REPLACE INTO Types 
(Type,								Kind)
VALUES
('BUILDING_CITYHALL_VILLAGE',		'KIND_BUILDING'),
('BUILDING_CITYHALL_TOWN',			'KIND_BUILDING'),
('BUILDING_CITYHALL_COUNTY',		'KIND_BUILDING'),
('BUILDING_CITYHALL_CITY',			'KIND_BUILDING'),
('BUILDING_CITYHALL_METROPOLIS',	'KIND_BUILDING');

INSERT OR REPLACE INTO Buildings 
(BuildingType,					        Name,                                       Description,                                      Cost, Maintenance, PrereqDistrict,         AdvisorType,       InternalOnly, Entertainment)
VALUES
('BUILDING_CITYHALL_VILLAGE',	        'LOC_BUILDING_CITYHALL_VILLAGE_NAME',       'LOC_BUILDING_CITYHALL_VILLAGE_DESCRIPTION',      100,  1,           'DISTRICT_CITY_CENTER', 'ADVISOR_GENERIC', 0,       0),
('BUILDING_CITYHALL_TOWN',	            'LOC_BUILDING_CITYHALL_TOWN_NAME',          'LOC_BUILDING_CITYHALL_TOWN_DESCRIPTION',         200,  2,           'DISTRICT_CITY_CENTER', 'ADVISOR_GENERIC', 1,       0),
('BUILDING_CITYHALL_COUNTY',	        'LOC_BUILDING_CITYHALL_COUNTY_NAME',        'LOC_BUILDING_CITYHALL_COUNTY_DESCRIPTION',       300,  3,           'DISTRICT_CITY_CENTER', 'ADVISOR_GENERIC', 1,       0),
('BUILDING_CITYHALL_CITY',	            'LOC_BUILDING_CITYHALL_CITY_NAME',          'LOC_BUILDING_CITYHALL_CITY_DESCRIPTION',         400,  4,           'DISTRICT_CITY_CENTER', 'ADVISOR_GENERIC', 1,       0),
('BUILDING_CITYHALL_METROPOLIS',	    'LOC_BUILDING_CITYHALL_METROPOLIS_NAME',    'LOC_BUILDING_CITYHALL_METROPOLIS_DESCRIPTION',   500,  5,           'DISTRICT_CITY_CENTER', 'ADVISOR_GENERIC', 1,       0);

INSERT OR REPLACE INTO Buildings_XP2 
(BuildingType,							Pillage)
VALUES
('BUILDING_CITYHALL_VILLAGE',	        0),
('BUILDING_CITYHALL_TOWN',	            0),
('BUILDING_CITYHALL_COUNTY',	        0),
('BUILDING_CITYHALL_CITY',	            0),
('BUILDING_CITYHALL_METROPOLIS',	    0);

INSERT OR REPLACE INTO MutuallyExclusiveBuildings 
(Building,					                MutuallyExclusiveBuilding)
VALUES	
('BUILDING_CITYHALL_VILLAGE',			'BUILDING_CITYHALL_TOWN'),
('BUILDING_CITYHALL_VILLAGE',			'BUILDING_CITYHALL_COUNTY'),
('BUILDING_CITYHALL_VILLAGE',			'BUILDING_CITYHALL_CITY'),
('BUILDING_CITYHALL_VILLAGE',			'BUILDING_CITYHALL_METROPOLIS'),
('BUILDING_CITYHALL_TOWN',				'BUILDING_CITYHALL_VILLAGE'),
('BUILDING_CITYHALL_TOWN',				'BUILDING_CITYHALL_COUNTY'),
('BUILDING_CITYHALL_TOWN',				'BUILDING_CITYHALL_CITY'),
('BUILDING_CITYHALL_TOWN',				'BUILDING_CITYHALL_METROPOLIS'),
('BUILDING_CITYHALL_COUNTY',			'BUILDING_CITYHALL_VILLAGE'),
('BUILDING_CITYHALL_COUNTY',			'BUILDING_CITYHALL_TOWN'),
('BUILDING_CITYHALL_COUNTY',			'BUILDING_CITYHALL_CITY'),
('BUILDING_CITYHALL_COUNTY',			'BUILDING_CITYHALL_METROPOLIS'),
('BUILDING_CITYHALL_CITY',				'BUILDING_CITYHALL_VILLAGE'),
('BUILDING_CITYHALL_CITY',				'BUILDING_CITYHALL_TOWN'),
('BUILDING_CITYHALL_CITY',				'BUILDING_CITYHALL_COUNTY'),
('BUILDING_CITYHALL_CITY',				'BUILDING_CITYHALL_METROPOLIS'),
('BUILDING_CITYHALL_METROPOLIS',		'BUILDING_CITYHALL_VILLAGE'),
('BUILDING_CITYHALL_METROPOLIS',		'BUILDING_CITYHALL_TOWN'),
('BUILDING_CITYHALL_METROPOLIS',		'BUILDING_CITYHALL_COUNTY'),
('BUILDING_CITYHALL_METROPOLIS',		'BUILDING_CITYHALL_CITY');

INSERT OR REPLACE INTO DistrictModifiers 
(DistrictType,				ModifierId)
VALUES	
('DISTRICT_CITY_CENTER',	'GOLDEN_FREE_BUILDING_CITYHALL_VILLAGE');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,								ModifierType,											RunOnce,	Permanent)
VALUES
('GOLDEN_FREE_BUILDING_CITYHALL_VILLAGE',	'MODIFIER_SINGLE_CITY_GRANT_BUILDING_IN_CITY_IGNORE',	1,			1);

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,								Name,				Value)
VALUES
('GOLDEN_FREE_BUILDING_CITYHALL_VILLAGE',	'BuildingType',		'BUILDING_CITYHALL_VILLAGE');

--城市扩建项目
INSERT OR REPLACE INTO Types 
(Type,							Kind)
VALUES	
('PROJECT_VILLAGE_TOWN',		'KIND_PROJECT'),
('PROJECT_TOWN_COUNTY',			'KIND_PROJECT'),
('PROJECT_COUNTY_CITY',			'KIND_PROJECT'),
('PROJECT_CITY_METROPOLIS',		'KIND_PROJECT');

INSERT OR REPLACE INTO Projects 
(ProjectType,					Name,									ShortName,								Description,									Cost,	PrereqCivic,					PrereqDistrict,			AdvisorType)
VALUES
('PROJECT_VILLAGE_TOWN',		'LOC_PROJECT_VILLAGE_TOWN_NAME',		'LOC_PROJECT_VILLAGE_TOWN_NAME',		'LOC_PROJECT_VILLAGE_TOWN_DESCRIPTION',			100,	'CIVIC_POLITICAL_PHILOSOPHY',	'DISTRICT_CITY_CENTER',	'ADVISOR_GENERIC'),
('PROJECT_TOWN_COUNTY',			'LOC_PROJECT_TOWN_COUNTY_NAME',			'LOC_PROJECT_TOWN_COUNTY_NAME',			'LOC_PROJECT_TOWN_COUNTY_DESCRIPTION',			200,	'CIVIC_GUILDS',					'DISTRICT_CITY_CENTER',	'ADVISOR_GENERIC'),
('PROJECT_COUNTY_CITY',			'LOC_PROJECT_COUNTY_CITY_NAME',			'LOC_PROJECT_COUNTY_CITY_NAME',			'LOC_PROJECT_COUNTY_CITY_DESCRIPTION',			300,	'CIVIC_CIVIL_ENGINEERING',		'DISTRICT_CITY_CENTER',	'ADVISOR_GENERIC'),
('PROJECT_CITY_METROPOLIS',		'LOC_PROJECT_CITY_METROPOLIS_NAME',		'LOC_PROJECT_CITY_METROPOLIS_NAME',		'LOC_PROJECT_CITY_METROPOLIS_DESCRIPTION',		400,	'CIVIC_CAPITALISM',				'DISTRICT_CITY_CENTER',	'ADVISOR_GENERIC');

INSERT OR REPLACE INTO Projects_XP2 
(ProjectType,					        CreateBuilding)
VALUES	
('PROJECT_VILLAGE_TOWN',	            'BUILDING_CITYHALL_TOWN'),
('PROJECT_TOWN_COUNTY',	                'BUILDING_CITYHALL_COUNTY'),
('PROJECT_COUNTY_CITY',	                'BUILDING_CITYHALL_CITY'),
('PROJECT_CITY_METROPOLIS',	            'BUILDING_CITYHALL_METROPOLIS');

INSERT OR REPLACE INTO Project_BuildingCosts 
(ProjectType,					        ConsumedBuildingType)
VALUES	
('PROJECT_VILLAGE_TOWN',	            'BUILDING_CITYHALL_VILLAGE'),
('PROJECT_TOWN_COUNTY',	                'BUILDING_CITYHALL_TOWN'),
('PROJECT_COUNTY_CITY',	                'BUILDING_CITYHALL_COUNTY'),
('PROJECT_CITY_METROPOLIS',	            'BUILDING_CITYHALL_CITY');

INSERT OR REPLACE INTO ProjectCompletionModifiers 
(ProjectType,					        ModifierId)
VALUES	
('PROJECT_VILLAGE_TOWN',	            'GOLDEN_VILLAGE_TOWN_HOUSING'),
('PROJECT_TOWN_COUNTY',	                'GOLDEN_TOWN_COUNTY_HOUSING'),
('PROJECT_COUNTY_CITY',	                'GOLDEN_COUNTY_CITY_HOUSING'),
('PROJECT_CITY_METROPOLIS',	            'GOLDEN_CITY_METROPOLIS_HOUSING');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,								ModifierType)
VALUES
('GOLDEN_VILLAGE_TOWN_HOUSING',	           'MODIFIER_SINGLE_CITY_ADJUST_BUILDING_HOUSING'),
('GOLDEN_TOWN_COUNTY_HOUSING',	           'MODIFIER_SINGLE_CITY_ADJUST_BUILDING_HOUSING'),
('GOLDEN_COUNTY_CITY_HOUSING',	           'MODIFIER_SINGLE_CITY_ADJUST_BUILDING_HOUSING'),
('GOLDEN_CITY_METROPOLIS_HOUSING',	       'MODIFIER_SINGLE_CITY_ADJUST_BUILDING_HOUSING');

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,						        Name,		    Value) VALUES
('GOLDEN_VILLAGE_TOWN_HOUSING',	            'Amount',	    1),
('GOLDEN_TOWN_COUNTY_HOUSING',	            'Amount',	    2),
('GOLDEN_COUNTY_CITY_HOUSING',	            'Amount',	    3),
('GOLDEN_CITY_METROPOLIS_HOUSING',	        'Amount',	    4);

--爆铺惩罚
INSERT OR REPLACE INTO DistrictModifiers 
(DistrictType,				ModifierId) 
VALUES	
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_SCIENCE_DEBUFF_TEN'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_CULTURE_DEBUFF_TEN'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_GOLD_DEBUFF_TEN'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_FAITH_DEBUFF_TEN'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_SCIENCE_DEBUFF_TWENTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_CULTURE_DEBUFF_TWENTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_GOLD_DEBUFF_TWENTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_FAITH_DEBUFF_TWENTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_SCIENCE_DEBUFF_THIRTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_CULTURE_DEBUFF_THIRTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_GOLD_DEBUFF_THIRTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_FAITH_DEBUFF_THIRTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_SCIENCE_DEBUFF_FOURTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_CULTURE_DEBUFF_FOURTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_GOLD_DEBUFF_FOURTY'),
('DISTRICT_CITY_CENTER',	'GOLDEN_CITY_FAITH_DEBUFF_FOURTY');

---抵消1次
INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,			ModifierId)
VALUES	
('BUILDING_PALACE',		'GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_TEN'),
('BUILDING_PALACE',		'GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_TEN'),
('BUILDING_PALACE',		'GOLDEN_CITY_GOLD_DEBUFF_OFFSET_TEN'),
('BUILDING_PALACE',		'GOLDEN_CITY_FAITH_DEBUFF_OFFSET_TEN'),
('BUILDING_PALACE',		'GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_TWENTY'),
('BUILDING_PALACE',		'GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_TWENTY'),
('BUILDING_PALACE',		'GOLDEN_CITY_GOLD_DEBUFF_OFFSET_TWENTY'),
('BUILDING_PALACE',		'GOLDEN_CITY_FAITH_DEBUFF_OFFSET_TWENTY'),
('BUILDING_PALACE',		'GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_THIRTY'),
('BUILDING_PALACE',		'GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_THIRTY'),
('BUILDING_PALACE',		'GOLDEN_CITY_GOLD_DEBUFF_OFFSET_THIRTY'),
('BUILDING_PALACE',		'GOLDEN_CITY_FAITH_DEBUFF_OFFSET_THIRTY'),
('BUILDING_PALACE',		'GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_FOURTY'),
('BUILDING_PALACE',		'GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_FOURTY'),
('BUILDING_PALACE',		'GOLDEN_CITY_GOLD_DEBUFF_OFFSET_FOURTY'),
('BUILDING_PALACE',		'GOLDEN_CITY_FAITH_DEBUFF_OFFSET_FOURTY');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,									ModifierType,											SubjectRequirementSetId)
VALUES
('GOLDEN_CITY_SCIENCE_DEBUFF_TEN',	        	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_4'),
('GOLDEN_CITY_CULTURE_DEBUFF_TEN',	        	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_4'),
('GOLDEN_CITY_GOLD_DEBUFF_TEN',	            	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_4'),
('GOLDEN_CITY_FAITH_DEBUFF_TEN',	        	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_4'),
('GOLDEN_CITY_SCIENCE_DEBUFF_TWENTY',	    	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_3'),
('GOLDEN_CITY_CULTURE_DEBUFF_TWENTY',	    	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_3'),
('GOLDEN_CITY_GOLD_DEBUFF_TWENTY',	        	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_3'),
('GOLDEN_CITY_FAITH_DEBUFF_TWENTY',	        	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_3'),
('GOLDEN_CITY_SCIENCE_DEBUFF_THIRTY',	    	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_2'),
('GOLDEN_CITY_CULTURE_DEBUFF_THIRTY',	    	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_2'),
('GOLDEN_CITY_GOLD_DEBUFF_THIRTY',	        	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_2'),
('GOLDEN_CITY_FAITH_DEBUFF_THIRTY',	        	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_2'),
('GOLDEN_CITY_SCIENCE_DEBUFF_FOURTY',	    	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_1'),
('GOLDEN_CITY_CULTURE_DEBUFF_FOURTY',	    	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_1'),
('GOLDEN_CITY_GOLD_DEBUFF_FOURTY',	        	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_1'),
('GOLDEN_CITY_FAITH_DEBUFF_FOURTY',	        	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_1'),
('GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_TEN',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_4'),
('GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_TEN',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_4'),
('GOLDEN_CITY_GOLD_DEBUFF_OFFSET_TEN',			'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_4'),
('GOLDEN_CITY_FAITH_DEBUFF_OFFSET_TEN',			'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_4'),
('GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_TWENTY',	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_3'),
('GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_TWENTY',	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_3'),
('GOLDEN_CITY_GOLD_DEBUFF_OFFSET_TWENTY',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_3'),
('GOLDEN_CITY_FAITH_DEBUFF_OFFSET_TWENTY',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_3'),
('GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_THIRTY',	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_2'),
('GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_THIRTY',	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_2'),
('GOLDEN_CITY_GOLD_DEBUFF_OFFSET_THIRTY',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_2'),
('GOLDEN_CITY_FAITH_DEBUFF_OFFSET_THIRTY',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_2'),
('GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_FOURTY',	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_1'),
('GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_FOURTY',	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_1'),
('GOLDEN_CITY_GOLD_DEBUFF_OFFSET_FOURTY',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_1'),
('GOLDEN_CITY_FAITH_DEBUFF_OFFSET_FOURTY',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'RS_PROP_CITY_LEVEL_1');

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,							    	Name,		    Value) VALUES
('GOLDEN_CITY_SCIENCE_DEBUFF_TEN',				'YieldType',    'YIELD_SCIENCE'),
('GOLDEN_CITY_SCIENCE_DEBUFF_TEN',				'Amount',	    -1),
('GOLDEN_CITY_CULTURE_DEBUFF_TEN',				'YieldType',    'YIELD_CULTURE'),
('GOLDEN_CITY_CULTURE_DEBUFF_TEN',				'Amount',	    -1),
('GOLDEN_CITY_GOLD_DEBUFF_TEN',					'YieldType',    'YIELD_GOLD'),
('GOLDEN_CITY_GOLD_DEBUFF_TEN',					'Amount',	    -1),
('GOLDEN_CITY_FAITH_DEBUFF_TEN',				'YieldType',    'YIELD_FAITH'),
('GOLDEN_CITY_FAITH_DEBUFF_TEN',				'Amount',	    -1),
('GOLDEN_CITY_SCIENCE_DEBUFF_TWENTY',			'YieldType',    'YIELD_SCIENCE'),
('GOLDEN_CITY_SCIENCE_DEBUFF_TWENTY',			'Amount',	    -1),
('GOLDEN_CITY_CULTURE_DEBUFF_TWENTY',			'YieldType',    'YIELD_CULTURE'),
('GOLDEN_CITY_CULTURE_DEBUFF_TWENTY',			'Amount',	    -1),
('GOLDEN_CITY_GOLD_DEBUFF_TWENTY',				'YieldType',    'YIELD_GOLD'),
('GOLDEN_CITY_GOLD_DEBUFF_TWENTY',				'Amount',	    -1),
('GOLDEN_CITY_FAITH_DEBUFF_TWENTY',				'YieldType',    'YIELD_FAITH'),
('GOLDEN_CITY_FAITH_DEBUFF_TWENTY',				'Amount',	    -1),
('GOLDEN_CITY_SCIENCE_DEBUFF_THIRTY',			'YieldType',    'YIELD_SCIENCE'),
('GOLDEN_CITY_SCIENCE_DEBUFF_THIRTY',			'Amount',	    -1),
('GOLDEN_CITY_CULTURE_DEBUFF_THIRTY',			'YieldType',    'YIELD_CULTURE'),
('GOLDEN_CITY_CULTURE_DEBUFF_THIRTY',			'Amount',	    -1),
('GOLDEN_CITY_GOLD_DEBUFF_THIRTY',				'YieldType',    'YIELD_GOLD'),
('GOLDEN_CITY_GOLD_DEBUFF_THIRTY',				'Amount',	    -1),
('GOLDEN_CITY_FAITH_DEBUFF_THIRTY',				'YieldType',    'YIELD_FAITH'),
('GOLDEN_CITY_FAITH_DEBUFF_THIRTY',				'Amount',	    -1),
('GOLDEN_CITY_SCIENCE_DEBUFF_FOURTY',	    	'YieldType',    'YIELD_SCIENCE'),
('GOLDEN_CITY_SCIENCE_DEBUFF_FOURTY',	    	'Amount',	    -1),
('GOLDEN_CITY_CULTURE_DEBUFF_FOURTY',	    	'YieldType',    'YIELD_CULTURE'),
('GOLDEN_CITY_CULTURE_DEBUFF_FOURTY',	    	'Amount',	    -1),
('GOLDEN_CITY_GOLD_DEBUFF_FOURTY',	        	'YieldType',    'YIELD_GOLD'),
('GOLDEN_CITY_GOLD_DEBUFF_FOURTY',	        	'Amount',	    -1),
('GOLDEN_CITY_FAITH_DEBUFF_FOURTY',	        	'YieldType',    'YIELD_FAITH'),
('GOLDEN_CITY_FAITH_DEBUFF_FOURTY',	        	'Amount',	    -1),
('GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_TEN',		'YieldType',    'YIELD_SCIENCE'),
('GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_TEN',		'Amount',	    1),
('GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_TEN',		'YieldType',    'YIELD_CULTURE'),
('GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_TEN',		'Amount',	    1),
('GOLDEN_CITY_GOLD_DEBUFF_OFFSET_TEN',			'YieldType',    'YIELD_GOLD'),
('GOLDEN_CITY_GOLD_DEBUFF_OFFSET_TEN',			'Amount',	    1),
('GOLDEN_CITY_FAITH_DEBUFF_OFFSET_TEN',			'YieldType',    'YIELD_FAITH'),
('GOLDEN_CITY_FAITH_DEBUFF_OFFSET_TEN',			'Amount',	    1),
('GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_TWENTY',	'YieldType',    'YIELD_SCIENCE'),
('GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_TWENTY',	'Amount',	    1),
('GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_TWENTY',	'YieldType',    'YIELD_CULTURE'),
('GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_TWENTY',	'Amount',	    1),
('GOLDEN_CITY_GOLD_DEBUFF_OFFSET_TWENTY',		'YieldType',    'YIELD_GOLD'),
('GOLDEN_CITY_GOLD_DEBUFF_OFFSET_TWENTY',		'Amount',	    1),
('GOLDEN_CITY_FAITH_DEBUFF_OFFSET_TWENTY',		'YieldType',    'YIELD_FAITH'),
('GOLDEN_CITY_FAITH_DEBUFF_OFFSET_TWENTY',		'Amount',	    1),
('GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_THIRTY',	'YieldType',    'YIELD_SCIENCE'),
('GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_THIRTY',	'Amount',	    1),
('GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_THIRTY',	'YieldType',    'YIELD_CULTURE'),
('GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_THIRTY',	'Amount',	    1),
('GOLDEN_CITY_GOLD_DEBUFF_OFFSET_THIRTY',		'YieldType',    'YIELD_GOLD'),
('GOLDEN_CITY_GOLD_DEBUFF_OFFSET_THIRTY',		'Amount',	    1),
('GOLDEN_CITY_FAITH_DEBUFF_OFFSET_THIRTY',		'YieldType',    'YIELD_FAITH'),
('GOLDEN_CITY_FAITH_DEBUFF_OFFSET_THIRTY',		'Amount',	    1),
('GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_FOURTY',	'YieldType',    'YIELD_SCIENCE'),
('GOLDEN_CITY_SCIENCE_DEBUFF_OFFSET_FOURTY',	'Amount',	    1),
('GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_FOURTY',	'YieldType',    'YIELD_CULTURE'),
('GOLDEN_CITY_CULTURE_DEBUFF_OFFSET_FOURTY',	'Amount',	    1),
('GOLDEN_CITY_GOLD_DEBUFF_OFFSET_FOURTY',		'YieldType',    'YIELD_GOLD'),
('GOLDEN_CITY_GOLD_DEBUFF_OFFSET_FOURTY',		'Amount',	    1),
('GOLDEN_CITY_FAITH_DEBUFF_OFFSET_FOURTY',		 'YieldType',    'YIELD_FAITH'),
('GOLDEN_CITY_FAITH_DEBUFF_OFFSET_FOURTY',		 'Amount',	    1);

--忠诚度压力
INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,						ModifierId)
VALUES	
('BUILDING_CITYHALL_TOWN',	        'GOLDEN_CITY_IDENTITY_TOWN'),
('BUILDING_CITYHALL_COUNTY',	    'GOLDEN_CITY_IDENTITY_COUNTY'),
('BUILDING_CITYHALL_CITY',	        'GOLDEN_CITY_IDENTITY_CITY'),
('BUILDING_CITYHALL_METROPOLIS',	'GOLDEN_CITY_IDENTITY_METROPOLIS');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,								ModifierType)
VALUES
('GOLDEN_CITY_IDENTITY_TOWN',	            'MODIFIER_SINGLE_CITY_ADJUST_IDENTITY_PRESSURE'),
('GOLDEN_CITY_IDENTITY_COUNTY',	            'MODIFIER_SINGLE_CITY_ADJUST_IDENTITY_PRESSURE'),
('GOLDEN_CITY_IDENTITY_CITY',	            'MODIFIER_SINGLE_CITY_ADJUST_IDENTITY_PRESSURE'),
('GOLDEN_CITY_IDENTITY_METROPOLIS',	        'MODIFIER_SINGLE_CITY_ADJUST_IDENTITY_PRESSURE');

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,						    Name,		    Value)
VALUES
('GOLDEN_CITY_IDENTITY_TOWN',	        'Amount',	    4),
('GOLDEN_CITY_IDENTITY_COUNTY',	        'Amount',	    8),
('GOLDEN_CITY_IDENTITY_CITY',	        'Amount',	    12),
('GOLDEN_CITY_IDENTITY_METROPOLIS',	    'Amount',	    16);

--单位人口产出
INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,						ModifierId)
VALUES	
('BUILDING_CITYHALL_TOWN',			'GOLDEN_CITY_TOWN_POP_SCIENCE'),
('BUILDING_CITYHALL_TOWN',			'GOLDEN_CITY_TOWN_POP_CULTURE'),
('BUILDING_CITYHALL_TOWN',			'GOLDEN_CITY_TOWN_POP_PRODUCTION'),
('BUILDING_CITYHALL_COUNTY',		'GOLDEN_CITY_COUNTY_POP_SCIENCE'),
('BUILDING_CITYHALL_COUNTY',		'GOLDEN_CITY_COUNTY_POP_CULTURE'),
('BUILDING_CITYHALL_COUNTY',		'GOLDEN_CITY_COUNTY_POP_PRODUCTION'),
('BUILDING_CITYHALL_CITY',			'GOLDEN_CITY_CITY_POP_SCIENCE'),
('BUILDING_CITYHALL_CITY',			'GOLDEN_CITY_CITY_POP_CULTURE'),
('BUILDING_CITYHALL_CITY',			'GOLDEN_CITY_CITY_POP_PRODUCTION'),
('BUILDING_CITYHALL_METROPOLIS',	'GOLDEN_CITY_METROPOLIS_POP_SCIENCE'),
('BUILDING_CITYHALL_METROPOLIS',	'GOLDEN_CITY_METROPOLIS_POP_CULTURE'),
('BUILDING_CITYHALL_METROPOLIS',	'GOLDEN_CITY_METROPOLIS_POP_PRODUCTION');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,								ModifierType)
VALUES
('GOLDEN_CITY_TOWN_POP_SCIENCE',	        'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_CITY_TOWN_POP_CULTURE',	        'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_CITY_TOWN_POP_PRODUCTION',	        'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_CITY_COUNTY_POP_SCIENCE',	        'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_CITY_COUNTY_POP_CULTURE',	        'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_CITY_COUNTY_POP_PRODUCTION',	    'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_CITY_CITY_POP_SCIENCE',	        'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_CITY_CITY_POP_CULTURE',	        'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_CITY_CITY_POP_PRODUCTION',	        'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_CITY_METROPOLIS_POP_SCIENCE',	    'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_CITY_METROPOLIS_POP_CULTURE',	    'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_CITY_METROPOLIS_POP_PRODUCTION',	'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION');

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,						        Name,		    Value)
VALUES
('GOLDEN_CITY_TOWN_POP_SCIENCE',	        'YieldType',	'YIELD_SCIENCE'),
('GOLDEN_CITY_TOWN_POP_SCIENCE',	        'Amount',	    0.2),
('GOLDEN_CITY_TOWN_POP_CULTURE',	        'YieldType',	'YIELD_CULTURE'),
('GOLDEN_CITY_TOWN_POP_CULTURE',	        'Amount',	    0.2),
('GOLDEN_CITY_TOWN_POP_PRODUCTION',	        'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_CITY_TOWN_POP_PRODUCTION',	        'Amount',	    0.2),
('GOLDEN_CITY_COUNTY_POP_SCIENCE',	        'YieldType',	'YIELD_SCIENCE'),
('GOLDEN_CITY_COUNTY_POP_SCIENCE',	        'Amount',	    0.2),
('GOLDEN_CITY_COUNTY_POP_CULTURE',	        'YieldType',	'YIELD_CULTURE'),
('GOLDEN_CITY_COUNTY_POP_CULTURE',	        'Amount',	    0.2),
('GOLDEN_CITY_COUNTY_POP_PRODUCTION',	    'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_CITY_COUNTY_POP_PRODUCTION',	    'Amount',	    0.2),
('GOLDEN_CITY_CITY_POP_SCIENCE',	        'YieldType',	'YIELD_SCIENCE'),
('GOLDEN_CITY_CITY_POP_SCIENCE',	        'Amount',	    0.2),
('GOLDEN_CITY_CITY_POP_CULTURE',	        'YieldType',	'YIELD_CULTURE'),
('GOLDEN_CITY_CITY_POP_CULTURE',	        'Amount',	    0.2),
('GOLDEN_CITY_CITY_POP_PRODUCTION',	        'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_CITY_CITY_POP_PRODUCTION',	        'Amount',	    0.2),
('GOLDEN_CITY_METROPOLIS_POP_SCIENCE',	    'YieldType',	'YIELD_SCIENCE'),
('GOLDEN_CITY_METROPOLIS_POP_SCIENCE',	    'Amount',	    0.2),
('GOLDEN_CITY_METROPOLIS_POP_CULTURE',	    'YieldType',	'YIELD_CULTURE'),
('GOLDEN_CITY_METROPOLIS_POP_CULTURE',	    'Amount',	    0.2),
('GOLDEN_CITY_METROPOLIS_POP_PRODUCTION',	'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_CITY_METROPOLIS_POP_PRODUCTION',	'Amount',	    0.2);


