-- GoldenAge_Buildings_Expansion_Aqueduct
-- Author: Flactine
-- DateCreated: 5/12/2025 8:22:24 PM
--------------------------------------------------------------
INSERT OR REPLACE INTO Types
(Type,							Kind)	
VALUES
('BUILDING_GA_RESERVOIR',		'KIND_BUILDING'),
('BUILDING_GA_IRRIGATION_HUB',	'KIND_BUILDING'),
('BUILDING_GA_WATERWORKS',		'KIND_BUILDING');

INSERT OR REPLACE INTO Buildings
(BuildingType,					Name,									Description,										PrereqTech,				PrereqCivic,	Cost,	PrereqDistrict,			PurChaseYield,		Maintenance,	Housing,	AdvisorType)
VALUES                                                                          
('BUILDING_GA_RESERVOIR',		'LOC_BUILDING_GA_RESERVOIR_NAME',		'LOC_BUILDING_GA_RESERVOIR_DESCRIPTION',			'TECH_ENGINEERING',		Null,			100,	'DISTRICT_AQUEDUCT',	'YIELD_GOLD',		1,				2,			'ADVISOR_GENERIC'),
('BUILDING_GA_IRRIGATION_HUB',	'LOC_BUILDING_GA_IRRIGATION_HUB_NAME',	'LOC_BUILDING_GA_IRRIGATION_HUB_DESCRIPTION',		'TECH_BUTTRESS',		Null,			200,	'DISTRICT_AQUEDUCT',	'YIELD_GOLD',		2,				5,			'ADVISOR_GENERIC'),
('BUILDING_GA_WATERWORKS',		'LOC_BUILDING_GA_WATERWORKS_NAME',		'LOC_BUILDING_GA_WATERWORKS_DESCRIPTION',			'TECH_CHEMISTRY',		Null,			300,	'DISTRICT_AQUEDUCT',	'YIELD_GOLD',		3,				7,			'ADVISOR_GENERIC');

INSERT OR REPLACE INTO BuildingPrereqs
(Building,						PrereqBuilding)	
VALUES
('BUILDING_GA_IRRIGATION_HUB',	'BUILDING_GA_RESERVOIR'),
('BUILDING_GA_WATERWORKS',		'BUILDING_GA_IRRIGATION_HUB');

INSERT OR REPLACE INTO Buildings_XP2
(BuildingType,				RequiredPower)	
VALUES
('BUILDING_GA_WATERWORKS',	2);

INSERT OR REPLACE INTO Building_YieldChanges
(BuildingType,					YieldType,				YieldChange)	
VALUES
('BUILDING_GA_RESERVOIR',		'YIELD_FOOD',			1),
('BUILDING_GA_IRRIGATION_HUB',	'YIELD_FOOD',			2),
('BUILDING_GA_WATERWORKS',		'YIELD_PRODUCTION',		2);

INSERT INTO Building_YieldChangesBonusWithPower	
(BuildingType,				YieldType,				YieldChange)
VALUES
('BUILDING_GA_WATERWORKS',	'YIELD_PRODUCTION',		3);

INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,					ModifierId)	
VALUES
('BUILDING_GA_RESERVOIR',		'GOLDEN_RESERVOIR_POPULATION_GROWTH'),
('BUILDING_GA_IRRIGATION_HUB',	'GOLDEN_IRRIGATION_HUB_POPULATION_GROWTH'),
('BUILDING_GA_IRRIGATION_HUB',	'GOLDEN_IRRIGATION_HUB_FARM_FOOD'),
('BUILDING_GA_IRRIGATION_HUB',	'GOLDEN_IRRIGATION_HUB_FARM_FOOD_EXTRA'),
('BUILDING_GA_IRRIGATION_HUB',	'GOLDEN_IRRIGATION_HUB_PLANTATION_FOOD'),
('BUILDING_GA_IRRIGATION_HUB',	'GOLDEN_IRRIGATION_HUB_PLANTATION_FOOD_EXTRA'),
('BUILDING_GA_IRRIGATION_HUB',	'GOLDEN_WATERWORKS_POPULATION_GROWTH'),
('BUILDING_GA_WATERWORKS',		'GOLDEN_WATERWORKS_IZONE_PRODUCTION');

INSERT OR REPLACE INTO Modifiers 
(ModifierId, 									ModifierType,										SubjectRequirementSetId) 
VALUES 
('GOLDEN_RESERVOIR_POPULATION_GROWTH',			'MODIFIER_SINGLE_CITY_ADJUST_CITY_GROWTH',			Null),
('GOLDEN_IRRIGATION_HUB_POPULATION_GROWTH',		'MODIFIER_SINGLE_CITY_ADJUST_CITY_GROWTH',			Null),
('GOLDEN_WATERWORKS_POPULATION_GROWTH',			'MODIFIER_SINGLE_CITY_ADJUST_CITY_GROWTH',			Null),
('GOLDEN_IRRIGATION_HUB_FARM_FOOD',				'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',				Null),
('GOLDEN_IRRIGATION_HUB_FARM_FOOD_EXTRA',		'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',				Null),
('GOLDEN_IRRIGATION_HUB_FARM_FOOD_MOD',			'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'REQSET_GABE_PLOT_HAS_FARM'),
('GOLDEN_IRRIGATION_HUB_FARM_FOOD_EXTRA_MOD',	'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'REQSET_GABE_PLOT_HAS_FARM_AND_NEAR_AQUEDUCT'),

('GOLDEN_IRRIGATION_HUB_PLANTATION_FOOD',			'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',				Null),
('GOLDEN_IRRIGATION_HUB_PLANTATION_FOOD_EXTRA',		'MODIFIER_SINGLE_CITY_ATTACH_MODIFIER',				Null),
('GOLDEN_IRRIGATION_HUB_PLANTATION_FOOD_MOD',		'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'REQSET_GABE_PLOT_HAS_PLANTATION'),
('GOLDEN_IRRIGATION_HUB_PLANTATION_FOOD_EXTRA_MOD',	'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'REQSET_GABE_PLOT_HAS_PLANTATION_AND_NEAR_AQUEDUCT'),

('GOLDEN_WATERWORKS_IZONE_PRODUCTION',			'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_MODIFIER',	'REQSET_GABE_PLOT_IS_IZONE_NEAR_WATERWORKS');

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId, 									Name, 			Value) 
VALUES 
('GOLDEN_RESERVOIR_POPULATION_GROWTH',			'Amount',		10),
('GOLDEN_IRRIGATION_HUB_POPULATION_GROWTH',		'Amount',		25),
('GOLDEN_WATERWORKS_POPULATION_GROWTH',			'Amount',		50),

('GOLDEN_IRRIGATION_HUB_FARM_FOOD',				'ModifierId',	'GOLDEN_IRRIGATION_HUB_FARM_FOOD_MOD'), 
('GOLDEN_IRRIGATION_HUB_FARM_FOOD_EXTRA',		'ModifierId',	'GOLDEN_IRRIGATION_HUB_FARM_FOOD_EXTRA_MOD'), 
('GOLDEN_IRRIGATION_HUB_FARM_FOOD_MOD',			'YieldType',	'YIELD_FOOD'),
('GOLDEN_IRRIGATION_HUB_FARM_FOOD_MOD',			'Amount',		1),
('GOLDEN_IRRIGATION_HUB_FARM_FOOD_EXTRA_MOD',	'YieldType',	'YIELD_FOOD'),
('GOLDEN_IRRIGATION_HUB_FARM_FOOD_EXTRA_MOD',	'Amount',		2),

('GOLDEN_IRRIGATION_HUB_PLANTATION_FOOD',				'ModifierId',	'GOLDEN_IRRIGATION_HUB_PLANTATION_FOOD_MOD'), 
('GOLDEN_IRRIGATION_HUB_PLANTATION_FOOD_EXTRA',			'ModifierId',	'GOLDEN_IRRIGATION_HUB_PLANTATION_FOOD_EXTRA_MOD'), 
('GOLDEN_IRRIGATION_HUB_PLANTATION_FOOD_MOD',			'YieldType',	'YIELD_FOOD'),
('GOLDEN_IRRIGATION_HUB_PLANTATION_FOOD_MOD',			'Amount',		1),
('GOLDEN_IRRIGATION_HUB_PLANTATION_FOOD_EXTRA_MOD',		'YieldType',	'YIELD_FOOD'),
('GOLDEN_IRRIGATION_HUB_PLANTATION_FOOD_EXTRA_MOD',		'Amount',		2),

('GOLDEN_WATERWORKS_IZONE_PRODUCTION',			'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_WATERWORKS_IZONE_PRODUCTION',			'Amount',		200);

INSERT OR REPLACE INTO RequirementSets
(RequirementSetId,										RequirementSetType)	
VALUES
('REQSET_GABE_PLOT_HAS_FARM',							'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_PLOT_HAS_FARM_AND_NEAR_AQUEDUCT',			'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_PLOT_HAS_PLANTATION',						'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_PLOT_HAS_PLANTATION_AND_NEAR_AQUEDUCT',	'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_PLOT_IS_IZONE_NEAR_WATERWORKS',			'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements 
(RequirementSetId,										RequirementId) 
VALUES
('REQSET_GABE_PLOT_HAS_FARM',							'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_FARM'),
('REQSET_GABE_PLOT_HAS_FARM_AND_NEAR_AQUEDUCT',			'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_FARM'),
('REQSET_GABE_PLOT_HAS_FARM_AND_NEAR_AQUEDUCT',			'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_AQUEDUCT'),
('REQSET_GABE_PLOT_HAS_PLANTATION',						'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_PLANTATION'),
('REQSET_GABE_PLOT_HAS_PLANTATION_AND_NEAR_AQUEDUCT',	'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_PLANTATION'),
('REQSET_GABE_PLOT_HAS_PLANTATION_AND_NEAR_AQUEDUCT',	'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_AQUEDUCT'),
('REQSET_GABE_PLOT_IS_IZONE_NEAR_WATERWORKS',			'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_AQUEDUCT'),
('REQSET_GABE_PLOT_IS_IZONE_NEAR_WATERWORKS',			'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_INDUSTRIAL_ZONE');
