INSERT OR REPLACE INTO Types (Type,		Kind)
('GREAT_PERSON_INDIVIDUAL_FAN_LI',		'KIND_GREAT_PERSON_INDIVIDUAL'),
('GREAT_PERSON_INDIVIDUAL_WIDOW_QING',	'KIND_GREAT_PERSON_INDIVIDUAL');


INSERT OR REPLACE INTO GreatPersonIndividuals (GreatPersonIndividualType,	Name,		GreatPersonClassType,	EraType,	Gender,	ActionCharges,	ActionRequiresCompletedDistrictType) VALUES
('GREAT_PERSON_INDIVIDUAL_FAN_LI',		'LOC_GREAT_PERSON_INDIVIDUAL_FAN_LI_NAME',		'GREAT_PERSON_CLASS_MERCHANT',	'ERA_CLASSICAL',	'M',	2, 'DISTRICT_COMMERCIAL_HUB' ),
('GREAT_PERSON_INDIVIDUAL_WIDOW_QING',	'LOC_GREAT_PERSON_INDIVIDUAL_WIDOW_QING_NAME',	'GREAT_PERSON_CLASS_MERCHANT',	'ERA_CLASSICAL',	'W',	1, 'DISTRICT_COMMERCIAL_HUB' ),

INSERT OR REPLACE INTO GreatPersonIndividualActionModifiers (GreatPersonIndividualType, ModifierId,AttachmentTargetType) VALUES 
('GREAT_PERSON_INDIVIDUAL_FAN_LI', 		'GREATPERSON_FANLI_GOLD',		'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_WIDOW_QING', 	'GREATPERSON_QING_IRON',		'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE');


INSERT OR REPLACE INTO Modifiers (ModifierId, 			ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('GREATPERSON_FANLI_GOLD', 	'MODIFIER_PLAYER_GRANT_YIELD', 							1, 1, 0, NULL, NULL),
('GREATPERSON_QING_IRON', 	'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION', 1, 1, 0, NULL, NULL);


INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('GREATPERSON_FANLI_GOLD', 		'YieldType', 	'YIELD_GOLD'),
('GREATPERSON_FANLI_GOLD', 		'Amount', 		2000),
('GREATPERSON_QING_IRON', 		'ResourceType', 'RESOURCE_IRON'),
('GREATPERSON_QING_IRON', 		'Amount', 		4);

UPDATE ModifierArguments SET Type = 'ScaleByGameSpeed' WHERE ModifierId = 'GREATPERSON_FANLI_GOLD' AND Name = 'Amount';
