INSERT OR REPLACE INTO Types
(Type,								Kind)	
VALUES
('BUILDING_GA_ROLLER_COASTER',		'KIND_BUILDING'),
('BUILDING_GA_CAROUSEL',			'KIND_BUILDING'),
('BUILDING_GA_POLARIA',				'KIND_BUILDING');

INSERT OR REPLACE INTO Buildings
(
    BuildingType,
    Name,
    Description,
    PrereqCivic,
    PrereqDistrict,
    PurchaseYield,
    Cost,
    Maintenance,
    Entertainment,
    RegionalRange,
    AdvisorType
)
SELECT
    'BUILDING_GA_ROLLER_COASTER',
    'LOC_BUILDING_GA_ROLLER_COASTER_NAME',
    'LOC_BUILDING_GA_ROLLER_COASTER_DESCRIPTION',
    PrereqCivic,
    PrereqDistrict,
    PurchaseYield,
    Cost,
    Maintenance,
    Entertainment,
    RegionalRange,
    AdvisorType
FROM Buildings
WHERE BuildingType = 'BUILDING_FERRIS_WHEEL'

UNION ALL
SELECT
    'BUILDING_GA_CAROUSEL',
    'LOC_BUILDING_GA_CAROUSEL_NAME',
    'LOC_BUILDING_GA_CAROUSEL_DESCRIPTION',
    PrereqCivic,
    PrereqDistrict,
    PurchaseYield,
    Cost,
    Maintenance,
    Entertainment,
    RegionalRange,
    AdvisorType
FROM Buildings
WHERE BuildingType = 'BUILDING_FERRIS_WHEEL'

UNION ALL
SELECT
    'BUILDING_GA_POLARIA',
    'LOC_BUILDING_GA_POLARIA_NAME',
    'LOC_BUILDING_GA_POLARIA_DESCRIPTION',
    PrereqCivic,
    PrereqDistrict,
    PurchaseYield,
    Cost,
    Maintenance,
    Entertainment,
    RegionalRange,
    AdvisorType
FROM Buildings
WHERE BuildingType = 'BUILDING_AQUARIUM';

UPDATE Buildings 
SET Description = 'LOC_BUILDING_FERRIS_WHEEL_GABE_DESCRIPTION'
WHERE BuildingType = 'BUILDING_FERRIS_WHEEL';

UPDATE Buildings 
SET Description = 'LOC_BUILDING_AQUARIUM_GABE_DESCRIPTION'
WHERE BuildingType = 'BUILDING_AQUARIUM';

INSERT OR REPLACE INTO BuildingPrereqs
(Building,						PrereqBuilding)	
VALUES
('BUILDING_AQUARIUM',			'BUILDING_GA_ROLLER_COASTER'),
('BUILDING_AQUARIUM',			'BUILDING_GA_CAROUSEL'),
('BUILDING_GA_POLARIA',			'BUILDING_FERRIS_WHEEL'),
('BUILDING_GA_POLARIA',			'BUILDING_GA_ROLLER_COASTER'),
('BUILDING_GA_POLARIA',			'BUILDING_GA_CAROUSEL'),
('BUILDING_AQUATICS_CENTER',	'BUILDING_GA_POLARIA');

INSERT OR REPLACE INTO MutuallyExclusiveBuildings
(Building,							MutuallyExclusiveBuilding)	
VALUES
('BUILDING_FERRIS_WHEEL',			'BUILDING_GA_ROLLER_COASTER'),
('BUILDING_FERRIS_WHEEL',			'BUILDING_GA_CAROUSEL'),
('BUILDING_GA_ROLLER_COASTER',		'BUILDING_FERRIS_WHEEL'),
('BUILDING_GA_ROLLER_COASTER',		'BUILDING_GA_CAROUSEL'),
('BUILDING_GA_CAROUSEL',			'BUILDING_FERRIS_WHEEL'),
('BUILDING_GA_CAROUSEL',			'BUILDING_GA_ROLLER_COASTER'),
('BUILDING_AQUARIUM',				'BUILDING_GA_POLARIA'),
('BUILDING_GA_POLARIA',				'BUILDING_AQUARIUM');

INSERT OR REPLACE INTO Building_YieldChanges
(BuildingType,					YieldType,	YieldChange)
SELECT
'BUILDING_GA_ROLLER_COASTER',	YieldType,	YieldChange
FROM Building_YieldChanges WHERE BuildingType = 'BUILDING_FERRIS_WHEEL'
UNION ALL
SELECT
'BUILDING_GA_CAROUSEL',			YieldType,	YieldChange
FROM Building_YieldChanges WHERE BuildingType = 'BUILDING_FERRIS_WHEEL'
UNION ALL
SELECT
'BUILDING_GA_POLARIA',			YieldType,	YieldChange
FROM Building_YieldChanges WHERE BuildingType = 'BUILDING_AQUARIUM';

INSERT OR REPLACE INTO Buildings_XP2
(BuildingType,					RequiredPower,	EntertainmentBonusWithPower)
SELECT
'BUILDING_GA_ROLLER_COASTER',	RequiredPower,	EntertainmentBonusWithPower
FROM Buildings_XP2 WHERE BuildingType = 'BUILDING_FERRIS_WHEEL'
UNION ALL
SELECT
'BUILDING_GA_CAROUSEL',			RequiredPower,	EntertainmentBonusWithPower
FROM Buildings_XP2 WHERE BuildingType = 'BUILDING_FERRIS_WHEEL'
UNION ALL
SELECT
'BUILDING_GA_POLARIA',			RequiredPower,	EntertainmentBonusWithPower
FROM Buildings_XP2 WHERE BuildingType = 'BUILDING_AQUARIUM';

INSERT OR REPLACE INTO Building_TourismBombs_XP2
(BuildingType,					TourismBombValue)
SELECT
'BUILDING_GA_ROLLER_COASTER',	TourismBombValue
FROM Building_TourismBombs_XP2 WHERE BuildingType = 'BUILDING_FERRIS_WHEEL'
UNION ALL
SELECT
'BUILDING_GA_CAROUSEL',			TourismBombValue
FROM Building_TourismBombs_XP2 WHERE BuildingType = 'BUILDING_FERRIS_WHEEL'
UNION ALL
SELECT
'BUILDING_GA_POLARIA',			TourismBombValue
FROM Building_TourismBombs_XP2 WHERE BuildingType = 'BUILDING_AQUARIUM';

INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,					ModifierId)
SELECT
'BUILDING_GA_ROLLER_COASTER',	ModifierId
FROM BuildingModifiers WHERE ModifierId = 'GOLDEN_FERRIS_WHEEL_TOURISM'
UNION ALL
SELECT
'BUILDING_GA_CAROUSEL',			ModifierId
FROM BuildingModifiers WHERE ModifierId = 'GOLDEN_FERRIS_WHEEL_TOURISM'
UNION ALL
SELECT
'BUILDING_GA_POLARIA',			ModifierId
FROM BuildingModifiers WHERE ModifierId = 'GOLDEN_AQUARIUM_TOURISM';

INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,						ModifierId)	
VALUES
('BUILDING_FERRIS_WHEEL',			'GOLDEN_FERRIS_WHEEL_EXTRA_AMENITY'),
('BUILDING_GA_ROLLER_COASTER',		'GOLDEN_ROLLER_COASTER_EXTRA_AMENITY'),
('BUILDING_GA_CAROUSEL',			'GOLDEN_CAROUSEL_EXTRA_AMENITY'),
('BUILDING_AQUARIUM',				'GOLDEN_AQUARIUM_BUILDING_SCIENCE'),
('BUILDING_AQUARIUM',				'GOLDEN_AQUARIUM_FISH_PLOT_SCIENCE'),
('BUILDING_GA_POLARIA',				'GOLDEN_GA_POLARIA_BUILDING_SCIENCE'),
('BUILDING_GA_POLARIA',				'GOLDEN_POLARIA_COLD_WATER_PLOT_SCIENCE');

INSERT OR REPLACE INTO Modifiers 
(ModifierId, 									ModifierType,									SubjectRequirementSetId) 
VALUES 
('GOLDEN_FERRIS_WHEEL_EXTRA_AMENITY',			'MODIFIER_SINGLE_CITY_ADJUST_ENTERTAINMENT',	'REQSET_GABE_CITY_HAS_NATURAL_OR_BUILDING_WONDER'),
('GOLDEN_ROLLER_COASTER_EXTRA_AMENITY',			'MODIFIER_SINGLE_CITY_ADJUST_ENTERTAINMENT',	'REQSET_GABE_CITY_HAS_5_HILLS_OR_MOUNTAIN_TILES'),
('GOLDEN_CAROUSEL_EXTRA_AMENITY',				'MODIFIER_SINGLE_CITY_ADJUST_ENTERTAINMENT',	'REQSET_GABE_CITY_HAS_4_SPECIALTY_DISTRICTS'),
('GOLDEN_AQUARIUM_BUILDING_SCIENCE',			'MODIFIER_BUILDING_YIELD_CHANGE',				'REQSET_GABE_CITY_HAS_BUILDING_RESEARCH_LAB'),
('GOLDEN_AQUARIUM_FISH_PLOT_SCIENCE',			'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',	'REQSET_GABE_PLOT_IS_FISH'),
('GOLDEN_GA_POLARIA_BUILDING_SCIENCE',			'MODIFIER_BUILDING_YIELD_CHANGE',				'REQSET_GABE_CITY_HAS_BUILDING_RESEARCH_LAB'),
('GOLDEN_POLARIA_COLD_WATER_PLOT_SCIENCE',		'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',	'REQSET_GABE_PLOT_IS_COLD_WATER');

INSERT OR REPLACE INTO ModifierArguments 
(ModifierId, 								Name, 				Value) 
VALUES 
('GOLDEN_FERRIS_WHEEL_EXTRA_AMENITY',		'Amount',			2), 
('GOLDEN_ROLLER_COASTER_EXTRA_AMENITY',		'Amount',			2), 
('GOLDEN_CAROUSEL_EXTRA_AMENITY',			'Amount',			2),
('GOLDEN_AQUARIUM_BUILDING_SCIENCE',		'BuildingType',		'BUILDING_AQUARIUM'),
('GOLDEN_AQUARIUM_BUILDING_SCIENCE',		'YieldType',		'YIELD_SCIENCE'),
('GOLDEN_AQUARIUM_BUILDING_SCIENCE',		'Amount',			1),
('GOLDEN_AQUARIUM_FISH_PLOT_SCIENCE',		'YieldType',		'YIELD_SCIENCE'),
('GOLDEN_AQUARIUM_FISH_PLOT_SCIENCE',		'Amount',			1),
('GOLDEN_GA_POLARIA_BUILDING_SCIENCE',		'BuildingType',		'BUILDING_GA_POLARIA'),
('GOLDEN_GA_POLARIA_BUILDING_SCIENCE',		'YieldType',		'YIELD_SCIENCE'),
('GOLDEN_GA_POLARIA_BUILDING_SCIENCE',		'Amount',			1),
('GOLDEN_POLARIA_COLD_WATER_PLOT_SCIENCE',	'YieldType',		'YIELD_SCIENCE'),
('GOLDEN_POLARIA_COLD_WATER_PLOT_SCIENCE',	'Amount',			1);

INSERT OR REPLACE INTO RequirementSets
(RequirementSetId,										RequirementSetType)	
VALUES
('REQSET_GABE_CITY_HAS_NATURAL_OR_BUILDING_WONDER',		'REQUIREMENTSET_TEST_ANY'),
('REQSET_GABE_CITY_HAS_5_HILLS_OR_MOUNTAIN_TILES',		'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_PLOT_IS_HILLS_OR_MOUNTAINS',				'REQUIREMENTSET_TEST_ANY'),
('REQSET_GABE_CITY_HAS_4_SPECIALTY_DISTRICTS',			'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_PLOT_IS_COLD_WATER',						'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_PLOT_IS_COLD_ADJACENT',					'REQUIREMENTSET_TEST_ANY');

INSERT INTO RequirementSetRequirements
(RequirementSetId,									RequirementId)
VALUES
('REQSET_GABE_CITY_HAS_NATURAL_OR_BUILDING_WONDER',	'REQUIRES_CITY_HAS_WONDER'),
('REQSET_GABE_CITY_HAS_5_HILLS_OR_MOUNTAIN_TILES',	'REQ_GABE_CITY_HAS_5_HILLS_PLOT'),
('REQSET_GABE_PLOT_IS_HILLS_OR_MOUNTAINS',			'PLOT_IS_HILLS_REQUIREMENT'),
('REQSET_GABE_PLOT_IS_HILLS_OR_MOUNTAINS',			'PLOT_IS_MOUNTAIN'),
('REQSET_GABE_CITY_HAS_4_SPECIALTY_DISTRICTS',		'GOLDEN_REQUIRES_CITY_HAS_4_SPECIALTY_DISTRICTS'),
('REQSET_GABE_PLOT_IS_COLD_WATER',					'REQUIRES_PLOT_IS_COAST'),
('REQSET_GABE_PLOT_IS_COLD_WATER',					'REQ_GABE_PLOT_IS_COLD_ADJACENT_REQSET'),
('REQSET_GABE_PLOT_IS_COLD_ADJACENT',				'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_TERRAIN_SNOW'),
('REQSET_GABE_PLOT_IS_COLD_ADJACENT',				'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_TERRAIN_SNOW_HILLS'),
('REQSET_GABE_PLOT_IS_COLD_ADJACENT',				'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_TERRAIN_SNOW_MOUNTAIN'),
('REQSET_GABE_PLOT_IS_COLD_ADJACENT',				'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_TERRAIN_TUNDRA'),
('REQSET_GABE_PLOT_IS_COLD_ADJACENT',				'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_TERRAIN_TUNDRA_HILLS'),
('REQSET_GABE_PLOT_IS_COLD_ADJACENT',				'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_TERRAIN_TUNDRA_MOUNTAIN'),
('REQSET_GABE_PLOT_IS_COLD_ADJACENT',				'GOLDEN_REQUIRES_PLOT_IS_ICE_ADJACENT');

INSERT INTO RequirementSetRequirements
(RequirementSetId,									RequirementId)
SELECT
'REQSET_GABE_CITY_HAS_NATURAL_OR_BUILDING_WONDER',	'GOLDEN_REQUIRES_CITY_HAS_'||FeatureType
FROM Features WHERE NaturalWonder = 1;

INSERT INTO Requirements
(RequirementId,								RequirementType)
VALUES
('REQ_GABE_CITY_HAS_5_HILLS_PLOT',			'REQUIREMENT_COLLECTION_COUNT_ATLEAST'),
('REQ_GABE_PLOT_IS_COLD_ADJACENT_REQSET',	'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT INTO RequirementArguments
(RequirementId,								Name,					Value)
VALUES
('REQ_GABE_CITY_HAS_5_HILLS_PLOT',			'CollectionType',		'COLLECTION_CITY_PLOT_YIELDS'),
('REQ_GABE_CITY_HAS_5_HILLS_PLOT',			'Count',				5),
('REQ_GABE_CITY_HAS_5_HILLS_PLOT',			'RequirementSetId',		'REQSET_GABE_PLOT_IS_HILLS_OR_MOUNTAINS'),
('REQ_GABE_PLOT_IS_COLD_ADJACENT_REQSET',	'RequirementSetId',		'REQSET_GABE_PLOT_IS_COLD_ADJACENT');