UPDATE Technologies SET  Cost="50" 
WHERE TechnologyType="TECH_ASTROLOGY";
UPDATE Technologies SET  Cost="25" 
WHERE TechnologyType="TECH_SAILING";
UPDATE Technologies SET  Cost="25",UITreeRow=2 
WHERE TechnologyType="TECH_BRONZE_WORKING";
UPDATE Technologies SET  Cost="50",UITreeRow=3 
WHERE TechnologyType="TECH_MASONRY";
UPDATE Technologies SET  Cost="50",UITreeRow=1 
WHERE TechnologyType="TECH_THE_WHEEL";
UPDATE Technologies SET  Description="LOC_TECH_MILITARY_TACTICS_DESCRIPTION",UITreeRow=1 
WHERE TechnologyType="TECH_MILITARY_TACTICS";	
UPDATE Technologies SET  Description="LOC_TECH_APPRENTICESHIP_DESCRIPTION",UITreeRow=-1
WHERE TechnologyType="TECH_APPRENTICESHIP";	
UPDATE Technologies SET  UITreeRow=-3 
WHERE TechnologyType="TECH_CELESTIAL_NAVIGATION";
UPDATE Technologies SET  Description="LOC_TECH_IRON_WORKING_DESCRIPTION",UITreeRow=2 
WHERE TechnologyType="TECH_IRON_WORKING";
UPDATE Technologies SET  Description="LOC_TECH_CONSTRUCTION_DESCRIPTION",UITreeRow=3 
WHERE TechnologyType="TECH_CONSTRUCTION";
UPDATE Technologies SET  Cost="120",Description="LOC_TECH_ENGINEERING_DESCRIPTION",UITreeRow=3 
WHERE TechnologyType="TECH_ENGINEERING";
UPDATE Technologies SET  Cost="200",Description="LOC_TECH_HORSEBACK_RIDING_DESCRIPTION" 
WHERE TechnologyType="TECH_HORSEBACK_RIDING";
UPDATE Technologies SET  UITreeRow=2,Description="LOC_TECH_MACHINERY_DESCRIPTION" 
WHERE TechnologyType="TECH_MACHINERY";
UPDATE Technologies SET  Description="LOC_TECH_CURRENCY_DESCRIPTION",UITreeRow=-1
WHERE TechnologyType="TECH_CURRENCY";
UPDATE Technologies SET  UITreeRow=-1
WHERE TechnologyType="TECH_PRINTING";
UPDATE Technologies SET  Description="LOC_TECH_BUTTRESS_DESCRIPTION",Cost="390",UITreeRow=-3 
WHERE TechnologyType="TECH_BUTTRESS";
UPDATE Technologies SET  Cost="300",Description="LOC_TECH_CASTLES_DESCRIPTION" 
WHERE TechnologyType="TECH_CASTLES";
UPDATE Technologies SET  Description="" 
WHERE TechnologyType="TECH_ROCKETRY";
UPDATE Technologies SET  UITreeRow=2 
WHERE TechnologyType="TECH_ROBOTICS";
UPDATE Technologies SET  Cost="2155",UITreeRow=-3 
WHERE TechnologyType="TECH_STEALTH_TECHNOLOGY";
UPDATE Technologies SET  Description="LOC_TECH_NANOTECHNOLOGY_DESCRIPTION",UITreeRow=-1
WHERE TechnologyType="TECH_NANOTECHNOLOGY";
UPDATE Technologies SET  Description="LOC_TECH_GUNPOWDER_DESCRIPTION" 
WHERE TechnologyType="TECH_GUNPOWDER";
UPDATE Technologies SET  Description="LOC_TECH_METAL_CASTING_DESCRIPTION" 
WHERE TechnologyType="TECH_METAL_CASTING";
UPDATE Technologies SET  UITreeRow=-1,Description="LOC_TECH_REFINING_DESCRIPTION" 
WHERE TechnologyType="TECH_REFINING";
UPDATE Technologies SET  Description="LOC_TECH_COMPOSITES_DESCRIPTION" 
WHERE TechnologyType="TECH_COMPOSITES";
UPDATE Technologies SET  Description="LOC_TECH_LASERS_DESCRIPTION" 
WHERE TechnologyType="TECH_LASERS";
UPDATE Technologies SET  UITreeRow=1,Cost="930",Description="LOC_TECH_RIFLING_DESCRIPTION" 
WHERE TechnologyType="TECH_RIFLING";
UPDATE Technologies SET  Cost="730",Description="LOC_TECH_MASS_PRODUCTION_DESCRIPTION" 
WHERE TechnologyType="TECH_MASS_PRODUCTION";
UPDATE Technologies SET  Description="LOC_TECH_RADIO_DESCRIPTION" 
WHERE TechnologyType="TECH_RADIO";
UPDATE Technologies SET  Description="LOC_TECH_CHEMISTRY_DESCRIPTION" 
WHERE TechnologyType="TECH_CHEMISTRY";
UPDATE Technologies SET  Description="LOC_TECH_ELECTRICITY_DESCRIPTION" 
WHERE TechnologyType="TECH_ELECTRICITY";
UPDATE Technologies SET  Description="LOC_TECH_TELECOMMUNICATIONS_DESCRIPTION" 
WHERE TechnologyType="TECH_TELECOMMUNICATIONS";
UPDATE Technologies SET  Description="LOC_TECH_MILITARY_ENGINEERING_DESCRIPTION",UITreeRow=3 
WHERE TechnologyType="TECH_MILITARY_ENGINEERING";
UPDATE Technologies SET  Description="LOC_TECH_ASTRONOMY_DESCRIPTION" 
WHERE TechnologyType="TECH_ASTRONOMY";
UPDATE Technologies SET  UITreeRow=3,Description="LOC_TECH_BALLISTICS_DESCRIPTION" 
WHERE TechnologyType="TECH_BALLISTICS";
UPDATE Technologies SET  Cost="600",Description="LOC_TECH_BANKING_DESCRIPTION" 
WHERE TechnologyType="TECH_BANKING";
UPDATE Technologies SET  Description="LOC_TECH_ECONOMICS_DESCRIPTION" 
WHERE TechnologyType="TECH_ECONOMICS";
UPDATE Technologies SET  Cost="600", Description="LOC_TECH_SIEGE_TACTICS_DESCRIPTION" 
WHERE TechnologyType="TECH_SIEGE_TACTICS";
UPDATE Technologies SET  UITreeRow=-1,Description="LOC_TECH_ADVANCED_FLIGHT_DESCRIPTION" 
WHERE TechnologyType="TECH_ADVANCED_FLIGHT";
UPDATE Technologies SET  Cost="1070",UITreeRow=2,Description="LOC_TECH_MILITARY_SCIENCE_DESCRIPTION" 
WHERE TechnologyType="TECH_MILITARY_SCIENCE";
UPDATE Technologies SET  Cost="25",UITreeRow=-1
WHERE TechnologyType="TECH_ARCHERY";
UPDATE Technologies SET  UITreeRow=2 
WHERE TechnologyType="TECH_STEEL";
UPDATE Technologies SET  Cost="1660" 
WHERE TechnologyType="TECH_ROCKETRY";
UPDATE Technologies SET  Description="LOC_TECH_NUCLEAR_FUSION_DESCRIPTION" 
WHERE TechnologyType="TECH_NUCLEAR_FUSION";
UPDATE Technologies SET  Description="LOC_TECH_STIRRUPS_DESCRIPTION" 
WHERE TechnologyType="TECH_STIRRUPS";
UPDATE Technologies SET  Description="LOC_TECH_GUIDANCE_SYSTEMS_DESCRIPTION" 
WHERE TechnologyType="TECH_GUIDANCE_SYSTEMS";
UPDATE Technologies SET  Description="LOC_TECH_COMBINED_ARMS_DESCRIPTION" 
WHERE TechnologyType="TECH_COMBINED_ARMS";
UPDATE Technologies SET  Cost="2200",UITreeRow=3 
WHERE TechnologyType="TECH_OFFWORLD_MISSION";
UPDATE Technologies SET  Description="LOC_TECH_EDUCATION_DESCRIPTION" 
WHERE TechnologyType="TECH_EDUCATION";

UPDATE Technologies_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE TechnologyType="TECH_FUTURE_TECH";
UPDATE Technologies_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE TechnologyType="TECH_SEASTEADS";
UPDATE Technologies_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE TechnologyType="TECH_ADVANCED_AI";
UPDATE Technologies_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE TechnologyType="TECH_ADVANCED_POWER_CELLS";
UPDATE Technologies_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE TechnologyType="TECH_CYBERNETICS";
UPDATE Technologies_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE TechnologyType="TECH_SMART_MATERIALS";
UPDATE Technologies_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE TechnologyType="TECH_PREDICTIVE_SYSTEMS";
UPDATE Technologies_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE TechnologyType="TECH_OFFWORLD_MISSION";

DELETE FROM TechnologyRandomCosts WHERE TechnologyType="TECH_SEASTEADS";
DELETE FROM TechnologyRandomCosts WHERE TechnologyType="TECH_ADVANCED_AI";
DELETE FROM TechnologyRandomCosts WHERE TechnologyType="TECH_ADVANCED_POWER_CELLS";
DELETE FROM TechnologyRandomCosts WHERE TechnologyType="TECH_CYBERNETICS";
DELETE FROM TechnologyRandomCosts WHERE TechnologyType="TECH_SMART_MATERIALS";
DELETE FROM TechnologyRandomCosts WHERE TechnologyType="TECH_PREDICTIVE_SYSTEMS";

DELETE FROM TechnologyPrereqs WHERE Technology="TECH_ARCHERY" AND PrereqTech="TECH_ANIMAL_HUSBANDRY";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_HORSEBACK_RIDING";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_IRRIGATION" AND PrereqTech="TECH_POTTERY";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_CELESTIAL_NAVIGATION" AND PrereqTech="TECH_ASTROLOGY";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_MACHINERY" AND PrereqTech="TECH_ENGINEERING";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_SIEGE_TACTICS" AND PrereqTech="TECH_CASTLES";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_MASS_PRODUCTION";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_RADIO" AND PrereqTech="TECH_STEAM_POWER";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_CONSTRUCTION";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_GUNPOWDER" AND PrereqTech="TECH_APPRENTICESHIP";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_APPRENTICESHIP" AND PrereqTech="TECH_CURRENCY";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_EDUCATION" AND PrereqTech="TECH_MATHEMATICS";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_BANKING" AND PrereqTech="TECH_STIRRUPS";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_ECONOMICS" AND PrereqTech="TECH_METAL_CASTING";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_ECONOMICS" AND PrereqTech="TECH_SCIENTIFIC_THEORY";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_FLIGHT" AND PrereqTech="TECH_SCIENTIFIC_THEORY";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_STIRRUPS" AND PrereqTech="TECH_HORSEBACK_RIDING";	
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_NANOTECHNOLOGY" AND PrereqTech="TECH_COMPOSITES";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_ROBOTICS" AND PrereqTech="TECH_SATELLITES";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_STEALTH_TECHNOLOGY" AND PrereqTech="TECH_SYNTHETIC_MATERIALS";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_ROBOTICS" AND PrereqTech="TECH_COMPUTERS";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_COMBINED_ARMS" AND PrereqTech="TECH_STEEL";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_BALLISTICS" AND PrereqTech="TECH_METAL_CASTING";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_RIFLING" AND PrereqTech="TECH_BALLISTICS";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_MILITARY_SCIENCE" AND PrereqTech="TECH_PRINTING";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_MILITARY_SCIENCE" AND PrereqTech="TECH_SIEGE_TACTICS";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_RIFLING" AND PrereqTech="TECH_MILITARY_SCIENCE";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_STEEL" AND PrereqTech="TECH_RIFLING";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_ADVANCED_BALLISTICS" AND PrereqTech="TECH_STEEL";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_SATELLITES" AND PrereqTech="TECH_ADVANCED_FLIGHT";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_ROCKETRY";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_NUCLEAR_FISSION" AND PrereqTech="TECH_ADVANCED_BALLISTICS";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_GUIDANCE_SYSTEMS" AND PrereqTech="TECH_ROCKETRY";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_BRONZE_WORKING" AND PrereqTech="TECH_MINING";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_REFINING" AND PrereqTech="TECH_RIFLING";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_CHEMISTRY" AND PrereqTech="TECH_SANITATION";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_CHEMISTRY" AND PrereqTech="TECH_REPLACEABLE_PARTS";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_COMBUSTION" AND PrereqTech="TECH_REFINING";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_THE_WHEEL" AND PrereqTech="TECH_MINING";
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_ENGINEERING" AND PrereqTech="TECH_THE_WHEEL"; 
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_SHIPBUILDING"; 
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_MILITARY_ENGINEERING" AND PrereqTech="TECH_CONSTRUCTION"; 
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_MILITARY_TACTICS" AND PrereqTech="TECH_MATHEMATICS"; 
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_PRINTING" AND PrereqTech="TECH_MACHINERY"; 
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_ASTRONOMY" AND PrereqTech="TECH_EDUCATION"; 
DELETE FROM TechnologyPrereqs WHERE Technology="TECH_COMPUTERS" AND PrereqTech="TECH_RADIO"; 

INSERT OR REPLACE INTO TechnologyPrereqs
(Technology , PrereqTech) VALUES
("TECH_SATELLITES" , "TECH_COMPUTERS" ),
("TECH_ROCKETRY" , "TECH_ADVANCED_BALLISTICS" ),
("TECH_COMPUTERS" , "TECH_ADVANCED_FLIGHT" ),
("TECH_COMBUSTION" , "TECH_REPLACEABLE_PARTS" ),
("TECH_ASTRONOMY" , "TECH_PRINTING" ),
("TECH_PRINTING" , "TECH_EDUCATION" ),
("TECH_STIRRUPS" , "TECH_MILITARY_TACTICS" ),
("TECH_IRRIGATION" , "TECH_ARCHERY" ),
("TECH_CURRENCY" , "TECH_IRRIGATION" ),
("TECH_MATHEMATICS" , "TECH_ASTROLOGY" ),
("TECH_APPRENTICESHIP" , "TECH_MATHEMATICS" ),
("TECH_MILITARY_TACTICS" , "TECH_IRON_WORKING" ),
("TECH_MILITARY_TACTICS" , "TECH_HORSEBACK_RIDING" ),
("TECH_SIEGE_TACTICS" , "TECH_MILITARY_ENGINEERING" ),
("TECH_MILITARY_ENGINEERING" , "TECH_CASTLES" ),
("TECH_MILITARY_ENGINEERING" , "TECH_MACHINERY" ),
("TECH_ECONOMICS" , "TECH_BANKING" ),
("TECH_ECONOMICS" , "TECH_RIFLING" ),
("TECH_EDUCATION" , "TECH_SHIPBUILDING" ),
("TECH_NANOTECHNOLOGY" , "TECH_SATELLITES" ),
("TECH_NANOTECHNOLOGY" , "TECH_GUIDANCE_SYSTEMS" ),
("TECH_NUCLEAR_FUSION" , "TECH_GUIDANCE_SYSTEMS" ),
("TECH_ROBOTICS" , "TECH_COMPOSITES" ),
("TECH_STEALTH_TECHNOLOGY" , "TECH_TELECOMMUNICATIONS" ),
("TECH_STEALTH_TECHNOLOGY" , "TECH_SATELLITES" ),
("TECH_COMBINED_ARMS" , "TECH_REPLACEABLE_PARTS" ),
("TECH_BALLISTICS" , "TECH_SIEGE_TACTICS" ),
("TECH_RIFLING" , "TECH_METAL_CASTING" ),
("TECH_MILITARY_SCIENCE" , "TECH_BALLISTICS" ),
("TECH_MILITARY_SCIENCE" , "TECH_RIFLING" ),
("TECH_STEEL" , "TECH_MILITARY_SCIENCE" ),
("TECH_SANITATION" , "TECH_INDUSTRIALIZATION" ),
("TECH_ADVANCED_BALLISTICS" , "TECH_CHEMISTRY" ),
("TECH_ROCKETRY" , "TECH_ADVANCED_FLIGHT" ),
("TECH_ADVANCED_FLIGHT" , "TECH_CHEMISTRY" ),
("TECH_GUIDANCE_SYSTEMS" , "TECH_NUCLEAR_FISSION" ),
("TECH_CONSTRUCTION" , "TECH_ENGINEERING" ),
("TECH_CONSTRUCTION" , "TECH_IRON_WORKING" ),
("TECH_IRON_WORKING" , "TECH_THE_WHEEL" ),
("TECH_HORSEBACK_RIDING" , "TECH_THE_WHEEL" ),
("TECH_HORSEBACK_RIDING" , "TECH_WRITING" ),
("TECH_BANKING" , "TECH_STIRRUPS" ),
("TECH_CARTOGRAPHY" , "TECH_EDUCATION" ),
("TECH_MASS_PRODUCTION" , "TECH_CARTOGRAPHY" ),
("TECH_METAL_CASTING" , "TECH_SIEGE_TACTICS" ),
("TECH_THE_WHEEL" , "TECH_ANIMAL_HUSBANDRY" ),
("TECH_ENGINEERING" , "TECH_MASONRY" ),
("TECH_MASONRY" , 			"TECH_BRONZE_WORKING" ),
("TECH_SHIPBUILDING" , "TECH_CELESTIAL_NAVIGATION" ),
("TECH_FLIGHT" , 			"TECH_SANITATION" ),
("TECH_ADVANCED_FLIGHT" , 	"TECH_ELECTRICITY" ),
--GS--
("TECH_REFINING" , "TECH_SANITATION" ),
("TECH_CHEMISTRY" , "TECH_REFINING" ),
("TECH_REFINING" , "TECH_ECONOMICS" ),

("TECH_FUTURE_TECH" , "TECH_SEASTEADS" ),
("TECH_FUTURE_TECH" , "TECH_ADVANCED_AI" ),
("TECH_FUTURE_TECH" , "TECH_ADVANCED_POWER_CELLS" ),
("TECH_FUTURE_TECH" , "TECH_CYBERNETICS" ),
("TECH_FUTURE_TECH" , "TECH_PREDICTIVE_SYSTEMS" ),
("TECH_FUTURE_TECH" , "TECH_SMART_MATERIALS" ),	
("TECH_FUTURE_TECH" , "TECH_OFFWORLD_MISSION" ),

("TECH_OFFWORLD_MISSION" , "TECH_STEALTH_TECHNOLOGY" ),	
("TECH_OFFWORLD_MISSION" , "TECH_NUCLEAR_FUSION" ),	
("TECH_SMART_MATERIALS" , "TECH_NANOTECHNOLOGY" ),
("TECH_SMART_MATERIALS" , "TECH_ROBOTICS" ),
("TECH_SEASTEADS" , "TECH_NANOTECHNOLOGY" ),
("TECH_ADVANCED_AI" , "TECH_ROBOTICS" ),
("TECH_ADVANCED_POWER_CELLS" , "TECH_NUCLEAR_FUSION" ),
("TECH_CYBERNETICS" , "TECH_ROBOTICS" ),
("TECH_PREDICTIVE_SYSTEMS" , "TECH_STEALTH_TECHNOLOGY" );


--Boosts
DELETE FROM Boosts WHERE TechnologyType="TECH_SIEGE_TACTICS";
DELETE FROM Boosts WHERE TechnologyType="TECH_HORSEBACK_RIDING";
DELETE FROM Boosts WHERE TechnologyType="TECH_MILITARY_TACTICS";
DELETE FROM Boosts WHERE TechnologyType="TECH_STIRRUPS";
DELETE FROM Boosts WHERE TechnologyType="TECH_ENGINEERING";
DELETE FROM Boosts WHERE TechnologyType="TECH_CASTLES";
DELETE FROM Boosts WHERE TechnologyType="TECH_CONSTRUCTION";
DELETE FROM Boosts WHERE TechnologyType="TECH_GUNPOWDER";
DELETE FROM Boosts WHERE TechnologyType="TECH_RIFLING";
DELETE FROM Boosts WHERE TechnologyType="TECH_MILITARY_SCIENCE";
DELETE FROM Boosts WHERE TechnologyType="TECH_SCIENTIFIC_THEORY";
DELETE FROM Boosts WHERE TechnologyType="TECH_MILITARY_ENGINEERING";
DELETE FROM Boosts WHERE TechnologyType="TECH_MASS_PRODUCTION";
DELETE FROM Boosts WHERE TechnologyType="TECH_SHIPBUILDING";
DELETE FROM Boosts WHERE TechnologyType="TECH_SQUARE_RIGGING";
DELETE FROM Boosts WHERE TechnologyType="TECH_INDUSTRIALIZATION";
DELETE FROM Boosts WHERE TechnologyType="TECH_ARCHERY";
DELETE FROM Boosts WHERE TechnologyType="TECH_ELECTRICITY";
DELETE FROM Boosts WHERE TechnologyType="TECH_REFINING";
DELETE FROM Boosts WHERE TechnologyType="TECH_STEEL";
DELETE FROM Boosts WHERE TechnologyType="TECH_COMBUSTION";
DELETE FROM Boosts WHERE TechnologyType="TECH_PLASTICS";
DELETE FROM Boosts WHERE TechnologyType="TECH_GUIDANCE_SYSTEMS";
DELETE FROM Boosts WHERE TechnologyType="TECH_ROBOTICS";
DELETE FROM Boosts WHERE TechnologyType="TECH_NANOTECHNOLOGY";
DELETE FROM Boosts WHERE TechnologyType="TECH_THE_WHEEL";
DELETE FROM Boosts WHERE TechnologyType="TECH_METAL_CASTING";
DELETE FROM Boosts WHERE TechnologyType="TECH_SYNTHETIC_MATERIALS";
DELETE FROM Boosts WHERE TechnologyType="TECH_IRON_WORKING";
DELETE FROM Boosts WHERE TechnologyType="TECH_APPRENTICESHIP";
DELETE FROM Boosts WHERE TechnologyType="TECH_ASTRONOMY";
DELETE FROM Boosts WHERE TechnologyType="TECH_NUCLEAR_FISSION";
DELETE FROM Boosts WHERE TechnologyType="TECH_CHEMISTRY";
DELETE FROM Boosts WHERE TechnologyType="TECH_BANKING";
DELETE FROM Boosts WHERE TechnologyType="TECH_ECONOMICS";
DELETE FROM Boosts WHERE TechnologyType="TECH_PRINTING";
DELETE FROM Boosts WHERE TechnologyType="TECH_RADIO";
DELETE FROM Boosts WHERE TechnologyType="TECH_SATELLITES";
DELETE FROM Boosts WHERE TechnologyType="TECH_EDUCATION";
DELETE FROM Boosts WHERE TechnologyType="TECH_SANITATION";
DELETE FROM Boosts WHERE TechnologyType="TECH_ROCKETRY";

INSERT OR REPLACE INTO Boosts  --改良类型尤里卡
(TechnologyType , 				Boost , TriggerDescription , 						TriggerLongDescription , 								BoostClass , 								ImprovementType , 		ResourceType , 			NumItems) VALUES
("TECH_HORSEBACK_RIDING" , 		40 , 	"LOC_BOOST_TRIGGER_HORSEBACK_RIDING" , 		"LOC_BOOST_TRIGGER_LONGDESC_HORSEBACK_RIDING" , 		"BOOST_TRIGGER_IMPROVE_SPECIFIC_RESOURCE" , "IMPROVEMENT_PASTURE" , "RESOURCE_HORSES"  , 	2),
("TECH_GUNPOWDER" , 			40 , 	"LOC_BOOST_TRIGGER_GUNPOWDER" , 			"LOC_BOOST_TRIGGER_LONGDESC_GUNPOWDER" , 				"BOOST_TRIGGER_IMPROVE_SPECIFIC_RESOURCE" , "IMPROVEMENT_QUARRY" , 	"RESOURCE_NITER"  , 	2),
("TECH_REFINING" , 				40 , 	"LOC_BOOST_TRIGGER_REFINING" , 				"LOC_BOOST_TRIGGER_LONGDESC_REFINING" , 				"BOOST_TRIGGER_IMPROVE_SPECIFIC_RESOURCE" , "IMPROVEMENT_MINE" , 	"RESOURCE_COAL"  , 		2),
("TECH_SYNTHETIC_MATERIALS" , 	40 , 	"LOC_BOOST_TRIGGER_SYNTHETIC_MATERIALS" , 	"LOC_BOOST_TRIGGER_LONGDESC_SYNTHETIC_MATERIALS" , 		"BOOST_TRIGGER_IMPROVE_SPECIFIC_RESOURCE" , "IMPROVEMENT_MINE" , 	"RESOURCE_ALUMINUM"  , 	2),
("TECH_NUCLEAR_FISSION" , 		40 , 	"LOC_BOOST_TRIGGER_NUCLEAR_FISSION" , 		"LOC_BOOST_TRIGGER_LONGDESC_NUCLEAR_FISSION" , 			"BOOST_TRIGGER_IMPROVE_SPECIFIC_RESOURCE" , "IMPROVEMENT_MINE" , 	"RESOURCE_URANIUM"  , 	2),
("TECH_APPRENTICESHIP" , 		40 , 	"LOC_BOOST_TRIGGER_APPRENTICESHIP" , 		"LOC_BOOST_TRIGGER_LONGDESC_APPRENTICESHIP" , 			"BOOST_TRIGGER_IMPROVE_SPECIFIC_RESOURCE" , "IMPROVEMENT_MINE" , 	"RESOURCE_IRON"  , 		2);

INSERT OR REPLACE INTO Boosts  
(TechnologyType , 			Boost , TriggerDescription , 					TriggerLongDescription , 						BoostClass , 							ImprovementType ,			 	RequiresResource , 	NumItems) VALUES
("TECH_MASS_PRODUCTION" , 	40 , 	"LOC_BOOST_TRIGGER_MASS_PRODUCTION" , 	"LOC_BOOST_TRIGGER_LONGDESC_MASS_PRODUCTION" , 	"BOOST_TRIGGER_HAVE_X_IMPROVEMENTS" , 	"IMPROVEMENT_LUMBER_MILL" , 	0, 					3),
("TECH_PLASTICS" , 			40 , 	"LOC_BOOST_TRIGGER_PLASTICS" , 			"LOC_BOOST_TRIGGER_LONGDESC_PLASTICS" , 		"BOOST_TRIGGER_HAVE_X_IMPROVEMENTS" , 	"IMPROVEMENT_OIL_WELL" , 		1, 					2),
("TECH_IRON_WORKING" , 		40 , 	"LOC_BOOST_TRIGGER_THE_WHEEL" , 		"LOC_BOOST_TRIGGER_LONGDESC_IRON_WORKING" , 	"BOOST_TRIGGER_HAVE_X_IMPROVEMENTS" , 	"IMPROVEMENT_MINE" , 			1, 					1);
	
INSERT OR REPLACE INTO Boosts   --单位类型尤里卡
(TechnologyType , Boost , TriggerDescription , TriggerLongDescription , BoostClass , Unit1Type , NumItems) VALUES
("TECH_SIEGE_TACTICS" , 40 , "LOC_BOOST_TRIGGER_SIEGE_TACTICS" , "LOC_BOOST_TRIGGER_LONGDESC_SIEGE_TACTICS" , "BOOST_TRIGGER_OWN_X_UNITS_OF_TYPE" , "UNIT_TREBUCHET" , 3),
("TECH_STIRRUPS" , 40 , "LOC_BOOST_TRIGGER_STIRRUPS" , "LOC_BOOST_TRIGGER_LONGDESC_STIRRUPS" , "BOOST_TRIGGER_OWN_X_UNITS_OF_TYPE" , "UNIT_HORSEMAN" , 3),
("TECH_RIFLING" , 40 , "LOC_BOOST_TRIGGER_RIFLING" , "LOC_BOOST_TRIGGER_LONGDESC_RIFLING" , "BOOST_TRIGGER_OWN_X_UNITS_OF_TYPE" , "UNIT_SKIRMISHER" , 3),
("TECH_SHIPBUILDING" , 40 , "LOC_BOOST_TRIGGER_SHIPBUILDING" , "LOC_BOOST_TRIGGER_LONGDESC_SHIPBUILDING" , "BOOST_TRIGGER_OWN_X_UNITS_OF_TYPE" , "UNIT_GALLEY" , 2),
("TECH_GUIDANCE_SYSTEMS" , 40 , "LOC_BOOST_TRIGGER_GUIDANCE_SYSTEMS" , "LOC_BOOST_TRIGGER_LONGDESC_GUIDANCE_SYSTEMS" , "BOOST_TRIGGER_OWN_X_UNITS_OF_TYPE" , "UNIT_ANTIAIR_GUN" , 3);

INSERT OR REPLACE INTO Boosts   --建筑类型尤里卡
(TechnologyType , 			Boost , TriggerDescription , TriggerLongDescription , BoostClass , BuildingType , NumItems) VALUES
("TECH_ASTRONOMY" , 		40 , "LOC_BOOST_TRIGGER_ASTRONOMY" , "LOC_BOOST_TRIGGER_LONGDESC_ASTRONOMY" , "BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_UNIVERSITY" , 100 ),--MODIFIER 触发
("TECH_CHEMISTRY" , 		40 , "LOC_BOOST_TRIGGER_CHEMISTRY" , "LOC_BOOST_TRIGGER_LONGDESC_CHEMISTRY" , "BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_UNIVERSITY" , 100 ),--MODIFIER 触发

("TECH_THE_WHEEL" , 		40 , "LOC_BOOST_TRIGGER_THE_WHEEL1" , "LOC_BOOST_TRIGGER_LONGDESC_THE_WHEEL" , "BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_GRANARY" , 1),
("TECH_ENGINEERING" , 		40 , "LOC_BOOST_TRIGGER_ENGINEERING" , "LOC_BOOST_TRIGGER_LONGDESC_ENGINEERING" , "BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_WATER_MILL" , 2 ),
("TECH_CASTLES" , 			40 , "LOC_BOOST_TRIGGER_CASTLES" , "LOC_BOOST_TRIGGER_LONGDESC_CASTLES" , "BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_WALLS" , 2 ),
("TECH_CONSTRUCTION" , 		40 , "LOC_BOOST_TRIGGER_CONSTRUCTION" , "LOC_BOOST_TRIGGER_LONGDESC_CONSTRUCTION" , "BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_MONUMENT" , 2 ),
("TECH_MILITARY_SCIENCE" , 	40 , "LOC_BOOST_TRIGGER_MILITARY_SCIENCE" , "LOC_BOOST_TRIGGER_LONGDESC_MILITARY_SCIENCE" , "BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_ARMORY" , 2 ),
("TECH_ELECTRICITY" , 		40 , "LOC_BOOST_TRIGGER_ELECTRICITY" , "LOC_BOOST_TRIGGER_LONGDESC_ELECTRICITY" , "BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_COAL_POWER_PLANT" , 2 );

INSERT OR REPLACE INTO Boosts   --区域类型尤里卡
(TechnologyType , Boost , TriggerDescription , TriggerLongDescription , BoostClass , DistrictType , NumItems) VALUES
("TECH_MILITARY_ENGINEERING" , 40 , "LOC_BOOST_TRIGGER_MILITARY_ENGINEERING" , "LOC_BOOST_TRIGGER_LONGDESC_MILITARY_ENGINEERING" , "BOOST_TRIGGER_HAVE_X_DISTRICTS" , "DISTRICT_AQUEDUCT" , 2 ),
("TECH_INDUSTRIALIZATION" , 40 , "LOC_BOOST_TRIGGER_INDUSTRIALIZATION" , "LOC_BOOST_TRIGGER_LONGDESC_INDUSTRIALIZATION" , "BOOST_TRIGGER_HAVE_X_DISTRICTS" , "DISTRICT_INDUSTRIAL_ZONE" , 4 ),
("TECH_STEEL" , 40 , "LOC_BOOST_TRIGGER_STEEL" , "LOC_BOOST_TRIGGER_LONGDESC_STEEL" , "BOOST_TRIGGER_HAVE_X_DISTRICTS" , "DISTRICT_DAM" , 2 ),
("TECH_COMBUSTION" , 40 , "LOC_BOOST_TRIGGER_COMBUSTION" , "LOC_BOOST_TRIGGER_LONGDESC_COMBUSTION" , "BOOST_TRIGGER_HAVE_X_DISTRICTS" , "DISTRICT_CANAL" , 2 );

INSERT OR REPLACE INTO Boosts   --特殊型尤里卡
(TechnologyType , 		Boost , TriggerDescription , 						TriggerLongDescription , 									BoostClass , Unit1Type) VALUES
("TECH_METAL_CASTING" , 40 , 	"LOC_BOOST_TRIGGER_METAL_CASTING" , 		"LOC_BOOST_TRIGGER_LONGDESC_METAL_CASTING" , 				"BOOST_TRIGGER_TRAIN_UNIT" , 	"UNIT_GREAT_ENGINEER"),
("TECH_SQUARE_RIGGING" , 40 , 	"LOC_BOOST_TRIGGER_SQUARE_RIGGING" , 		"LOC_BOOST_TRIGGER_LONGDESC_SQUARE_RIGGING" ,	 			"BOOST_TRIGGER_TRAIN_UNIT" , 	"UNIT_GREAT_ADMIRAL"),
("TECH_MILITARY_TACTICS" , 40 , "LOC_BOOST_TRIGGER_MILITARY_TACTICS" , 		"LOC_BOOST_TRIGGER_LONGDESC_MILITARY_TACTICS" , 			"BOOST_TRIGGER_TRAIN_UNIT" , 	"UNIT_GREAT_GENERAL"),
("TECH_SCIENTIFIC_THEORY" , 40 , "LOC_BOOST_TRIGGER_SCIENTIFIC_THEORY" , 	"LOC_BOOST_TRIGGER_LONGDESC_SCIENTIFIC_THEORY" , 			"BOOST_TRIGGER_TRAIN_UNIT" , 	"UNIT_GREAT_SCIENTIST"),
("TECH_ROBOTICS" , 		40 , 	"LOC_BOOST_TRIGGER_MUST_STEAL" , 		"Critical late game tech - boost description not needed" , 	"BOOST_TRIGGER_NONE_LATE_GAME_CRITICAL_TECH" , null),
("TECH_NANOTECHNOLOGY" ,40 , 	"LOC_BOOST_TRIGGER_MUST_STEAL" , 		"Critical late game tech - boost description not needed" , 	"BOOST_TRIGGER_NONE_LATE_GAME_CRITICAL_TECH" , null);

--MODIFIER 触发
INSERT OR REPLACE INTO DistrictModifiers (DistrictType,					ModifierId) VALUES	
('DISTRICT_CAMPUS',	'GA_TECH_ASTRONOMY_BOOST'),
('DISTRICT_CAMPUS',	'GA_TECH_CHEMISTRY_BOOST');
INSERT OR REPLACE INTO Modifiers 
(ModifierId,							ModifierType,											SubjectRequirementSetId) VALUES
('GA_TECH_ASTRONOMY_BOOST',	            'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',	        'GOLDEN_PLOT_IS_ADJACENT_TO_MOUNTAINS_AND_3_ADJACENCY_CAMPUS_REQUIREMENTS'),
('GA_TECH_CHEMISTRY_BOOST',	            'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',	        'GOLDEN_PLOT_IS_ADJACENT_TO_MINE_AND_4_ADJACENCY_CAMPUS_REQUIREMENTS');
INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,							Name,		    Value) VALUES
('GA_TECH_ASTRONOMY_BOOST',	            'TechType',   'TECH_ASTRONOMY'),
('GA_TECH_CHEMISTRY_BOOST',	            'TechType',   'TECH_CHEMISTRY');
INSERT OR REPLACE INTO RequirementSets 				(RequirementSetId ,     RequirementSetType) 	VALUES 		
('GOLDEN_PLOT_IS_ADJACENT_TO_MOUNTAINS_AND_3_ADJACENCY_CAMPUS_REQUIREMENTS' , 		    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLOT_IS_ADJACENT_TO_MINE_AND_4_ADJACENCY_CAMPUS_REQUIREMENTS' , 		    	'REQUIREMENTSET_TEST_ALL');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			VALUES 		
('GOLDEN_PLOT_IS_ADJACENT_TO_MOUNTAINS_AND_3_ADJACENCY_CAMPUS_REQUIREMENTS' , 		    'GOLDEN_REQUIRES_CAMPUS_HAS_THREE_ADJACENCY'),
('GOLDEN_PLOT_IS_ADJACENT_TO_MOUNTAINS_AND_3_ADJACENCY_CAMPUS_REQUIREMENTS' , 			'GOLDEN_REQUIRES_PLOT_ADJACENT_TO_MOUNTAINS_ASTRONOMY_BOOST'),
('GOLDEN_PLOT_IS_ADJACENT_TO_MINE_AND_4_ADJACENCY_CAMPUS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_CAMPUS_HAS_FOUR_ADJACENCY'),
('GOLDEN_PLOT_IS_ADJACENT_TO_MINE_AND_4_ADJACENCY_CAMPUS_REQUIREMENTS' , 				'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_MINE');
INSERT OR REPLACE INTO 		Requirements (RequirementId,				            RequirementType) VALUES						
('GOLDEN_REQUIRES_PLOT_ADJACENT_TO_MOUNTAINS_ASTRONOMY_BOOST',						'REQUIREMENT_REQUIREMENTSET_IS_MET');
INSERT OR REPLACE INTO 		RequirementArguments (RequirementId,		                Name,			        Value) VALUES					    
('GOLDEN_REQUIRES_PLOT_ADJACENT_TO_MOUNTAINS_ASTRONOMY_BOOST',							'RequirementSetId',		'GOLDEN_PLOT_IS_ADJACENT_TO_ANY_MOUNTAINS_REQUIREMENTS');

--商业中心建筑
INSERT OR REPLACE INTO Boosts   --MODIFIER 触发（不可能达成）
(TechnologyType , 		Boost , TriggerDescription , TriggerLongDescription , BoostClass , BuildingType , NumItems) VALUES
("TECH_BANKING" , 		40 , "LOC_BOOST_TRIGGER_BANKING" , 	 "LOC_BOOST_TRIGGER_LONGDESC_BANKING" , 	"BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_UNIVERSITY" , 100 ),
("TECH_ECONOMICS" , 	40 , "LOC_BOOST_TRIGGER_ECONOMICS" , "LOC_BOOST_TRIGGER_LONGDESC_ECONOMICS" , 	"BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_UNIVERSITY" , 100 );

INSERT OR REPLACE INTO TraitModifiers (TraitType,					ModifierId) VALUES	
('TRAIT_LEADER_MAJOR_CIV',	'GA_TECH_BANKING_BOOST'),
('TRAIT_LEADER_MAJOR_CIV',	'GA_TECH_ECONOMICS_BOOST');
INSERT OR REPLACE INTO Modifiers 
(ModifierId,							ModifierType,											SubjectRequirementSetId) VALUES
('GA_TECH_BANKING_BOOST',	            'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',	        'GOLDEN_PLAYER_HAS_ALL_COMMERCIAL_T1_BUILDINGS_REQUIREMENTS'),
('GA_TECH_ECONOMICS_BOOST',	            'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',	        'GOLDEN_PLAYER_HAS_ALL_COMMERCIAL_T2_BUILDINGS_REQUIREMENTS');
INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,							Name,		    Value) VALUES
('GA_TECH_BANKING_BOOST',	            'TechType',   'TECH_BANKING'),
('GA_TECH_ECONOMICS_BOOST',	            'TechType',   'TECH_ECONOMICS');
INSERT OR REPLACE INTO RequirementSets 				(RequirementSetId ,     RequirementSetType) 	VALUES 		
('GOLDEN_PLAYER_HAS_ALL_COMMERCIAL_T1_BUILDINGS_REQUIREMENTS' , 		    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLAYER_HAS_ALL_COMMERCIAL_T2_BUILDINGS_REQUIREMENTS' , 		    'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			VALUES 		
('GOLDEN_PLAYER_HAS_ALL_COMMERCIAL_T1_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_MARKET'),
('GOLDEN_PLAYER_HAS_ALL_COMMERCIAL_T2_BUILDINGS_REQUIREMENTS' , 				'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_BANK');

INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_COMMERCIAL_T1_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_MINT' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_MINT');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_COMMERCIAL_T1_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_POST_STATION' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_POST_STATION');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_COMMERCIAL_T2_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_COMMERCIAL' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_COMMERCIAL_T2_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_TAX_BUREAU' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');

INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_MINT' , 		    	 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_MINT');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_POST_STATION' , 		 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_POST_STATION');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_COMMERCIAL' , 		     'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_TAX_BUREAU' , 		     'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');

INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_MINT',		'BuildingType',	    'BUILDING_MINT' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_MINT');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_POST_STATION',		'BuildingType',	    'BUILDING_POST_STATION' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_POST_STATION');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_COMMERCIAL',		'BuildingType',	    'BUILDING_COMMERCIAL' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_TAX_BUREAU',		'BuildingType',	    'BUILDING_TAX_BUREAU' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');

--剧院广场建筑
INSERT OR REPLACE INTO Boosts   --MODIFIER 触发（不可能达成）
(TechnologyType , 		Boost , TriggerDescription , TriggerLongDescription , BoostClass , BuildingType , NumItems) VALUES
("TECH_PRINTING" , 		40 , "LOC_BOOST_TRIGGER_PRINTING" , 	"LOC_BOOST_TRIGGER_LONGDESC_PRINTING" , 	"BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_UNIVERSITY" , 100 ),
("TECH_RADIO" , 		40 , "LOC_BOOST_TRIGGER_RADIO" , 		"LOC_BOOST_TRIGGER_LONGDESC_RADIO" , 	"BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_UNIVERSITY" , 100 ),
("TECH_SATELLITES" , 	40 , "LOC_BOOST_TRIGGER_SATELLITES" , 	"LOC_BOOST_TRIGGER_LONGDESC_SATELLITES" , 	"BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_UNIVERSITY" , 100 );

INSERT OR REPLACE INTO TraitModifiers (TraitType,					ModifierId) VALUES	
('TRAIT_LEADER_MAJOR_CIV',	'GA_TECH_PRINTING_BOOST'),
('TRAIT_LEADER_MAJOR_CIV',	'GA_TECH_RADIO_BOOST'),
('TRAIT_LEADER_MAJOR_CIV',	'GA_TECH_SATELLITES_BOOST');
INSERT OR REPLACE INTO Modifiers 
(ModifierId,							ModifierType,											SubjectRequirementSetId) VALUES
('GA_TECH_PRINTING_BOOST',	            'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',	        'GOLDEN_PLAYER_HAS_ALL_THEATER_T1_BUILDINGS_REQUIREMENTS'),
('GA_TECH_RADIO_BOOST',	            	'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',	        'GOLDEN_PLAYER_HAS_ALL_THEATER_T2_BUILDINGS_REQUIREMENTS'),
('GA_TECH_SATELLITES_BOOST',	        'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',	        'GOLDEN_PLAYER_HAS_ALL_THEATER_T3_BUILDINGS_REQUIREMENTS');
INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,							Name,		    Value) VALUES
('GA_TECH_PRINTING_BOOST',	            'TechType',   'TECH_PRINTING'),
('GA_TECH_RADIO_BOOST',	            	'TechType',   'TECH_RADIO'),
('GA_TECH_SATELLITES_BOOST',	        'TechType',   'TECH_SATELLITES');

INSERT OR REPLACE INTO RequirementSets 				(RequirementSetId ,     RequirementSetType) 	VALUES 		
('GOLDEN_PLAYER_HAS_ALL_THEATER_T1_BUILDINGS_REQUIREMENTS' , 		    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLAYER_HAS_ALL_THEATER_T2_BUILDINGS_REQUIREMENTS' , 		    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLAYER_HAS_ALL_THEATER_T3_BUILDINGS_REQUIREMENTS' , 		    'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			VALUES 		
('GOLDEN_PLAYER_HAS_ALL_THEATER_T1_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_AMPHITHEATER'),
('GOLDEN_PLAYER_HAS_ALL_THEATER_T2_BUILDINGS_REQUIREMENTS' , 				'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_MUSEUM_ART'),
('GOLDEN_PLAYER_HAS_ALL_THEATER_T2_BUILDINGS_REQUIREMENTS' , 				'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_MUSEUM_ARTIFACT'),
('GOLDEN_PLAYER_HAS_ALL_THEATER_T3_BUILDINGS_REQUIREMENTS' , 				'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_BROADCAST_CENTER');

INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_THEATER_T1_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_EPIC_THEATRE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_EPIC_THEATRE');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_THEATER_T1_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_TAMPLE_STAGE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAMPLE_STAGE');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_THEATER_T2_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_THERTERMUSEUM' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_THERTERMUSEUM');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_THEATER_T2_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_LIBRARYMUSEUM' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_LIBRARYMUSEUM');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_THEATER_T3_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_OPERA_HOUSE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_OPERA_HOUSE');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_THEATER_T3_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_ART_ASSOCIATION' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ART_ASSOCIATION');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_THEATER_T3_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_PHOTOSTUDIO' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PHOTOSTUDIO');

INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_EPIC_THEATRE' , 		 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_EPIC_THEATRE');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_TAMPLE_STAGE' , 		 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAMPLE_STAGE');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_THERTERMUSEUM' , 		 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_THERTERMUSEUM');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_LIBRARYMUSEUM' , 		 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_LIBRARYMUSEUM');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_OPERA_HOUSE' , 		 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_OPERA_HOUSE');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_ART_ASSOCIATION' , 	 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ART_ASSOCIATION');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_PHOTOSTUDIO' , 		 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PHOTOSTUDIO');

INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_EPIC_THEATRE',			'BuildingType',	    'BUILDING_EPIC_THEATRE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_EPIC_THEATRE');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_TAMPLE_STAGE',			'BuildingType',	    'BUILDING_TAMPLE_STAGE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAMPLE_STAGE');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_THERTERMUSEUM',		'BuildingType',	    'BUILDING_THERTERMUSEUM' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_THERTERMUSEUM');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_LIBRARYMUSEUM',		'BuildingType',	    'BUILDING_LIBRARYMUSEUM' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_LIBRARYMUSEUM');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_OPERA_HOUSE',			'BuildingType',	    'BUILDING_OPERA_HOUSE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_OPERA_HOUSE');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_ART_ASSOCIATION',		'BuildingType',	    'BUILDING_ART_ASSOCIATION' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ART_ASSOCIATION');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_PHOTOSTUDIO',			'BuildingType',	    'BUILDING_PHOTOSTUDIO' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PHOTOSTUDIO');

--学院建筑
INSERT OR REPLACE INTO Boosts   --MODIFIER 触发（不可能达成）
(TechnologyType , 		Boost , TriggerDescription , TriggerLongDescription , BoostClass , BuildingType , NumItems) VALUES
("TECH_EDUCATION" , 		40 , "LOC_BOOST_TRIGGER_EDUCATION" , 	"LOC_BOOST_TRIGGER_LONGDESC_EDUCATION" , 	"BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_UNIVERSITY" , 100 ),
("TECH_SANITATION" , 		40 , "LOC_BOOST_TRIGGER_SANITATION" , 	"LOC_BOOST_TRIGGER_LONGDESC_SANITATION" , 	"BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_UNIVERSITY" , 100 ),
("TECH_ROCKETRY" , 			40 , "LOC_BOOST_TRIGGER_ROCKETRY" , 	"LOC_BOOST_TRIGGER_LONGDESC_ROCKETRY" , 	"BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_UNIVERSITY" , 100 );

INSERT OR REPLACE INTO TraitModifiers (TraitType,					ModifierId) VALUES	
('TRAIT_LEADER_MAJOR_CIV',	'GA_TECH_EDUCATION_BOOST'),
('TRAIT_LEADER_MAJOR_CIV',	'GA_TECH_SANITATION_BOOST'),
('TRAIT_LEADER_MAJOR_CIV',	'GA_TECH_ROCKETRY_BOOST');
INSERT OR REPLACE INTO Modifiers 
(ModifierId,							ModifierType,											SubjectRequirementSetId) VALUES
('GA_TECH_EDUCATION_BOOST',	            'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',	        'GOLDEN_PLAYER_HAS_ALL_CAMPUS_T1_BUILDINGS_REQUIREMENTS'),
('GA_TECH_SANITATION_BOOST',	        'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',	        'GOLDEN_PLAYER_HAS_ALL_CAMPUS_T2_BUILDINGS_REQUIREMENTS'),
('GA_TECH_ROCKETRY_BOOST',	        	'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',	        'GOLDEN_PLAYER_HAS_ALL_CAMPUS_T3_BUILDINGS_REQUIREMENTS');
INSERT OR REPLACE INTO ModifierArguments 
(ModifierId,							Name,		    Value) VALUES
('GA_TECH_EDUCATION_BOOST',	            'TechType',   'TECH_EDUCATION'),
('GA_TECH_SANITATION_BOOST',	        'TechType',   'TECH_SANITATION'),
('GA_TECH_ROCKETRY_BOOST',	        	'TechType',   'TECH_ROCKETRY');

INSERT OR REPLACE INTO RequirementSets 				(RequirementSetId ,     RequirementSetType) 	VALUES 		
('GOLDEN_PLAYER_HAS_ALL_CAMPUS_T1_BUILDINGS_REQUIREMENTS' , 		    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLAYER_HAS_ALL_CAMPUS_T2_BUILDINGS_REQUIREMENTS' , 		    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLAYER_HAS_ALL_CAMPUS_T3_BUILDINGS_REQUIREMENTS' , 		    'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			VALUES 		
('GOLDEN_PLAYER_HAS_ALL_CAMPUS_T1_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_LIBRARY'),
('GOLDEN_PLAYER_HAS_ALL_CAMPUS_T2_BUILDINGS_REQUIREMENTS' , 				'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_UNIVERSITY'),
('GOLDEN_PLAYER_HAS_ALL_CAMPUS_T3_BUILDINGS_REQUIREMENTS' , 				'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_RESEARCH_LAB');

INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_CAMPUS_T1_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_ALCHEMY_HOUSE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ALCHEMY_HOUSE');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_CAMPUS_T1_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_OBSERVATORY' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_OBSERVATORY');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_CAMPUS_T2_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_PUBLIC_SCHOOL' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PUBLIC_SCHOOL');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_CAMPUS_T2_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_ACADEMIC_EXCHANGE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ACADEMIC_EXCHANGE');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_CAMPUS_T3_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_BIOLOGY_LAB' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_BIOLOGY_LAB');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_CAMPUS_T3_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_ANIMAL_LAB' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ANIMAL_LAB');
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,     RequirementId) 			SELECT 	
'GOLDEN_PLAYER_HAS_ALL_CAMPUS_T3_BUILDINGS_REQUIREMENTS' , 		    	'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_CHEMISTRY_LAB' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_CHEMISTRY_LAB');

INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_ALCHEMY_HOUSE' , 		 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ALCHEMY_HOUSE');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_OBSERVATORY' , 		 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_OBSERVATORY');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_PUBLIC_SCHOOL' , 		 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PUBLIC_SCHOOL');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_ACADEMIC_EXCHANGE' , 	 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ACADEMIC_EXCHANGE');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_BIOLOGY_LAB' , 		 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_BIOLOGY_LAB');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_ANIMAL_LAB' , 	 		 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ANIMAL_LAB');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_CHEMISTRY_LAB' , 		 'REQUIREMENT_PLAYER_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_CHEMISTRY_LAB');

INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_ALCHEMY_HOUSE',			'BuildingType',	    'BUILDING_ALCHEMY_HOUSE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ALCHEMY_HOUSE');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_OBSERVATORY',				'BuildingType',	    'BUILDING_OBSERVATORY' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_OBSERVATORY');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_PUBLIC_SCHOOL',			'BuildingType',	    'BUILDING_PUBLIC_SCHOOL' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PUBLIC_SCHOOL');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_ACADEMIC_EXCHANGE',		'BuildingType',	    'BUILDING_ACADEMIC_EXCHANGE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ACADEMIC_EXCHANGE');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_BIOLOGY_LAB',				'BuildingType',	    'BUILDING_BIOLOGY_LAB' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_BIOLOGY_LAB');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_ANIMAL_LAB',				'BuildingType',	    'BUILDING_ANIMAL_LAB' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ANIMAL_LAB');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_CHEMISTRY_LAB',			'BuildingType',	    'BUILDING_CHEMISTRY_LAB' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_CHEMISTRY_LAB');