UPDATE Civics SET  Cost="250",UITreeRow=-3 
WHERE CivicType="CIVIC_NAVAL_TRADITION";
UPDATE Civics SET  Cost="350",UITreeRow=0,Description="LOC_CIVIC_MERCENARIES_DESCRIPTION" 
WHERE CivicType="CIVIC_MERCENARIES";
UPDATE Civics SET  Cost="470",EraType="ERA_RENAISSANCE",UITreeRow=0 
WHERE CivicType="CIVIC_DIVINE_RIGHT";
UPDATE Civics SET  Description="LOC_CIVIC_SCORCHED_EARTH_DESCRIPTION",Cost="1000",UITreeRow=0 
WHERE CivicType="CIVIC_SCORCHED_EARTH";
UPDATE Civics SET  Cost="820",UITreeRow=3 
WHERE CivicType="CIVIC_OPERA_BALLET";
UPDATE Civics SET  Description="LOC_CIVIC_MASS_MEDIA_DESCRIPTION",Cost="1300",UITreeRow=3 
WHERE CivicType="CIVIC_MASS_MEDIA";
UPDATE Civics SET  Cost="1300",UITreeRow=1 
WHERE CivicType="CIVIC_MOBILIZATION";
UPDATE Civics SET  Cost="1700",UITreeRow=0 
WHERE CivicType="CIVIC_SUFFRAGE";
UPDATE Civics SET  Cost="1700",UITreeRow=-1
WHERE CivicType="CIVIC_TOTALITARIANISM";
UPDATE Civics SET  Cost="1700",UITreeRow=-2 
WHERE CivicType="CIVIC_CLASS_STRUGGLE";
UPDATE Civics SET  Description="LOC_CIVIC_CAPITALISM_DESCRIPTION",Cost="1700",UITreeRow=3 
WHERE CivicType="CIVIC_CAPITALISM";
UPDATE Civics SET  Description="LOC_CIVIC_NUCLEAR_PROGRAM_DESCRIPTION",Cost="1700",UITreeRow=1 
WHERE CivicType="CIVIC_NUCLEAR_PROGRAM";
UPDATE Civics SET  Cost="2100",UITreeRow=1 
WHERE CivicType="CIVIC_COLD_WAR";
UPDATE Civics SET  Cost="1300",UITreeRow=-1
WHERE CivicType="CIVIC_IDEOLOGY";
UPDATE Civics SET  Cost="470",Description="" 
WHERE CivicType="CIVIC_EXPLORATION";
UPDATE Civics SET  Description="LOC_CIVIC_GAMES_RECREATION_DESCRIPTION" 
WHERE CivicType="CIVIC_GAMES_RECREATION";
UPDATE Civics SET  Cost="1000",Description="LOC_CIVIC_NATURAL_HISTORY_DESCRIPTION" 
WHERE CivicType="CIVIC_NATURAL_HISTORY";
UPDATE Civics SET  Cost="148",Description="LOC_CIVIC_THEOLOGY_DESCRIPTION" 
WHERE CivicType="CIVIC_THEOLOGY";
UPDATE Civics SET  Cost="250",Description="LOC_CIVIC_CIVIL_SERVICE_DESCRIPTION" 
WHERE CivicType="CIVIC_CIVIL_SERVICE";
UPDATE Civics SET  Cost="60" 
WHERE CivicType="CIVIC_MILITARY_TRADITION";
UPDATE Civics SET  Cost="60" 
WHERE CivicType="CIVIC_STATE_WORKFORCE";
UPDATE Civics SET  Cost="60" 
WHERE CivicType="CIVIC_EARLY_EMPIRE";
UPDATE Civics SET  Cost="60" 
WHERE CivicType="CIVIC_MYSTICISM";
UPDATE Civics SET  Cost="148" 
WHERE CivicType="CIVIC_MILITARY_TRAINING";
UPDATE Civics SET  Cost="148" 
WHERE CivicType="CIVIC_DEFENSIVE_TACTICS";
UPDATE Civics SET  Cost="148" 
WHERE CivicType="CIVIC_RECORDED_HISTORY";
UPDATE Civics SET  Cost="250" 
WHERE CivicType="CIVIC_FEUDALISM";
UPDATE Civics SET  Cost="350",Description="LOC_CIVIC_MEDIEVAL_FAIRES_DESCRIPTION",UITreeRow=-2 
WHERE CivicType="CIVIC_MEDIEVAL_FAIRES";
UPDATE Civics SET  Cost="350",UITreeRow=2 
WHERE CivicType="CIVIC_GUILDS";
UPDATE Civics SET  Cost="470" 
WHERE CivicType="CIVIC_HUMANISM";
UPDATE Civics SET  Cost="470" 
WHERE CivicType="CIVIC_DIPLOMATIC_SERVICE";
UPDATE Civics SET  Cost="470" 
WHERE CivicType="CIVIC_REFORMED_CHURCH";
UPDATE Civics SET  Cost="820" 
WHERE CivicType="CIVIC_COLONIALISM";
UPDATE Civics SET  Cost="820" 
WHERE CivicType="CIVIC_CIVIL_ENGINEERING";
UPDATE Civics SET  Cost="820" 
WHERE CivicType="CIVIC_NATIONALISM";
UPDATE Civics SET  Description="LOC_CIVIC_URBANIZATION_DESCRIPTION",Cost="1000" 
WHERE CivicType="CIVIC_URBANIZATION";
UPDATE Civics SET  Cost="1300" 
WHERE CivicType="CIVIC_CONSERVATION";
UPDATE Civics SET  Cost="2100" 
WHERE CivicType="CIVIC_PROFESSIONAL_SPORTS";
UPDATE Civics SET  Cost="2100" 
WHERE CivicType="CIVIC_CULTURAL_HERITAGE";
UPDATE Civics SET  Cost="3000" 
WHERE CivicType="CIVIC_NEAR_FUTURE_GOVERNANCE";

DELETE FROM CivicPrereqs WHERE Civic="CIVIC_EXPLORATION" AND PrereqCivic="CIVIC_MERCENARIES";
DELETE FROM CivicPrereqs WHERE Civic="CIVIC_MERCENARIES" AND PrereqCivic="CIVIC_MILITARY_TRAINING"; 
DELETE FROM CivicPrereqs WHERE Civic="CIVIC_DIVINE_RIGHT" AND PrereqCivic="CIVIC_CIVIL_SERVICE";
DELETE FROM CivicPrereqs WHERE Civic="CIVIC_DIVINE_RIGHT" AND PrereqCivic="CIVIC_THEOLOGY";
DELETE FROM CivicPrereqs WHERE Civic="CIVIC_THE_ENLIGHTENMENT" AND PrereqCivic="CIVIC_HUMANISM";
DELETE FROM CivicPrereqs WHERE Civic="CIVIC_REFORMED_CHURCH" AND PrereqCivic="CIVIC_DIVINE_RIGHT";
DELETE FROM CivicPrereqs WHERE Civic="CIVIC_GUILDS" AND PrereqCivic="CIVIC_FEUDALISM";
DELETE FROM CivicPrereqs WHERE Civic="CIVIC_CIVIL_SERVICE" AND PrereqCivic="CIVIC_DEFENSIVE_TACTICS";
DELETE FROM CivicPrereqs WHERE Civic="CIVIC_MASS_MEDIA" AND PrereqCivic="CIVIC_URBANIZATION";
DELETE FROM CivicPrereqs WHERE Civic="CIVIC_IDEOLOGY" AND PrereqCivic="CIVIC_MOBILIZATION";

UPDATE CivicPrereqs SET  PrereqCivic="CIVIC_MILITARY_TRAINING" 
WHERE Civic="CIVIC_NAVAL_TRADITION"; 
UPDATE CivicPrereqs SET  PrereqCivic="CIVIC_OPERA_BALLET" 
WHERE Civic="CIVIC_MASS_MEDIA" AND PrereqCivic="CIVIC_NATURAL_HISTORY"; 
UPDATE CivicPrereqs SET  PrereqCivic="CIVIC_MOBILIZATION" 
WHERE Civic="CIVIC_NUCLEAR_PROGRAM" AND PrereqCivic="CIVIC_IDEOLOGY"; 
UPDATE CivicPrereqs SET  PrereqCivic="CIVIC_NUCLEAR_PROGRAM" 
WHERE Civic="CIVIC_COLD_WAR" AND PrereqCivic="CIVIC_IDEOLOGY"; 
UPDATE CivicPrereqs SET  PrereqCivic="CIVIC_CAPITALISM" 
WHERE Civic="CIVIC_PROFESSIONAL_SPORTS" AND PrereqCivic="CIVIC_IDEOLOGY"; 
UPDATE CivicPrereqs SET  PrereqCivic="CIVIC_URBANIZATION" 
WHERE Civic="CIVIC_IDEOLOGY" AND PrereqCivic="CIVIC_MASS_MEDIA"; 

INSERT OR REPLACE INTO CivicPrereqs
(Civic , PrereqCivic) VALUES
("CIVIC_MERCENARIES" , "CIVIC_CIVIL_SERVICE" ), 
("CIVIC_DIVINE_RIGHT" , "CIVIC_MERCENARIES" ),
("CIVIC_NATIONALISM" , "CIVIC_DIVINE_RIGHT" ),
("CIVIC_OPERA_BALLET" , "CIVIC_REFORMED_CHURCH" ),
("CIVIC_COLONIALISM" , "CIVIC_EXPLORATION" ),
("CIVIC_GUILDS" , "CIVIC_THEOLOGY" ),
("CIVIC_MEDIEVAL_FAIRES" , "CIVIC_NAVAL_TRADITION" ),
--XP2
("CIVIC_GLOBAL_WARMING_MITIGATION" , "CIVIC_NEAR_FUTURE_GOVERNANCE" ),
("CIVIC_SMART_POWER_DOCTRINE" , "CIVIC_NEAR_FUTURE_GOVERNANCE" ),
("CIVIC_INFORMATION_WARFARE" , "CIVIC_NEAR_FUTURE_GOVERNANCE" ),
("CIVIC_EXODUS_IMPERATIVE" , "CIVIC_NEAR_FUTURE_GOVERNANCE" ),
("CIVIC_CULTURAL_HEGEMONY" , "CIVIC_NEAR_FUTURE_GOVERNANCE" ),
("CIVIC_FUTURE_CIVIC" , "CIVIC_GLOBAL_WARMING_MITIGATION" ),
("CIVIC_FUTURE_CIVIC" , "CIVIC_SMART_POWER_DOCTRINE" ),
("CIVIC_FUTURE_CIVIC" , "CIVIC_INFORMATION_WARFARE" ),
("CIVIC_FUTURE_CIVIC" , "CIVIC_EXODUS_IMPERATIVE" ),
("CIVIC_FUTURE_CIVIC" , "CIVIC_CULTURAL_HEGEMONY" );
DELETE FROM CivicPrereqs WHERE Civic='CIVIC_FUTURE_CIVIC' AND PrereqCivic='CIVIC_GLOBALIZATION';
DELETE FROM CivicPrereqs WHERE Civic='CIVIC_FUTURE_CIVIC' AND PrereqCivic='CIVIC_SOCIAL_MEDIA';
UPDATE Civics_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE CivicType="CIVIC_GLOBAL_WARMING_MITIGATION";
UPDATE Civics_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE CivicType="CIVIC_SMART_POWER_DOCTRINE";
UPDATE Civics_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE CivicType="CIVIC_INFORMATION_WARFARE";
UPDATE Civics_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE CivicType="CIVIC_EXODUS_IMPERATIVE";
UPDATE Civics_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE CivicType="CIVIC_CULTURAL_HEGEMONY";
UPDATE Civics_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE CivicType="CIVIC_FUTURE_CIVIC";

--Boosts
DELETE FROM Boosts WHERE CivicType="CIVIC_DIVINE_RIGHT";
DELETE FROM Boosts WHERE CivicType="CIVIC_GUILDS";
DELETE FROM Boosts WHERE CivicType="CIVIC_GAMES_RECREATION";
DELETE FROM Boosts WHERE CivicType="CIVIC_MILITARY_TRAINING";
DELETE FROM Boosts WHERE CivicType="CIVIC_MEDIEVAL_FAIRES";
DELETE FROM Boosts WHERE CivicType="CIVIC_CIVIL_ENGINEERING";
DELETE FROM Boosts WHERE CivicType="CIVIC_OPERA_BALLET";
DELETE FROM Boosts WHERE CivicType="CIVIC_SCORCHED_EARTH";
DELETE FROM Boosts WHERE CivicType="CIVIC_COLONIALISM";
DELETE FROM Boosts WHERE CivicType="CIVIC_NATURAL_HISTORY";
DELETE FROM Boosts WHERE CivicType="CIVIC_URBANIZATION";
DELETE FROM Boosts WHERE CivicType="CIVIC_MASS_MEDIA";
DELETE FROM Boosts WHERE CivicType="CIVIC_NUCLEAR_PROGRAM";
DELETE FROM Boosts WHERE CivicType="CIVIC_SUFFRAGE";
DELETE FROM Boosts WHERE CivicType="CIVIC_PROFESSIONAL_SPORTS";
DELETE FROM Boosts WHERE CivicType="CIVIC_COLD_WAR";
DELETE FROM Boosts WHERE CivicType="CIVIC_SPACE_RACE";
DELETE FROM Boosts WHERE CivicType="CIVIC_SOCIAL_MEDIA";
DELETE FROM Boosts WHERE CivicType="CIVIC_NAVAL_TRADITION";
DELETE FROM Boosts WHERE CivicType="CIVIC_EXPLORATION";
DELETE FROM Boosts WHERE CivicType="CIVIC_ENVIRONMENTALISM";
DELETE FROM Boosts WHERE CivicType="CIVIC_CORPORATE_LIBERTARIANISM";
DELETE FROM Boosts WHERE CivicType="CIVIC_SYNTHETIC_TECHNOCRACY";
DELETE FROM Boosts WHERE CivicType="CIVIC_DIGITAL_DEMOCRACY";
DELETE FROM Boosts WHERE CivicType="CIVIC_CLASS_STRUGGLE";
DELETE FROM Boosts WHERE CivicType="CIVIC_CAPITALISM";
DELETE FROM Boosts WHERE CivicType="CIVIC_HUMANISM";
DELETE FROM Boosts WHERE CivicType="CIVIC_OPERA_BALLET";
DELETE FROM Boosts WHERE CivicType="CIVIC_MASS_MEDIA";

--人口鼓舞
INSERT OR REPLACE INTO Boosts 
(CivicType , Boost, TriggerDescription , TriggerLongDescription , BoostClass , NumItems) VALUES
("CIVIC_CLASS_STRUGGLE" , 40 , "LOC_BOOST_TRIGGER_CLASS_STRUGGLE" , "LOC_BOOST_TRIGGER_LONGDESC_CLASS_STRUGGLE" , "BOOST_TRIGGER_EMPIRE_POPULATION" , 100 ),
("CIVIC_URBANIZATION" , 40 , "LOC_BOOST_TRIGGER_URBANIZATION" , "LOC_BOOST_TRIGGER_LONGDESC_URBANIZATION" , "BOOST_TRIGGER_CITY_POPULATION" , 24 ),
("CIVIC_IDEOLOGY" , 40 , "LOC_BOOST_TRIGGER_IDEOLOGY" , "LOC_BOOST_TRIGGER_LONGDESC_URBANIZATION" , "BOOST_TRIGGER_CITY_POPULATION" , 36 ),
("CIVIC_SOCIAL_MEDIA" , 40 , "LOC_BOOST_TRIGGER_SOCIAL_MEDIA" , "LOC_BOOST_TRIGGER_LONGDESC_SOCIAL_MEDIA" , "BOOST_TRIGGER_CITY_POPULATION" , 48 );

--改良鼓舞
INSERT OR REPLACE INTO Boosts 
(CivicType , Boost, TriggerDescription , TriggerLongDescription , BoostClass , ImprovementType , ResourceType , NumItems) VALUES
("CIVIC_GAMES_RECREATION" , 40 , "LOC_BOOST_TRIGGER_GAMES_RECREATION" , "LOC_BOOST_TRIGGER_LONGDESC_GAMES_RECREATION" , "BOOST_TRIGGER_HAVE_X_IMPROVEMENTS" , "IMPROVEMENT_CAMP" , null , 2 ),
("CIVIC_MASS_MEDIA" , 40 , "LOC_BOOST_TRIGGER_MASS_MEDIA" , "LOC_BOOST_TRIGGER_LONGDESC_MASS_MEDIA" , "BOOST_TRIGGER_HAVE_X_IMPROVEMENTS" , "IMPROVEMENT_CITY_PARK" , null , 3 ),
("CIVIC_CORPORATE_LIBERTARIANISM" , 40 , "LOC_BOOST_TRIGGER_CORPORATE_LIBERTARIANISM" , "LOC_BOOST_TRIGGER_LONGDESC_CORPORATE_LIBERTARIANISM" , "BOOST_TRIGGER_HAVE_X_IMPROVEMENTS" , "IMPROVEMENT_SKI_RESORT" , null , 3 );

--单位鼓舞
INSERT OR REPLACE INTO Boosts 
(CivicType , Boost, TriggerDescription , TriggerLongDescription , BoostClass , Unit1Type , NumItems) VALUES
("CIVIC_MEDIEVAL_FAIRES" , 40 , "LOC_BOOST_TRIGGER_MEDIEVAL_FAIRES" , "LOC_BOOST_TRIGGER_LONGDESC_MEDIEVAL_FAIRES" , "BOOST_TRIGGER_MAINTAIN_X_TRADE_ROUTES" , "UNIT_TRADER" , 3 ),
("CIVIC_SCORCHED_EARTH" , 40 , "LOC_BOOST_TRIGGER_SCORCHED_EARTH" , "LOC_BOOST_TRIGGER_LONGDESC_SCORCHED_EARTH" , "BOOST_TRIGGER_OWN_X_UNITS_OF_TYPE" , "UNIT_FIELD_CANNON" , 3 ),
("CIVIC_COLONIALISM" , 40 , "LOC_BOOST_TRIGGER_COLONIALISM" , "LOC_BOOST_TRIGGER_LONGDESC_COLONIALISM" , "BOOST_TRIGGER_OWN_X_UNITS_OF_TYPE" , "UNIT_PRIVATEER" , 3 ),
("CIVIC_EXPLORATION" , 40 , "LOC_BOOST_TRIGGER_EXPLORATION" , "LOC_BOOST_TRIGGER_LONGDESC_EXPLORATION" , "BOOST_TRIGGER_OWN_X_UNITS_OF_TYPE" , "UNIT_CARAVEL" , 3 ),
("CIVIC_SYNTHETIC_TECHNOCRACY" , 40 , "LOC_BOOST_TRIGGER_SYNTHETIC_TECHNOCRACY" , "LOC_BOOST_TRIGGER_LONGDESC_SYNTHETIC_TECHNOCRACY" , "BOOST_TRIGGER_OWN_X_UNITS_OF_TYPE" , "UNIT_GIANT_DEATH_ROBOT" , 1 ),
("CIVIC_DIGITAL_DEMOCRACY" , 40 , "LOC_BOOST_TRIGGER_DIGITAL_DEMOCRACY" , "LOC_BOOST_TRIGGER_LONGDESC_DIGITAL_DEMOCRACY" , "BOOST_TRIGGER_TRAIN_UNIT" , "UNIT_ROCK_BAND" , 2 );

--建筑鼓舞
INSERT OR REPLACE INTO Boosts 
(CivicType , Boost, TriggerDescription , TriggerLongDescription , BoostClass , BuildingType , NumItems) VALUES
("CIVIC_DIVINE_RIGHT" , 40 , "LOC_BOOST_TRIGGER_DIVINE_RIGHT" , "LOC_BOOST_TRIGGER_LONGDESC_DIVINE_RIGHT" , "BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_CASTLE" , 2 ),
("CIVIC_OPERA_BALLET" , 40 , "LOC_BOOST_TRIGGER_OPERA_BALLET" , "LOC_BOOST_TRIGGER_LONGDESC_OPERA_BALLET" , "BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_MUSEUM_ART" , 2 ),
("CIVIC_NATURAL_HISTORY" , 40 , "LOC_BOOST_TRIGGER_NATURAL_HISTORY" , "LOC_BOOST_TRIGGER_LONGDESC_NATURAL_HISTORY" , "BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_MUSEUM_ARTIFACT" , 2 ),
("CIVIC_SUFFRAGE" , 40 , "LOC_BOOST_TRIGGER_SUFFRAGE" , "LOC_BOOST_TRIGGER_LONGDESC_SUFFRAGE" , "BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_SEWER" , 3 ),
("CIVIC_NAVAL_TRADITION" , 40 , "LOC_BOOST_TRIGGER_NAVAL_TRADITION" , "LOC_BOOST_TRIGGER_LONGDESC_NAVAL_TRADITION" , "BOOST_TRIGGER_HAVE_X_BUILDINGS" , "BUILDING_LIGHTHOUSE" , 2 );

--区域鼓舞
INSERT OR REPLACE INTO Boosts 
(CivicType , Boost, TriggerDescription , TriggerLongDescription , BoostClass , DistrictType , NumItems) VALUES
("CIVIC_GUILDS" , 40 , "LOC_BOOST_TRIGGER_GUILDS" , "LOC_BOOST_TRIGGER_LONGDESC_GUILDS" , "BOOST_TRIGGER_HAVE_X_DISTRICTS" , "DISTRICT_COMMERCIAL_HUB" , 2 ),
("CIVIC_MILITARY_TRAINING" , 40 , "LOC_BOOST_TRIGGER_MILITARY_TRAINING" , "LOC_BOOST_TRIGGER_LONGDESC_MILITARY_TRAINING" , "BOOST_TRIGGER_HAVE_X_DISTRICTS" , "DISTRICT_ENCAMPMENT" , 2 ),
("CIVIC_PROFESSIONAL_SPORTS" , 40 , "LOC_BOOST_TRIGGER_PROFESSIONAL_SPORTS" , "LOC_BOOST_TRIGGER_LONGDESC_PROFESSIONAL_SPORTS" , "BOOST_TRIGGER_HAVE_X_DISTRICTS" , "DISTRICT_ENTERTAINMENT_COMPLEX" , 3 ),
("CIVIC_SPACE_RACE" , 40 , "LOC_BOOST_TRIGGER_SPACE_RACE" , "LOC_BOOST_TRIGGER_LONGDESC_SPACE_RACE" , "BOOST_TRIGGER_HAVE_X_DISTRICTS" , "DISTRICT_SPACEPORT" , 2 ),
("CIVIC_CIVIL_ENGINEERING" , 40 , "LOC_BOOST_TRIGGER_CIVIL_ENGINEERING" , "LOC_BOOST_TRIGGER_LONGDESC_CIVIL_ENGINEERING" , "BOOST_TRIGGER_HAVE_X_UNIQUE_SPECIALTY_DISTRICTS" , null , 6 );
INSERT OR REPLACE INTO Boosts 
(CivicType , Boost, TriggerDescription , TriggerLongDescription , BoostClass , DistrictType , NumItems) VALUES
("CIVIC_CAPITALISM" , 30 , "LOC_BOOST_TRIGGER_CAPITALISM" , "LOC_BOOST_TRIGGER_LONGDESC_CAPITALISM" , "BOOST_TRIGGER_HAVE_X_DISTRICTS" , "DISTRICT_COMMERCIAL_HUB" , 5 );

--伟人鼓舞
INSERT OR REPLACE INTO Boosts   
(CivicType , 				Boost , TriggerDescription , 					TriggerLongDescription , 								BoostClass ,					Unit1Type) VALUES
("CIVIC_HUMANISM" , 		30 , 	"LOC_BOOST_TRIGGER_HUMANISM" , 			"LOC_BOOST_TRIGGER_LONGDESC_HUMANISM" , 				"BOOST_TRIGGER_TRAIN_UNIT" ,	"UNIT_GREAT_WRITER"),
("CIVIC_OPERA_BALLET" , 	30 , 	"LOC_BOOST_TRIGGER_OPERA_BALLET" , 		"LOC_BOOST_TRIGGER_LONGDESC_OPERA_BALLET" , 			"BOOST_TRIGGER_TRAIN_UNIT" , 	"UNIT_GREAT_ARTIST"),
("CIVIC_MASS_MEDIA" , 		30 , 	"LOC_BOOST_TRIGGER_MASS_MEDIA" , 		"LOC_BOOST_TRIGGER_LONGDESC_MASS_MEDIA" ,	 			"BOOST_TRIGGER_TRAIN_UNIT" , 	"UNIT_GREAT_MUSICIAN");

--others
INSERT OR REPLACE INTO Boosts 
(CivicType , 				Boost, 	TriggerDescription , 					TriggerLongDescription , 						BoostClass , 								NumItems) VALUES
("CIVIC_NUCLEAR_PROGRAM" , 	40 , 	"LOC_BOOST_TRIGGER_NUCLEAR_PROGRAM" , 	"LOC_BOOST_TRIGGER_LONGDESC_NUCLEAR_PROGRAM" , 	"BOOST_TRIGGER_HAVE_ALLIANCE_LEVEL_X" , 	2 ),
("CIVIC_COLD_WAR" , 		40 , 	"LOC_BOOST_TRIGGER_COLD_WAR" , 			"LOC_BOOST_TRIGGER_LONGDESC_COLD_WAR" , 		"BOOST_TRIGGER_HAVE_ALLIANCE_LEVEL_X" ,  	3 );

INSERT OR REPLACE INTO Boosts 
(CivicType , 				Boost, 	TriggerDescription , 					TriggerLongDescription , 						BoostClass) VALUES
("CIVIC_ENVIRONMENTALISM" , 40 , 	"LOC_BOOST_TRIGGER_ENVIRONMENTALISM" , 	"LOC_BOOST_TRIGGER_LONGDESC_ENVIRONMENTALISM" , "BOOST_TRIGGER_CREATED_NATIONAL_PARK");

