INSERT OR REPLACE INTO District_Adjacencies 
(DistrictType,				YieldChangeId) VALUES
('DISTRICT_CAMPUS',          'GA_CAMPUS_SCIENCE'),
('DISTRICT_THEATER',         'GA_THEATER_CULTURE'),
('DISTRICT_HOLY_SITE',       'GA_HOLY_SITE_FAITH'),
('DISTRICT_COMMERCIAL_HUB',  'GA_COMMERCIAL_HUB_GOLD'),
('DISTRICT_INDUSTRIAL_ZONE', 'GA_INDUSTRIAL_ZONE_PRODUCTION'),
('DISTRICT_HARBOR',          'GA_HARBOR_GOLD'),
('DISTRICT_CAMPUS',          'GA_CAMPUS_SCIENCE_STANDARD'),
('DISTRICT_THEATER',         'GA_THEATER_CULTURE_STANDARD'),
('DISTRICT_HOLY_SITE',       'GA_HOLY_SITE_FAITH_STANDARD'),
('DISTRICT_COMMERCIAL_HUB',  'GA_COMMERCIAL_HUB_GOLD_STANDARD'),
('DISTRICT_INDUSTRIAL_ZONE', 'GA_INDUSTRIAL_ZONE_PRODUCTION_STANDARD'),
('DISTRICT_HARBOR',          'GA_HARBOR_GOLD_STANDARD'),
('DISTRICT_CAMPUS',          'GA_CAMPUS_SCIENCE_MEGA'),
('DISTRICT_THEATER',         'GA_THEATER_CULTURE_MEGA'),
('DISTRICT_HOLY_SITE',       'GA_HOLY_SITE_FAITH_MEGA'),
('DISTRICT_COMMERCIAL_HUB',  'GA_COMMERCIAL_HUB_GOLD_MEGA'),
('DISTRICT_INDUSTRIAL_ZONE', 'GA_INDUSTRIAL_ZONE_PRODUCTION_MEGA'),
('DISTRICT_HARBOR',          'GA_HARBOR_GOLD_MEGA');

INSERT OR REPLACE INTO Adjacency_YieldChanges 
(ID,										Description,								YieldType,				YieldChange,	TilesRequired,	AdjacentDistrict)
VALUES 
('GA_CAMPUS_SCIENCE_STANDARD',				'LOC_CAMPUS_SCIENCE_STANDARD',				'YIELD_SCIENCE',		1,				1,				'DISTRICT_CAMPUS'),
('GA_THEATER_CULTURE_STANDARD',				'LOC_THEATER_CULTURE_STANDARD',				'YIELD_CULTURE',		1,				1,				'DISTRICT_THEATER'),
('GA_HOLY_SITE_FAITH_STANDARD',				'LOC_HOLY_SITE_FAITH_STANDARD',				'YIELD_FAITH',			1,				1,				'DISTRICT_HOLY_SITE'),
('GA_COMMERCIAL_HUB_GOLD_STANDARD',			'LOC_COMMERCIAL_HUB_GOLD_STANDARD',			'YIELD_GOLD',			1,				1,				'DISTRICT_COMMERCIAL_HUB'),
('GA_INDUSTRIAL_ZONE_PRODUCTION_STANDARD',	'LOC_INDUSTRIAL_ZONE_PRODUCTION_STANDARD',	'YIELD_PRODUCTION',		1,				1,				'DISTRICT_INDUSTRIAL_ZONE'),
('GA_HARBOR_GOLD_STANDARD',					'LOC_HARBOR_GOLD_STANDARD',					'YIELD_GOLD',			1,				1,				'DISTRICT_HARBOR');
	
INSERT OR REPLACE INTO Adjacency_YieldChanges 
(ID,									Description,							YieldType,				YieldChange,	TilesRequired,	AdjacentDistrict,			PrereqCivic) 
VALUES
('GA_CAMPUS_SCIENCE',             		'LOC_CAMPUS_SCIENCE',             		'YIELD_SCIENCE',    	1,         		1,            	'DISTRICT_CAMPUS',           'CIVIC_CIVIL_SERVICE'),
('GA_THEATER_CULTURE',            		'LOC_THEATER_CULTURE',            		'YIELD_CULTURE',    	1,         		1,            	'DISTRICT_THEATER',          'CIVIC_CIVIL_SERVICE'),
('GA_HOLY_SITE_FAITH',            		'LOC_HOLY_SITE_FAITH',            		'YIELD_FAITH',      	1,         		1,            	'DISTRICT_HOLY_SITE',        'CIVIC_CIVIL_SERVICE'),
('GA_COMMERCIAL_HUB_GOLD',        		'LOC_COMMERCIAL_HUB_GOLD',        		'YIELD_GOLD',       	1,         		1,            	'DISTRICT_COMMERCIAL_HUB',   'CIVIC_CIVIL_SERVICE'),
('GA_INDUSTRIAL_ZONE_PRODUCTION', 		'LOC_INDUSTRIAL_ZONE_PRODUCTION', 		'YIELD_PRODUCTION', 	1,         		1,            	'DISTRICT_INDUSTRIAL_ZONE',  'CIVIC_CIVIL_SERVICE'),
('GA_HARBOR_GOLD',                		'LOC_HARBOR_GOLD',                		'YIELD_GOLD',       	1,         		1,            	'DISTRICT_HARBOR',           'CIVIC_CIVIL_SERVICE'),
('GA_CAMPUS_SCIENCE_MEGA',               'LOC_CAMPUS_SCIENCE_MEGA',              'YIELD_SCIENCE',     	1,          	1,            	'DISTRICT_CAMPUS',           'CIVIC_URBANIZATION'),
('GA_THEATER_CULTURE_MEGA',              'LOC_THEATER_CULTURE_MEGA',             'YIELD_CULTURE',     	1,          	1,            	'DISTRICT_THEATER',          'CIVIC_URBANIZATION'),
('GA_HOLY_SITE_FAITH_MEGA',              'LOC_HOLY_SITE_FAITH_MEGA',             'YIELD_FAITH',       	1,          	1,            	'DISTRICT_HOLY_SITE',        'CIVIC_URBANIZATION'),
('GA_COMMERCIAL_HUB_GOLD_MEGA',          'LOC_COMMERCIAL_HUB_GOLD_MEGA',         'YIELD_GOLD',        	1,          	1,            	'DISTRICT_COMMERCIAL_HUB',   'CIVIC_URBANIZATION'),
('GA_INDUSTRIAL_ZONE_PRODUCTION_MEGA',   'LOC_INDUSTRIAL_ZONE_PRODUCTION_MEGA',  'YIELD_PRODUCTION',  	1,          	1,            	'DISTRICT_INDUSTRIAL_ZONE',  'CIVIC_URBANIZATION'),
('GA_HARBOR_GOLD_MEGA',                  'LOC_HARBOR_GOLD_MEGA',                 'YIELD_GOLD',        	1,          	1,            	'DISTRICT_HARBOR',           'CIVIC_URBANIZATION');

-- Major
INSERT OR REPLACE INTO District_Adjacencies 
(DistrictType,						YieldChangeId) VALUES
('DISTRICT_HANSA',					'GA_HANSA_PRODUCTION'),
('DISTRICT_HANSA', 					'GA_HANSA_PRODUCTION_STANDARD'),
('DISTRICT_ACROPOLIS', 				'GA_ACROPOLIS_CULTURE'), 
('DISTRICT_ACROPOLIS', 				'GA_ACROPOLIS_CULTURE_STANDARD'), 
('DISTRICT_ROYAL_NAVY_DOCKYARD', 	'GA_ROYAL_NAVY_DOCKYARD_GOLD'), 
('DISTRICT_ROYAL_NAVY_DOCKYARD', 	'GA_ROYAL_NAVY_DOCKYARD_GOLD_STANDARD'), 
('DISTRICT_COTHON', 				'GA_COTHON_GOLD'),
('DISTRICT_COTHON', 				'GA_COTHON_GOLD_STANDARD'),
('DISTRICT_SUGUBA', 				'GA_SUGUBA_GOLD'),
('DISTRICT_SUGUBA', 				'GA_SUGUBA_GOLD_STANDARD'),
('DISTRICT_SEOWON', 				'GA_SEOWON_SCIENCE'),
('DISTRICT_SEOWON', 				'GA_SEOWON_SCIENCE_STANDARD'),
('DISTRICT_LAVRA', 					'GA_LAVRA_FAITH'),
('DISTRICT_LAVRA', 					'GA_LAVRA_FAITH_STANDARD'),

('DISTRICT_HANSA', 					'GA_HANSA_PRODUCTION_MEGA'),
('DISTRICT_ACROPOLIS', 				'GA_ACROPOLIS_CULTURE_MEGA'), 
('DISTRICT_ROYAL_NAVY_DOCKYARD', 	'GA_ROYAL_NAVY_DOCKYARD_GOLD_MEGA'), 
('DISTRICT_COTHON', 				'GA_COTHON_GOLD_MEGA'),
('DISTRICT_SUGUBA', 				'GA_SUGUBA_GOLD_MEGA'),
('DISTRICT_SEOWON', 				'GA_SEOWON_SCIENCE_MEGA'),
('DISTRICT_LAVRA', 					'GA_LAVRA_FAITH_MEGA');

INSERT OR REPLACE INTO Adjacency_YieldChanges 
(ID,											Description, 								YieldType, 					YieldChange, 	TilesRequired,	AdjacentDistrict) VALUES
('GA_SEOWON_SCIENCE_STANDARD', 				'LOC_CAMPUS_SCIENCE_STANDARD',			 	'YIELD_SCIENCE', 			1, 				1, 			'DISTRICT_SEOWON'),
('GA_ACROPOLIS_CULTURE_STANDARD', 			'LOC_THEATER_CULTURE_STANDARD', 			'YIELD_CULTURE', 			1, 				1, 			'DISTRICT_ACROPOLIS'),
('GA_LAVRA_FAITH_STANDARD', 				'LOC_HOLY_SITE_FAITH_STANDARD', 			'YIELD_FAITH', 				1, 				1, 			'DISTRICT_LAVRA'),
('GA_SUGUBA_GOLD_STANDARD', 				'LOC_COMMERCIAL_HUB_GOLD_STANDARD', 		'YIELD_GOLD', 				1, 				1, 			'DISTRICT_SUGUBA'),
('GA_HANSA_PRODUCTION_STANDARD', 			'LOC_INDUSTRIAL_ZONE_PRODUCTION_STANDARD', 	'YIELD_PRODUCTION', 		1, 				1, 			'DISTRICT_HANSA'),
('GA_ROYAL_NAVY_DOCKYARD_GOLD_STANDARD', 	'LOC_HARBOR_GOLD_STANDARD', 				'YIELD_GOLD', 				1, 				1, 			'DISTRICT_ROYAL_NAVY_DOCKYARD'),
('GA_COTHON_GOLD_STANDARD', 				'LOC_HARBOR_GOLD_STANDARD', 				'YIELD_GOLD', 				1, 				1, 			'DISTRICT_COTHON');

INSERT OR REPLACE INTO Adjacency_YieldChanges 
(ID,										Description, 							YieldType, 					YieldChange, 	TilesRequired,	AdjacentDistrict, 					PrereqCivic) VALUES
('GA_SEOWON_SCIENCE', 					'LOC_CAMPUS_SCIENCE', 					'YIELD_SCIENCE', 			1, 				1, 				'DISTRICT_SEOWON', 					'CIVIC_CIVIL_SERVICE'),
('GA_ACROPOLIS_CULTURE', 				'LOC_THEATER_CULTURE', 					'YIELD_CULTURE', 			1, 				1, 				'DISTRICT_ACROPOLIS', 				'CIVIC_CIVIL_SERVICE'),
('GA_LAVRA_FAITH', 						'LOC_HOLY_SITE_FAITH',					'YIELD_FAITH', 				1, 				1, 				'DISTRICT_LAVRA', 					'CIVIC_CIVIL_SERVICE'),
('GA_SUGUBA_GOLD', 						'LOC_COMMERCIAL_HUB_GOLD', 				'YIELD_GOLD', 				1, 				1, 				'DISTRICT_SUGUBA',					'CIVIC_CIVIL_SERVICE'),
('GA_HANSA_PRODUCTION', 				'LOC_INDUSTRIAL_ZONE_PRODUCTION', 		'YIELD_PRODUCTION', 		1, 				1, 				'DISTRICT_HANSA', 					'CIVIC_CIVIL_SERVICE'),
('GA_ROYAL_NAVY_DOCKYARD_GOLD', 		'LOC_HARBOR_GOLD', 						'YIELD_GOLD', 				1, 				1, 				'DISTRICT_ROYAL_NAVY_DOCKYARD', 	'CIVIC_CIVIL_SERVICE'),
('GA_COTHON_GOLD', 						'LOC_HARBOR_GOLD', 						'YIELD_GOLD', 				1, 				1, 				'DISTRICT_COTHON', 					'CIVIC_CIVIL_SERVICE'),
('GA_SEOWON_SCIENCE_MEGA', 				'LOC_CAMPUS_SCIENCE_MEGA',			 	'YIELD_SCIENCE', 			1, 				1, 				'DISTRICT_SEOWON', 					'CIVIC_URBANIZATION'),
('GA_ACROPOLIS_CULTURE_MEGA', 			'LOC_THEATER_CULTURE_MEGA', 			'YIELD_CULTURE', 			1, 				1, 				'DISTRICT_ACROPOLIS', 				'CIVIC_URBANIZATION'),
('GA_LAVRA_FAITH_MEGA', 				'LOC_HOLY_SITE_FAITH_MEGA', 			'YIELD_FAITH', 				1, 				1, 				'DISTRICT_LAVRA', 					'CIVIC_URBANIZATION'),
('GA_SUGUBA_GOLD_MEGA', 				'LOC_COMMERCIAL_HUB_GOLD_MEGA', 		'YIELD_GOLD', 				1, 				1, 				'DISTRICT_SUGUBA', 					'CIVIC_URBANIZATION'),
('GA_HANSA_PRODUCTION_MEGA', 			'LOC_INDUSTRIAL_ZONE_PRODUCTION_MEGA', 	'YIELD_PRODUCTION', 		1, 				1, 				'DISTRICT_HANSA', 					'CIVIC_URBANIZATION'),
('GA_ROYAL_NAVY_DOCKYARD_GOLD_MEGA', 	'LOC_HARBOR_GOLD_MEGA', 				'YIELD_GOLD', 				1, 				1, 				'DISTRICT_ROYAL_NAVY_DOCKYARD', 	'CIVIC_URBANIZATION'),
('GA_COTHON_GOLD_MEGA', 				'LOC_HARBOR_GOLD_MEGA', 				'YIELD_GOLD', 				1, 				1, 				'DISTRICT_COTHON', 					'CIVIC_URBANIZATION');

--DLC
--CIVILIZATION_MAYA
--DISTRICT_OBSERVATORY
INSERT OR REPLACE INTO District_Adjacencies (DistrictType, YieldChangeId)
SELECT	'DISTRICT_OBSERVATORY', 'GA_OBSERVATORY_OBSERVATORY' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_OBSERVATORY');
INSERT OR REPLACE INTO District_Adjacencies (DistrictType, YieldChangeId)
SELECT	'DISTRICT_OBSERVATORY', 'GA_OBSERVATORY_OBSERVATORY_PLUS' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_OBSERVATORY');
INSERT OR REPLACE INTO District_Adjacencies (DistrictType, YieldChangeId)
SELECT	'DISTRICT_OBSERVATORY', 'GA_OBSERVATORY_OBSERVATORY_MEGA' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_OBSERVATORY');
INSERT OR REPLACE INTO Adjacency_YieldChanges (ID, Description, YieldType, YieldChange, TilesRequired, AdjacentDistrict)
SELECT	'GA_OBSERVATORY_OBSERVATORY', 		'LOC_CAMPUS_SCIENCE_STANDARD', 'YIELD_SCIENCE', 1, 1, 'DISTRICT_OBSERVATORY' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_OBSERVATORY');
INSERT OR REPLACE INTO Adjacency_YieldChanges (ID, Description, YieldType, YieldChange, TilesRequired, AdjacentDistrict, PrereqCivic)
SELECT	'GA_OBSERVATORY_OBSERVATORY_PLUS', 'LOC_CAMPUS_SCIENCE', 'YIELD_SCIENCE', 1, 1, 'DISTRICT_OBSERVATORY', 'CIVIC_CIVIL_SERVICE' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_OBSERVATORY');
INSERT OR REPLACE INTO Adjacency_YieldChanges (ID, Description, YieldType, YieldChange, TilesRequired, AdjacentDistrict, PrereqCivic)
SELECT	'GA_OBSERVATORY_OBSERVATORY_MEGA', 'LOC_CAMPUS_SCIENCE_MEGA', 'YIELD_SCIENCE', 1, 1, 'DISTRICT_OBSERVATORY', 'CIVIC_URBANIZATION' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_OBSERVATORY');

--CIVILIZATION_GAUL
--DISTRICT_OPPIDUM
INSERT OR REPLACE INTO District_Adjacencies (DistrictType, YieldChangeId)
SELECT	'DISTRICT_OPPIDUM', 'GA_OPPIDUM_OPPIDUM' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_OPPIDUM');
INSERT OR REPLACE INTO District_Adjacencies (DistrictType, YieldChangeId)
SELECT	'DISTRICT_OPPIDUM', 'GA_OPPIDUM_OPPIDUM_PLUS' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_OPPIDUM');
INSERT OR REPLACE INTO District_Adjacencies (DistrictType, YieldChangeId)
SELECT	'DISTRICT_OPPIDUM', 'GA_OPPIDUM_OPPIDUM_MEGA' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_OPPIDUM');
INSERT OR REPLACE INTO Adjacency_YieldChanges (ID, Description, YieldType, YieldChange, TilesRequired, AdjacentDistrict)
SELECT	'GA_OPPIDUM_OPPIDUM', 		'LOC_INDUSTRIAL_ZONE_PRODUCTION_STANDARD', 'YIELD_PRODUCTION', 1, 1, 'DISTRICT_OPPIDUM' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_OPPIDUM');
INSERT OR REPLACE INTO Adjacency_YieldChanges (ID, Description, YieldType, YieldChange, TilesRequired, AdjacentDistrict, PrereqCivic)
SELECT	'GA_OPPIDUM_OPPIDUM_PLUS', 'LOC_INDUSTRIAL_ZONE_PRODUCTION', 'YIELD_PRODUCTION', 1, 1, 'DISTRICT_OPPIDUM', 'CIVIC_CIVIL_SERVICE' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_OPPIDUM');
INSERT OR REPLACE INTO Adjacency_YieldChanges (ID, Description, YieldType, YieldChange, TilesRequired, AdjacentDistrict, PrereqCivic)
SELECT	'GA_OPPIDUM_OPPIDUM_MEGA', 'LOC_INDUSTRIAL_ZONE_PRODUCTION_MEGA', 'YIELD_PRODUCTION', 1, 1, 'DISTRICT_OPPIDUM', 'CIVIC_URBANIZATION' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_OPPIDUM');

--军营、娱乐中心
INSERT OR REPLACE INTO TraitModifiers 
(TraitType,                 ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'GOLDEN_ENCAMPMENT_ENCAMPMENT_HOUSING'),
('TRAIT_LEADER_MAJOR_CIV', 'GOLDEN_ENTERTAINMENT_COMPLEX_ENTERTAINMENT_COMPLEX_AMENITY'),
('TRAIT_LEADER_MAJOR_CIV', 'GOLDEN_WATER_ENTERTAINMENT_COMPLEX_WATER_ENTERTAINMENT_COMPLEX_AMENITY');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,																	ModifierType, 												SubjectRequirementSetId) VALUES
('GOLDEN_ENCAMPMENT_ENCAMPMENT_HOUSING', 										'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING', 				'GOLDEN_DISTRICT_IS_ENCAMPMENT_ADJACENT_TO_ENCAMPMENT_REQUIREMENTS'),
('GOLDEN_ENTERTAINMENT_COMPLEX_ENTERTAINMENT_COMPLEX_AMENITY', 					'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT', 	'GOLDEN_DISTRICT_IS_ENTERTAINMENT_COMPLEX_ADJACENT_TO_ENTERTAINMENT_COMPLEX_REQUIREMENTS'),
('GOLDEN_WATER_ENTERTAINMENT_COMPLEX_WATER_ENTERTAINMENT_COMPLEX_AMENITY', 		'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT', 	'GOLDEN_DISTRICT_IS_WATER_ENTERTAINMENT_COMPLEX_ADJACENT_TO_WATER_ENTERTAINMENT_COMPLEX_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments
(ModifierId,																Name, 		Value) VALUES
('GOLDEN_ENCAMPMENT_ENCAMPMENT_HOUSING', 									'Amount', 	1),
('GOLDEN_ENTERTAINMENT_COMPLEX_ENTERTAINMENT_COMPLEX_AMENITY', 				'Amount', 	1),
('GOLDEN_WATER_ENTERTAINMENT_COMPLEX_WATER_ENTERTAINMENT_COMPLEX_AMENITY', 	'Amount', 	1);

INSERT OR REPLACE INTO RequirementSets 
(RequirementSetId,																							RequirementSetType) VALUES
('GOLDEN_DISTRICT_IS_ENCAMPMENT_ADJACENT_TO_ENCAMPMENT_REQUIREMENTS', 										'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_ENTERTAINMENT_COMPLEX_ADJACENT_TO_ENTERTAINMENT_COMPLEX_REQUIREMENTS', 				'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_WATER_ENTERTAINMENT_COMPLEX_ADJACENT_TO_WATER_ENTERTAINMENT_COMPLEX_REQUIREMENTS', 	'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements
(RequirementSetId,																							RequirementId) VALUES
('GOLDEN_DISTRICT_IS_ENCAMPMENT_ADJACENT_TO_ENCAMPMENT_REQUIREMENTS', 										'REQUIRES_DISTRICT_IS_ENCAMPMENT'),
('GOLDEN_DISTRICT_IS_ENCAMPMENT_ADJACENT_TO_ENCAMPMENT_REQUIREMENTS', 										'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_ENCAMPMENT'),
('GOLDEN_DISTRICT_IS_ENTERTAINMENT_COMPLEX_ADJACENT_TO_ENTERTAINMENT_COMPLEX_REQUIREMENTS', 				'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_ENTERTAINMENT_COMPLEX'),
('GOLDEN_DISTRICT_IS_ENTERTAINMENT_COMPLEX_ADJACENT_TO_ENTERTAINMENT_COMPLEX_REQUIREMENTS', 				'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_ENTERTAINMENT_COMPLEX'),
('GOLDEN_DISTRICT_IS_WATER_ENTERTAINMENT_COMPLEX_ADJACENT_TO_WATER_ENTERTAINMENT_COMPLEX_REQUIREMENTS', 	'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_WATER_ENTERTAINMENT_COMPLEX'),
('GOLDEN_DISTRICT_IS_WATER_ENTERTAINMENT_COMPLEX_ADJACENT_TO_WATER_ENTERTAINMENT_COMPLEX_REQUIREMENTS', 	'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_WATER_ENTERTAINMENT_COMPLEX');

--UD
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_CIVILIZATION_ZULU_ISIBONGO',	'GOLDEN_IKANDA_IKANDA_HOUSING'),
('TRAIT_CIVILIZATION_AMAZON',	        'GOLDEN_STREET_CARNIVAL_STREET_CARNIVAL_AMENITY'),
('TRAIT_CIVILIZATION_AMAZON',	        'GOLDEN_WATER_STREET_CARNIVAL_WATER_STREET_CARNIVAL_AMENITY');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES	
('GOLDEN_IKANDA_IKANDA_HOUSING',			        			'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_IKANDA_REQUIREMENTS'),
('GOLDEN_STREET_CARNIVAL_STREET_CARNIVAL_AMENITY',             	'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT',   	'GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_STREET_CARNIVAL_REQUIREMENTS'),
('GOLDEN_WATER_STREET_CARNIVAL_WATER_STREET_CARNIVAL_AMENITY', 	'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT',   	'GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_WATER_STREET_CARNIVAL_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_IKANDA_IKANDA_HOUSING',					       				 	'Amount',	    1),
('GOLDEN_STREET_CARNIVAL_STREET_CARNIVAL_AMENITY',				            'Amount',	    1),
('GOLDEN_WATER_STREET_CARNIVAL_WATER_STREET_CARNIVAL_AMENITY',				'Amount',	    1);

INSERT OR REPLACE INTO RequirementSets		(RequirementSetId,							RequirementSetType) VALUES
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_IKANDA_REQUIREMENTS',		            				'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_STREET_CARNIVAL_REQUIREMENTS',		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_WATER_STREET_CARNIVAL_REQUIREMENTS',		'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements		(RequirementSetId,							RequirementId) VALUES	
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_IKANDA_REQUIREMENTS',		    							'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_IKANDA'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_IKANDA_REQUIREMENTS',		    							'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_IKANDA'),
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_STREET_CARNIVAL_REQUIREMENTS',		        		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_STREET_CARNIVAL'),
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_STREET_CARNIVAL_REQUIREMENTS',		        		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_STREET_CARNIVAL'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_WATER_STREET_CARNIVAL_REQUIREMENTS',			'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_WATER_STREET_CARNIVAL'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_WATER_STREET_CARNIVAL_REQUIREMENTS',			'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_WATER_STREET_CARNIVAL');

--DLC
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
SELECT	'TRAIT_CIVILIZATION_BYZANTIUM', 'GOLDEN_HIPPODROME_HIPPODROME_AMENITY' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_HIPPODROME');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
SELECT	'GOLDEN_HIPPODROME_HIPPODROME_AMENITY', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT', 0, 0, 'GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_HIPPODROME_REQUIREMENTS' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_HIPPODROME');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_HIPPODROME_HIPPODROME_AMENITY', 'Amount', 1 WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_HIPPODROME');

INSERT OR REPLACE INTO RequirementSets		(RequirementSetId,							RequirementSetType) VALUES
('GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_HIPPODROME_REQUIREMENTS',		                'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements		(RequirementSetId,							RequirementId) VALUES	
('GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_HIPPODROME_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HIPPODROME'),
('GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_HIPPODROME_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_HIPPODROME');

INSERT OR REPLACE INTO Requirements (RequirementId,			RequirementType) VALUES	 
('GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HIPPODROME',	           'REQUIREMENT_DISTRICT_TYPE_MATCHES'),
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_HIPPODROME',	   'REQUIREMENT_PLOT_ADJACENT_DISTRICT_TYPE_MATCHES');

INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) VALUES
('GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HIPPODROME',		        'DistrictType',	    'DISTRICT_HIPPODROME'),
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_HIPPODROME',		'DistrictType',	    'DISTRICT_HIPPODROME');

--DLC
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
SELECT	'TRAIT_CIVILIZATION_VIETNAM', 'GOLDEN_THANH_THANH_HOUSING' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_THANH');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
SELECT	'GOLDEN_THANH_THANH_HOUSING', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING', 0, 0, 'GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_THANH_REQUIREMENTS' WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_THANH');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_THANH_THANH_HOUSING', 'Amount', 1 WHERE EXISTS (SELECT * FROM Districts WHERE DistrictType = 'DISTRICT_THANH');

INSERT OR REPLACE INTO RequirementSets		(RequirementSetId,							RequirementSetType) VALUES
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_THANH_REQUIREMENTS',		                'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements		(RequirementSetId,							RequirementId) VALUES	
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_THANH_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THANH'),
('GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_THANH_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_THANH');

INSERT OR REPLACE INTO Requirements (RequirementId,			RequirementType) VALUES	 
('GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THANH',	           		'REQUIREMENT_DISTRICT_TYPE_MATCHES'),
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_THANH',	   	'REQUIREMENT_PLOT_ADJACENT_DISTRICT_TYPE_MATCHES');

INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) VALUES
('GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THANH',		        	'DistrictType',	    'DISTRICT_THANH'),
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_THANH',		'DistrictType',	    'DISTRICT_THANH');