-- GoldenAge_Buildings_Expansion_Neighborhood
-- Author: Flactine
-- DateCreated: 1/31/2024 9:23:13 PM
--------------------------------------------------------------
INSERT OR REPLACE INTO Types
(Type,											Kind)	
VALUES
('BUILDING_GA_POLICEST',						'KIND_BUILDING'),
('BUILDING_GA_FIREST',							'KIND_BUILDING'),
('BUILDING_GA_CLINIC',							'KIND_BUILDING'),
('ABILITY_TRADER_PROTECTED_BY_GA_POLICEST',		'KIND_ABILITY');

INSERT OR REPLACE INTO Buildings
(BuildingType,				Name,								Description,								PrereqTech,					PrereqCivic,				Cost,	PrereqDistrict,				PurChaseYield,		Maintenance,	CitizenSlots,	Housing,	AdvisorType)
VALUES                                                                          	
('BUILDING_GA_POLICEST',	'LOC_BUILDING_GA_POLICEST_NAME',	'LOC_BUILDING_GA_POLICEST_DESCRIPTION',		Null,						'CIVIC_URBANIZATION',		800,	'DISTRICT_NEIGHBORHOOD',	'YIELD_GOLD',		3,				1,				0,			'ADVISOR_GENERIC'),
('BUILDING_GA_FIREST',		'LOC_BUILDING_GA_FIREST_NAME',		'LOC_BUILDING_GA_FIREST_DESCRIPTION',		'TECH_SCIENTIFIC_THEORY',	Null,						800,	'DISTRICT_NEIGHBORHOOD',	'YIELD_GOLD',		3,				1,				0,			'ADVISOR_GENERIC'),
('BUILDING_GA_CLINIC',		'LOC_BUILDING_GA_CLINIC_NAME',		'LOC_BUILDING_GA_CLINIC_DESCRIPTION',		'TECH_SANITATION',			Null,						800,	'DISTRICT_NEIGHBORHOOD',	'YIELD_GOLD',		3,				1,				3,			'ADVISOR_GENERIC');

INSERT OR REPLACE INTO Building_YieldChanges
(BuildingType,				YieldType,				YieldChange)	
VALUES
('BUILDING_GA_FIREST',		'YIELD_PRODUCTION',		1);

INSERT OR REPLACE INTO Buildings_XP2
(BuildingType,				Pillage)	
VALUES
('BUILDING_GA_FIREST',		0);

INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,				ModifierId)	
VALUES
('BUILDING_GA_POLICEST',	'GOLDEN_POLICEST_TRADER_IMMUNITY'),
('BUILDING_GA_FIREST',		'GOLDEN_FIREST_AUTOREPAIR_BUILDING'),
('BUILDING_GA_CLINIC',		'GOLDEN_CLINIC_ADD_CITY_GROWTH'),
('BUILDING_GA_CLINIC',		'GOLDEN_CLINIC_GRANT_UNIT_HEAL');

INSERT OR REPLACE INTO TraitModifiers
(TraitType,					ModifierId)	
VALUES
('TRAIT_LEADER_MAJOR_CIV',	'GOLDEN_POLICEST_SPY_DEBUFF');

INSERT OR REPLACE INTO Modifiers 
(ModifierId, 								ModifierType,									SubjectRequirementSetId) 
VALUES 
('GOLDEN_POLICEST_TRADER_IMMUNITY',			'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',			'REQSET_GABE_TRADER_NEAR_POLICEST'),
('GOLDEN_POLICEST_SPY_DEBUFF',				'MODIFIER_PLAYER_CITIES_ADJUST_SPY_BONUS',		'REQSET_GABE_CITY_HAS_POLICEST'),
('GOLDEN_FIREST_AUTOREPAIR_BUILDING',		'MODIFIER_SINGLE_CITY_ADJUST_PROPERTY',			Null),
('GOLDEN_CLINIC_ADD_CITY_GROWTH',			'MODIFIER_SINGLE_CITY_ADJUST_CITY_GROWTH',		Null),
('GOLDEN_CLINIC_GRANT_UNIT_HEAL',			'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER',		'REQSET_GABE_UNIT_NEAR_CLINIC'),
('GOLDEN_CLINIC_GRANT_UNIT_HEAL_MOD',		'MODIFIER_PLAYER_UNIT_ADJUST_HEAL_PER_TURN',	Null),
('GOLDEN_TRADER_IMMUNITY_FROM_POLICEST',	'MODIFIER_PLAYER_UNIT_ADJUST_TRADE_ROUTE_PLUNDER_IMMUNITY',	Null);




INSERT OR REPLACE INTO ModifierArguments 
(ModifierId, 								Name, 			Value) 
VALUES 
('GOLDEN_POLICEST_TRADER_IMMUNITY',			'AbilityType',	'ABILITY_TRADER_PROTECTED_BY_GA_POLICEST'),
('GOLDEN_POLICEST_SPY_DEBUFF',				'Amount',		2), 
('GOLDEN_FIREST_AUTOREPAIR_BUILDING',		'Key',			'PROP_GA_FIREST_AUTOREPAIR_BUILDING'),
('GOLDEN_FIREST_AUTOREPAIR_BUILDING',		'Amount',		1),
('GOLDEN_CLINIC_ADD_CITY_GROWTH',			'Amount',		20), 
('GOLDEN_CLINIC_GRANT_UNIT_HEAL',			'ModifierId',	'GOLDEN_CLINIC_GRANT_UNIT_HEAL_MOD'), 
('GOLDEN_CLINIC_GRANT_UNIT_HEAL_MOD',		'Type',			'ALL'),
('GOLDEN_CLINIC_GRANT_UNIT_HEAL_MOD',		'Amount',		20),
('GOLDEN_TRADER_IMMUNITY_FROM_POLICEST',	'DomainType',	'DOMAIN_LAND');

INSERT OR REPLACE INTO RequirementSets
(RequirementSetId,						RequirementSetType)	
VALUES
('REQSET_GABE_TRADER_NEAR_POLICEST',	'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_CITY_HAS_POLICEST',		'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_UNIT_NEAR_CLINIC',		'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements 
(RequirementSetId,						RequirementId) 
VALUES 
('REQSET_GABE_TRADER_NEAR_POLICEST',	'GOLDEN_REQUIRES_NEAR_POLICEST'),
('REQSET_GABE_CITY_HAS_POLICEST',		'GOLDEN_REQUIRES_CITY_HAS_POLICEST'),
('REQSET_GABE_UNIT_NEAR_CLINIC',		'GOLDEN_REQUIRES_NEAR_CLINIC');

INSERT OR REPLACE INTO Requirements
(RequirementId,							RequirementType)
VALUES 
('GOLDEN_REQUIRES_NEAR_POLICEST',		'REQUIREMENT_PLOT_NEARBY_UNIT_TAG_MATCHES'),
('GOLDEN_REQUIRES_CITY_HAS_POLICEST',	'REQUIREMENT_CITY_HAS_BUILDING'),
('GOLDEN_REQUIRES_NEAR_CLINIC',			'REQUIREMENT_PLOT_ADJACENT_TO_OWNER');

INSERT OR REPLACE INTO RequirementArguments
(RequirementId, 						Name, 			Value)
VALUES 
('GOLDEN_REQUIRES_NEAR_POLICEST',		'MinDistance',	0),
('GOLDEN_REQUIRES_NEAR_POLICEST',		'MaxDistance',	5),
('GOLDEN_REQUIRES_NEAR_POLICEST',		'Tag', 			'CLASS_TRADER'),
('GOLDEN_REQUIRES_CITY_HAS_POLICEST',	'BuildingType', 'BUILDING_GA_POLICEST'),
('GOLDEN_REQUIRES_NEAR_CLINIC',			'MinDistance',	0),
('GOLDEN_REQUIRES_NEAR_CLINIC',			'MaxDistance',	3);

INSERT OR REPLACE INTO TypeTags
(Type,											Tag)
VALUES 
('ABILITY_TRADER_PROTECTED_BY_GA_POLICEST',		'CLASS_TRADER');

INSERT OR REPLACE INTO UnitAbilities	
(UnitAbilityType,								Name,													Description,												Inactive)
VALUES
('ABILITY_TRADER_PROTECTED_BY_GA_POLICEST',		'LOC_ABILITY_TRADER_PROTECTED_BY_GA_POLICEST_NAME',		'LOC_ABILITY_TRADER_PROTECTED_BY_GA_POLICEST_DESCRIPTION',	1);

INSERT INTO UnitAbilityModifiers	
(UnitAbilityType,								ModifierId)
VALUES
('ABILITY_TRADER_PROTECTED_BY_GA_POLICEST',		'GOLDEN_TRADER_IMMUNITY_FROM_POLICEST');