--国家公园每点魅力值提供1金币
UPDATE	GlobalParameters SET Value = 1 WHERE Name = 'NATIONAL_PARK_GOLD_YIELD_PER_TOURISM';
----------------------------------------------------
--可再生资源改良设施
----------------------------------------------------
--提前解锁
UPDATE	Improvements SET PrereqTech = 'TECH_SYNTHETIC_MATERIALS' WHERE ImprovementType = 'IMPROVEMENT_WIND_FARM';
UPDATE	Improvements SET PrereqTech = 'TECH_COMPOSITES' WHERE ImprovementType = 'IMPROVEMENT_OFFSHORE_WIND_FARM';
--可在火山土和沼泽上造地热发电厂，可在雪地造太阳能发电厂，可在海洋造离岸发电厂
INSERT OR REPLACE INTO Improvement_ValidFeatures 
(ImprovementType,                FeatureType) VALUES	
('IMPROVEMENT_GEOTHERMAL_PLANT', 'FEATURE_MARSH'),
('IMPROVEMENT_GEOTHERMAL_PLANT', 'FEATURE_VOLCANIC_SOIL');
UPDATE Improvement_ValidTerrains SET PrereqTech='TECH_ADVANCED_POWER_CELLS' WHERE ImprovementType='IMPROVEMENT_SOLAR_FARM' AND TerrainType='TERRAIN_TUNDRA';
INSERT OR REPLACE INTO Improvement_ValidTerrains
(ImprovementType,					TerrainType,		PrereqTech) VALUES	
('IMPROVEMENT_SOLAR_FARM',			'TERRAIN_SNOW',		'TECH_ADVANCED_POWER_CELLS'),
('IMPROVEMENT_OFFSHORE_WIND_FARM',	'TERRAIN_OCEAN',	'TECH_SEASTEADS');
--产出均为2金币2生产力
UPDATE Improvement_YieldChanges SET YieldChange=2 WHERE YieldType='YIELD_PRODUCTION'	AND ImprovementType='IMPROVEMENT_GEOTHERMAL_PLANT';
UPDATE Improvement_YieldChanges SET YieldChange=0 WHERE YieldType='YIELD_SCIENCE'	    AND ImprovementType='IMPROVEMENT_GEOTHERMAL_PLANT';
UPDATE Improvement_YieldChanges SET YieldChange=2 WHERE YieldType='YIELD_GOLD'	        AND ImprovementType='IMPROVEMENT_GEOTHERMAL_PLANT';
UPDATE Improvement_YieldChanges SET YieldChange=2 WHERE YieldType='YIELD_PRODUCTION'	AND ImprovementType='IMPROVEMENT_WIND_FARM';
UPDATE Improvement_YieldChanges SET YieldChange=2 WHERE YieldType='YIELD_PRODUCTION'	AND ImprovementType='IMPROVEMENT_OFFSHORE_WIND_FARM';
UPDATE Improvement_YieldChanges SET YieldChange=2 WHERE YieldType='YIELD_PRODUCTION'	AND ImprovementType='IMPROVEMENT_SOLAR_FARM';
UPDATE Improvement_YieldChanges SET YieldChange=2 WHERE YieldType='YIELD_GOLD'		    AND ImprovementType='IMPROVEMENT_WIND_FARM';
UPDATE Improvement_YieldChanges SET YieldChange=2 WHERE YieldType='YIELD_GOLD'		    AND ImprovementType='IMPROVEMENT_OFFSHORE_WIND_FARM';
UPDATE Improvement_YieldChanges SET YieldChange=2 WHERE YieldType='YIELD_GOLD'		    AND ImprovementType='IMPROVEMENT_SOLAR_FARM';

--彼此相邻时额外+1电力		
INSERT OR REPLACE INTO ImprovementModifiers 
(ImprovementType,                   ModifierId) VALUES	
('IMPROVEMENT_SOLAR_FARM',	        'GOLDEN_SOLAR_FARM_BONUS_POWER_ADJACENT'),
('IMPROVEMENT_WIND_FARM',	        'GOLDEN_WIND_FARM_BONUS_POWER_ADJACENT'),
('IMPROVEMENT_OFFSHORE_WIND_FARM',	'GOLDEN_OFFSHORE_WIND_FARM_BONUS_POWER_ADJACENT'),
('IMPROVEMENT_GEOTHERMAL_PLANT',	'GOLDEN_GEOTHERMAL_PLANT_BONUS_POWER_ADJACENT');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,                                                    ModifierType,                             SubjectRequirementSetId) VALUES	
('GOLDEN_SOLAR_FARM_BONUS_POWER_ADJACENT',	                    'MODIFIER_SINGLE_CITY_ADJUST_FREE_POWER', 'GOLDEN_PLOT_IS_ADJACENT_TO_IMPROVEMENT_SOLAR_FARM_REQUIREMENTS'),
('GOLDEN_WIND_FARM_BONUS_POWER_ADJACENT',	                    'MODIFIER_SINGLE_CITY_ADJUST_FREE_POWER', 'GOLDEN_PLOT_IS_ADJACENT_TO_IMPROVEMENT_WIND_FARM_REQUIREMENTS'),
('GOLDEN_OFFSHORE_WIND_FARM_BONUS_POWER_ADJACENT',	            'MODIFIER_SINGLE_CITY_ADJUST_FREE_POWER', 'GOLDEN_PLOT_IS_ADJACENT_TO_IMPROVEMENT_OFFSHORE_WIND_FARM_REQUIREMENTS'),
('GOLDEN_GEOTHERMAL_PLANT_BONUS_POWER_ADJACENT',	            'MODIFIER_SINGLE_CITY_ADJUST_FREE_POWER', 'GOLDEN_PLOT_IS_ADJACENT_TO_IMPROVEMENT_GEOTHERMAL_PLANT_REQUIREMENTS');

INSERT OR IGNORE INTO ModifierArguments
(ModifierId,													Name,			Value) VALUES	
('GOLDEN_SOLAR_FARM_BONUS_POWER_ADJACENT',						'SourceType',	'FREE_POWER_SOURCE_SOLAR'),
('GOLDEN_SOLAR_FARM_BONUS_POWER_ADJACENT',						'Amount',		1),
('GOLDEN_WIND_FARM_BONUS_POWER_ADJACENT',						'SourceType',	'FREE_POWER_SOURCE_WIND'),
('GOLDEN_WIND_FARM_BONUS_POWER_ADJACENT',						'Amount',		1),
('GOLDEN_OFFSHORE_WIND_FARM_BONUS_POWER_ADJACENT',				'SourceType',	'FREE_POWER_SOURCE_WIND'),
('GOLDEN_OFFSHORE_WIND_FARM_BONUS_POWER_ADJACENT',				'Amount',		1),
('GOLDEN_GEOTHERMAL_PLANT_BONUS_POWER_ADJACENT',				'SourceType',	'FREE_POWER_SOURCE_GEOTHERMAL'),
('GOLDEN_GEOTHERMAL_PLANT_BONUS_POWER_ADJACENT',				'Amount',		1);

--造对地方额外电力
INSERT OR REPLACE INTO ImprovementModifiers 
(ImprovementType,                   ModifierId) VALUES	
('IMPROVEMENT_GEOTHERMAL_PLANT',	'GOLDEN_GEOTHERMAL_PLANT_BONUS_POWER_MARSH'),
('IMPROVEMENT_GEOTHERMAL_PLANT',	'GOLDEN_GEOTHERMAL_PLANT_BONUS_POWER_GEOTHERMAL_FISSURE'),
('IMPROVEMENT_SOLAR_FARM',	        'GOLDEN_SOLAR_FARM_BONUS_POWER_DESERT'),
('IMPROVEMENT_WIND_FARM',	        'GOLDEN_WIND_FARM_BONUS_POWER_COASTAL'),
('IMPROVEMENT_OFFSHORE_WIND_FARM',	'GOLDEN_OFFSHORE_WIND_FARM_BONUS_POWER_OCEAN');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,                                                    ModifierType,                             SubjectRequirementSetId) VALUES	
('GOLDEN_GEOTHERMAL_PLANT_BONUS_POWER_MARSH',	                'MODIFIER_SINGLE_CITY_ADJUST_FREE_POWER', 'GOLDEN_PLOT_HAS_MARSH_REQUIREMENTS'),
('GOLDEN_GEOTHERMAL_PLANT_BONUS_POWER_GEOTHERMAL_FISSURE',	    'MODIFIER_SINGLE_CITY_ADJUST_FREE_POWER', 'GOLDEN_PLOT_HAS_GEOTHERMAL_FISSURE_REQUIREMENTS'),
('GOLDEN_SOLAR_FARM_BONUS_POWER_DESERT',	                    'MODIFIER_SINGLE_CITY_ADJUST_FREE_POWER', 'GOLDEN_PLOT_HAS_ANY_DESERT_REQUIREMENTS'),
('GOLDEN_WIND_FARM_BONUS_POWER_COASTAL',	                    'MODIFIER_SINGLE_CITY_ADJUST_FREE_POWER', 'GOLDEN_PLOT_ADJACENT_TO_COAST_REQUIREMENTS'),
('GOLDEN_OFFSHORE_WIND_FARM_BONUS_POWER_OCEAN',	                'MODIFIER_SINGLE_CITY_ADJUST_FREE_POWER', 'GOLDEN_PLOT_HAS_OCEAN_REQUIREMENTS');

INSERT OR IGNORE INTO ModifierArguments
(ModifierId,													Name,			Value) VALUES	
('GOLDEN_GEOTHERMAL_PLANT_BONUS_POWER_MARSH',					'SourceType',	'FREE_POWER_SOURCE_GEOTHERMAL'),
('GOLDEN_GEOTHERMAL_PLANT_BONUS_POWER_MARSH',					'Amount',		2),
('GOLDEN_GEOTHERMAL_PLANT_BONUS_POWER_GEOTHERMAL_FISSURE',		'SourceType',	'FREE_POWER_SOURCE_GEOTHERMAL'),
('GOLDEN_GEOTHERMAL_PLANT_BONUS_POWER_GEOTHERMAL_FISSURE',		'Amount',		2),
('GOLDEN_SOLAR_FARM_BONUS_POWER_DESERT',						'SourceType',	'FREE_POWER_SOURCE_SOLAR'),
('GOLDEN_SOLAR_FARM_BONUS_POWER_DESERT',						'Amount',		1),
('GOLDEN_WIND_FARM_BONUS_POWER_COASTAL',						'SourceType',	'FREE_POWER_SOURCE_WIND'),
('GOLDEN_WIND_FARM_BONUS_POWER_COASTAL',						'Amount',		1),
('GOLDEN_OFFSHORE_WIND_FARM_BONUS_POWER_OCEAN',				    'SourceType',	'FREE_POWER_SOURCE_WIND'),
('GOLDEN_OFFSHORE_WIND_FARM_BONUS_POWER_OCEAN',				    'Amount',		1);

--造对地方时+2金币
INSERT OR REPLACE INTO ImprovementModifiers 
(ImprovementType,                   ModifierId) VALUES	
('IMPROVEMENT_GEOTHERMAL_PLANT',	'GOLDEN_GEOTHERMAL_PLANT_BONUS_GOLD_MARSH'),
('IMPROVEMENT_GEOTHERMAL_PLANT',	'GOLDEN_GEOTHERMAL_PLANT_BONUS_GOLD_GEOTHERMAL_FISSURE'),
('IMPROVEMENT_SOLAR_FARM',	        'GOLDEN_SOLAR_FARM_BONUS_GOLD_DESERT'),
('IMPROVEMENT_WIND_FARM',	        'GOLDEN_WIND_FARM_BONUS_GOLD_COASTAL'),
('IMPROVEMENT_OFFSHORE_WIND_FARM',	'GOLDEN_OFFSHORE_WIND_FARM_BONUS_GOLD_OCEAN');

INSERT OR REPLACE INTO Modifiers 
(ModifierId,                                                    ModifierType,                             SubjectRequirementSetId) VALUES	
('GOLDEN_GEOTHERMAL_PLANT_BONUS_GOLD_MARSH',	                'MODIFIER_SINGLE_PLOT_ADJUST_PLOT_YIELDS', 'GOLDEN_PLOT_HAS_MARSH_REQUIREMENTS'),
('GOLDEN_GEOTHERMAL_PLANT_BONUS_GOLD_GEOTHERMAL_FISSURE',	    'MODIFIER_SINGLE_PLOT_ADJUST_PLOT_YIELDS', 'GOLDEN_PLOT_HAS_GEOTHERMAL_FISSURE_REQUIREMENTS'),
('GOLDEN_SOLAR_FARM_BONUS_GOLD_DESERT',	                        'MODIFIER_SINGLE_PLOT_ADJUST_PLOT_YIELDS', 'GOLDEN_PLOT_HAS_ANY_DESERT_REQUIREMENTS'),
('GOLDEN_WIND_FARM_BONUS_GOLD_COASTAL',	                        'MODIFIER_SINGLE_PLOT_ADJUST_PLOT_YIELDS', 'GOLDEN_PLOT_ADJACENT_TO_COAST_REQUIREMENTS'),
('GOLDEN_OFFSHORE_WIND_FARM_BONUS_GOLD_OCEAN',	                'MODIFIER_SINGLE_PLOT_ADJUST_PLOT_YIELDS', 'GOLDEN_PLOT_HAS_OCEAN_REQUIREMENTS');

INSERT OR IGNORE INTO ModifierArguments
(ModifierId,								                    Name,			Value) VALUES	
('GOLDEN_GEOTHERMAL_PLANT_BONUS_GOLD_MARSH',	                'YieldType',	'YIELD_GOLD'),
('GOLDEN_GEOTHERMAL_PLANT_BONUS_GOLD_MARSH',	                'Amount',		2),
('GOLDEN_GEOTHERMAL_PLANT_BONUS_GOLD_GEOTHERMAL_FISSURE',		'YieldType',	'YIELD_GOLD'),
('GOLDEN_GEOTHERMAL_PLANT_BONUS_GOLD_GEOTHERMAL_FISSURE',		'Amount',		2),
('GOLDEN_SOLAR_FARM_BONUS_GOLD_DESERT',				            'YieldType',	'YIELD_GOLD'),
('GOLDEN_SOLAR_FARM_BONUS_GOLD_DESERT',				            'Amount',		2),
('GOLDEN_WIND_FARM_BONUS_GOLD_COASTAL',		                    'YieldType',	'YIELD_GOLD'),
('GOLDEN_WIND_FARM_BONUS_GOLD_COASTAL',		                    'Amount',		2),
('GOLDEN_OFFSHORE_WIND_FARM_BONUS_GOLD_OCEAN',			    	'YieldType',	'YIELD_GOLD'),
('GOLDEN_OFFSHORE_WIND_FARM_BONUS_GOLD_OCEAN',				    'Amount',		2);
		
--基础电力均上调为2
UPDATE ModifierArguments SET Value=2 WHERE Name='Amount' AND ModifierId='SOLAR_FARM_GENERATE_POWER';
UPDATE ModifierArguments SET Value=2 WHERE Name='Amount' AND ModifierId='WIND_FARM_GENERATE_POWER';
UPDATE ModifierArguments SET Value=2 WHERE Name='Amount' AND ModifierId='OFFSHORE_WIND_FARM_GENERATE_POWER';
UPDATE ModifierArguments SET Value=2 WHERE Name='Amount' AND ModifierId='GEOTHERMAL_GENERATE_POWER';

INSERT OR REPLACE INTO RequirementSets 				(RequirementSetId ,         RequirementSetType) 	VALUES 		
('GOLDEN_PLOT_IS_ADJACENT_TO_IMPROVEMENT_GEOTHERMAL_PLANT_REQUIREMENTS' , 		    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLOT_IS_ADJACENT_TO_IMPROVEMENT_SOLAR_FARM_REQUIREMENTS' , 		        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLOT_IS_ADJACENT_TO_IMPROVEMENT_WIND_FARM_REQUIREMENTS' , 		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLOT_IS_ADJACENT_TO_IMPROVEMENT_OFFSHORE_WIND_FARM_REQUIREMENTS' , 		'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,         RequirementId) 			VALUES 		
('GOLDEN_PLOT_IS_ADJACENT_TO_IMPROVEMENT_GEOTHERMAL_PLANT_REQUIREMENTS' , 		    'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_GEOTHERMAL_PLANT'),
('GOLDEN_PLOT_IS_ADJACENT_TO_IMPROVEMENT_SOLAR_FARM_REQUIREMENTS' , 		        'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_SOLAR_FARM'),
('GOLDEN_PLOT_IS_ADJACENT_TO_IMPROVEMENT_WIND_FARM_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_WIND_FARM'),
('GOLDEN_PLOT_IS_ADJACENT_TO_IMPROVEMENT_OFFSHORE_WIND_FARM_REQUIREMENTS' , 		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_OFFSHORE_WIND_FARM');			

INSERT OR REPLACE INTO 		Requirements (RequirementId,				            RequirementType) VALUES				    
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_GEOTHERMAL_PLANT',	'REQUIREMENT_PLOT_ADJACENT_IMPROVEMENT_TYPE_MATCHES'),
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_SOLAR_FARM',	        'REQUIREMENT_PLOT_ADJACENT_IMPROVEMENT_TYPE_MATCHES'),
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_WIND_FARM',      	    'REQUIREMENT_PLOT_ADJACENT_IMPROVEMENT_TYPE_MATCHES'),
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_OFFSHORE_WIND_FARM',	'REQUIREMENT_PLOT_ADJACENT_IMPROVEMENT_TYPE_MATCHES');									
	
INSERT OR REPLACE INTO 		RequirementArguments (RequirementId,		                Name,			        Value) VALUES					    
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_GEOTHERMAL_PLANT',		'ImprovementType',		'IMPROVEMENT_GEOTHERMAL_PLANT'),
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_SOLAR_FARM',		        'ImprovementType',		'IMPROVEMENT_SOLAR_FARM'),
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_WIND_FARM',	        	'ImprovementType',		'IMPROVEMENT_WIND_FARM'),
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_OFFSHORE_WIND_FARM',		'ImprovementType',		'IMPROVEMENT_OFFSHORE_WIND_FARM');		