UPDATE Buildings 
SET Cost = 220, PrereqCivic = 'CIVIC_HUMANISM'
WHERE BuildingType = 'BUILDING_SANCTUARY';

INSERT OR REPLACE INTO Types
(Type,									Kind)	
VALUES
('BUILDING_GA_FOREST_RESERVE',			'KIND_BUILDING'),
('BUILDING_GA_FLOODPLAINS_RESERVE',		'KIND_BUILDING'),
('BUILDING_GA_WONDER_RESERVE',			'KIND_BUILDING');

INSERT OR REPLACE INTO Buildings
(BuildingType,							Name,											Description,										PrereqCivic,			Cost,	PrereqDistrict,			PurChaseYield,		AdvisorType)
VALUES        
('BUILDING_GA_FOREST_RESERVE',			'LOC_BUILDING_GA_FOREST_RESERVE_NAME',			'LOC_BUILDING_GA_FOREST_RESERVE_DESCRIPTION',		'CIVIC_CONSERVATION',	440,	'DISTRICT_PRESERVE',	'YIELD_GOLD',		'ADVISOR_CULTURE'),                                                                  
('BUILDING_GA_FLOODPLAINS_RESERVE',		'LOC_BUILDING_GA_FLOODPLAINS_RESERVE_NAME',		'LOC_BUILDING_GA_FLOODPLAINS_RESERVE_DESCRIPTION',	'CIVIC_CONSERVATION',	440,	'DISTRICT_PRESERVE',	'YIELD_GOLD',		'ADVISOR_CULTURE'),
('BUILDING_GA_WONDER_RESERVE',			'LOC_BUILDING_GA_WONDER_RESERVE_NAME',			'LOC_BUILDING_GA_WONDER_RESERVE_DESCRIPTION',		'CIVIC_CONSERVATION',	440,	'DISTRICT_PRESERVE',	'YIELD_GOLD',		'ADVISOR_CULTURE');

INSERT OR REPLACE INTO BuildingPrereqs
(Building,								PrereqBuilding)	
VALUES
('BUILDING_SANCTUARY',					'BUILDING_GROVE'),
('BUILDING_GA_FOREST_RESERVE',			'BUILDING_SANCTUARY'),
('BUILDING_GA_FLOODPLAINS_RESERVE',		'BUILDING_SANCTUARY'),
('BUILDING_GA_WONDER_RESERVE',			'BUILDING_SANCTUARY');

INSERT OR REPLACE INTO MutuallyExclusiveBuildings
(Building,								MutuallyExclusiveBuilding)
VALUES
('BUILDING_GA_FOREST_RESERVE',			'BUILDING_GA_FLOODPLAINS_RESERVE'),
('BUILDING_GA_FOREST_RESERVE',			'BUILDING_GA_WONDER_RESERVE'),
('BUILDING_GA_FLOODPLAINS_RESERVE',		'BUILDING_GA_FOREST_RESERVE'),
('BUILDING_GA_FLOODPLAINS_RESERVE',		'BUILDING_GA_WONDER_RESERVE'),
('BUILDING_GA_WONDER_RESERVE',			'BUILDING_GA_FOREST_RESERVE'),
('BUILDING_GA_WONDER_RESERVE',			'BUILDING_GA_FLOODPLAINS_RESERVE');

INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,							ModifierId)	
VALUES
('BUILDING_GA_FOREST_RESERVE',			'MODIFIER_GA_RESERVE_T3_BUILDING_TOURISM'),
('BUILDING_GA_FOREST_RESERVE',			'MODIFIER_GA_FOREST_RESERVE_FOREST_OR_JUNGLE_CULTURE'),
('BUILDING_GA_FOREST_RESERVE',			'MODIFIER_GA_FOREST_RESERVE_FOREST_OR_JUNGLE_FAITH'),
('BUILDING_GA_FLOODPLAINS_RESERVE',		'MODIFIER_GA_RESERVE_T3_BUILDING_TOURISM'),
('BUILDING_GA_FLOODPLAINS_RESERVE',		'MODIFIER_GA_FLOODPLAINS_RESERVE_FLOODPLAINS_CULTURE'),
('BUILDING_GA_FLOODPLAINS_RESERVE',		'MODIFIER_GA_FLOODPLAINS_RESERVE_FLOODPLAINS_FAITH'),
('BUILDING_GA_WONDER_RESERVE',			'MODIFIER_GA_RESERVE_T3_BUILDING_TOURISM'),
('BUILDING_GA_WONDER_RESERVE',			'MODIFIER_GA_WONDER_RESERVE_ADJACENT_WONDER_CULTURE'),
('BUILDING_GA_WONDER_RESERVE',			'MODIFIER_GA_WONDER_RESERVE_ADJACENT_WONDER_FAITH');

INSERT OR REPLACE INTO TraitModifiers
(TraitType, 				ModifierId)
VALUES
('TRAIT_LEADER_MAJOR_CIV',	'MODIFIER_GA_FOREST_RESERVE_FEATURE_FOREST_APPEAL'),
('TRAIT_LEADER_MAJOR_CIV',	'MODIFIER_GA_FOREST_RESERVE_FEATURE_JUNGLE_APPEAL'),
('TRAIT_LEADER_MAJOR_CIV',	'MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_OASIS_APPEAL'),
('TRAIT_LEADER_MAJOR_CIV',	'MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_MARSH_APPEAL'),
('TRAIT_LEADER_MAJOR_CIV',	'MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_APPEAL'),
('TRAIT_LEADER_MAJOR_CIV',	'MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_GRASSLAND_APPEAL'),
('TRAIT_LEADER_MAJOR_CIV',	'MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_PLAINS_APPEAL'),
('TRAIT_LEADER_MAJOR_CIV',	'MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_TUNDRA_APPEAL'),
('TRAIT_LEADER_MAJOR_CIV',	'MODIFIER_GA_WONDER_RESERVE_NATIONAL_PARK_APPEAL');

INSERT OR REPLACE INTO Modifiers 
(ModifierId, 																ModifierType,												SubjectRequirementSetId) 
VALUES
('MODIFIER_GA_RESERVE_T3_BUILDING_TOURISM',									'MODIFIER_PLAYER_DISTRICT_ADJUST_TOURISM_CHANGE',			Null),
('MODIFIER_GA_FOREST_RESERVE_FOREST_OR_JUNGLE_CULTURE',						'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',				'REQSET_GABE_PLOT_IS_FEATURE_FOREST_OR_JUNGLE'),
('MODIFIER_GA_FOREST_RESERVE_FOREST_OR_JUNGLE_FAITH',						'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',				'REQSET_GABE_PLOT_IS_FEATURE_FOREST_OR_JUNGLE'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FLOODPLAINS_CULTURE',						'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',				'REQSET_GABE_PLOT_IS_FEATURE_FLOODPLAINS_ETC'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FLOODPLAINS_FAITH',						'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',				'REQSET_GABE_PLOT_IS_FEATURE_FLOODPLAINS_ETC'),
('MODIFIER_GA_WONDER_RESERVE_ADJACENT_WONDER_CULTURE',						'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',				'REQSET_GABE_PLOT_IS_ADJACENT_NATURAL_WONDER'),
('MODIFIER_GA_WONDER_RESERVE_ADJACENT_WONDER_FAITH',						'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',				'REQSET_GABE_PLOT_IS_ADJACENT_NATURAL_WONDER'),
('MODIFIER_GA_FOREST_RESERVE_FEATURE_FOREST_APPEAL',						'MODIFIER_PLAYER_CITIES_ADJUST_FEATURE_APPEAL_MODIFIER',	'REQSET_GABE_CITY_HAS_BUILDING_GA_FOREST_RESERVE'),
('MODIFIER_GA_FOREST_RESERVE_FEATURE_JUNGLE_APPEAL',						'MODIFIER_PLAYER_CITIES_ADJUST_FEATURE_APPEAL_MODIFIER',	'REQSET_GABE_CITY_HAS_BUILDING_GA_FOREST_RESERVE'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_OASIS_APPEAL',					'MODIFIER_PLAYER_CITIES_ADJUST_FEATURE_APPEAL_MODIFIER',	'REQSET_GABE_CITY_HAS_BUILDING_GA_FLOODPLAINS_RESERVE'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_MARSH_APPEAL',					'MODIFIER_PLAYER_CITIES_ADJUST_FEATURE_APPEAL_MODIFIER',	'REQSET_GABE_CITY_HAS_BUILDING_GA_FLOODPLAINS_RESERVE'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_APPEAL',				'MODIFIER_PLAYER_CITIES_ADJUST_FEATURE_APPEAL_MODIFIER',	'REQSET_GABE_CITY_HAS_BUILDING_GA_FLOODPLAINS_RESERVE'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_GRASSLAND_APPEAL',	'MODIFIER_PLAYER_CITIES_ADJUST_FEATURE_APPEAL_MODIFIER',	'REQSET_GABE_CITY_HAS_BUILDING_GA_FLOODPLAINS_RESERVE'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_PLAINS_APPEAL',		'MODIFIER_PLAYER_CITIES_ADJUST_FEATURE_APPEAL_MODIFIER',	'REQSET_GABE_CITY_HAS_BUILDING_GA_FLOODPLAINS_RESERVE'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_TUNDRA_APPEAL',		'MODIFIER_PLAYER_CITIES_ADJUST_FEATURE_APPEAL_MODIFIER',	'REQSET_GABE_CITY_HAS_BUILDING_GA_FLOODPLAINS_RESERVE'),
('MODIFIER_GA_WONDER_RESERVE_NATIONAL_PARK_APPEAL',							'MODIFIER_PLAYER_CITIES_ADJUST_CITY_APPEAL',				'REQSET_GABE_CITY_HAS_BUILDING_GA_WONDER_RESERVE_AND_NATIONAL_PARK');

INSERT OR REPLACE INTO ModifierArguments
(ModifierId,																Name,			Value)
VALUES 
('MODIFIER_GA_RESERVE_T3_BUILDING_TOURISM', 								'Amount',		5),
('MODIFIER_GA_FOREST_RESERVE_FOREST_OR_JUNGLE_CULTURE', 					'YieldType' , 	'YIELD_CULTURE'),
('MODIFIER_GA_FOREST_RESERVE_FOREST_OR_JUNGLE_CULTURE', 					'Amount' , 		1),
('MODIFIER_GA_FOREST_RESERVE_FOREST_OR_JUNGLE_FAITH', 						'YieldType' , 	'YIELD_FAITH'),
('MODIFIER_GA_FOREST_RESERVE_FOREST_OR_JUNGLE_FAITH', 						'Amount' , 		1),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FLOODPLAINS_CULTURE', 					'YieldType' , 	'YIELD_CULTURE'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FLOODPLAINS_CULTURE', 					'Amount' , 		1),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FLOODPLAINS_FAITH', 						'YieldType' , 	'YIELD_FAITH'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FLOODPLAINS_FAITH', 						'Amount' , 		1),
('MODIFIER_GA_WONDER_RESERVE_ADJACENT_WONDER_CULTURE', 						'YieldType' , 	'YIELD_CULTURE'),
('MODIFIER_GA_WONDER_RESERVE_ADJACENT_WONDER_CULTURE', 						'Amount' , 		2),
('MODIFIER_GA_WONDER_RESERVE_ADJACENT_WONDER_FAITH', 						'YieldType' , 	'YIELD_FAITH'),
('MODIFIER_GA_WONDER_RESERVE_ADJACENT_WONDER_FAITH', 						'Amount' , 		2),
('MODIFIER_GA_FOREST_RESERVE_FEATURE_FOREST_APPEAL', 						'FeatureType', 	'FEATURE_FOREST'),
('MODIFIER_GA_FOREST_RESERVE_FEATURE_FOREST_APPEAL', 						'Amount', 		1),
('MODIFIER_GA_FOREST_RESERVE_FEATURE_JUNGLE_APPEAL', 						'FeatureType', 	'FEATURE_JUNGLE'),
('MODIFIER_GA_FOREST_RESERVE_FEATURE_JUNGLE_APPEAL', 						'Amount', 		1),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_OASIS_APPEAL', 					'FeatureType', 	'FEATURE_OASIS'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_OASIS_APPEAL', 					'Amount', 		1),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_MARSH_APPEAL', 					'FeatureType', 	'FEATURE_MARSH'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_MARSH_APPEAL', 					'Amount', 		1),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_APPEAL', 				'FeatureType', 	'FEATURE_FLOODPLAINS'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_APPEAL', 				'Amount', 		1),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_GRASSLAND_APPEAL', 	'FeatureType', 	'FEATURE_FLOODPLAINS_GRASSLAND'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_GRASSLAND_APPEAL', 	'Amount', 		1),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_PLAINS_APPEAL', 		'FeatureType', 	'FEATURE_FLOODPLAINS_PLAINS'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_PLAINS_APPEAL', 		'Amount', 		1),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_TUNDRA_APPEAL', 		'FeatureType', 	'FEATURE_FLOODPLAINS_TUNDRA'),
('MODIFIER_GA_FLOODPLAINS_RESERVE_FEATURE_FLOODPLAINS_TUNDRA_APPEAL', 		'Amount', 		1),
('MODIFIER_GA_WONDER_RESERVE_NATIONAL_PARK_APPEAL', 						'Amount', 		1);

INSERT INTO RequirementSets
(RequirementSetId,														RequirementSetType)
VALUES
('REQSET_GABE_PLOT_IS_FEATURE_FOREST_OR_JUNGLE',						'REQUIREMENTSET_TEST_ANY'),
('REQSET_GABE_PLOT_IS_FEATURE_FLOODPLAINS_ETC',							'REQUIREMENTSET_TEST_ANY'),
('REQSET_GABE_PLOT_IS_ADJACENT_NATURAL_WONDER',							'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_CITY_HAS_BUILDING_GA_FOREST_RESERVE',						'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_CITY_HAS_BUILDING_GA_FLOODPLAINS_RESERVE',				'REQUIREMENTSET_TEST_ALL'),
('REQSET_GABE_CITY_HAS_BUILDING_GA_WONDER_RESERVE_AND_NATIONAL_PARK',	'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
(RequirementSetId,														RequirementId)
VALUES
('REQSET_GABE_PLOT_IS_FEATURE_FOREST_OR_JUNGLE',						'GOLDEN_REQUIRES_PLOT_HAS_FOREST'),
('REQSET_GABE_PLOT_IS_FEATURE_FOREST_OR_JUNGLE',						'GOLDEN_REQUIRES_PLOT_HAS_JUNGLE'),
('REQSET_GABE_PLOT_IS_FEATURE_FLOODPLAINS_ETC',							'REQ_GABE_PLOT_IS_FEATURE_OASIS'),
('REQSET_GABE_PLOT_IS_FEATURE_FLOODPLAINS_ETC',							'REQ_GABE_PLOT_IS_FEATURE_MARSH'),
('REQSET_GABE_PLOT_IS_FEATURE_FLOODPLAINS_ETC',							'REQ_GABE_PLOT_IS_FEATURE_FLOODPLAINS'),
('REQSET_GABE_PLOT_IS_FEATURE_FLOODPLAINS_ETC',							'REQ_GABE_PLOT_IS_FEATURE_FLOODPLAINS_GRASSLAND'),
('REQSET_GABE_PLOT_IS_FEATURE_FLOODPLAINS_ETC',							'REQ_GABE_PLOT_IS_FEATURE_FLOODPLAINS_PLAINS'),
('REQSET_GABE_PLOT_IS_FEATURE_FLOODPLAINS_ETC',							'REQ_GABE_PLOT_IS_FEATURE_FLOODPLAINS_TUNDRA'),
('REQSET_GABE_PLOT_IS_ADJACENT_NATURAL_WONDER',							'REQUIRES_PLOT_ADJACENT_TO_NATURAL_WONDER'),
('REQSET_GABE_CITY_HAS_BUILDING_GA_FOREST_RESERVE',						'REQ_GABE_CITY_HAS_BUILDING_GA_FOREST_RESERVE'),
('REQSET_GABE_CITY_HAS_BUILDING_GA_FLOODPLAINS_RESERVE',				'REQ_GABE_CITY_HAS_BUILDING_GA_FLOODPLAINS_RESERVE'),
('REQSET_GABE_CITY_HAS_BUILDING_GA_WONDER_RESERVE_AND_NATIONAL_PARK',	'REQ_GABE_CITY_HAS_BUILDING_GA_WONDER_RESERVE'),
('REQSET_GABE_CITY_HAS_BUILDING_GA_WONDER_RESERVE_AND_NATIONAL_PARK',	'REQUIRES_CITY_HAS_NATIONAL_PARK');

INSERT OR IGNORE INTO Requirements
(RequirementId,											RequirementType)
VALUES
('REQ_GABE_PLOT_IS_FEATURE_OASIS',						'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES'),
('REQ_GABE_PLOT_IS_FEATURE_MARSH',						'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES'),
('REQ_GABE_PLOT_IS_FEATURE_FLOODPLAINS',				'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES'),
('REQ_GABE_PLOT_IS_FEATURE_FLOODPLAINS_GRASSLAND',		'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES'),
('REQ_GABE_PLOT_IS_FEATURE_FLOODPLAINS_PLAINS',			'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES'),
('REQ_GABE_PLOT_IS_FEATURE_FLOODPLAINS_TUNDRA',			'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES'),
('REQ_GABE_CITY_HAS_BUILDING_GA_FOREST_RESERVE',		'REQUIREMENT_CITY_HAS_BUILDING'),
('REQ_GABE_CITY_HAS_BUILDING_GA_FLOODPLAINS_RESERVE',	'REQUIREMENT_CITY_HAS_BUILDING'),
('REQ_GABE_CITY_HAS_BUILDING_GA_WONDER_RESERVE',		'REQUIREMENT_CITY_HAS_BUILDING');

INSERT OR REPLACE INTO RequirementArguments
(RequirementId,											Name,				Value)
VALUES
('REQ_GABE_PLOT_IS_FEATURE_OASIS',						'FeatureType',		'FEATURE_OASIS'),
('REQ_GABE_PLOT_IS_FEATURE_MARSH',						'FeatureType',		'FEATURE_MARSH'),
('REQ_GABE_PLOT_IS_FEATURE_FLOODPLAINS',				'FeatureType',		'FEATURE_FLOODPLAINS'),
('REQ_GABE_PLOT_IS_FEATURE_FLOODPLAINS_GRASSLAND',		'FeatureType',		'FEATURE_FLOODPLAINS_GRASSLAND'),
('REQ_GABE_PLOT_IS_FEATURE_FLOODPLAINS_PLAINS',			'FeatureType',		'FEATURE_FLOODPLAINS_PLAINS'),
('REQ_GABE_PLOT_IS_FEATURE_FLOODPLAINS_TUNDRA',			'FeatureType',		'FEATURE_FLOODPLAINS_TUNDRA'),
('REQ_GABE_CITY_HAS_BUILDING_GA_FOREST_RESERVE',		'BuildingType',		'BUILDING_GA_FOREST_RESERVE'),
('REQ_GABE_CITY_HAS_BUILDING_GA_FLOODPLAINS_RESERVE',	'BuildingType',		'BUILDING_GA_FLOODPLAINS_RESERVE'),
('REQ_GABE_CITY_HAS_BUILDING_GA_WONDER_RESERVE',		'BuildingType',		'BUILDING_GA_WONDER_RESERVE');