INSERT OR REPLACE INTO Types 
(Type,	Kind) VALUES	
('BUILDING_NATIONAL_LIBRARY', 'KIND_BUILDING'),
('BUILDING_NATIONAL_UNIVERSITY', 'KIND_BUILDING'),
('BUILDING_NATIONAL_RESEARCH_LAB', 'KIND_BUILDING'),
	
('BUILDING_NATIONAL_MARKET', 'KIND_BUILDING'),
('BUILDING_NATIONAL_BANK', 'KIND_BUILDING'),
('BUILDING_NATIONAL_STOCK_EXCHANGE', 'KIND_BUILDING'),
	
('BUILDING_NATIONAL_WORKSHOP', 'KIND_BUILDING'),
('BUILDING_NATIONAL_FACTORY', 'KIND_BUILDING'),
('BUILDING_NATIONAL_POWER_STATION', 'KIND_BUILDING'),
	
('BUILDING_NATIONAL_SHRINE', 'KIND_BUILDING'),
('BUILDING_NATIONAL_TEMPLE', 'KIND_BUILDING'),
('BUILDING_NATIONAL_CATHEDRAL', 'KIND_BUILDING'),
		
('BUILDING_NATIONAL_AMPHITHEATER', 'KIND_BUILDING'),
('BUILDING_NATIONAL_MUSEUM', 'KIND_BUILDING'),
('BUILDING_NATIONAL_BROADCAST_CENTER', 'KIND_BUILDING'),

('BUILDING_NATIONAL_ARENA', 'KIND_BUILDING'),
('BUILDING_NATIONAL_ZOO', 'KIND_BUILDING'),
('BUILDING_NATIONAL_STADIUM', 'KIND_BUILDING'),

('BUILDING_NATIONAL_LIGHTHOUSE', 'KIND_BUILDING'),
('BUILDING_NATIONAL_SHIPYARD', 'KIND_BUILDING'),
('BUILDING_NATIONAL_SEAPORT', 'KIND_BUILDING'),
	
('BUILDING_NATIONAL_BARRACKS', 'KIND_BUILDING'),
('BUILDING_NATIONAL_ARMORY', 'KIND_BUILDING'),
('BUILDING_NATIONAL_MILITARY_ACADEMY', 'KIND_BUILDING');
	
INSERT OR REPLACE INTO Buildings 
(BuildingType, Name, Description, PrereqTech, PrereqCivic, PrereqDistrict, Cost, AdvisorType, Maintenance, CitizenSlots, MaxPlayerInstances, RegionalRange, Entertainment, Housing) VALUES	
('BUILDING_NATIONAL_LIBRARY', 'LOC_BUILDING_NATIONAL_LIBRARY_NAME', 'LOC_BUILDING_NATIONAL_LIBRARY_DESCRIPTION', 'TECH_WRITING', null, 'DISTRICT_NATIONAL_CAMPUS', 200, 'ADVISOR_TECHNOLOGY', 4, 2, 1, 0, 0, 0),	
('BUILDING_NATIONAL_UNIVERSITY', 'LOC_BUILDING_NATIONAL_UNIVERSITY_NAME', 'LOC_BUILDING_NATIONAL_UNIVERSITY_DESCRIPTION', 'TECH_EDUCATION', null, 'DISTRICT_NATIONAL_CAMPUS', 800, 'ADVISOR_TECHNOLOGY', 6, 2, 1, 0, 0, 0),	
('BUILDING_NATIONAL_RESEARCH_LAB', 'LOC_BUILDING_NATIONAL_RESEARCH_LAB_NAME', 'LOC_BUILDING_NATIONAL_RESEARCH_LAB_DESCRIPTION', 'TECH_SANITATION', null, 'DISTRICT_NATIONAL_CAMPUS', 1300, 'ADVISOR_TECHNOLOGY', 8, 2, 1, 0, 0, 0),	
	
('BUILDING_NATIONAL_MARKET', 'LOC_BUILDING_NATIONAL_MARKET_NAME', 'LOC_BUILDING_NATIONAL_MARKET_DESCRIPTION', 'TECH_CURRENCY', null, 'DISTRICT_NATIONAL_COMMERCIAL_HUB', 400, 'ADVISOR_GENERIC', 0, 2, 1, 0, 0, 0),	
('BUILDING_NATIONAL_BANK', 'LOC_BUILDING_NATIONAL_BANK_NAME', 'LOC_BUILDING_NATIONAL_BANK_DESCRIPTION', 'TECH_BANKING', null, 'DISTRICT_NATIONAL_COMMERCIAL_HUB', 1000, 'ADVISOR_GENERIC', 0, 2, 1, 0, 0, 0),	
('BUILDING_NATIONAL_STOCK_EXCHANGE', 'LOC_BUILDING_NATIONAL_STOCK_EXCHANGE_NAME', 'LOC_BUILDING_NATIONAL_STOCK_EXCHANGE_DESCRIPTION', 'TECH_ECONOMICS', null, 'DISTRICT_NATIONAL_COMMERCIAL_HUB', 1300, 'ADVISOR_GENERIC', 0, 2, 1, 0, 0, 0),	
	
('BUILDING_NATIONAL_WORKSHOP', 'LOC_BUILDING_NATIONAL_WORKSHOP_NAME', 'LOC_BUILDING_NATIONAL_WORKSHOP_DESCRIPTION', 'TECH_APPRENTICESHIP', null, 'DISTRICT_NATIONAL_INDUSTRIAL_ZONE', 800, 'ADVISOR_GENERIC', 4, 2, 1, 0, 0, 0),	
('BUILDING_NATIONAL_FACTORY', 'LOC_BUILDING_NATIONAL_FACTORY_NAME', 'LOC_BUILDING_NATIONAL_FACTORY_DESCRIPTION', 'TECH_INDUSTRIALIZATION', null, 'DISTRICT_NATIONAL_INDUSTRIAL_ZONE', 1300, 'ADVISOR_GENERIC', 6, 2, 1, 0, 0, 0),	
('BUILDING_NATIONAL_POWER_STATION', 'LOC_BUILDING_NATIONAL_POWER_STATION_NAME', 'LOC_BUILDING_NATIONAL_POWER_STATION_DESCRIPTION', 'TECH_NUCLEAR_FISSION', null, 'DISTRICT_NATIONAL_INDUSTRIAL_ZONE', 2000, 'ADVISOR_GENERIC', 8, 2, 1, 0, 0, 0),	
	
('BUILDING_NATIONAL_SHRINE', 'LOC_BUILDING_NATIONAL_SHRINE_NAME', 'LOC_BUILDING_NATIONAL_SHRINE_DESCRIPTION', 'TECH_ASTROLOGY', null, 'DISTRICT_NATIONAL_HOLY_SITE', 200, 'ADVISOR_RELIGIOUS', 4, 2, 1, 0, 0, 0),	
('BUILDING_NATIONAL_TEMPLE', 'LOC_BUILDING_NATIONAL_TEMPLE_NAME', 'LOC_BUILDING_NATIONAL_TEMPLE_DESCRIPTION', null, 'CIVIC_THEOLOGY', 'DISTRICT_NATIONAL_HOLY_SITE', 400, 'ADVISOR_RELIGIOUS', 6, 2, 1, 0, 0, 0),	
('BUILDING_NATIONAL_CATHEDRAL', 'LOC_BUILDING_NATIONAL_CATHEDRAL_NAME', 'LOC_BUILDING_NATIONAL_CATHEDRAL_DESCRIPTION', null, 'CIVIC_REFORMED_CHURCH', 'DISTRICT_NATIONAL_HOLY_SITE', 1000, 'ADVISOR_RELIGIOUS', 8, 2, 1, 0, 0, 0),
	
('BUILDING_NATIONAL_AMPHITHEATER', 'LOC_BUILDING_NATIONAL_AMPHITHEATER_NAME', 'LOC_BUILDING_NATIONAL_AMPHITHEATER_DESCRIPTION', null, 'CIVIC_DRAMA_POETRY', 'DISTRICT_NATIONAL_THEATER', 400, 'ADVISOR_CULTURE', 4, 2, 1, 0, 0, 0),	
('BUILDING_NATIONAL_MUSEUM', 'LOC_BUILDING_NATIONAL_MUSEUM_NAME', 'LOC_BUILDING_NATIONAL_MUSEUM_DESCRIPTION', null, 'CIVIC_HUMANISM', 'DISTRICT_NATIONAL_THEATER', 1000, 'ADVISOR_CULTURE', 6, 2, 1, 0, 0, 0),	
('BUILDING_NATIONAL_BROADCAST_CENTER', 'LOC_BUILDING_NATIONAL_BROADCAST_CENTER_NAME', 'LOC_BUILDING_NATIONAL_BROADCAST_CENTER_DESCRIPTION', 'TECH_RADIO', null, 'DISTRICT_NATIONAL_THEATER', 1600, 'ADVISOR_CULTURE', 8, 2, 1, 0, 0, 0),	

('BUILDING_NATIONAL_LIGHTHOUSE', 'LOC_BUILDING_NATIONAL_LIGHTHOUSE_NAME', 'LOC_BUILDING_NATIONAL_LIGHTHOUSE_DESCRIPTION', 'TECH_CELESTIAL_NAVIGATION', null, 'DISTRICT_NATIONAL_HARBOR', 400, 'ADVISOR_GENERIC', 4, 2, 1, 0, 0, 0),	
('BUILDING_NATIONAL_SHIPYARD', 'LOC_BUILDING_NATIONAL_SHIPYARD_NAME', 'LOC_BUILDING_NATIONAL_SHIPYARD_DESCRIPTION', 'TECH_MASS_PRODUCTION', null, 'DISTRICT_NATIONAL_HARBOR', 1000, 'ADVISOR_GENERIC', 6, 2, 1, 0, 0, 0),	
('BUILDING_NATIONAL_SEAPORT', 'LOC_BUILDING_NATIONAL_SEAPORT_NAME', 'LOC_BUILDING_NATIONAL_SEAPORT_DESCRIPTION', 'TECH_ELECTRICITY', null, 'DISTRICT_NATIONAL_HARBOR', 1600, 'ADVISOR_GENERIC', 8, 2, 1, 0, 0, 0),	

('BUILDING_NATIONAL_ARENA', 'LOC_BUILDING_NATIONAL_ARENA_NAME', 'LOC_BUILDING_NATIONAL_ARENA_DESCRIPTION', null, 'CIVIC_GAMES_RECREATION', 'DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX', 400, 'ADVISOR_GENERIC', 4, 2, 1, 0, 1, 0),	
('BUILDING_NATIONAL_ZOO', 'LOC_BUILDING_NATIONAL_ZOO_NAME', 'LOC_BUILDING_NATIONAL_ZOO_DESCRIPTION', null, 'CIVIC_NATURAL_HISTORY', 'DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX', 1300, 'ADVISOR_GENERIC', 6, 2, 1, 0, 2, 0),	
('BUILDING_NATIONAL_STADIUM', 'LOC_BUILDING_NATIONAL_STADIUM_NAME', 'LOC_BUILDING_NATIONAL_STADIUM_DESCRIPTION', null, 'CIVIC_PROFESSIONAL_SPORTS', 'DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX', 2000, 'ADVISOR_GENERIC', 8, 2, 1, 0, 3, 0),	
	
('BUILDING_NATIONAL_BARRACKS', 'LOC_BUILDING_NATIONAL_BARRACKS_NAME', 'LOC_BUILDING_NATIONAL_BARRACKS_DESCRIPTION', 'TECH_BRONZE_WORKING', null, 'DISTRICT_NATIONAL_ENCAMPMENT', 200, 'ADVISOR_CONQUEST', 4, 2, 1, 0, 0, 2),	
('BUILDING_NATIONAL_ARMORY', 'LOC_BUILDING_NATIONAL_ARMORY_NAME', 'LOC_BUILDING_NATIONAL_ARMORY_DESCRIPTION', 'TECH_MILITARY_ENGINEERING', null, 'DISTRICT_NATIONAL_ENCAMPMENT', 800, 'ADVISOR_CONQUEST', 6, 2, 1, 0, 0, 3),	
('BUILDING_NATIONAL_MILITARY_ACADEMY', 'LOC_BUILDING_NATIONAL_MILITARY_ACADEMY_NAME', 'LOC_BUILDING_NATIONAL_MILITARY_ACADEMY_DESCRIPTION', 'TECH_MILITARY_SCIENCE', null, 'DISTRICT_NATIONAL_ENCAMPMENT', 1300, 'ADVISOR_CONQUEST', 8, 2, 1, 0, 0, 4);


INSERT OR REPLACE INTO BuildingPrereqs 
(Building, PrereqBuilding) VALUES
('BUILDING_NATIONAL_UNIVERSITY', 'BUILDING_NATIONAL_LIBRARY'),
('BUILDING_NATIONAL_RESEARCH_LAB', 'BUILDING_NATIONAL_UNIVERSITY'),

('BUILDING_NATIONAL_BANK', 'BUILDING_NATIONAL_MARKET'),
('BUILDING_NATIONAL_STOCK_EXCHANGE', 'BUILDING_NATIONAL_BANK'),

('BUILDING_NATIONAL_FACTORY', 'BUILDING_NATIONAL_WORKSHOP'),
('BUILDING_NATIONAL_POWER_STATION', 'BUILDING_NATIONAL_FACTORY'),

('BUILDING_NATIONAL_TEMPLE', 'BUILDING_NATIONAL_SHRINE'),
('BUILDING_NATIONAL_CATHEDRAL', 'BUILDING_NATIONAL_TEMPLE'),

('BUILDING_NATIONAL_MUSEUM', 'BUILDING_NATIONAL_AMPHITHEATER'),
('BUILDING_NATIONAL_BROADCAST_CENTER', 'BUILDING_NATIONAL_MUSEUM'),

('BUILDING_NATIONAL_SHIPYARD', 'BUILDING_NATIONAL_LIGHTHOUSE'),
('BUILDING_NATIONAL_SEAPORT', 'BUILDING_NATIONAL_SHIPYARD'),

('BUILDING_NATIONAL_ZOO', 'BUILDING_NATIONAL_ARENA'),
('BUILDING_NATIONAL_STADIUM', 'BUILDING_NATIONAL_ZOO'),

('BUILDING_NATIONAL_ARMORY', 'BUILDING_NATIONAL_BARRACKS'),
('BUILDING_NATIONAL_MILITARY_ACADEMY', 'BUILDING_NATIONAL_ARMORY');	
	
	
INSERT OR REPLACE INTO Building_YieldChanges 
(BuildingType, YieldType, YieldChange) VALUES	
('BUILDING_NATIONAL_LIBRARY', 'YIELD_SCIENCE', 2),
('BUILDING_NATIONAL_UNIVERSITY', 'YIELD_SCIENCE', 4),
('BUILDING_NATIONAL_RESEARCH_LAB', 'YIELD_SCIENCE', 6),
		
('BUILDING_NATIONAL_MARKET', 'YIELD_GOLD', 2),
('BUILDING_NATIONAL_BANK', 'YIELD_GOLD', 4),
('BUILDING_NATIONAL_STOCK_EXCHANGE', 'YIELD_GOLD', 6),
		
('BUILDING_NATIONAL_WORKSHOP', 'YIELD_PRODUCTION', 2),
('BUILDING_NATIONAL_FACTORY', 'YIELD_PRODUCTION', 4),
('BUILDING_NATIONAL_POWER_STATION', 'YIELD_PRODUCTION', 6),
	
('BUILDING_NATIONAL_SHRINE', 'YIELD_FAITH', 2),
('BUILDING_NATIONAL_TEMPLE', 'YIELD_FAITH', 4),
('BUILDING_NATIONAL_CATHEDRAL', 'YIELD_FAITH', 6),

('BUILDING_NATIONAL_AMPHITHEATER', 'YIELD_CULTURE', 2),
('BUILDING_NATIONAL_MUSEUM', 'YIELD_CULTURE', 4),
('BUILDING_NATIONAL_BROADCAST_CENTER', 'YIELD_CULTURE', 6);	
	
	
INSERT OR REPLACE INTO Building_GreatPersonPoints 
(BuildingType, GreatPersonClassType, PointsPerTurn) VALUES	
('BUILDING_NATIONAL_LIBRARY', 'GREAT_PERSON_CLASS_SCIENTIST', 2),
('BUILDING_NATIONAL_UNIVERSITY', 'GREAT_PERSON_CLASS_SCIENTIST', 2),
('BUILDING_NATIONAL_RESEARCH_LAB', 'GREAT_PERSON_CLASS_SCIENTIST', 2),
	
('BUILDING_NATIONAL_MARKET', 'GREAT_PERSON_CLASS_MERCHANT', 2),
('BUILDING_NATIONAL_BANK', 'GREAT_PERSON_CLASS_MERCHANT', 2),
('BUILDING_NATIONAL_STOCK_EXCHANGE', 'GREAT_PERSON_CLASS_MERCHANT', 2),
	
('BUILDING_NATIONAL_WORKSHOP', 'GREAT_PERSON_CLASS_ENGINEER', 2),
('BUILDING_NATIONAL_FACTORY', 'GREAT_PERSON_CLASS_ENGINEER', 2),
('BUILDING_NATIONAL_POWER_STATION', 'GREAT_PERSON_CLASS_ENGINEER', 2),
	
('BUILDING_NATIONAL_SHRINE', 'GREAT_PERSON_CLASS_PROPHET', 2),
('BUILDING_NATIONAL_TEMPLE', 'GREAT_PERSON_CLASS_PROPHET', 2),
('BUILDING_NATIONAL_CATHEDRAL', 'GREAT_PERSON_CLASS_PROPHET', 2),
	
('BUILDING_NATIONAL_AMPHITHEATER', 'GREAT_PERSON_CLASS_WRITER', 2),
('BUILDING_NATIONAL_MUSEUM', 'GREAT_PERSON_CLASS_WRITER', 2),
('BUILDING_NATIONAL_MUSEUM', 'GREAT_PERSON_CLASS_ARTIST', 2),
('BUILDING_NATIONAL_BROADCAST_CENTER', 'GREAT_PERSON_CLASS_ARTIST', 2),
('BUILDING_NATIONAL_BROADCAST_CENTER', 'GREAT_PERSON_CLASS_MUSICIAN', 2),
	
('BUILDING_NATIONAL_BARRACKS', 'GREAT_PERSON_CLASS_GENERAL', 2),
('BUILDING_NATIONAL_ARMORY', 'GREAT_PERSON_CLASS_GENERAL', 2),		
('BUILDING_NATIONAL_MILITARY_ACADEMY', 'GREAT_PERSON_CLASS_GENERAL', 2),

('BUILDING_NATIONAL_LIGHTHOUSE', 'GREAT_PERSON_CLASS_ADMIRAL', 2),
('BUILDING_NATIONAL_SHIPYARD', 'GREAT_PERSON_CLASS_ADMIRAL', 2),		
('BUILDING_NATIONAL_SEAPORT', 'GREAT_PERSON_CLASS_ADMIRAL', 2);
	
	
INSERT OR REPLACE INTO Building_GreatWorks 
(BuildingType, GreatWorkSlotType, NumSlots) VALUES	
('BUILDING_NATIONAL_AMPHITHEATER','GREATWORKSLOT_WRITING', 4),
('BUILDING_NATIONAL_MUSEUM','GREATWORKSLOT_ART', 6),
('BUILDING_NATIONAL_BROADCAST_CENTER','GREATWORKSLOT_MUSIC', 2),
('BUILDING_NATIONAL_SHRINE','GREATWORKSLOT_RELIC', 2),
('BUILDING_NATIONAL_TEMPLE','GREATWORKSLOT_RELIC', 2),
('BUILDING_NATIONAL_CATHEDRAL','GREATWORKSLOT_RELIC', 2);	


INSERT OR REPLACE INTO Buildings_XP2 
(BuildingType, RequiredPower) VALUES	
('BUILDING_NATIONAL_LIBRARY',1),
('BUILDING_NATIONAL_UNIVERSITY',2),
('BUILDING_NATIONAL_RESEARCH_LAB',3),
('BUILDING_NATIONAL_MARKET',1),
('BUILDING_NATIONAL_BANK',2),
('BUILDING_NATIONAL_STOCK_EXCHANGE',3),
('BUILDING_NATIONAL_WORKSHOP',1),
('BUILDING_NATIONAL_FACTORY',2),
('BUILDING_NATIONAL_POWER_STATION',3),
('BUILDING_NATIONAL_SHRINE',1),
('BUILDING_NATIONAL_TEMPLE',2),
('BUILDING_NATIONAL_CATHEDRAL',3),
('BUILDING_NATIONAL_AMPHITHEATER',1),
('BUILDING_NATIONAL_MUSEUM',2),
('BUILDING_NATIONAL_BROADCAST_CENTER',3);

INSERT OR REPLACE INTO Buildings_XP2 
(BuildingType, RequiredPower, EntertainmentBonusWithPower) VALUES		
('BUILDING_NATIONAL_ARENA',1,1),
('BUILDING_NATIONAL_ZOO',2,2),
('BUILDING_NATIONAL_STADIUM',3,3);


INSERT OR REPLACE INTO Building_YieldChangesBonusWithPower 
(BuildingType, YieldType, YieldChange) VALUES	
('BUILDING_NATIONAL_LIBRARY', 'YIELD_SCIENCE', 2),
('BUILDING_NATIONAL_UNIVERSITY', 'YIELD_SCIENCE', 4),	
('BUILDING_NATIONAL_RESEARCH_LAB', 'YIELD_SCIENCE', 6),	
('BUILDING_NATIONAL_MARKET', 'YIELD_GOLD', 2),
('BUILDING_NATIONAL_BANK', 'YIELD_GOLD', 4),	
('BUILDING_NATIONAL_STOCK_EXCHANGE', 'YIELD_GOLD', 6),
('BUILDING_NATIONAL_WORKSHOP', 'YIELD_PRODUCTION', 2),
('BUILDING_NATIONAL_FACTORY', 'YIELD_PRODUCTION', 4),	
('BUILDING_NATIONAL_POWER_STATION', 'YIELD_PRODUCTION', 6),	
('BUILDING_NATIONAL_SHRINE', 'YIELD_FAITH', 2),
('BUILDING_NATIONAL_TEMPLE', 'YIELD_FAITH', 4),	
('BUILDING_NATIONAL_CATHEDRAL', 'YIELD_FAITH', 6),
('BUILDING_NATIONAL_AMPHITHEATER', 'YIELD_CULTURE', 2),
('BUILDING_NATIONAL_MUSEUM', 'YIELD_CULTURE', 4),	
('BUILDING_NATIONAL_BROADCAST_CENTER', 'YIELD_CULTURE', 6);	

INSERT OR REPLACE INTO Building_CitizenYieldChanges 
(BuildingType, YieldType, YieldChange) VALUES	
('BUILDING_NATIONAL_LIBRARY',          'YIELD_SCIENCE', 1),
('BUILDING_NATIONAL_UNIVERSITY',       'YIELD_SCIENCE', 1),	
('BUILDING_NATIONAL_RESEARCH_LAB',     'YIELD_SCIENCE', 1),	
('BUILDING_NATIONAL_MARKET',           'YIELD_GOLD', 1),
('BUILDING_NATIONAL_BANK',             'YIELD_GOLD', 1),	
('BUILDING_NATIONAL_STOCK_EXCHANGE',   'YIELD_GOLD', 1),
('BUILDING_NATIONAL_WORKSHOP',         'YIELD_PRODUCTION', 1),
('BUILDING_NATIONAL_FACTORY',          'YIELD_PRODUCTION', 1),	
('BUILDING_NATIONAL_POWER_STATION',    'YIELD_PRODUCTION', 1),	
('BUILDING_NATIONAL_SHRINE',           'YIELD_FAITH', 1),
('BUILDING_NATIONAL_TEMPLE',           'YIELD_FAITH', 1),	
('BUILDING_NATIONAL_CATHEDRAL',        'YIELD_FAITH', 1),
('BUILDING_NATIONAL_AMPHITHEATER',     'YIELD_CULTURE', 1),
('BUILDING_NATIONAL_MUSEUM',           'YIELD_CULTURE', 1),	
('BUILDING_NATIONAL_BROADCAST_CENTER', 'YIELD_CULTURE', 1),
('BUILDING_NATIONAL_LIGHTHOUSE',       'YIELD_GOLD', 1),
('BUILDING_NATIONAL_SHIPYARD',         'YIELD_GOLD', 1),	
-- ('BUILDING_NATIONAL_SEAPORT',          'YIELD_GOLD', 1),
-- ('BUILDING_NATIONAL_LIGHTHOUSE',       'YIELD_CULTURE', 1),
-- ('BUILDING_NATIONAL_SHIPYARD',         'YIELD_CULTURE', 1),	
('BUILDING_NATIONAL_SEAPORT',          'YIELD_CULTURE', 1),
-- ('BUILDING_NATIONAL_BARRACKS',         'YIELD_SCIENCE', 1),
('BUILDING_NATIONAL_BARRACKS',         'YIELD_PRODUCTION', 1),
-- ('BUILDING_NATIONAL_ARMORY',           'YIELD_SCIENCE', 1),
('BUILDING_NATIONAL_ARMORY',           'YIELD_PRODUCTION', 1),
('BUILDING_NATIONAL_MILITARY_ACADEMY', 'YIELD_SCIENCE', 1),
-- ('BUILDING_NATIONAL_MILITARY_ACADEMY', 'YIELD_PRODUCTION', 1),
('BUILDING_NATIONAL_ARENA',            'YIELD_CULTURE', 1),
('BUILDING_NATIONAL_ARENA',            'YIELD_GOLD', 1),
-- ('BUILDING_NATIONAL_ARENA',            'YIELD_FAITH', 1),
-- ('BUILDING_NATIONAL_ARENA',            'YIELD_SCIENCE', 1),
-- ('BUILDING_NATIONAL_ZOO',              'YIELD_CULTURE', 1),
('BUILDING_NATIONAL_ZOO',              'YIELD_GOLD', 1),
-- ('BUILDING_NATIONAL_ZOO',              'YIELD_FAITH', 1),
('BUILDING_NATIONAL_ZOO',              'YIELD_SCIENCE', 1),
('BUILDING_NATIONAL_STADIUM',          'YIELD_CULTURE', 1),
('BUILDING_NATIONAL_STADIUM',          'YIELD_GOLD', 1);
-- ('BUILDING_NATIONAL_STADIUM',          'YIELD_FAITH', 1),
-- ('BUILDING_NATIONAL_STADIUM',          'YIELD_SCIENCE', 1);
	
INSERT OR REPLACE INTO BuildingModifiers 
(BuildingType, ModifierId) VALUES	
('BUILDING_NATIONAL_BARRACKS', 'BARRACKS_ADJUST_RESOURCE_STOCKPILE_CAP'),
('BUILDING_NATIONAL_ARMORY', 'ARMORY_ADJUST_RESOURCE_STOCKPILE_CAP'),		
('BUILDING_NATIONAL_MILITARY_ACADEMY', 'MILITARY_ACADEMY_ADJUST_RESOURCE_STOCKPILE_CAP'),
	
('BUILDING_NATIONAL_BARRACKS', 'GOLDEN_NATIONAL_FREE_HORSES'),
('BUILDING_NATIONAL_BARRACKS', 'GOLDEN_NATIONAL_FREE_IRON'),
('BUILDING_NATIONAL_ARMORY', 'GOLDEN_NATIONAL_FREE_NITER'),		
('BUILDING_NATIONAL_ARMORY', 'GOLDEN_NATIONAL_FREE_COAL'),	
('BUILDING_NATIONAL_MILITARY_ACADEMY', 'GOLDEN_NATIONAL_FREE_OIL'),	
('BUILDING_NATIONAL_MILITARY_ACADEMY', 'GOLDEN_NATIONAL_FREE_ALUMINUM'),	
('BUILDING_NATIONAL_MILITARY_ACADEMY', 'GOLDEN_NATIONAL_FREE_URANIUM'),	

('BUILDING_NATIONAL_LIGHTHOUSE', 'GOLDEN_TRADE_ROUNTES_DOMESTIC_1'),
('BUILDING_NATIONAL_LIGHTHOUSE', 'GOLDEN_TRADE_ROUNTES_INTERNATIONAL_1'),
('BUILDING_NATIONAL_SHIPYARD', 'GOLDEN_TRADE_ROUNTES_DOMESTIC_2'),	
('BUILDING_NATIONAL_SHIPYARD', 'GOLDEN_TRADE_ROUNTES_INTERNATIONAL_2'),		
('BUILDING_NATIONAL_SEAPORT', 'GOLDEN_TRADE_ROUNTES_DOMESTIC_3'),
('BUILDING_NATIONAL_SEAPORT', 'GOLDEN_TRADE_ROUNTES_INTERNATIONAL_3'),

('BUILDING_NATIONAL_LIGHTHOUSE', 'LIGHTHOUSE_COAST_FOOD'),
('BUILDING_NATIONAL_LIGHTHOUSE', 'GOLDEN_LIGHTHOUSE_OCEAN_FOOD'),
('BUILDING_NATIONAL_SHIPYARD', 'GOLDEN_SHIPYARD_COAST_PRODUCTION'),	
('BUILDING_NATIONAL_SHIPYARD', 'GOLDEN_SHIPYARD_OCEAN_PRODUCTION'),		
('BUILDING_NATIONAL_SEAPORT', 'SEAPORT_COAST_GOLD'),
('BUILDING_NATIONAL_SEAPORT', 'GOLDEN_SEAPORT_OCEAN_GOLD'),

('BUILDING_NATIONAL_LIGHTHOUSE', 'GOLDEN_NATIONAL_ADD_TRADE_ROUNTE'),
('BUILDING_NATIONAL_SHIPYARD', 'GOLDEN_NATIONAL_ADD_TRADE_ROUNTE'),
('BUILDING_NATIONAL_SEAPORT', 'GOLDEN_NATIONAL_ADD_TRADE_ROUNTE'),

('BUILDING_NATIONAL_ARENA', 'GOLDEN_NATIONAL_ARENA_GROWTH'),
('BUILDING_NATIONAL_ZOO', 'GOLDEN_NATIONAL_ZOO_GROWTH'),
('BUILDING_NATIONAL_STADIUM', 'GOLDEN_NATIONAL_STADIUM_GROWTH');
	
INSERT OR REPLACE INTO Modifiers 
(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
	('GOLDEN_NATIONAL_FREE_HORSES', 'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION', 'GOLDEN_PLAYER_HAS_TECH_ANIMAL_HUSBANDRY_REQUIREMENTS'),	
	('GOLDEN_NATIONAL_FREE_IRON', 'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION', 'GOLDEN_PLAYER_HAS_TECH_IRON_WORKING_REQUIREMENTS'),	
	('GOLDEN_NATIONAL_FREE_NITER', 'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION', 'GOLDEN_PLAYER_HAS_TECH_MILITARY_ENGINEERING_REQUIREMENTS'),	
	('GOLDEN_NATIONAL_FREE_COAL', 'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION', 'GOLDEN_PLAYER_HAS_TECH_INDUSTRIALIZATION_REQUIREMENTS'),	
	('GOLDEN_NATIONAL_FREE_OIL', 'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION', 'GOLDEN_PLAYER_HAS_TECH_REFINING_REQUIREMENTS'),	
	('GOLDEN_NATIONAL_FREE_ALUMINUM', 'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION', 'GOLDEN_PLAYER_HAS_TECH_CHEMISTRY_REQUIREMENTS'),	
	('GOLDEN_NATIONAL_FREE_URANIUM', 'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION', 'GOLDEN_PLAYER_HAS_TECH_COMBINED_ARMS_REQUIREMENTS'),	
	
	('GOLDEN_TRADE_ROUNTES_DOMESTIC_1', 'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC', NULL),	
	('GOLDEN_TRADE_ROUNTES_INTERNATIONAL_1', 'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL', NULL),	
	('GOLDEN_TRADE_ROUNTES_DOMESTIC_2', 'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC', NULL),	
	('GOLDEN_TRADE_ROUNTES_INTERNATIONAL_2', 'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL', NULL),	
	('GOLDEN_TRADE_ROUNTES_DOMESTIC_3', 'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC', NULL),	
	('GOLDEN_TRADE_ROUNTES_INTERNATIONAL_3', 'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL', NULL),	
	
	('GOLDEN_NATIONAL_ADD_TRADE_ROUNTE', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', NULL),	
	
	('GOLDEN_NATIONAL_ARENA_GROWTH', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_GROWTH', NULL),	
	('GOLDEN_NATIONAL_ZOO_GROWTH', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_GROWTH', NULL),	
	('GOLDEN_NATIONAL_STADIUM_GROWTH', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_GROWTH', NULL);
	
	
INSERT OR REPLACE INTO ModifierArguments 
(ModifierId, Name, Value) VALUES		
	('GOLDEN_NATIONAL_FREE_HORSES', 'ResourceType', 'RESOURCE_HORSES'),
	('GOLDEN_NATIONAL_FREE_HORSES', 'Amount', 5),
	('GOLDEN_NATIONAL_FREE_IRON', 'ResourceType', 'RESOURCE_IRON'),
	('GOLDEN_NATIONAL_FREE_IRON', 'Amount', 5),
	('GOLDEN_NATIONAL_FREE_NITER', 'ResourceType', 'RESOURCE_NITER'),
	('GOLDEN_NATIONAL_FREE_NITER', 'Amount', 5),
	('GOLDEN_NATIONAL_FREE_COAL', 'ResourceType', 'RESOURCE_COAL'),
	('GOLDEN_NATIONAL_FREE_COAL', 'Amount', 5),
	('GOLDEN_NATIONAL_FREE_OIL', 'ResourceType', 'RESOURCE_OIL'),
	('GOLDEN_NATIONAL_FREE_OIL', 'Amount', 5),
	('GOLDEN_NATIONAL_FREE_ALUMINUM', 'ResourceType', 'RESOURCE_ALUMINUM'),
	('GOLDEN_NATIONAL_FREE_ALUMINUM', 'Amount', 5),
	('GOLDEN_NATIONAL_FREE_URANIUM', 'ResourceType', 'RESOURCE_URANIUM'),
	('GOLDEN_NATIONAL_FREE_URANIUM', 'Amount', 5),
	
	('GOLDEN_TRADE_ROUNTES_DOMESTIC_1', 'YieldType', 'YIELD_GOLD'),
	('GOLDEN_TRADE_ROUNTES_DOMESTIC_1', 'Amount', 1),
	('GOLDEN_TRADE_ROUNTES_INTERNATIONAL_1', 'YieldType', 'YIELD_GOLD'),
	('GOLDEN_TRADE_ROUNTES_INTERNATIONAL_1', 'Amount', 1),
	('GOLDEN_TRADE_ROUNTES_DOMESTIC_2', 'YieldType', 'YIELD_GOLD'),
	('GOLDEN_TRADE_ROUNTES_DOMESTIC_2', 'Amount', 2),
	('GOLDEN_TRADE_ROUNTES_INTERNATIONAL_2', 'YieldType', 'YIELD_GOLD'),
	('GOLDEN_TRADE_ROUNTES_INTERNATIONAL_2', 'Amount', 2),
	('GOLDEN_TRADE_ROUNTES_DOMESTIC_3', 'YieldType', 'YIELD_GOLD'),
	('GOLDEN_TRADE_ROUNTES_DOMESTIC_3', 'Amount', 3),
	('GOLDEN_TRADE_ROUNTES_INTERNATIONAL_3', 'YieldType', 'YIELD_GOLD'),
	('GOLDEN_TRADE_ROUNTES_INTERNATIONAL_3', 'Amount', 3),
	
	('GOLDEN_NATIONAL_ADD_TRADE_ROUNTE', 'Amount', 1),
	
	('GOLDEN_NATIONAL_ARENA_GROWTH', 'Amount', 10),
	('GOLDEN_NATIONAL_ZOO_GROWTH', 'Amount', 20),
	('GOLDEN_NATIONAL_STADIUM_GROWTH', 'Amount', 30);
--BUFF	
INSERT OR REPLACE INTO BuildingModifiers 
(BuildingType, 							ModifierId)  VALUES	
('BUILDING_NATIONAL_LIBRARY', 			'GOLDEN_NATIONAL_SCIENCE_T1_BUFF'),	
('BUILDING_NATIONAL_SHRINE', 			'GOLDEN_NATIONAL_FAITH_T1_BUFF'),
('BUILDING_NATIONAL_MARKET', 			'GOLDEN_NATIONAL_GOLD_T1_BUFF'),
('BUILDING_NATIONAL_AMPHITHEATER', 		'GOLDEN_NATIONAL_CULTURE_T1_BUFF'),
('BUILDING_NATIONAL_WORKSHOP', 			'GOLDEN_NATIONAL_PRODUCTION_T1_BUFF'),
('BUILDING_NATIONAL_UNIVERSITY', 		'GOLDEN_NATIONAL_SCIENCE_T2_BUFF'),
('BUILDING_NATIONAL_TEMPLE', 			'GOLDEN_NATIONAL_FAITH_T2_BUFF'),	
('BUILDING_NATIONAL_BANK', 				'GOLDEN_NATIONAL_GOLD_T2_BUFF'),
('BUILDING_NATIONAL_MUSEUM', 			'GOLDEN_NATIONAL_CULTURE_T2_BUFF'),	
('BUILDING_NATIONAL_FACTORY', 			'GOLDEN_NATIONAL_PRODUCTION_T2_BUFF'),
('BUILDING_NATIONAL_RESEARCH_LAB', 		'GOLDEN_NATIONAL_SCIENCE_T3_BUFF'),
('BUILDING_NATIONAL_CATHEDRAL', 		'GOLDEN_NATIONAL_FAITH_T3_BUFF'),	
('BUILDING_NATIONAL_STOCK_EXCHANGE', 	'GOLDEN_NATIONAL_GOLD_T3_BUFF'),
('BUILDING_NATIONAL_BROADCAST_CENTER', 	'GOLDEN_NATIONAL_CULTURE_T3_BUFF'),	
('BUILDING_NATIONAL_POWER_STATION', 	'GOLDEN_NATIONAL_PRODUCTION_T3_BUFF');

INSERT OR REPLACE INTO Modifiers
(ModifierId,							ModifierType) VALUES
('GOLDEN_NATIONAL_SCIENCE_T1_BUFF',		'MODIFIER_BUILDING_YIELD_CHANGE'),
('GOLDEN_NATIONAL_FAITH_T1_BUFF',		'MODIFIER_BUILDING_YIELD_CHANGE'),
('GOLDEN_NATIONAL_GOLD_T1_BUFF',		'MODIFIER_BUILDING_YIELD_CHANGE'),
('GOLDEN_NATIONAL_CULTURE_T1_BUFF',		'MODIFIER_BUILDING_YIELD_CHANGE'),
('GOLDEN_NATIONAL_PRODUCTION_T1_BUFF',	'MODIFIER_BUILDING_YIELD_CHANGE'),
('GOLDEN_NATIONAL_SCIENCE_T2_BUFF',		'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_NATIONAL_FAITH_T2_BUFF',		'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_NATIONAL_GOLD_T2_BUFF',		'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_NATIONAL_CULTURE_T2_BUFF',		'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_NATIONAL_PRODUCTION_T2_BUFF',	'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION'),
('GOLDEN_NATIONAL_SCIENCE_T3_BUFF',		'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER'),
('GOLDEN_NATIONAL_FAITH_T3_BUFF',		'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER'),
('GOLDEN_NATIONAL_GOLD_T3_BUFF',		'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER'),
('GOLDEN_NATIONAL_CULTURE_T3_BUFF',		'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER'),
('GOLDEN_NATIONAL_PRODUCTION_T3_BUFF',	'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER');

INSERT OR REPLACE INTO ModifierArguments
(ModifierId,							Name,			Value) VALUES
('GOLDEN_NATIONAL_SCIENCE_T1_BUFF',		'Amount',		11),
('GOLDEN_NATIONAL_FAITH_T1_BUFF',		'Amount',		11),
('GOLDEN_NATIONAL_GOLD_T1_BUFF',		'Amount',		11),
('GOLDEN_NATIONAL_CULTURE_T1_BUFF',		'Amount',		11),
('GOLDEN_NATIONAL_PRODUCTION_T1_BUFF',	'Amount',		11),
('GOLDEN_NATIONAL_SCIENCE_T1_BUFF',		'YieldType',	'YIELD_SCIENCE'),
('GOLDEN_NATIONAL_FAITH_T1_BUFF',		'YieldType',	'YIELD_FAITH'),
('GOLDEN_NATIONAL_GOLD_T1_BUFF',		'YieldType',	'YIELD_GOLD'),
('GOLDEN_NATIONAL_CULTURE_T1_BUFF',		'YieldType',	'YIELD_CULTURE'),
('GOLDEN_NATIONAL_PRODUCTION_T1_BUFF',	'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_NATIONAL_SCIENCE_T1_BUFF',		'BuildingType',	'BUILDING_NATIONAL_LIBRARY'),
('GOLDEN_NATIONAL_FAITH_T1_BUFF',		'BuildingType',	'BUILDING_NATIONAL_SHRINE'),
('GOLDEN_NATIONAL_GOLD_T1_BUFF',		'BuildingType',	'BUILDING_NATIONAL_MARKET'),
('GOLDEN_NATIONAL_CULTURE_T1_BUFF',		'BuildingType',	'BUILDING_NATIONAL_AMPHITHEATER'),
('GOLDEN_NATIONAL_PRODUCTION_T1_BUFF',	'BuildingType',	'BUILDING_NATIONAL_WORKSHOP'),
('GOLDEN_NATIONAL_SCIENCE_T1_BUFF',		'CityStatesOnly',	0),
('GOLDEN_NATIONAL_FAITH_T1_BUFF',		'CityStatesOnly',	0),
('GOLDEN_NATIONAL_GOLD_T1_BUFF',		'CityStatesOnly',	0),
('GOLDEN_NATIONAL_CULTURE_T1_BUFF',		'CityStatesOnly',	0),
('GOLDEN_NATIONAL_PRODUCTION_T1_BUFF',	'CityStatesOnly',	0),
('GOLDEN_NATIONAL_SCIENCE_T2_BUFF',		'Amount',		2.2),
('GOLDEN_NATIONAL_FAITH_T2_BUFF',		'Amount',		2.2),
('GOLDEN_NATIONAL_GOLD_T2_BUFF',		'Amount',		2.2),
('GOLDEN_NATIONAL_CULTURE_T2_BUFF',		'Amount',		2.2),
('GOLDEN_NATIONAL_PRODUCTION_T2_BUFF',	'Amount',		2.2),
('GOLDEN_NATIONAL_SCIENCE_T2_BUFF',		'YieldType',	'YIELD_SCIENCE'),
('GOLDEN_NATIONAL_FAITH_T2_BUFF',		'YieldType',	'YIELD_FAITH'),
('GOLDEN_NATIONAL_GOLD_T2_BUFF',		'YieldType',	'YIELD_GOLD'),
('GOLDEN_NATIONAL_CULTURE_T2_BUFF',		'YieldType',	'YIELD_CULTURE'),
('GOLDEN_NATIONAL_PRODUCTION_T2_BUFF',	'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_NATIONAL_SCIENCE_T3_BUFF',		'Amount',		64),
('GOLDEN_NATIONAL_FAITH_T3_BUFF',		'Amount',		64),
('GOLDEN_NATIONAL_GOLD_T3_BUFF',		'Amount',		64),
('GOLDEN_NATIONAL_CULTURE_T3_BUFF',		'Amount',		64),
('GOLDEN_NATIONAL_PRODUCTION_T3_BUFF',	'Amount',		64),
('GOLDEN_NATIONAL_SCIENCE_T3_BUFF',		'YieldType',	'YIELD_SCIENCE'),
('GOLDEN_NATIONAL_FAITH_T3_BUFF',		'YieldType',	'YIELD_FAITH'),
('GOLDEN_NATIONAL_GOLD_T3_BUFF',		'YieldType',	'YIELD_GOLD'),
('GOLDEN_NATIONAL_CULTURE_T3_BUFF',		'YieldType',	'YIELD_CULTURE'),
('GOLDEN_NATIONAL_PRODUCTION_T3_BUFF',	'YieldType',	'YIELD_PRODUCTION');	
--DEBUFF	
INSERT OR REPLACE INTO BuildingModifiers 
(BuildingType, 							ModifierId) VALUES	
('BUILDING_NATIONAL_LIBRARY', 			'GOLDEN_NATIONAL_SCIENCE_T1_GAIN_DEBUFF'),	
('BUILDING_NATIONAL_SHRINE', 			'GOLDEN_NATIONAL_FAITH_T1_GAIN_DEBUFF'),
('BUILDING_NATIONAL_MARKET', 			'GOLDEN_NATIONAL_GOLD_T1_GAIN_DEBUFF'),
('BUILDING_NATIONAL_AMPHITHEATER', 		'GOLDEN_NATIONAL_CULTURE_T1_GAIN_DEBUFF'),
('BUILDING_NATIONAL_WORKSHOP', 			'GOLDEN_NATIONAL_PRODUCTION_T1_GAIN_DEBUFF'),
('BUILDING_NATIONAL_UNIVERSITY', 		'GOLDEN_NATIONAL_SCIENCE_T2_GAIN_DEBUFF'),
('BUILDING_NATIONAL_TEMPLE', 			'GOLDEN_NATIONAL_FAITH_T2_GAIN_DEBUFF'),	
('BUILDING_NATIONAL_BANK', 				'GOLDEN_NATIONAL_GOLD_T2_GAIN_DEBUFF'),
('BUILDING_NATIONAL_MUSEUM', 			'GOLDEN_NATIONAL_CULTURE_T2_GAIN_DEBUFF'),	
('BUILDING_NATIONAL_FACTORY', 			'GOLDEN_NATIONAL_PRODUCTION_T2_GAIN_DEBUFF'),
('BUILDING_NATIONAL_RESEARCH_LAB', 		'GOLDEN_NATIONAL_SCIENCE_T3_GAIN_DEBUFF'),
('BUILDING_NATIONAL_CATHEDRAL', 		'GOLDEN_NATIONAL_FAITH_T3_GAIN_DEBUFF'),	
('BUILDING_NATIONAL_STOCK_EXCHANGE', 	'GOLDEN_NATIONAL_GOLD_T3_GAIN_DEBUFF'),
('BUILDING_NATIONAL_BROADCAST_CENTER', 	'GOLDEN_NATIONAL_CULTURE_T3_GAIN_DEBUFF'),	
('BUILDING_NATIONAL_POWER_STATION', 	'GOLDEN_NATIONAL_PRODUCTION_T3_GAIN_DEBUFF');

INSERT OR REPLACE INTO Modifiers
(ModifierId,									ModifierType,										SubjectStackLimit) VALUES
('GOLDEN_NATIONAL_SCIENCE_T1_GAIN_DEBUFF',		'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1),
('GOLDEN_NATIONAL_FAITH_T1_GAIN_DEBUFF',		'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1),
('GOLDEN_NATIONAL_GOLD_T1_GAIN_DEBUFF',			'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1),
('GOLDEN_NATIONAL_CULTURE_T1_GAIN_DEBUFF',		'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1),
('GOLDEN_NATIONAL_PRODUCTION_T1_GAIN_DEBUFF',	'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1),
('GOLDEN_NATIONAL_SCIENCE_T2_GAIN_DEBUFF',		'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1),
('GOLDEN_NATIONAL_FAITH_T2_GAIN_DEBUFF',		'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1),
('GOLDEN_NATIONAL_GOLD_T2_GAIN_DEBUFF',			'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1),
('GOLDEN_NATIONAL_CULTURE_T2_GAIN_DEBUFF',		'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1),
('GOLDEN_NATIONAL_PRODUCTION_T2_GAIN_DEBUFF',	'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1),
('GOLDEN_NATIONAL_SCIENCE_T3_GAIN_DEBUFF',		'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1),
('GOLDEN_NATIONAL_FAITH_T3_GAIN_DEBUFF',		'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1),
('GOLDEN_NATIONAL_GOLD_T3_GAIN_DEBUFF',			'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1),
('GOLDEN_NATIONAL_CULTURE_T3_GAIN_DEBUFF',		'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1),
('GOLDEN_NATIONAL_PRODUCTION_T3_GAIN_DEBUFF',	'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',           1);

INSERT OR REPLACE INTO ModifierArguments
(ModifierId,									Name,				Value) VALUES
('GOLDEN_NATIONAL_SCIENCE_T1_GAIN_DEBUFF',		'ModifierId',		'GOLDEN_NATIONAL_SCIENCE_T1_DEBUFF'),	
('GOLDEN_NATIONAL_FAITH_T1_GAIN_DEBUFF',		'ModifierId',		'GOLDEN_NATIONAL_FAITH_T1_DEBUFF'),
('GOLDEN_NATIONAL_GOLD_T1_GAIN_DEBUFF',			'ModifierId',		'GOLDEN_NATIONAL_GOLD_T1_DEBUFF'),
('GOLDEN_NATIONAL_CULTURE_T1_GAIN_DEBUFF',		'ModifierId',		'GOLDEN_NATIONAL_CULTURE_T1_DEBUFF'),
('GOLDEN_NATIONAL_PRODUCTION_T1_GAIN_DEBUFF',	'ModifierId',		'GOLDEN_NATIONAL_PRODUCTION_T1_DEBUFF'),
('GOLDEN_NATIONAL_SCIENCE_T2_GAIN_DEBUFF',		'ModifierId',		'GOLDEN_NATIONAL_SCIENCE_T2_DEBUFF'),
('GOLDEN_NATIONAL_FAITH_T2_GAIN_DEBUFF',		'ModifierId',		'GOLDEN_NATIONAL_FAITH_T2_DEBUFF'),	
('GOLDEN_NATIONAL_GOLD_T2_GAIN_DEBUFF',			'ModifierId',		'GOLDEN_NATIONAL_GOLD_T2_DEBUFF'),
('GOLDEN_NATIONAL_CULTURE_T2_GAIN_DEBUFF',		'ModifierId',		'GOLDEN_NATIONAL_CULTURE_T2_DEBUFF'),	
('GOLDEN_NATIONAL_PRODUCTION_T2_GAIN_DEBUFF',	'ModifierId',		'GOLDEN_NATIONAL_PRODUCTION_T2_DEBUFF'),
('GOLDEN_NATIONAL_SCIENCE_T3_GAIN_DEBUFF',		'ModifierId',		'GOLDEN_NATIONAL_SCIENCE_T3_DEBUFF'),
('GOLDEN_NATIONAL_FAITH_T3_GAIN_DEBUFF',		'ModifierId',		'GOLDEN_NATIONAL_FAITH_T3_DEBUFF'),	
('GOLDEN_NATIONAL_GOLD_T3_GAIN_DEBUFF',			'ModifierId',		'GOLDEN_NATIONAL_GOLD_T3_DEBUFF'),
('GOLDEN_NATIONAL_CULTURE_T3_GAIN_DEBUFF',		'ModifierId',		'GOLDEN_NATIONAL_CULTURE_T3_DEBUFF'),	
('GOLDEN_NATIONAL_PRODUCTION_T3_GAIN_DEBUFF',	'ModifierId',		'GOLDEN_NATIONAL_PRODUCTION_T3_DEBUFF');

---------------------------------------------------------------

INSERT OR REPLACE INTO Modifiers
(ModifierId,								ModifierType,												SubjectRequirementSetId,										SubjectStackLimit) VALUES
('GOLDEN_NATIONAL_SCIENCE_T1_DEBUFF',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',		'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_LIBRARY',				7),
('GOLDEN_NATIONAL_FAITH_T1_DEBUFF',			'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',		'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_SHRINE',				7),
('GOLDEN_NATIONAL_GOLD_T1_DEBUFF',			'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',		'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_MARKET',				7),
('GOLDEN_NATIONAL_CULTURE_T1_DEBUFF',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',		'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_AMPHITHEATER',		7),
('GOLDEN_NATIONAL_PRODUCTION_T1_DEBUFF',	'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',		'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_WORKSHOP',			7),
('GOLDEN_NATIONAL_SCIENCE_T2_DEBUFF',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',	'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_UNIVERSITY', 			9),
('GOLDEN_NATIONAL_FAITH_T2_DEBUFF',			'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',	'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_TEMPLE', 				9),
('GOLDEN_NATIONAL_GOLD_T2_DEBUFF',			'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',	'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_BANK', 				9),
('GOLDEN_NATIONAL_CULTURE_T2_DEBUFF',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',	'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_MUSEUM', 				9),
('GOLDEN_NATIONAL_PRODUCTION_T2_DEBUFF',	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',	'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_FACTORY', 			9),
('GOLDEN_NATIONAL_SCIENCE_T3_DEBUFF',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',		'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_RESEARCH_LAB', 		12),
('GOLDEN_NATIONAL_FAITH_T3_DEBUFF',			'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',		'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_CATHEDRAL', 			12),
('GOLDEN_NATIONAL_GOLD_T3_DEBUFF',			'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',		'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_STOCK_EXCHANGE', 		12),
('GOLDEN_NATIONAL_CULTURE_T3_DEBUFF',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',		'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_BROADCAST_CENTER', 	12),
('GOLDEN_NATIONAL_PRODUCTION_T3_DEBUFF',	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',		'GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_POWER_STATION', 		12);

INSERT OR REPLACE INTO ModifierArguments
(ModifierId,								Name,			Value) VALUES
('GOLDEN_NATIONAL_SCIENCE_T1_DEBUFF',		'Amount',		-1),
('GOLDEN_NATIONAL_FAITH_T1_DEBUFF',			'Amount',		-1),
('GOLDEN_NATIONAL_GOLD_T1_DEBUFF',			'Amount',		-1),
('GOLDEN_NATIONAL_CULTURE_T1_DEBUFF',		'Amount',		-1),
('GOLDEN_NATIONAL_PRODUCTION_T1_DEBUFF',	'Amount',		-1),
('GOLDEN_NATIONAL_SCIENCE_T1_DEBUFF',		'YieldType',	'YIELD_SCIENCE'),
('GOLDEN_NATIONAL_FAITH_T1_DEBUFF',			'YieldType',	'YIELD_FAITH'),
('GOLDEN_NATIONAL_GOLD_T1_DEBUFF',			'YieldType',	'YIELD_GOLD'),
('GOLDEN_NATIONAL_CULTURE_T1_DEBUFF',		'YieldType',	'YIELD_CULTURE'),
('GOLDEN_NATIONAL_PRODUCTION_T1_DEBUFF',	'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_NATIONAL_SCIENCE_T1_DEBUFF',		'BuildingType',	'BUILDING_NATIONAL_LIBRARY'),
('GOLDEN_NATIONAL_FAITH_T1_DEBUFF',			'BuildingType',	'BUILDING_NATIONAL_SHRINE'),
('GOLDEN_NATIONAL_GOLD_T1_DEBUFF',			'BuildingType',	'BUILDING_NATIONAL_MARKET'),
('GOLDEN_NATIONAL_CULTURE_T1_DEBUFF',		'BuildingType',	'BUILDING_NATIONAL_AMPHITHEATER'),
('GOLDEN_NATIONAL_PRODUCTION_T1_DEBUFF',	'BuildingType',	'BUILDING_NATIONAL_WORKSHOP'),
('GOLDEN_NATIONAL_SCIENCE_T1_DEBUFF',		'CityStatesOnly',	0),
('GOLDEN_NATIONAL_FAITH_T1_DEBUFF',			'CityStatesOnly',	0),
('GOLDEN_NATIONAL_GOLD_T1_DEBUFF',			'CityStatesOnly',	0),
('GOLDEN_NATIONAL_CULTURE_T1_DEBUFF',		'CityStatesOnly',	0),
('GOLDEN_NATIONAL_PRODUCTION_T1_DEBUFF',	'CityStatesOnly',	0),
('GOLDEN_NATIONAL_SCIENCE_T2_DEBUFF',		'Amount',		-0.2),
('GOLDEN_NATIONAL_FAITH_T2_DEBUFF',			'Amount',		-0.2),
('GOLDEN_NATIONAL_GOLD_T2_DEBUFF',			'Amount',		-0.2),
('GOLDEN_NATIONAL_CULTURE_T2_DEBUFF',		'Amount',		-0.2),
('GOLDEN_NATIONAL_PRODUCTION_T2_DEBUFF',	'Amount',		-0.2),
('GOLDEN_NATIONAL_SCIENCE_T2_DEBUFF',		'YieldType',	'YIELD_SCIENCE'),
('GOLDEN_NATIONAL_FAITH_T2_DEBUFF',			'YieldType',	'YIELD_FAITH'),
('GOLDEN_NATIONAL_GOLD_T2_DEBUFF',			'YieldType',	'YIELD_GOLD'),
('GOLDEN_NATIONAL_CULTURE_T2_DEBUFF',		'YieldType',	'YIELD_CULTURE'),
('GOLDEN_NATIONAL_PRODUCTION_T2_DEBUFF',	'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_NATIONAL_SCIENCE_T3_DEBUFF',		'Amount',		-4),
('GOLDEN_NATIONAL_FAITH_T3_DEBUFF',			'Amount',		-4),
('GOLDEN_NATIONAL_GOLD_T3_DEBUFF',			'Amount',		-4),
('GOLDEN_NATIONAL_CULTURE_T3_DEBUFF',		'Amount',		-4),
('GOLDEN_NATIONAL_PRODUCTION_T3_DEBUFF',	'Amount',		-4),
('GOLDEN_NATIONAL_SCIENCE_T3_DEBUFF',		'YieldType',	'YIELD_SCIENCE'),
('GOLDEN_NATIONAL_FAITH_T3_DEBUFF',			'YieldType',	'YIELD_FAITH'),
('GOLDEN_NATIONAL_GOLD_T3_DEBUFF',			'YieldType',	'YIELD_GOLD'),
('GOLDEN_NATIONAL_CULTURE_T3_DEBUFF',		'YieldType',	'YIELD_CULTURE'),
('GOLDEN_NATIONAL_PRODUCTION_T3_DEBUFF',	'YieldType',	'YIELD_PRODUCTION');

INSERT OR REPLACE INTO RequirementSets 
(RequirementSetId,												RequirementSetType) VALUES
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_LIBRARY',			'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_SHRINE',				'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_MARKET',				'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_AMPHITHEATER',		'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_WORKSHOP',			'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_UNIVERSITY', 		'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_TEMPLE', 			'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_BANK', 				'REQUIREMENTSET_TEST_ALL'),	
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_MUSEUM', 			'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_FACTORY', 			'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_RESEARCH_LAB', 		'REQUIREMENTSET_TEST_ALL'),	
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_CATHEDRAL', 			'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_STOCK_EXCHANGE', 	'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_BROADCAST_CENTER', 	'REQUIREMENTSET_TEST_ALL'),	
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_POWER_STATION', 		'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements
(RequirementSetId,												RequirementId) VALUES	
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_LIBRARY',			'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_LIBRARY'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_SHRINE',				'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_SHRINE'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_MARKET',				'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_MARKET'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_AMPHITHEATER',		'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_AMPHITHEATER'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_WORKSHOP',			'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_WORKSHOP'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_UNIVERSITY', 		'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_UNIVERSITY'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_TEMPLE', 			'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_TEMPLE'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_BANK', 				'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_BANK'),	
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_MUSEUM', 			'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_MUSEUM'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_FACTORY', 			'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_FACTORY'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_RESEARCH_LAB', 		'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_RESEARCH_LAB'),	
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_CATHEDRAL', 			'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_CATHEDRAL'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_STOCK_EXCHANGE', 	'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_STOCK_EXCHANGE'),
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_BROADCAST_CENTER', 	'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_BROADCAST_CENTER'),	
('GOLDEN_REQSET_CITY_HAS_BUILDING_NATIONAL_POWER_STATION', 		'GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_POWER_STATION');

INSERT OR REPLACE INTO Requirements
(RequirementId, 												RequirementType) VALUES
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_LIBRARY',			'REQUIREMENT_CITY_HAS_BUILDING'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_SHRINE',			'REQUIREMENT_CITY_HAS_BUILDING'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_MARKET',			'REQUIREMENT_CITY_HAS_BUILDING'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_AMPHITHEATER',		'REQUIREMENT_CITY_HAS_BUILDING'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_WORKSHOP',			'REQUIREMENT_CITY_HAS_BUILDING'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_UNIVERSITY', 		'REQUIREMENT_CITY_HAS_BUILDING'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_TEMPLE', 			'REQUIREMENT_CITY_HAS_BUILDING'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_BANK', 			'REQUIREMENT_CITY_HAS_BUILDING'),	
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_MUSEUM', 			'REQUIREMENT_CITY_HAS_BUILDING'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_FACTORY', 			'REQUIREMENT_CITY_HAS_BUILDING'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_RESEARCH_LAB', 	'REQUIREMENT_CITY_HAS_BUILDING'),	
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_CATHEDRAL', 		'REQUIREMENT_CITY_HAS_BUILDING'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_STOCK_EXCHANGE', 	'REQUIREMENT_CITY_HAS_BUILDING'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_BROADCAST_CENTER', 'REQUIREMENT_CITY_HAS_BUILDING'),	
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_POWER_STATION', 	'REQUIREMENT_CITY_HAS_BUILDING');

INSERT OR REPLACE INTO RequirementArguments 
(RequirementId,													Name, 			Value) VALUES 	
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_LIBRARY',			'BuildingType',	'BUILDING_NATIONAL_LIBRARY'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_SHRINE',			'BuildingType',	'BUILDING_NATIONAL_SHRINE'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_MARKET',			'BuildingType',	'BUILDING_NATIONAL_MARKET'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_AMPHITHEATER',		'BuildingType',	'BUILDING_NATIONAL_AMPHITHEATER'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_WORKSHOP',			'BuildingType',	'BUILDING_NATIONAL_WORKSHOP'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_UNIVERSITY', 		'BuildingType',	'BUILDING_NATIONAL_UNIVERSITY'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_TEMPLE', 			'BuildingType',	'BUILDING_NATIONAL_TEMPLE'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_BANK', 			'BuildingType',	'BUILDING_NATIONAL_BANK'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_MUSEUM', 			'BuildingType',	'BUILDING_NATIONAL_MUSEUM'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_FACTORY', 			'BuildingType',	'BUILDING_NATIONAL_FACTORY'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_RESEARCH_LAB', 	'BuildingType',	'BUILDING_NATIONAL_RESEARCH_LAB'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_CATHEDRAL', 		'BuildingType',	'BUILDING_NATIONAL_CATHEDRAL'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_STOCK_EXCHANGE', 	'BuildingType',	'BUILDING_NATIONAL_STOCK_EXCHANGE'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_BROADCAST_CENTER', 'BuildingType',	'BUILDING_NATIONAL_BROADCAST_CENTER'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_NATIONAL_POWER_STATION', 	'BuildingType',	'BUILDING_NATIONAL_POWER_STATION');
------------------------------------
------------------------------------
INSERT OR REPLACE INTO District_Adjacencies 
(DistrictType, YieldChangeId) VALUES	
('DISTRICT_CAMPUS', 'GOLDEN_NATIONAL_CAMPUS_SCIENCE'),
('DISTRICT_CAMPUS', 'GOLDEN_NATIONAL_CAMPUS_SCIENCE_PLUS'),
('DISTRICT_HOLY_SITE', 'GOLDEN_NATIONAL_HOLY_SITE_FAITH'),
('DISTRICT_HOLY_SITE', 'GOLDEN_NATIONAL_HOLY_SITE_FAITH_PLUS'),
('DISTRICT_COMMERCIAL_HUB', 'GOLDEN_NATIONAL_COMMERCIAL_HUB_GOLD'),
('DISTRICT_COMMERCIAL_HUB', 'GOLDEN_NATIONAL_COMMERCIAL_HUB_GOLD_PLUS'),
('DISTRICT_THEATER', 'GOLDEN_NATIONAL_THEATER_CULTURE'),
('DISTRICT_THEATER', 'GOLDEN_NATIONAL_THEATER_CULTURE_PLUS'),
('DISTRICT_INDUSTRIAL_ZONE', 'GOLDEN_NATIONAL_INDUSTRIAL_ZONE_PRODUCTION'),
('DISTRICT_INDUSTRIAL_ZONE', 'GOLDEN_NATIONAL_INDUSTRIAL_ZONE_PRODUCTION_PLUS'),
('DISTRICT_HARBOR', 'GOLDEN_NATIONAL_HARBOR_GOLD'),
('DISTRICT_HARBOR', 'GOLDEN_NATIONAL_HARBOR_GOLD_PLUS'),
--UD
('DISTRICT_HANSA', 'GOLDEN_NATIONAL_INDUSTRIAL_ZONE_PRODUCTION'),
('DISTRICT_HANSA', 'GOLDEN_NATIONAL_INDUSTRIAL_ZONE_PRODUCTION_PLUS'),
('DISTRICT_ACROPOLIS', 'GOLDEN_NATIONAL_THEATER_CULTURE'),
('DISTRICT_ACROPOLIS', 'GOLDEN_NATIONAL_THEATER_CULTURE_PLUS'),
('DISTRICT_ROYAL_NAVY_DOCKYARD', 'GOLDEN_NATIONAL_HARBOR_GOLD'),
('DISTRICT_ROYAL_NAVY_DOCKYARD', 'GOLDEN_NATIONAL_HARBOR_GOLD_PLUS'),
('DISTRICT_COTHON', 'GOLDEN_NATIONAL_HARBOR_GOLD'),
('DISTRICT_COTHON', 'GOLDEN_NATIONAL_HARBOR_GOLD_PLUS'),
('DISTRICT_SUGUBA', 'GOLDEN_NATIONAL_COMMERCIAL_HUB_GOLD'),
('DISTRICT_SUGUBA', 'GOLDEN_NATIONAL_COMMERCIAL_HUB_GOLD_PLUS'),
('DISTRICT_SEOWON', 'GOLDEN_NATIONAL_CAMPUS_SCIENCE'),
('DISTRICT_SEOWON', 'GOLDEN_NATIONAL_CAMPUS_SCIENCE_PLUS'),
('DISTRICT_LAVRA', 'GOLDEN_NATIONAL_HOLY_SITE_FAITH'),
('DISTRICT_LAVRA', 'GOLDEN_NATIONAL_HOLY_SITE_FAITH_PLUS');
--DLC UD
INSERT OR REPLACE INTO District_Adjacencies (DistrictType, YieldChangeId)
SELECT	'DISTRICT_OPPIDUM', 'GOLDEN_NATIONAL_INDUSTRIAL_ZONE_PRODUCTION' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO District_Adjacencies (DistrictType, YieldChangeId)
SELECT	'DISTRICT_OPPIDUM', 'GOLDEN_NATIONAL_INDUSTRIAL_ZONE_PRODUCTION_PLUS' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO District_Adjacencies (DistrictType, YieldChangeId)
SELECT	'DISTRICT_OBSERVATORY', 'GOLDEN_NATIONAL_CAMPUS_SCIENCE' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO District_Adjacencies (DistrictType, YieldChangeId)
SELECT	'DISTRICT_OBSERVATORY', 'GOLDEN_NATIONAL_CAMPUS_SCIENCE_PLUS' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
------------------------------------
--HOUSING AND AMENITY ADJACENCY BONUS FROM NATIONAL WONDER DISTRICT
-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_LEADER_MAJOR_CIV',	            'GOLDEN_ENCAMPMENT_NATIONAL_ENCAMPMENT_HOUSING'),
('TRAIT_CIVILIZATION_ZULU_ISIBONGO',	'GOLDEN_IKANDA_NATIONAL_ENCAMPMENT_HOUSING'),
('TRAIT_LEADER_MAJOR_CIV',	            'GOLDEN_ENTERTAINMENT_COMPLEX_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY'),
('TRAIT_LEADER_MAJOR_CIV',	            'GOLDEN_WATER_ENTERTAINMENT_COMPLEX_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY'),
('TRAIT_CIVILIZATION_AMAZON',	        'GOLDEN_WATER_STREET_CARNIVAL_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY'),
('TRAIT_CIVILIZATION_AMAZON',	        'GOLDEN_STREET_CARNIVAL_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY');
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
SELECT	'TRAIT_CIVILIZATION_BYZANTIUM', 'GOLDEN_HIPPODROME_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
SELECT	'TRAIT_CIVILIZATION_VIETNAM', 'GOLDEN_THANH_NATIONAL_ENCAMPMENT_HOUSING' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');

-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
('GOLDEN_ENCAMPMENT_NATIONAL_ENCAMPMENT_HOUSING',                        'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',               0, 0,  'GOLDEN_DISTRICT_IS_ENCAMPMENT_ADJACENT_TO_NATIONAL_ENCAMPMENT_REQUIREMENTS'),
('GOLDEN_IKANDA_NATIONAL_ENCAMPMENT_HOUSING',                            'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',               0, 0,  'GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_NATIONAL_ENCAMPMENT_REQUIREMENTS'),
('GOLDEN_ENTERTAINMENT_COMPLEX_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY',  'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT',   0, 0,  'GOLDEN_DISTRICT_IS_ENTERTAINMENT_COMPLEX_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS'),
('GOLDEN_WATER_ENTERTAINMENT_COMPLEX_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY',  'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT',   0, 0,  'GOLDEN_DISTRICT_IS_WATER_ENTERTAINMENT_COMPLEX_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS'),
('GOLDEN_WATER_STREET_CARNIVAL_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY',  'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT',   0, 0,  'GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS'),
('GOLDEN_STREET_CARNIVAL_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY',        'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT',   0, 0,  'GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
SELECT	'GOLDEN_HIPPODROME_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT', 0, 0, 'GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
SELECT	'GOLDEN_THANH_NATIONAL_ENCAMPMENT_HOUSING', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING', 0, 0, 'GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_NATIONAL_ENCAMPMENT_REQUIREMENTS' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');
-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_ENCAMPMENT_NATIONAL_ENCAMPMENT_HOUSING',				                'Amount',	   3),
('GOLDEN_IKANDA_NATIONAL_ENCAMPMENT_HOUSING',				                    'Amount',	   3),
('GOLDEN_ENTERTAINMENT_COMPLEX_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY',			'Amount',	   2),
('GOLDEN_WATER_ENTERTAINMENT_COMPLEX_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY',	'Amount',	   2),
('GOLDEN_WATER_STREET_CARNIVAL_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY',			'Amount',	   2),
('GOLDEN_STREET_CARNIVAL_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY',				'Amount',	   2);
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_HIPPODROME_NATIONAL_ENTERTAINMENT_COMPLEX_AMENITY', 'Amount', 2 WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_THANH_NATIONAL_ENCAMPMENT_HOUSING', 'Amount', 3 WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');
---------------------------------------------------------------------------------------------------------------
-- RequirementSets
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSets		(RequirementSetId,							RequirementSetType) VALUES
('GOLDEN_DISTRICT_IS_ENCAMPMENT_ADJACENT_TO_NATIONAL_ENCAMPMENT_REQUIREMENTS',		                    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_NATIONAL_ENCAMPMENT_REQUIREMENTS',		                        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_ENTERTAINMENT_COMPLEX_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS',	'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_WATER_ENTERTAINMENT_COMPLEX_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS',	'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS',	'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS',		    'REQUIREMENTSET_TEST_ALL');
INSERT OR REPLACE INTO RequirementSets (RequirementSetId, RequirementSetType)
SELECT	'GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO RequirementSets (RequirementSetId, RequirementSetType)
SELECT	'GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_NATIONAL_ENCAMPMENT_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');
---------------------------------------------------------------------------------------------------------------
-- RequirementSetRequirements
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSetRequirements		(RequirementSetId,							RequirementId) VALUES	
('GOLDEN_DISTRICT_IS_ENCAMPMENT_ADJACENT_TO_NATIONAL_ENCAMPMENT_REQUIREMENTS',		'REQUIRES_DISTRICT_IS_ENCAMPMENT'),
('GOLDEN_DISTRICT_IS_ENCAMPMENT_ADJACENT_TO_NATIONAL_ENCAMPMENT_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_NATIONAL_ENCAMPMENT'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_NATIONAL_ENCAMPMENT_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_IKANDA'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_NATIONAL_ENCAMPMENT_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_NATIONAL_ENCAMPMENT'),
('GOLDEN_DISTRICT_IS_ENTERTAINMENT_COMPLEX_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_ENTERTAINMENT_COMPLEX'),
('GOLDEN_DISTRICT_IS_ENTERTAINMENT_COMPLEX_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX'),
('GOLDEN_DISTRICT_IS_WATER_ENTERTAINMENT_COMPLEX_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_WATER_ENTERTAINMENT_COMPLEX'),
('GOLDEN_DISTRICT_IS_WATER_ENTERTAINMENT_COMPLEX_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_WATER_STREET_CARNIVAL'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX'),
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_STREET_CARNIVAL'),
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX');
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT	'GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS', 'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HIPPODROME' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT	'GOLDEN_DISTRICT_IS_HIPPODROME_ADJACENT_TO_NATIONAL_ENTERTAINMENT_COMPLEX_REQUIREMENTS', 'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_BYZANTINE_DROMON');
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT	'GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_NATIONAL_ENCAMPMENT_REQUIREMENTS', 'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THANH' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT	'GOLDEN_DISTRICT_IS_THANH_ADJACENT_TO_NATIONAL_ENCAMPMENT_REQUIREMENTS', 'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_NATIONAL_ENCAMPMENT' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN');
---------------------------------------------------------------------------------------------------------------
-- Requirements
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO Requirements	(RequirementId,												RequirementType) VALUES	
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_NATIONAL_ENCAMPMENT',				'REQUIREMENT_PLOT_ADJACENT_DISTRICT_TYPE_MATCHES'),
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX',		'REQUIREMENT_PLOT_ADJACENT_DISTRICT_TYPE_MATCHES');
---------------------------------------------------------------------------------------------------------------
-- RequirementArguments
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO RequirementArguments		(RequirementId,												Name,			Value) VALUES	
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_NATIONAL_ENCAMPMENT',				'DistrictType',	'DISTRICT_NATIONAL_ENCAMPMENT'),
('GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX',		'DistrictType',	'DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX');

---------------------------------------------------------------------------------------------------------------
-- Policy (when districts and buildings production bonus policies exist)
---------------------------------------------------------------------------------------------------------------   
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_RELAXATION', 'GOLDEN_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX_DISTRICT_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_RELAXATION', 'GOLDEN_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX_BUILDINGS_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_SACRED', 'GOLDEN_DISTRICT_NATIONAL_HOLY_SITE_DISTRICT_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_SACRED', 'GOLDEN_DISTRICT_NATIONAL_HOLY_SITE_BUILDINGS_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_SEAFAIRING', 'GOLDEN_DISTRICT_NATIONAL_HARBOR_DISTRICT_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_SEAFAIRING', 'GOLDEN_DISTRICT_NATIONAL_HARBOR_BUILDINGS_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_ARTS_HUMANITIES', 'GOLDEN_DISTRICT_NATIONAL_THEATER_DISTRICT_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_ARTS_HUMANITIES', 'GOLDEN_DISTRICT_NATIONAL_THEATER_BUILDINGS_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_MANUFACTURE', 'GOLDEN_DISTRICT_NATIONAL_INDUSTRIAL_ZONE_DISTRICT_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_MANUFACTURE', 'GOLDEN_DISTRICT_NATIONAL_INDUSTRIAL_ZONE_BUILDINGS_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_BUSINESS', 'GOLDEN_DISTRICT_NATIONAL_COMMERCIAL_HUB_DISTRICT_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_BUSINESS', 'GOLDEN_DISTRICT_NATIONAL_COMMERCIAL_HUB_BUILDINGS_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_VETERANCY', 'GOLDEN_DISTRICT_NATIONAL_ENCAMPMENT_DISTRICT_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_VETERANCY', 'GOLDEN_DISTRICT_NATIONAL_ENCAMPMENT_BUILDINGS_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_MOTIVATION', 'GOLDEN_DISTRICT_NATIONAL_CAMPUS_DISTRICT_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO PolicyModifiers (PolicyType, ModifierId)
SELECT	'POLICY_MOTIVATION', 'GOLDEN_DISTRICT_NATIONAL_CAMPUS_BUILDINGS_PRODUCTION' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');

INSERT OR REPLACE INTO Modifiers
       (ModifierId , ModifierType)
SELECT ModifierId , 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION' 
FROM PolicyModifiers WHERE ModifierId LIKE 'GOLDEN_DISTRICT_NATIONAL_%_DISTRICT_PRODUCTION' AND EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');

INSERT OR REPLACE INTO Modifiers
       (ModifierId , ModifierType) SELECT
       ModifierId , 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'
FROM PolicyModifiers WHERE ModifierId LIKE 'GOLDEN_DISTRICT_NATIONAL_%_BUILDINGS_PRODUCTION' AND EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');

INSERT OR REPLACE INTO ModifierArguments
       (ModifierId , Name , Value)
SELECT  ModifierId , 'Amount' , 50 FROM PolicyModifiers WHERE ModifierId LIKE 'GOLDEN_DISTRICT_NATIONAL_%_DISTRICT_PRODUCTION' AND EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');

INSERT OR REPLACE INTO ModifierArguments
       (ModifierId , Name , Value)
SELECT ModifierId , 'Amount' , 50 FROM PolicyModifiers WHERE ModifierId LIKE 'GOLDEN_DISTRICT_NATIONAL_%_BUILDINGS_PRODUCTION' AND EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
	   
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX_DISTRICT_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX_BUILDINGS_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_HOLY_SITE_DISTRICT_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_HOLY_SITE' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_HOLY_SITE_BUILDINGS_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_HOLY_SITE' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_HARBOR_DISTRICT_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_HARBOR' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_HARBOR_BUILDINGS_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_HARBOR' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_THEATER_DISTRICT_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_THEATER' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_THEATER_BUILDINGS_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_THEATER' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_INDUSTRIAL_ZONE_DISTRICT_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_INDUSTRIAL_ZONE' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_INDUSTRIAL_ZONE_BUILDINGS_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_INDUSTRIAL_ZONE' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_COMMERCIAL_HUB_DISTRICT_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_COMMERCIAL_HUB' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_COMMERCIAL_HUB_BUILDINGS_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_COMMERCIAL_HUB' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_ENCAMPMENT_DISTRICT_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_ENCAMPMENT' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_ENCAMPMENT_BUILDINGS_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_ENCAMPMENT' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_CAMPUS_DISTRICT_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_CAMPUS' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_DISTRICT_NATIONAL_CAMPUS_BUILDINGS_PRODUCTION', 'DistrictType', 'DISTRICT_NATIONAL_CAMPUS' WHERE EXISTS (SELECT PolicyType FROM Policies WHERE PolicyType = 'POLICY_RELAXATION');