
--铺城扩张偏好
-- DELETE FROM LeaderTraits WHERE TraitType = 'TRAIT_LEADER_EXPANSIONIST';

-- UPDATE AiLists SET LeaderType = 'TRAIT_LEADER_MAJOR_CIV' WHERE ListType = "ExpansionistCitySettlement";

--宣战（突袭）偏好
-- DELETE FROM LeaderTraits WHERE TraitType ='TRAIT_LEADER_AGGRESSIVE_MILITARY';

-- UPDATE AiLists SET LeaderType = 'TRAIT_LEADER_MAJOR_CIV' WHERE ListType = "AgressiveDiplomacy";

-- UPDATE AiFavoredItems SET Item = 'DIPLOACTION_DECLARE_SURPRISE_WAR' WHERE ListType = "AgressiveDiplomacy";

--兵种偏好
UPDATE AiLists SET LeaderType = 'TRAIT_LEADER_MAJOR_CIV' WHERE ListType = "TomyrisiUnitBuilds";--PROMOTION_CLASS_LIGHT_CAVALRY

INSERT OR REPLACE INTO AiListTypes
(ListType)  VALUES 
('GOLDEN_PROMOTION_CLASS_MELEE'), 
('GOLDEN_PROMOTION_CLASS_HEAVY_CAVALRY'), 
('GOLDEN_PROMOTION_CLASS_SIEGE');

INSERT OR REPLACE INTO AiFavoredItems
(ListType, Item, Value)  VALUES 
('GOLDEN_PROMOTION_CLASS_MELEE', 'PROMOTION_CLASS_MELEE', 1), 
('GOLDEN_PROMOTION_CLASS_HEAVY_CAVALRY', 'PROMOTION_CLASS_HEAVY_CAVALRY', 1), 
('GOLDEN_PROMOTION_CLASS_SIEGE', 'PROMOTION_CLASS_SIEGE', 1);

INSERT OR REPLACE INTO AiLists
(ListType, LeaderType, System)  VALUES 
('GOLDEN_PROMOTION_CLASS_MELEE', 'TRAIT_LEADER_MAJOR_CIV', 'UnitPromotionClasses'),
('GOLDEN_PROMOTION_CLASS_HEAVY_CAVALRY', 'TRAIT_LEADER_MAJOR_CIV', 'UnitPromotionClasses'),
('GOLDEN_PROMOTION_CLASS_SIEGE', 'TRAIT_LEADER_MAJOR_CIV', 'UnitPromotionClasses');

--宗教偏好
-- DELETE FROM LeaderTraits WHERE TraitType = 'TRAIT_LEADER_NONRELIGIOUS_MAJOR_CIV';
-- DELETE FROM LeaderTraits WHERE TraitType = 'TRAIT_LEADER_LOW_RELIGIOUS_PREFERENCE';
      	   	   
--空军偏好
-- UPDATE PseudoYields SET DefaultValue=22 WHERE PseudoYieldType="PSEUDOYIELD_UNIT_AIR_COMBAT"; --DefaultValue=2 +50trait=52
-- UPDATE AiFavoredItems SET Value=30 WHERE ListType="AirpowerLoverAirpowerPreference"; --Value=50 30+22=52

--产出偏好
-- UPDATE AiFavoredItems SET Value = 3 WHERE ListType="DefaultCitySpecialization" AND Item="BUILD_FOR_FOOD";
-- UPDATE AiFavoredItems SET Value = 3 WHERE ListType="DefaultCitySpecialization" AND Item="BUILD_FOR_PRODUCTION";
-- UPDATE AiFavoredItems SET Value = 1 WHERE ListType="DefaultCitySpecialization" AND Item="BUILD_FOR_GOLD";
-- UPDATE AiFavoredItems SET Value = 2 WHERE ListType="DefaultCitySpecialization" AND Item="BUILD_FOR_SCIENCE";
-- UPDATE AiFavoredItems SET Value = 2 WHERE ListType="DefaultCitySpecialization" AND Item="BUILD_FOR_CULTURE";
-- UPDATE AiFavoredItems SET Value = 1 WHERE ListType="DefaultCitySpecialization" AND Item="BUILD_FOR_FAITH";

UPDATE AiFavoredItems SET Value = 15 WHERE ListType="DefaultYieldBias" AND Item="YIELD_PRODUCTION";--was 25
UPDATE AiFavoredItems SET Value = 15 WHERE ListType="DefaultYieldBias" AND Item="YIELD_SCIENCE";--was 10
UPDATE AiFavoredItems SET Value = 15 WHERE ListType="DefaultYieldBias" AND Item="YIELD_CULTURE";--was 10
UPDATE AiFavoredItems SET Value = 15 WHERE ListType="DefaultYieldBias" AND Item="YIELD_GOLD";--was 20
UPDATE AiFavoredItems SET Value = 15 WHERE ListType="DefaultYieldBias" AND Item="YIELD_FAITH";--was -25

--建造区域偏好
INSERT OR REPLACE INTO AiLists
(ListType, LeaderType, System)  VALUES 
('MinorCivScienceDistrict', 'TRAIT_LEADER_MAJOR_CIV', 'Districts'), 
('MinorCivReligiousDistrict', 'TRAIT_LEADER_MAJOR_CIV', 'Districts'), 
('MinorCivTradeDistrict', 'TRAIT_LEADER_MAJOR_CIV', 'Districts'), 
('MinorCivCultureDistrict', 'TRAIT_LEADER_MAJOR_CIV', 'Districts'), 
-- ('MinorCivMilitaryDistrict', 'TRAIT_LEADER_MAJOR_CIV', 'Districts'), --Always first district to build
('MinorCivIndustryDistrict', 'TRAIT_LEADER_MAJOR_CIV', 'Districts');

--国家区域偏好
INSERT OR REPLACE INTO AiListTypes
(ListType)  VALUES 
('GOLDEN_DISTRICT_NATIONAL_CAMPUS'), 
('GOLDEN_DISTRICT_NATIONAL_HOLY_SITE'), 
('GOLDEN_DISTRICT_NATIONAL_COMMERCIAL_HUB'), 
('GOLDEN_DISTRICT_NATIONAL_THEATER'), 
('GOLDEN_DISTRICT_NATIONAL_INDUSTRIAL_ZONE'), 
('GOLDEN_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX'), 
('GOLDEN_DISTRICT_NATIONAL_ENCAMPMENT'), 
('GOLDEN_DISTRICT_NATIONAL_HARBOR');

INSERT OR REPLACE INTO AiFavoredItems
(ListType, Item, Favored)  VALUES 
('GOLDEN_DISTRICT_NATIONAL_CAMPUS',                'DISTRICT_NATIONAL_CAMPUS', 1), 
('GOLDEN_DISTRICT_NATIONAL_HOLY_SITE',             'DISTRICT_NATIONAL_HOLY_SITE', 1), 
('GOLDEN_DISTRICT_NATIONAL_COMMERCIAL_HUB',        'DISTRICT_NATIONAL_COMMERCIAL_HUB', 1), 
('GOLDEN_DISTRICT_NATIONAL_THEATER',               'DISTRICT_NATIONAL_THEATER', 1), 
('GOLDEN_DISTRICT_NATIONAL_INDUSTRIAL_ZONE',       'DISTRICT_NATIONAL_INDUSTRIAL_ZONE', 1), 
('GOLDEN_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX', 'DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX', 1), 
('GOLDEN_DISTRICT_NATIONAL_ENCAMPMENT',            'DISTRICT_NATIONAL_ENCAMPMENT', 1), 
('GOLDEN_DISTRICT_NATIONAL_HARBOR',                'DISTRICT_NATIONAL_HARBOR', 1);

INSERT OR REPLACE INTO AiLists
(ListType, LeaderType, System)  VALUES 
('GOLDEN_DISTRICT_NATIONAL_CAMPUS',                'TRAIT_LEADER_MAJOR_CIV', 'Districts'),
('GOLDEN_DISTRICT_NATIONAL_HOLY_SITE',             'TRAIT_LEADER_MAJOR_CIV', 'Districts'),
('GOLDEN_DISTRICT_NATIONAL_COMMERCIAL_HUB',        'TRAIT_LEADER_MAJOR_CIV', 'Districts'),
('GOLDEN_DISTRICT_NATIONAL_THEATER',               'TRAIT_LEADER_MAJOR_CIV', 'Districts'),
('GOLDEN_DISTRICT_NATIONAL_INDUSTRIAL_ZONE',       'TRAIT_LEADER_MAJOR_CIV', 'Districts'),
('GOLDEN_DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX', 'TRAIT_LEADER_MAJOR_CIV', 'Districts'),
('GOLDEN_DISTRICT_NATIONAL_ENCAMPMENT',            'TRAIT_LEADER_MAJOR_CIV', 'Districts'),
('GOLDEN_DISTRICT_NATIONAL_HARBOR',                'TRAIT_LEADER_MAJOR_CIV', 'Districts');

--市政广场偏好
-- INSERT OR REPLACE INTO AiListTypes
-- (ListType)  VALUES 
-- ('GOLDEN_DISTRICT_GOVERNMENT');

-- INSERT OR REPLACE INTO AiFavoredItems
-- (ListType, Item, Favored)  VALUES 
-- ('GOLDEN_DISTRICT_GOVERNMENT',           'DISTRICT_GOVERNMENT', 1);

-- INSERT OR REPLACE INTO AiLists
-- (ListType, LeaderType, System)  VALUES 
-- ('GOLDEN_DISTRICT_GOVERNMENT',           'TRAIT_LEADER_MAJOR_CIV', 'Districts');

--建造区域建筑偏好
-- INSERT OR REPLACE INTO AiListTypes
-- (ListType)  VALUES 
-- ('GOLDEN_BUILDING_SHRINE'), 
-- ('GOLDEN_BUILDING_TEMPLE');
-- ('GOLDEN_BUILDING_LIBRARY'), 
-- ('GOLDEN_BUILDING_UNIVERSITY'), 
-- ('GOLDEN_BUILDING_RESEARCH_LAB'), 
-- ('GOLDEN_BUILDING_AMPHITHEATER'), 
-- ('GOLDEN_BUILDING_MUSEUM_ART'), 
-- ('GOLDEN_BUILDING_MUSEUM_ARTIFACT'),
-- ('GOLDEN_BUILDING_BROADCAST_CENTER'),  
-- ('GOLDEN_BUILDING_MARKET'), 
-- ('GOLDEN_BUILDING_BANK'),
-- ('GOLDEN_BUILDING_STOCK_EXCHANGE'), 
-- ('GOLDEN_BUILDING_WORKSHOP'), 
-- ('GOLDEN_BUILDING_FACTORY'),
-- ('GOLDEN_BUILDING_LIGHTHOUSE'),
-- ('GOLDEN_BUILDING_SHIPYARD'), 
-- ('GOLDEN_BUILDING_SEAPORT'),
-- ('GOLDEN_BUILDING_BARRACKS'),
-- ('GOLDEN_BUILDING_STABLE'), 
-- ('GOLDEN_BUILDING_ARMORY'),
-- ('GOLDEN_BUILDING_MILITARY_ACADEMY');

-- INSERT OR REPLACE INTO AiFavoredItems
-- (ListType, Item, Favored)  VALUES 
-- ('GOLDEN_BUILDING_SHRINE', 'BUILDING_SHRINE', 1), 
-- ('GOLDEN_BUILDING_TEMPLE', 'BUILDING_TEMPLE', 1);
-- ('GOLDEN_BUILDING_LIBRARY', 'BUILDING_LIBRARY', 1), 
-- ('GOLDEN_BUILDING_UNIVERSITY', 'BUILDING_UNIVERSITY', 1), 
-- ('GOLDEN_BUILDING_RESEARCH_LAB', 'BUILDING_RESEARCH_LAB', 1), 
-- ('GOLDEN_BUILDING_AMPHITHEATER', 'BUILDING_AMPHITHEATER', 1), 
-- ('GOLDEN_BUILDING_MUSEUM_ART', 'BUILDING_MUSEUM_ART', 1), 
-- ('GOLDEN_BUILDING_MUSEUM_ARTIFACT', 'BUILDING_MUSEUM_ARTIFACT', 1), 
-- ('GOLDEN_BUILDING_BROADCAST_CENTER', 'BUILDING_BROADCAST_CENTER', 1), 
-- ('GOLDEN_BUILDING_MARKET', 'BUILDING_MARKET', 1), 
-- ('GOLDEN_BUILDING_BANK', 'BUILDING_BANK', 1), 
-- ('GOLDEN_BUILDING_STOCK_EXCHANGE', 'BUILDING_STOCK_EXCHANGE', 1), 
-- ('GOLDEN_BUILDING_WORKSHOP', 'BUILDING_WORKSHOP', 1), 
-- ('GOLDEN_BUILDING_FACTORY', 'BUILDING_FACTORY', 1), 
-- ('GOLDEN_BUILDING_LIGHTHOUSE', 'BUILDING_LIGHTHOUSE', 1), 
-- ('GOLDEN_BUILDING_SHIPYARD', 'BUILDING_SHIPYARD', 1), 
-- ('GOLDEN_BUILDING_SEAPORT', 'BUILDING_SEAPORT', 1),
-- ('GOLDEN_BUILDING_BARRACKS', 'BUILDING_BARRACKS', 1), 
-- ('GOLDEN_BUILDING_STABLE', 'BUILDING_STABLE', 1), 
-- ('GOLDEN_BUILDING_ARMORY', 'BUILDING_ARMORY', 1), 
-- ('GOLDEN_BUILDING_MILITARY_ACADEMY', 'BUILDING_MILITARY_ACADEMY', 1);

-- INSERT OR REPLACE INTO AiLists
-- (ListType, LeaderType, System)  VALUES 
-- ('GOLDEN_BUILDING_SHRINE', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_TEMPLE', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings');
-- ('GOLDEN_BUILDING_LIBRARY', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_UNIVERSITY', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_RESEARCH_LAB', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_AMPHITHEATER', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_MUSEUM_ART', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_MUSEUM_ARTIFACT', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_BROADCAST_CENTER', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_MARKET', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_BANK', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_STOCK_EXCHANGE', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_WORKSHOP', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_FACTORY', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_LIGHTHOUSE', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_SHIPYARD', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_SEAPORT', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_BARRACKS', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_STABLE', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_ARMORY', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'),
-- ('GOLDEN_BUILDING_MILITARY_ACADEMY', 'TRAIT_LEADER_MAJOR_CIV', 'Buildings');

--个别
--胜利方式偏好
INSERT OR REPLACE INTO LeaderTraits(LeaderType, TraitType) 
VALUES ('LEADER_T_ROOSEVELT', 'TRAIT_LEADER_SCIENCE_MAJOR_CIV'),       
	   ('LEADER_CLEOPATRA', 'TRAIT_LEADER_CULTURAL_MAJOR_CIV'),
       ('LEADER_VICTORIA', 'TRAIT_LEADER_SCIENCE_MAJOR_CIV'),
	   ('LEADER_CATHERINE_DE_MEDICI', 'TRAIT_LEADER_PURSUE_DIPLOMATIC_VICTORY'),
       ('LEADER_BARBAROSSA', 'TRAIT_LEADER_SCIENCE_MAJOR_CIV'),
	   ('LEADER_HOJO', 'TRAIT_LEADER_SCIENCE_MAJOR_CIV'),
       ('LEADER_POUNDMAKER', 'TRAIT_LEADER_SCIENCE_MAJOR_CIV'),
	   ('LEADER_WILHELMINA', 'TRAIT_LEADER_CULTURAL_MAJOR_CIV'),
       ('LEADER_ELEANOR_ENGLAND', 'TRAIT_LEADER_CULTURAL_MAJOR_CIV'),
	   ('LEADER_MANSA_MUSA', 'TRAIT_LEADER_PURSUE_DIPLOMATIC_VICTORY'),
	   ('LEADER_LAUTARO', 'TRAIT_LEADER_SCIENCE_MAJOR_CIV'),
	   ('LEADER_LAUTARO', 'TRAIT_LEADER_CULTURAL_MAJOR_CIV'),
	   ('LEADER_DIDO', 'TRAIT_LEADER_SCIENCE_MAJOR_CIV');	

INSERT OR REPLACE INTO LeaderTraits(LeaderType, TraitType) 	   
SELECT 'LEADER_JAYAVARMAN', 'TRAIT_LEADER_RELIGIOUS_MAJOR_CIV' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');
INSERT OR REPLACE INTO LeaderTraits(LeaderType, TraitType) 	   
SELECT 'LEADER_GITARJA', 'TRAIT_LEADER_RELIGIOUS_MAJOR_CIV' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_INDONESIAN_JONG');	

INSERT OR REPLACE INTO LeaderTraits(LeaderType, TraitType) 	   
SELECT 'LEADER_JOHN_CURTIN', 'TRAIT_LEADER_SCIENCE_MAJOR_CIV' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_DIGGER');

-- INSERT OR REPLACE INTO LeaderTraits(LeaderType, TraitType) 	   
-- SELECT 'LEADER_MONTEZUMA', 'TRAIT_LEADER_AGGRESSIVE_MILITARY' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_AZTEC_EAGLE_WARRIOR');

--V229 空军偏好
UPDATE PseudoYields SET DefaultValue=10 WHERE PseudoYieldType="PSEUDOYIELD_UNIT_AIR_COMBAT"; --DefaultValue=2

--V229 产出偏好
UPDATE AiFavoredItems SET Value = 20 WHERE ListType="DefaultYieldBias" AND Item="YIELD_PRODUCTION";--was 25
UPDATE AiFavoredItems SET Value = 15 WHERE ListType="DefaultYieldBias" AND Item="YIELD_SCIENCE";--was 10
UPDATE AiFavoredItems SET Value = 15 WHERE ListType="DefaultYieldBias" AND Item="YIELD_CULTURE";--was 10
UPDATE AiFavoredItems SET Value = 25 WHERE ListType="DefaultYieldBias" AND Item="YIELD_GOLD";--was 20
UPDATE AiFavoredItems SET Value = 10 WHERE ListType="DefaultYieldBias" AND Item="YIELD_FAITH";--was -25

--V229 飞天项目偏好
INSERT OR REPLACE INTO AiListTypes
(ListType)  VALUES 
('GOLDEN_PROJECT_LAUNCH_EARTH_SATELLITE'), 
('GOLDEN_PROJECT_LAUNCH_MOON_LANDING'), 
('GOLDEN_PROJECT_LAUNCH_MARS_BASE'), 
('GOLDEN_PROJECT_LAUNCH_EXOPLANET_EXPEDITION');

INSERT OR REPLACE INTO AiFavoredItems
(ListType, Item, Favored)  VALUES 
('GOLDEN_PROJECT_LAUNCH_EARTH_SATELLITE',           'PROJECT_LAUNCH_EARTH_SATELLITE', 		1), 
('GOLDEN_PROJECT_LAUNCH_MOON_LANDING',             	'PROJECT_LAUNCH_MOON_LANDING', 			1), 
('GOLDEN_PROJECT_LAUNCH_MARS_BASE',        			'PROJECT_LAUNCH_MARS_BASE', 			1), 
('GOLDEN_PROJECT_LAUNCH_EXOPLANET_EXPEDITION',      'PROJECT_LAUNCH_EXOPLANET_EXPEDITION', 	1);

INSERT OR REPLACE INTO AiLists
(ListType, LeaderType, System)  VALUES 
('GOLDEN_PROJECT_LAUNCH_EARTH_SATELLITE',              	'TRAIT_LEADER_MAJOR_CIV', 'Projects'),
('GOLDEN_PROJECT_LAUNCH_MOON_LANDING',             		'TRAIT_LEADER_MAJOR_CIV', 'Projects'),
('GOLDEN_PROJECT_LAUNCH_MARS_BASE',        				'TRAIT_LEADER_MAJOR_CIV', 'Projects'),
('GOLDEN_PROJECT_LAUNCH_EXOPLANET_EXPEDITION',          'TRAIT_LEADER_MAJOR_CIV', 'Projects');

--V229 世界奇观偏好
DELETE FROM AiListTypes 	WHERE ListType LIKE '%Wonders';
DELETE FROM AiFavoredItems 	WHERE ListType LIKE '%Wonders';
DELETE FROM AiLists 		WHERE ListType LIKE '%Wonders';

INSERT OR REPLACE INTO AiListTypes (ListType) SELECT	 
'GOLDEN_AI_LIKE_WORLD_WONDER_' || BuildingType 
FROM Buildings WHERE IsWonder = 1;

INSERT OR REPLACE INTO AiFavoredItems (ListType, Item, Favored)  SELECT 
'GOLDEN_AI_LIKE_WORLD_WONDER_' || BuildingType, BuildingType, 1
FROM Buildings WHERE IsWonder = 1;

INSERT OR REPLACE INTO AiLists (ListType, LeaderType, System) SELECT
'GOLDEN_AI_LIKE_WORLD_WONDER_' || BuildingType, 'TRAIT_LEADER_MAJOR_CIV', 'Buildings'
FROM Buildings WHERE IsWonder = 1;