-- GA2_Fix
-- Author: Flactine
-- DateCreated: 9/5/2022 18:47:44 AM
--------------------------------------------------------------
-------
--修复结社建筑无法触发判定的Bug
-------
UPDATE RequirementSetRequirements
SET RequirementId = 'GOLDEN_REQUIRES_CITY_HAS_BUILDING_MONUMENT_SOCIETY_FIX'
WHERE RequirementId = 'GOLDEN_REQUIRES_CITY_HAS_BUILDING_MONUMENT' AND (RequirementSetId != 'GA_REQSET_CITY_HAS_BUILDING_MONUMENT_SOCIETY_FIX');

UPDATE RequirementSetRequirements
SET RequirementId = 'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_MONUMENT_SOCIETY_FIX'
WHERE RequirementId = 'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_MONUMENT' AND (RequirementSetId != 'GA_REQSET_PLAYER_HAS_BUILDING_MONUMENT_SOCIETY_FIX');

UPDATE RequirementSetRequirements
SET RequirementId = 'GOLDEN_REQUIRES_CITY_HAS_BUILDING_UNIVERSITY_SOCIETY_FIX'
WHERE RequirementId = 'GOLDEN_REQUIRES_CITY_HAS_BUILDING_UNIVERSITY' AND (RequirementSetId != 'GA_REQSET_CITY_HAS_BUILDING_UNIVERSITY_SOCIETY_FIX');

UPDATE RequirementSetRequirements
SET RequirementId = 'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_UNIVERSITY_SOCIETY_FIX'
WHERE RequirementId = 'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_UNIVERSITY' AND (RequirementSetId != 'GA_REQSET_PLAYER_HAS_BUILDING_UNIVERSITY_SOCIETY_FIX');

UPDATE RequirementSetRequirements
SET RequirementId = 'GOLDEN_REQUIRES_CITY_HAS_BUILDING_BANK_SOCIETY_FIX'
WHERE RequirementId = 'GOLDEN_REQUIRES_CITY_HAS_BUILDING_BANK' AND (RequirementSetId != 'GA_REQSET_CITY_HAS_BUILDING_BANK_SOCIETY_FIX');

UPDATE RequirementSetRequirements
SET RequirementId = 'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_BANK_SOCIETY_FIX'
WHERE RequirementId = 'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_BANK' AND (RequirementSetId != 'GA_REQSET_PLAYER_HAS_BUILDING_BANK_SOCIETY_FIX');


INSERT OR REPLACE INTO Requirements 	
(RequirementId,     												RequirementType) 
VALUES
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_MONUMENT_SOCIETY_FIX' ,			'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_MONUMENT_SOCIETY_FIX' ,		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_UNIVERSITY_SOCIETY_FIX' ,		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_UNIVERSITY_SOCIETY_FIX' ,		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_BANK_SOCIETY_FIX' ,				'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_BANK_SOCIETY_FIX' ,			'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT OR REPLACE INTO RequirementArguments 	
(RequirementId,     											Name,					Value) 			
VALUES
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_MONUMENT_SOCIETY_FIX' ,		'RequirementSetId',		'GA_REQSET_CITY_HAS_BUILDING_MONUMENT_SOCIETY_FIX'),
('GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_MONUMENT_SOCIETY_FIX' ,	'RequirementSetId',		'GA_REQSET_PLAYER_HAS_BUILDING_MONUMENT_SOCIETY_FIX'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_UNIVERSITY_SOCIETY_FIX' ,	'RequirementSetId',		'GA_REQSET_CITY_HAS_BUILDING_UNIVERSITY_SOCIETY_FIX'),
('GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_UNIVERSITY_SOCIETY_FIX' ,	'RequirementSetId',		'GA_REQSET_PLAYER_HAS_BUILDING_UNIVERSITY_SOCIETY_FIX'),
('GOLDEN_REQUIRES_CITY_HAS_BUILDING_BANK_SOCIETY_FIX' ,			'RequirementSetId',		'GA_REQSET_CITY_HAS_BUILDING_BANK_SOCIETY_FIX'),
('GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_BANK_SOCIETY_FIX' ,		'RequirementSetId',		'GA_REQSET_PLAYER_HAS_BUILDING_BANK_SOCIETY_FIX');

INSERT OR REPLACE INTO RequirementSets 	
(RequirementSetId,     										RequirementSetType) 			
VALUES
('GA_REQSET_CITY_HAS_BUILDING_MONUMENT_SOCIETY_FIX' ,		'REQUIREMENTSET_TEST_ANY'),
('GA_REQSET_PLAYER_HAS_BUILDING_MONUMENT_SOCIETY_FIX' ,		'REQUIREMENTSET_TEST_ANY'),
('GA_REQSET_CITY_HAS_BUILDING_UNIVERSITY_SOCIETY_FIX' ,		'REQUIREMENTSET_TEST_ANY'),
('GA_REQSET_PLAYER_HAS_BUILDING_UNIVERSITY_SOCIETY_FIX' ,	'REQUIREMENTSET_TEST_ANY'),
('GA_REQSET_CITY_HAS_BUILDING_BANK_SOCIETY_FIX' ,			'REQUIREMENTSET_TEST_ANY'),
('GA_REQSET_PLAYER_HAS_BUILDING_BANK_SOCIETY_FIX' ,			'REQUIREMENTSET_TEST_ANY');

INSERT OR REPLACE INTO RequirementSetRequirements 	
(RequirementSetId,     									RequirementId) 			
SELECT 	
'GA_REQSET_CITY_HAS_BUILDING_MONUMENT_SOCIETY_FIX' ,	RequirementId
FROM Requirements WHERE RequirementId = 'GOLDEN_REQUIRES_CITY_HAS_BUILDING_MONUMENT' OR RequirementId = 'GOLDEN_REQUIRES_CITY_HAS_BUILDING_OLD_GOD_OBELISK';

INSERT OR REPLACE INTO RequirementSetRequirements 	
(RequirementSetId,     									RequirementId) 			
SELECT 	
'GA_REQSET_PLAYER_HAS_BUILDING_MONUMENT_SOCIETY_FIX' ,	RequirementId
FROM Requirements WHERE RequirementId = 'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_MONUMENT' OR RequirementId = 'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_OLD_GOD_OBELISK';

INSERT OR REPLACE INTO RequirementSetRequirements 	
(RequirementSetId,     									RequirementId) 			
SELECT 	
'GA_REQSET_CITY_HAS_BUILDING_UNIVERSITY_SOCIETY_FIX' ,	RequirementId
FROM Requirements WHERE RequirementId = 'GOLDEN_REQUIRES_CITY_HAS_BUILDING_UNIVERSITY' OR RequirementId = 'GOLDEN_REQUIRES_CITY_HAS_BUILDING_ALCHEMICAL_SOCIETY';

INSERT OR REPLACE INTO RequirementSetRequirements 	
(RequirementSetId,     										RequirementId) 			
SELECT 	
'GA_REQSET_PLAYER_HAS_BUILDING_UNIVERSITY_SOCIETY_FIX' ,	RequirementId
FROM Requirements WHERE RequirementId = 'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_UNIVERSITY' OR RequirementId = 'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_ALCHEMICAL_SOCIETY';

INSERT OR REPLACE INTO RequirementSetRequirements 	
(RequirementSetId,     								RequirementId) 			
SELECT 	
'GA_REQSET_CITY_HAS_BUILDING_BANK_SOCIETY_FIX' ,	RequirementId
FROM Requirements WHERE RequirementId = 'GOLDEN_REQUIRES_CITY_HAS_BUILDING_BANK' OR RequirementId = 'GOLDEN_REQUIRES_CITY_HAS_BUILDING_GILDED_VAULT';

INSERT OR REPLACE INTO RequirementSetRequirements 	
(RequirementSetId,     								RequirementId) 			
SELECT 	
'GA_REQSET_PLAYER_HAS_BUILDING_BANK_SOCIETY_FIX' ,	RequirementId
FROM Requirements WHERE RequirementId = 'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_BANK' OR RequirementId = 'GOLDEN_REQUIRES_PLAYER_HAS_BUILDING_GILDED_VAULT';