---------------------------------------------------------------------------------------------------------------
-- Improvement_Adjacencies
---------------------------------------------------------------------------------------------------------------
DELETE FROM Improvement_Adjacencies WHERE ImprovementType = 'IMPROVEMENT_MINE' AND YieldChangeId = 'Mine_ScienceSeowonAdjacency';
DELETE FROM Improvement_Adjacencies WHERE ImprovementType = 'IMPROVEMENT_FARM' AND YieldChangeId = 'Farm_FoodSeowonAdjacency';
---------------------------------------------------------------------------------------------------------------
-- District_CitizenYieldChanges
---------------------------------------------------------------------------------------------------------------
UPDATE District_CitizenYieldChanges SET YieldChange = 5
WHERE DistrictType = 'DISTRICT_SEOWON' AND YieldType = 'YIELD_SCIENCE';
-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_CIVILIZATION_THREE_KINGDOMS',	'GOLDEN_TRAIT_FISHING_BOATS_ADJACENT_FISHING_BOATS_FOOD'),
('TRAIT_CIVILIZATION_THREE_KINGDOMS',	'GOLDEN_TRAIT_FARM_ADJACENT_FARM_FOOD'),
('TRAIT_CIVILIZATION_THREE_KINGDOMS',	'GOLDEN_TRAIT_PASTURE_ADJACENT_PASTURE_FOOD'),
('TRAIT_CIVILIZATION_THREE_KINGDOMS',	'GOLDEN_TRAIT_FISHERY_ADJACENT_FISHERY_GOLD'),
('TRAIT_CIVILIZATION_THREE_KINGDOMS',	'GOLDEN_TRAIT_CAMP_ADJACENT_CAMP_GOLD'),
('TRAIT_CIVILIZATION_THREE_KINGDOMS',	'GOLDEN_TRAIT_PLANTATION_ADJACENT_PLANTATION_GOLD'),
('TRAIT_CIVILIZATION_THREE_KINGDOMS',	'GOLDEN_TRAIT_QUARRY_ADJACENT_QUARRY_PRODUCTION'),
('TRAIT_CIVILIZATION_THREE_KINGDOMS',	'GOLDEN_TRAIT_MINE_ADJACENT_MINE_PRODUCTION'),
('TRAIT_CIVILIZATION_THREE_KINGDOMS',	'GOLDEN_TRAIT_LUMBERMILL_ADJACENT_LUMBERMILL_PRODUCTION'),

('TRAIT_LEADER_HWARANG',	'GA_HWARANG_SCIENCE_BUILDINGS'),
('TRAIT_LEADER_HWARANG',	'GOLDEN_TRAIT_ADJUST_CITY_PRODUCTION_PER_GOVERNOR_TITLE_MODIFIER'),
('TRAIT_LEADER_HWARANG',	'GOLDEN_TRAIT_ADJUST_CITY_GOLD_PER_GOVERNOR_TITLE_MODIFIER'),
('TRAIT_LEADER_HWARANG',	'GOLDEN_TRAIT_ADJUST_CITY_FAITH_PER_GOVERNOR_TITLE_MODIFIER');
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'TRAIT_LEADER_HWARANG',	'GOLDEN_TRAIT_CITY_WITHOUT_GOVERNOR_DEBUFF' || YieldType FROM	Yields WHERE YieldType <>'YIELD_FOOD';	
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'TRAIT_LEADER_HWARANG',	'GOLDEN_HWARANG_GOVERNOR_' || EraType FROM Eras WHERE EraType <> 'ERA_ANCIENT';	

-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId,						            ModifierType,								                                    SubjectRequirementSetId) VALUES	
('GOLDEN_TRAIT_FISHING_BOATS_ADJACENT_FISHING_BOATS_FOOD',			    'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		                                    'GOLDEN_KOREA_PLOT_HAS_FISHING_BOATS_ADJACENT_FISHING_BOATS_REQUIREMENTS'),
('GOLDEN_TRAIT_FARM_ADJACENT_FARM_FOOD',			                	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		                                    'GOLDEN_KOREA_PLOT_HAS_FARM_ADJACENT_FARM_REQUIREMENTS'),
('GOLDEN_TRAIT_PASTURE_ADJACENT_PASTURE_FOOD',			                'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		                                    'GOLDEN_KOREA_PLOT_HAS_PASTURE_ADJACENT_PASTURE_REQUIREMENTS'),
('GOLDEN_TRAIT_FISHERY_ADJACENT_FISHERY_GOLD',			                'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		                                    'GOLDEN_KOREA_PLOT_HAS_FISHERY_ADJACENT_FISHERY_REQUIREMENTS'),
('GOLDEN_TRAIT_CAMP_ADJACENT_CAMP_GOLD',			                	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		                                    'GOLDEN_KOREA_PLOT_HAS_CAMP_ADJACENT_CAMP_REQUIREMENTS'),
('GOLDEN_TRAIT_PLANTATION_ADJACENT_PLANTATION_GOLD',			        'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		                                    'GOLDEN_KOREA_PLOT_HAS_PLANTATION_ADJACENT_PLANTATION_REQUIREMENTS'),
('GOLDEN_TRAIT_QUARRY_ADJACENT_QUARRY_PRODUCTION',			            'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		                                    'GOLDEN_KOREA_PLOT_HAS_QUARRY_ADJACENT_QUARRY_REQUIREMENTS'),
('GOLDEN_TRAIT_MINE_ADJACENT_MINE_PRODUCTION',			            	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		                                    'GOLDEN_KOREA_PLOT_HAS_MINE_ADJACENT_MINE_REQUIREMENTS'),
('GOLDEN_TRAIT_LUMBERMILL_ADJACENT_LUMBERMILL_PRODUCTION',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		                                    'GOLDEN_KOREA_PLOT_HAS_LUMBERMILL_ADJACENT_LUMBERMILL_REQUIREMENTS'),

('GA_HWARANG_SCIENCE_BUILDINGS' , 													'MODIFIER_PLAYER_CITIES_GRANT_YIELD_PER_BUILDING_COST' , 														NULL),
('GOLDEN_TRAIT_ADJUST_CITY_PRODUCTION_PER_GOVERNOR_TITLE_MODIFIER',			        'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER_PER_GOVERNOR_TITLE',		                                    NULL),
('GOLDEN_TRAIT_ADJUST_CITY_GOLD_PER_GOVERNOR_TITLE_MODIFIER',			            'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER_PER_GOVERNOR_TITLE',		                                    NULL),
('GOLDEN_TRAIT_ADJUST_CITY_FAITH_PER_GOVERNOR_TITLE_MODIFIER',			            'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER_PER_GOVERNOR_TITLE',		                                    NULL);
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_CITY_WITHOUT_GOVERNOR_DEBUFF' || YieldType,	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'CITY_HAS_NO_GOVERNOR_REQUIREMENTS' FROM Yields WHERE YieldType <>'YIELD_FOOD';	
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'GOLDEN_HWARANG_GOVERNOR_' || EraType,	'MODIFIER_PLAYER_ADJUST_GOVERNOR_POINTS', 'GOLDEN_GAME_ERA_IS_'|| EraType ||'_REQUIREMENTS' FROM Eras WHERE EraType <> 'ERA_ANCIENT';	
-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_TRAIT_FISHING_BOATS_ADJACENT_FISHING_BOATS_FOOD',				'YieldType',	    'YIELD_FOOD'),
('GOLDEN_TRAIT_FISHING_BOATS_ADJACENT_FISHING_BOATS_FOOD',				'Amount',	        1),
('GOLDEN_TRAIT_FARM_ADJACENT_FARM_FOOD',					            'YieldType',	    'YIELD_FOOD'),
('GOLDEN_TRAIT_FARM_ADJACENT_FARM_FOOD',					            'Amount',	        1),
('GOLDEN_TRAIT_PASTURE_ADJACENT_PASTURE_FOOD',					        'YieldType',	    'YIELD_FOOD'),
('GOLDEN_TRAIT_PASTURE_ADJACENT_PASTURE_FOOD',					        'Amount',	        1),
('GOLDEN_TRAIT_FISHERY_ADJACENT_FISHERY_GOLD',					        'YieldType',	    'YIELD_GOLD'),
('GOLDEN_TRAIT_FISHERY_ADJACENT_FISHERY_GOLD',					        'Amount',	        1),
('GOLDEN_TRAIT_CAMP_ADJACENT_CAMP_GOLD',					            'YieldType',	    'YIELD_GOLD'),
('GOLDEN_TRAIT_CAMP_ADJACENT_CAMP_GOLD',					            'Amount',	        1),
('GOLDEN_TRAIT_PLANTATION_ADJACENT_PLANTATION_GOLD',					'YieldType',	    'YIELD_GOLD'),
('GOLDEN_TRAIT_PLANTATION_ADJACENT_PLANTATION_GOLD',					'Amount',	        1),
('GOLDEN_TRAIT_QUARRY_ADJACENT_QUARRY_PRODUCTION',					    'YieldType',	    'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_QUARRY_ADJACENT_QUARRY_PRODUCTION',					    'Amount',	        1),
('GOLDEN_TRAIT_MINE_ADJACENT_MINE_PRODUCTION',					        'YieldType',	    'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_MINE_ADJACENT_MINE_PRODUCTION',					        'Amount',	        1),
('GOLDEN_TRAIT_LUMBERMILL_ADJACENT_LUMBERMILL_PRODUCTION',		        'YieldType',	    'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_LUMBERMILL_ADJACENT_LUMBERMILL_PRODUCTION',		        'Amount',	        1),

('GA_HWARANG_SCIENCE_BUILDINGS', 			'YieldType', 					'YIELD_SCIENCE'),
('GA_HWARANG_SCIENCE_BUILDINGS', 			'BuildingProductionPercent', 	20), 
('GA_HWARANG_SCIENCE_BUILDINGS', 			'IncludeWonder', 				1), 
('GOLDEN_TRAIT_ADJUST_CITY_PRODUCTION_PER_GOVERNOR_TITLE_MODIFIER',		'YieldType',	    'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_ADJUST_CITY_PRODUCTION_PER_GOVERNOR_TITLE_MODIFIER',		'Amount',	        5),
('GOLDEN_TRAIT_ADJUST_CITY_GOLD_PER_GOVERNOR_TITLE_MODIFIER',			'YieldType',	    'YIELD_GOLD'),
('GOLDEN_TRAIT_ADJUST_CITY_GOLD_PER_GOVERNOR_TITLE_MODIFIER',			'Amount',	        5),
('GOLDEN_TRAIT_ADJUST_CITY_FAITH_PER_GOVERNOR_TITLE_MODIFIER',		    'YieldType',	    'YIELD_FAITH'),
('GOLDEN_TRAIT_ADJUST_CITY_FAITH_PER_GOVERNOR_TITLE_MODIFIER',		    'Amount',	        5);
UPDATE ModifierArguments SET  Value = 5
WHERE ModifierId = 'TRAIT_ADJUST_CITY_CULTURE_PER_GOVERNOR_TITLE_MODIFIER' AND Name = 'Amount';
UPDATE ModifierArguments SET  Value = 5
WHERE ModifierId = 'TRAIT_ADJUST_CITY_SCIENCE_PER_GOVERNOR_TITLE_MODIFIER' AND Name = 'Amount';
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_CITY_WITHOUT_GOVERNOR_DEBUFF' || YieldType,	'YieldType', YieldType FROM	Yields WHERE YieldType <>'YIELD_FOOD';	
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_CITY_WITHOUT_GOVERNOR_DEBUFF' || YieldType,	'Amount', -10 FROM Yields WHERE YieldType <>'YIELD_FOOD';
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_HWARANG_GOVERNOR_' || EraType,	'Delta', 1 FROM	Eras WHERE EraType <> 'ERA_ANCIENT';	
---------------------------------------------------------------------------------------------------------------
-- RequirementSets
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSets 				(RequirementSetId ,         RequirementSetType) 	VALUES 	
('GOLDEN_KOREA_PLOT_HAS_FISHING_BOATS_ADJACENT_FISHING_BOATS_REQUIREMENTS' , 		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_KOREA_PLOT_HAS_FARM_ADJACENT_FARM_REQUIREMENTS' , 		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_KOREA_PLOT_HAS_PASTURE_ADJACENT_PASTURE_REQUIREMENTS' , 		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_KOREA_PLOT_HAS_FISHERY_ADJACENT_FISHERY_REQUIREMENTS' , 		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_KOREA_PLOT_HAS_CAMP_ADJACENT_CAMP_REQUIREMENTS' , 		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_KOREA_PLOT_HAS_PLANTATION_ADJACENT_PLANTATION_REQUIREMENTS' , 		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_KOREA_PLOT_HAS_QUARRY_ADJACENT_QUARRY_REQUIREMENTS' , 		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_KOREA_PLOT_HAS_MINE_ADJACENT_MINE_REQUIREMENTS' , 		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_KOREA_PLOT_HAS_LUMBERMILL_ADJACENT_LUMBERMILL_REQUIREMENTS' , 		'REQUIREMENTSET_TEST_ALL');
---------------------------------------------------------------------------------------------------------------
-- RequirementSetRequirements
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,         RequirementId) 			VALUES 	
('GOLDEN_KOREA_PLOT_HAS_FISHING_BOATS_ADJACENT_FISHING_BOATS_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_FISHING_BOATS'),
('GOLDEN_KOREA_PLOT_HAS_FISHING_BOATS_ADJACENT_FISHING_BOATS_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_FISHING_BOATS'),
('GOLDEN_KOREA_PLOT_HAS_FARM_ADJACENT_FARM_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_FARM'),
('GOLDEN_KOREA_PLOT_HAS_FARM_ADJACENT_FARM_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_FARM'),
('GOLDEN_KOREA_PLOT_HAS_PASTURE_ADJACENT_PASTURE_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_PASTURE'),
('GOLDEN_KOREA_PLOT_HAS_PASTURE_ADJACENT_PASTURE_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_PASTURE'),
('GOLDEN_KOREA_PLOT_HAS_FISHERY_ADJACENT_FISHERY_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_FISHERY'),
('GOLDEN_KOREA_PLOT_HAS_FISHERY_ADJACENT_FISHERY_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_FISHERY'),
('GOLDEN_KOREA_PLOT_HAS_CAMP_ADJACENT_CAMP_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_CAMP'),
('GOLDEN_KOREA_PLOT_HAS_CAMP_ADJACENT_CAMP_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_CAMP'),
('GOLDEN_KOREA_PLOT_HAS_PLANTATION_ADJACENT_PLANTATION_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_PLANTATION'),
('GOLDEN_KOREA_PLOT_HAS_PLANTATION_ADJACENT_PLANTATION_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_PLANTATION'),
('GOLDEN_KOREA_PLOT_HAS_QUARRY_ADJACENT_QUARRY_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_QUARRY'),
('GOLDEN_KOREA_PLOT_HAS_QUARRY_ADJACENT_QUARRY_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_QUARRY'),
('GOLDEN_KOREA_PLOT_HAS_MINE_ADJACENT_MINE_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_MINE'),
('GOLDEN_KOREA_PLOT_HAS_MINE_ADJACENT_MINE_REQUIREMENTS' , 		            'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_MINE'),
('GOLDEN_KOREA_PLOT_HAS_LUMBERMILL_ADJACENT_LUMBERMILL_REQUIREMENTS' , 		'GOLDEN_REQUIRES_PLOT_HAS_IMPROVEMENT_LUMBER_MILL'),
('GOLDEN_KOREA_PLOT_HAS_LUMBERMILL_ADJACENT_LUMBERMILL_REQUIREMENTS' , 		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_LUMBER_MILL');