-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_MELEE_COASTAL_RAIDS' AND ModifierId = 'TRAIT_ANCIENT_NAVAL_MELEE_PRODUCTION';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_MELEE_COASTAL_RAIDS' AND ModifierId = 'TRAIT_CLASSICAL_NAVAL_MELEE_PRODUCTION';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_MELEE_COASTAL_RAIDS' AND ModifierId = 'TRAIT_MEDIEVAL_NAVAL_MELEE_PRODUCTION';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_MELEE_COASTAL_RAIDS' AND ModifierId = 'TRAIT_RENAISSANCE_NAVAL_MELEE_PRODUCTION';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_MELEE_COASTAL_RAIDS' AND ModifierId = 'TRAIT_INDUSTRIAL_NAVAL_MELEE_PRODUCTION';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_MELEE_COASTAL_RAIDS' AND ModifierId = 'TRAIT_MODERN_NAVAL_MELEE_PRODUCTION';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_MELEE_COASTAL_RAIDS' AND ModifierId = 'TRAIT_ATOMIC_NAVAL_MELEE_PRODUCTION';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_MELEE_COASTAL_RAIDS' AND ModifierId = 'TRAIT_INFORMATION_NAVAL_MELEE_PRODUCTION';

INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_CIVILIZATION_EARLY_OCEAN_NAVIGATION',	        'GOLDEN_COASTAL_CITY_FREE_NAVAL_MELEE'),
('TRAIT_LEADER_MELEE_COASTAL_RAIDS',	                'GOLDEN_TRAIT_PLUNDER_BONUS'),
('TRAIT_LEADER_MELEE_COASTAL_RAIDS',	                'GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_MINES'),
('TRAIT_LEADER_MELEE_COASTAL_RAIDS',	                'GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_QUARRIES'),
('TRAIT_LEADER_MELEE_COASTAL_RAIDS',	                'GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_PLANTATIONS'),
('TRAIT_LEADER_MELEE_COASTAL_RAIDS',	                'GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_PASTURES'),
('TRAIT_LEADER_MELEE_COASTAL_RAIDS',	                'GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_CAMPS'),
('TRAIT_LEADER_MELEE_COASTAL_RAIDS',	                'GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_LUMBERMILL'),
('TRAIT_LEADER_MELEE_COASTAL_RAIDS',	                'GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_LUMBERMILL'),
('TRAIT_LEADER_MELEE_COASTAL_RAIDS',	                'GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_FISHING_BOATS'),
('TRAIT_LEADER_MELEE_COASTAL_RAIDS',	                'GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_FISHING_BOATS');
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
('GOLDEN_COASTAL_CITY_FREE_NAVAL_MELEE',             'MODIFIER_PLAYER_CITIES_GRANT_UNIT_BY_CLASS',                    0, 0, 'GOLDEN_PLOT_ADJACENT_TO_COAST_REQUIREMENTS'),
('GOLDEN_TRAIT_PLUNDER_BONUS',                       'MODIFIER_PLAYER_UNITS_ADJUST_PLUNDER_YIELDS',                   0, 0, NULL),
('GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_MINES',                       'MODIFIER_PLAYER_ADJUST_ADDITIONAL_PILLAGING',                   0, 0, NULL),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_QUARRIES',                    'MODIFIER_PLAYER_ADJUST_ADDITIONAL_PILLAGING',                   0, 0, NULL),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_PLANTATIONS',                 'MODIFIER_PLAYER_ADJUST_ADDITIONAL_PILLAGING',                   0, 0, NULL),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_PASTURES',                    'MODIFIER_PLAYER_ADJUST_ADDITIONAL_PILLAGING',                   0, 0, NULL),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_CAMPS',                       'MODIFIER_PLAYER_ADJUST_ADDITIONAL_PILLAGING',                   0, 0, NULL),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_LUMBERMILL',                  'MODIFIER_PLAYER_ADJUST_ADDITIONAL_PILLAGING',                   0, 0, NULL),
('GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_LUMBERMILL',                  'MODIFIER_PLAYER_ADJUST_ADDITIONAL_PILLAGING',                   0, 0, NULL),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_FISHING_BOATS',               'MODIFIER_PLAYER_ADJUST_ADDITIONAL_PILLAGING',                   0, 0, NULL),
('GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_FISHING_BOATS',               'MODIFIER_PLAYER_ADJUST_ADDITIONAL_PILLAGING',                   0, 0, NULL);
-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			                Name,		                        Value) VALUES
('GOLDEN_COASTAL_CITY_FREE_NAVAL_MELEE',			                'UnitPromotionClassType',	        'PROMOTION_CLASS_NAVAL_MELEE'),
('GOLDEN_TRAIT_PLUNDER_BONUS',			                            'Amount',	                        100),
('GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_MINES',			            'PlunderType',	                    'PLUNDER_CULTURE'),
('GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_MINES',			            'ImprovementType',	                'IMPROVEMENT_MINE'),
('GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_MINES',			            'Amount',	                        15),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_QUARRIES',			        'PlunderType',	                    'PLUNDER_SCIENCE'),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_QUARRIES',			        'ImprovementType',	                'IMPROVEMENT_QUARRY'),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_QUARRIES',			        'Amount',	                        15),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_PLANTATIONS',			        'PlunderType',	                    'PLUNDER_SCIENCE'),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_PLANTATIONS',			        'ImprovementType',	                'IMPROVEMENT_PLANTATION'),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_PLANTATIONS',			        'Amount',	                        15),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_PASTURES',			        'PlunderType',	                    'PLUNDER_SCIENCE'),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_PASTURES',			        'ImprovementType',	                'IMPROVEMENT_PASTURE'),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_PASTURES',			        'Amount',	                        15),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_CAMPS',			            'PlunderType',	                    'PLUNDER_SCIENCE'),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_CAMPS',			            'ImprovementType',	                'IMPROVEMENT_CAMP'),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_CAMPS',			            'Amount',	                        15),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_LUMBERMILL',			        'PlunderType',	                    'PLUNDER_SCIENCE'),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_LUMBERMILL',			        'ImprovementType',	                'IMPROVEMENT_LUMBER_MILL'),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_LUMBERMILL',			        'Amount',	                        15),
('GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_LUMBERMILL',			        'PlunderType',	                    'PLUNDER_CULTURE'),
('GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_LUMBERMILL',			        'ImprovementType',	                'IMPROVEMENT_LUMBER_MILL'),
('GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_LUMBERMILL',			        'Amount',	                        15),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_FISHING_BOATS',			    'PlunderType',	                    'PLUNDER_SCIENCE'),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_FISHING_BOATS',			    'ImprovementType',	                'IMPROVEMENT_FISHING_BOATS'),
('GOLDEN_TRAIT_LEADER_PILLAGE_SCIENCE_FISHING_BOATS',			    'Amount',	                        15),
('GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_FISHING_BOATS',			    'PlunderType',	                    'PLUNDER_CULTURE'),
('GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_FISHING_BOATS',			    'ImprovementType',	                'IMPROVEMENT_FISHING_BOATS'),
('GOLDEN_TRAIT_LEADER_PILLAGE_CULTURE_FISHING_BOATS',			    'Amount',	                        15);