-----------------------------------------------
-- ExcludedAdjacencies
-----------------------------------------------
INSERT OR REPLACE INTO ExcludedAdjacencies (YieldChangeId, 			TraitType) VALUES	
('District_Science',	    'TRAIT_CIVILIZATION_AMAZON'),
('District_Faith',	        'TRAIT_CIVILIZATION_AMAZON'),
('District_Gold',	        'TRAIT_CIVILIZATION_AMAZON'),
('District_Culture',	    'TRAIT_CIVILIZATION_AMAZON'),
('District_Production',	    'TRAIT_CIVILIZATION_AMAZON'),
('DISTRICT_FOOD',	        'TRAIT_CIVILIZATION_AMAZON'),
('CITY_CENTER_CULTURE',	    'TRAIT_CIVILIZATION_AMAZON'),
('CITY_CENTER_FAITH',	    'TRAIT_CIVILIZATION_AMAZON'),
('CITY_CENTER_GOLD',	    'TRAIT_CIVILIZATION_AMAZON'),
('CITY_CENTER_PRODUCTION',	'TRAIT_CIVILIZATION_AMAZON'),
('CITY_CENTER_SCIENCE',	    'TRAIT_CIVILIZATION_AMAZON'),
('CITY_CENTER_FOOD',	    'TRAIT_CIVILIZATION_AMAZON');

--------------------------------------------------
-- TraitModifiers
--------------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType,						ModifierId) VALUES	
('TRAIT_CIVILIZATION_AMAZON',	'GOLDEN_TRAIT_AMAZON_INDUSTRIAL_ZONE_ADJACENCYPRODUCTION'),
('TRAIT_CIVILIZATION_AMAZON',	'GOLDEN_TRAIT_AMAZON_HARBOR_ADJACENCYGOLD'),
('TRAIT_CIVILIZATION_AMAZON',	'GOLDEN_TRAIT_AMAZON_FOOD'),
('TRAIT_CIVILIZATION_AMAZON',	'GOLDEN_TRAIT_AMAZON_CULTURE');
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)VALUES
('TRAIT_LEADER_MAGNANIMOUS', 'GOLDEN_MAGNANIMOUS_GREATPERSON_TILE'),
('TRAIT_LEADER_MAGNANIMOUS', 'GOLDEN_MAGNANIMOUS_GREAT_WORK_SCULPTURE_GOLD'),
('TRAIT_LEADER_MAGNANIMOUS', 'GOLDEN_MAGNANIMOUS_GREAT_WORK_SCULPTURE_FAITH'),
('TRAIT_LEADER_MAGNANIMOUS', 'GOLDEN_MAGNANIMOUS_GREAT_WORK_PORTRAIT_GOLD'),
('TRAIT_LEADER_MAGNANIMOUS', 'GOLDEN_MAGNANIMOUS_GREAT_WORK_PORTRAIT_FAITH'),
('TRAIT_LEADER_MAGNANIMOUS', 'GOLDEN_MAGNANIMOUS_GREAT_WORK_LANDSCAPE_GOLD'),
('TRAIT_LEADER_MAGNANIMOUS', 'GOLDEN_MAGNANIMOUS_GREAT_WORK_LANDSCAPE_FAITH'),
('TRAIT_LEADER_MAGNANIMOUS', 'GOLDEN_MAGNANIMOUS_GREAT_WORK_RELIGIOUS_GOLD'),
('TRAIT_LEADER_MAGNANIMOUS', 'GOLDEN_MAGNANIMOUS_GREAT_WORK_RELIGIOUS_FAITH'),
('TRAIT_LEADER_MAGNANIMOUS', 'GOLDEN_MAGNANIMOUS_GREAT_WORK_MUSIC_GOLD'),
('TRAIT_LEADER_MAGNANIMOUS', 'GOLDEN_MAGNANIMOUS_GREAT_WORK_MUSIC_FAITH');


---------------------------------------------------------------------------------------------------------------
-- Modifiers
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId,				ModifierType,									RunOnce,	Permanent,	SubjectRequirementSetId) VALUES	
('GOLDEN_TRAIT_AMAZON_HARBOR_ADJACENCYGOLD',					'MODIFIER_PLAYER_CITIES_FEATURE_ADJACENCY',	0,			0,			NULL),
('GOLDEN_TRAIT_AMAZON_INDUSTRIAL_ZONE_ADJACENCYPRODUCTION',		'MODIFIER_PLAYER_CITIES_FEATURE_ADJACENCY',	0,			0,			NULL),
('GOLDEN_TRAIT_AMAZON_FOOD',				    				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		0,			0,			'PLOT_HAS_JUNGLE_NO_IMPROVEMENT_REQUIREMENTS'),
('GOLDEN_TRAIT_AMAZON_CULTURE',				    				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		0,			0,			'PLOT_HAS_JUNGLE_CONSERVATION_REQUIREMENTS');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)VALUES
('GOLDEN_MAGNANIMOUS_GREATPERSON_TILE', 'MODIFIER_PLAYER_CITIES_ADD_EXPENDED_GREAT_PERSON_TILES', 0, 0, NULL),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_SCULPTURE_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', 0, 0, NULL),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_SCULPTURE_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', 0, 0, NULL),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_PORTRAIT_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', 0, 0, NULL),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_PORTRAIT_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', 0, 0, NULL),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_LANDSCAPE_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', 0, 0, NULL),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_LANDSCAPE_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', 0, 0, NULL),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_RELIGIOUS_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', 0, 0, NULL),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_RELIGIOUS_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', 0, 0, NULL),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_MUSIC_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', 0, 0, NULL),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_MUSIC_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', 0, 0, NULL);

---------------------------------------------------------------------------------------------------------------
-- ModifierArguments
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,											Name,			Value) VALUES	
('GOLDEN_MAGNANIMOUS_GREATPERSON_TILE',					'Amount',			2),
('GOLDEN_TRAIT_AMAZON_HARBOR_ADJACENCYGOLD',					'DistrictType',		'DISTRICT_HARBOR'),
('GOLDEN_TRAIT_AMAZON_HARBOR_ADJACENCYGOLD',					'FeatureType',		'FEATURE_JUNGLE'),
('GOLDEN_TRAIT_AMAZON_HARBOR_ADJACENCYGOLD',					'YieldType',		'YIELD_GOLD'),
('GOLDEN_TRAIT_AMAZON_HARBOR_ADJACENCYGOLD',					'Amount',			1),
('GOLDEN_TRAIT_AMAZON_HARBOR_ADJACENCYGOLD',					'Description',		'LOC_DISTRICT_JUNGLE_2_GOLD'),
('GOLDEN_TRAIT_AMAZON_INDUSTRIAL_ZONE_ADJACENCYPRODUCTION',					'DistrictType',		'DISTRICT_INDUSTRIAL_ZONE'),
('GOLDEN_TRAIT_AMAZON_INDUSTRIAL_ZONE_ADJACENCYPRODUCTION',					'FeatureType',		'FEATURE_JUNGLE'),
('GOLDEN_TRAIT_AMAZON_INDUSTRIAL_ZONE_ADJACENCYPRODUCTION',					'YieldType',		'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_AMAZON_INDUSTRIAL_ZONE_ADJACENCYPRODUCTION',					'Amount',			1),
('GOLDEN_TRAIT_AMAZON_INDUSTRIAL_ZONE_ADJACENCYPRODUCTION',					'Description',		'LOC_DISTRICT_JUNGLE_2_PRODUCTION'),
('GOLDEN_TRAIT_AMAZON_FOOD',					'YieldType',		'YIELD_FOOD'),
('GOLDEN_TRAIT_AMAZON_FOOD',					'Amount',			1),
('GOLDEN_TRAIT_AMAZON_CULTURE',					'YieldType',		'YIELD_CULTURE'),
('GOLDEN_TRAIT_AMAZON_CULTURE',					'Amount',			2);

UPDATE ModifierArguments SET  Value = 25
WHERE ModifierId = 'TRAIT_GREAT_PERSON_REFUND' AND Name = 'Tourism';

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)VALUES
('GOLDEN_MAGNANIMOUS_GREAT_WORK_SCULPTURE_GOLD', 'GreatWorkObjectType', 'GREATWORKOBJECT_SCULPTURE'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_SCULPTURE_GOLD', 'YieldChange', 5),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_SCULPTURE_GOLD', 'YieldType', 'YIELD_GOLD'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_SCULPTURE_FAITH', 'GreatWorkObjectType', 'GREATWORKOBJECT_SCULPTURE'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_SCULPTURE_FAITH', 'YieldChange', 5),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_SCULPTURE_FAITH', 'YieldType', 'YIELD_FAITH'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_PORTRAIT_GOLD', 'GreatWorkObjectType', 'GREATWORKOBJECT_PORTRAIT'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_PORTRAIT_GOLD', 'YieldChange', 5),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_PORTRAIT_GOLD', 'YieldType', 'YIELD_GOLD'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_PORTRAIT_FAITH', 'GreatWorkObjectType', 'GREATWORKOBJECT_PORTRAIT'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_PORTRAIT_FAITH', 'YieldChange', 5),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_PORTRAIT_FAITH', 'YieldType', 'YIELD_FAITH'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_LANDSCAPE_GOLD', 'GreatWorkObjectType', 'GREATWORKOBJECT_LANDSCAPE'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_LANDSCAPE_GOLD', 'YieldChange', 5),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_LANDSCAPE_GOLD', 'YieldType', 'YIELD_GOLD'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_LANDSCAPE_FAITH', 'GreatWorkObjectType', 'GREATWORKOBJECT_LANDSCAPE'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_LANDSCAPE_FAITH', 'YieldChange', 5),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_LANDSCAPE_FAITH', 'YieldType', 'YIELD_FAITH'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_RELIGIOUS_GOLD', 'GreatWorkObjectType', 'GREATWORKOBJECT_RELIGIOUS'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_RELIGIOUS_GOLD', 'YieldChange', 5),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_RELIGIOUS_GOLD', 'YieldType', 'YIELD_GOLD'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_RELIGIOUS_FAITH', 'GreatWorkObjectType', 'GREATWORKOBJECT_RELIGIOUS'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_RELIGIOUS_FAITH', 'YieldChange', 5),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_RELIGIOUS_FAITH', 'YieldType', 'YIELD_FAITH'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_MUSIC_GOLD', 'GreatWorkObjectType', 'GREATWORKOBJECT_MUSIC'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_MUSIC_GOLD', 'YieldChange', 5),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_MUSIC_GOLD', 'YieldType', 'YIELD_GOLD'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_MUSIC_FAITH', 'GreatWorkObjectType', 'GREATWORKOBJECT_MUSIC'),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_MUSIC_FAITH', 'YieldChange', 5),
('GOLDEN_MAGNANIMOUS_GREAT_WORK_MUSIC_FAITH', 'YieldType', 'YIELD_FAITH');






-----------------------------------------------
--UD
-----------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_CIVILIZATION_AMAZON',	        'GOLDEN_STREET_CARNIVAL_CITY_CENTER_AMENITY'),
('TRAIT_CIVILIZATION_AMAZON',	        'GOLDEN_STREET_CARNIVAL_GOVERNMENT_AMENITY'),
('TRAIT_CIVILIZATION_AMAZON',	        'GOLDEN_STREET_CARNIVAL_WATER_STREET_CARNIVAL_AMENITY'),
('TRAIT_CIVILIZATION_AMAZON',	        'GOLDEN_WATER_STREET_CARNIVAL_STREET_CARNIVAL_AMENITY'),
('TRAIT_CIVILIZATION_AMAZON',	        'GOLDEN_WATER_STREET_CARNIVAL_CITY_CENTER_AMENITY'),
('TRAIT_CIVILIZATION_AMAZON',	        'GOLDEN_WATER_STREET_CARNIVAL_GOVERNMENT_AMENITY');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
('GOLDEN_STREET_CARNIVAL_CITY_CENTER_AMENITY',                 'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT',   0, 0,  'GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_CITY_CENTER_REQUIREMENTS'),
('GOLDEN_STREET_CARNIVAL_GOVERNMENT_AMENITY',                  'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT',   0, 0,  'GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_GOVERNMENT_REQUIREMENTS'),
('GOLDEN_STREET_CARNIVAL_WATER_STREET_CARNIVAL_AMENITY',       'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT',   0, 0,  'GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_WATER_STREET_CARNIVAL_REQUIREMENTS'),
('GOLDEN_WATER_STREET_CARNIVAL_STREET_CARNIVAL_AMENITY',       'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT',   0, 0,  'GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_STREET_CARNIVAL_REQUIREMENTS'),
('GOLDEN_WATER_STREET_CARNIVAL_CITY_CENTER_AMENITY',           'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT',   0, 0,  'GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_CITY_CENTER_REQUIREMENTS'),
('GOLDEN_WATER_STREET_CARNIVAL_GOVERNMENT_AMENITY',            'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT',   0, 0,  'GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_COMPLEX_ADJACENT_TO_GOVERNMENT_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_STREET_CARNIVAL_CITY_CENTER_AMENITY',				                'Amount',	   1),
('GOLDEN_STREET_CARNIVAL_GOVERNMENT_AMENITY',				                'Amount',	   1),
('GOLDEN_STREET_CARNIVAL_WATER_STREET_CARNIVAL_AMENITY',				    'Amount',	   1),
('GOLDEN_WATER_STREET_CARNIVAL_STREET_CARNIVAL_AMENITY',				    'Amount',	   1),
('GOLDEN_WATER_STREET_CARNIVAL_CITY_CENTER_AMENITY',				        'Amount',	   1),
('GOLDEN_WATER_STREET_CARNIVAL_GOVERNMENT_AMENITY',				            'Amount',	   1);

INSERT OR REPLACE INTO RequirementSets		(RequirementSetId,							RequirementSetType) VALUES
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_CITY_CENTER_REQUIREMENTS',		                    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		                    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_WATER_STREET_CARNIVAL_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_STREET_CARNIVAL_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_CITY_CENTER_REQUIREMENTS',		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_COMPLEX_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		    'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements		(RequirementSetId,							RequirementId) VALUES	
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_CITY_CENTER_REQUIREMENTS',		            'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_STREET_CARNIVAL'),
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_CITY_CENTER_REQUIREMENTS',		            'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_CITY_CENTER'),
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		            'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_STREET_CARNIVAL'),
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		            'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_GOVERNMENT'),
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_WATER_STREET_CARNIVAL_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_STREET_CARNIVAL'),
('GOLDEN_DISTRICT_IS_STREET_CARNIVAL_ADJACENT_TO_WATER_STREET_CARNIVAL_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_WATER_STREET_CARNIVAL'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_STREET_CARNIVAL_REQUIREMENTS',		                'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_WATER_STREET_CARNIVAL'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_STREET_CARNIVAL_REQUIREMENTS',		                'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_STREET_CARNIVAL'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_CITY_CENTER_REQUIREMENTS',		                    'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_WATER_STREET_CARNIVAL'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_ADJACENT_TO_CITY_CENTER_REQUIREMENTS',		                    'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_CITY_CENTER'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_COMPLEX_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		            'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_WATER_STREET_CARNIVAL'),
('GOLDEN_DISTRICT_IS_WATER_STREET_CARNIVAL_COMPLEX_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		            'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_GOVERNMENT');