-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_CIVILIZATION_PLATOS_REPUBLIC',	'GOLDEN_TRAIT_GOVERNOR_GOVERNMENT'),
('TRAIT_CIVILIZATION_PLATOS_REPUBLIC',	'GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER1'),
('TRAIT_CIVILIZATION_PLATOS_REPUBLIC',	'GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER2'),
('TRAIT_CIVILIZATION_PLATOS_REPUBLIC',	'GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER3'),
('CULTURE_KILLS_TRAIT',	                'GOLDEN_TRAIT_CULTURE_KILLS_ENCAMPMENT_HOUSING'),
('TRAIT_LEADER_SURROUNDED_BY_GLORY',	'GOLDEN_TRAIT_ANCIENT_CLASSICAL_WONDER_PRODUCTION'),
('TRAIT_LEADER_SURROUNDED_BY_GLORY',	'GOLDEN_TRAIT_SURROUNDED_BY_GLORY_WONDER_CULTURE'),
('TRAIT_LEADER_SURROUNDED_BY_GLORY',	'GOLDEN_TRAIT_SURROUNDED_BY_GLORY_WONDER_GOLD');
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT',						'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',								0,			0,			'GOLDEN_CITY_HAS_DISTRICT_GOVERNMENT_REQUIREMENTS'),
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_MODIFIER',				'MODIFIER_PLAYER_ADJUST_GOVERNOR_POINTS',								1,			1,			NULL),
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER1',					'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',								0,			0,			'BUILDING_IS_TIER1'),
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER1_MODIFIER',			'MODIFIER_PLAYER_ADJUST_GOVERNOR_POINTS',								1,			1,			NULL),
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER2',					'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',								0,			0,			'BUILDING_IS_TIER2'),
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER2_MODIFIER',			'MODIFIER_PLAYER_ADJUST_GOVERNOR_POINTS',								1,			1,			NULL),
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER3',					'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',								0,			0,			'BUILDING_IS_TIER3'),
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER3_MODIFIER',			'MODIFIER_PLAYER_ADJUST_GOVERNOR_POINTS',								1,			1,			NULL),
('GOLDEN_TRAIT_CULTURE_KILLS_ENCAMPMENT_HOUSING',			'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		                        0,			0,			'GOLDEN_DISTRICT_IS_DISTRICT_ENCAMPMENT_REQUIREMENTS'),
('GOLDEN_TRAIT_ANCIENT_CLASSICAL_WONDER_PRODUCTION',		'MODIFIER_PLAYER_CITIES_ADJUST_WONDER_ERA_PRODUCTION',		            0,			0,			NULL),
('GOLDEN_TRAIT_SURROUNDED_BY_GLORY_WONDER_CULTURE',		    'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		                            0,			0,			'PLOT_ADJACENT_TO_WONDER_REQUIREMENTS'),
('GOLDEN_TRAIT_SURROUNDED_BY_GLORY_WONDER_GOLD',		    'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		                            0,			0,			'PLOT_ADJACENT_TO_WONDER_REQUIREMENTS');

-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			        Name,		        Value) VALUES
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT',						'ModifierId',	'GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_MODIFIER'),
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_MODIFIER',				'Delta',		1),
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER1',					'ModifierId',	'GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER1_MODIFIER'),
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER1_MODIFIER',			'Delta',		1),
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER2',					'ModifierId',	'GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER2_MODIFIER'),
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER2_MODIFIER',			'Delta',		1),
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER3',					'ModifierId',	'GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER3_MODIFIER'),
('GOLDEN_TRAIT_GOVERNOR_GOVERNMENT_TIER3_MODIFIER',			'Delta',		1),
('GOLDEN_TRAIT_CULTURE_KILLS_ENCAMPMENT_HOUSING',			'Amount',		3),
('GOLDEN_TRAIT_ANCIENT_CLASSICAL_WONDER_PRODUCTION',		'Amount',		100),
('GOLDEN_TRAIT_ANCIENT_CLASSICAL_WONDER_PRODUCTION',		'IsWonder',		1),
('GOLDEN_TRAIT_ANCIENT_CLASSICAL_WONDER_PRODUCTION',		'StartEra',		'ERA_ANCIENT'),
('GOLDEN_TRAIT_ANCIENT_CLASSICAL_WONDER_PRODUCTION',		'EndEra',		'ERA_CLASSICAL'),
('GOLDEN_TRAIT_SURROUNDED_BY_GLORY_WONDER_CULTURE',			'YieldType',	'YIELD_CULTURE'),
('GOLDEN_TRAIT_SURROUNDED_BY_GLORY_WONDER_CULTURE',		    'Amount',		1),
('GOLDEN_TRAIT_SURROUNDED_BY_GLORY_WONDER_GOLD',			'YieldType',	'YIELD_GOLD'),
('GOLDEN_TRAIT_SURROUNDED_BY_GLORY_WONDER_GOLD',		    'Amount',		1);
