-----------------------------------------------
-- Districts
-----------------------------------------------
UPDATE Districts SET Housing = 6
WHERE DistrictType = 'DISTRICT_MBANZA';
-----------------------------------------------
-- DistrictModifiers
-----------------------------------------------
INSERT OR REPLACE INTO DistrictModifiers (DistrictType, 			ModifierID) VALUES	
('DISTRICT_MBANZA',	'GOLDEN_MBANZA_SCIENCE'),
('DISTRICT_MBANZA',	'GOLDEN_MBANZA_FAITH'),
('DISTRICT_MBANZA',	'GOLDEN_MBANZA_CULTURE'),
('DISTRICT_MBANZA',	'GOLDEN_MBANZA_PRODUCTION');
-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_LEADER_RELIGIOUS_CONVERT',	'GOLDEN_TRAIT_RELIGIOUS_CONVERT_FOREST_FAITH'),
('TRAIT_LEADER_RELIGIOUS_CONVERT',	'GOLDEN_TRAIT_RELIGIOUS_CONVERT_JUNGLE_FAITH'),
('TRAIT_CIVILIZATION_NKISI',	    'GOLDEN_TRAIT_DOUBLE_WRITING'),
('TRAIT_CIVILIZATION_NKISI',	    'GOLDEN_TRAIT_DOUBLE_RELIGIOUS'),
('TRAIT_CIVILIZATION_NKISI',	    'GOLDEN_TRAIT_DOUBLE_SCULPTURE'),
('TRAIT_CIVILIZATION_NKISI',	    'GOLDEN_TRAIT_DOUBLE_LANDSCAPE'),
('TRAIT_CIVILIZATION_NKISI',	    'GOLDEN_TRAIT_DOUBLE_ARTIFACT'),
('TRAIT_CIVILIZATION_NKISI',	    'GOLDEN_TRAIT_DOUBLE_MUSIC'),
('TRAIT_LEADER_RELIGIOUS_CONVERT',	    'GOLDEN_TRAIT_RELIGIOUS_CONVERT_LOYAL'),
('TRAIT_LEADER_RELIGIOUS_CONVERT',	    'GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST'),
('TRAIT_LEADER_RELIGIOUS_CONVERT',	    'GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST_2'),
('TRAIT_LEADER_RELIGIOUS_CONVERT',	    'GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST_3'),
('TRAIT_LEADER_RELIGIOUS_CONVERT',	    'GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST'),
('TRAIT_LEADER_RELIGIOUS_CONVERT',	    'GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST_2'),
('TRAIT_LEADER_RELIGIOUS_CONVERT',	    'GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST_3');

DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_NKISI' AND ModifierId = 'TRAIT_DOUBLE_MERCHANT_POINTS';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_NKISI' AND ModifierId = 'TRAIT_GREAT_WORK_FOOD_RELIC';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_NKISI' AND ModifierId = 'TRAIT_GREAT_WORK_PRODUCTION_RELIC';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_NKISI' AND ModifierId = 'TRAIT_GREAT_WORK_GOLD_RELIC';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_NKISI' AND ModifierId = 'TRAIT_GREAT_WORK_FOOD_ARTIFACT';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_NKISI' AND ModifierId = 'TRAIT_GREAT_WORK_PRODUCTION_ARTIFACT';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_NKISI' AND ModifierId = 'TRAIT_GREAT_WORK_GOLD_ARTIFACT';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_NKISI' AND ModifierId = 'TRAIT_GREAT_WORK_FOOD_SCULPTURE';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_NKISI' AND ModifierId = 'TRAIT_GREAT_WORK_PRODUCTION_SCULPTURE';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_NKISI' AND ModifierId = 'TRAIT_GREAT_WORK_GOLD_SCULPTURE';
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'TRAIT_CIVILIZATION_NKISI',	'GOLDEN_TRAIT_WRITING_BONUS' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'TRAIT_CIVILIZATION_NKISI',	'GOLDEN_TRAIT_RELIGIOUS_BONUS' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'TRAIT_CIVILIZATION_NKISI',	'GOLDEN_TRAIT_SCULPTURE_BONUS' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'TRAIT_CIVILIZATION_NKISI',	'GOLDEN_TRAIT_LANDSCAPE_BONUS' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'TRAIT_CIVILIZATION_NKISI',	'GOLDEN_TRAIT_ARTIFACT_BONUS' || YieldType FROM Yields;
INSERT OR REPLACE INTO TraitModifiers (TraitType,									ModifierId)
SELECT	'TRAIT_CIVILIZATION_NKISI',	'GOLDEN_TRAIT_MUSIC_BONUS' || YieldType FROM Yields;
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_RELIGIOUS_CONVERT' AND ModifierId = 'TRAIT_FREE_APOSTLE_FINISH_MBANZA';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_RELIGIOUS_CONVERT' AND ModifierId = 'TRAIT_FREE_APOSTLE_FINISH_THEATER_DISTRICT';
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES	
('GOLDEN_MBANZA_SCIENCE',                         'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', NULL),
('GOLDEN_MBANZA_FAITH',                           'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', NULL),
('GOLDEN_MBANZA_CULTURE',                         'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', NULL),
('GOLDEN_MBANZA_PRODUCTION',                      'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', NULL);

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_FOREST_FAITH',           'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',                  0, 0, 'GOLDEN_PLOT_HAS_FOREST_REQUIREMENTS'),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_JUNGLE_FAITH',           'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',                  0, 0, 'GOLDEN_PLOT_HAS_JUNGLE_REQUIREMENTS'),
('GOLDEN_TRAIT_DOUBLE_WRITING',                           'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM',              0, 0, NULL),
('GOLDEN_TRAIT_DOUBLE_RELIGIOUS',                         'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM',              0, 0, NULL),
('GOLDEN_TRAIT_DOUBLE_SCULPTURE',                         'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM',              0, 0, NULL),
('GOLDEN_TRAIT_DOUBLE_LANDSCAPE',                         'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM',              0, 0, NULL),
('GOLDEN_TRAIT_DOUBLE_ARTIFACT',                          'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM',              0, 0, NULL),
('GOLDEN_TRAIT_DOUBLE_MUSIC',                             'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM',              0, 0, NULL),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_LOYAL',                  'MODIFIER_PLAYER_CITIES_ADJUST_ALWAYS_LOYAL',         0, 0, 'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST',              'MODIFIER_PLAYER_GRANT_BOOST_WITH_GREAT_PERSON',      0, 0, NULL),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST_2',              'MODIFIER_PLAYER_GRANT_BOOST_WITH_GREAT_PERSON',      0, 0, NULL),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST_3',              'MODIFIER_PLAYER_GRANT_BOOST_WITH_GREAT_PERSON',      0, 0, NULL),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST',             'MODIFIER_PLAYER_GRANT_BOOST_WITH_GREAT_PERSON',      0, 0, NULL),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST_2',             'MODIFIER_PLAYER_GRANT_BOOST_WITH_GREAT_PERSON',      0, 0, NULL),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST_3',             'MODIFIER_PLAYER_GRANT_BOOST_WITH_GREAT_PERSON',      0, 0, NULL);


INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_WRITING_BONUS' || YieldType,	'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', NULL FROM Yields;		
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_RELIGIOUS_BONUS' || YieldType,	'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', NULL FROM Yields;		
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_SCULPTURE_BONUS' || YieldType,	'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', NULL FROM Yields;		
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_LANDSCAPE_BONUS' || YieldType,	'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', NULL FROM Yields;		
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_ARTIFACT_BONUS' || YieldType,	'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', NULL FROM Yields;		
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_MUSIC_BONUS' || YieldType,	'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', NULL FROM Yields;		
-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
UPDATE ModifierArguments SET  Value = 2
WHERE ModifierId = 'MBANZA_GOLD' AND Name = 'Amount';
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_MBANZA_SCIENCE',				'YieldType',	        'YIELD_SCIENCE'),
('GOLDEN_MBANZA_SCIENCE',				'Amount',	            2),
('GOLDEN_MBANZA_FAITH',				    'YieldType',	        'YIELD_FAITH'),
('GOLDEN_MBANZA_FAITH',				    'Amount',	            2),
('GOLDEN_MBANZA_CULTURE',				'YieldType',	        'YIELD_CULTURE'),
('GOLDEN_MBANZA_CULTURE',				'Amount',	            2),
('GOLDEN_MBANZA_PRODUCTION',			'YieldType',	        'YIELD_PRODUCTION'),
('GOLDEN_MBANZA_PRODUCTION',			'Amount',	            2),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_FOREST_FAITH',				'YieldType',	        'YIELD_FAITH'),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_FOREST_FAITH',				'Amount',	            2),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_JUNGLE_FAITH',				'YieldType',	        'YIELD_FAITH'),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_JUNGLE_FAITH',				'Amount',	            2),
('GOLDEN_TRAIT_DOUBLE_WRITING',				                'GreatWorkObjectType',	        'GREATWORKOBJECT_WRITING'),
('GOLDEN_TRAIT_DOUBLE_WRITING',				                'ScalingFactor',	            200),
('GOLDEN_TRAIT_DOUBLE_RELIGIOUS',			               	'GreatWorkObjectType',	        'GREATWORKOBJECT_RELIGIOUS'),
('GOLDEN_TRAIT_DOUBLE_RELIGIOUS',				            'ScalingFactor',	            200),
('GOLDEN_TRAIT_DOUBLE_SCULPTURE',				            'GreatWorkObjectType',	        'GREATWORKOBJECT_SCULPTURE'),
('GOLDEN_TRAIT_DOUBLE_SCULPTURE',				            'ScalingFactor',	            200),
('GOLDEN_TRAIT_DOUBLE_LANDSCAPE',				            'GreatWorkObjectType',	        'GREATWORKOBJECT_LANDSCAPE'),
('GOLDEN_TRAIT_DOUBLE_LANDSCAPE',				            'ScalingFactor',	            200),
('GOLDEN_TRAIT_DOUBLE_ARTIFACT',				            'GreatWorkObjectType',	        'GREATWORKOBJECT_ARTIFACT'),
('GOLDEN_TRAIT_DOUBLE_ARTIFACT',			            	'ScalingFactor',	            200),
('GOLDEN_TRAIT_DOUBLE_MUSIC',				                'GreatWorkObjectType',	        'GREATWORKOBJECT_MUSIC'),
('GOLDEN_TRAIT_DOUBLE_MUSIC',				                'ScalingFactor',	            200),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST',			            	'GreatPersonClass',	    'GREAT_PERSON_CLASS_PROPHET'),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST',				            'TechBoost',	        1),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST',				            'OtherPlayers',	        1),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST_2',			            	'GreatPersonClass',	    'GREAT_PERSON_CLASS_PROPHET'),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST_2',				            'TechBoost',	        1),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST_2',				            'OtherPlayers',	        1),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST_3',			            	'GreatPersonClass',	    'GREAT_PERSON_CLASS_PROPHET'),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST_3',				            'TechBoost',	        1),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_TECHBOOST_3',				            'OtherPlayers',	        1),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST',			            	'GreatPersonClass',	    'GREAT_PERSON_CLASS_PROPHET'),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST',				            'TechBoost',	        0),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST',				            'OtherPlayers',	        1),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST_2',			            	'GreatPersonClass',	    'GREAT_PERSON_CLASS_PROPHET'),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST_2',				            'TechBoost',	        0),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST_2',				            'OtherPlayers',	        1),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST_3',			            	'GreatPersonClass',	    'GREAT_PERSON_CLASS_PROPHET'),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST_3',				            'TechBoost',	        0),
('GOLDEN_TRAIT_RELIGIOUS_CONVERT_CIVICBOOST_3',				            'OtherPlayers',	        1);

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_WRITING_BONUS' || YieldType,	'YieldType', YieldType FROM	Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_WRITING_BONUS' || YieldType,	'YieldChange', 2 FROM Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_WRITING_BONUS' || YieldType,	'GreatWorkObjectType', 'GREATWORKOBJECT_WRITING' FROM Yields;
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_RELIGIOUS_BONUS' || YieldType,	'YieldType', YieldType FROM	Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_RELIGIOUS_BONUS' || YieldType,	'YieldChange', 2 FROM Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_RELIGIOUS_BONUS' || YieldType,	'GreatWorkObjectType', 'GREATWORKOBJECT_RELIGIOUS' FROM Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_SCULPTURE_BONUS' || YieldType,	'YieldType', YieldType FROM	Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_SCULPTURE_BONUS' || YieldType,	'YieldChange', 2 FROM Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_SCULPTURE_BONUS' || YieldType,	'GreatWorkObjectType', 'GREATWORKOBJECT_SCULPTURE' FROM Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_LANDSCAPE_BONUS' || YieldType,	'YieldType', YieldType FROM	Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_LANDSCAPE_BONUS' || YieldType,	'YieldChange', 2 FROM Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_LANDSCAPE_BONUS' || YieldType,	'GreatWorkObjectType', 'GREATWORKOBJECT_LANDSCAPE' FROM Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_ARTIFACT_BONUS' || YieldType,	'YieldType', YieldType FROM	Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_ARTIFACT_BONUS' || YieldType,	'YieldChange', 2 FROM Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_ARTIFACT_BONUS' || YieldType,	'GreatWorkObjectType', 'GREATWORKOBJECT_ARTIFACT' FROM Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_MUSIC_BONUS' || YieldType,	'YieldType', YieldType FROM	Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_MUSIC_BONUS' || YieldType,	'YieldChange', 2 FROM Yields;		
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_MUSIC_BONUS' || YieldType,	'GreatWorkObjectType', 'GREATWORKOBJECT_MUSIC' FROM Yields;		