-----------------------------------------------
-- Leaders_XP2
-----------------------------------------------
-- DELETE FROM Leaders_XP2 WHERE LeaderType = 'LEADER_KUPE' AND OceanStart = 1;
-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_CIVILIZATION_MAORI_MANA',	'GOLDEN_TRAIT_COAST_CITY_CENTER_FOOD'),
('TRAIT_CIVILIZATION_MAORI_MANA',	'GOLDEN_TRAIT_COAST_CITY_CENTER_PRODUCTION'),
('TRAIT_CIVILIZATION_MAORI_MANA',	'GOLDEN_TRAIT_COAST_CITY_CENTER_GOLD'),
('TRAIT_CIVILIZATION_MAORI_MANA',	'GOLDEN_TRAIT_COAST_CITY_CENTER_FAITH'),
('TRAIT_CIVILIZATION_MAORI_MANA',	'GOLDEN_TRAIT_COAST_CITY_CENTER_SCIENCE'),
('TRAIT_CIVILIZATION_MAORI_MANA',	'GOLDEN_TRAIT_COAST_CITY_CENTER_CULTURE');
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_MAORI_MANA' AND ModifierId = 'TRAIT_MAORI_FISHING_BOAT_FOOD';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_MAORI_MANA' AND ModifierId = 'TRAIT_MAORI_FISHING_BOAT_CULTURE_BOMB';
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
('GOLDEN_TRAIT_COAST_CITY_CENTER_FOOD',       'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY', 0, 0, NULL),
('GOLDEN_TRAIT_COAST_CITY_CENTER_PRODUCTION', 'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY', 0, 0, NULL),
('GOLDEN_TRAIT_COAST_CITY_CENTER_GOLD',       'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY', 0, 0, NULL),
('GOLDEN_TRAIT_COAST_CITY_CENTER_FAITH',      'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY', 0, 0, NULL),
('GOLDEN_TRAIT_COAST_CITY_CENTER_SCIENCE',    'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY', 0, 0, NULL),
('GOLDEN_TRAIT_COAST_CITY_CENTER_CULTURE',    'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY', 0, 0, NULL);

-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_TRAIT_COAST_CITY_CENTER_FOOD',					            'YieldType',	    'YIELD_FOOD'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_FOOD',					            'Amount',	        1),
('GOLDEN_TRAIT_COAST_CITY_CENTER_FOOD',					            'Description',	    'LOC_DISTRICT_COAST_FOOD'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_FOOD',					            'TerrainType',	    'TERRAIN_COAST'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_FOOD',					            'DistrictType',	    'DISTRICT_CITY_CENTER'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_PRODUCTION',					    'YieldType',	    'YIELD_PRODUCTION'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_PRODUCTION',					    'Amount',	        1),
('GOLDEN_TRAIT_COAST_CITY_CENTER_PRODUCTION',					    'Description',	    'LOC_DISTRICT_COAST_PRODUCTION'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_PRODUCTION',					    'TerrainType',	    'TERRAIN_COAST'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_PRODUCTION',					    'DistrictType',	    'DISTRICT_CITY_CENTER'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_GOLD',					            'YieldType',	    'YIELD_GOLD'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_GOLD',					            'Amount',	        1),
('GOLDEN_TRAIT_COAST_CITY_CENTER_GOLD',					            'Description',	    'LOC_DISTRICT_COAST_GOLD'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_GOLD',					            'TerrainType',	    'TERRAIN_COAST'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_GOLD',					            'DistrictType',	    'DISTRICT_CITY_CENTER'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_FAITH',					        'YieldType',	    'YIELD_FAITH'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_FAITH',					        'Amount',	        1),
('GOLDEN_TRAIT_COAST_CITY_CENTER_FAITH',					        'Description',	    'LOC_DISTRICT_COAST_FAITH'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_FAITH',					        'TerrainType',	    'TERRAIN_COAST'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_FAITH',					        'DistrictType',	    'DISTRICT_CITY_CENTER'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_SCIENCE',					        'YieldType',	    'YIELD_SCIENCE'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_SCIENCE',					        'Amount',	        1),
('GOLDEN_TRAIT_COAST_CITY_CENTER_SCIENCE',					        'Description',	    'LOC_DISTRICT_COAST_SCIENCE'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_SCIENCE',					        'TerrainType',	    'TERRAIN_COAST'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_SCIENCE',					        'DistrictType',	    'DISTRICT_CITY_CENTER'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_CULTURE',					        'YieldType',	    'YIELD_CULTURE'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_CULTURE',					        'Amount',	        1),
('GOLDEN_TRAIT_COAST_CITY_CENTER_CULTURE',					        'Description',	    'LOC_DISTRICT_COAST_CULTURE'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_CULTURE',					        'TerrainType',	    'TERRAIN_COAST'),
('GOLDEN_TRAIT_COAST_CITY_CENTER_CULTURE',					        'DistrictType',	    'DISTRICT_CITY_CENTER');
UPDATE ModifierArguments SET  Value = 2
WHERE ModifierId = 'POPULATION_PRESETTLEMENT' AND Name = 'Amount';