--UA
-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_NOBEL_PRIZE';
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'TRAIT_GREATPERSON_FAVOR_MODIFIER'),--base game
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'TRAIT_GREAT_SCIENTIST_UNIVERSITY_MODIFIER'),--base game
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'TRAIT_GREAT_ENGINEER_FACTORY_MODIFIER'),--base game

('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_GREAT_MERCHANT_BANK_MODIFIER'),
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_HOUSING_BANK'),
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_HOUSING_UNIVERSITY'),
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_HOUSING_FACTORY'),
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_AMENITY_BANK'),
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_AMENITY_UNIVERSITY'),
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_AMENITY_FACTORY'),
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_CITIZEN_BANK'),
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_CITIZEN_UNIVERSITY'),
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_CITIZEN_FACTORY'),

('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_BANK'),
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_UNIVERSITY'),
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_FACTORY'),
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_BANK'),
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_UNIVERSITY'),
('TRAIT_CIVILIZATION_NOBEL_PRIZE',	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_FACTORY');

INSERT OR REPLACE INTO TraitModifiers (TraitType,				ModifierId) SELECT	
'TRAIT_CIVILIZATION_NOBEL_PRIZE',		'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_COMMERCIAL'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,				ModifierId) SELECT	
'TRAIT_CIVILIZATION_NOBEL_PRIZE',		'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_TAX_BUREAU'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');
INSERT OR REPLACE INTO TraitModifiers (TraitType,				ModifierId) SELECT	
'TRAIT_CIVILIZATION_NOBEL_PRIZE',		'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_PUBLIC_SCHOOL'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PUBLIC_SCHOOL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,				ModifierId) SELECT	
'TRAIT_CIVILIZATION_NOBEL_PRIZE',		'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_ACADEMIC_EXCHANGE'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ACADEMIC_EXCHANGE');
INSERT OR REPLACE INTO TraitModifiers (TraitType,				ModifierId) SELECT	
'TRAIT_CIVILIZATION_NOBEL_PRIZE',		'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_RAWMATERIAL'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_RAWMATERIAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,				ModifierId) SELECT	
'TRAIT_CIVILIZATION_NOBEL_PRIZE',		'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_FABRICATION'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_FABRICATION');
INSERT OR REPLACE INTO TraitModifiers (TraitType,				ModifierId) SELECT	
'TRAIT_CIVILIZATION_NOBEL_PRIZE',		'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_COMMERCIAL'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,				ModifierId) SELECT	
'TRAIT_CIVILIZATION_NOBEL_PRIZE',		'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_TAX_BUREAU'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');
INSERT OR REPLACE INTO TraitModifiers (TraitType,				ModifierId) SELECT	
'TRAIT_CIVILIZATION_NOBEL_PRIZE',		'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_PUBLIC_SCHOOL'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PUBLIC_SCHOOL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,				ModifierId) SELECT	
'TRAIT_CIVILIZATION_NOBEL_PRIZE',		'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_ACADEMIC_EXCHANGE'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ACADEMIC_EXCHANGE');
INSERT OR REPLACE INTO TraitModifiers (TraitType,				ModifierId) SELECT	
'TRAIT_CIVILIZATION_NOBEL_PRIZE',		'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_RAWMATERIAL'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_RAWMATERIAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,				ModifierId) SELECT	
'TRAIT_CIVILIZATION_NOBEL_PRIZE',		'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_FABRICATION'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_FABRICATION');
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId,						ModifierType,								                                    SubjectRequirementSetId) VALUES	
('GA_TRAIT_GREAT_MERCHANT_BANK_MODIFIER',			            'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',		                        'GA_SWEDEN_CITY_HAS_COMMERCIAL_T2_REQUIREMENTS'),
('GA_TRAIT_NOBEL_PRIZE_HOUSING_BANK',			                'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_HOUSING',		                        'GA_SWEDEN_CITY_HAS_COMMERCIAL_T2_REQUIREMENTS'),
('GA_TRAIT_NOBEL_PRIZE_HOUSING_UNIVERSITY',			            'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_HOUSING',		                        'GA_SWEDEN_CITY_HAS_CAMPUS_T2_REQUIREMENTS'),
('GA_TRAIT_NOBEL_PRIZE_HOUSING_FACTORY',			            'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_HOUSING',		                        'GA_SWEDEN_CITY_HAS_INDUSTRIAL_T2_REQUIREMENTS'),
('GA_TRAIT_NOBEL_PRIZE_AMENITY_BANK',			                'MODIFIER_PLAYER_CITIES_ADJUST_TRAIT_AMENITY',		                            'GA_SWEDEN_CITY_HAS_COMMERCIAL_T2_REQUIREMENTS'),
('GA_TRAIT_NOBEL_PRIZE_AMENITY_UNIVERSITY',			            'MODIFIER_PLAYER_CITIES_ADJUST_TRAIT_AMENITY',		                            'GA_SWEDEN_CITY_HAS_CAMPUS_T2_REQUIREMENTS'),
('GA_TRAIT_NOBEL_PRIZE_AMENITY_FACTORY',			            'MODIFIER_PLAYER_CITIES_ADJUST_TRAIT_AMENITY',		                            'GA_SWEDEN_CITY_HAS_INDUSTRIAL_T2_REQUIREMENTS'),
('GA_TRAIT_NOBEL_PRIZE_CITIZEN_BANK',			                'MODIFIER_PLAYER_CITIES_ADD_POPULATION',		                                'GA_SWEDEN_CITY_HAS_COMMERCIAL_T2_REQUIREMENTS'),
('GA_TRAIT_NOBEL_PRIZE_CITIZEN_UNIVERSITY',			            'MODIFIER_PLAYER_CITIES_ADD_POPULATION',		                                'GA_SWEDEN_CITY_HAS_CAMPUS_T2_REQUIREMENTS'),
('GA_TRAIT_NOBEL_PRIZE_CITIZEN_FACTORY',			            'MODIFIER_PLAYER_CITIES_ADD_POPULATION',		                                'GA_SWEDEN_CITY_HAS_INDUSTRIAL_T2_REQUIREMENTS');
UPDATE Modifiers SET  SubjectRequirementSetId = 'GA_SWEDEN_CITY_HAS_CAMPUS_T2_REQUIREMENTS'
WHERE ModifierId = 'TRAIT_GREAT_SCIENTIST_UNIVERSITY_MODIFIER';
UPDATE Modifiers SET  SubjectRequirementSetId = 'GA_SWEDEN_CITY_HAS_INDUSTRIAL_T2_REQUIREMENTS'
WHERE ModifierId = 'TRAIT_GREAT_ENGINEER_FACTORY_MODIFIER';
INSERT OR REPLACE INTO Modifiers (ModifierId,										    ModifierType,												SubjectRequirementSetId)
SELECT	ModifierId,	        'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',				NULL FROM TraitModifiers WHERE ModifierId LIKE 'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_%';
INSERT OR REPLACE INTO Modifiers (ModifierId,										    ModifierType,												SubjectRequirementSetId)
SELECT	ModifierId,	    	'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION',				NULL FROM TraitModifiers WHERE ModifierId LIKE 'GA_TRAIT_NOBEL_PRIZE_FASTER_%';
-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GA_TRAIT_GREAT_MERCHANT_BANK_MODIFIER',					'GreatPersonClassType',	    'GREAT_PERSON_CLASS_MERCHANT'),
('GA_TRAIT_GREAT_MERCHANT_BANK_MODIFIER',					'Amount',	                1),
('GA_TRAIT_NOBEL_PRIZE_HOUSING_BANK',				    	'Amount',	                1),
('GA_TRAIT_NOBEL_PRIZE_HOUSING_UNIVERSITY',					'Amount',	                1),
('GA_TRAIT_NOBEL_PRIZE_HOUSING_FACTORY',					'Amount',	                1),
('GA_TRAIT_NOBEL_PRIZE_AMENITY_BANK',				    	'Amount',	                1),
('GA_TRAIT_NOBEL_PRIZE_AMENITY_UNIVERSITY',					'Amount',	                1),
('GA_TRAIT_NOBEL_PRIZE_AMENITY_FACTORY',					'Amount',	                1),
('GA_TRAIT_NOBEL_PRIZE_CITIZEN_BANK',				    	'Amount',	                1),
('GA_TRAIT_NOBEL_PRIZE_CITIZEN_UNIVERSITY',					'Amount',	                1),
('GA_TRAIT_NOBEL_PRIZE_CITIZEN_FACTORY',					'Amount',	                1);
UPDATE ModifierArguments SET  Value = 100
WHERE ModifierId = 'TRAIT_GREATPERSON_FAVOR_MODIFIER' AND Name = 'Amount';

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_BANK',					'BuildingType',	    'BUILDING_BANK'),
('GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_BANK',					'YieldType',	    'YIELD_GOLD'),
('GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_UNIVERSITY',			'BuildingType',	    'BUILDING_UNIVERSITY'),
('GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_UNIVERSITY',			'YieldType',	    'YIELD_SCIENCE'),
('GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_FACTORY',				'BuildingType',	    'BUILDING_FACTORY'),
('GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_FACTORY',				'YieldType',	    'YIELD_PRODUCTION'),
('GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_BANK',						'BuildingType',	    'BUILDING_BANK'),
('GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_BANK',						'YieldType',	    'YIELD_GOLD'),
('GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_UNIVERSITY',					'BuildingType',	    'BUILDING_UNIVERSITY'),
('GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_UNIVERSITY',					'YieldType',	    'YIELD_SCIENCE'),
('GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_FACTORY',					'BuildingType',	    'BUILDING_FACTORY'),
('GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_FACTORY',					'YieldType',	    'YIELD_PRODUCTION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	ModifierId,					'Amount',	    4 	FROM TraitModifiers WHERE ModifierId LIKE 'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_%';
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	ModifierId,					'Amount',	    100 FROM TraitModifiers WHERE ModifierId LIKE 'GA_TRAIT_NOBEL_PRIZE_FASTER_%';
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_COMMERCIAL',			'BuildingType',	'BUILDING_COMMERCIAL' 			WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_COMMERCIAL',			'YieldType',	'YIELD_GOLD' 					WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_TAX_BUREAU',			'BuildingType',	'BUILDING_TAX_BUREAU' 			WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_TAX_BUREAU',			'YieldType',	'YIELD_GOLD' 					WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_PUBLIC_SCHOOL',			'BuildingType',	'BUILDING_PUBLIC_SCHOOL' 		WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PUBLIC_SCHOOL');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_PUBLIC_SCHOOL',			'YieldType',	'YIELD_SCIENCE' 				WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PUBLIC_SCHOOL');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_ACADEMIC_EXCHANGE',		'BuildingType',	'BUILDING_ACADEMIC_EXCHANGE' 	WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ACADEMIC_EXCHANGE');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_ACADEMIC_EXCHANGE',		'YieldType',	'YIELD_SCIENCE' 				WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ACADEMIC_EXCHANGE');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_RAWMATERIAL',			'BuildingType',	'BUILDING_RAWMATERIAL' 			WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_RAWMATERIAL');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_RAWMATERIAL',			'YieldType',	'YIELD_PRODUCTION' 				WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_RAWMATERIAL');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_FABRICATION',			'BuildingType',	'BUILDING_FABRICATION' 			WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_FABRICATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_DOUBLE_YIELD_BUILDING_FABRICATION',			'YieldType',	'YIELD_PRODUCTION' 				WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_FABRICATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_COMMERCIAL',				'BuildingType',	'BUILDING_COMMERCIAL' 			WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_COMMERCIAL',				'YieldType',	'YIELD_GOLD' 					WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_TAX_BUREAU',				'BuildingType',	'BUILDING_TAX_BUREAU' 			WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_TAX_BUREAU',				'YieldType',	'YIELD_GOLD' 					WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_PUBLIC_SCHOOL',			'BuildingType',	'BUILDING_PUBLIC_SCHOOL' 		WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PUBLIC_SCHOOL');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_PUBLIC_SCHOOL',			'YieldType',	'YIELD_SCIENCE' 				WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PUBLIC_SCHOOL');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_ACADEMIC_EXCHANGE',		'BuildingType',	'BUILDING_ACADEMIC_EXCHANGE' 	WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ACADEMIC_EXCHANGE');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_ACADEMIC_EXCHANGE',		'YieldType',	'YIELD_SCIENCE' 				WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ACADEMIC_EXCHANGE');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_RAWMATERIAL',				'BuildingType',	'BUILDING_RAWMATERIAL' 			WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_RAWMATERIAL');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_RAWMATERIAL',				'YieldType',	'YIELD_PRODUCTION' 				WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_RAWMATERIAL');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_FABRICATION',				'BuildingType',	'BUILDING_FABRICATION' 			WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_FABRICATION');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_NOBEL_PRIZE_FASTER_BUILDING_FABRICATION',				'YieldType',	'YIELD_PRODUCTION' 				WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_FABRICATION');
---------------------------------------------------------------------------------------------------------------
-- RequirementSets
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSets 				
(RequirementSetId ,         RequirementSetType) 	VALUES 		
('GA_SWEDEN_CITY_HAS_COMMERCIAL_T2_REQUIREMENTS' , 		'REQUIREMENTSET_TEST_ANY'),
('GA_SWEDEN_CITY_HAS_CAMPUS_T2_REQUIREMENTS' , 			'REQUIREMENTSET_TEST_ANY'),
('GA_SWEDEN_CITY_HAS_INDUSTRIAL_T2_REQUIREMENTS' , 		'REQUIREMENTSET_TEST_ANY');
---------------------------------------------------------------------------------------------------------------
-- RequirementSetRequirements
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSetRequirements 	
(RequirementSetId ,         RequirementId) 			VALUES 		
('GA_SWEDEN_CITY_HAS_COMMERCIAL_T2_REQUIREMENTS' , 		    'GOLDEN_REQUIRES_CITY_HAS_BUILDING_BANK'),
('GA_SWEDEN_CITY_HAS_CAMPUS_T2_REQUIREMENTS' , 				'GOLDEN_REQUIRES_CITY_HAS_BUILDING_UNIVERSITY'),
('GA_SWEDEN_CITY_HAS_INDUSTRIAL_T2_REQUIREMENTS' , 		    'GOLDEN_REQUIRES_CITY_HAS_BUILDING_FACTORY');
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,							RequirementId) SELECT	
'GA_SWEDEN_CITY_HAS_COMMERCIAL_T2_REQUIREMENTS',	    'GA_REQUIRES_CITY_HAS_BUILDING_COMMERCIAL' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,							RequirementId) SELECT	
'GA_SWEDEN_CITY_HAS_COMMERCIAL_T2_REQUIREMENTS',	    'GA_REQUIRES_CITY_HAS_BUILDING_TAX_BUREAU' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,							RequirementId) SELECT	
'GA_SWEDEN_CITY_HAS_CAMPUS_T2_REQUIREMENTS',	    'GA_REQUIRES_CITY_HAS_BUILDING_PUBLIC_SCHOOL' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PUBLIC_SCHOOL');
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,							RequirementId) SELECT	
'GA_SWEDEN_CITY_HAS_CAMPUS_T2_REQUIREMENTS',	    'GA_REQUIRES_CITY_HAS_BUILDING_ACADEMIC_EXCHANGE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ACADEMIC_EXCHANGE');
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,							RequirementId) SELECT	
'GA_SWEDEN_CITY_HAS_INDUSTRIAL_T2_REQUIREMENTS',	    'GA_REQUIRES_CITY_HAS_BUILDING_RAWMATERIAL' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_RAWMATERIAL');
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,							RequirementId) SELECT	
'GA_SWEDEN_CITY_HAS_INDUSTRIAL_T2_REQUIREMENTS',	    'GA_REQUIRES_CITY_HAS_BUILDING_FABRICATION' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_FABRICATION');
---------------------------------------------------------------------------------------------------------------
-- Requirements
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GA_REQUIRES_CITY_HAS_BUILDING_COMMERCIAL' , 		   	 'REQUIREMENT_CITY_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GA_REQUIRES_CITY_HAS_BUILDING_TAX_BUREAU' , 		   	 'REQUIREMENT_CITY_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GA_REQUIRES_CITY_HAS_BUILDING_PUBLIC_SCHOOL' , 		 'REQUIREMENT_CITY_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PUBLIC_SCHOOL');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GA_REQUIRES_CITY_HAS_BUILDING_ACADEMIC_EXCHANGE' , 	 'REQUIREMENT_CITY_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ACADEMIC_EXCHANGE');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GA_REQUIRES_CITY_HAS_BUILDING_RAWMATERIAL' , 		   	 'REQUIREMENT_CITY_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_RAWMATERIAL');
INSERT OR REPLACE INTO Requirements 	(RequirementId ,     RequirementType) 			SELECT 	
'GA_REQUIRES_CITY_HAS_BUILDING_FABRICATION' , 		   	 'REQUIREMENT_CITY_HAS_BUILDING' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_FABRICATION');
---------------------------------------------------------------------------------------------------------------
-- RequirementArguments
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GA_REQUIRES_CITY_HAS_BUILDING_COMMERCIAL',			'BuildingType',	    'BUILDING_COMMERCIAL' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GA_REQUIRES_CITY_HAS_BUILDING_TAX_BUREAU',			'BuildingType',	    'BUILDING_TAX_BUREAU' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GA_REQUIRES_CITY_HAS_BUILDING_PUBLIC_SCHOOL',		'BuildingType',	    'BUILDING_PUBLIC_SCHOOL' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_PUBLIC_SCHOOL');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GA_REQUIRES_CITY_HAS_BUILDING_ACADEMIC_EXCHANGE',	'BuildingType',	    'BUILDING_ACADEMIC_EXCHANGE' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_ACADEMIC_EXCHANGE');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GA_REQUIRES_CITY_HAS_BUILDING_RAWMATERIAL',		'BuildingType',	    'BUILDING_RAWMATERIAL' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_RAWMATERIAL');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,				Name,				Value) SELECT	 
'GA_REQUIRES_CITY_HAS_BUILDING_FABRICATION',		'BuildingType',	    'BUILDING_FABRICATION' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_FABRICATION');

--LA
-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_KRISTINA_AUTO_THEME';
--可考虑给剧院广场T1和T3建筑加1个槽位
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_LEADER_KRISTINA_AUTO_THEME',	'AUTO_THEME_AT_LEAST_3_SLOTS'),--base game
('TRAIT_LEADER_KRISTINA_AUTO_THEME',	'AUTO_THEME_AT_LEAST_2_SLOTS'),--base game
('TRAIT_LEADER_KRISTINA_AUTO_THEME',	'THEMED_YIELD_MODIFIER'),--base game??
('TRAIT_LEADER_KRISTINA_AUTO_THEME',	'THEMED_TOURISM_MODIFIER');--base game??

UPDATE ModifierArguments SET  Value = 200
WHERE ModifierId = 'THEMED_YIELD_MODIFIER' AND Name = 'Amount';
UPDATE ModifierArguments SET  Value = 200
WHERE ModifierId = 'THEMED_TOURISM_MODIFIER' AND Name = 'Amount';
---------------------------------------------------------------------------------------------------------------
-- Building_GreatWorks
---------------------------------------------------------------------------------------------------------------
DELETE FROM Building_GreatWorks WHERE BuildingType = 'BUILDING_QUEENS_BIBLIOTHEQUE';
INSERT OR REPLACE INTO Building_GreatWorks (BuildingType, 			GreatWorkSlotType, NumSlots) VALUES	
('BUILDING_QUEENS_BIBLIOTHEQUE',	    'GREATWORKSLOT_PALACE', 6);
---------------------------------------------------------------------------------------------------------------
-- Building_GreatPersonPoints
---------------------------------------------------------------------------------------------------------------
UPDATE Building_GreatPersonPoints SET PointsPerTurn = 4
WHERE BuildingType = 'BUILDING_QUEENS_BIBLIOTHEQUE' AND GreatPersonClassType = 'GREAT_PERSON_CLASS_ARTIST';
UPDATE Building_GreatPersonPoints SET PointsPerTurn = 4
WHERE BuildingType = 'BUILDING_QUEENS_BIBLIOTHEQUE' AND GreatPersonClassType = 'GREAT_PERSON_CLASS_WRITER';
UPDATE Building_GreatPersonPoints SET PointsPerTurn = 4
WHERE BuildingType = 'BUILDING_QUEENS_BIBLIOTHEQUE' AND GreatPersonClassType = 'GREAT_PERSON_CLASS_MUSICIAN';