-----------------------------------------------
-- DistrictModifiers
-----------------------------------------------
DELETE FROM DistrictModifiers WHERE DistrictType = 'DISTRICT_ROYAL_NAVY_DOCKYARD' AND ModifierId = 'ROYAL_NAVY_DOCKYARD_GOLD_FROM_FOREIGN_CONTINENT';
-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_INDUSTRIAL_REVOLUTION';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_PAX_BRITANNICA';

INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_LEADER_PAX_BRITANNICA',					'TRAIT_ROYAL_NAVY_DOCKYARD_NAVAL_UNIT'),--Base game
('TRAIT_LEADER_PAX_BRITANNICA',					'GOLDEN_TRAIT_PAX_BRITANNICA_FOREIGN_COMBAT'),
('TRAIT_LEADER_PAX_BRITANNICA',	                'GOLDEN_TRAIT_PAX_BRITANNICA_FOREIGN_CITY_MELEE_UNIT');
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_CIVILIZATION_INDUSTRIAL_REVOLUTION',	'TRAIT_FOREIGN_CONTINENT_TRADE_ROUTE'),--Base game
('TRAIT_CIVILIZATION_INDUSTRIAL_REVOLUTION',	'TRAIT_ADJUST_INDUSTRIAL_ZONE_BUILDINGS_PRODUCTION'),--Base game
('TRAIT_CIVILIZATION_INDUSTRIAL_REVOLUTION',	'GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_INDUSTRIAL_ZONE_PRODUCTION'),
('TRAIT_CIVILIZATION_INDUSTRIAL_REVOLUTION',	'GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_TECH_INDUSTRIALIZATION'),
('TRAIT_CIVILIZATION_INDUSTRIAL_REVOLUTION',	'GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_TECH_SCIENTIFIC_THEORY'),
('TRAIT_CIVILIZATION_INDUSTRIAL_REVOLUTION',	'GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_TECH_BALLISTICS'),
('TRAIT_CIVILIZATION_INDUSTRIAL_REVOLUTION',	'GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_TECH_RIFLING');

INSERT OR REPLACE INTO TraitModifiers (TraitType,			ModifierId)
SELECT	'TRAIT_CIVILIZATION_INDUSTRIAL_REVOLUTION',			'GA_TRAIT_INDUSTRIAL_REVOLUTION_FOREIGN_COASTAL_CITY' ||YieldType FROM Yields WHERE YieldType <>'YIELD_FOOD';	

-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
('GOLDEN_TRAIT_PAX_BRITANNICA_FOREIGN_CITY_MELEE_UNIT',             'MODIFIER_PLAYER_CITIES_GRANT_UNIT_BY_CLASS',         0, 0,                     'GOLDEN_ENGLAND_CITY_NOT_OWNER_CAPITAL_CONTINENT_REQUIREMENTS'),
('GOLDEN_TRAIT_PAX_BRITANNICA_FOREIGN_COMBAT' , 					'MODIFIER_PLAYER_UNITS_GRANT_ABILITY' ,	0 , 0 , NULL ),
('GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_INDUSTRIAL_ZONE_PRODUCTION',	'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION',  0, 0,                    	NULL),
('GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_TECH_INDUSTRIALIZATION',       'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',          1, 1,                     'GOLDEN_PLAYER_HAS_TECH_MASS_PRODUCTION_AND_TECH_SQUARE_RIGGING_REQUIREMENTS'),
('GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_TECH_SCIENTIFIC_THEORY',       'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',          1, 1,                     'GOLDEN_PLAYER_HAS_TECH_ASTRONOMY_AND_TECH_BANKING_REQUIREMENTS'),
('GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_TECH_BALLISTICS',              'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',          1, 1,                     'GOLDEN_PLAYER_HAS_TECH_SIEGE_TACTICS_REQUIREMENTS'),
('GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_TECH_RIFLING',                 'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',          1, 1,                     'GOLDEN_PLAYER_HAS_TECH_METAL_CASTING_REQUIREMENTS');
INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,												SubjectRequirementSetId)
SELECT	'GA_TRAIT_INDUSTRIAL_REVOLUTION_FOREIGN_COASTAL_CITY' ||YieldType,	        'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',		'GOLDEN_ENGLAND_COASTAL_CITY_NOT_OWNER_CAPITAL_CONTINENT_REQUIREMENTS' FROM Yields WHERE YieldType <>'YIELD_FOOD';	

-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_TRAIT_PAX_BRITANNICA_FOREIGN_CITY_MELEE_UNIT',			                    'UnitPromotionClassType',	    'PROMOTION_CLASS_MELEE'),
('GOLDEN_TRAIT_PAX_BRITANNICA_FOREIGN_COMBAT', 						'AbilityType', 					'ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT'),
('GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_INDUSTRIAL_ZONE_PRODUCTION',					'DistrictType',	                'DISTRICT_INDUSTRIAL_ZONE'),
('GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_INDUSTRIAL_ZONE_PRODUCTION',					'Amount',	                    100),
('GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_TECH_INDUSTRIALIZATION',		                'TechType',	                    'TECH_INDUSTRIALIZATION'),
('GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_TECH_SCIENTIFIC_THEORY',		                'TechType',	                    'TECH_SCIENTIFIC_THEORY'),
('GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_TECH_BALLISTICS',		                        'TechType',	                    'TECH_BALLISTICS'),
('GOLDEN_TRAIT_INDUSTRIAL_REVOLUTION_TECH_RIFLING',		                            'TechType',	                    'TECH_RIFLING');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_INDUSTRIAL_REVOLUTION_FOREIGN_COASTAL_CITY' ||YieldType,	        'Amount',	    20 FROM Yields WHERE YieldType <>'YIELD_FOOD';	
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,			            Value)
SELECT	'GA_TRAIT_INDUSTRIAL_REVOLUTION_FOREIGN_COASTAL_CITY' ||YieldType,	        'YieldType',	YieldType FROM Yields WHERE YieldType <>'YIELD_FOOD';	

UPDATE ModifierArguments SET  Value = 100
WHERE ModifierId = 'TRAIT_ADJUST_INDUSTRIAL_ZONE_BUILDINGS_PRODUCTION' AND Name = 'Amount';
UPDATE ModifierArguments SET  Value = 2
WHERE ModifierId = 'TRAIT_FOREIGN_CONTINENT_TRADE_ROUTE' AND Name = 'Amount';
UPDATE ModifierArguments SET  Value = 10
WHERE ModifierId = 'ROYAL_NAVY_DOCKYARD_IDENTITY_PER_TURN_MODIFIER' AND Name = 'Amount';

---------------------------------------------------------------------------------------------------------------
-- RequirementSets
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSets 				(RequirementSetId ,         	RequirementSetType) 	VALUES
('GOLDEN_ENGLAND_CITY_NOT_OWNER_CAPITAL_CONTINENT_REQUIREMENTS' , 		        	'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_ENGLAND_COASTAL_CITY_NOT_OWNER_CAPITAL_CONTINENT_REQUIREMENTS' , 	    	'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLAYER_HAS_TECH_ASTRONOMY_AND_TECH_BANKING_REQUIREMENTS' , 	    		'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PLAYER_HAS_TECH_MASS_PRODUCTION_AND_TECH_SQUARE_RIGGING_REQUIREMENTS' , 	'REQUIREMENTSET_TEST_ALL');
---------------------------------------------------------------------------------------------------------------
-- RequirementSetRequirements
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,         RequirementId) 			VALUES 		
('GOLDEN_ENGLAND_CITY_NOT_OWNER_CAPITAL_CONTINENT_REQUIREMENTS' , 		            'REQUIRES_CITY_IS_NOT_OWNER_CAPITAL_CONTINENT'),
('GOLDEN_ENGLAND_COASTAL_CITY_NOT_OWNER_CAPITAL_CONTINENT_REQUIREMENTS' , 		    'REQUIRES_CITY_IS_NOT_OWNER_CAPITAL_CONTINENT'),
('GOLDEN_ENGLAND_COASTAL_CITY_NOT_OWNER_CAPITAL_CONTINENT_REQUIREMENTS' , 		    'GOLDEN_REQUIRES_PLOT_ADJACENT_TO_COAST'),
('GOLDEN_PLAYER_HAS_TECH_ASTRONOMY_AND_TECH_BANKING_REQUIREMENTS' , 				'GOLDEN_REQUIRES_PLAYER_HAS_TECH_ASTRONOMY'),
('GOLDEN_PLAYER_HAS_TECH_ASTRONOMY_AND_TECH_BANKING_REQUIREMENTS' , 				'GOLDEN_REQUIRES_PLAYER_HAS_TECH_BANKING'),
('GOLDEN_PLAYER_HAS_TECH_MASS_PRODUCTION_AND_TECH_SQUARE_RIGGING_REQUIREMENTS' , 	'GOLDEN_REQUIRES_PLAYER_HAS_TECH_SQUARE_RIGGING'),
('GOLDEN_PLAYER_HAS_TECH_MASS_PRODUCTION_AND_TECH_SQUARE_RIGGING_REQUIREMENTS' , 	'GOLDEN_REQUIRES_PLAYER_HAS_TECH_MASS_PRODUCTION');


-----------------------------------------------
-- Types
-----------------------------------------------
INSERT OR REPLACE INTO Types (Type,						Kind) VALUES
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',					'KIND_ABILITY');
-----------------------------------------------
-- TypeTags
-----------------------------------------------		
INSERT OR REPLACE INTO TypeTags (Type,									Tag) VALUES	
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',				'CLASS_LIGHT_CAVALRY'),
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',			    'CLASS_HEAVY_CAVALRY'),
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',			    'CLASS_MELEE'),
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',			    'CLASS_TRUE_RANGED'),
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',			    'CLASS_SIEGE'),
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',			    'CLASS_RECON'),
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',			    'CLASS_ANTI_CAVALRY'),
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',			    'CLASS_NAVAL_MELEE'),
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',			    'CLASS_NAVAL_RANGED'),
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',			    'CLASS_NAVAL_RAIDER'),
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',			    'CLASS_NAVAL_CARRIER'),
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',			    'CLASS_AIRCRAFT');
INSERT OR REPLACE INTO TypeTags (Type, Tag) SELECT 'ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT', 'CLASS_AUTOMATIC_GUN' WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_COMPOSITE_BOWMAN');
-----------------------------------------------
-- UnitAbilities
-----------------------------------------------
INSERT OR REPLACE INTO UnitAbilities (UnitAbilityType,						Name,									Description, Inactive) VALUES	
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',			'LOC_ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT_NAME',	'LOC_ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT_DESCRIPTION', 1);
-----------------------------------------------
-- UnitAbilityModifiers
-----------------------------------------------
INSERT OR REPLACE INTO UnitAbilityModifiers (UnitAbilityType,						ModifierId) VALUES	
('ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',			            'GA_ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT');
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId,						ModifierType,		SubjectRequirementSetId) VALUES	
('GA_ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',		'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',		'REDCOAT_PLOT_IS_FOREIGN_CONTINENT');
-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GA_ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',	'Amount',	    5);
-----------------------------------------------
-- ModifierStrings
-----------------------------------------------
INSERT OR REPLACE INTO ModifierStrings (ModifierId,			Context,		        Text) VALUES
('GA_ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT',	'Preview',	    'LOC_ABILITY_PAX_BRITANNICA_FOREIGN_COMBAT_DESCRIPTION');

