-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_CIVILIZATION_FIRST_CIVILIZATION',	    'GOLDEN_FIRST_CIVILIZATION_MORE_CIVIC_BOOST'),
('TRAIT_CIVILIZATION_FIRST_CIVILIZATION',	    'GOLDEN_FIRST_CIVILIZATION_CULTURE_DEBUFF'),
-- ('TRAIT_CIVILIZATION_FIRST_CIVILIZATION',	    'GOLDEN_TRAIT_FIRST_CIVILIZATION_RIVER_CITY_HOUSING'),
-- ('TRAIT_CIVILIZATION_FIRST_CIVILIZATION',	    'GOLDEN_TRAIT_FIRST_CIVILIZATION_RIVER_CITY_AMENITY'),
('TRAIT_CIVILIZATION_FIRST_CIVILIZATION',	    'GOLDEN_TRAIT_FIRST_CIVILIZATION_BARBARIAN_COMBAT_BONUS');

DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_ADVENTURES_ENKIDU' AND NOT EXISTS (SELECT TraitType FROM Traits WHERE TraitType = 'TRAIT_LEADER_GILGAMESH_HEROES');

INSERT OR REPLACE INTO TraitModifiers (TraitType,					ModifierId)	
SELECT 'TRAIT_LEADER_ADVENTURES_ENKIDU',	'GOLDEN_TRAIT_ENKIDU_RIVER_CITY_INFLUENCE_TOKEN' WHERE NOT EXISTS (SELECT TraitType FROM Traits WHERE TraitType = 'TRAIT_LEADER_GILGAMESH_HEROES');
INSERT OR REPLACE INTO TraitModifiers (TraitType,					ModifierId)	
SELECT 'TRAIT_LEADER_ADVENTURES_ENKIDU',	'TRAIT_LEVY_DISCOUNT' WHERE NOT EXISTS (SELECT TraitType FROM Traits WHERE TraitType = 'TRAIT_LEADER_GILGAMESH_HEROES');
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
-- ('GOLDEN_TRAIT_FIRST_CIVILIZATION_RIVER_CITY_HOUSING',					        'MODIFIER_PLAYER_CITIES_ADJUST_WATER_HOUSING',								0,			0,			'PLOT_ADJACENT_TO_RIVER_REQUIREMENTS'),
-- ('GOLDEN_TRAIT_FIRST_CIVILIZATION_RIVER_CITY_AMENITY',					        'MODIFIER_PLAYER_CITIES_ADJUST_TRAIT_AMENITY',								0,			0,			'PLOT_ADJACENT_TO_RIVER_REQUIREMENTS'),
('GOLDEN_TRAIT_ENKIDU_RIVER_CITY_INFLUENCE_TOKEN',								'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',								    0,			0,			'PLOT_ADJACENT_TO_RIVER_REQUIREMENTS'),
('GOLDEN_TRAIT_ENKIDU_RIVER_CITY_INFLUENCE_TOKEN_MODIFIER',		    			'MODIFIER_PLAYER_GRANT_INFLUENCE_TOKEN',								    1,			1,			NULL),
('GOLDEN_TRAIT_FIRST_CIVILIZATION_BARBARIAN_COMBAT_BONUS',			            'MODIFIER_PLAYER_UNITS_ADJUST_BARBARIAN_COMBAT',							0,			0,			NULL),
('GOLDEN_FIRST_CIVILIZATION_MORE_CIVIC_BOOST',			                        'MODIFIER_PLAYER_ADJUST_CIVIC_BOOST',							            0,			0,			NULL),
('GOLDEN_FIRST_CIVILIZATION_CULTURE_DEBUFF',			                        'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',		0,			0,			NULL);
-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			    Name,		        Value) VALUES
-- ('GOLDEN_TRAIT_FIRST_CIVILIZATION_RIVER_CITY_HOUSING',					    'Amount',		1),
-- ('GOLDEN_TRAIT_FIRST_CIVILIZATION_RIVER_CITY_AMENITY',					    'Amount',		1),
('GOLDEN_TRAIT_ENKIDU_RIVER_CITY_INFLUENCE_TOKEN',				'ModifierId',	'GOLDEN_TRAIT_ENKIDU_RIVER_CITY_INFLUENCE_TOKEN_MODIFIER'),
('GOLDEN_TRAIT_ENKIDU_RIVER_CITY_INFLUENCE_TOKEN_MODIFIER',	    'Amount',		1),
('GOLDEN_TRAIT_FIRST_CIVILIZATION_BARBARIAN_COMBAT_BONUS',		            'Amount',		10),

('GOLDEN_FIRST_CIVILIZATION_MORE_CIVIC_BOOST',		                            'Amount',		100),
('GOLDEN_FIRST_CIVILIZATION_CULTURE_DEBUFF',		                            'YieldType',	'YIELD_CULTURE'),
('GOLDEN_FIRST_CIVILIZATION_CULTURE_DEBUFF',		                            'Amount',		-50);
 