-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_CIVILIZATION_ZULU_ISIBONGO',	'GOLDEN_TRAIT_PASTURE_ADJACENT_FOOD'),
('TRAIT_CIVILIZATION_ZULU_ISIBONGO',	'GOLDEN_TRAIT_PLANTATION_ADJACENT_GOLD'),
('TRAIT_LEADER_AMABUTHO',	            'GOLDEN_TRAIT_ANTICAVALRY_PRODUCTION');
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId,						        ModifierType,								                                    SubjectRequirementSetId) VALUES	
('GOLDEN_TRAIT_PASTURE_ADJACENT_FOOD',			                'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		                                    'GOLDEN_PLOT_IS_ADJACENT_TO_IMPROVEMENT_PASTURE_REQUIREMENTS'),
('GOLDEN_TRAIT_PLANTATION_ADJACENT_GOLD',			            'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		                                    'GOLDEN_PLOT_IS_ADJACENT_TO_IMPROVEMENT_PLANTATION_REQUIREMENTS'),
('GOLDEN_TRAIT_ANTICAVALRY_PRODUCTION',			                'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION',		                NULL);
-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_TRAIT_PASTURE_ADJACENT_FOOD',					            'YieldType',	        'YIELD_FOOD'),
('GOLDEN_TRAIT_PASTURE_ADJACENT_FOOD',					            'Amount',	            1),
('GOLDEN_TRAIT_PLANTATION_ADJACENT_GOLD',					        'YieldType',	        'YIELD_GOLD'),
('GOLDEN_TRAIT_PLANTATION_ADJACENT_GOLD',					        'Amount',	            1),
('GOLDEN_TRAIT_ANTICAVALRY_PRODUCTION',					            'UnitPromotionClass',	'PROMOTION_CLASS_ANTI_CAVALRY'),
('GOLDEN_TRAIT_ANTICAVALRY_PRODUCTION',					            'EraType',	            'NO_ERA'),
('GOLDEN_TRAIT_ANTICAVALRY_PRODUCTION',					            'Amount',	            100);


--UD
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_CIVILIZATION_ZULU_ISIBONGO',	'GOLDEN_IKANDA_FARM_HOUSING'),
('TRAIT_CIVILIZATION_ZULU_ISIBONGO',	'GOLDEN_IKANDA_PASTURE_HOUSING'),
('TRAIT_CIVILIZATION_ZULU_ISIBONGO',	'GOLDEN_IKANDA_PLANTATION_HOUSING'),
('TRAIT_CIVILIZATION_ZULU_ISIBONGO',	'GOLDEN_IKANDA_CAMP_HOUSING'),
('TRAIT_CIVILIZATION_ZULU_ISIBONGO',	'GOLDEN_IKANDA_CANAL_HOUSING'),
('TRAIT_CIVILIZATION_ZULU_ISIBONGO',	'GOLDEN_IKANDA_AERODROME_HOUSING'),
('TRAIT_CIVILIZATION_ZULU_ISIBONGO',	'GOLDEN_IKANDA_GOVERNMENT_HOUSING'),
('TRAIT_CIVILIZATION_ZULU_ISIBONGO',	'GOLDEN_IKANDA_CITY_CENTER_HOUSING');

INSERT OR REPLACE INTO Modifiers (ModifierId,						ModifierType,								                                    SubjectRequirementSetId) VALUES	
('GOLDEN_IKANDA_FARM_HOUSING',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_FARM_REQUIREMENTS'),
('GOLDEN_IKANDA_PASTURE_HOUSING',			        'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_PASTURE_REQUIREMENTS'),
('GOLDEN_IKANDA_PLANTATION_HOUSING',			    'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_PLANTATION_REQUIREMENTS'),
('GOLDEN_IKANDA_CAMP_HOUSING',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_CAMP_REQUIREMENTS'),
('GOLDEN_IKANDA_CANAL_HOUSING',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_CANAL_REQUIREMENTS'),
('GOLDEN_IKANDA_AERODROME_HOUSING',			        'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_AERODROME_REQUIREMENTS'),
('GOLDEN_IKANDA_GOVERNMENT_HOUSING',			    'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_GOVERNMENT_REQUIREMENTS'),
('GOLDEN_IKANDA_CITY_CENTER_HOUSING',			    'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',		            'GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_CITY_CENTER_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_IKANDA_FARM_HOUSING',					            'Amount',	    1),
('GOLDEN_IKANDA_PASTURE_HOUSING',					        'Amount',	    1),
('GOLDEN_IKANDA_PLANTATION_HOUSING',					    'Amount',	    1),
('GOLDEN_IKANDA_CAMP_HOUSING',					            'Amount',	    1),
('GOLDEN_IKANDA_CANAL_HOUSING',					            'Amount',	    1),
('GOLDEN_IKANDA_AERODROME_HOUSING',					        'Amount',	    1),
('GOLDEN_IKANDA_GOVERNMENT_HOUSING',					    'Amount',	    1),
('GOLDEN_IKANDA_CITY_CENTER_HOUSING',					    'Amount',	    1);

INSERT OR REPLACE INTO RequirementSets		(RequirementSetId,							RequirementSetType) VALUES
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_FARM_REQUIREMENTS',		                'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_PASTURE_REQUIREMENTS',		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_PLANTATION_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_CAMP_REQUIREMENTS',		                'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_CANAL_REQUIREMENTS',		            'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_AERODROME_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_CITY_CENTER_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements		(RequirementSetId,							RequirementId) VALUES	
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_FARM_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_IKANDA'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_FARM_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_FARM'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_PASTURE_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_IKANDA'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_PASTURE_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_PASTURE'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_PLANTATION_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_IKANDA'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_PLANTATION_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_PLANTATION'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_CAMP_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_IKANDA'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_CAMP_REQUIREMENTS',		        'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_IMPROVEMENT_CAMP'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_CANAL_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_IKANDA'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_CANAL_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_CANAL'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_AERODROME_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_IKANDA'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_AERODROME_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_AERODROME'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_IKANDA'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_GOVERNMENT_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_GOVERNMENT'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_CITY_CENTER_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_IKANDA'),
('GOLDEN_DISTRICT_IS_IKANDA_ADJACENT_TO_CITY_CENTER_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_CITY_CENTER');