-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
-- ('TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT',	'GOLDEN_TRAIT_ENLIGHTENMENT_GOLD_HAPPY'),
-- ('TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT',	'GOLDEN_TRAIT_ENLIGHTENMENT_GOLD_ECSTATIC'),
-- ('TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT',	'GOLDEN_TRAIT_ENLIGHTENMENT_MERCHANT_HAPPY'),
-- ('TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT',	'GOLDEN_TRAIT_ENLIGHTENMENT_MERCHANT_ECSTATIC'),
('TRAIT_LEADER_BANNOCKBURN',	                'GOLDEN_TRAIT_BANNOCKBURN_CAMPUS_HOUSING'),
('TRAIT_LEADER_BANNOCKBURN',	                'GOLDEN_TRAIT_BANNOCKBURN_COMMERCIAL_HUB_HOUSING'),
('TRAIT_LEADER_BANNOCKBURN',	                'GOLDEN_TRAIT_BANNOCKBURN_HOLY_SITE_HOUSING'),
('TRAIT_LEADER_BANNOCKBURN',	                'GOLDEN_TRAIT_BANNOCKBURN_THEATER_HOUSING'),
('TRAIT_LEADER_BANNOCKBURN',	                'GOLDEN_TRAIT_BANNOCKBURN_INDUSTRIAL_ZONE_HOUSING'),
('TRAIT_LEADER_BANNOCKBURN',	                'GOLDEN_TRAIT_BANNOCKBURN_ENCAMPMENT_HOUSING'),
('TRAIT_LEADER_BANNOCKBURN',	                'GOLDEN_TRAIT_BANNOCKBURN_CAMPUS_AMENITY'),
('TRAIT_LEADER_BANNOCKBURN',	                'GOLDEN_TRAIT_BANNOCKBURN_COMMERCIAL_HUB_AMENITY'),
('TRAIT_LEADER_BANNOCKBURN',	                'GOLDEN_TRAIT_BANNOCKBURN_HOLY_SITE_AMENITY'),
('TRAIT_LEADER_BANNOCKBURN',	                'GOLDEN_TRAIT_BANNOCKBURN_THEATER_AMENITY'),
('TRAIT_LEADER_BANNOCKBURN',	                'GOLDEN_TRAIT_BANNOCKBURN_INDUSTRIAL_ZONE_AMENITY'),
('TRAIT_LEADER_BANNOCKBURN',	                'GOLDEN_TRAIT_BANNOCKBURN_ENCAMPMENT_AMENITY');
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_GOLD_HAPPY',              'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_YIELD',          0, 0,  NULL),
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_GOLD_ECSTATIC',           'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_YIELD',          0, 0,  NULL),
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_MERCHANT_HAPPY',          'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_GREAT_PERSON',   0, 0,  'DISTRICT_IS_COMMERCIAL_HUB'),
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_MERCHANT_ECSTATIC',       'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_GREAT_PERSON',   0, 0,  'DISTRICT_IS_COMMERCIAL_HUB'),
('GOLDEN_TRAIT_BANNOCKBURN_CAMPUS_HOUSING',            'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_HOUSING',   0, 0,  'GOLDEN_CAMPUS_HAS_TWO_ADJACENCY_REQUIREMENTS'),
('GOLDEN_TRAIT_BANNOCKBURN_COMMERCIAL_HUB_HOUSING',    'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_HOUSING',   0, 0,  'GOLDEN_COMMERCIAL_HUB_HAS_TWO_ADJACENCY_REQUIREMENTS'),
('GOLDEN_TRAIT_BANNOCKBURN_HOLY_SITE_HOUSING',         'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_HOUSING',   0, 0,  'GOLDEN_HOLY_SITE_HAS_TWO_ADJACENCY_REQUIREMENTS'),
('GOLDEN_TRAIT_BANNOCKBURN_THEATER_HOUSING',           'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_HOUSING',   0, 0,  'GOLDEN_THEATER_HAS_TWO_ADJACENCY_REQUIREMENTS'),
('GOLDEN_TRAIT_BANNOCKBURN_INDUSTRIAL_ZONE_HOUSING',   'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_HOUSING',   0, 0,  'GOLDEN_INDUSTRIAL_ZONE_HAS_TWO_ADJACENCY_REQUIREMENTS'),
('GOLDEN_TRAIT_BANNOCKBURN_ENCAMPMENT_HOUSING',        'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_HOUSING',   0, 0,  'GOLDEN_HARBOR_HAS_TWO_ADJACENCY_REQUIREMENTS'),
('GOLDEN_TRAIT_BANNOCKBURN_CAMPUS_AMENITY',            'MODIFIER_PLAYER_CITIES_ADJUST_TRAIT_AMENITY',   0, 0,  'GOLDEN_CAMPUS_HAS_FOUR_ADJACENCY_REQUIREMENTS'),
('GOLDEN_TRAIT_BANNOCKBURN_COMMERCIAL_HUB_AMENITY',    'MODIFIER_PLAYER_CITIES_ADJUST_TRAIT_AMENITY',   0, 0,  'GOLDEN_COMMERCIAL_HUB_HAS_FOUR_ADJACENCY_REQUIREMENTS'),
('GOLDEN_TRAIT_BANNOCKBURN_HOLY_SITE_AMENITY',         'MODIFIER_PLAYER_CITIES_ADJUST_TRAIT_AMENITY',   0, 0,  'GOLDEN_HOLY_SITE_HAS_FOUR_ADJACENCY_REQUIREMENTS'),
('GOLDEN_TRAIT_BANNOCKBURN_THEATER_AMENITY',           'MODIFIER_PLAYER_CITIES_ADJUST_TRAIT_AMENITY',   0, 0,  'GOLDEN_THEATER_HAS_FOUR_ADJACENCY_REQUIREMENTS'),
('GOLDEN_TRAIT_BANNOCKBURN_INDUSTRIAL_ZONE_AMENITY',   'MODIFIER_PLAYER_CITIES_ADJUST_TRAIT_AMENITY',   0, 0,  'GOLDEN_INDUSTRIAL_ZONE_HAS_FOUR_ADJACENCY_REQUIREMENTS'),
('GOLDEN_TRAIT_BANNOCKBURN_ENCAMPMENT_AMENITY',        'MODIFIER_PLAYER_CITIES_ADJUST_TRAIT_AMENITY',   0, 0,  'GOLDEN_HARBOR_HAS_FOUR_ADJACENCY_REQUIREMENTS');
-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_GOLD_HAPPY',				'YieldType',	            'YIELD_GOLD'),
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_GOLD_HAPPY',				'HappinessType',            'HAPPINESS_HAPPY'),
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_GOLD_HAPPY',				'Amount',	                7),
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_GOLD_ECSTATIC',			'YieldType',	            'YIELD_GOLD'),
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_GOLD_ECSTATIC',			'HappinessType',            'HAPPINESS_ECSTATIC'),
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_GOLD_ECSTATIC',			'Amount',	                14),
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_MERCHANT_HAPPY',			'GreatPersonClassType',	    'GREAT_PERSON_CLASS_MERCHANT'),
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_MERCHANT_HAPPY',			'HappinessType',            'HAPPINESS_HAPPY'),
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_MERCHANT_HAPPY',			'Amount',	                1),
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_MERCHANT_ECSTATIC',		'GreatPersonClassType',	    'GREAT_PERSON_CLASS_MERCHANT'),
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_MERCHANT_ECSTATIC',		'HappinessType',            'HAPPINESS_ECSTATIC'),
-- ('GOLDEN_TRAIT_ENLIGHTENMENT_MERCHANT_ECSTATIC',		'Amount',	                2),
('GOLDEN_TRAIT_BANNOCKBURN_CAMPUS_HOUSING',			    'Amount',	                1),
('GOLDEN_TRAIT_BANNOCKBURN_COMMERCIAL_HUB_HOUSING',		'Amount',	                1),
('GOLDEN_TRAIT_BANNOCKBURN_HOLY_SITE_HOUSING',			'Amount',	                1),
('GOLDEN_TRAIT_BANNOCKBURN_THEATER_HOUSING',			'Amount',	                1),
('GOLDEN_TRAIT_BANNOCKBURN_INDUSTRIAL_ZONE_HOUSING',	'Amount',	                1),
('GOLDEN_TRAIT_BANNOCKBURN_ENCAMPMENT_HOUSING',			'Amount',	                1),
('GOLDEN_TRAIT_BANNOCKBURN_CAMPUS_AMENITY',			    'Amount',	                1),
('GOLDEN_TRAIT_BANNOCKBURN_COMMERCIAL_HUB_AMENITY',		'Amount',	                1),
('GOLDEN_TRAIT_BANNOCKBURN_HOLY_SITE_AMENITY',			'Amount',	                1),
('GOLDEN_TRAIT_BANNOCKBURN_THEATER_AMENITY',			'Amount',	                1),
('GOLDEN_TRAIT_BANNOCKBURN_INDUSTRIAL_ZONE_AMENITY',	'Amount',	                1),
('GOLDEN_TRAIT_BANNOCKBURN_ENCAMPMENT_AMENITY',			'Amount',	                1);
-- UPDATE ModifierArguments SET  Value = 7
-- WHERE ModifierId = 'TRAIT_SCIENCE_HAPPY' AND Name = 'Amount';
-- UPDATE ModifierArguments SET  Value = 14
-- WHERE ModifierId = 'TRAIT_SCIENCE_ECSTATIC' AND Name = 'Amount';
-- UPDATE ModifierArguments SET  Value = 7
-- WHERE ModifierId = 'TRAIT_PRODUCTION_HAPPY' AND Name = 'Amount';
-- UPDATE ModifierArguments SET  Value = 14
-- WHERE ModifierId = 'TRAIT_PRODUCTION_ECSTATIC' AND Name = 'Amount';

-----------------------------------------------
-- New Happinesses
----------------------------------------------
-- UPDATE Traits SET  Description = 'LOC_TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT_DESCRIPTION_GA'
-- WHERE TraitType = 'TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT';
--YIELD
DELETE FROM TraitModifiers WHERE  ModifierId = 'TRAIT_SCIENCE_HAPPY' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
DELETE FROM TraitModifiers WHERE  ModifierId = 'TRAIT_SCIENCE_ECSTATIC' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
DELETE FROM TraitModifiers WHERE  ModifierId = 'TRAIT_PRODUCTION_HAPPY' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
DELETE FROM TraitModifiers WHERE  ModifierId = 'TRAIT_PRODUCTION_ECSTATIC' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
DELETE FROM TraitModifiers WHERE  ModifierId = 'GOLDEN_TRAIT_ENLIGHTENMENT_GOLD_HAPPY' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
DELETE FROM TraitModifiers WHERE  ModifierId = 'GOLDEN_TRAIT_ENLIGHTENMENT_GOLD_ECSTATIC' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');

INSERT OR REPLACE INTO TraitModifiers (TraitType,		 ModifierID) SELECT	
'TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT',	         'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_GOLD_' ||HappinessType 	  	FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO TraitModifiers (TraitType,		 ModifierID) SELECT	
'TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT',	         'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_SCIENCE_' ||HappinessType 	FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO TraitModifiers (TraitType,		 ModifierID) SELECT	
'TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT',	         'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_PRODUCTION_' ||HappinessType FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');

INSERT OR REPLACE INTO Modifiers (ModifierID,		 ModifierType) SELECT	
ModifierID,	         'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_YIELD'  FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_%' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'YieldType',	            'YIELD_GOLD' FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_GOLD_%' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'YieldType',	            'YIELD_SCIENCE' FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_SCIENCE_%' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'YieldType',	            'YIELD_PRODUCTION' FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_PRODUCTION_%' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_GOLD_' ||HappinessType,			 	 'HappinessType',	            HappinessType FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_SCIENCE_' ||HappinessType,			 'HappinessType',	            HappinessType FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_PRODUCTION_' ||HappinessType,			 'HappinessType',	            HappinessType FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'Amount',	            5 FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_%HAPPINESS_HAPPY' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'Amount',	            5 FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_%HAPPINESS_JOYOUS' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'Amount',	            10 FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_%HAPPINESS_ELATED' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'Amount',	            10 FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_%HAPPINESS_ECSTATIC' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'Amount',	            15 FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_%HAPPINESS_UTOPIC' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'Amount',	            15 FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_YIELD_%HAPPINESS_HEAVEN' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');

--GREAT PEOPLE
DELETE FROM TraitModifiers WHERE  ModifierId = 'TRAIT_SCIENTIST_HAPPY' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
DELETE FROM TraitModifiers WHERE  ModifierId = 'TRAIT_SCIENTIST_ECSTATIC' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
DELETE FROM TraitModifiers WHERE  ModifierId = 'TRAIT_ENGINEER_HAPPY' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
DELETE FROM TraitModifiers WHERE  ModifierId = 'TRAIT_ENGINEER_ECSTATIC' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
DELETE FROM TraitModifiers WHERE  ModifierId = 'GOLDEN_TRAIT_ENLIGHTENMENT_MERCHANT_HAPPY' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
DELETE FROM TraitModifiers WHERE  ModifierId = 'GOLDEN_TRAIT_ENLIGHTENMENT_MERCHANT_ECSTATIC' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');

INSERT OR REPLACE INTO TraitModifiers (TraitType,		 ModifierID) SELECT	
'TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT',	         'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_SCIENTIST_' ||HappinessType FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO TraitModifiers (TraitType,		 ModifierID) SELECT	
'TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT',	         'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_ENGINEER_' ||HappinessType 	FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO TraitModifiers (TraitType,		 ModifierID) SELECT	
'TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT',	         'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_MERCHANT_' ||HappinessType  FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');

INSERT OR REPLACE INTO Modifiers (ModifierID,		 ModifierType,		SubjectRequirementSetId) SELECT	
'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_SCIENTIST_' ||HappinessType,	         'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_GREAT_PERSON',  'DISTRICT_IS_CAMPUS' FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO Modifiers (ModifierID,		 ModifierType,		SubjectRequirementSetId) SELECT	
'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_ENGINEER_' ||HappinessType,	         'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_GREAT_PERSON',  'DISTRICT_IS_INDUSTRIAL_ZONE' FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO Modifiers (ModifierID,		 ModifierType,		SubjectRequirementSetId) SELECT	
'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_MERCHANT_' ||HappinessType,	         'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_GREAT_PERSON',  'DISTRICT_IS_COMMERCIAL_HUB' FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_SCIENTIST_' ||HappinessType,			 'HappinessType',	            HappinessType FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_ENGINEER_' ||HappinessType,			 'HappinessType',	            HappinessType FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_MERCHANT_' ||HappinessType,			 'HappinessType',	            HappinessType FROM Happinesses WHERE NonFoodYieldModifier>0 AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'GreatPersonClassType',	            'GREAT_PERSON_CLASS_SCIENTIST' FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_SCIENTIST_%' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'GreatPersonClassType',	            'GREAT_PERSON_CLASS_ENGINEER' FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_ENGINEER_%' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'GreatPersonClassType',	            'GREAT_PERSON_CLASS_MERCHANT' FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_MERCHANT_%' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');

INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'Amount',	            1 FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_%HAPPINESS_HAPPY' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'Amount',	            1 FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_%HAPPINESS_JOYOUS' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'Amount',	            2 FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_%HAPPINESS_ELATED' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'Amount',	            2 FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_%HAPPINESS_ECSTATIC' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'Amount',	            3 FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_%HAPPINESS_UTOPIC' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) SELECT
ModifierID,			 'Amount',	            3 FROM TraitModifiers WHERE ModifierID LIKE 'GOLDEN_TRAIT_ENLIGHTENMENT_GREAT_PERSON_CLASS_%HAPPINESS_HEAVEN' AND EXISTS (SELECT * FROM Happinesses WHERE HappinessType = 'HAPPINESS_HEAVEN');
