------
--UA--
------
--TraitModifiers
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_LAST_PROPHET';
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_CIVILIZATION_LAST_PROPHET',	'TRAIT_GUARANTEE_ONE_PROPHET'),--Base game
('TRAIT_CIVILIZATION_LAST_PROPHET',	'TRAIT_ORIGIN_DESTINATION_RELIGIOUS_PRESSURE'),--Base game
('TRAIT_CIVILIZATION_LAST_PROPHET',	'GOLDEN_TRAIT_TRADE_ROUTE_FROM_TEMPLE'),
('TRAIT_CIVILIZATION_LAST_PROPHET',	'GA_TRAIT_LAST_PROPHET_LOYALTY_DEBUFF'),
('TRAIT_CIVILIZATION_LAST_PROPHET',	'GA_ARABIA_TRAIT_HOLY_SITE_DESERT_FAITH'),
('TRAIT_CIVILIZATION_LAST_PROPHET',	'GA_ARABIA_TRAIT_HOLY_SITE_DESERT_HILLS_FAITH'),
('TRAIT_CIVILIZATION_LAST_PROPHET',	'GA_ARABIA_TRAIT_HOLY_SITE_DESERT_MOUNTAIN_FAITH');
----Modifiers
INSERT OR REPLACE INTO Modifiers (ModifierId,					ModifierType,												SubjectRequirementSetId) VALUES
('GOLDEN_TRAIT_TRADE_ROUTE_FROM_TEMPLE',						'MODIFIER_PLAYER_CITIES_ADJUST_TRADE_ROUTE_CAPACITY',		'GOLDEN_CITY_HAS_BUILDING_TEMPLE_REQUIREMENTS'),
('GA_TRAIT_LAST_PROPHET_LOYALTY_DEBUFF',						'MODIFIER_PLAYER_CITIES_ADJUST_IDENTITY_PER_TURN',		    'GOLDEN_CITY_NOT_FOLLOWS_RELIGION_REQUIREMENTS'),	
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_FAITH',           			'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY',					NULL),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_HILLS_FAITH',             	'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY',					NULL),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_MOUNTAIN_FAITH',		        'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY',					NULL);
--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments (ModifierId,				    Name,		        Value) VALUES
('GOLDEN_TRAIT_TRADE_ROUTE_FROM_TEMPLE',					        	'Amount',       	1),
('GA_TRAIT_LAST_PROPHET_LOYALTY_DEBUFF',								'Amount',	        -6),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_FAITH',			            		'DistrictType',		'DISTRICT_HOLY_SITE'),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_FAITH',			            		'TerrainType',		'TERRAIN_DESERT'),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_FAITH',			            		'YieldType',		'YIELD_FAITH'),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_FAITH',			            		'Amount',			1),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_FAITH',			            		'TilesRequired',	1),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_FAITH',		             			'Description',		'LOC_DISTRICT_DESERT_FAITH'),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_HILLS_FAITH',		        		'DistrictType',		'DISTRICT_HOLY_SITE'),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_HILLS_FAITH',		                'TerrainType',		'TERRAIN_DESERT_HILLS'),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_HILLS_FAITH',		                'YieldType',		'YIELD_FAITH'),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_HILLS_FAITH',		                'Amount',			1),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_HILLS_FAITH',		                'TilesRequired',	1),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_HILLS_FAITH',		                'Description',		'LOC_DISTRICT_DESERT_FAITH'),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_MOUNTAIN_FAITH',		                'DistrictType',		'DISTRICT_HOLY_SITE'),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_MOUNTAIN_FAITH',		                'TerrainType',		'TERRAIN_DESERT_MOUNTAIN'),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_MOUNTAIN_FAITH',		                'YieldType',		'YIELD_FAITH'),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_MOUNTAIN_FAITH',		                'Amount',			1),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_MOUNTAIN_FAITH',		                'TilesRequired',	1),
('GA_ARABIA_TRAIT_HOLY_SITE_DESERT_MOUNTAIN_FAITH',		                'Description',		'LOC_DISTRICT_DESERT_FAITH');
------
--LA--
------
--TraitModifiers
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH';
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH',	'TRAIT_RELIGIOUS_BUILDING_DISCOUNT'),--Base game
('TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH',	'TRAIT_RELIGIOUS_BUILDING_MULTIPLIER_CULTURE'),--Base game
('TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH',	'TRAIT_RELIGIOUS_BUILDING_MULTIPLIER_FAITH'),--Base game
('TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH',	'TRAIT_RELIGIOUS_BUILDING_MULTIPLIER_SCIENCE'),--Base game
('TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH',	'GA_TRAIT_RIGHTEOUSNESS_OF_FAITH_COMBAT'),
('TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH',	'GA_TRAIT_SCIENCE_PER_FOREIGN_CITY_FOLLOWING_RELIGION'),
('TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH',	'GA_TRAIT_FAITH_PER_FOREIGN_CITY_FOLLOWING_RELIGION'),
('TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH',	'GA_TRAIT_SCIENCE_PER_CITY_FOLLOWING_RELIGION'),
('TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH',	'GA_TRAIT_FAITH_PER_CITY_FOLLOWING_RELIGION');
----Modifiers
INSERT OR REPLACE INTO Modifiers (ModifierId,						ModifierType,												SubjectRequirementSetId) VALUES
('GA_TRAIT_RIGHTEOUSNESS_OF_FAITH_COMBAT',							'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER',	        		'WARS_OF_RELIGION_REQUIREMENTS'),
('GA_TRAIT_RIGHTEOUSNESS_OF_FAITH_COMBAT_MODIFIER',					'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',	            		'REQUIREMENTS_OPPONENT_IS_OTHER_RELIGION'),
('GA_TRAIT_SCIENCE_PER_FOREIGN_CITY_FOLLOWING_RELIGION',			'MODIFIER_PLAYER_RELIGION_ADD_PLAYER_BELIEF_YIELD',		    NULL),
('GA_TRAIT_FAITH_PER_FOREIGN_CITY_FOLLOWING_RELIGION',				'MODIFIER_PLAYER_RELIGION_ADD_PLAYER_BELIEF_YIELD',		    NULL),
('GA_TRAIT_SCIENCE_PER_CITY_FOLLOWING_RELIGION',					'MODIFIER_PLAYER_RELIGION_ADD_PLAYER_BELIEF_YIELD',		    NULL),
('GA_TRAIT_FAITH_PER_CITY_FOLLOWING_RELIGION',						'MODIFIER_PLAYER_RELIGION_ADD_PLAYER_BELIEF_YIELD',		    NULL);
--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments (ModifierId,					Name,				Value) VALUES
('GA_TRAIT_RIGHTEOUSNESS_OF_FAITH_COMBAT',                  			'ModifierId', 		'GA_TRAIT_RIGHTEOUSNESS_OF_FAITH_COMBAT_MODIFIER'),
('GA_TRAIT_RIGHTEOUSNESS_OF_FAITH_COMBAT_MODIFIER',        			 	'Amount',      		10),
('GA_TRAIT_SCIENCE_PER_FOREIGN_CITY_FOLLOWING_RELIGION',				'BeliefYieldType',	'BELIEF_YIELD_PER_FOREIGN_CITY'),
('GA_TRAIT_SCIENCE_PER_FOREIGN_CITY_FOLLOWING_RELIGION',				'YieldType',	    'YIELD_SCIENCE'),
('GA_TRAIT_SCIENCE_PER_FOREIGN_CITY_FOLLOWING_RELIGION',				'Amount',	        2),
('GA_TRAIT_SCIENCE_PER_FOREIGN_CITY_FOLLOWING_RELIGION',				'PerXItems',    	1),
('GA_TRAIT_FAITH_PER_FOREIGN_CITY_FOLLOWING_RELIGION',					'BeliefYieldType',	'BELIEF_YIELD_PER_FOREIGN_CITY'),
('GA_TRAIT_FAITH_PER_FOREIGN_CITY_FOLLOWING_RELIGION',					'YieldType',	    'YIELD_FAITH'),
('GA_TRAIT_FAITH_PER_FOREIGN_CITY_FOLLOWING_RELIGION',					'Amount',	        2),
('GA_TRAIT_FAITH_PER_FOREIGN_CITY_FOLLOWING_RELIGION',					'PerXItems',    	1),
('GA_TRAIT_SCIENCE_PER_CITY_FOLLOWING_RELIGION',						'BeliefYieldType',	'BELIEF_YIELD_PER_CITY'),
('GA_TRAIT_SCIENCE_PER_CITY_FOLLOWING_RELIGION',						'YieldType',	    'YIELD_SCIENCE'),
('GA_TRAIT_SCIENCE_PER_CITY_FOLLOWING_RELIGION',						'Amount',	        2),
('GA_TRAIT_SCIENCE_PER_CITY_FOLLOWING_RELIGION',						'PerXItems',    	1),
('GA_TRAIT_FAITH_PER_CITY_FOLLOWING_RELIGION',							'BeliefYieldType',	'BELIEF_YIELD_PER_CITY'),
('GA_TRAIT_FAITH_PER_CITY_FOLLOWING_RELIGION',							'YieldType',	    'YIELD_FAITH'),
('GA_TRAIT_FAITH_PER_CITY_FOLLOWING_RELIGION',							'Amount',	        2),
('GA_TRAIT_FAITH_PER_CITY_FOLLOWING_RELIGION',							'PerXItems',    	1);
-- ModifierStrings
INSERT OR REPLACE INTO ModifierStrings (ModifierId,				Context,	Text) VALUES	
('GA_TRAIT_RIGHTEOUSNESS_OF_FAITH_COMBAT_MODIFIER',				'Preview',	'GOLDEN_LOC_RIGHTEOUSNESS_OF_FAITH');