-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_LEADER_SAHEL_MERCHANTS',	'GOLDEN_TRADE_ROUTE_GOLD_DESERT_HILLS_ORIGIN'),
('TRAIT_LEADER_SAHEL_MERCHANTS',	'GOLDEN_TRADE_ROUTE_GOLD_DESERT_MOUNTAIN_ORIGIN'),
('TRAIT_LEADER_SAHEL_MERCHANTS',	'GOLDEN_TRADE_ECONOMIC_QUEST'),
-- ('TRAIT_CIVILIZATION_MALI_GOLD_DESERT',	'GOLDEN_TRAIT_DESERT_CITY_CENTER_PRODUCTION'),
-- ('TRAIT_CIVILIZATION_MALI_GOLD_DESERT',	'GOLDEN_TRAIT_DESERT_HILLS_CITY_CENTER_PRODUCTION'),
('TRAIT_CIVILIZATION_MALI_GOLD_DESERT',	'GOLDEN_TRAIT_MALI_FREE_RESOURCE_GOLD'),
('TRAIT_CIVILIZATION_MALI_GOLD_DESERT',	'GOLDEN_TRAIT_MALI_FREE_RESOURCE_SALT'),
('TRAIT_CIVILIZATION_MALI_GOLD_DESERT',	'GOLDEN_TRAIT_DESERT_CITY_CENTER_GOLD'),
('TRAIT_CIVILIZATION_MALI_GOLD_DESERT',	'GOLDEN_TRAIT_DESERT_HILLS_CITY_CENTER_GOLD'),
('TRAIT_CIVILIZATION_MALI_GOLD_DESERT',	'GOLDEN_TRAIT_DUST_STORM_GRADIENT_PREVENTION'),
('TRAIT_CIVILIZATION_MALI_GOLD_DESERT',	'GOLDEN_TRAIT_DUST_STORM_HABOOB_PREVENTION'),
('TRAIT_CIVILIZATION_MALI_GOLD_DESERT',	'GOLDEN_TRAIT_DUST_STORM_GRADIENT_DOUBLE_DAMAGE'),
('TRAIT_CIVILIZATION_MALI_GOLD_DESERT',	'GOLDEN_TRAIT_DUST_STORM_HABOOB_DOUBLE_DAMAGE');
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_MALI_GOLD_DESERT' AND ModifierId = 'TRAIT_PURCHASE_COMMERCIAL_HUB_BUILDINGS_FAITH';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_MALI_GOLD_DESERT' AND ModifierId = 'TRAIT_MALI_MINES_PRODUCTION';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_MALI_GOLD_DESERT' AND ModifierId = 'TRAIT_MALI_MINES_GOLD';
--UA改成UA
DELETE FROM DistrictModifiers WHERE DistrictType = 'DISTRICT_SUGUBA' AND ModifierId = 'SUGUBA_CHEAPER_BUILDING_PURCHASE';
DELETE FROM DistrictModifiers WHERE DistrictType = 'DISTRICT_SUGUBA' AND ModifierId = 'SUGUBA_CHEAPER_DISTRICT_PURCHASE';
DELETE FROM DistrictModifiers WHERE DistrictType = 'DISTRICT_SUGUBA' AND ModifierId = 'SUGUBA_CHEAPER_UNIT_PURCHASE';
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_CIVILIZATION_MALI_GOLD_DESERT',	'GOLDEN_SUGUBA_CHEAPER_BUILDING_PURCHASE'),
('TRAIT_CIVILIZATION_MALI_GOLD_DESERT',	'GOLDEN_SUGUBA_CHEAPER_DISTRICT_PURCHASE'),
('TRAIT_CIVILIZATION_MALI_GOLD_DESERT',	'GOLDEN_SUGUBA_CHEAPER_UNIT_PURCHASE');
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
('GOLDEN_TRADE_ROUTE_GOLD_DESERT_HILLS_ORIGIN',      	'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_PER_TERRAIN_INTERNATIONAL', 0, 0, NULL),
('GOLDEN_TRADE_ROUTE_GOLD_DESERT_MOUNTAIN_ORIGIN',   	'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_PER_TERRAIN_INTERNATIONAL', 0, 0, NULL),
('GOLDEN_TRADE_ECONOMIC_QUEST',                      	'MODIFIER_PLAYER_ADJUST_PLAYER_ERA_SCORE_PER_TRADE_ROUTE_COMPLETED',  0, 0, NULL),
-- ('GOLDEN_TRAIT_DESERT_CITY_CENTER_PRODUCTION',       'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY', 0, 0, NULL),
-- ('GOLDEN_TRAIT_DESERT_HILLS_CITY_CENTER_PRODUCTION', 'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY', 0, 0, NULL),
('GOLDEN_TRAIT_MALI_FREE_RESOURCE_GOLD',				'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT',				0, 0, NULL),
('GOLDEN_TRAIT_MALI_FREE_RESOURCE_SALT',				'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT',				0, 0, 	NULL),
('GOLDEN_TRAIT_DESERT_CITY_CENTER_GOLD',             	'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY', 0, 0, NULL),
('GOLDEN_TRAIT_DESERT_HILLS_CITY_CENTER_GOLD',       	'MODIFIER_PLAYER_CITIES_TERRAIN_ADJACENCY', 0, 0, NULL),
('GOLDEN_TRAIT_DUST_STORM_GRADIENT_PREVENTION',       	'MODIFIER_PLAYER_ADJUST_RANDOM_EVENT_NO_UNIT_DAMAGE', 0, 0, NULL),
('GOLDEN_TRAIT_DUST_STORM_HABOOB_PREVENTION',         	'MODIFIER_PLAYER_ADJUST_RANDOM_EVENT_NO_UNIT_DAMAGE', 0, 0, NULL),
('GOLDEN_TRAIT_DUST_STORM_GRADIENT_DOUBLE_DAMAGE',    	'MODIFIER_PLAYER_ADJUST_RANDOM_EVENT_MODIFIED_DAMAGE_OPPOSING_PLAYER', 0, 0, NULL),
('GOLDEN_TRAIT_DUST_STORM_HABOOB_DOUBLE_DAMAGE',      	'MODIFIER_PLAYER_ADJUST_RANDOM_EVENT_MODIFIED_DAMAGE_OPPOSING_PLAYER', 0, 0, NULL);
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
('GOLDEN_SUGUBA_CHEAPER_BUILDING_PURCHASE',          'MODIFIER_PLAYER_CITIES_ADJUST_ALL_BUILDINGS_PURCHASE_COST',  		   0, 0, NULL),
('GOLDEN_SUGUBA_CHEAPER_DISTRICT_PURCHASE',          'GOLDEN_MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PURCHASE_COST',   0, 0, NULL),
('GOLDEN_SUGUBA_CHEAPER_UNIT_PURCHASE',              'MODIFIER_PLAYER_CITIES_ADJUST_UNITS_PURCHASE_COST',  	  			   0, 0, NULL);
-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_TRADE_ROUTE_GOLD_DESERT_HILLS_ORIGIN',					            'YieldType',	    'YIELD_GOLD'),
('GOLDEN_TRADE_ROUTE_GOLD_DESERT_HILLS_ORIGIN',					            'Amount',	        1),
('GOLDEN_TRADE_ROUTE_GOLD_DESERT_HILLS_ORIGIN',					            'Origin',	        1),
('GOLDEN_TRADE_ROUTE_GOLD_DESERT_HILLS_ORIGIN',					            'TerrainType',	    'TERRAIN_DESERT_HILLS'),
('GOLDEN_TRADE_ROUTE_GOLD_DESERT_MOUNTAIN_ORIGIN',					        'YieldType',	    'YIELD_GOLD'),
('GOLDEN_TRADE_ROUTE_GOLD_DESERT_MOUNTAIN_ORIGIN',					        'Amount',	        1),
('GOLDEN_TRADE_ROUTE_GOLD_DESERT_MOUNTAIN_ORIGIN',					        'Origin',	        1),
('GOLDEN_TRADE_ROUTE_GOLD_DESERT_MOUNTAIN_ORIGIN',					        'TerrainType',	    'TERRAIN_DESERT_MOUNTAIN'),
('GOLDEN_TRADE_ECONOMIC_QUEST',					                            'Amount',	        1),
-- ('GOLDEN_TRAIT_DESERT_CITY_CENTER_PRODUCTION',					            'YieldType',	    'YIELD_PRODUCTION'),
-- ('GOLDEN_TRAIT_DESERT_CITY_CENTER_PRODUCTION',					            'Amount',	        1),
-- ('GOLDEN_TRAIT_DESERT_CITY_CENTER_PRODUCTION',					            'Description',	    'LOC_DISTRICT_DESERT_PRODUCTION'),
-- ('GOLDEN_TRAIT_DESERT_CITY_CENTER_PRODUCTION',					            'TerrainType',	    'TERRAIN_DESERT'),
-- ('GOLDEN_TRAIT_DESERT_CITY_CENTER_PRODUCTION',					            'DistrictType',	    'DISTRICT_CITY_CENTER'),
-- ('GOLDEN_TRAIT_DESERT_HILLS_CITY_CENTER_PRODUCTION',					    'YieldType',	    'YIELD_PRODUCTION'),
-- ('GOLDEN_TRAIT_DESERT_HILLS_CITY_CENTER_PRODUCTION',					    'Amount',	        1),
-- ('GOLDEN_TRAIT_DESERT_HILLS_CITY_CENTER_PRODUCTION',					    'Description',	    'LOC_DISTRICT_DESERT_PRODUCTION'),
-- ('GOLDEN_TRAIT_DESERT_HILLS_CITY_CENTER_PRODUCTION',					    'TerrainType',	    'TERRAIN_DESERT_HILLS'),
-- ('GOLDEN_TRAIT_DESERT_HILLS_CITY_CENTER_PRODUCTION',					    'DistrictType',	    'DISTRICT_CITY_CENTER'),
('GOLDEN_TRAIT_MALI_FREE_RESOURCE_GOLD',									'ResourceType',	'RESOURCE_GOLD'),
('GOLDEN_TRAIT_MALI_FREE_RESOURCE_GOLD',									'Amount',		10),
('GOLDEN_TRAIT_MALI_FREE_RESOURCE_SALT',									'ResourceType',	'RESOURCE_SALT'),
('GOLDEN_TRAIT_MALI_FREE_RESOURCE_SALT',									'Amount',		10),
('GOLDEN_TRAIT_DESERT_CITY_CENTER_GOLD',					                'YieldType',	    'YIELD_GOLD'),
('GOLDEN_TRAIT_DESERT_CITY_CENTER_GOLD',					                'Amount',	        1),
('GOLDEN_TRAIT_DESERT_CITY_CENTER_GOLD',					                'Description',	    'LOC_DISTRICT_DESERT_GOLD'),
('GOLDEN_TRAIT_DESERT_CITY_CENTER_GOLD',					                'TerrainType',	    'TERRAIN_DESERT'),
('GOLDEN_TRAIT_DESERT_CITY_CENTER_GOLD',					                'DistrictType',	    'DISTRICT_CITY_CENTER'),
('GOLDEN_TRAIT_DESERT_HILLS_CITY_CENTER_GOLD',					            'YieldType',	    'YIELD_GOLD'),
('GOLDEN_TRAIT_DESERT_HILLS_CITY_CENTER_GOLD',					            'Amount',	        1),
('GOLDEN_TRAIT_DESERT_HILLS_CITY_CENTER_GOLD',					            'Description',	    'LOC_DISTRICT_DESERT_GOLD'),
('GOLDEN_TRAIT_DESERT_HILLS_CITY_CENTER_GOLD',					            'TerrainType',	    'TERRAIN_DESERT_HILLS'),
('GOLDEN_TRAIT_DESERT_HILLS_CITY_CENTER_GOLD',					            'DistrictType',	    'DISTRICT_CITY_CENTER'),
('GOLDEN_TRAIT_DUST_STORM_GRADIENT_PREVENTION',					            'RandomEventType',	'RANDOM_EVENT_DUST_STORM_GRADIENT'),
('GOLDEN_TRAIT_DUST_STORM_GRADIENT_PREVENTION',					            'NoDamage',	        1),
('GOLDEN_TRAIT_DUST_STORM_HABOOB_PREVENTION',					            'RandomEventType',	'RANDOM_EVENT_DUST_STORM_HABOOB'),
('GOLDEN_TRAIT_DUST_STORM_HABOOB_PREVENTION',					            'NoDamage',	        1),
('GOLDEN_TRAIT_DUST_STORM_GRADIENT_DOUBLE_DAMAGE',					        'RandomEventType',	'RANDOM_EVENT_DUST_STORM_GRADIENT'),
('GOLDEN_TRAIT_DUST_STORM_GRADIENT_DOUBLE_DAMAGE',					        'Amount',	        100),
('GOLDEN_TRAIT_DUST_STORM_HABOOB_DOUBLE_DAMAGE',					        'RandomEventType',	'RANDOM_EVENT_DUST_STORM_HABOOB'),
('GOLDEN_TRAIT_DUST_STORM_HABOOB_DOUBLE_DAMAGE',					        'Amount',	        100);
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_SUGUBA_CHEAPER_BUILDING_PURCHASE',					                 'Amount',	        20),
('GOLDEN_SUGUBA_CHEAPER_DISTRICT_PURCHASE',					                 'Amount',	        20),
('GOLDEN_SUGUBA_CHEAPER_UNIT_PURCHASE',					                     'Amount',	        20),
('GOLDEN_SUGUBA_CHEAPER_UNIT_PURCHASE',					                     'IncludeCivilian',	1);
UPDATE ModifierArguments SET  Value = 2
WHERE ModifierId = 'GOLDEN_AGE_TRADE_ROUTE' AND Name = 'Amount';
UPDATE ModifierArguments SET  Value = -25
WHERE ModifierId = 'TRAIT_LESS_BUILDING_PRODUCTION' AND Name = 'Amount';
UPDATE ModifierArguments SET  Value = -25
WHERE ModifierId = 'TRAIT_LESS_UNIT_PRODUCTION' AND Name = 'Amount';