-----------------------------------------------
-- ExcludedAdjacencies
-----------------------------------------------
INSERT OR REPLACE INTO ExcludedAdjacencies (YieldChangeId, 			TraitType) VALUES	
('District_Science',	    'TRAIT_CIVILIZATION_GROTE_RIVIEREN'),
('District_Faith',	        'TRAIT_CIVILIZATION_GROTE_RIVIEREN'),
('District_Gold',	        'TRAIT_CIVILIZATION_GROTE_RIVIEREN'),
('District_Culture',	    'TRAIT_CIVILIZATION_GROTE_RIVIEREN'),
('District_Production',	    'TRAIT_CIVILIZATION_GROTE_RIVIEREN'),
('DISTRICT_FOOD',	        'TRAIT_CIVILIZATION_GROTE_RIVIEREN'),
('CITY_CENTER_CULTURE',	    'TRAIT_CIVILIZATION_GROTE_RIVIEREN'),
('CITY_CENTER_FAITH',	    'TRAIT_CIVILIZATION_GROTE_RIVIEREN'),
('CITY_CENTER_GOLD',	    'TRAIT_CIVILIZATION_GROTE_RIVIEREN'),
('CITY_CENTER_PRODUCTION',	'TRAIT_CIVILIZATION_GROTE_RIVIEREN'),
('CITY_CENTER_SCIENCE',	    'TRAIT_CIVILIZATION_GROTE_RIVIEREN'),
('CITY_CENTER_FOOD',	    'TRAIT_CIVILIZATION_GROTE_RIVIEREN');

UPDATE Traits SET  Description = 'LOC_TRAIT_CIVILIZATION_GROTE_RIVIEREN_EXPANSION2_DESCRIPTION'
WHERE TraitType = 'TRAIT_CIVILIZATION_GROTE_RIVIEREN';
------
--UA--
------
--TraitModifiers
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_GROTE_RIVIEREN';
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_CIVILIZATION_GROTE_RIVIEREN',	'TRAIT_CAMPUS_RIVER_ADJACENCY'),--Base game
('TRAIT_CIVILIZATION_GROTE_RIVIEREN',	'TRAIT_INDUSTRIAL_ZONE_RIVER_ADJACENCY'),--Base game
('TRAIT_CIVILIZATION_GROTE_RIVIEREN',	'TRAIT_THEATER_DISTRICT_RIVER_ADJACENCY'),--Base game
('TRAIT_CIVILIZATION_GROTE_RIVIEREN',	'GOLDEN_TRAIT_GROTE_RIVIEREN_COMMERCIAL_HUB_ADJACENCYGOLD'),
('TRAIT_CIVILIZATION_GROTE_RIVIEREN',	'GOLDEN_TRAIT_GROTE_RIVIEREN_HARBOR_ADJACENCYGOLD'),
('TRAIT_CIVILIZATION_GROTE_RIVIEREN',	'GOLDEN_TRAIT_GROTE_RIVIEREN_HOLY_SITE_ADJACENCYFAITH'),
('TRAIT_CIVILIZATION_GROTE_RIVIEREN',	'GA_TRAIT_GROTE_RIVIEREN_FLOODPLAINS_GRASSLAND_APPEAL'),
('TRAIT_CIVILIZATION_GROTE_RIVIEREN',	'GA_TRAIT_GROTE_RIVIEREN_FLOODPLAINS_PLAINS_APPEAL');
INSERT OR REPLACE INTO TraitModifiers (TraitType,						ModifierId)
SELECT	'TRAIT_CIVILIZATION_GROTE_RIVIEREN',		'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_DOUBLE_' ||YieldType FROM Terrain_YieldChanges;
INSERT OR REPLACE INTO TraitModifiers (TraitType,						ModifierId)
SELECT	'TRAIT_CIVILIZATION_GROTE_RIVIEREN',		'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_PRODUCTION' FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO TraitModifiers (TraitType,						ModifierId)
SELECT	'TRAIT_CIVILIZATION_GROTE_RIVIEREN',		'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_GOLD' FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO TraitModifiers (TraitType,						ModifierId)
SELECT	'TRAIT_CIVILIZATION_GROTE_RIVIEREN',		'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_FAITH' FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO TraitModifiers (TraitType,						ModifierId)
SELECT	'TRAIT_CIVILIZATION_GROTE_RIVIEREN',		'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_FOOD' FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO TraitModifiers (TraitType,						ModifierId)
SELECT	'TRAIT_CIVILIZATION_GROTE_RIVIEREN',		'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_SCIENCE' FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO TraitModifiers (TraitType,						ModifierId)
SELECT	'TRAIT_CIVILIZATION_GROTE_RIVIEREN',		'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_CULTURE' FROM Terrains WHERE Mountain=1;
----Modifiers
INSERT OR REPLACE INTO Modifiers (ModifierId,					ModifierType,											SubjectRequirementSetId) VALUES
('GOLDEN_TRAIT_GROTE_RIVIEREN_COMMERCIAL_HUB_ADJACENCYGOLD',	'MODIFIER_PLAYER_CITIES_RIVER_ADJACENCY',	                    NULL),
('GOLDEN_TRAIT_GROTE_RIVIEREN_HARBOR_ADJACENCYGOLD',			'MODIFIER_PLAYER_CITIES_RIVER_ADJACENCY',	                    NULL),
('GOLDEN_TRAIT_GROTE_RIVIEREN_HOLY_SITE_ADJACENCYFAITH',		'MODIFIER_PLAYER_CITIES_RIVER_ADJACENCY',	                    NULL),
('GA_TRAIT_GROTE_RIVIEREN_FLOODPLAINS_GRASSLAND_APPEAL',		'MODIFIER_PLAYER_CITIES_ADJUST_FEATURE_APPEAL_MODIFIER',	    NULL),
('GA_TRAIT_GROTE_RIVIEREN_FLOODPLAINS_PLAINS_APPEAL',	    	'MODIFIER_PLAYER_CITIES_ADJUST_FEATURE_APPEAL_MODIFIER',	    NULL);
INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,								SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_DOUBLE_' ||YieldType,		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		'GOLDEN_NETHERLAND_PLOT_IS_' ||TerrainType|| '_ADJACENT_TO_WATER_DISTRICT_REQUIREMENTS' FROM Terrain_YieldChanges;
INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,								SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_PRODUCTION',	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		'GOLDEN_NETHERLAND_PLOT_IS_MOUNTAIN_' ||TerrainType|| '_REQUIREMENTS' FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,								SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_GOLD',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		'GOLDEN_NETHERLAND_PLOT_IS_MOUNTAIN_' ||TerrainType|| '_REQUIREMENTS' FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,								SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_FAITH',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		'GOLDEN_NETHERLAND_PLOT_IS_MOUNTAIN_' ||TerrainType|| '_REQUIREMENTS' FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,								SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_FOOD',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		'GOLDEN_NETHERLAND_PLOT_IS_MOUNTAIN_' ||TerrainType|| '_REQUIREMENTS' FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,								SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_SCIENCE',	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		'GOLDEN_NETHERLAND_PLOT_IS_MOUNTAIN_' ||TerrainType|| '_REQUIREMENTS' FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO Modifiers (ModifierId,										ModifierType,								SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_CULTURE',	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		'GOLDEN_NETHERLAND_PLOT_IS_MOUNTAIN_' ||TerrainType|| '_REQUIREMENTS' FROM Terrains WHERE Mountain=1;
--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments (ModifierId,						Name,				Value) VALUES
('GOLDEN_TRAIT_GROTE_RIVIEREN_COMMERCIAL_HUB_ADJACENCYGOLD',                'Description', 		'LOC_DISTRICT_RIVER_GOLD'),
('GOLDEN_TRAIT_GROTE_RIVIEREN_COMMERCIAL_HUB_ADJACENCYGOLD',                'YieldType',      	'YIELD_GOLD'),
('GOLDEN_TRAIT_GROTE_RIVIEREN_COMMERCIAL_HUB_ADJACENCYGOLD',                'DistrictType', 	'DISTRICT_COMMERCIAL_HUB'),
('GOLDEN_TRAIT_GROTE_RIVIEREN_COMMERCIAL_HUB_ADJACENCYGOLD',                'Amount',      		2),
('GOLDEN_TRAIT_GROTE_RIVIEREN_HARBOR_ADJACENCYGOLD',                		'Description', 		'LOC_DISTRICT_RIVER_GOLD'),
('GOLDEN_TRAIT_GROTE_RIVIEREN_HARBOR_ADJACENCYGOLD',                		'YieldType',      	'YIELD_GOLD'),
('GOLDEN_TRAIT_GROTE_RIVIEREN_HARBOR_ADJACENCYGOLD',                		'DistrictType', 	'DISTRICT_HARBOR'),
('GOLDEN_TRAIT_GROTE_RIVIEREN_HARBOR_ADJACENCYGOLD',                		'Amount',      		2),
('GOLDEN_TRAIT_GROTE_RIVIEREN_HOLY_SITE_ADJACENCYFAITH',                	'Description', 		'LOC_DISTRICT_RIVER_GOLD'),
('GOLDEN_TRAIT_GROTE_RIVIEREN_HOLY_SITE_ADJACENCYFAITH',                	'YieldType',      	'YIELD_FAITH'),
('GOLDEN_TRAIT_GROTE_RIVIEREN_HOLY_SITE_ADJACENCYFAITH',                	'DistrictType', 	'DISTRICT_HOLY_SITE'),
('GOLDEN_TRAIT_GROTE_RIVIEREN_HOLY_SITE_ADJACENCYFAITH',                	'Amount',      		2),
('GA_TRAIT_GROTE_RIVIEREN_FLOODPLAINS_GRASSLAND_APPEAL',                    'FeatureType', 		'FEATURE_FLOODPLAINS_GRASSLAND'),
('GA_TRAIT_GROTE_RIVIEREN_FLOODPLAINS_GRASSLAND_APPEAL',                    'Amount',      		2),
('GA_TRAIT_GROTE_RIVIEREN_FLOODPLAINS_PLAINS_APPEAL',                     	'FeatureType', 		'FEATURE_FLOODPLAINS_PLAINS'),
('GA_TRAIT_GROTE_RIVIEREN_FLOODPLAINS_PLAINS_APPEAL',                     	'Amount',      		2);
INSERT OR REPLACE INTO ModifierArguments (ModifierId,												Name,			Value)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_DOUBLE_' ||YieldType,			'YieldType',	YieldType			FROM Terrain_YieldChanges;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,												Name,			Value)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_DOUBLE_' ||YieldType,			'Amount',		YieldChange 		FROM Terrain_YieldChanges;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,												Name,			Value)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_PRODUCTION',		'YieldType',	'YIELD_PRODUCTION' 	FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,												Name,			Value)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_PRODUCTION',		'Amount',		-100 			 	FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,												Name,			Value)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_GOLD',			'YieldType',	'YIELD_GOLD' 		FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,												Name,			Value)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_GOLD',			'Amount',		-100 			 	FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,												Name,			Value)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_FAITH',			'YieldType',	'YIELD_FAITH' 		FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,												Name,			Value)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_FAITH',			'Amount',		-100 			 	FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,												Name,			Value)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_FOOD',			'YieldType',	'YIELD_FOOD' 		FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,												Name,			Value)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_FOOD',			'Amount',		-100 			 	FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,												Name,			Value)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_SCIENCE',		'YieldType',	'YIELD_SCIENCE' 	FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,												Name,			Value)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_SCIENCE',		'Amount',		-100 			 	FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,												Name,			Value)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_CULTURE',		'YieldType',	'YIELD_CULTURE' 	FROM Terrains WHERE Mountain=1;
INSERT OR REPLACE INTO ModifierArguments (ModifierId,												Name,			Value)
SELECT	'GOLDEN_TRAIT_GROTE_RIVIEREN_' ||TerrainType|| '_MOUNTAIN_LESS_CULTURE',		'Amount',		-100 			 	FROM Terrains WHERE Mountain=1;
--RequirementSets
INSERT OR REPLACE INTO RequirementSets (RequirementSetId,							RequirementSetType)
SELECT	'GOLDEN_NETHERLAND_PLOT_IS_' ||TerrainType|| '_ADJACENT_TO_WATER_DISTRICT_REQUIREMENTS',	'REQUIREMENTSET_TEST_ALL' FROM Terrains;
INSERT OR REPLACE INTO RequirementSets (RequirementSetId,							RequirementSetType)
SELECT	'GOLDEN_NETHERLAND_PLOT_IS_MOUNTAIN_' ||TerrainType|| '_REQUIREMENTS',	'REQUIREMENTSET_TEST_ANY' FROM Terrains WHERE Mountain=1;
--RequirementSetRequirements
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,								RequirementId)
SELECT	'GOLDEN_NETHERLAND_PLOT_IS_' ||TerrainType|| '_ADJACENT_TO_WATER_DISTRICT_REQUIREMENTS',	'GOLDEN_NETHERLAND_REQUIRES_PLOT_IS_ADJACENT_TO_WATER_DISTRICT' FROM Terrains;
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,								RequirementId)
SELECT	'GOLDEN_NETHERLAND_PLOT_IS_' ||TerrainType|| '_ADJACENT_TO_WATER_DISTRICT_REQUIREMENTS',	'GOLDEN_NETHERLAND_REQUIRES_PLOT_IS_' ||TerrainType  FROM Terrains;
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId,								RequirementId)
SELECT	'GOLDEN_NETHERLAND_PLOT_IS_MOUNTAIN_' ||TerrainType|| '_REQUIREMENTS',						'GOLDEN_NETHERLAND_REQUIRES_PLOT_IS_MOUNTAIN_' ||TerrainType  FROM Terrains WHERE Mountain=1;
--Requirements
INSERT OR REPLACE INTO 		Requirements (RequirementId,				            RequirementType)
VALUES					    ('GOLDEN_NETHERLAND_REQUIRES_PLOT_IS_ADJACENT_TO_WATER_DISTRICT',	'REQUIREMENT_REQUIREMENTSET_IS_MET');
INSERT OR REPLACE INTO Requirements (RequirementId,									RequirementType)
SELECT	'GOLDEN_NETHERLAND_REQUIRES_PLOT_IS_' ||TerrainType,	'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES' FROM Terrains;
INSERT OR REPLACE INTO Requirements (RequirementId,									RequirementType)
SELECT	'GOLDEN_NETHERLAND_REQUIRES_PLOT_IS_MOUNTAIN_' ||TerrainType,	'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES' FROM Terrains WHERE Mountain=1;
--RequirementArguments
INSERT OR REPLACE INTO 		RequirementArguments (RequirementId,		                Name,			        Value)
VALUES					    ('GOLDEN_NETHERLAND_REQUIRES_PLOT_IS_ADJACENT_TO_WATER_DISTRICT',		'RequirementSetId',		'GOLDEN_NETHERLAND_PLOT_IS_ADJACENT_TO_WATER_DISTRICT_REQUIREMENTS');
INSERT OR REPLACE INTO RequirementArguments (RequirementId,									Name,			Value)
SELECT	'GOLDEN_NETHERLAND_REQUIRES_PLOT_IS_' ||TerrainType,	'TerrainType',	TerrainType FROM Terrains;
INSERT OR REPLACE INTO RequirementArguments (RequirementId,									Name,			Value)
SELECT	'GOLDEN_NETHERLAND_REQUIRES_PLOT_IS_MOUNTAIN_' ||TerrainType,	'TerrainType',	TerrainType FROM Terrains WHERE Mountain=1;
--RequirementSets
INSERT OR REPLACE INTO RequirementSets 				(RequirementSetId ,     RequirementSetType) 	VALUES
('GOLDEN_NETHERLAND_PLOT_IS_ADJACENT_TO_WATER_DISTRICT_REQUIREMENTS' , 			'REQUIREMENTSET_TEST_ANY');
--RequirementSetRequirements
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId ,   RequirementId) 			VALUES
('GOLDEN_NETHERLAND_PLOT_IS_ADJACENT_TO_WATER_DISTRICT_REQUIREMENTS' , 		  	'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_AQUEDUCT'),
('GOLDEN_NETHERLAND_PLOT_IS_ADJACENT_TO_WATER_DISTRICT_REQUIREMENTS' , 		  	'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_CANAL'),
('GOLDEN_NETHERLAND_PLOT_IS_ADJACENT_TO_WATER_DISTRICT_REQUIREMENTS' , 		  	'GOLDEN_REQUIRES_PLOT_IS_ADJACENT_TO_DISTRICT_DAM');
------
--LA--
------
--TraitModifiers
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_RADIO_ORANJE';
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_RADIO_ORANJE',	'TRAIT_CULTURE_FROM_INTERNATIONAL_TRADE_ROUTES'),--Base game
('TRAIT_RADIO_ORANJE',	'TRAIT_CULTURE_FROM_INCOMING_TRADE_ROUTES'),--Base game
('TRAIT_RADIO_ORANJE',	'GOLDEN_TRAIT_GOLD_FROM_INTERNATIONAL_TRADE_ROUTES'),
('TRAIT_RADIO_ORANJE',	'GOLDEN_TRAIT_GOLD_FROM_INCOMING_TRADE_ROUTES'),
('TRAIT_RADIO_ORANJE',	'GOLDEN_TRAIT_RADIO_ORANJE_WAR_GOLD'),
('TRAIT_RADIO_ORANJE',	'GOLDEN_TRAIT_RADIO_ORANJE_WAR_CULTURE'),
('TRAIT_RADIO_ORANJE',	'GOLDEN_TRAIT_RADIO_ORANJE_WAR_ALWAYS_LOYAL'),
('TRAIT_RADIO_ORANJE',	'GOLDEN_TRAIT_RADIO_ORANJE_SLOT_DIPLOMATIC1'),
('TRAIT_RADIO_ORANJE',	'GOLDEN_TRAIT_RADIO_ORANJE_SLOT_DIPLOMATIC2');
----Modifiers
INSERT OR REPLACE INTO Modifiers (ModifierId,	ModifierType,											SubjectRequirementSetId) VALUES
('GOLDEN_TRAIT_GOLD_FROM_INTERNATIONAL_TRADE_ROUTES',	'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	                    NULL),
('GOLDEN_TRAIT_GOLD_FROM_INCOMING_TRADE_ROUTES',		'MODIFIER_PLAYER_CITIES_ADJUST_TRADE_ROUTE_YIELD_FROM_OTHERS',	                    NULL),
('GOLDEN_TRAIT_RADIO_ORANJE_WAR_GOLD',			'MODIFIER_PLAYER_ADD_DIPLOMATIC_YIELD_MODIFIER',	                    NULL),
('GOLDEN_TRAIT_RADIO_ORANJE_WAR_CULTURE',		'MODIFIER_PLAYER_ADD_DIPLOMATIC_YIELD_MODIFIER',	                    NULL),
('GOLDEN_TRAIT_RADIO_ORANJE_WAR_ALWAYS_LOYAL',	'MODIFIER_PLAYER_CITIES_ADJUST_ALWAYS_LOYAL',	                   		'GOLDEN_PLAYER_IS_AT_WAR_WITH_MAJOR_REQUIREMENTS'),
('GOLDEN_TRAIT_RADIO_ORANJE_SLOT_DIPLOMATIC1',	'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',	            'GOLDEN_PLAYER_HAS_RENAISSANCE_ANY_TECH_CIVIC_REQUIREMENTS'),
('GOLDEN_TRAIT_RADIO_ORANJE_SLOT_DIPLOMATIC2',	'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',	            'GOLDEN_PLAYER_HAS_RENAISSANCE_ANY_TECH_CIVIC_REQUIREMENTS');
--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments (ModifierId,		Name,						Value) VALUES
('GOLDEN_TRAIT_GOLD_FROM_INTERNATIONAL_TRADE_ROUTES',       'YieldType', 				'YIELD_GOLD'),
('GOLDEN_TRAIT_GOLD_FROM_INTERNATIONAL_TRADE_ROUTES',       'Amount',      				2),
('GOLDEN_TRAIT_GOLD_FROM_INCOMING_TRADE_ROUTES',            'YieldType', 				'YIELD_GOLD'),
('GOLDEN_TRAIT_GOLD_FROM_INCOMING_TRADE_ROUTES',            'Amount',      				2),
('GOLDEN_TRAIT_RADIO_ORANJE_WAR_GOLD',                    	'DiplomaticYieldSource', 	'WAR_DECLARATION_RECEIVED'),
('GOLDEN_TRAIT_RADIO_ORANJE_WAR_GOLD',                    	'TurnsActive',      		10),
('GOLDEN_TRAIT_RADIO_ORANJE_WAR_GOLD',                    	'YieldType', 				'YIELD_GOLD'),
('GOLDEN_TRAIT_RADIO_ORANJE_WAR_GOLD',                    	'Amount',      				50),
('GOLDEN_TRAIT_RADIO_ORANJE_WAR_CULTURE',                   'DiplomaticYieldSource', 	'WAR_DECLARATION_RECEIVED'),
('GOLDEN_TRAIT_RADIO_ORANJE_WAR_CULTURE',                   'TurnsActive',      		10),
('GOLDEN_TRAIT_RADIO_ORANJE_WAR_CULTURE',                   'YieldType', 				'YIELD_CULTURE'),
('GOLDEN_TRAIT_RADIO_ORANJE_WAR_CULTURE',                   'Amount',      				50),
('GOLDEN_TRAIT_RADIO_ORANJE_WAR_ALWAYS_LOYAL',              'AlwaysLoyal',      		1),
('GOLDEN_TRAIT_RADIO_ORANJE_SLOT_DIPLOMATIC1',              'GovernmentSlotType', 		'SLOT_DIPLOMATIC'),
('GOLDEN_TRAIT_RADIO_ORANJE_SLOT_DIPLOMATIC2',              'GovernmentSlotType', 		'SLOT_DIPLOMATIC');
UPDATE ModifierArguments SET  Value = 2
WHERE ModifierId = 'TRAIT_CULTURE_FROM_INTERNATIONAL_TRADE_ROUTES' AND Name = 'Amount';
UPDATE ModifierArguments SET  Value = 2
WHERE ModifierId = 'TRAIT_CULTURE_FROM_INCOMING_TRADE_ROUTES' AND Name = 'Amount';
--RequirementSets
INSERT OR REPLACE INTO RequirementSets 				(RequirementSetId , RequirementSetType) 	VALUES 		
('GOLDEN_PLAYER_HAS_RENAISSANCE_ANY_TECH_CIVIC_REQUIREMENTS' , 		'REQUIREMENTSET_TEST_ALL');
--RequirementSetRequirements
INSERT OR REPLACE INTO RequirementSetRequirements 	(RequirementSetId , RequirementId) 			VALUES 		
('GOLDEN_PLAYER_HAS_RENAISSANCE_ANY_TECH_CIVIC_REQUIREMENTS' , 		'GOLDEN_REQUIRES_PLAYER_HAS_RENAISSANCE_ANY_TECH'),					
('GOLDEN_PLAYER_HAS_RENAISSANCE_ANY_TECH_CIVIC_REQUIREMENTS' , 		'GOLDEN_REQUIRES_PLAYER_HAS_RENAISSANCE_ANY_CIVIC');
--Requirements
INSERT OR REPLACE INTO 		Requirements (RequirementId,				   RequirementType) VALUES						
('GOLDEN_REQUIRES_PLAYER_HAS_RENAISSANCE_ANY_TECH',		    'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('GOLDEN_REQUIRES_PLAYER_HAS_RENAISSANCE_ANY_CIVIC',		'REQUIREMENT_REQUIREMENTSET_IS_MET');
-- RequirementArguments
INSERT OR REPLACE INTO 		RequirementArguments (RequirementId,		                Name,			        Value) VALUES					    
('GOLDEN_REQUIRES_PLAYER_HAS_RENAISSANCE_ANY_TECH',		'RequirementSetId',		'GOLDEN_PLAYER_HAS_RENAISSANCE_TECH_REQUIREMENTS'),
('GOLDEN_REQUIRES_PLAYER_HAS_RENAISSANCE_ANY_CIVIC',	'RequirementSetId',		'GOLDEN_PLAYER_HAS_RENAISSANCE_CIVIC_REQUIREMENTS');