-----------------------------------------------
-- DistrictModifiers
-----------------------------------------------
DELETE FROM DistrictModifiers WHERE DistrictType = 'DISTRICT_COTHON' AND ModifierId = 'COTHON_SETTLER_PRODUCTION';
-----------------------------------------------
-- TraitModifiers
-----------------------------------------------
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_FOUNDER_CARTHAGE' AND ModifierId = 'DISTRICT_COMPLETE_MOVE_CAPITAL';
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES' AND ModifierId = 'TRAIT_MEDITERRANEAN_COLONIES_GRANT_SETTLERS_ABILITY';
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_LEADER_FOUNDER_CARTHAGE',	'GOLDEN_TRAIT_FOUNDER_CARTHAGE_CAPITAL_DISTRICT_PRODUCTION'),
('TRAIT_LEADER_FOUNDER_CARTHAGE',	'GOLDEN_FOUNDER_CARTHAGE_SETTLER'),
('TRAIT_LEADER_FOUNDER_CARTHAGE',	'GOLDEN_FOUNDER_CARTHAGE_COAST_TRADE_ROUTES_GOLD'),
('TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES',	'GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_CAMPUS'),
('TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES',	'GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_HOLY_SITE'),
('TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES',	'GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_COMMERCIAL_HUB'),
('TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES',	'GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_THEATER'),
('TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES',	'GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_INDUSTRIAL_ZONE'),
('TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES',	'GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_HARBOR'),
('TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES',	'GOLDEN_MEDITERRANEAN_COLONIES_LAND_CAMPUS'),
('TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES',	'GOLDEN_MEDITERRANEAN_COLONIES_LAND_HOLY_SITE'),
('TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES',	'GOLDEN_MEDITERRANEAN_COLONIES_LAND_COMMERCIAL_HUB'),
('TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES',	'GOLDEN_MEDITERRANEAN_COLONIES_LAND_THEATER'),
('TRAIT_CIVILIZATION_MEDITERRANEAN_COLONIES',	'GOLDEN_MEDITERRANEAN_COLONIES_LAND_INDUSTRIAL_ZONE');
-----------------------------------------------
-- Modifiers
-----------------------------------------------
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectStackLimit, Permanent, SubjectRequirementSetId) VALUES	
('GOLDEN_FOUNDER_CARTHAGE_SETTLER',	 'MODIFIER_PLAYER_GRANT_UNIT_IN_CAPITAL', 1, 1, NULL);
INSERT OR REPLACE INTO Modifiers (ModifierId,						ModifierType,								                                    SubjectRequirementSetId) VALUES	
('GOLDEN_TRAIT_FOUNDER_CARTHAGE_CAPITAL_DISTRICT_PRODUCTION',			'GOLDEN_MODIFIER_PLAYER_CAPITAL_CITY_ADJUST_DISTRICT_PRODUCTION_MODIFIER',		        NULL),
('GOLDEN_FOUNDER_CARTHAGE_COAST_TRADE_ROUTES_GOLD',			            'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_PER_TERRAIN_INTERNATIONAL',		            NULL),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_CAMPUS',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_PHOENICIA_DISTRICT_IS_CAMPUS_ADJACENT_TO_COAST_REQUIREMENTS'),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_HOLY_SITE',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_PHOENICIA_DISTRICT_IS_HOLY_SITE_ADJACENT_TO_COAST_REQUIREMENTS'),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_COMMERCIAL_HUB',			    'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_PHOENICIA_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_TO_COAST_REQUIREMENTS'),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_THEATER',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_PHOENICIA_DISTRICT_IS_THEATER_ADJACENT_TO_COAST_REQUIREMENTS'),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_INDUSTRIAL_ZONE',			    'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_PHOENICIA_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_TO_COAST_REQUIREMENTS'),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_HARBOR',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_PHOENICIA_DISTRICT_IS_HARBOR_REQUIREMENTS'),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_CAMPUS',			                'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_PHOENICIA_DISTRICT_IS_CAMPUS_ADJACENT_NOT_TO_COAST_REQUIREMENTS'),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_HOLY_SITE',			            'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_PHOENICIA_DISTRICT_IS_HOLY_SITE_ADJACENT_NOT_TO_COAST_REQUIREMENTS'),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_COMMERCIAL_HUB',			        'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_PHOENICIA_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_NOT_TO_COAST_REQUIREMENTS'),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_THEATER',			                'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_PHOENICIA_DISTRICT_IS_THEATER_ADJACENT_NOT_TO_COAST_REQUIREMENTS'),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_INDUSTRIAL_ZONE',			        'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		            'GOLDEN_PHOENICIA_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_NOT_TO_COAST_REQUIREMENTS');
UPDATE Modifiers SET  ModifierType = 'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY'
WHERE ModifierId = 'TRAIT_FREE_TECH_BOOST_WRITING';
-----------------------------------------------
-- ModifierArguments
-----------------------------------------------
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_TRAIT_FOUNDER_CARTHAGE_CAPITAL_DISTRICT_PRODUCTION',					'Amount',	    100),
('GOLDEN_FOUNDER_CARTHAGE_SETTLER',					                            'UnitType',	    'UNIT_SETTLER'),
('GOLDEN_FOUNDER_CARTHAGE_SETTLER',					                            'Amount',	    1),
('GOLDEN_FOUNDER_CARTHAGE_COAST_TRADE_ROUTES_GOLD',					            'YieldType',	'YIELD_GOLD'),
('GOLDEN_FOUNDER_CARTHAGE_COAST_TRADE_ROUTES_GOLD',					            'Amount',	    1),
('GOLDEN_FOUNDER_CARTHAGE_COAST_TRADE_ROUTES_GOLD',					            'TerrainType',	'TERRAIN_COAST'),
('GOLDEN_FOUNDER_CARTHAGE_COAST_TRADE_ROUTES_GOLD',					            'Origin',	    1),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_CAMPUS',					            'YieldType',	'YIELD_SCIENCE'),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_CAMPUS',					            'Amount',	    100),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_HOLY_SITE',					            'YieldType',	'YIELD_FAITH'),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_HOLY_SITE',					            'Amount',	    100),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_COMMERCIAL_HUB',					    'YieldType',	'YIELD_GOLD'),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_COMMERCIAL_HUB',					    'Amount',	    100),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_THEATER',					            'YieldType',	'YIELD_CULTURE'),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_THEATER',					            'Amount',	    100),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_INDUSTRIAL_ZONE',					    'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_INDUSTRIAL_ZONE',					    'Amount',	    100),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_HARBOR',					            'YieldType',	'YIELD_GOLD'),
('GOLDEN_MEDITERRANEAN_COLONIES_COASTAL_HARBOR',					            'Amount',	    100),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_CAMPUS',					                'YieldType',	'YIELD_SCIENCE'),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_CAMPUS',					                'Amount',	    -100),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_HOLY_SITE',					            'YieldType',	'YIELD_FAITH'),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_HOLY_SITE',					            'Amount',	    -100),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_COMMERCIAL_HUB',					        'YieldType',	'YIELD_GOLD'),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_COMMERCIAL_HUB',					        'Amount',	    -100),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_THEATER',					                'YieldType',	'YIELD_CULTURE'),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_THEATER',					                'Amount',	    -100),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_INDUSTRIAL_ZONE',					        'YieldType',	'YIELD_PRODUCTION'),
('GOLDEN_MEDITERRANEAN_COLONIES_LAND_INDUSTRIAL_ZONE',					        'Amount',	    -100);
UPDATE ModifierArguments SET  Value = 100
WHERE ModifierId = 'PRODUCTION_GOVERNMENT_DISTRICT' AND Name = 'Amount';
-----------------------------------------------
-- RequirementSets
-----------------------------------------------
INSERT OR REPLACE INTO RequirementSets		
(RequirementSetId,							    RequirementSetType) VALUES	
('GOLDEN_PHOENICIA_DISTRICT_IS_CAMPUS_ADJACENT_TO_COAST_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PHOENICIA_DISTRICT_IS_HOLY_SITE_ADJACENT_TO_COAST_REQUIREMENTS',		    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PHOENICIA_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_TO_COAST_REQUIREMENTS',		'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PHOENICIA_DISTRICT_IS_THEATER_ADJACENT_TO_COAST_REQUIREMENTS',		        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PHOENICIA_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_TO_COAST_REQUIREMENTS',		'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PHOENICIA_DISTRICT_IS_HARBOR_REQUIREMENTS',		                        'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PHOENICIA_DISTRICT_IS_CAMPUS_ADJACENT_NOT_TO_COAST_REQUIREMENTS',		    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PHOENICIA_DISTRICT_IS_HOLY_SITE_ADJACENT_NOT_TO_COAST_REQUIREMENTS',		'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PHOENICIA_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_NOT_TO_COAST_REQUIREMENTS',  'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PHOENICIA_DISTRICT_IS_THEATER_ADJACENT_NOT_TO_COAST_REQUIREMENTS',		    'REQUIREMENTSET_TEST_ALL'),
('GOLDEN_PHOENICIA_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_NOT_TO_COAST_REQUIREMENTS',	'REQUIREMENTSET_TEST_ALL');
---------------------------------------------------------------------------------------------------------------
-- RequirementSetRequirements
---------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSetRequirements		
(RequirementSetId,							RequirementId) VALUES	
('GOLDEN_PHOENICIA_DISTRICT_IS_CAMPUS_ADJACENT_TO_COAST_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_CAMPUS'),
('GOLDEN_PHOENICIA_DISTRICT_IS_CAMPUS_ADJACENT_TO_COAST_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_ADJACENT_TO_COAST'),
('GOLDEN_PHOENICIA_DISTRICT_IS_HOLY_SITE_ADJACENT_TO_COAST_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HOLY_SITE'),
('GOLDEN_PHOENICIA_DISTRICT_IS_HOLY_SITE_ADJACENT_TO_COAST_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_ADJACENT_TO_COAST'),
('GOLDEN_PHOENICIA_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_TO_COAST_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_COMMERCIAL_HUB'),
('GOLDEN_PHOENICIA_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_TO_COAST_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_ADJACENT_TO_COAST'),
('GOLDEN_PHOENICIA_DISTRICT_IS_THEATER_ADJACENT_TO_COAST_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THEATER'),
('GOLDEN_PHOENICIA_DISTRICT_IS_THEATER_ADJACENT_TO_COAST_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_ADJACENT_TO_COAST'),
('GOLDEN_PHOENICIA_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_TO_COAST_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_INDUSTRIAL_ZONE'),
('GOLDEN_PHOENICIA_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_TO_COAST_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_ADJACENT_TO_COAST'),
('GOLDEN_PHOENICIA_DISTRICT_IS_HARBOR_REQUIREMENTS',	                        'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HARBOR'),
('GOLDEN_PHOENICIA_DISTRICT_IS_CAMPUS_ADJACENT_NOT_TO_COAST_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_CAMPUS'),
('GOLDEN_PHOENICIA_DISTRICT_IS_CAMPUS_ADJACENT_NOT_TO_COAST_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_NOT_ADJACENT_TO_COAST'),
('GOLDEN_PHOENICIA_DISTRICT_IS_HOLY_SITE_ADJACENT_NOT_TO_COAST_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_HOLY_SITE'),
('GOLDEN_PHOENICIA_DISTRICT_IS_HOLY_SITE_ADJACENT_NOT_TO_COAST_REQUIREMENTS',		'GOLDEN_REQUIRES_PLOT_NOT_ADJACENT_TO_COAST'),
('GOLDEN_PHOENICIA_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_NOT_TO_COAST_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_COMMERCIAL_HUB'),
('GOLDEN_PHOENICIA_DISTRICT_IS_COMMERCIAL_HUB_ADJACENT_NOT_TO_COAST_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_NOT_ADJACENT_TO_COAST'),
('GOLDEN_PHOENICIA_DISTRICT_IS_THEATER_ADJACENT_NOT_TO_COAST_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_THEATER'),
('GOLDEN_PHOENICIA_DISTRICT_IS_THEATER_ADJACENT_NOT_TO_COAST_REQUIREMENTS',		    'GOLDEN_REQUIRES_PLOT_NOT_ADJACENT_TO_COAST'),
('GOLDEN_PHOENICIA_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_NOT_TO_COAST_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_HAS_DISTRICT_INDUSTRIAL_ZONE'),
('GOLDEN_PHOENICIA_DISTRICT_IS_INDUSTRIAL_ZONE_ADJACENT_NOT_TO_COAST_REQUIREMENTS',	'GOLDEN_REQUIRES_PLOT_NOT_ADJACENT_TO_COAST');