INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text)
VALUES
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_NAME",		"史实时代"		),
("en_US",	    "LOC_GOLDEN_TRAIT_NAME",		"Historical Era"	),

("zh_Hans_CN",	"LOC_GA_HISTORICAL_ERA_TEXT",		"[ICON_BULLET][COLOR_FLOAT_CULTURE]其中{1_Num}来自辉煌或至暗时代[ENDCOLOR]"		),
("en_US",	    "LOC_GA_HISTORICAL_ERA_TEXT",		"[ICON_BULLET][COLOR_FLOAT_CULTURE]including {1_Num} from Glorious Era or Dark Era[ENDCOLOR]"	),
--CIVILIZATION_AMERICA
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_AMERICA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：原子能时代。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_AMERICA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Atomic Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_ARABIA
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_ARABIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：中世纪。[ICON_GLORY_DARK_AGE] 至暗时代：文艺复兴时期。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_ARABIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Medieval Era. [ICON_GLORY_DARK_AGE] Dark Era: Renaissance Era."	),
--CIVILIZATION_BRAZIL
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_BRAZIL_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：电气时代。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_BRAZIL_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Modern Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_CHINA
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_CHINA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：中世纪。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_CHINA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Medieval Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_EGYPT
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_EGYPT_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：远古时代。[ICON_GLORY_DARK_AGE] 至暗时代：古典时期。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_EGYPT_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Ancient Era. [ICON_GLORY_DARK_AGE] Dark Era: Classical Era."	),
--CIVILIZATION_ENGLAND
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_ENGLAND_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：工业时代。[ICON_GLORY_DARK_AGE] 至暗时代：中世纪。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_ENGLAND_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Industrial Era. [ICON_GLORY_DARK_AGE] Dark Era: Medieval Era."	),
--CIVILIZATION_FRANCE
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_FRANCE_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：中世纪。[ICON_GLORY_DARK_AGE] 至暗时代：电气时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_FRANCE_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Medieval Era. [ICON_GLORY_DARK_AGE] Dark Era: Modern Era."	),
--CIVILIZATION_GERMANY
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_GERMANY_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：电气时代。[ICON_GLORY_DARK_AGE] 至暗时代：中世纪。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_GERMANY_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Modern Era. [ICON_GLORY_DARK_AGE] Dark Era: Medieval Era."	),
--CIVILIZATION_GREECE
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_GREECE_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：远古时代。[ICON_GLORY_DARK_AGE] 至暗时代：古典时期。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_GREECE_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Ancient Era. [ICON_GLORY_DARK_AGE] Dark Era: Classical Era."	),
--CIVILIZATION_INDIA
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_INDIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：远古时代。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_INDIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Ancient Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_JAPAN
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_JAPAN_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：电气时代。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_JAPAN_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Modern Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_KONGO
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_KONGO_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：文艺复兴时期。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_KONGO_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Renaissance Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_NORWAY
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_NORWAY_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：中世纪。[ICON_GLORY_DARK_AGE] 至暗时代：文艺复兴时期。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_NORWAY_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Medieval Era. [ICON_GLORY_DARK_AGE] Dark Era: Renaissance Era."	),
--CIVILIZATION_ROME
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_ROME_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：古典时期。[ICON_GLORY_DARK_AGE] 至暗时代：中世纪。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_ROME_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Classical Era. [ICON_GLORY_DARK_AGE] Dark Era: Medieval Era."	),
--CIVILIZATION_RUSSIA
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_RUSSIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：电气时代。[ICON_GLORY_DARK_AGE] 至暗时代：原子能时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_RUSSIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Modern Era. [ICON_GLORY_DARK_AGE] Dark Era: Atomic Era."	),
--CIVILIZATION_SCYTHIA
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_SCYTHIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：古典时期。[ICON_GLORY_DARK_AGE] 至暗时代：中世纪。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_SCYTHIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Classical Era. [ICON_GLORY_DARK_AGE] Dark Era: Medieval Era."	),
--CIVILIZATION_SPAIN
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_SPAIN_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：文艺复兴时期。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_SPAIN_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Renaissance Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_SUMERIA
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_SUMERIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：远古时代。[ICON_GLORY_DARK_AGE] 至暗时代：古典时期。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_SUMERIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Ancient Era. [ICON_GLORY_DARK_AGE] Dark Era: Classical Era."	),
--CIVILIZATION_CREE
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_CREE_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：工业时代。[ICON_GLORY_DARK_AGE] 至暗时代：电气时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_CREE_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Industrial Era. [ICON_GLORY_DARK_AGE] Dark Era: Modern Era."	),
--CIVILIZATION_KOREA
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_KOREA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：文艺复兴时期。[ICON_GLORY_DARK_AGE] 至暗时代：电气时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_KOREA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Renaissance Era. [ICON_GLORY_DARK_AGE] Dark Era: Modern Era."	),
--CIVILIZATION_GEORGIA
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_GEORGIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：中世纪。[ICON_GLORY_DARK_AGE] 至暗时代：文艺复兴时期。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_GEORGIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Medieval Era. [ICON_GLORY_DARK_AGE] Dark Era: Renaissance Era."	),
--CIVILIZATION_MAPUCHE
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_MAPUCHE_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：电气时代。[ICON_GLORY_DARK_AGE] 至暗时代：文艺复兴时期。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_MAPUCHE_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Modern Era. [ICON_GLORY_DARK_AGE] Dark Era: Renaissance Era."	),
--CIVILIZATION_MONGOLIA
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_MONGOLIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：文艺复兴时期。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_MONGOLIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Renaissance Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_NETHERLANDS
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：文艺复兴时期。[ICON_GLORY_DARK_AGE] 至暗时代：电气时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Renaissance Era. [ICON_GLORY_DARK_AGE] Dark Era: Modern Era."	),
--CIVILIZATION_SCOTLAND
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_SCOTLAND_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：工业时代。[ICON_GLORY_DARK_AGE] 至暗时代：文艺复兴时期。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_SCOTLAND_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Industrial Era. [ICON_GLORY_DARK_AGE] Dark Era: Renaissance Era."	),
--CIVILIZATION_ZULU
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_ZULU_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：文艺复兴时期。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_ZULU_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Renaissance Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_CANADA
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_CANADA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：电气时代。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_CANADA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Modern Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_HUNGARY
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_HUNGARY_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：中世纪。[ICON_GLORY_DARK_AGE] 至暗时代：电气时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_HUNGARY_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Medieval Era. [ICON_GLORY_DARK_AGE] Dark Era: Modern Era."	),
--CIVILIZATION_INCA
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_INCA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：文艺复兴时期。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_INCA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Renaissance Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_MALI
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_MALI_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：文艺复兴时期。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_MALI_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Renaissance Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_MAORI
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_MAORI_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：中世纪。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_MAORI_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Medieval Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_OTTOMAN
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_OTTOMAN_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：文艺复兴时期。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_OTTOMAN_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Renaissance Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_PHOENICIA
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_PHOENICIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：远古时代。[ICON_GLORY_DARK_AGE] 至暗时代：古典时期。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_PHOENICIA_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Ancient Era. [ICON_GLORY_DARK_AGE] Dark Era: Classical Era."	),
--CIVILIZATION_SWEDEN
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_SWEDEN_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：电气时代。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"		),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_SWEDEN_DESCRIPTION",		"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Modern Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era."	),
--CIVILIZATION_AUSTRALIA	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_AUSTRALIA_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：原子能时代。[ICON_GLORY_DARK_AGE] 至暗时代：电气时代。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_AUSTRALIA_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Atomic Era. [ICON_GLORY_DARK_AGE] Dark Era: Modern Era. "		),
--CIVILIZATION_AZTEC	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_AZTEC_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：文艺复兴时期。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_AZTEC_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Renaissance Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era. "		),	
--CIVILIZATION_NUBIA	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_NUBIA_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：远古时代。[ICON_GLORY_DARK_AGE] 至暗时代：古典时期。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_NUBIA_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Ancient Era. [ICON_GLORY_DARK_AGE] Dark Era: Classical Era. "		),		
--CIVILIZATION_POLAND	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_POLAND_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：文艺复兴时期。[ICON_GLORY_DARK_AGE] 至暗时代：电气时代。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_POLAND_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Renaissance Era. [ICON_GLORY_DARK_AGE] Dark Era: Modern Era. "		),		
--CIVILIZATION_MACEDON	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_MACEDON_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：古典时期。[ICON_GLORY_DARK_AGE] 至暗时代：中世纪。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_MACEDON_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Classical Era. [ICON_GLORY_DARK_AGE] Dark Era: Medieval Era. "		),	
--CIVILIZATION_PERSIA	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_PERSIA_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：古典时期。[ICON_GLORY_DARK_AGE] 至暗时代：中世纪。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_PERSIA_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Classical Era. [ICON_GLORY_DARK_AGE] Dark Era: Medieval Era. "		),		
--CIVILIZATION_KHMER	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_KHMER_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：中世纪。[ICON_GLORY_DARK_AGE] 至暗时代：原子能时代。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_KHMER_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Medieval Era. [ICON_GLORY_DARK_AGE] Dark Era: Atomic Era. "		),	
--CIVILIZATION_INDONESIA	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_INDONESIA_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：文艺复兴时期。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_INDONESIA_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Renaissance Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era. "		),
--CIVILIZATION_GRAN_COLOMBIA	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_GRAN_COLOMBIA_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：工业时代。[ICON_GLORY_DARK_AGE] 至暗时代：文艺复兴时期。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_GRAN_COLOMBIA_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Industrial Era. [ICON_GLORY_DARK_AGE] Dark Era: Renaissance Era. "		),
--CIVILIZATION_MAYA	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_MAYA_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：古典时期。[ICON_GLORY_DARK_AGE] 至暗时代：文艺复兴时期。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_MAYA_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Classical Era. [ICON_GLORY_DARK_AGE] Dark Era: Renaissance Era. "		),
--CIVILIZATION_ETHIOPIA	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_ETHIOPIA_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：工业时代。[ICON_GLORY_DARK_AGE] 至暗时代：原子能时代。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_ETHIOPIA_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Industrial Era. [ICON_GLORY_DARK_AGE] Dark Era: Atomic Era. "		),
--CIVILIZATION_BYZANTIUM	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_BYZANTIUM_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：中世纪。[ICON_GLORY_DARK_AGE] 至暗时代：文艺复兴时期。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_BYZANTIUM_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Medieval Era. [ICON_GLORY_DARK_AGE] Dark Era: Renaissance Era. "		),
--CIVILIZATION_GAUL	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_GAUL_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：古典时期。[ICON_GLORY_DARK_AGE] 至暗时代：中世纪。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_GAUL_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Classical Era. [ICON_GLORY_DARK_AGE] Dark Era: Medieval Era. "		),
--CIVILIZATION_BABYLON_STK	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_BABYLON_STK_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：远古时代。[ICON_GLORY_DARK_AGE] 至暗时代：古典时期。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_BABYLON_STK_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Ancient Era. [ICON_GLORY_DARK_AGE] Dark Era: Classical Era. "		),
--CIVILIZATION_VIETNAM	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_VIETNAM_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：中世纪。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_VIETNAM_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Medieval Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era. "		),
--CIVILIZATION_PORTUGAL	
("zh_Hans_CN",	"LOC_GOLDEN_TRAIT_CIVILIZATION_PORTUGAL_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] 辉煌时代：文艺复兴时期。[ICON_GLORY_DARK_AGE] 至暗时代：工业时代。"),
("en_US",	    "LOC_GOLDEN_TRAIT_CIVILIZATION_PORTUGAL_DESCRIPTION",			"[ICON_GLORY_GOLDEN_AGE] Glorious Era: Renaissance Era. [ICON_GLORY_DARK_AGE] Dark Era: Industrial Era. "		);	













































