-- GoldenAge_Icons_Building_Expansion
-- Author: Flactine
-- DateCreated: 9/17/2022 3:35:43 PM
--------------------------------------------------------------
--=====
--IconTextureAtlases
--=====
INSERT INTO IconTextureAtlases 
(Name,									IconSize,	IconsPerRow,	IconsPerColumn, Filename)
VALUES
('ICON_ATLAS_BUILDINGS_NORMAL',			32,			8,				11,				'BuildingsExpansion_Normal_32'),
('ICON_ATLAS_BUILDINGS_NORMAL',			38,			8,				11,				'BuildingsExpansion_Normal_38'),
('ICON_ATLAS_BUILDINGS_NORMAL',			50,			8,				11,				'BuildingsExpansion_Normal_50'),
('ICON_ATLAS_BUILDINGS_NORMAL',			80,			8,				11,				'BuildingsExpansion_Normal_80'),
('ICON_ATLAS_BUILDINGS_NORMAL',			12,			8,				11,				'BuildingsExpansion_Normal_128'),
('ICON_ATLAS_BUILDINGS_NORMAL',			256,		8,				11,				'BuildingsExpansion_Normal_256'),
('ICON_ATLAS_BUILDINGS_NORMAL_FOW',		256,		8,				11,				'BuildingsExpansion_Normal_256'),

('ICON_ATLAS_BUILDINGS_GRAY',			32,			8,				11,				'BuildingsExpansion_Gray_32'),
('ICON_ATLAS_BUILDINGS_GRAY',			38,			8,				11,				'BuildingsExpansion_Gray_38'),
('ICON_ATLAS_BUILDINGS_GRAY',			50,			8,				11,				'BuildingsExpansion_Gray_50'),
('ICON_ATLAS_BUILDINGS_GRAY',			80,			8,				11,				'BuildingsExpansion_Gray_80'),
('ICON_ATLAS_BUILDINGS_GRAY',			12,			8,				11,				'BuildingsExpansion_Gray_128'),
('ICON_ATLAS_BUILDINGS_GRAY',			256,		8,				11,				'BuildingsExpansion_Gray_256'),
('ICON_ATLAS_BUILDINGS_GRAY_FOW',		256,		8,				11,				'BuildingsExpansion_Gray_256'),

('ICON_ATLAS_BUILDINGS_BLUE',			32,			8,				11,				'BuildingsExpansion_Blue_32'),
('ICON_ATLAS_BUILDINGS_BLUE',			38,			8,				11,				'BuildingsExpansion_Blue_38'),
('ICON_ATLAS_BUILDINGS_BLUE',			50,			8,				11,				'BuildingsExpansion_Blue_50'),
('ICON_ATLAS_BUILDINGS_BLUE',			80,			8,				11,				'BuildingsExpansion_Blue_80'),
('ICON_ATLAS_BUILDINGS_BLUE',			12,			8,				11,				'BuildingsExpansion_Blue_128'),
('ICON_ATLAS_BUILDINGS_BLUE',			256,		8,				11,				'BuildingsExpansion_Blue_256'),
('ICON_ATLAS_BUILDINGS_BLUE_FOW',		256,		8,				11,				'BuildingsExpansion_Blue_256'),

('ICON_ATLAS_BUILDINGS_CYAN',			32,			8,				11,				'BuildingsExpansion_Cyan_32'),
('ICON_ATLAS_BUILDINGS_CYAN',			38,			8,				11,				'BuildingsExpansion_Cyan_38'),
('ICON_ATLAS_BUILDINGS_CYAN',			50,			8,				11,				'BuildingsExpansion_Cyan_50'),
('ICON_ATLAS_BUILDINGS_CYAN',			80,			8,				11,				'BuildingsExpansion_Cyan_80'),
('ICON_ATLAS_BUILDINGS_CYAN',			12,			8,				11,				'BuildingsExpansion_Cyan_128'),
('ICON_ATLAS_BUILDINGS_CYAN',			256,		8,				11,				'BuildingsExpansion_Cyan_256'),
('ICON_ATLAS_BUILDINGS_CYAN_FOW',		256,		8,				11,				'BuildingsExpansion_Cyan_256'),

('ICON_ATLAS_BUILDINGS_PINK',			32,			8,				11,				'BuildingsExpansion_Pink_32'),
('ICON_ATLAS_BUILDINGS_PINK',			38,			8,				11,				'BuildingsExpansion_Pink_38'),
('ICON_ATLAS_BUILDINGS_PINK',			50,			8,				11,				'BuildingsExpansion_Pink_50'),
('ICON_ATLAS_BUILDINGS_PINK',			80,			8,				11,				'BuildingsExpansion_Pink_80'),
('ICON_ATLAS_BUILDINGS_PINK',			12,			8,				11,				'BuildingsExpansion_Pink_128'),
('ICON_ATLAS_BUILDINGS_PINK',			256,		8,				11,				'BuildingsExpansion_Pink_256'),
('ICON_ATLAS_BUILDINGS_PINK_FOW',		256,		8,				11,				'BuildingsExpansion_Pink_256'),

('ICON_ATLAS_BUILDINGS_RED',			32,			8,				11,				'BuildingsExpansion_Red_32'),
('ICON_ATLAS_BUILDINGS_RED',			38,			8,				11,				'BuildingsExpansion_Red_38'),
('ICON_ATLAS_BUILDINGS_RED',			50,			8,				11,				'BuildingsExpansion_Red_50'),
('ICON_ATLAS_BUILDINGS_RED',			80,			8,				11,				'BuildingsExpansion_Red_80'),
('ICON_ATLAS_BUILDINGS_RED',			12,			8,				11,				'BuildingsExpansion_Red_128'),
('ICON_ATLAS_BUILDINGS_RED',			256,		8,				11,				'BuildingsExpansion_Red_256'),
('ICON_ATLAS_BUILDINGS_RED_FOW',		256,		8,				11,				'BuildingsExpansion_Red_256'),

('ICON_ATLAS_BUILDINGS_GREEN',			32,			8,				11,				'BuildingsExpansion_Green_32'),
('ICON_ATLAS_BUILDINGS_GREEN',			38,			8,				11,				'BuildingsExpansion_Green_38'),
('ICON_ATLAS_BUILDINGS_GREEN',			50,			8,				11,				'BuildingsExpansion_Green_50'),
('ICON_ATLAS_BUILDINGS_GREEN',			80,			8,				11,				'BuildingsExpansion_Green_80'),
('ICON_ATLAS_BUILDINGS_GREEN',			12,			8,				11,				'BuildingsExpansion_Green_128'),
('ICON_ATLAS_BUILDINGS_GREEN',			256,		8,				11,				'BuildingsExpansion_Green_256'),
('ICON_ATLAS_BUILDINGS_GREEN_FOW',		256,		8,				11,				'BuildingsExpansion_Green_256'),

('ICON_ATLAS_BUILDINGS_YELLOW',			32,			8,				11,				'BuildingsExpansion_Yellow_32'),
('ICON_ATLAS_BUILDINGS_YELLOW',			38,			8,				11,				'BuildingsExpansion_Yellow_38'),
('ICON_ATLAS_BUILDINGS_YELLOW',			50,			8,				11,				'BuildingsExpansion_Yellow_50'),
('ICON_ATLAS_BUILDINGS_YELLOW',			80,			8,				11,				'BuildingsExpansion_Yellow_80'),
('ICON_ATLAS_BUILDINGS_YELLOW',			12,			8,				11,				'BuildingsExpansion_Yellow_128'),
('ICON_ATLAS_BUILDINGS_YELLOW',			256,		8,				11,				'BuildingsExpansion_Yellow_256'),
('ICON_ATLAS_BUILDINGS_YELLOW_FOW',		256,		8,				11,				'BuildingsExpansion_Yellow_256');
--=====
--IconTextureAtlases
--=====
INSERT INTO IconDefinitions
(Name,										Atlas,								'Index')
VALUES
('ICON_BUILDING_STONEMASON',             	'ICON_ATLAS_BUILDINGS_GRAY',		20),
('ICON_BUILDING_STONEMASON_FOW',			'ICON_ATLAS_BUILDINGS_GRAY_FOW',	20),
('ICON_BUILDING_SMELTERY',             	 	'ICON_ATLAS_BUILDINGS_RED',			20),
('ICON_BUILDING_SMELTERY_FOW',             	'ICON_ATLAS_BUILDINGS_RED_FOW',		20),

('ICON_BUILDING_RAWMATERIAL',             	'ICON_ATLAS_BUILDINGS_GRAY',		26),
('ICON_BUILDING_RAWMATERIAL_FOW',			'ICON_ATLAS_BUILDINGS_GRAY_FOW',	26),
('ICON_BUILDING_FABRICATION',             	'ICON_ATLAS_BUILDINGS_RED',			26),
('ICON_BUILDING_FABRICATION_FOW',			'ICON_ATLAS_BUILDINGS_RED_FOW',		26),

('ICON_BUILDING_ASSEMBLYLINE',             	'ICON_ATLAS_BUILDINGS_RED',			27),
('ICON_BUILDING_ASSEMBLYLINE',             	'ICON_ATLAS_BUILDINGS_RED_FOW',		27),
('ICON_BUILDING_AUTOMATED',             	'ICON_ATLAS_BUILDINGS_BLUE',		27),
('ICON_BUILDING_AUTOMATED',             	'ICON_ATLAS_BUILDINGS_BLUE_FOW',	27),
  
('ICON_BUILDING_ALCHEMY_HOUSE',				'ICON_ATLAS_BUILDINGS_GREEN',		4),
('ICON_BUILDING_ALCHEMY_HOUSE_FOW',			'ICON_ATLAS_BUILDINGS_GREEN_FOW',	4),
('ICON_BUILDING_OBSERVATORY',               'ICON_ATLAS_BUILDINGS_BLUE',		4),
('ICON_BUILDING_OBSERVATORY_FOW',			'ICON_ATLAS_BUILDINGS_BLUE_FOW',	4),

('ICON_BUILDING_PUBLIC_SCHOOL',             'ICON_ATLAS_BUILDINGS_RED',			18),
('ICON_BUILDING_PUBLIC_SCHOOL_FOW',			'ICON_ATLAS_BUILDINGS_RED_FOW',		18),
('ICON_BUILDING_ACADEMIC_EXCHANGE',         'ICON_ATLAS_BUILDINGS_BLUE',		18),
('ICON_BUILDING_ACADEMIC_EXCHANGE_FOW',		'ICON_ATLAS_BUILDINGS_BLUE_FOW',	18),

('ICON_BUILDING_BIOLOGY_LAB',               'ICON_ATLAS_BUILDINGS_GREEN',		37),
('ICON_BUILDING_BIOLOGY_LAB_FOW',			'ICON_ATLAS_BUILDINGS_GREEN_FOW',	37),
('ICON_BUILDING_ANIMAL_LAB',               	'ICON_ATLAS_BUILDINGS_PINK',		37),
('ICON_BUILDING_ANIMAL_LAB_FOW',			'ICON_ATLAS_BUILDINGS_PINK_FOW',	37),
('ICON_BUILDING_CHEMISTRY_LAB',             'ICON_ATLAS_BUILDINGS_GRAY',		37),
('ICON_BUILDING_CHEMISTRY_LAB_FOW',			'ICON_ATLAS_BUILDINGS_GRAY_FOW',	37),

('ICON_BUILDING_GIANT_TELESCOPE',           'ICON_ATLAS_BUILDINGS_BLUE',		72),
('ICON_BUILDING_GIANT_TELESCOPE_FOW',       'ICON_ATLAS_BUILDINGS_BLUE_FOW',	72),  
('ICON_BUILDING_HADRON_COLLIDER',           'ICON_ATLAS_BUILDINGS_RED',			72),
('ICON_BUILDING_HADRON_COLLIDER_FOW',       'ICON_ATLAS_BUILDINGS_RED_FOW',		72),  
('ICON_BUILDING_SUPER_COMPUTER',           	'ICON_ATLAS_BUILDINGS_CYAN',		72),
('ICON_BUILDING_SUPER_COMPUTER_FOW',       	'ICON_ATLAS_BUILDINGS_CYAN_FOW',	72),

('ICON_BUILDING_MINT',                		'ICON_ATLAS_BUILDINGS_BLUE',		11),
('ICON_BUILDING_MINT_FOW',                	'ICON_ATLAS_BUILDINGS_BLUE_FOW',	11),
('ICON_BUILDING_POST_STATION',              'ICON_ATLAS_BUILDINGS_RED',			11),
('ICON_BUILDING_POST_STATION_FOW',			'ICON_ATLAS_BUILDINGS_RED_FOW',		11),

('ICON_BUILDING_TAX_BUREAU',                'ICON_ATLAS_BUILDINGS_RED',			23),
('ICON_BUILDING_TAX_BUREAU_FOW',			'ICON_ATLAS_BUILDINGS_RED_FOW',		23),
('ICON_BUILDING_COMMERCIAL',                'ICON_ATLAS_BUILDINGS_YELLOW',		23),
('ICON_BUILDING_COMMERCIAL_FOW',			'ICON_ATLAS_BUILDINGS_YELLOW_FOW',	23),

('ICON_BUILDING_URBAN_CONSTRUCTION',        'ICON_ATLAS_BUILDINGS_GRAY',		28),
('ICON_BUILDING_URBAN_CONSTRUCTION_FOW',	'ICON_ATLAS_BUILDINGS_GRAY_FOW',	28),
('ICON_BUILDING_MILITARY_CORP',             'ICON_ATLAS_BUILDINGS_RED',			28),
('ICON_BUILDING_MILITARY_CORP_FOW',			'ICON_ATLAS_BUILDINGS_RED_FOW',		28),

('ICON_BUILDING_LUXURY_GOODS',              'ICON_ATLAS_BUILDINGS_RED',			64),
('ICON_BUILDING_LUXURY_GOODS_FOW',			'ICON_ATLAS_BUILDINGS_RED_FOW',		64),
('ICON_BUILDING_DIGITAL_CURRENCY',          'ICON_ATLAS_BUILDINGS_CYAN',		64),
('ICON_BUILDING_DIGITAL_CURRENCY_FOW',		'ICON_ATLAS_BUILDINGS_CYAN_FOW',	64),
('ICON_BUILDING_FINANCIAL_TOWER',           'ICON_ATLAS_BUILDINGS_YELLOW',		64),
('ICON_BUILDING_FINANCIAL_TOWER_FOW',		'ICON_ATLAS_BUILDINGS_YELLOW_FOW',	64),
('ICON_BUILDING_MINING_GROUP',              'ICON_ATLAS_BUILDINGS_GRAY',		64),
('ICON_BUILDING_MINING_GROUP_FOW',			'ICON_ATLAS_BUILDINGS_GRAY_FOW',	64),

('ICON_BUILDING_EPIC_THEATRE',				'ICON_ATLAS_BUILDINGS_RED',			16),
('ICON_BUILDING_EPIC_THEATRE_FOW',			'ICON_ATLAS_BUILDINGS_RED_FOW',		16),
('ICON_BUILDING_TAMPLE_STAGE',				'ICON_ATLAS_BUILDINGS_BLUE',		16),
('ICON_BUILDING_TAMPLE_STAGE_FOW',			'ICON_ATLAS_BUILDINGS_BLUE_FOW',	16),
	
('ICON_BUILDING_THERTERMUSEUM',				'ICON_ATLAS_BUILDINGS_PINK',		25),
('ICON_BUILDING_THERTERMUSEUM_FOW',			'ICON_ATLAS_BUILDINGS_PINK_FOW',	25),
('ICON_BUILDING_LIBRARYMUSEUM',				'ICON_ATLAS_BUILDINGS_YELLOW',		25),
('ICON_BUILDING_LIBRARYMUSEUM_FOW',			'ICON_ATLAS_BUILDINGS_YELLOW_FOW',	25),

('ICON_BUILDING_OPERA_HOUSE',				'ICON_ATLAS_BUILDINGS_RED',			35),
('ICON_BUILDING_OPERA_HOUSE_FOW',			'ICON_ATLAS_BUILDINGS_RED_FOW',		35),
('ICON_BUILDING_ART_ASSOCIATION',			'ICON_ATLAS_BUILDINGS_PINK',		35),
('ICON_BUILDING_ART_ASSOCIATION_FOW',		'ICON_ATLAS_BUILDINGS_PINK_FOW',	35),
('ICON_BUILDING_PHOTOSTUDIO',				'ICON_ATLAS_BUILDINGS_GREEN',		36),
('ICON_BUILDING_PHOTOSTUDIO_FOW',			'ICON_ATLAS_BUILDINGS_GREEN_FOW',	36),

('ICON_BUILDING_CINEMA',				'ICON_ATLAS_BUILDINGS_RED',				66),
('ICON_BUILDING_CINEMA_FOW',			'ICON_ATLAS_BUILDINGS_RED_FOW',			66),
('ICON_BUILDING_CONCERT_HALL',			'ICON_ATLAS_BUILDINGS_BLUE',			66),
('ICON_BUILDING_CONCERT_HALL_FOW',		'ICON_ATLAS_BUILDINGS_BLUE_FOW',		66),
('ICON_BUILDING_WE_MEDIA',				'ICON_ATLAS_BUILDINGS_CYAN',			66),
('ICON_BUILDING_WE_MEDIA_FOW',			'ICON_ATLAS_BUILDINGS_CYAN_FOW',		66),

('ICON_BUILDING_CHESS_ROOM',		'ICON_ATLAS_BUILDINGS_RED',			8),
('ICON_BUILDING_CHESS_ROOM_FOW',	'ICON_ATLAS_BUILDINGS_RED_FOW',		8),
('ICON_BUILDING_TEAHOUSE',			'ICON_ATLAS_BUILDINGS_GREEN',		8),
('ICON_BUILDING_TEAHOUSE_FOW',		'ICON_ATLAS_BUILDINGS_GREEN_FOW',	8),

('ICON_BUILDING_ARBORETUM',			'ICON_ATLAS_BUILDINGS_GREEN',		31),
('ICON_BUILDING_ARBORETUM_FOW',		'ICON_ATLAS_BUILDINGS_GREEN_FOW',	31),

('ICON_BUILDING_GA_POLICEST',		'ICON_ATLAS_BUILDINGS_BLUE',		58),
('ICON_BUILDING_GA_POLICEST_FOW',	'ICON_ATLAS_BUILDINGS_BLUE_FOW',	58),
('ICON_BUILDING_GA_FIREST',			'ICON_ATLAS_BUILDINGS_RED',			59),
('ICON_BUILDING_GA_FIREST_FOW',		'ICON_ATLAS_BUILDINGS_RED_FOW',		59),
('ICON_BUILDING_GA_CLINIC',			'ICON_ATLAS_BUILDINGS_GREEN',		64),
('ICON_BUILDING_GA_CLINIC_FOW',		'ICON_ATLAS_BUILDINGS_GREEN_FOW',	64),

('ICON_BUILDING_GA_RESERVOIR',			'ICON_ATLAS_BUILDINGS_CYAN',		48),
('ICON_BUILDING_GA_RESERVOIR_FOW',		'ICON_ATLAS_BUILDINGS_CYAN_FOW',	48),
('ICON_BUILDING_GA_IRRIGATION_HUB',		'ICON_ATLAS_BUILDINGS_GREEN',		48),
('ICON_BUILDING_GA_IRRIGATION_HUB_FOW',	'ICON_ATLAS_BUILDINGS_GREEN_FOW',	48),
('ICON_BUILDING_GA_WATERWORKS',			'ICON_ATLAS_BUILDINGS_RED',			48),
('ICON_BUILDING_GA_WATERWORKS_FOW',		'ICON_ATLAS_BUILDINGS_RED_FOW',		48),

('ICON_BUILDING_GA_FOREST_RESERVE',				'ICON_ATLAS_BUILDINGS_GREEN',		72),
('ICON_BUILDING_GA_FOREST_RESERVE_FOW',			'ICON_ATLAS_BUILDINGS_GREEN_FOW',	72),
('ICON_BUILDING_GA_FLOODPLAINS_RESERVE',		'ICON_ATLAS_BUILDINGS_GRAY',		72),
('ICON_BUILDING_GA_FLOODPLAINS_RESERVE_FOW',	'ICON_ATLAS_BUILDINGS_GRAY_FOW',	72),
('ICON_BUILDING_GA_WONDER_RESERVE',				'ICON_ATLAS_BUILDINGS_YELLOW',		72),
('ICON_BUILDING_GA_WONDER_RESERVE_FOW',			'ICON_ATLAS_BUILDINGS_YELLOW_FOW',	72),

('ICON_BUILDING_GA_ROLLER_COASTER',			'ICON_ATLAS_BUILDINGS_CYAN',		75),
('ICON_BUILDING_GA_ROLLER_COASTER_FOW',		'ICON_ATLAS_BUILDINGS_CYAN_FOW',	75),
('ICON_BUILDING_GA_CAROUSEL',				'ICON_ATLAS_BUILDINGS_PINK',		75),
('ICON_BUILDING_GA_CAROUSEL_FOW',			'ICON_ATLAS_BUILDINGS_PINK_FOW',	75),
('ICON_BUILDING_GA_POLARIA',				'ICON_ATLAS_BUILDINGS_BLUE',		73),
('ICON_BUILDING_GA_POLARIA_FOW',			'ICON_ATLAS_BUILDINGS_BLUE_FOW',	73);