UPDATE Units SET Cost = 50, PrereqCivic = 'CIVIC_GAMES_RECREATION', BaseMoves = 2
WHERE UnitType = 'UNIT_IMMIGRATION_ONE' AND EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_IMMIGRATION_ONE');
UPDATE Units SET Cost = 100, PrereqCivic = 'CIVIC_HUMANISM', BaseMoves = 2
WHERE UnitType = 'UNIT_IMMIGRATION_TWO' AND EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_IMMIGRATION_ONE');
UPDATE Units SET Cost = 150, PrereqCivic = 'CIVIC_IDEOLOGY', BaseMoves = 2
WHERE UnitType = 'UNIT_IMMIGRATION_THREE' AND EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_IMMIGRATION_ONE');
UPDATE Units SET Cost = 200, PrereqCivic = 'CIVIC_GLOBALIZATION', BaseMoves = 2
WHERE UnitType = 'UNIT_IMMIGRATION_FOUR' AND EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_IMMIGRATION_ONE');
DELETE FROM Types WHERE Type = 'UNIT_IMMIGRATION_FIVE' AND EXISTS (SELECT UnitType FROM Units WHERE UnitType='UNIT_IMMIGRATION_ONE');