--订阅则移除
DELETE FROM Types WHERE Type = 'PROJECT_SATELLITE_ESPIONAGE' AND EXISTS (SELECT ProjectType FROM Projects WHERE ProjectType='PROJECT_JNR_SATELLITE_ESPIONAGE');
DELETE FROM Types WHERE Type = 'PROJECT_SATELLITE_MILITARY' AND EXISTS (SELECT ProjectType FROM Projects WHERE ProjectType='PROJECT_JNR_SATELLITE_ESPIONAGE');
DELETE FROM Types WHERE Type = 'PROJECT_SATELLITE_NAVIGATION' AND EXISTS (SELECT ProjectType FROM Projects WHERE ProjectType='PROJECT_JNR_SATELLITE_ESPIONAGE');
-- DELETE FROM Types WHERE Type = 'PROJECT_SATELLITE_WEATHER' AND EXISTS (SELECT ProjectType FROM Projects WHERE ProjectType='PROJECT_JNR_SATELLITE_ESPIONAGE');
DELETE FROM Types WHERE Type = 'PROJECT_SATELLITE_BROADCAST' AND EXISTS (SELECT ProjectType FROM Projects WHERE ProjectType='PROJECT_JNR_SATELLITE_ESPIONAGE');
DELETE FROM Types WHERE Type = 'PROJECT_SATELLITE_COMMUNICATION' AND EXISTS (SELECT ProjectType FROM Projects WHERE ProjectType='PROJECT_JNR_SATELLITE_ESPIONAGE');
DELETE FROM Types WHERE Type = 'PROJECT_SATELLITE_SOLAR_POWER' AND EXISTS (SELECT ProjectType FROM Projects WHERE ProjectType='PROJECT_JNR_SATELLITE_ESPIONAGE');