--BUILDING_ITSUKUSHIMA
UPDATE Buildings SET  Cost = 500, ObsoleteEra = 'ERA_RENAISSANCE'
WHERE BuildingType = 'BUILDING_ITSUKUSHIMA' AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType='BUILDING_ITSUKUSHIMA');

--BUILDING_BAMYAN
UPDATE Buildings SET  Cost = 500, ObsoleteEra = 'ERA_RENAISSANCE'
WHERE BuildingType = 'BUILDING_BAMYAN' AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType='BUILDING_BAMYAN');

--BUILDING_YELLOW_CRANE
UPDATE Buildings SET  Cost = 500, ObsoleteEra = 'ERA_RENAISSANCE'
WHERE BuildingType = 'BUILDING_YELLOW_CRANE' AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType='BUILDING_YELLOW_CRANE');

--BUILDING_LEANING_TOWER
UPDATE Buildings SET  Cost = 1500, ObsoleteEra = 'ERA_MODERN'
WHERE BuildingType = 'BUILDING_LEANING_TOWER' AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType='BUILDING_LEANING_TOWER');

--BUILDING_GLOBE_THEATRE
UPDATE Buildings SET  Cost = 1500, ObsoleteEra = 'ERA_MODERN'
WHERE BuildingType = 'BUILDING_GLOBE_THEATRE' AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType='BUILDING_GLOBE_THEATRE');

--BUILDING_PORCELAIN_TOWER
UPDATE Buildings SET  Cost = 1500, ObsoleteEra = 'ERA_MODERN'
WHERE BuildingType = 'BUILDING_PORCELAIN_TOWER' AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType='BUILDING_PORCELAIN_TOWER');

--BUILDING_UFFIZI
UPDATE Buildings SET  Cost = 1500, ObsoleteEra = 'ERA_MODERN'
WHERE BuildingType = 'BUILDING_UFFIZI' AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType='BUILDING_UFFIZI');

--BUILDING_BRANDENBURG_GATE
UPDATE Buildings SET  Cost = 2000, ObsoleteEra = 'ERA_ATOMIC'
WHERE BuildingType = 'BUILDING_BRANDENBURG_GATE' AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType='BUILDING_BRANDENBURG_GATE');

--BUILDING_BURJ_KHALIFA
UPDATE Buildings SET  Cost = 2000
WHERE BuildingType = 'BUILDING_BURJ_KHALIFA' AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType='BUILDING_BURJ_KHALIFA');

--BUILDING_ABU_SIMBEL
UPDATE Buildings SET  Cost = 250, ObsoleteEra = 'ERA_MEDIEVAL'
WHERE BuildingType = 'BUILDING_ABU_SIMBEL' AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType='BUILDING_ABU_SIMBEL');

--BUILDING_BOROBUDUR
UPDATE Buildings SET  Cost = 1000, ObsoleteEra = 'ERA_INDUSTRIAL'
WHERE BuildingType = 'BUILDING_BOROBUDUR' AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType='BUILDING_BOROBUDUR');

--BUILDING_NOTRE_DAME
UPDATE Buildings SET  Cost = 1500, ObsoleteEra = 'ERA_MODERN', PrereqCivic = 'CIVIC_HUMANISM'
WHERE BuildingType = 'BUILDING_NOTRE_DAME' AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType='BUILDING_NOTRE_DAME');

--BUILDING_NEUSCHWANSTEIN
UPDATE Buildings SET  Cost = 2000, ObsoleteEra = 'ERA_ATOMIC'
WHERE BuildingType = 'BUILDING_NEUSCHWANSTEIN' AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType='BUILDING_NEUSCHWANSTEIN');

--BUILDING_TOWER_BRIDGE
UPDATE Buildings SET  Cost = 2500, ObsoleteEra = 'ERA_INFORMATION'
WHERE BuildingType = 'BUILDING_TOWER_BRIDGE' AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType='BUILDING_TOWER_BRIDGE');